### ISSUE TITLE
Orchestrator functions cannot be directly run in the portal

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#10]
### Repro steps
1. Follow the setup instructions [here](https://azure.github.io/azure-functions-durable-extension/articles/installation.html) for portal development.
2. Create a simple orchestrator function in the portal
3. Click the Run button

### Result
The function fails to run with the following error:

```
2017-07-12T18:58:11.669 Exception while executing function: Functions.DurableTimer. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'context'. Microsoft.Azure.WebJobs.Extensions.DurableTask: Cannot convert Test Value to DurableOrchestrationContext.
```

### Issue
This is because the orchestration trigger is not designed to be invoked manually. The problem is that the portal sends the trigger input as string data, but the binding code does not know how to convert this string into a properly `DurableOrchestrationContext` object.

### Expectation
It may not ever be possible to invoke orchestrator functions from the portal directly since orchestrator functions must be driven by the DTFx control queue. At the bare minimum, we should try to detect this case and return a friendly error message. Even better would be to allow binding extensions to disable the **Run** button in the portal with a tooltip explaining why it's disabled.

### Workaround
Create another function with a manual trigger type which binds to an `orchestrationClient`. Trigger that manually and have it start the orchestrator function. Here is an example:

#### Code
```csharp
#r "Microsoft.Azure.WebJobs.Extensions.DurableTask"

using System;

public static async Task Run(string functionName, DurableOrchestrationClient starter, TraceWriter log)
{
    log.Info($"Starting orchestration named: {functionName}");
    string instanceId = await starter.StartNewAsync(functionName, null);
    log.Info($"Started orchestration with ID = '{instanceId}'.");   
}
```

#### function.json
```json
{
  "bindings": [
    {
      "type": "manualTrigger",
      "direction": "in",
      "name": "functionName"
    },
    {
      "name": "starter",
      "type": "orchestrationClient",
      "direction": "in"
    }
  ],
  "disabled": false
}
```

**Comment by SeanFeldman** [comment]
With this workaround durable function does start, but throws the following exception: 
```

context | Microsoft.Azure.WebJobs.DurableOrchestrationContext
log | Cannot access a disposed object.
 Object name: 'LoggerFactory'.
_context | 15efcc18-2d71-4191-a01f-dda100f8638d
Failure | Exception binding parameter 'log'

Exception while executing function: Functions.DurableTimer
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.DurableTimer ---> System.InvalidOperationException : Exception binding parameter 'log' ---> System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'LoggerFactory'.
   at Microsoft.Extensions.Logging.LoggerFactory.CreateLogger(String categoryName)
   at Microsoft.Azure.WebJobs.Host.Bindings.TraceWriterBinding.BindAsync(BindingContext context)
   at async Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync[TTriggerValue](ValueBindingContext context,Object value,IDictionary`2 parameters) 
   End of inner exception
   at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstance instance,IReadOnlyDictionary`2 parameters,TraceWriter traceWriter,ILogger logger,CancellationTokenSource functionCancellationTokenSource)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??)
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) 
   End of inner exception
```

**Comment by cgillum** [comment]
I'll take a look at that as well. It's surprising that I've not run into this with any of my published samples. From the callstack, it seems you might be able to work around it by removing the `log` parameter, but I'll investigate further and may open a separate issue to track.

**Comment by SeanFeldman** [comment]
@cgillum users are the best testers 😉
I wanted to have the logs to verify execution works as expected.

**Comment by SeanFeldman** [comment]
Removing `log` parameter doesn't help as it still fails.

**Comment by cgillum** [comment]
Yeah, I noticed the same thing. I'm following up with the core Functions team to figure this out.  I'm told that this can happen if the functions host recycles while functions are still running, but that's not happening as far as I can tell so more investigation is needed.

**Comment by SeanFeldman** [comment]
@cgillum any updates?

**Comment by cgillum** [comment]
Not yet. Unfortunately I cannot reproduce it when running the functions script host locally, so it's going to take a bit more effort to chase this down.

As a workaround, are you able to use the VS Tools instead of developing directly in the portal?

**Comment by cgillum** [comment]
@SeanFeldman Looks like there is a known issue in Functions which may be responsible for this, likely caused by a recent runtime update: https://github.com/Azure/azure-webjobs-sdk-script/issues/1690#issuecomment-316801577

There are a couple things you can try:
1. Kill w3wp.exe using Kudu and then try your scenario again. The restarts caused by code changes, config changes, etc. are putting the functions host in a bad state.
2. Enable [Application Insights](https://github.com/Azure/Azure-Functions/wiki/App-Insights-(Preview)). I tried this on a whim and I was able to get the manual trigger to work. Not sure if this was a coincidence or not.

**Comment by SeanFeldman** [comment]
Kudu on a consuption plan @cgillum? 🙂
I'll need to try AI to see if that would resolve it. For VS, it requires VS preview which I currently don't have.
Functions are very much bleeding edge ATM 😉

**Comment by cgillum** [comment]
Yep, Kudu works great on consumption plan. :)

**Comment by SeanFeldman** [comment]
What happened to the true #serverless? I'm digressing, sowwy 🙂

**Comment by SeanFeldman** [comment]
Killing w3wp process didn't help @cgillum 
I'll try #2 (AI), though it's very weird to force AI to fix the issue. Something is off.

**Comment by SeanFeldman** [comment]
No luck with AI either 😞

**Comment by fabiocav** [comment]
Sorry for the inconvenience. You can try setting the 'FUNCTIONS_EXTENSION_VERSION' app setting to 1.0.11015 to see if the helps. We'll have that fixed ASAP!

**Comment by fabiocav** [comment]
Might be an issue if the DF bits you're using rely on some of the new functionality deployed, but I don't think that's the case.

**Comment by SeanFeldman** [comment]
> Might be an issue if the DF bits you're using rely on some of the new functionality deployed, but I don't think that's the case.

Surprise, surprise 🙂 The function is no longer failing.

**Comment by fabiocav** [comment]
Glad to hear. The issue referenced here will be updated when this is patched up. We'll update this issue as well. Once the fix is deployed, you can remove the workaround.

You can watch this to be notified of new releases: https://github.com/Azure/app-service-announcements

**Comment by SeanFeldman** [comment]
@fabiocav to note, I had to restart Functions app when tried to disable AI. Otherwise was getting log exception.

**Comment by cgillum** [comment]
While there was a very similar issue in Azure Functions, more investigation revealed that this extension was not properly managing function invokers, resulting in us using stale objects whenever a host recycle happened. This should be fixed in the latest release.
