### ISSUE TITLE
Hacking the durable-extension when deploying at localhost

### ISSUE THREAD

**Issue by hazelnutsgz** [Azure/azure-functions-durable-extension#1001]
## Background
I was playing with durable function on Windows10 PC with visual studio 2019 installed recently,  following the [tutorial](  https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-functions/durable/durable-functions-create-first-csharp.md), and got things done at localhost.

## What I wanted?
Recently, I am studying the source code of `durable function`, basically including these repos:
- https://github.com/Azure/azure-functions-durable-extension
- https://github.com/Azure/durabletask/
- https://github.com/Azure/azure-functions-host

So I learned the code by hacking it at localhost. My question here is 
1. How to enable my modification of the source code(C#) in three repos? (I even want to set the breakpoint to understand the code if I could !!!!!)
2. Is there any documentation concerning the design & imple of the durable function to help the beginner to understand it?

**Comment by ConnorMcMahon** [comment]
**https://github.com/Azure/azure-functions-durable-extension**

This repo essentially has two responsibilities:

1. Making sure that DurableTask integrates cleanly with Azure Functions.
2. Adds some features on top of Durable Task that we think would be useful to customers, like entities, notifications, HTTP handling, etc.

Consider checking out our [contribution guide](https://github.com/Azure/azure-functions-durable-extension/blob/dev/CONTRIBUTING.md). This should cover the dev experience for change exclusively to this repository.

**https://github.com/Azure/durabletask/**

This repo is the meat and bones of the durable extension, as all of the work that actually provides durability is in this repository. The two core projects to look at are DurableTask.Core and DurableTask.AzureStorage. Consider looking at the READMEs for those projects, as well as contributing guides if the projects have those. I know we are in the process of adding a fairly in depth explanation for DurableTask.AzureStorage in [this PR](https://github.com/Azure/durabletask/pull/331).

If you make a change to this repo and you want to use it in your extension, you generally have to publish a local nuget package, and reference that nuget package in the DurableTask extension project. Then you can proceed as normal.

**https://github.com/Azure/azure-functions-host**

This is the functions runtime, and in general we almost never need to make modifications here to add functionality to Durable Functions. It should have a contributing guide and readme where you can read more, and you could probably develop some workflow where you make edits across all three repos and test them locally.

**Comment by hazelnutsgz** [comment]
It's really helpful!

**Comment by hazelnutsgz** [comment]
There are two repos puzzles me (When I conducted the code tracking)
https://github.com/Azure/azure-webjobs-sdk-extensions/tree/dev
https://github.com/Azure/azure-webjobs-sdk

So basically I am a little confused about the WebJobs and Azure Functions, so what's the relationship between these `webjobs` repos and `azure-functions-host`?

Thanks

**Comment by ConnorMcMahon** [comment]
The WebJobs repo is where most of the code for our event-based triggering takes place. That is because this is a historical App Service feature that allowed event-driven long-running tasks a couple of years before Azure Functions even existed.

The functions host is built on top of the WebJobs library, and turns it into a robust web app with things like logging, HTTP-based triggers, multiple language support, etc. 

The WebJobs extension repo is where most of the trigger-specific code lives. Where WebJobs contains the generic logic for running triggers and all of the abstractions for triggers, most of our actual triggers are built as extensions, so that we only need to pull in the triggers that your code needs.
