### ISSUE TITLE
[Func v1 - Suborchestrator] Failed to deserialize from TaskActivity

### ISSUE THREAD

**Issue by BigBd1** [Azure/azure-functions-durable-extension#1008]
### Description
An exception thrown in a an activity called by a suborchestrator will failed to deserialize in the main orchestrator. I know this issue has already been reported and must have been fixed in 1.8.0 release but I still encounter the problem. Here is a similar issue #697 (but the origin of the issue does not seem to be the same).

### Expected behavior 
I shouldn't have the deserialization exception that occured at orchestrator level.

### Relevant source code snippets
A very dumb example to reproduce the issue :

```csharp
        [FunctionName("Function1")]
        public static async Task Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log,
            [OrchestrationClient]DurableOrchestrationClient starter)
        {
            await starter.StartNewAsync("Orch", null);
        }


        [FunctionName("Orch")]
        public static async Task RunOrch([OrchestrationTrigger]DurableOrchestrationContext ctx, TraceWriter log, Microsoft.Azure.WebJobs.ExecutionContext context)
        {
            try
            {
                await ctx.CallSubOrchestratorAsync("SubOrch", null);
            }
            catch (System.Exception ex)
            {
                log.Error("Act ex catched in orch", ex);
                throw;
            }
        }

        [FunctionName("SubOrch")]
        public static async Task RunSubOrch([OrchestrationTrigger]DurableOrchestrationContext ctx, TraceWriter log, Microsoft.Azure.WebJobs.ExecutionContext context)
        {
            await ctx.CallActivityAsync("Act", null);
        }

        [FunctionName("Act")]
        public static async Task RunAct([ActivityTrigger]DurableActivityContext ctx, TraceWriter log, ExecutionContext context)
        {
            throw new System.Exception("Hello");
        }
```

### Known workarounds
Unfortunately I don't have any workaround for this issue except extracting the original exception from the deserialization exception message...

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 1.8.3
- **Azure Functions runtime version (1.0 or 2.0)**: 1.0 (Sdk 1.0.29)
- **Programming language used**: C#

### Screenshots
Maybe you can find some useful info there : 
![image](https://user-images.githubusercontent.com/4406847/67936451-1b36ff00-fbcc-11e9-8663-12beba8411a7.png)

The stack trace for the last inner exception with message : 'Could not load assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask'' is here : 

>    at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(TypeNameKey typeNameKey)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at DurableTask.Core.Serializing.PackageUpgradeSerializationBinder.BindToType(String assemblyName, String typeName) in C:\source\durabletask\src\DurableTask.Core\Serializing\PackageUpgradeSerializationBinder.cs:line 59
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)

Thank you in advance !

**Comment by ConnorMcMahon** [comment]
This now has a solution in our 2.1 release. I have opened an issue to better document this (#1208).
