### ISSUE TITLE
Analyzer confuses Durable 2.X project with Durable 1.x

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#1018]
### Description
I've added the analyzer to the precompiled sample project and it gives me this warning:

> Warning	DF0201	OrchestrationTrigger is applied to a 'IDurableOrchestrationContext' but must be used with a DurableOrchestrationContext or a DurableOrchestrationContextBase instead.	VSSample	C:\GitHub\azure-functions-durable-extension\samples\precompiled\HelloSequence.cs	15	Active

This would be correct for a Durable 1.x project, but this is actually a Durable 2.x project.

### Expected behavior
The analyzer should know what kind of project it is analyzing and make the appropriate recommendation.

### Relevant source code snippets
```csharp
[FunctionName("E1_HelloSequence")]
public static async Task<List<string>> Run(
    [OrchestrationTrigger] IDurableOrchestrationContext context)
{
    ...
}
```

### Known workarounds
None

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.0.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: c#

**Comment by n-margalit** [comment]
I have the same issue 😒

**Comment by amdeel** [comment]
@n-margalit Hey. A few questions:
Which version of durable functions are you using?
Which version of the analyzer are you using?
Also, can you confirm which warning you are seeing? Is it "DF0201"?

**Comment by franklixuefei** [comment]
@amdeel the author explicitly said DF0201, 
>Warning DF0201 OrchestrationTrigger is applied to a 'IDurableOrchestrationContext' but must be used with a DurableOrchestrationContext or a DurableOrchestrationContextBase instead. VSSample C:\GitHub\azure-functions-durable-extension\samples\precompiled\HelloSequence.cs 15 Active
and
>this is actually a Durable 2.x project.
he's using the latest.

**Comment by franklixuefei** [comment]
I also hit this. latest version of the analyzer, latest version of webjobs dtfx.
