### ISSUE TITLE
Doc Request: Orchestrator function replays for each activity function response during Task.WhenAll();

### ISSUE THREAD

**Issue by FinVamp1** [Azure/azure-functions-durable-extension#1022]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

### Expected behavior
> A clear and concise description of what you expected to happen.

### Actual behavior
> A clear and concise description of what actually happened.

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
- **Azure Functions runtime version (1.0 or 2.0)**:
- **Programming language used**:

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by FinVamp1** [comment]
Hi, saved in error but this is the same issue as in https://github.com/Azure/azure-functions-durable-extension/issues/92 where you can get up to 32 responses. From @cgillum This is by design, If the two activity functions complete at the same time, the replays will be batched together so that there is only one replay. We will batch at most 32 activity responses together into a single replay. If they complete at separate times, there will be one replay for each response.

**Comment by cgillum** [comment]
Hey @FinVamp1 - sorry if I'm a little confused, but is this a request to add documentation about replay batching behaviors?

**Comment by FinVamp1** [comment]
Thanks @cgillum yes, this is a documentation request for replay batching replay in regard to Async coding.

**Comment by cgillum** [comment]
I've submitted a docs PR that mentions this behavior in [this documentation section](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#orchestrator-function-replay).

> As mentioned previously, orchestrator functions are replayed using the contents of the **History** table. By default, the orchestrator function code is replayed every time a batch of messages are dequeued from a control queue. **_Even if you are using the fan-out, fan-in pattern and are awaiting for all tasks to complete (for example, using `Task.WhenAll` in .NET or `context.df.Task.all` in JavaScript), there will be replays that occur as batches of task responses are processed over time_**. When extended sessions are enabled, orchestrator function instances are held in memory longer and new messages can be processed without a full history replay.

**Comment by cgillum** [comment]
The docs PR has been merged.
