### ISSUE TITLE
Durable Tasks 2.0 prevents Moq'ing of GetStatusAsync because it's now an extension method

### ISSUE THREAD

**Issue by oising** [Azure/azure-functions-durable-extension#1032]
OrchestrationClientBase.GetStatusAsync was easily mockable. Now that GetStatusAsync is an extension method, it's not mockable with Moq (or any other framework.) This seems like a mistake on your part. Why is it now an extension method? If you have your own strategies for unit testing durable task 2.x orchestrations, please share. You broke 25 of my tests and now I don't really know how to fix them.

**Comment by ConnorMcMahon** [comment]
@oising 

I am sorry for the frustration you are experiencing transferring over to durable functions 2.0 given our usage of extension methods. We are tracking these concerns here: #1000. Some guidance is provided there about how to get around this issue, but I understand that the guidance is not perfect at this moment.

Developer experience is something that we want to make sure we do a good job on, and we clearly missed the mark on unit testing in this release. We will make sure that we improve upon this in the near future, and in the meantime I hope that the instructions that I provided in that thread about how to use Moq for the extension methods will allow you to make due in the meantime.

**Comment by oising** [comment]
For anyone else who finds this issue, after the panic went away, I followed the chain and realized that `GetStatusAsync(<instanceId>, false, false, false)` is the effective call for `GetStatusAsync(<instanceId>)`, and is Moq'able due to it being a de-facto instance method.
