### ISSUE TITLE
System.Net.Sockets.SocketException With Control Queue

### ISSUE THREAD

**Issue by kirikintha** [Azure/azure-functions-durable-extension#1033]
### Description

Hello, about 6 days ago my durable orchestrations started putting all our "starting" orchestrations into a "Pending" state into our Instance Table.

We us an HTTP Trigger -> orchestrator -> sub orchestrator approach to batch out notifications via Email and SMS.

I have been watching our orchestrations work very well for about a month and no issues until all new "StartNewAsync" commands instantly went into "Pending" and never left. I waited for about 24 hours to see if the queue reset itself, but it did not.

I cannot see any errors that are jumping out at me code/application wise, so I dug into our logs and I wanted to give you some feedback into what I am seeing.  

I have two failures that I am seeing:

1. System.Net.Sockets.SocketException "Connection reset by peer" when trying to POST to: https://[ourstorageaccount].queue.core.windows.net:443/[our-task-hub]-control-00/messages
2. GET 404 https://[ourstorageaccount].table.core.windows.net:443/[our-task-hub]Instances(PartitionKey='520ac2df052b4973a58072170d982f46',RowKey='')

When the "Connection reset by peer" reset happened - that seems to have precipitated everything going into pending.

Regarding the 404, I can clearly query the '520ac2df052b4973a58072170d982f46' via storage explorer, but it comes back 404 when queried.

In both cases, I am not sure what any of that really means or if it is relevant. 

I also have in my AI that the method that failed was: System.Net.Http.HttpConnection+<SendAsyncCore>d__61.MoveNext

### Known workarounds

We cleared the storage queues, history and instance tables and all came back as expected. I am still monitoring to see if everything is stable.

### App Details

Durable Task: 1.8.2
Azure Functions Runtime: 2.x
Programming Language: C#

### If deployed to Azure

I am so sorry that I cannot share my instance IDs with you as I had to reset everything quickly to get our notification system running and quite frankly had to go with a quick and dirty solution.

I can give you the AI information I have:

Operation ID: a4cadd76b9bb884f94f3cfcf0f787065
InvocationId: 508d5a91-e240-4e37-8c69-1e0cb8ec623d

- **Timeframe issue observed**: 11/1/2019, 2:03:46 PM (Local time)
- **Azure region**: West Central US

If I see this again, I will certainly let you know. My apologies if this was not super helpful and thanks for your thoughts on the issue.

**Comment by cgillum** [comment]
The symptoms you are describing sound very much like https://github.com/Azure/azure-functions-durable-extension/issues/961 (deadlock in the Azure Storage SDK - usually triggered by network issues).

We have a fix for the deadlock issue coming in the v1.8.4 release. If you'd like to try our fix ahead of time, I suggest upgrading to the 1.8.3 version of the extension, and then adding a nuget reference to this package: https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/1.6.5. Let us know if this helps.

**Comment by kirikintha** [comment]
@cgillum - Thank you so much for the update, I have updated and our dev environment. Since this seems to be based around networking timeouts I am not sure I can reproduce the issue, but hopefully we do not see any other issues. To keep noise out, I'll report back if I see the deadlock again. Many thanks!

**Comment by cgillum** [comment]
Thanks for the update @kirikintha. I'll go ahead and close this issue for now. Do let me know if you run into this again with the updated package and we will investigate further.
