### ISSUE TITLE
Covariance and Contravariance in Task<TResult> CallActivityAsync<TResult>(string functionName, object input); 

### ISSUE THREAD

**Issue by hunyhabib** [Azure/azure-functions-durable-extension#1034]
### Description
> Deserialization for List of children are failing when calling CallActivityAsync<T> with List of Base item

### Expected behavior
> Serialization & Desalinization should have type persistence through the flow. 

### Actual behavior
> type is changed to base type upon deserialization of result of CallActivityAsync<T>

### Relevant source code snippets
```csharp
var jobsInfo = await context.CallActivityAsync<List<BaseJob>>("GetJobsConfiguration", null);
```

### Known workarounds
I returned Objects List and then cast later dependent on info inside the Serialized JObject.
```csharp
var jobsInfo = await context.CallActivityAsync<List<object>>("GetJobsConfiguration", null);
  var templateName = ((JObject) job)["TemplateName"].ToString();
                        var castedJob =
                            (BaseJobInfo) ((JObject) job).ToObject(JobInfoTypeServiceLocator.GetType(templateName));
```
### App Details

- **Azure Functions runtime version **: 2.0
- **Programming language used**: c#

**Comment by ConnorMcMahon** [comment]
This should technically be possible by injecting a custom `IMessageSerializerSettingsFactory` in Durable Functions v2.1 or later. We will be documenting it as a part of #1208.
