### ISSUE TITLE
Orchestartion function status stay at "Pending" state durring execution

### ISSUE THREAD

**Issue by petr-x** [Azure/azure-functions-durable-extension#1038]
### Description
Orchestrator fuction doesn't change status from "Pending" state to "Running"

### Expected behavior
Once Orchestrator function is processing code within the function, the status should change to Running

### Actual behavior
Orchestrator function keep Pending durring run of Function code. Even have 5 sec sleep before the breakpoint  will not change the status from Pending to Runnnig.

### Relevant source code snippets
```csharp
        [FunctionName("Orchestrator")]
        public static async Task MyOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context,
            ILogger log)
        {
            var inventoryData = context.GetInput<InventoryEntity>();

            // sleep before Entity check
            var nextRun = context.CurrentUtcDateTime.AddSeconds(5);
            await context.CreateTimer(nextRun, CancellationToken.None);
        }
```

Set breakpoint on the "var nextRun" row. The Orchestrator instance status will be on pending state however it should be already on running state.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.0.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0.12858.0
- **Azure Functions Core Tools**: 2.7.1846
- **Programming language used**: C# (.Net Core 3.0)

**Comment by keithpatton** [comment]
We have the same issue where we have an Orchestrate Function that was previously calling an Activity and now calls entity, but the control queue has messages and the Orchestration is stuck in pending and never starts. We stopped our app, deleted all associated azure storaage resources and restarted and the same thing happened.

**Comment by BenjaBobs** [comment]
Not sure if this is related, but I am also experiencing an Orchestrator function stuck in `Pending`.

What I've noticed is, I recently decided upon using a custom TaskHub name.
I can reliably reproduce the following:
```c#
[FunctionName(nameof(BrokenOrchestratorStarter))]
public async Task<HttpResponseMessage> BrokenOrchestratorStarter(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")]HttpRequestMessage req,
    [DurableClient(TaskHub = "SomeName")] IDurableOrchestrationClient client
) {
    // This orchestration will be stuck in pending
    string instanceId = await client.StartNewAsync("MyOrchestration", args);
	// ...
}

[FunctionName(nameof(WorkingOtherOrchestratorStarter))]
public async Task<HttpResponseMessage> WorkingOtherOrchestratorStarter(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")]HttpRequestMessage req,
    [DurableClient] IDurableOrchestrationClient client
) {
    // This orchestration will work as expected
    string instanceId = await client.StartNewAsync("MyOrchestration", args);
	// ...
}
```

My settings are

```xml
<PropertyGroup>
	<TargetFramework>netcoreapp3.0</TargetFramework>
	<AzureFunctionsVersion>v3-preview</AzureFunctionsVersion>
</PropertyGroup>

<ItemGroup>
    // ...
	<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
	<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.0.0" />
	<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.30-beta2" />
</ItemGroup>
```

**Comment by cgillum** [comment]
Hi @petr-x. What you're observing is by design, and is a behavior of the Durable Task Framework. The orchestration status will not switch from `Pending` to `Running` until the first `await` statement in your code. Once the first `await` is hit, the orchestration history will be updated and the status will be updated to `Running`. Since you are putting a breakpoint `before` the first await statement, the orchestration does not have a chance to update its history and status.

@keithpatton and @BenjaBobs, I think you are observing different issues. Would you mind opening separate issues on GitHub so that we can track them individually? And for those issues, please let us know the instance ID of the stuck orchestration, the region you are observing this, and an approximate date/time where you're seeing this.

Thanks!
