### ISSUE TITLE
StartNewAsync sometimes takes 2 minutes to complete

### ISSUE THREAD

**Issue by Dzoukr** [Azure/azure-functions-durable-extension#1040]
### Description
I have a starter function which is triggered by `BlobTrigger` and just calls `client.StartNewAsync` (and awaits its return to get orchestration id). Sometimes (sorry, it happens totally randomly - probably under higher load) the starter function takes about two minutes to complete:

![image](https://user-images.githubusercontent.com/851307/68619760-5ee31000-04cc-11ea-911e-152b02d0ab27.png)

Here are the detailed info from AppInsights:

![image](https://user-images.githubusercontent.com/851307/68620567-07de3a80-04ce-11ea-8e3f-997abd233a0c.png)

### Expected behavior
Starter function runs in few seconds at most.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Microsoft.NET.Sdk.Functions**: 1.0.29
- **Programming language used**: F#

### Azure information
- **Timeframe issue observed**: `2019-11-11 18:57 UTC`
- **Function name(s)**: `ImportPrices_Starter`
- **Host Instance ID**: `f299654a-33ff-45f1-a202-97068fa778ee`
- **Operation ID**: `05e0d56bed75a4479ad44ff6c121291f`

**Comment by ConnorMcMahon** [comment]
@Dzoukr 

Sorry for the delay in getting to this issue. Are you still encountering this, and if so, can you provide an instance id. Unfortunately your original instance id has fallen out of our logs.

**Comment by Dzoukr** [comment]
@ConnorMcMahon 

Sorry, we had to workaround this and instance is no longer active. I'll reopen if we encounter it ever again.
