### ISSUE TITLE
Durable functions not behaving in an idempotent way

### ISSUE THREAD

**Issue by madan81k** [Azure/azure-functions-durable-extension#1044]
Scenario: I am architecting a message delivery from point a to point b with some tranformation in between. I have suggested this durable function to the client saying that it is atomic and idempotent.
I ran a negative scenario of their requirement and found it is not behaving as expected in the below scenario. this is very critical since they have a tight schedule to release. please let me know whats happening here, so i can suggest an alternate for now, before  the fix OR is it something i am doing wrong?
Steps:
 1. Create a durable functions with  one http trigger, one orchestrator and one activity function
 2.  In the http trigger, start the orchestrator by calling StartNewAsync to Orchestrator function.
 3. In the Orchestrator call the activity function more than once(twice,thrice..)
 4.  In Activity function store the message in some table storage just for this demo.
If unable to follow,this is the basic code template thats get generated when we create an Azure durable functions in VS2019/VS2017.
Build and publish it to the Azure.
1. Once in Azure, for testing negative scenario, disable Activity Function. 
2. Post an http message to the http trigger function. it gives 202 accepted status
3. Now, disable Orchestrator function
4. Post another http message to the http trigger. it also gives 202 accepted
5. now, enable orchestrator function and wait for sometime
6. enable activity function
Now,if the orchestrator had called activity function twice, then the number messages expected would be 4. But, it is 5.
Please let me know if the info is clear or need more info. awaiting quick reply.
Thanks,
Madan

**Comment by oising** [comment]
In your flow above steps 6 and 8 result in TWO orchestrator instances being created. It sounds like it's behaving as designed.

An orchestrator __instance_ when written according to the guidelines should behave idempotently for on the *same instance* when being replayed. Replaying is equivalent to deserialization of a serialized instance. It doesn't mean multiple instances of an orchestration with the same input will behave idempotently - example, if the orchestrator had an activity that created a new guid, each instance would have a different guid.
