### ISSUE TITLE
Consider enhancing the analyzer to process local (inline) functions

### ISSUE THREAD

**Issue by oising** [Azure/azure-functions-durable-extension#1045]
The durable functions analyzer does not seem to analyze local (inline) functions.

**Comment by amdeel** [comment]
@oising Can you provide more detail? I don't understand what you're suggesting we analyze. Any specific expectations you have and code snippets would help.

I really appreciate feedback and suggestions for our analyzer, so thank you for taking the time to give us your input.

**Comment by oising** [comment]
Sorry, I think I got this backwards -- if I use a local function, I cannot use `[Deterministic]` to annotate it (c# limitation), and it is flagged as being in violation of orchestrator rules. 

e.g.

```c#
        [FunctionName(nameof(TriggerBreaker))]
        public async Task TriggerBreaker(
            [OrchestrationTrigger] [NotNull] IDurableOrchestrationContext context)
        {
            // ...

             // [Deterministic] <-- will not compile
            async Task<DurableHttpResponse> FunctionCommand(string operation)
            {
                var functionCommandRequest = new DurableHttpRequest(
                    HttpMethod.Post,
                    new Uri($"https://management.azure.com{config.ResourceId}/{operation}?api-version=2016-08-01"),
                    tokenSource: new ManagedIdentityTokenSource("https://management.core.windows.net"));

                return await context.CallHttpAsync(functionCommandRequest);
            }

            var response = await FunctionCommand("stop");

            // ...

           var response = await FunctionCommand("start");
```
I guess this is by design and I can suppress in the source.

**Comment by amdeel** [comment]
Good point. This is definitely an oversight. I don't think it's reasonable for the customer to have to suppress the warning that this causes at the moment. I can add the ability to analyze those funcitons that are defined within the orchestrator itself. Thanks for this suggestion!
