### ISSUE TITLE
Http response coming as BadRequest in azure function though it works fine in postman

### ISSUE THREAD

**Issue by iamsuresha** [Azure/azure-functions-durable-extension#1046]
While running azure function in local & in postman the http request returns 200 OK but the same request returns BadRequest after hosting in Azure function.

Received HTTP response after 88.0211ms - BadRequest.

Any suggestions please.

@cgillum @markheath

**Comment by markheath** [comment]
we'd need to know a bit more about what your function is doing to know why that happens. Have a look at the function invocation history in the portal to see if the logs give any clues.

**Comment by iamsuresha** [comment]
![image](https://user-images.githubusercontent.com/50022627/68942008-6442a200-07cd-11ea-9443-34d70be69f5c.png)
When i used HttpClient for this request i do not face any issues but when I used HTTPClientFactory i am getting bad request for the attached request. Is there any additional parameters needed for this request in azure function?

**Comment by cgillum** [comment]
Hi @iamsuresha. I don't think this is actually an issue with Durable Functions itself, but has something to do with your application logic. If you're able to reproduce this locally, then I suggest you use an HTTP network trace tool like [Fiddler](https://www.telerik.com/fiddler) to compare the successful request with the failing request. That should help clarify why the postman and `HttpClient` requests are succeeding while the `HttpClientFactory` requests are failing. Most likely there is some configuration issue with your `HttpClientFactory` which is creating a payload that the target service does not like.

I'm going to go ahead and close this issue for now. If after debugging you can point to a specific issue with the injected `HttpClientFactory`, then please open a new issue in the [Azure Functions GitHub repo](https://github.com/Azure/azure-functions).

Thanks.
