### ISSUE TITLE
Cannot use any kind of queueTrigger anymore locally

### ISSUE THREAD

**Issue by pregoli** [Azure/azure-functions-durable-extension#1048]
I'm running the project on VisualStudio 2019 version 16.3.9

Since today, everytime I run the project I get this error:

**Microsoft.Azure.WebJobs.Host: Error indexing method 'TriggerUserProvisioningChainingWorkflow'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter '$return' to type String&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).**

**Error indexing method 'TriggerUserProvisioningChainingWorkflow'
[11/13/2019 9:37:59 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'TriggerUserProvisioningChainingWorkflow'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter '$return' to type String&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).**

 **The 'TriggerUserProvisioningChainingWorkflow' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'TriggerUserProvisioningChainingWorkflow'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter '$return' to type String&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).**

I have the same issue with all kind of queue triggers, it was working till yesterday.

**Comment by ConnorMcMahon** [comment]
Did you update either the Durable Functions or Azure Storage extension, or the Azure Functions VS extension?

Also, what is the exact version of the Azure Functions runtime you are using? It should be in one of the first few lines of the output when you run the project.

**Comment by pregoli** [comment]
Hi @ConnorMcMahon ,
Nope, I only tried running the project were working hours before. I'didn't applied any kind of change since the last working time.

**Function Runtime Version: 2.0.12858.0**
Project Packages:

    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.RabbitMQ" Version="0.2.2029-beta" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
    <PackageReference Include="MongoDB.Driver" Version="2.9.2" />
    <PackageReference Include="Sendgrid" Version="9.12.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.6.0" />


The foolish thing, I tried to create a clone project from scratch by copying all the same settings and it works....

**Comment by pregoli** [comment]
At the end I discovered TriggerFunctions were returning Task<string> that is not available. By removing the output, so changing from Task<string> to Task, everything rorks.

Thank you

**Comment by ConnorMcMahon** [comment]
Glad to hear the issue was resolved!
