### ISSUE TITLE
How to use Durable Functions 2.0 for non-.NET languages?

### ISSUE THREAD

**Issue by wisesimpson** [Azure/azure-functions-durable-extension#1051]
I'm using extension bundles to develop durable functions in JavaScript. By [the tutorial](https://docs.microsoft.com/en-gb/azure/azure-functions/functions-bindings-register#extension-bundles) this seems the recommended way to setup local development.  
But I can't find any documents about specifying the desired version of each extensions.

This is my host.json file
{
    "version": "2.0",
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[1.*, 2.0.0)"
    }
}

How can I specify the version of Durable Functions? For example version 2.0?

**Comment by cgillum** [comment]
I don't think Durable 2.0 is available as a bundle quite yet. Adding @soninaren to confirm.

**Comment by ConnorMcMahon** [comment]
You do not have to use extension bundles, it is just the most convenient experience for non-.NET languages.

1.	Remove the following from yourhost.json 
```json
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[1.*, 2.0.0)"
  }
 ```
2.	Install the specific version of the extension with this command at the root of your function app. It requires the functions core cli tools to be installed on your dev box.
 
`func extensions install -p Microsoft.Azure.WebJobs.Extensions.DurableTask -v 2.0.0`

That should create an `extensions.csproj` file in your directory, which should have a reference to the appropriate version of Durable Functions.

**Comment by wisesimpson** [comment]
Using Functions Core CLI tool and installing extensions manually works. Thank you.

The documents always point us to using ExtensionBundle for non-.net language, so better documentation is needed.

**Comment by soninaren** [comment]
@wisesimpson An extension bundle for durable 2.0 should out very soon. The bundles deployment should have kept up with new extension releases. The infrastructure for faster extension bundles releases is in progress. That being said we can definitely have better documentation on what bundle version to extension version mapping and updates on upcoming releases.

**Comment by cgillum** [comment]
FYI @anthonychu regarding documentation.
