### ISSUE TITLE
Control queues not being processed

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1059]
DF 1.8.3
.NET Core
UK South

@cgillum Our durable function app throughput started to degrade during a sustained load test, after several hours we noticed that the throughput was slowly declining towards zero, despite there being hundreds of thousands of messages remaining across the 16 control queues. We eventually abandoned the sustained load test.

This graph demarks the start and end of the sustained load test.

![image](https://user-images.githubusercontent.com/4224880/69177414-64a9a880-0aff-11ea-86dd-a7671a2cd287.png)

---

Upon closer inspection I noticed that our `purge` function, which runs every 15 minutes to clean up old orchestrations was timing out (5 minute consumption limit). I had an assumption that the purge function might be the reason of the throughput degradation. I disabled the purge function and restarted the Function App. The Function App sprang back to life and began processing the control queue messages once again. However a while the throughput began dropping again.

This marks the moment I disabled the recurring purge function

![image](https://user-images.githubusercontent.com/4224880/69179890-337fa700-0b04-11ea-90bf-c64203de6e8b.png)

---

The following graph shows me performing restarts on the Function App.

![function app restarting events (2)](https://user-images.githubusercontent.com/4224880/69174874-90765f80-0afa-11ea-8138-992ec0f4ec7b.png)

The following graph shows the activities starting and completing for various in-flight orchestrations.

![throughput (2)](https://user-images.githubusercontent.com/4224880/69175039-ef3bd900-0afa-11ea-8d5d-15d253d193af.png)

Notice the correlation between the graphs, performance increases substantially immediately after a restart, but then quickly drops. This has been like this for over 12 hours now. 

---

Execution ID `95f5a9d2def6487eb5d86de10571b325` of one particular orchestration that took several hours to move between the various activity steps, when it should have took just a few seconds.

![image](https://user-images.githubusercontent.com/4224880/69176514-bf420500-0afd-11ea-9b57-edf1e802e5cc.png)

---

It appears that the work-item queue is processed as normal, but the control queues are not being actively processed.

I've currently got an open support ticket with Azure support `119111922000409`, but support insist I need to upgrade to 2.0.0 before they investigate further (which as we all know, we can't just upgrade to a major version during a live incident)  

Luckily I've mitigated this issue through our active-active configuration but it means we are currently only running in one region (UK West) which leaves us unable to mitigate further incidents. 

I need this Function App fixing so that the control-queues can be processed as normal. I also need to know why this has happened, as a simple sustained load test on the Function App shouldn't cause this.

Many thanks.

**Comment by ConnorMcMahon** [comment]
So this is definitely concerning. My first guess would be this [storage SDK deadlock](https://github.com/Azure/azure-functions-durable-extension/issues/961), which a fix for will be going out in 1.8.4, which we are currently prepping for release. The symptoms are very similar, in that restarting seems to fix it.

That being said, I would be concerned if it is that consistent for your application. @cgillum did reproduce an issue where the deadlock seemed to be tied to a corrupted blob that we were using for partition leasing, which made it happen more consistently for that application, so that is possibly what is going on here.

Unfortunately, to definitively prove it is the storage deadlock, we would need a memory dump of one of the stalled out workers, which can be hard on consumption plans. Would you be able to wait a day or two for us to get 1.8.4 out the door to see if that resolves your issue?

**Comment by cgillum** [comment]
If you don't want to wait for 1.8.4, you can also add [Microsoft.Azure.DurableTask.AzureStorage](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage) v1.6.5 as an explicit package reference to your existing 1.8.3 app. You will get the automatic deadlock mitigation by updating the AzureStorage dependency.

**Comment by olitomlinson** [comment]
@ConnorMcMahon @cgillum thanks for taking a look! It really is appreciated!

I will certainly try adding the nuget package for AzureStorage v.1.6.5 and see what happens.

---

I've left the app alone for 24 hours. It definitely begins to start processesing after an app restart, but then quickly stops again.

Here are a few restarts that have occurred during the early hours of the morning (probably workers being recycled by the platform)

![image](https://user-images.githubusercontent.com/4224880/69281873-fb9a6180-0be0-11ea-9c01-738dc2ba0047.png)

and the corresponding signals coming from my orchestration/activity code

![image](https://user-images.githubusercontent.com/4224880/69282016-3dc3a300-0be1-11ea-9fa8-d3f42eb6f866.png)

**Comment by olitomlinson** [comment]
@ConnorMcMahon @cgillum adding a reference to the new AzureStorage storage package fixed the problem. Upon deployment, the control queues drained until completion.

One thing I did notice is that just one host leased all 16 partitions for the entire duration. I expected a couple of hosts, therefor clearing faster. Shouldn’t the scale controller be looking at how deep the queues are, and allocate more hosts accordingly?

Once again, thank you so much for the fix!

**Comment by ConnorMcMahon** [comment]
That definitely sounds a bit odd. Queue length isn't the only factor (latency also is), but I imagine if the backlog was that large we would be scaling. I can take a look at see if anything unusual was going on there.

**Comment by cgillum** [comment]
Glad to see this resolved the issue!

Actually, queue length doesn't play any role in scale-out. Unlike regular storage queue triggers, the Durable scale logic only considers message latency - i.e. how long a message has been waiting in the queue. For example, we'll try to scale out if a message has been sitting idle for more than 1 or 2 seconds.

Another factor is the distribution of messages across queues. For example, if you have 1 million messages they are all in the _control queue_, then we will _not_ scale out since scaling out won't actually help us process messages any faster (only one worker VM instance is allowed to process a single control queue). I don't know if that's the case you're seeing, but thought it might be worth mentioning.

**Comment by olitomlinson** [comment]
@cgillum @ConnorMcMahon  We had around 300,000 control queue messages distributed across the 16 partitions, which had been sat there for easily over 24 hours. To be more precise, the distribution wasn't uniform, 2/3 control queues had 0, whereas others had over 100,000 messages. 

If latency was a factor in scaling, as you describe, I would have expected more workers to be leasing the partitions than just the one.

---

Immediately after the release of the fix, here is a graph showing 1 telemetry event matched to 1 control queue message being processed (so no double counting here). Notice several thousand events per minute.

![image](https://user-images.githubusercontent.com/4224880/69418534-c2620e80-0d12-11ea-8fdd-0e4f2171c159.png)

Just one `cloud_RoleInstance` processing all of the above control queue messages

![image](https://user-images.githubusercontent.com/4224880/69418616-f50c0700-0d12-11ea-9da1-ba2afa85a9e7.png)

---

By contrast, here is a very small burst of load that landed this morning over just 2 minutes :

![image](https://user-images.githubusercontent.com/4224880/69419029-a9a62880-0d13-11ea-869a-c7bbcfafeb3d.png)
![image](https://user-images.githubusercontent.com/4224880/69419325-26390700-0d14-11ea-8d7a-d3dabdd22868.png)


Which allocated across more than one `cloud_RoleInstance` - which is exactly what I would expect.

![image](https://user-images.githubusercontent.com/4224880/69419250-01449400-0d14-11ea-8814-a6f5998931b1.png)

---

My observation of the first scenario after recovery of the incident is that the function App didn't scale out the partitioned control queue work across multiple workers after the fix was applied. Maybe some sort of cold/non-happy path scenario where the latency of those control messages was not being honoured/observed? 

However the small burst of load that naturally occurred this morning, scaled as expected.
