### ISSUE TITLE
Durable 2.0: Apps without an explicit hubName do not scale in Consumption/ElasticPremium plans

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#1064]
### Description
Durable Function 2.x apps running in the Azure Functions Consumption and Elastic Premium plans do not scale unless the [hubName](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#host-json) property is explicitly set in `host.json`.

### Expected behavior
The `hubName` property has always been optional. In Durable 1.x, a function without an explicit `hubName` scales fine in the Consumption and Elastic Premium plans because the Scale Controller knew to use the default value of `DurableFunctionsHub`. Naturally, Durable 2.x apps should also scale fine when no `hubName` is specified.

### Actual behavior
The scale controller defaulting behavior no longer works with Durable 2.0 apps that do not have a `hubName` configured. The result is that these apps cannot be scaled, and may idle out.

The scale controller does not currently understand the distinction between Durable 1.x and 2.x apps, so this is not a trivial issue to fix. Additional metadata may need to be provided to the scale controller when the list of triggers is registered (this happens in several places, including Kudu and the Azure Functions runtime).

### Known workarounds
Adding a `hubName` value in host.json should cause scaling to work correctly.

### App Details

- **Durable Functions extension version**: 2.0+
- **Azure Functions runtime version (1.0 or 2.0)**: any
- **Programming language used**: any

**Comment by ConnorMcMahon** [comment]
We have [a temporary fix](https://github.com/Azure/azure-functions-host/pull/5282) for this in the next Functions V2 (and maybe V3?) release. 

We are working on something more robust and sustainable.

**Comment by ConnorMcMahon** [comment]
We have a fix in-progress for the Scale Controller that should go out as a part of the next App Service deployment cycle (late January/early February).

**Comment by cgillum** [comment]
Closing since the App Service change has been merged and we're just waiting for it to be deployed worldwide (should be completed by no later than Feb 2020).

**Comment by tbasallo** [comment]
Has this been deployed? Where can we check?

**Comment by ConnorMcMahon** [comment]
@tbasallo,

The Functions V2 runtime has been deployed for a while with the fix. The App Service change has just started rolling out, and will likely due so over the course of the next month or so. I believe you can check by going to the Advanced Tools/Kudu site for your function app and checking when the Azure App Service version starts with `87.`

**Comment by tbasallo** [comment]
Does it have to be in both places for the fix to "work." I guess O am confused between the difference of the fix being applied in two paces. 

When is it ultimately fixed?

I am stuck on 1.8 and afraid to upgrade if it's even remotely possible that it can affect any functions.

**Comment by ConnorMcMahon** [comment]
@tbasallo 

So the Function runtime is responsible for sending trigger information to the App Service scale controller infrastructure. There are 3 different versions of the Functions Runtime (V1, V2, and V3). This is different from the version of the Durable Functions extension you are using (1.8). You can read more about this [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions).

If you are on Functions V2, the issue should be resolved for you. If you are on V1 or V3, a fix will be deployed to the App Service infrastructure that more gracefully handles this. Once that deploys, the issue should be fixed regardless of your Functions runtime version.

Also, you can completely avoid this issue by including a TaskHub in your host.json. This is generally a best practice anyways.

**Comment by tbasallo** [comment]
@ConnorMcMahon 

Thanks for the explanation Much appreciated.

I do have a taskhub on my host file, but even with it I suffered from a related issue (#1082) which I am not sure if it's actually fixed in the release. Waiting for the rollout to test (I am on v3).
