### ISSUE TITLE
Microsoft.Azure.Management.ResourceManager.Models Nuget is in prerelease version.To use in production we need a stable version.When is it planned?

### ISSUE THREAD

**Issue by shiwani** [Azure/azure-functions-durable-extension#1070]
**Is your feature request related to a problem? Please describe.**
Cannot use preview package - Microsoft.Azure.Management.ResourceManager.Models.
What is the timeline for a stable version.

**Describe the solution you'd like**
A 1.0 stable nuget package.

**Describe alternatives you've considered**

**Additional context**

**Comment by shiwani** [comment]
@azure-sdk any update?

**Comment by ConnorMcMahon** [comment]
I think you opened this in the wrong repository. Unfortunately, I do not have the ability to transfer it to their repo. Try opening an issue [here](https://github.com/Azure/azure-sdk-for-net).
