### ISSUE TITLE
The code logic concerning the persistence of instance in entity function.

### ISSUE THREAD

**Issue by hazelnutsgz** [Azure/azure-functions-durable-extension#1076]
I am exploring the implementation of persistence desire in entity function.

As mentioned in the documentation:
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities, 
it stresses that 
`To persist this object in storage, it's serialized and deserialized by the Json.NET library.". `
The experiment I conducted confirms the stance.
But when diving into the code, I feel a little puzzle.

Basically, I tracked to:
```
internal static TEntityInterface Create<TEntityInterface>(IEntityProxyContext context, EntityId entityId)
{
       var type = TypeMappings.GetOrAdd(typeof(TEntityInterface), CreateProxyType);

       return (TEntityInterface)Activator.CreateInstance(type, context, entityId);
}
```

I held that `Activator.CreateInstance` is just a method to create an instance based on reflection according to NET docs. So how could it be connected with Azure Storage.

My guess here is this is kind of ORM, and the annotation `[JsonObject(MemberSerialization = MemberSerialization.OptIn)]`
in each definition of Entity class plays an important role. But I can not find further proof for it. (The codebase is so large!!!)

I would appreciate it if anyone could help with it. Thanks.

**Comment by sebastianburckhardt** [comment]
The deserialization is happening *after* the object has been constructed, using `JsonConvert.Populate`, which is a useful feature of the Json.NET library. The advantage is that it allows us to do pass arguments to the constructor, and leverage dependency injection.

See `DurableEntityContext.cs` - the relevant piece of code looks like this: 
```csharp
    if (this.State.EntityExists)
            {
                try
                {
                    JsonConvert.PopulateObject(this.State.EntityState, result);
                }
                catch (Exception e)
                {
                    throw new EntitySchedulerException($"Failed to populate entity state from JSON: {e.Message}", e);
                }
            }
```
