### ISSUE TITLE
DurabilityProvider.GetDelayInSecondsAfterOnProcessException causes StackOverflowException

### ISSUE THREAD

**Issue by thomasrosdahl** [Azure/azure-functions-durable-extension#1077]
### Description
`DurabilityProvider.GetDelayInSecondsAfterOnProcessException` causes `StackOverflowException`

### Expected behavior
Method does not trigger infinite recursion

### Actual behavior
Method triggers infinite recursion causing `StackOverflowException`

### Relevant source code snippets
https://github.com/Azure/azure-functions-durable-extension/search?q=GetDelayInSecondsAfterOnProcessException&unscoped_q=GetDelayInSecondsAfterOnProcessException

`public int GetDelayInSecondsAfterOnProcessException(Exception exception)
{
        return this.GetDelayInSecondsAfterOnProcessException(exception);
}
`

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.0.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0.12888.0
- **Programming language used**: C#

**Comment by ConnorMcMahon** [comment]
Didn't mean to close this.

**Comment by cgillum** [comment]
Closing completed issues in preparation for the v2.1 release.
