### ISSUE TITLE
Eternal Orchestration Functions stops on host shutdown

### ISSUE THREAD

**Issue by mpalese** [Azure/azure-functions-durable-extension#1078]
Durable functions stop running when the hosts shutdowns on consumption plan. Only after an event that restarts the host occurs (like a new Service Bus message, connecting through log streaming or the portal) the orchestration restarts.

I also tried to put WEBSITE_USE_PLACEHOLDER = 0 in configuration without solving

**Investigative information**

Durable Functions extension version: 2.0.0
Function App version (1.0 or 2.0): 2.0
Programming language used: C#

**To Reproduce**
Just creating an eternal orchestration function that runs every two minutes:

`
[FunctionName("Durable")]
        public static async Task RunOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
        {
            int i = context.GetInput<int>();

            if (i == 0)
            {
                log.LogError("[Durable] i is ZERO!");
                return;
            }

            log.LogInformation("IsReplaying=" + context.IsReplaying);
            if (!context.IsReplaying)
            {
                var outputs = new List<string>();

                // Replace "hello" with the name of your Durable Activity Function.
                outputs.Add(await context.CallActivityAsync<string>("Durable_Hello", "Tokyo"));
                outputs.Add(await context.CallActivityAsync<string>("Durable_Hello", "Seattle"));
                outputs.Add(await context.CallActivityAsync<string>("Durable_Hello", "London"));

                log.LogInformation("[Durable] Finish with i = " + i);
                var nextCheckpoint = context.CurrentUtcDateTime.AddMinutes(2);

                ++i;
                await context.CreateTimer(nextCheckpoint, CancellationToken.None);
                log.LogInformation("[Durable] context.CreateTimer");
                context.ContinueAsNew(i);

            }
            return;
        }

        [FunctionName("Durable_Hello")]
        public static string SayHello([ActivityTrigger] string name, ILogger log)
        {
            log.LogInformation($"Saying hello to {name}.");
            return $"Hello {name}!";
        }

        [FunctionName("Durable_HttpStart")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, methods: "post", Route = "{istanceId}")]HttpRequestMessage req,
            [DurableClient]IDurableOrchestrationClient starter,
            string istanceId,
            ILogger log)
        {
            // Function input comes from the request content.
            await starter.StartNewAsync("Durable", istanceId,1);

            log.LogInformation($"Started orchestration with ID = '{istanceId}'.");

            return starter.CreateCheckStatusResponse(req, istanceId);
        }`

**Expected behavior**
The function should run endessly every two minutes.

**Actual behavior**
Instead, it runs for an hour or so, and then stops running. If the instance is connected to app insights you get a "host is stopping" trace before the orchestration stops. Azure storage durable functions table shows the orchestration as running.

**Comment by ConnorMcMahon** [comment]
@mpalese 

Have you specified the task hub name in the application you are experiencing this on? If not, you are likely experiencing issue #1064. This should have been mitigated in the latest Azure Functions 2.0 release, with a more permanent and robust fix coming as an Scale Controller fix in late January or early February. 

You can also mitigate it by yourself by specifying a Task Hub name in your host.json, which is recommended.
