### ISSUE TITLE
Orchestrations hang caused by unhandled exception in dependency injection

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#1081]
### Description
This issue was created as part of investigating ICM #159447500 (which contains all the details). To summarize, there appears to be a failure case where an unhandled exception in dependency injection code (for example, an `ObjectDisposedException` in an injected `LoggerFactory`) can result in a hung orchestration.

From what I can tell, it seems that an exception in the customer's .NET class constructor can cause the function execution to be aborted without surfacing any exception information to the Durable Functions extension. As a result, the extension is not aware of any failures and assumes the orchestration scheduled any subsequent actions, when in fact it didn't. Depending on the orchestrator function code, this can result in an orchestration that is permanently hung.

### Repro
The following code demonstrates how to minimally reproduce this issue.
```csharp
public class HelloSequence
{
    // Constructor called by Azure Functions dependency injection infrastructure
    public HelloSequence()
    {
        // Any exception thrown in here stalls the orchestration
        throw new System.Exception("Kah-BOOOOOM!!!");
    }

    [FunctionName("E1_HelloSequence")]
    public async Task<List<string>> Run(
        [OrchestrationTrigger] IDurableOrchestrationContext context)
    {
        var outputs = new List<string>();

        outputs.Add(await context.CallActivityAsync<string>("E1_SayHello", "Tokyo"));
        outputs.Add(await context.CallActivityAsync<string>("E1_SayHello", "Seattle"));
        outputs.Add(await context.CallActivityAsync<string>("E1_SayHello", "London"));

        // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!"]
        return outputs;
    }

    [FunctionName("E1_SayHello")]
    public static string SayHello([ActivityTrigger] IDurableActivityContext context)
    {
        string name = context.GetInput<string>();
        return $"Hello {name}!";
    }
}
```

### Expected behavior
An orchestration should never hang, even if there is an exception in dependency injection logic. At a minimum, the orchestration instance should be terminated.

### Actual behavior
The orchestration hangs because the runtime doesn't execute the replay.

### Known workarounds
Making sure custom DI code doesn't throw unhandled exceptions.

### App Details
This is expected to impact any .NET orchestrator functions that use dependency injection.

### If deployed to Azure
Here is a query that shows an instance of this problem. The region is West EU:
```
DurableFunctionsEvents
| where PreciseTimeStamp >= datetime(2019-11-16 16:21:00) and PreciseTimeStamp <= datetime(2019-11-16 16:22:10)
| where ExecutionId == '9f9bdd1f9e0645669491992380ade65d'
| where ProviderName == "DurableTask-AzureStorage"
| extend ActId = substring(ActivityId, 0, 8), RelActId = substring(RelatedActivityId, 0, 8), ExId = substring(ExecutionId, 0, 4), MsgId = substring(MessageId, 0, 8) 
| project TIMESTAMP, EventStampName, RoleInstance, Pid, Tid, ActId, RelActId, Level, MsgId, ExId, TaskName, TaskEventId, PartitionId, EventType, Age, NewEvents, DequeueCount, Details, LatencyMs, TaskHub, Account, ExtensionVersion, ExecutionId
| order by TIMESTAMP asc
| take 5000
```

```
FunctionsLogs
| where PreciseTimeStamp >= datetime(2019-11-16 16:21:00) and PreciseTimeStamp <= datetime(2019-11-16 16:22:10)
| where FunctionInvocationId == '8d410462-3810-4813-88fb-9fc25e28f093'
| take 5000
```

**Comment by cgillum** [comment]
I've updated the issue description with a minimal repro derived from the [HelloSequence](https://github.com/Azure/azure-functions-durable-extension/blob/cb30d41ecf5c1f4238c03f5c48e169b6b958051f/samples/precompiled/HelloSequence.cs) sample code.

**Comment by ConnorMcMahon** [comment]
This is pushed to 2.2.1
