### ISSUE TITLE
Durable Functions 1.8.4: Release activities

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1091]
As part of a release, the following items need to be taken care of. For any items that are not applicable, they should be crossed out using the `~~ ~~` markdown syntax with an explanation.

- [ ] Run private scale tests and ensure no regressions
- [X]  ~~Publish updated versions of [DurableTask.Core](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.Core/) and [DurableTask.AzureStorage](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/) to nuget.org~~ _Using DurableTask.AzureStorage v1.6.5 which is already published._
- [x] Merge all features and fixes into the `v1` branch
- [X] ~~Update .NET API docs at https://azure.github.io/azure-functions-durable-extension~~ _No public API changes._
- [ ] Publish signed version of [Microsoft.Azure.WebJobs.Extensions.DurableTask](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/) to nuget.org
- [X] Update samples to point to the latest nuget packages
- [ ] Create a PR in the [Azure Functions templates repo](https://github.com/Azure/azure-functions-templates) to update templates to the latest version
- [ ] Create a PR in the [Azure Functions bundles repo](https://github.com/Azure/azure-functions-extension-bundles) to update bundles to the latest version
- [ ] Close out or punt remaining GitHub issues for the current milestone
- [X] ~~Update official docs under https://docs.microsoft.com/en-us/azure/azure-functions/durable ([private docs repo for Microsoft employees](http://github.com/MicrosoftDocs/azure-docs-pr))~~ _Mostly internal changes, no need to update docs._
- [ ] Publish release notes
- [ ] Post announcement on [App Service Announcements GitHub repo](https://github.com/Azure/app-service-announcements) and Twitter.

**Comment by dsm0880** [comment]
@ConnorMcMahon I'm trying to track down the release notes for 1.8.4, it's available in nuget but not having the release notes here in addition the durable task project is missing the release notes for 1.6.5 which is a dependency makes me nervous. Should I not install 1.8.4?

**Comment by ConnorMcMahon** [comment]
@dsm0880 

Sorry for the delay. 1.8.4 is a suitable release to be used, but we will be releasing 1.8.5 today, which I would wait for, as it has many more fixes than 1.8.4.
