### ISSUE TITLE
IDurableOrchestrationClient.GetStatusAsync(IEnumerable<string> instanceIds)

### ISSUE THREAD

**Issue by MariaCobretti** [Azure/azure-functions-durable-extension#1097]
I am trying to compare the results of a handfull of orchestrations.

Therefor I'd like to call the GetStatusAsync Method on the DurableOrchestrationClient and pass an array of instance Ids.

there is already a overloaded method that takes datetimes and runtime states to filter the result. It should be easy to integrate the ids here.

Similarly I think that should be included in the OrchestrationStatusQueryCondition class as well as the PurgeInstanceHistoryAsync method

**Comment by cgillum** [comment]
Sounds like a reasonable feature request.
