### ISSUE TITLE
Orchestrator and sub orchestrator not calling 

### ISSUE THREAD

**Issue by NaveeKota** [Azure/azure-functions-durable-extension#1103]
Hi,

I am creating orchestrator like below, after i deployed in azure functions, what ever logs i kept in  "CreateOrderOrchestrator" orchestrator those are not showing up  application insights.I assuming my orchestrator not calling, can any once help whether i am creating orchestrator & sub-orchestrator correct or not.

**Main Orchestrator**
```csharp
string message = await client.StartNewAsync(
    Orchestrator.CreateOrderOrchestrator,
    new SharedRequests.Order.Initialization()
    {
        CartId = cart.id,
        TenantId = cart.tenantId,
        cartConfirmationNum = cart.cartConfirmationNum
    });
```
**Note:** below sub orchestrator i am using in my main orchestrator function
**Sub Orchestrator** for reference
```csharp
  var output = await ctx.CallSubOrchestratorAsync<dynamic>(
      "ProcessOrdersOrchestrator",
      new ProcessOrderIntialization()
      {
          CartId = cartId,
          CartConfirmationNum = cartConfirmationNum,
          source = preorders[0].sourceType
      });
```

Surprisingly log are coming fine when i run locally, when i deployed in azure i am facing this issue

**Comment by cgillum** [comment]
Hi @NaveeKota. Your code looks fine. Take a look at this documentation to ensure that you've correctly configured Application Insights integration with your function app: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring#enable-application-insights-integration

**Comment by NaveeKota** [comment]
Hey @cgillum, Thanks for quick reply.

i believe have configured correctly, because i can see in app insights for all logs except orchestrator logs.I am thinking i have some issue in orchestrator and sub-orchestrator level

Can you please clarify below questions 
1. can we call async/await methods in orchestrator/sub-orchestrator along with activity triggers?
2. can we call async/await methods in activity triggers?

In some cases orchestrator working fine and i am able to seen logs as well when i redeploy the code. Is there any configuration did i missed.Appreciate it.

**Comment by cgillum** [comment]
To answer your questions:

1. Yes, provided you are awaiting tasks that derive from the durable orchestration context.
2. Yes, there are no restrictions on activity trigger functions.

One thing you can try is downloading our [Durable Functions Analyzer](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers/). It can help detect if you are doing anything wrong in your code.

If things still aren't working for you. We can investigate our telemetry to try and help figure out what's going wrong. We would need to know the orchestration instance ID of one of your orchestrations, the region your app is running in, and an approximate timeframe.
