### ISSUE TITLE
How to access IDurableOrchestrationContext when using class-based durable entities and proxies

### ISSUE THREAD

**Issue by johndowns** [Azure/azure-functions-durable-extension#1104]
I've set up a durable entity using the class-based syntax. I have an orchestrator function that calls the entity, and it uses the `CreateEntityProxy<>` method so that I can work with an interface.

The entity method that I'm calling needs to signal another entity, so it needs access to the `IDurableOrchestrationContext` to be able to do this. However, I'm not sure how best to handle this. 
 I assume the `IDurableOrchestrationContext is injected automatically so I don't want to explicitly declare it on my interface and use it the caller orchestration, but if I add the `IDurableOrchestrationContext` parameter to my interface, I get this error:

>System.InvalidOperationException: Method 'MyEntityMethod' defines more than one parameter. Entity proxy interface methods must define at most one argument for operation input.

Is there a way to achieve this, or should I just avoid using a proxy for this scenario?

**Comment by johndowns** [comment]
After further investigation I was able to achieve this by overriding the dispatcher, like this:

```csharp
public class MyEntity : IMyEntity
{
    private IDurableEntityContext context;

    [FunctionName(nameof(MyEntity))]
    public static Task HandleEntityOperation([EntityTrigger] IDurableEntityContext context)
    {
        return context.DispatchAsync<MyEntity>(context);
    }

    public MyEntity(IDurableEntityContext context)
    {
        this.context = context;
    }
}
```

This way, any methods will be able to use the `context` instance field.

If there's another/better way to handle this, please let me know!

**Comment by cgillum** [comment]
Yes, this works. However, the recommended way to achieve this is to use the static [Entity.Current](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.entity.current?view=azure-dotnet#Microsoft_Azure_WebJobs_Extensions_DurableTask_Entity_Current) static property. We don't do a great job of making this apparent in the documentation, but you can find more mention of this (and samples) here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities#what-can-operations-do
