### ISSUE TITLE
The orchestration falls asleep after 20 minutes 

### ISSUE THREAD

**Issue by tugrulelmas** [Azure/azure-functions-durable-extension#1127]
### Description
I have a durable function that gets fired from an Http trigger. The aim of this function is creating a scheduled Slack message. Steps in the orchestration:

1. Getting a waiting time from a string via calling GetDateFromMessage function.
2. Sending a Slack message via calling  SendSlackMessage function.
3. Waiting until the waiting time is over.
4. Sending a Slack message via calling SendSlackMessage function.

### Expected behavior
Regardless of the duration of the waiting time, SendSlackMessage function should be called for the 4th step.

### Actual behavior
SendSlackMessage function isn't called again after creating the timer if the waiting time is longer than 20 minutes. I think the orchestration falls asleep and isn't triggered after waiting 20 minutes if there is no action. When I create a new instance or check the status of an instance the orchestration wakes up and calls SendSlackMessage function.

### Relevant source code snippets
```csharp
var message = context.GetInput<string>();
var startAt = await context.CallActivityAsync<DateTime>("GetDateFromMessage", message);
await context.CallActivityAsync("SendSlackMessage", $"*{message}* has been scheduled for *{startAt}*");
await context.CreateTimer(startAt, CancellationToken.None);
await context.CallActivityAsync("SendSlackMessage", $"*{message}* to happen now.");
```

### Known workarounds
N/A

### App Details

- **Durable Functions extension version (v2.1.0)**:
- **Azure Functions runtime version (2.0.12888.0)**:
- **Programming language used**: c#

### Screenshots
N/A

### If deployed to Azure

- **Function name(s)**: ScheduleOrchestration
- **Azure region**: West US 2
- **Orchestration instance ID(s)**: e20b54425de9471f8d9e80eff648093e

**Comment by cgillum** [comment]
If it's 20 minutes, then I assume this must be running on the consumption plan, and somehow the scale controller is not waking up the app to process the durable timer. Is this app hosted in the Azure Functions Consumption plan? If so, it might be caused by another issue where scaling does not work unless you provide an explicit `hubName` value in host.json.

**Comment by tugrulelmas** [comment]
You're right, it runs on the consumption plan. After adding following code to host.json, the problem is solved.

```
"extensions": {
    "durableTask": {
      "hubName": "SchedulerHub"
    }
}
```

**Comment by cgillum** [comment]
Great, thank you for confirming. We have another issue tracking this here (https://github.com/Azure/azure-functions-durable-extension/issues/1064), so I will mark this one as a duplicate.
