### ISSUE TITLE
Azure Portal Function host missing assemblies for durable functions?

### ISSUE THREAD

**Issue by NSTA1** [Azure/azure-functions-durable-extension#113]
I have upgraded my function app to use version 2 of the function runtime (beta)

I receive the following compilation error when I use the "Durable Functions Http Starter" template (without any modification)

> 2017-12-15T08:28:46.315 run.csx(1,1): error CS0006: Metadata file 'Microsoft.Azure.WebJobs.Extensions.DurableTask' could not be found

Do I need to pull in the Durable Functions Nuget package myself?

**Comment by cgillum** [comment]
When you created the function via the template, were you given the option to install the extension? Or do you see a link for installing the extension in the Integrate tab?

**Comment by cgillum** [comment]
The error message means that the extension was not installed. When using the portal, you can install the extension by clicking the appropriate link in the **Integrate** tab. Be warned that the process is a little slow today. For other installation mechanisms (e.g. Visual Studio 2017 or the local CLI), see the [Installation documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-install).
