### ISSUE TITLE
CallSubOrchestratorAsync serialization inconsistency

### ISSUE THREAD

**Issue by kareem613** [Azure/azure-functions-durable-extension#114]
It appears as though serialization in DurableOrchestrationContext.CallSubOrchestrationAsync result in different strings than was originally in the DurableOrchestrationContext. 

ex. The string value in DurableOrchestrationContext as a result of using DurableOrchestrationClient.StartNewAsync
`{"$type":"AzureFunctionApp.DoubleSerializationBug+InputBody, AzureFunctionApp","Name":"somevalue"}`

The string value in DurableOrchestrationContext in a suborchestration as a result of using DurableOrchestrationContext.CallSubOrchestrationAsync is
`"[{\"Name\":\"somevalue\"}]"`

Demonstrated in this gist. You should be able to execute this at 
`http://localhost:7071/api/bugs/trigger`
with body 
`{
	"property":"somevalue"
}`
https://gist.github.com/kareem613/a27a7fce39600e63d03bd262963b00c3

**Comment by cgillum** [comment]
Thanks for reporting this. Which version of the `Microsoft.Azure.WebJobs.Extensions.DurableTask` package are you using? There was a bug in version `1.0.0-beta` which had a double-serialization issue. This was fixed in `1.1.0-beta2`. More details here: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.1.0-beta2

**Comment by kareem613** [comment]
That's it. Updated to 1.1.0-beta2 and it's fine. 
So the bug is in the docs. Install instructions still reference 1.0.0-beta. 
https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-install

**Comment by cgillum** [comment]
Glad that resolved the issue for you. Thanks for noticing the docs bug. Looks like we updated the VS Code instructions but not the VS 2017 instructions. I'll look into that.
