### ISSUE TITLE
Using the built in HTTP activity with x-functions-key header breaks polling functionality

### ISSUE THREAD

**Issue by b10-dslappendel** [Azure/azure-functions-durable-extension#1141]
### Description
When using `IDurableOrchestrationContext.CallHttpAsync` to call another Azure Function with the custom header `x-functions-key` set to the default key, polling will fail with 403s.

The `Location` header that's received from the first call, contains the correct `code` param (that equals the `durabletask_extension` key), and the full URL is accessible by manually opening the page in the browser. It seems that the custom `x-functions-key` is also used during polling. Therefore the HTTP request ends up with 2 keys (both as a query param and header), and this breaks the polling because it seems that the one in the header takes priority.

### Expected behavior
The polling should not fail with a 403.
This means that one of the following options are available:
- The header `x-functions-key` should not be sent again when polling
- The key in the query param takes priority
- Both keys in the query param and header are checked for validity

### Actual behavior
As mentioned above, even if the key in the URL is valid, it seems that the header takes priority if the header is set. This causes the request to fail with a 403.

### Relevant source code snippets
```csharp
// Given that context is a IDurableOrchestrationContext
var data = new { SomeData = "here" };
var uri = "https://azurefunction.azurewebsites.net/api/HttpTrigger";
var headers = new Dictionary<string, StringValues> { ["x-functions-key"] = "default-key-here" };
var request = new DurableHttpRequest(HttpMethod.Post, uri, headers, JsonConvert.SerializeObject(data));
var response = await context.CallHttpAsync(request);
```

### Known workarounds
Instead of using the header, the key can also be directly injected into the URL as query param.
While this is definitely doable, I do expect the header to work as well.

### App Details
- **Durable Functions extension version**: v2.1.0
- **Azure Functions runtime version**: 3.0
- **Programming language used**: C#

### If deployed to Azure
- **Orchestration instance ID(s)**: 10c18cb1f7334b38aeb9cae446fa6fa9 (caller), 1c4c46139f624dadaae19186b0cdfe7e (callee)

**Comment by cgillum** [comment]
I’m a little confused. Are you saying specifying a key in the header doesn’t work at all or that specifying both the header and the query string code together doesn’t work?

Also, what do you mean when you say “the default key”? Is this the durable extension key or some other key?

**Comment by b10-dslappendel** [comment]
Specifying both causes the key in the header to take priority. The one in the URL isn't checked at all it seems. Therefore the request fails with a 403.

The default key is the one that's named `default` in Azure.

**Comment by cgillum** [comment]
So it sounds like you’re just using the wrong key. You need to use the durable extension key, not the function key. What happens if you use the durable extension key as the `x-functions-key` header?

**Comment by b10-dslappendel** [comment]
No, I'm not using the wrong key. As I've said, I'm only specifying the key I need for the first request *in the `x-functions-key` header*. The built-in HTTP activity polls automatically when the server returns a 202 with a `Location` header. It's doing that just fine. This URL includes a key as well, *and this is the correct one* I don't have control over. However, for some reason, the `x-functions-key` header is apparently also included in the following polling requests, and I have no control over that. And it seems that the server only checks the header for the key, and not the one in the query.

So yes, in that regard, it's checking the wrong key. Am I using the wrong key however? I don't think so. I'm expecting the server to check the one in the query at the very least.

**Comment by cgillum** [comment]
Ah, okay. I think I understand what you’re saying now. You’re saying that the `CallHttpAsync` API is reusing the original `x-functions-key` request header when it polls the `Location` URL. I agree this doesn’t seem like correct behavior. We will investigate.

@ConnorMcMahon were you aware of this behavior?

**Comment by ConnorMcMahon** [comment]
I was not. I think this is just the matter of us deciding to copy the headers for the original request in subsequent requests.

That may be in the incorrect behavior in general, or it may be better just to special-case avoid copying certain headers.

**Comment by b10-dslappendel** [comment]
@cgillum Yes, that's exactly what I meant 👍
