### ISSUE TITLE
Durable Function with ILogger

### ISSUE THREAD

**Issue by eddynaka** [Azure/azure-functions-durable-extension#1144]
### Description
I created an Azure Durable Function with Application Insights (just enabled it in the portal).
Created the code above to inject ILogger:
```csharp
public ConstructorFunction(ILogger<ConstructorFunction> logger)
{
    _logger = logger;
}
```
With that, when debugging, it shows in the Console windows. But, when I publish to Azure, it doesn't log it in Application Insights. 

### Expected behavior
When using ILogger from DI, it should log in Application Insights

### Actual behavior
Today, it's only logging in this scenario:
```csharp
[FunctionName("Function_HttpStart")]
public async Task HttpStart(
    [TimerTrigger("0 0 8 * * 2,3,4,5,6")]TimerInfo myTimer,
    [DurableClient]IDurableOrchestrationClient starter,
    ILogger log)
{
    // Function input comes from the request content.
    string instanceId = await starter.StartNewAsync("MyFunction", null);

    log.LogInformation($"Started orchestration with ID = '{instanceId}'.");
}
```

### App Details
- **Durable Functions extension version (e.g. v1.8.3)**: 2.1.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by ltouro** [comment]
@eddynaka I don't think it is recommended to have the Logger on the class level. It is specific to each function execution. 

Also, I don't think you need DI for that as the framework will provide this dependency for you. Each function execution will receive a new logger instance automatically. 

But if you really need the log on class level, my guess is your DI will have to setup it for you. You may use the same env vars as the framework to get your logs to the same App Insights instance (not sure which keys they use, but you may look at the configuration screen on Azure platform).

**Comment by cgillum** [comment]
@eddynaka can you explain more why you need to use the constructor `ILogger<T>` instead of the `ILogger` in the function signature? As @ltouro says, the `ILogger` you get from the function parameter already allows you to log to Application Insights.

**Comment by eddynaka** [comment]
hi @cgillum , i was using ILogger<T> because i'm using DI everywhere. So, i thought that removing that and adding the DI would work fine.

When we add a new Azure Durable Function to a project, it creates this:
```csharp
[FunctionName("Function1")]
public static async Task<List<string>> RunOrchestrator(
    [OrchestrationTrigger] DurableOrchestrationContext context)
{
    var outputs = new List<string>();

    // Replace "hello" with the name of your Durable Activity Function.
    outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "Tokyo"));

    // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!"]
    return outputs;
}
```

Can I add the ILogger here as well?

**Comment by cgillum** [comment]
@eddynaka Yeah, you can use `ILogger` in the orchestrator function too. One thing to be aware of when using it in orchestrator function is the impact of replay behavior. More information, including how to properly handle this can be found here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics#logging

**Comment by eddynaka** [comment]
I see...thanks for the response!
