### ISSUE TITLE
Purge instance history times out when there are many instances to purge

### ISSUE THREAD

**Issue by ahawes-clarity** [Azure/azure-functions-durable-extension#1145]
### Description
When running PurgeInstanceHistoryAsync under a consumption plan in Azure Functions, using the code provided in the link below, when there is a lot of data to purge (over 20,000 instances), Azure Functions times out after 10 minutes.

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management#purge-instance-history

### Expected behavior
I would expect (desire) it to just work without extra code. I realize that I could also wrap this call in a Durable function but since this something internal to the Durable Functions client I was hoping it would take care of things. Ideally, I won't even have to write a Timer function just to perform this action. It would think this could just be a config option. Maybe it is and I am unaware.

### Actual behavior
Azure Functions times out after 10 minutes.

### Relevant source code snippets
```csharp
FunctionName("PurgeInstanceHistory")]
public static Task Run(
    [DurableClient] IDurableOrchestrationClient client,
    [TimerTrigger("0 0 12 * * *")]TimerInfo myTimer)
{
    return client.PurgeInstanceHistoryAsync(
        DateTime.MinValue,
        DateTime.UtcNow.AddDays(-30),  
        new List<OrchestrationStatus>
        {
            OrchestrationStatus.Completed
        });
}
```

**Comment by ConnorMcMahon** [comment]
Unfortunately, I don't think we fully mitigate this problem in non-orchestration function executions. The 10 minute timeout is an inherit limit in how long a function can execute on Azure Functions (at least the consumption plan). Orchestrations get around this by each replay occurring as it's own Function execution, so as long as no given replay takes longer than 10 minutes.

We could potentially add an extension method to IDurableOrchestrationContext that supports a long-running purge options. Your code would look something like the below:

```csharp
FunctionName("PurgeInstanceHistory")]
public static async Task Run(
    [OrchestrationTrigger] IDurableOrchestrationContext context
    [DurableClient] IDurableOrchestrationClient client,
    [TimerTrigger("0 0 12 * * *")]TimerInfo myTimer)
{
    return await context.LongRunningPurgeInstanceHistoryAsync(
        client,
        DateTime.MinValue,
        DateTime.UtcNow.AddDays(-30),  
        new List<OrchestrationStatus>
        {
            OrchestrationStatus.Completed
        });
}
```

@cgillum, thoughts?

**Comment by cgillum** [comment]
I think the best solution in this case would be the auto-purge feature. We don't have it yet, but it's definitely something folks have been asking for: https://github.com/Azure/azure-functions-durable-extension/issues/892.  @ahawes-clarity would something like that work for you?

**Comment by ahawes-clarity** [comment]
@cgillum, yes, I suspect that an auto-purge feature would meet our needs.

**Comment by amdeel** [comment]
Marking this issue as duplicate and closing in favor of #892
