### ISSUE TITLE
Orchestraton function fails with "Non-Deterministic workflow detected: TaskScheduledEvent: 1 TaskScheduled A_CacheImage" error message.

### ISSUE THREAD

**Issue by oblomingo** [Azure/azure-functions-durable-extension#1146]
We are having long running (2-3 hours) orchestration function, which fails with "Non-Deterministic workflow detected: TaskScheduledEvent: 1 TaskScheduled A_CacheImage" message error. 
The function gets input parameter, calls first activity function to get non cached image ids list (data from the database and blob storage), then in foreach block calls second activity function (gets picture from database and puts to the blob storage) for each image id. Azure function app has two triggers – http trigger to call orchestration function via http request and timer trigger to call the function one per day.
`
public class ImageCache
{
	private readonly IImageCachingService _imageCachingService;

	public ImageCache(IImageCachingService imageCachingService)
	{
		_imageCachingService = imageCachingService;
	}

	[FunctionName("StartImagesCache")]
	public async Task<HttpResponseMessage> HttpStart(
		[HttpTrigger(AuthorizationLevel.Function, "get", "post")]HttpRequestMessage req,
		[OrchestrationClient] DurableOrchestrationClient starter,
		ILogger log)
	{
		string resetParam = HttpUtility.ParseQueryString(req.RequestUri.Query).Get("reset");
		bool resetAllImages = bool.TryParse(resetParam, out bool result) && result;

		string instanceId = await starter.StartNewAsync("O_CacheImages", null, resetAllImages);
		log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

		return starter.CreateCheckStatusResponse(req, instanceId);
	}

	[FunctionName("ScheduledStartImagesCache")]
	public async Task RunScheduled(
		[TimerTrigger("0 0 12 * * *")] TimerInfo timerInfo,
		[OrchestrationClient] DurableOrchestrationClient starter,
		ILogger log)
	{
		string instanceId = await starter.StartNewAsync("O_CacheImages", null);
		log.LogInformation($"Started scheduled orchestration with ID = '{instanceId} at {DateTime.UtcNow}.");
	}

	[FunctionName("O_CacheImages")]
	public async Task<object> RunOrchestrator(
		[OrchestrationTrigger] DurableOrchestrationContext context,
		ILogger log)
	{
		var resetAllImages = context.GetInput<bool>();

		if (!context.IsReplaying)
		{
			log.LogInformation($"Starting image caching process. InstanceId: {context.InstanceId}, resetAllImages: {resetAllImages}");
		}

		var imageIds = await context.CallActivityAsync<List<int>>("A_GetImagesForCaching", resetAllImages);
		foreach (var id in imageIds)
		{
			try
			{
				await context.CallActivityAsync<int>("A_CacheImage", id);
			}
			catch (Exception e)
			{
				log.LogError(e, $"Cache failed for image {id}");
			}
			finally
			{
				context.SetCustomStatus($"Image caching progress: {imageIds.IndexOf(id) + 1} from {imageIds.Count}.");
			}
		}

		if (!context.IsReplaying)
		{
			log.LogInformation($"Image caching process completed. InstanceId: {context.InstanceId}");
		}

		return new { Success = true, Output = $"Image caching process completed. {imageIds.Count} images cached." };
	}

	[FunctionName("A_GetImagesForCaching")]
	public async Task<List<int>> A_GetImagesForCaching(
		[ActivityTrigger] DurableActivityContext context,
		ILogger log)
	{
		var resetAllImages = context.GetInput<bool>();
		var imageIds = resetAllImages
			? await _imageCachingService.GetAllImageIdsAsync()
			: await _imageCachingService.GetNotCachedImageIdsAsync();
		log.LogInformation($"Found {imageIds.Count} images for caching.");

		return imageIds;
	}

	[FunctionName("A_CacheImage")]
	public async Task<int> CacheImage([ActivityTrigger] int imageId, ILogger log)
	{
		var id = await _imageCachingService.CacheImage(imageId);
		log.LogInformation($"A_CacheImage: Image id: {id} cached.");

		return id;
	}

Application Insight has only trace information without any error logs.
statusQueryGetUri result:
```
{
    "name": "O_CacheImages",
    "instanceId": "96d60bb4fe6a4cafa577ba968d4b8f48",
    "runtimeStatus": "Failed",
    "input": false,
    "customStatus": "Image caching progress: 1956 from 4549.",
    "output": "Non-Deterministic workflow detected: TaskScheduledEvent: 1 TaskScheduled A_CacheImage",
    "createdTime": "2020-01-07T10:16:29Z",
    "lastUpdatedTime": "2020-01-07T11:13:35Z"
}
```
Versions:
Microsoft.Azure.Functions.Extensions" Version="1.0.0"
Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.8.3"
Microsoft.NET.Sdk.Functions" Version="1.0.28"

Programming language: C#
Deployed from Visual Studio 2019

**Comment by GlennDOrr** [comment]
I'm getting "Non-Deterministic workflow detected: TaskScheduledEvent: 6 TaskScheduled UpsertNameAndCodeActivity". I get this message consistently after the durable function has ran for more than 30 minutes and 2,000+ activities have run. No errors are reported.

Using netcoreapp2.2, v2 azure function version, 
Microsoft.Azure.WebJobs.Extensions.DurableTask Version=2.1.0
Microsoft.NET.Sdk.Functions Version=1.0.29
On consumption plan

**Comment by amdeel** [comment]
Hey @oblomingo, I checked our logs to investigate your issue.

It appears that your Prod and QA apps are using the same TaskHub name, which is causing your issue. Specifying a TaskHub name for your app should resolve this issue.

Here is our documentation on TaskHubs:
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs

**Comment by amdeel** [comment]
@GlennDOrr Perhaps your issue is related. Try updating to 2.1.1 and make sure that any test and production apps have unique TaskHub names. I hope that solves your problem! If not, open an issue with as much information as possible including relevant code and an orchestration instanceId and I'll see if I can help you out as well.

**Comment by oblomingo** [comment]
@amdeel I configured TaskHub name for each environment and now all functions running without errors in all environments. Thank you very much!
However I wish to draw attension that initial error message was "Non-Deterministic workflow detected". Probably, durable fuction in some way should detect that same taskhub used for more that one function and provide correct error message.
If it's not possible, could you please place this warning about task hub usage in a more visible page place (for example under overview section). That it would be easier to find it.
