### ISSUE TITLE
HTTP API start orchestration fails with request body

### ISSUE THREAD

**Issue by pajzo** [Azure/azure-functions-durable-extension#1156]
### Description
When I want to start an orchestration trough the HTTP API it fails when I'm includes a request body. If the request body is empty everything works fine.

### Expected behavior
To accept the JSON in the request body.

### Actual behavior
It gives an error:
```
{
    "Message": "Something went wrong while processing your request",
    "ExceptionMessage": "Object reference not set to an instance of an object.",
    "ExceptionType": "System.NullReferenceException",
    "StackTrace": "   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 666\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 206"
}
```

Problem seems to be here:
https://github.com/Azure/azure-functions-durable-extension/blob/65fdda6590f25db9b2127ea99ce1315d4af1758d/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L666

![image](https://user-images.githubusercontent.com/8638460/72152167-83fbde00-33aa-11ea-88e7-d3f951597e70.png)

### Relevant source code snippets
```csharp
        [FunctionName("Just-a-test")]
        public async Task<string> Test([OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            string name = context.GetInput<MyClass>();
            return $"Hello {name}!";
        }
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version0**: 2.1.1 + 2.1.0
- **Azure Functions runtime version**: 2.0
- **Programming language used**: C#

### If deployed to Azure
Deployed a test on instance _FunctionApp203320200110022613_

**Comment by lechnerc77** [comment]
The same is true for JavaScript/Typescript invocation - see [#1160 ](https://github.com/Azure/azure-functions-durable-extension/issues/1160). 

You find a GitHub repo to reproduce the issue:
[https://github.com/lechnerc77/AzureDurableInputIssue](https://github.com/lechnerc77/AzureDurableInputIssue)
Branch "[master](https://github.com/lechnerc77/AzureDurableInputIssue/tree/master)": Correct behavior with ExtensionBundle
Branch "[plainextension](https://github.com/lechnerc77/AzureDurableInputIssue/tree/plainextension)": Code with  plain extension
See README.md on branch master for details

**Comment by pajzo** [comment]
@cgillum any idea when v2.2 will be released?

**Comment by pajzo** [comment]
As a workaround, this script can be used:
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-features#http-api-url-discovery
