### ISSUE TITLE
Durable Function Activity exception stack trace not accurately reported to AI

### ISSUE THREAD

**Issue by jublair** [Azure/azure-functions-durable-extension#1157]
### Description
I have recently encountered a user error in one of my durable activity functions. While I was ultimately able to identify the root cause of the exception from the error message provided, the stack trace did not provide the line number on which the exception was thrown.

### Expected behavior
I expect the stack trace being logged on exception to include the line number of the exception.

### Actual behavior
Here is the exception logged to Application Insights:

Title | Description
-- | --
timestamp | 2020-01-10T21:30:42.2946948Z
problemId | System.FormatException at   FraudHunters.FileReader.AdlsStreamReader+<PullNewEntries>d__19.MoveNext
handledAt |  
type | System.FormatException
message |  
assembly | FraudHuntersFileReader, Version=1.0.0.0, Culture=neutral,   PublicKeyToken=null
method | FraudHunters.FileReader.AdlsStreamReader+<PullNewEntries>d__19.MoveNext
outerType | Microsoft.Azure.WebJobs.Host.FunctionInvocationException
outerMessage | Exception while executing function: PullNewEntries
outerAssembly | System.Private.CoreLib, Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e
outerMethod | System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
innermostType | System.FormatException
innermostMessage | String '' was not recognized as a valid DateTime.
innermostAssembly |  
innermostMethod |  
severityLevel | 3
details | ``[{"severityLevel":"Error","parsedStack":[{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":0,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host,   Version=3.0.15.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__19.MoveNext","level":1,"line":322,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":2,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":3,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":4,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","level":5,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host,   Version=3.0.15.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsyncCore>d__16.MoveNext","level":6,"line":117,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"}],"outerId":"0","message":"Exception   while executing function:   PullNewEntries","type":"Microsoft.Azure.WebJobs.Host.FunctionInvocationException","id":"43737118"},{"severityLevel":"Error","parsedStack":[**{"assembly":"FraudHuntersFileReader,   Version=1.0.0.0, Culture=neutral,   PublicKeyToken=null","method":"FraudHunters.FileReader.AdlsStreamReader+<PullNewEntries>d__19.MoveNext","level":0,"line":0}**,{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":1,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":2,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":3,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host,   Version=3.0.15.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2+<InvokeAsync>d__10.MoveNext","level":4,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":5,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":6,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":7,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter`1.GetResult","level":8,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host,   Version=3.0.15.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<InvokeAsync>d__27.MoveNext","level":9,"line":585,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":10,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":11,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":12,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.GetResult","level":13,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host,   Version=3.0.15.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithWatchersAsync>d__26.MoveNext","level":14,"line":532,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":15,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":16,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":17,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.GetResult","level":18,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host,   Version=3.0.15.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__25.MoveNext","level":19,"line":468,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":20,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess","level":21,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification","level":22,"line":0},{"assembly":"System.Private.CoreLib,   Version=4.0.0.0, Culture=neutral,   PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.CompilerServices.TaskAwaiter.GetResult","level":23,"line":0},{"assembly":"Microsoft.Azure.WebJobs.Host,   Version=3.0.15.0, Culture=neutral,   PublicKeyToken=31bf3856ad364e35","method":"Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__19.MoveNext","level":24,"line":278,"fileName":"C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs"}],"outerId":"43737118","message":"String   '' was not recognized as a valid   DateTime.","type":"System.FormatException","id":"62354235"}]``
itemType | exception
customDimensions | {"HostInstanceId":"5641a49b-008d-471a-9295-afa366731e65","InvocationId":"0d1d2a1a-7210-4952-998b-f555ecdb7ba6","ProcessId":"14808","Category":"Host.Results","LogLevel":"Error","prop__InvocationId":"0d1d2a1a-7210-4952-998b-f555ecdb7ba6","prop__Succeeded":"False","prop__StartTime":"2020-01-10T21:30:41.2500000Z","prop__FullName":"PullNewEntries","prop__Duration":"00:00:01.0437101","prop__EndTime":"2020-01-10T21:30:42.2940000Z","prop__Name":"PullNewEntries"}
customMeasurements | null
operation_Name | PullNewEntries
operation_Id | f20074d95c1e8048844c8cd2e9f132ed
operation_ParentId | 8a8d8bb9a85da44a
operation_SyntheticSource |  
session_Id |  
user_Id |  
user_AuthenticatedId |  
user_AccountId |  
application_Version |  
client_Type | PC
client_Model |  
client_OS |  
client_IP | 0.0.0.0
client_City |  
client_StateOrProvince |  
client_CountryOrRegion |  
client_Browser |  
cloud_RoleName | fraudhuntersfilereader-test
cloud_RoleInstance | 96fb5dcc80475275582f7001fcfc3411c0bd963f5c09352e5e0c2cabf8eb3d45
appId | d9ddb0ee-e302-4928-b1fe-34ab4d5c5993
appName | FraudHuntersApplicationInsightsTest
iKey | 40275346-5cce-45e8-9e7d-597100ca9c8b
sdkVersion | azurefunctions: 2.0.12888.0
itemId | 76147041-33f0-11ea-bb94-87fcbce79495
itemCount | 3

The stack trace line of interest does not include a valid line number:

**{"assembly":"FraudHuntersFileReader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","method":"FraudHunters.FileReader.AdlsStreamReader+<PullNewEntries>d__19.MoveNext","level":0,"line":0}**

### Relevant source code snippets
```csharp
[FunctionName(nameof(PullNewEntries))]
public static async Task<(int linesRead, StringBuilder lineBuffer, long filePosition)>
    PullNewEntries([ActivityTrigger] IDurableActivityContext context, ILogger log)
{
    ...
    // Exception thrown on the line below
    DateTime entryDate = DateTime.Parse(entryDateString, CultureInfo.InvariantCulture);
    ...
}
```

### Known workarounds
I've used alternative debug methods such as log-and-test for the time being.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.1.1
- **Azure Functions runtime version (1.0 or 2.0)**: v2.x
- **Programming language used**: C#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 1/10/2020, 9:06:43.580 PM (UTC)
- **Function App name**: fraudhuntersfilereader-test
- **Function name(s)**: PullNewEntries
- **Azure region**: East US 2
- **Orchestration instance ID(s)**:
- **Azure storage account name**: fraudhunterswebjobtest

**Comment by cgillum** [comment]
Hi @jublair. In order for the .NET runtime to produce line numbers will callstacks, you need to publish your debug symbols alongside your application binaries. In most cases, compiling and releasing in Debug mode will do this for you. This is a general .NET behavior and not specific to Azure Functions. More discussion of this can be found here: https://stackoverflow.com/a/3791997/2069

**Comment by jublair** [comment]
@cgillum Makes sense, thanks!!
