### ISSUE TITLE
Orchestration seems to be Stuck

### ISSUE THREAD

**Issue by kijujjav** [Azure/azure-functions-durable-extension#1158]
### Description
> Stuck orchestration , id : cefe9533b0114fb78e3694927861ace8
sub-orch id's : bcbeda6e28764bf286cf7d570f9a699a:6, 1f8f04fc1d4347108fe9b3732f184b1c:2

### Expected behavior
Continue with next steps in code

### Actual behavior
> not sure what is happening, seems to be stuck 

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 1.8.3
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 12/4/2019, 6:24:16.768 PM
- **Function App name**: NetAssistStatefulWorkflow
- **Function name(s)**: GetLinkHistoryForPastMonth
- **Azure region**: West US
- **Orchestration instance ID(s)**: cefe9533b0114fb78e3694927861ace8
- **Azure storage account name**: netassistdurable

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by amdeel** [comment]
Hello @kijujjav, sorry for the delayed response. We were seeing some issues with orchestrations getting stuck relating to large messages. This has been fixed in our latest v1 and v2 releases. Try updating to 1.8.5 or 2.1.1 and let us know if you see this issue again.

**Comment by kijujjav** [comment]
Thanks. I will upgrade

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by amdeel** [comment]
@kijujjav For now, I'm going to close the issue. Let us know if you run into this same problem again; if so, feel free to reopen this issue.

**Comment by kijujjav** [comment]
Sure. Thank you
