### ISSUE TITLE
Reduce size of statusQueryGetUri webhook response

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-durable-extension#1159]
**Is your feature request related to a problem? Please describe.**
Sometimes a large input is passed to an orchestrator. If a client starts an orchestration via HTTP and is polling for status, the response payload could be quite large.

**Describe the solution you'd like**
Add a query string that, when enabled, returns a smaller payload or removes the payload completely. Would be great if this were the default for the URL returned in the `Location` header but this would be a breaking change.

**Describe alternatives you've considered**
Write custom code instead of using CreateCheckStatusResponse and the built-in HTTP APIs.

**Comment by amdeel** [comment]
We actually [already](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-instance-status) allow users to specify if they want to showInput in the query string for querying single instances and all instances.

It's possible I'm misunderstanding the suggestion. Do you have more details you can provide about your enhancement idea?

**Comment by anthonychu** [comment]
Looks like that was added in 2.1.0 and I missed it. That's great. Thanks!
