### ISSUE TITLE
Creation of orchestrator fails when HTTP body is transfered

### ISSUE THREAD

**Issue by lechnerc77** [Azure/azure-functions-durable-extension#1160]
### Description
A durable function shall be called via an HTTP trigger. The HTTP request contains data in a JSON body. This fails when using the durable extension instead of the extension bundle. However when the function should support durable entities the extension bundle cannot be used.

### Expected behavior
The data from the JSON of the request body should be available in the orchestrator function as `context.bindingData.input`

### Actual behavior
The execution of the HTTP call fails in the durableClient function when executing the `client.startNew`
The error message is: 
```
Executed 'Functions.DurableFunctionsHttpStart' (Failed, Id=8626ff18-a7b1-49c3-8b47-ec8a2c43dd5e)
System.Private.CoreLib: Exception while executing function: Functions.DurableFunctionsHttpStart. System.Private.CoreLib: Result: Failure
Exception: Error: {"Message":"Something went wrong while processing your request","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 666\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 206"}
Stack: Error: {"Message":"Something went wrong while processing your request","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 666\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 206"}
    at DurableOrchestrationClient.<anonymous> (C:\Users\xxx\sandbox\AzureDurableTestSimple\node_modules\durable-functions\lib\src\durableorchestrationclient.js:340:43)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\xxx\sandbox\AzureDurableTestSimple\node_modules\durable-functions\lib\src\durableorchestrationclient.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7).
```

### Relevant source code snippets
See GitHub repository: [https://github.com/lechnerc77/AzureDurableInputIssue](https://github.com/lechnerc77/AzureDurableInputIssue)
Branch "[master](https://github.com/lechnerc77/AzureDurableInputIssue/tree/master)": Correct behavior with ExtensionBundle
Branch "[plainextension](https://github.com/lechnerc77/AzureDurableInputIssue/tree/plainextension)": Code with  plain extension

See README.md on branch master for details to reproduce the behavior

### Known workarounds
Under the constraint that a durable entity shall be used there is nor way to mitigate the behavior

### App Details
**Node Version:**: 10.18.0
**Durable Functions extension version**: 2.1.1/2.1.0
**Azure Functions runtime version (1.0 or 2.0)**:  2.0
**Programming language used**: TypeScript

**Comment by pajzo** [comment]
Looks to be similar with the issue is reported yesterday #1156

**Comment by lechnerc77** [comment]
Your are right. I missed that one. WIl put a comment in [#1156](https://github.com/Azure/azure-functions-durable-extension/issues/1156).

**Comment by cgillum** [comment]
We're currently investigating this issue. We'll follow up on #1156.
