### ISSUE TITLE
incorrect queue picked when a variable is used for hubName in host.json

### ISSUE THREAD

**Issue by Infionion** [Azure/azure-functions-durable-extension#1163]
### Description
When using a variable to set the hubName in host.json, i.e. with the %% as documented in: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs
2 sets of queues are created in storage. One with the name of the variable and one with the resolved value.
The second set of queues is created when an orchestration is started from a starter-function.
As a result, the orchestration is never started, as the process that's responsible for responding to the queues seems to be looking at the wrong queue.

### Expected behavior
When an orchestration is started, it is picked and executed.
Only the queue with a resolved variable is created.

### Actual behavior
The variableName is used for the second queue, in stead of the value (that's set in local.settings.json)

### Relevant source code snippets
```csharp

host.json:
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "%VariableName%",
      "storageProvider": {
        "connectionStringName": "MyDurableFnStorage",
        "trackingStoreConnectionStringName": "MyDurableFnStorage",
        "trackingStoreNamePrefix": "variablevalue"
      }
    }
  }
}

local.settings.json, under Values:
"VariableName": "variablevalue",
"MyDurableFnStorage": "AccountName=devstoreaccount1 ...."

Starter-function:
   public async Task<IActionResult> SomeStarterAsync(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = DeviceAllocationStarterFunction)]HttpRequestMessage req,
            [DurableClientAttribute(TaskHub = "%VariableName%")]IDurableOrchestrationClient starter,
            ILogger log)
```

Orchestration-function:
 public async Task SomeOrchestratorAsync(
            [OrchestrationTrigger(Orchestration = "SomeOrchestration")] IDurableOrchestrationContext context,
            ILogger logger)
        {
}
### Known workarounds
> Provide a description of any known workarounds you used.

### App Details
Durable Functions extension: v2.1.1
Azure functions runtime 2.0
language: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.
At function startup:
The queues:
![image](https://user-images.githubusercontent.com/6482598/72245420-d2022300-35f0-11ea-9474-70f5279c1acd.png)

The tables:
![image](https://user-images.githubusercontent.com/6482598/72245545-20172680-35f1-11ea-9b11-fd75424306d2.png)

After Orchestration started, the variablename queues are added (tables are unaltered):
![image](https://user-images.githubusercontent.com/6482598/72245768-92880680-35f1-11ea-971e-3d77cf8c0b47.png)

As a result, the orchestration is never picked.

they are added to the correct queue though:
![image](https://user-images.githubusercontent.com/6482598/72245822-b21f2f00-35f1-11ea-814a-4a7d26b399dd.png)

When in host.json:    
"hubName": "%VariableName%", 
is replaced with:
"hubName": "variablevalue", (so the resolved value) 

the orchestration is dequeued and proccessed.

**Comment by amdeel** [comment]
Hey @Infionion, we aren't able to reproduce this issue. Could you provide us your AppName?

**Comment by cgillum** [comment]
@Infionion I just now noticed that you're also using `%VariableName%` in your `SomeStarterAsync` function.

```csharp
public async Task<IActionResult> SomeStarterAsync(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = DeviceAllocationStarterFunction)]HttpRequestMessage req,
    [DurableClientAttribute(TaskHub = "%VariableName%")]IDurableOrchestrationClient starter,
    ILogger log)
```

Does it work correctly if you remove the `TaskHub = "%VariableName%"` attribute property assignment in your code? This is actually redundant because we use the value in host.json by default. For example:

```csharp
[DurableClientAttribute] IDurableOrchestrationClient starter,
```
