### ISSUE TITLE
Durable entity task instance remains in "running" runtimeStatus

### ISSUE THREAD

**Issue by bragma** [Azure/azure-functions-durable-extension#1165]
### Description
I have a simple chain of functions: a durable client gets data from a storage queue and starts an orchestration that calls a method on a durable entity. After the orchestration terminates correctly, I've noticed that the durable entity task remains in "running" state instead.

I am using DurableTask 2.1.1 on .NET Core 2.2

The durable entity code is similar to this (removed some parts to simplify):

```csharp
    [JsonObject(MemberSerialization.OptIn)]
    public class TrainingGoalData : ITrainingGoalData
    {
        [JsonProperty]
        public int Sessions { get; set; }

        public Task<TrainingGoalData> Get()
        {
            return Task.FromResult(this);
        }

        [FunctionName(nameof(TrainingGoalData))]
        public static Task HandleEntityOperation([EntityTrigger] IDurableEntityContext ctx)
            => ctx.DispatchAsync<TrainingGoalData>();
    }
}
```

The orchestrator code calling the entity is:

```csharp
                var data = await context
                    .CreateEntityProxy<ITrainingGoalData>(new EntityId(nameof(TrainingGoalData), $"U{training.UserId}-G{goal.TrainingGoalId}"))
                    .Get();
```

I am running the functions in Visual Studio. After execution, if I try:

GET http://0.0.0.0:7071/runtime/webhooks/durabletask/instances

The result is (just relevant parts copied):

```
[
    {
        "name": "@traininggoaldata@U29763-G1",
        "instanceId": "@traininggoaldata@U29763-G1",
        "runtimeStatus": "Running",
        "input": {
            "exists": true,
            "state": "{\"Sessions\":0}",
            "sorter": {
                "ReceivedFromInstance": {
                    "caf2ee803bbd4907bcf3c421e02d5ec2": {
                        "Last": "2020-01-14T22:52:21.9888836Z"
                    }
                },
                "ReceiveHorizon": "2020-01-14T22:22:21.9888836Z"
            }
        },
        "customStatus": {
            "entityExists": true
        },
        "output": null,
        "createdTime": "2020-01-14T22:52:22Z",
        "lastUpdatedTime": "2020-01-14T22:52:22Z"
    },
    {
        "name": "ProcessGoal",
        "instanceId": "caf2ee803bbd4907bcf3c421e02d5ec2",
        "runtimeStatus": "Completed",
...
```

The orchestrator status is "Completed" while the entity is still running. I am not sure it is normal. Am I doing something wrong of there is something I should check?

Thanks!

**Comment by sebastianburckhardt** [comment]
No worries, @bragma: this is the normal and expected behavior. Our implementation of entities uses eternal orchestrations, so they remain in `Running` state forever once started.

**Comment by bragma** [comment]
@sebastianburckhardt thanks a lot for the clarification and keep up the great job!

**Comment by JoeBrockhaus** [comment]
@bragma I came across this behavior today and am curious for the implications of this on Consumption Plan usage when deployed to Azure. Do these 'running' entities incur usage, or are they effectively suspended? Is it best-practice to eventually 'clean up' outstanding entities?

I'm also not sure if this is the same question [asked here](https://github.com/Azure/azure-functions-durable-extension/issues/901), where it was noted the behavior stopped occurring after a certain version.

**Comment by sebastianburckhardt** [comment]
> Do these 'running' entities incur usage, or are they effectively suspended?

They are effectively suspended. Entities are scheduled for execution only when there are pending messages in the control queue. 

> Is it best-practice to eventually 'clean up' outstanding entities?

Only if that number is expected to grow significantly over time and/or if you would like to reclaim the storage used by the entities.

**Comment by theplankmeister** [comment]
> No worries, @bragma: this is the normal and expected behavior. Our implementation of entities uses eternal orchestrations, so they remain in `Running` state forever once started.

@sebastianburckhardt Is this behaviour documented anywhere? I've spent longer than I would have liked on this issue, until I stumbled across your comment. I haven't seen it mentioned anywhere that entity tasks remain in the running state, and at this point, after reading so many articles, blog posts, examples, samples, source code, etc, I can't see the wood for the trees...

**Comment by marius-stanescu** [comment]
I am also interested in the answer to the question above. Are durable entities still implemented using eternal orchestrators, making them remain in the `Running` state forever?

**Comment by cgillum** [comment]
@marius-stanescu the answer is a bit complicated because of some internal refactoring we've done with entities over the past year or so. In some cases, yes, entities are a layer on top of eternal orchestrations. In some cases, they are mostly distinct from orchestrations. We don't currently document this since it's supposed to be an internal implementation detail. Let us know if/how this is an important detail to know about so that we can identify appropriate solutions.

**Comment by marius-stanescu** [comment]
We have a background process that periodically checks for orchestrators that may be running longer than expected, potentially indicating that they are stuck. If an orchestrator has been running for an unusually long time, this process flags it, allowing us to investigate. The problem is that the durable entities we are using are identified by this process as being ”potentially stuck.”

**Comment by cgillum** [comment]
@marius-stanescu unfortunately, the best I can suggest right now is to filter out entities from your background process checking.
