### ISSUE TITLE
[minor bug] Error message not accurate

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1175]
Durable Functions 2.1.1 (possibly others as well, but not checked)

---

I had a blip when raising an event to an orchestration instance which already had a `runtimeStatus` of  `complete`.

the `Exception` message looks incorrect

```
Cannot raise event xctfc3m1 for orchestration instance 338d621e-6d99-42e9-ba09-173baf4ed39d because instance is in {"status":"Completed","user":"****","use****":"False"} state
```

It looks like the error message is pulling in my `customStatus` rather than the `runtimeStatus`. 

Given that the `customStatus` is entirely optional, it doesn't really make sense to use the `customStatus` in the context of the error message. I think the actual behaviour here should be to use the `runtimeStatus`

https://github.com/Azure/azure-functions-durable-extension/blob/c2b8fa74c6c171e0d3f4b4cca19c22092ab78744/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L507

**Comment by f2bo** [comment]
I just saw the same using `TerminateAsync` when I mistakenly attempted to cancel an orchestration that had already completed and had no custom status.

``` 
Exception while executing function: Terminate. Microsoft.Azure.WebJobs.Extensions.DurableTask: Cannot terminate the orchestration instance 3b38c2a50e674de5914d4e06c3d090de because instance is in  state.
```
