### ISSUE TITLE
Extreme latency between activity function call and invocation

### ISSUE THREAD

**Issue by jonny-powell** [Azure/azure-functions-durable-extension#1176]
### Description
Witnessed >15min delay between .CallActivityAsync() and named activity function being invoked. At the time, there was relatively little activity overall in the Function App, so it doesn't seem capacity related. The behaviour began following a usual overnight lull in activity in the app; the previous day no signs of the slowdown were present, and no code or configuration changes were deployed overnight.

### Expected behavior
Sub 1 second delay between .CallActivityAsync() and the corresponding activity beginning to execute.

### Actual behavior
>15 minute delay between .CallActivityAsync() and the corresponding activity executing. This was not limited to one orchestration or activity function, but affected all Functions in the App.

### Relevant source code snippets
```csharp
var purchaseOrderData = await context.CallActivityAsync<PurchaseOrdersModel>(GetPurchaseOrderData.FunctionName, (purchaseOrderID, cID));
```
```csharp
public async Task<PurchaseOrdersModel> Run([ActivityTrigger] DurableActivityContext context)
{
    var (id, correlationID) = context.GetInput<(string, string)>();
    LogContext.PushProperty("CorrelationID", correlationID);
    _logger.Debug("Activities: Get Purchase Order Data: Running.");
    var data = await CallPurchaseOrderDataHttpEndpoint(id);
    return data;
}
```

### Known workarounds
Stop the Function App, provision a new Storage Account, point the Function App at the new storage account, start the Function App.

### App Details

- **Durable Functions extension version**: v1.8.4
- **Azure Functions runtime version**: 2.0
- **Programming language used**: C# (8.0)

- **Timeframe issue observed**: 21/01/2020: 7.30am onwards
- **Function App name**: jla-int-prod-ukw-io-fnc
- **Azure region**: UK West
- **Azure storage account name**: jlaintprodukwiostg

**Comment by amdeel** [comment]
Hello, @jonny-powell, I investigated this issue and found that the activity function your orchestrator was attempting to invoke was set to disabled (in the portal). This caused the orchestrator to get in a bad state where it continued to attempt to process the activity. I've opened an issue for this here to find a way to more gracefully handle this case (https://github.com/Azure/azure-functions-durable-extension/issues/1190).
