### ISSUE TITLE
Fix Functions V3 async deserialization in Durable extension V1

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-durable-extension#1178]
- [x] Port [this fix](https://github.com/Azure/azure-functions-durable-extension/pull/1085) to V1. Anyone using bundles V1 (which will be the default for some time) will still be using Durable V1. 
- [x] Release an updated extension bundle that contains this fix.

**Comment by ConnorMcMahon** [comment]
@soninaren, just to understand from our conversation today, the v1 extension bundle is primed for once the release pipeline is ready to deploy, right?

**Comment by soninaren** [comment]
@ConnorMcMahon we still have OGF's pending. We can deploy once the release is unblocked and we get the go ahead. The release pipeline is set up to deploy to prod no additional work needed there.

**Comment by ConnorMcMahon** [comment]
This has been resolved for a while now.
