### ISSUE TITLE
Ensure traces are captured on Linux

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-durable-extension#1181]
In the meantime, we should recommend Windows for Durable Functions. And this is a blocker for Python Durable Functions GA.

/cc @cgillum @anirudhgarg @priyaananthasankar

**Comment by ConnorMcMahon** [comment]
@anthonychu, is this for dedicated Linux, consumption Linux, or both?

**Comment by anirudhgarg** [comment]
For consumption Linux as far as I know.

**Comment by anthonychu** [comment]
I think we need to check dedicated, consumption, and premium.

**Comment by davidmrdavid** [comment]
Closing as this work was completed for the DF Python GA 🎉
