### ISSUE TITLE
Duplicated Activity Function Scheduled

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-durable-extension#1184]
### Description
We are seeing that an activity is being processed twice in one of our workflows. It looks like activity succeeds and then 6mins later succeeds again for the same `TaskScheduleId`.

We are paging through some data in cosmosDB using a continuation token, each page is processed by an ActivityFunction. What we are seeing is that a page was processed twice. You can verify this by looking into the History Table

Intial Result
![image](https://user-images.githubusercontent.com/8879065/73337338-cb281100-427c-11ea-87e2-e13eb2069882.png)

Subsequent duplicate Result
![image](https://user-images.githubusercontent.com/8879065/73337396-eabf3980-427c-11ea-9427-1388f7c7b048.png)

### Known workarounds
Either make the method idempotent or have some sort of locking safe guard to prevent duplicates.

### App Details
```<TargetFramework>netcoreapp2.2</TargetFramework>
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.8.3" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.8" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.29" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.8" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
```

*Azure Functions Runtime 2.0
*C#
*VS 2019

### If deployed to Azure

- **Timeframe issue observed**: 2020-01-28T16:37:57.486Z
- **Function App name**:  durableprocessor-prod
- **Function name(s)**:    WorkflowOrchestrator (ParentOrchestrator), ServiceOrchestrator (suborchestrator), CreateTransactionsAndQueue (Activity)
- **Azure region**: East US
- **Orchestration instance ID(s)**: 
*ParentOrchestrationId: af662b03-f26a-41de-8e43-7d10eb38c45e
*SubOrchestrationId in Question:  ac3c83b686a04f609ea4dbd3f9ec4a75:2
- **Azure storage account name**: durableprocessorprod

I suspect this may be related to #382 but cannot be sure.

**Comment by olitomlinson** [comment]
@gorillapower Is it possible that your cosmos query is taking over 5 minutes to run in the activity?

I believe that an activity has approx 5 minutes to execute to completion, until the activity looses its lock and becomes available for reprocessing. If this was to occur your activity would be started again.

**Comment by cgillum** [comment]
If an activity function takes more than 5 minutes to complete, we should be renewing the visibility timeout of the message in the background, so I wouldn't _expect_ that to be the case (assuming that behavior is working correctly).

**Comment by olitomlinson** [comment]
Sorry I forgot to say that I had an assumption that this was running on consumption plan, which has a 5 minute duration limit in the default configuration. Hence the activity shutting down loosing its lock and starting again.

**Comment by gorillapower** [comment]
@olitomlinson well noted and thanks for your feedback. I should have stipulated what plan I was using, that function is using consumption plan and I noticed there is no `host.json` override on the `functionTimeout`, so yes it should be timing-out after 5mins, which falls in line with the timing we are seeing, but I would have thought that a timeout exception would have been thrown in that case?

**Comment by olitomlinson** [comment]
Yeah, If you’re hooked up to App Insights you should see very clearly If the operation is completing successfully.

If it is completing successfully then, I’m out of ideas. 

Either way, the Team are on it 👍🏻

**Comment by amdeel** [comment]
Hey @gorillapower I investigated your issue and found that this is actually a known issue (https://github.com/Azure/durabletask/issues/280) involving a race condition with messages being renewed and deleted at the same time. Every 30 seconds we renew the message, so if your function takes 30 seconds to complete you're likely to run into this issue.

Thanks for bringing it to our attention.
