### ISSUE TITLE
Documentation of GET orchestration status API is incorrect for Durable 2.x

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1186]
### Description
As a breaking change in Durable 2.x, we changed the default behavior of the GET single orchestration instance status API to return 200 when the orchestration failed. The [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#response-1) does not reflect this.

We should additionally add documentation for the `returnInternalServerErrorOnFailure` query string parameter that is used to control this behavior.

**Comment by cgillum** [comment]
Thanks for opening this. I've opened a corresponding bug in the docs repo. I think that will be a better place to track docs issues: https://github.com/MicrosoftDocs/azure-docs/issues/47101
