### ISSUE TITLE
Azure Service bus queue output bindings

### ISSUE THREAD

**Issue by fisapras** [Azure/azure-functions-durable-extension#1188]
I am calling an orchestator which calls a sub-orchestrator 142 times (test payload) and waits for the all the sub-orchestrator calls to finish to do post processing. The sub-orchestrator in turn calls an activity function which queues the request to the Service Bus queue and wait for the external event.  Here is the code for the activity function,
       
        [FunctionName("QueueRequest")]
        [return: ServiceBus("'%ServiceRequestQueue'%", Connection = "ServiceBusConnection")]
        public static string QueueRequest([ActivityTrigger] Request request)
        {
            var settings = new JsonSerializerSettings
            {
                ContractResolver = new ContractResolver
                {
                    NamingStrategy = new CamelCaseNamingStrategy()
                }
            };
            return JsonConvert.SerializeObject(request, settings);
        }

This is how i invoke the Activity Function from my sub orchestraror

            await context.CallActivityAsync<string>("QueueRequest", calculationRequest);

After the first call to the Orchestrator the queue correctly shows 142 items queued. However the subsequent calls queue more than 142 messages. However when I change the Activity function to use QueueClient to send the messages, the queued messages match what is to be expected. This leads me to believe that this is not a logic bug but there is bug when using the binding expression to output to the service bus queue.  

This is the Activity Function with Queue Client.

        [FunctionName("QueueRequest")]
        public static Task QueueRequest([ActivityTrigger] Request request)
        {
            var settings = new JsonSerializerSettings
            {
                ContractResolver = new ContractResolver
                {
                    NamingStrategy = new CamelCaseNamingStrategy()
                }
            };

            var message = new Message
            {
                MessageId = calculationRequest.InstanceId,
                Body = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(request, settings))
            };

            var client = new QueueClient(connectionString, queueName);
            await client.SendAsync(message);
        }

This is how i invoke the Activity Function from my sub orchestraror when using QueueClient

await context.CallActivityAsync("QueueRequest", calculationRequest);

Can somebody explain why do I see more than expected queue messages when using Service Bus Queue output bindings?

**Comment by ConnorMcMahon** [comment]
I vaguely remember us having a limitation on using `yield` in C# orchestrators, but I can't find this documented anywhere. I think we would have to look at your orchestrator example before and after to diagnose it further.

@cgillum, does using iterator methods in an orchestrator sound like it could cause unexpected behavior in orchestrators?

**Comment by cgillum** [comment]
The `yield` keyword itself is just syntactic sugar for implementing an `IEnumerable`. That by itself should not cause any problems. That said, I have seen issues when doing things like calling `Task.WhenAll(...)` or `Task.WhenAny(...)` and passing a lazily evaluated `IEnumerable<Task>` as the argument (a `yield` function would produce something similar). In those cases, the workaround for me was to convert the `IEnumerable<Task>` into `List<Task>` or `Task[]` and then pass that to `Task.WhenAll(...)` and `Task.WhenAny(...)`.

**Comment by ConnorMcMahon** [comment]
@fisapras can you give us more details as to how you are using `yield`?
