### ISSUE TITLE
Is ContinueWith supported on ctx.CallSubOrchestratorAsync?

### ISSUE THREAD

**Issue by andreasbotsikas** [Azure/azure-functions-durable-extension#119]
Happy new year! 

I noticed that an orchestration would stuck, with no errors in the function log, if I use the following code 
```
// processingItemList is a list of items being processed
var taskList= new List<Task>();
foreach(var currentItem in processingItemList){
	var task = ctx.CallSubOrchestratorAsync<Guid>(SubOrchestrator.FunctionName, currentItem).ContinueWith(i=> currentItem.GuidProperty = i.Result) ;
	taskList.Add(task)
}
await Task.WhenAll(taskList);
```
I am passing to the SubOrchestrator the currentItem object, which is being processed and then try to update a property of that object with the result of the sub orchestrator. 
I ended up changing the codebase to run the tasks and then after the Task.WhenAll, update the objects, which seems to be working fine.

Is this a known limitation?

Running in West Europe under Consumption plan.

**Comment by cgillum** [comment]
I tried this out myself and it seems to work fine. Here is the orchestration I created for testing:

```csharp
[FunctionName("ContinueWith")]
public static async Task Run(
    [OrchestrationTrigger] DurableOrchestrationContext ctx,
    TraceWriter log)
{
    await ctx.CallActivityAsync("Sleep", 3)
        .ContinueWith(t =>
        {
            if (!ctx.IsReplaying) log.Warning("Done sleeping");
        });

    await ctx.CallActivityAsync("Sleep", 3)
        .ContinueWith(t =>
        {
            if (!ctx.IsReplaying) log.Warning("Done sleeping");
        });

    log.Warning("Done!");
}
```
The orchestration runs to completion and I see the outputs I expect.
