### ISSUE TITLE
Orchestration instances fire multiple times.

### ISSUE THREAD

**Issue by bobbytreed** [Azure/azure-functions-durable-extension#1194]
### Description

I have a SINGLETON instance using a leaseblob for checking that starts orchestration instances in a single manner which fire a service bus message and wait for an event.

### Expected behavior

Only one service bus messages fires in singleton mode.

### Actual behavior

I occasionally see instances popping up and attempting to perform there functions (firing messages).  This is especially concerning since my code terminates ALL instances before first execution.

### Relevant source code snippets
This is the try/catch/try/catch code I have had to use to make sure I can actually start and debug an orchestration instance.
```csharp
 try
{
     await starter.StartNewAsync("ProcessEvent", instanceid, message);
     return;
}
catch (Exception outer)
{
     // Get the current count of running instances that we supposedly terminated.
     int count = await starter.TerminateInstances();
     try
     {
          await starter.StartNewAsync("ProcessEvent", instanceid, message);
          return;
     }
     catch (Exception oncemore)
     {
          instanceid = $"{count + 1}_" + instanceid;
          await starter.StartNewAsync("ProcessEvent", instanceid, message);
          return;
     }
}
```

Running locally

**Comment by ConnorMcMahon** [comment]
Fixed in https://github.com/Azure/durabletask/pull/528, shipping with v2.5.0
