### ISSUE TITLE
Cannot raise event for orchestration instance, null state

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-functions-durable-extension#1196]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

We currently have an orchestration that performs an `WaitForExternalEvent` and waits for a response via a ServiceBus queue that then triggers `RaiseEventAsync`. Upon this code being called, we seem to have an `InvalidOperationException` being indicating that we can't raise this event, but the state of the orchestration doesn't get printed. We aren't really sure where to go with this! This piece of code seems to work for a number of other scenarios but seemed to fail on over the weekend.

### Expected behavior
> A clear and concise description of what you expected to happen.

Orchestration is able to raise event to wake up the waiting orchestration, or at the very least, a message to explain why this cannot be done

### Actual behavior
> A clear and concise description of what actually happened.

Exception is thrown:
```
Exception while executing function: InvokeDeviceExtractProcessingResponse Cannot raise event DeviceExtractProcessing for orchestration instance 3da5232876ef4cc4939f094fd6320a52:2 because instance is in  state 
```
Note the message doesn't seem to populate the 'state' variable correctly, so I believe its printing out `null` for that resolution.

### Relevant source code snippets
```csharp
// calling Orchestration code
                // Await responses for completion of external tasks
                var externalDeviceExtractTask = context.WaitForExternalEvent<ExternalEvent>(Constants.DeviceExtractProcessingEvent,
                    ExternalProcessingTimeout(parseResult));

// ServiceBus trigger which is attempting to raise the event when it receives a message off the queue
        [FunctionName("InvokeDeviceExtractProcessingResponse")]
        public static async Task InvokeDeviceExtractProcessingResponse(
            [ServiceBusTrigger(ServiceBusQueueNameConstants.ProcessDeviceExtractResponseQueueName, Connection = "ServiceBusConnection")]
            ExternalEvent message,
            [DurableClient] IDurableOrchestrationClient client,
            ILogger log)
        {
            log.LogInformation($"{ServiceBusQueueNameConstants.ProcessDeviceExtractResponseQueueName} message received for instance {message.InstanceId}");

            await client.RaiseEventAsync(message.InstanceId, Constants.DeviceExtractProcessingEvent, message);
        }
```

### Known workarounds
> Provide a description of any known workarounds you used.

None so far

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.1.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/4549796/73621571-8f70bb00-4671-11ea-8e07-44ca5f180cfc.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 2020-01-31T03:30:51.2453871Z
- **Function App name**: soze-wapol-managementfunctions
- **Function name(s)**: ProcessDeviceExtractOrchestrator, InvokeDeviceExtractProcessingResponse
- **Azure region**: australiaeast
- **Orchestration instance ID(s)**: 3da5232876ef4cc4939f094fd6320a52:2.
- **Azure storage account name**: sozewapolmgt

OperationID trace in Application Insights: f75dd92785c08c4b880f8ed6a1d8dbf2

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by PiotrPerak** [comment]
I also saw this error today.

**Comment by ConnorMcMahon** [comment]
I think Amanda's fix [here](https://github.com/Azure/azure-functions-durable-extension/pull/1198) actually already fixed this. It turns out we were using CustomStatus instead of Status.

**Comment by wahyuen** [comment]
@ConnorMcMahon Good to know there is a fix in progress for resolving the status. 

Is there any indication or other known issue that might point as to 'why' this is even ocurring to start off with (ie. why DF thinks there is an orchestration in a state it cannot raise an event for?) That is our larger concern as it appears to be a sporadic occurrence for us which then plays havoc which our message processing.

**Comment by PiotrPerak** [comment]
@wahuyen I see this issue only locally (so far) when I run app under debugger and just stop it and later try to run again. So looks to me like hard shutdown is not updating some state.

**Comment by wahyuen** [comment]
@PiotrPerak unfortunately, we care seeing this in our production environment :/ We can run the exact same workload through and sometimes it works, sometimes we get this error :(

**Comment by ConnorMcMahon** [comment]
@wahyuen 

This error comes up when your orchestration instance is in the `Completed`, `Failed`, `Canceled` or `Terminated` state. You could catch this exception and query the instance to see what state it is. 

At that point it is a matter of figuring out if that is the expected state of your orchestration, and if not, how your orchestration got into that state.
