### ISSUE TITLE
Starting an orchestration that is already started

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1203]
DF 1.8.4 
Consumption plan
UK South

---

Not entirely sure whats happened here but it looks like an orchestration was allowed to start again while it was already running. I didn't think this was possible, could you take a look at what happened?

Instance started : `2020-02-01T00:01:48.284742Z`
instance started again : `2020-02-01T00:02:20.1960877Z`

Looking at the history there are 2 execution IDs logged `8191956ead1545dc831ae7567dcb63d1`
: `6ea0b8c622f9411fa761ff9e22eedfae`

---

I'm believe that the orchestration was started twice because we start the orchestration in a `ServiceBusTrigger` function, I believe the service bus message failed to Ack, so the message was retried and the code to start orchestration was executed again. 

However it is my understanding that you can't start an orchestration that is already in a `running` state? I expected it would throw an exception or just silently proceed without actually starting a new instance.

**Comment by amdeel** [comment]
We added a configurable option in our 2.0.0 release to prevent orchestration instances from being overridden in an already running state. We defaulted it to the new option, to make it a breaking change, but defaulting it to AnyState would prevent a breaking change for our V1 customers. Worth adding to our next release of V1? @cgillum @ConnorMcMahon

**Comment by olitomlinson** [comment]
Thanks @amdeel ! 

So it is intentional in v1.x that orchestrations can be restarted if they are already in a running state?

**Comment by cgillum** [comment]
@olitomlinson unfortunately yes, this is intentional (for v1.x). It started out as a bug, but then some users started relying on the behavior and we ended up not being able to fix it without it being a breaking change.

**Comment by olitomlinson** [comment]
@cgillum great thanks Chris. I suspect I'll be adopting v2 after more testing, so happy to not have it ported back to v1.

**Comment by amdeel** [comment]
@olitomlinson It actually is being ported to v1. I have a PR open for it right now. It will be a configurable option, so you'll have to specify that you want to change the behavior. (See above PR, if you're interested)
