### ISSUE TITLE
Durable Entities - Multithreaded execution detected when calling activity within an orchestrator

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-functions-durable-extension#1206]
### Description
First off, I'm not 100% sure this is a bug or simply just an anti pattern that we are using. Either way, would love some guidance on this issue.

We are currently using Durable Entities to track the state of long running processes along with some progress values. At certain intervals, we have the entity call out to an Orchestrator to then persist the current state into Table Storage so that the application front end can display this back to the end user. Traditionally, we have offloaded these calls to Table Storage into an activity as to not block the orchestrator thread, however, upon doing so, we seem to get a `InvalidOperationException: Multithreaded execution was detected` exception.

### Expected behavior
No exception thrown, and activity is invoked.

### Actual behavior
Exception thrown:
`Reason: System.InvalidOperationException: Multithreaded execution was detected. This can happen if the orchestrator function code awaits on a task that was not created by a DurableOrchestrationContext method.`

### Relevant source code snippets
Created repro project below. Please see comment on line 49

```csharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace DurableEntities
{
    public class Function1
    {
        [FunctionName("Function1")]
        public async Task Run([TimerTrigger("0 */5 * * * *", RunOnStartup = true)]TimerInfo myTimer, ILogger log, [DurableClient] IDurableOrchestrationClient client)
        {
            log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");

            await client.StartNewAsync("CounterOrchestration");
        }

        [FunctionName("CounterOrchestration")]
        public static async Task CounterOrchestration([OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
        {
            var entityId = new EntityId(nameof(Job), "MyJob");

            await context.CallEntityAsync(entityId, "Delete");

            for (var i = 0; i < 5; i++)
            {
                await context.CallEntityAsync(entityId, "Increment");
                var value = await context.CallEntityAsync<int>(entityId, "Get");

                if (!context.IsReplaying) log.LogWarning($"CounterOrchestration: {value}");
            }
        }

        [FunctionName("Output")]
        public async Task Output([OrchestrationTrigger] IDurableOrchestrationContext context, [DurableClient] IDurableEntityClient client, ILogger log)
        {
            log.LogWarning("Orchestration called...");

            var job = context.GetInput<EntityId>();

            var jobEntity = await client.ReadEntityStateAsync<Job>(job);

            log.LogWarning($"From orchestration: {jobEntity.EntityState.Counter}");

            // according to the stack trace, this is the offending line that is throwing the multithreaded exception
            await context.CallActivityAsync("TestActivity", jobEntity.EntityState.Counter);
        }

        [FunctionName("TestActivity")]
        public void TestActivity([ActivityTrigger] int value,  ILogger log)
        {
            log.LogWarning($"Inside TestActivity value: {value}");
        }
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class Job
    {
        [JsonProperty("value")]
        public int Counter { get; set; }

        public void Increment()
        {
            Counter++;

            if (Counter == 3)
            {
                Entity.Current.StartNewOrchestration("Output", Entity.Current.EntityId);
            }
        }

        public void Reset() => Counter = 0;

        public int Get() => Counter;

        public void Delete() => Entity.Current.DeleteState();

        [FunctionName(nameof(Job))]
        public static Task Run([EntityTrigger] IDurableEntityContext context)
        {
            if (!context.HasState)
            {
                context.SetState(new Job());
            }
            return context.DispatchAsync<Job>();
        }
    }
}

```

### Known workarounds
I currently wonder whether or not the real issue is that we are putting the `DurableClient` attribute into the signature of the orchestrator. Are we even allowed to do this??. We originally did this as we didn't see a way to 'Read' the state of the entity from an orchestrator (perhaps there is a different way to do this?) and we didn't want to have to make a call to each property via the proxy.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.1.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0.2
- **Programming language used**: C#

**Comment by sebastianburckhardt** [comment]
Sorry for the delayed response.

As you suspected correctly, putting the `DurableClient` into the signature of the orchestrator is an anti-pattern. The right way to read the entity state from the orchestrator is to call the 'Get' operation:
```csharp
var result = await context.CallEntityAsync(entityId, "Get");
```
Does that answer your question?

**Comment by wahyuen** [comment]
@sebastianburckhardt Perhaps I'm still missing something here. 

The 'Get' operation will only return something if that method exists on the DurableEntity correct? While I can do this to return specific 'properties' of that entity, what we are struggling with is to find a similar function to `client.ReadEntityStateAsync` that allows us to read the whole state of the entity.

To illustrate, if i extend the object from the above example to this

```csharp
    [JsonObject(MemberSerialization.OptIn)]
    public class Job
    {
        public string SomeOtherPropertyState { get; set; }

        public int PerhapsMoreState { get; set; }

        [JsonProperty("value")]
        public int Counter { get; set; }

        public void Increment()
        {
            Counter++;

            if (Counter == 3)
            {
                Entity.Current.StartNewOrchestration("Output", Entity.Current.EntityId);
            }
        }

        public void Reset() => Counter = 0;

        public int Get() => Counter;

        public void Delete() => Entity.Current.DeleteState();

        public void SetSomeOtherPropertyState(string value) => SomeOtherPropertyState = value;

        public string GetSomeOtherPropertyState() => SomeOtherPropertyState;

        public void SetPerhapsMoreState(int value) => PerhapsMoreState = value;

        public int GetPerhapsMoreState => PerhapsMoreState;

        [FunctionName(nameof(Job))]
        public static Task Run([EntityTrigger] IDurableEntityContext context)
        {
            if (!context.HasState)
            {
                context.SetState(new Job());
            }
            return context.DispatchAsync<Job>();
        }
    }
```

How would I retrieve all the state values from the entity without having to call the 'Getter' for each property? ie

```csharp
var counterValue = await context.CallEntityAsync<int>(entityId, "Get");
var someOtherPropertyState = await context.CallEntityAsync<string>(entityId, "GetSomeOtherPropertyState");
var perhapsMoreState = await context.CallEntityAsync<int>(entityId, "GetPerhapsMoreState");

```

Would this be a valid statement to make in a DurableEntity?

```csharp
public Job GetState() => this;
```

**Comment by anthonychu** [comment]
I think `public Job GetState() => this;` should work. Note that in your updated sample, the new attributes are missing `JsonProperty` attributes so their values won't be saved or returned; you'd just get the default values for those props.

Another potential problem with the original implementation, even if it didn't throw the multithreaded error, is you could get different values from the `client.ReadEntityStateAsync<Job>(job)` call during subsequent replays and you'll have non-deterministic errors.

**Comment by wahyuen** [comment]
@anthonychu Fair enough. Is there support for possibly passing the current state of the entity when calling the orchestration itself? By this I mean something along the lines of

```csharp
            if (Counter == 3)
            {
                Entity.Current.StartNewOrchestration("Output", Entity.Current.EntityId);
            }

// to something perhaps like....
            if (Counter == 3)
            {
                Entity.Current.StartNewOrchestration("Output", this);
            }
```

Bit unsure what we are allowed to pass through as the parameter...

**Comment by anthonychu** [comment]
@wahyuen You should be able to pass anything that's serializable by JSON.NET, so either of those should work.
