### ISSUE TITLE
Release Notes for 1.8.4 and 1.8.5

### ISSUE THREAD

**Issue by dsm0880** [Azure/azure-functions-durable-extension#1211]
### Description
Please provide the release notes for 1.8.4 and 1.8.5

### Expected behavior
Release notes with every release

### Actual behavior
No release (that I can find) in 1.8.4 and 1.8.5

### Known workarounds
None

**Comment by ConnorMcMahon** [comment]
I have published release notes for v1.8.5.

Now that 1.8.5 is released, GitHub does not have the right tooling to release v1.8.4 release notes, so I made sure to explicitly call out the changes that v1.8.4 is responsible for in the release notes for v1.8.5.

**Comment by dsm0880** [comment]
Thank you @ConnorMcMahon !!
