### ISSUE TITLE
[Bug] Fetching instances not consistent - v2.1.1

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-functions-durable-extension#1214]
### Description
After migrating from 2.0.0 to 2.1.1 when fetching instances, certain times the data is inconsistent ,i tried with and without passing `createdTimeFrom`
This works perfectly in v2.0.0.

### Expected behavior
Does not matter how many times i request any API the results should be consistent.

### Actual behavior
I have one app with about 3000 instances (most of them completed). When I query repeatedly, lets say every 10 seconds, time to time i get way less data, about 60 instances only. 

### Relevant source code snippets
```js
//Doing this every 10 seconds will return different instances length.
let instances = await fetch(`https://APPNAME.azurewebsites.net/runtime/webhooks/durabletask/instances?code=CODE`)
console.log('instances', instances.length)
```

### App Details

- **Durable Functions extension version: 2.1.1
- **Azure Functions runtime version : 2

### If deployed to Azure
Cant publicly share info

**Comment by cgillum** [comment]
Thanks for reporting this.

We made a change in the v2.1.0 release (#1119) which might be causing this. It limited the number of instances we return by default and also changed the code path we follow.

A few questions to help us narrow down why you are seeing inconsistent behavior:

* What happen if you add a `top=3000` query string parameter to your fetch request?
* Are all your instances orchestrations or do you have entities as well?

**Comment by andreujuanc** [comment]
Hi, 
I already tested top. It maxes out at 1000 items, so top 2000==top3000, shows only 1000
Yes indeed, the app that has this issue has an entity (a single instance one BTW), and the one that works fine doesn't have any.  

So might be that this intermittence caused by entities instances?

**Comment by andreujuanc** [comment]
Hi @cgillum  I wont be able to test this anymore. 
Can be closed unless someone managed to repro.

Best

**Comment by ConnorMcMahon** [comment]
I'm going to leave this open, since it sounds relatively straightforward for us to repro ourselves. I will close if we can't repro.

**Comment by cgillum** [comment]
Closing this issue since it has gone stale. It very well could be related to entities, which we have separate issues open for (fixing those could likely resolve this issue).
