### ISSUE TITLE
[Bug] NullReferenceException in HttpApiHandler - v2.1.1

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-functions-durable-extension#1215]
### Description
While testing some functions, we got this error when migrating from 2.0.0 to 2.1.1

### Expected behavior
Check your nullables :smile: 

### Actual behavior
Several nullables are not checked (C# 8?)

### Relevant source code snippets
```csharp
Exception while executing function: Functions.FUNCTIONNAMERequestBusTrigger Result: Failure
Exception: Error: The operation failed with an unexpected status code: 500. Details: {"Message":"Something went wrong while processing your request","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 666\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 206"}
Stack: Error: The operation failed with an unexpected status code: 500. Details: {"Message":"Something went wrong while processing your request","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":"   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleStartOrchestratorRequestAsync(HttpRequestMessage request, String functionName, String instanceId) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 666\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in d:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 206"}
    at DurableOrchestrationClient.createGenericError (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:587:16)
    at DurableOrchestrationClient.<anonymous> (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:401:44)
    at Generator.next (<anonymous>)
    at fulfilled (D:\home\site\wwwroot\node_modules\durable-functions\lib\src\durableorchestrationclient.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7) 
```

According to 2.1.1 merge, this is the relevant line:
https://github.com/Azure/azure-functions-durable-extension/blob/fd6da7bb82fc0fddb09a0a1504b6be68984b7d9f/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L666

I think the dataConverter is null, since it was introduced in this version:
https://github.com/Azure/azure-functions-durable-extension/blob/fd6da7bb82fc0fddb09a0a1504b6be68984b7d9f/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L71

### App Details

- **Durable Functions extension version: 2.1.1
- **Azure Functions runtime version: 2

### If deployed to Azure
Cant publicly share info

**Comment by cgillum** [comment]
I'm looking at this code and I can't think of any reason why the `dataConverter` object would be null for Functions 2.0. Can you share more information about when you encounter this?

**Comment by andreujuanc** [comment]
We got that error from application insights. That's an orchestrator that never failed before. 
We did had some in "running" state and also some other "pending" when we moved from 2.0.0 to 2.1.1
It's definitely a NRE, the problem here is what's the actual cause. 
I just followed the code back and you were right. Cannot see dataConverter being null.

It's either the line number does not match with the code, or something else I'm missing. 

Is it possible that upgrading the version while having orchestrators alive might be the cause of this?

**Comment by cgillum** [comment]
I think the line number might be off by one. I suspect the null-ref is actually on [line 665](https://github.com/Azure/azure-functions-durable-extension/blob/8b4abf7a38cb016b16af1143b89b9072b1fe7be8/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L665) (`request.Content` is null). We thought we were handling nulls correctly here, but we later realized that this was not the case.

We fixed this in **v1.8.5** but it is not fixed in **v2.1.1**. Specifically, we fixed this as part of [this PR](https://github.com/Azure/azure-functions-durable-extension/pull/1166) (you can see the updated code [here](https://github.com/Azure/azure-functions-durable-extension/blob/88084dc6a4a7c0ccecac1ce265f92539b2acedda/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L694)) but that won't be available until the next release (**v2.2.0**).

Which JS API is causing this failure for you? Depending on which one it is, you might be able to work around it by sending some request content.

**Comment by andreujuanc** [comment]
So it's basically something is starting the orchestrator with empty/null input parameters? that's weird.
I'll have to wait for Monday to investigate further.
Cheers

**Comment by andreujuanc** [comment]
Hi @cgillum I just verified the data, and the message is not empty. This is the operation id in app insights: `3e0e182141ab7f4c8cbb77e6678bd6e1`
Maybe the error is caught in the HttpApiHandler, but the actual problem happened in js?

**Comment by andreujuanc** [comment]
UPDATE: Rolling back to 2.0.0 :(

**Comment by andreujuanc** [comment]
@cgillum  I tried with 2.1.0 and did not work either. 
Tried again several with 2.1.1 and 2.1.0 and got the same error.
Rolled back to 2.0.0 and started properly. 

If you want to get more into this, let me know.

**Comment by aweber1** [comment]
Possibly related issue? https://github.com/Azure/azure-functions-durable-extension/issues/1178
(which appears to have an associated, merged PR)

I'm seeing the same error as OP with the following stack:

* JavaScript orchestrator function
* `Microsoft.Azure.WebJobs.Extensions.DurableTask` version `2.1.1` installed
* Azure Functions Core Tools version: `3.0.2106`
* Function Runtime Version: `3.0.13107`

I have only tried running locally.

**Comment by ConnorMcMahon** [comment]
We likely have fixed this with #1164.

**Comment by andreujuanc** [comment]
I'll be happy to try this when patch goes live. Is it in 2.2.0?

**Comment by ConnorMcMahon** [comment]
It will be. I'm hoping to get 2.2.0 out in the next few business days.

I might put a preliminary release today or tomorrow on our azure-app-service myget feed at https://www.myget.org/F/azure-appservice/api/v3/index.json if that would be helpful.

**Comment by ConnorMcMahon** [comment]
Took some time, but 2.2.0 got released.
