### ISSUE TITLE
"Multithreaded execution was detected" when using context.CallHttpAsync

### ISSUE THREAD

**Issue by n-margalit** [Azure/azure-functions-durable-extension#1221]
I have an OrchestrationTrigger function that call another service by http request.
```
 [FunctionName("MyFunc")]
        public async Task RunOrchestrator(
        [OrchestrationTrigger] IDurableOrchestrationContext context,
        ILogger logger)
    {
        var req = new DurableHttpRequest(HttpMethod.Post, _uri, headers, jsonBody);
        var res = await context.CallHttpAsync(req);
        // Do something
    }
```
but get the following error: 

`Multithreaded execution was detected. This can happen if the orchestrator function code awaits on a task that was not created by a DurableOrchestrationContext method. More details can be found in this article https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-checkpointing-and-replay#orchestrator-code-constraints.`

**Comment by ConnorMcMahon** [comment]
@n-margalit 

From my look at the code in the `CallHttpAsync()` method, it is single-threaded.

Are you positive that this is the segment throwing that exception? I would recommend debugging locally and set the debugger to stop when that exception is detected. 

The other option is to provide us an example instance id of you hitting this error in Azure.

You could also provide us with a more comprehensive code sample/repro, and we could diagnose it that way.

**Comment by cgillum** [comment]
Note that this exception is thrown only *after* a problem is detected. If it’s being thrown by CallHttpAsync, it means that some illegal asynchronous operation happened *before* the CallHttpAsync call.

An easy way to detect these kinds of code violations is to add the Durable Functions analyzer package to your project. It can automatically detect coding errors and flag them as warnings.

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers/

/cc @amdeel

**Comment by n-margalit** [comment]
I've installed and get the warning from #1018

**Comment by n-margalit** [comment]
@ConnorMcMahon  how can I provide  an example instance id?

**Comment by ConnorMcMahon** [comment]
@n-margalit

If you are creating the orchestration instance with `DurableClient.StartNewAsync()`, the return value should be the instance id as a string.

**Comment by n-margalit** [comment]
I've upgraded Microsoft.Azure.WebJobs.Extensions.DurableTask and Microsoft.NET.Sdk.Functions and the issue disappeared
