### ISSUE TITLE
Add setting to configure whether entity state on an exception

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-durable-extension#1223]
(This may only apply to C#, need to verify)

From the discussion in #1219, entity state is persisted even when there's an exception. This behavior may be counterintuitive.

Propose adding a new setting (in code or config) to configure whether entity state is persisted on an exception. Possibly make this the default in future versions of Durable Entities.

**Comment by sebastianburckhardt** [comment]
To keep things consistent, I think the behavior should be the same for all languages.

To support rollback in the implementation, what we need to do is make sure we keep a serialized snapshot of the entity state prior to performing *any* operation. Unfortunately it is not possible to accurately predict or detect whether an operation modifies the state, so we have to be conservative.

We already pay the cost of creating such a snapshot at the end of each operation batch, so we have a snapshot of the entity state before we start the first operation in a batch. However, we are not currently doing that in between the operations of a batch. 

We would have to add logic for taking such snapshots, for catching exceptions during an operation, for rolling back to the pre-operation snapshot, and then continuing with the next operation in the batch. This logic needs to be implemented separately for each language (e.g. the batch processing inside the javascript would need to call `JSON.stringify` or similar in between operations so it can restore the state of an operation that throws an exception).

**Comment by sebastianburckhardt** [comment]
If we provide this "transactional entity state" guarantee, we could even go one step further and roll back entity states of all participating entities when a critical section throws an exception!

**Comment by sebastianburckhardt** [comment]
Any suggestions on how one would configure this option? Perhaps a `[RollbackOnExceptions]` attribute somewhere? Not sure what would be a good place for it.

**Comment by msajid** [comment]
I think it should be a default behavior. Developers should opt in for non-rollback version using some kind of attribute or config

**Comment by sebastianburckhardt** [comment]
Yeah, I think I am warming up to that idea. Rollback is bad for the performance with large entity states with lots of batching but those aren't our main use cases at the moment, and they already don't perform well with the current state management approach so we will probably address those issues using some alternative state configuration options anyway.

**Comment by sebastianburckhardt** [comment]
At least on the C# side this is actually a pretty easy change and in fact simplifies the current implementation. We can get this done pretty quickly I think.

**Comment by anthonychu** [comment]
Great! I just wonder if this is going to change behavior for existing apps. It wouldn't affect deployed apps until they update the extension and redeploy. @cgillum Thoughts on whether this is a breaking change or a bug fix?

Also need to test on JavaScript to see if this is a .NET only issue, which might dictate how to implement this. @ConnorMcMahon is going to look into it when he is able to.

**Comment by cgillum** [comment]
Since we've been GA for a few months already, I worry about making this kind of default behavioral change. Normally we want to enable people to upgrade their versions of the extension without fear of such changes. It's probably a corner case, though, and we might be able to get away with it depending on the current usage of Durable Entities in production.

**Comment by msajid** [comment]
I don't think many people know about this issue. This is clearly a user experience problem and most of the people will find it problematic. Making it default behavior will improve the user experience and save developers from surprises.

**Comment by sebastianburckhardt** [comment]
For new users, the rollback-on-exceptions behavior is definitely safer - it is much more likely to do the right thing by default. By the way, after looking into it some more I see that to make the design consistent, the roll back should also include creation and deletion (not just the modification) of entity state. And as I mentioned earlier, I am also excited about extending this roll-back feature  to critical sections; simply have all participating entity states roll back when a critical section throws an exception. So we are making the critical sections behave like transactions with respect to entity states. 

Perhaps we need a configuration option somewhere to disable this new 'rollback-on-exceptions' behavior? If users run into trouble when upgrading existing code they can turn it off.

**Comment by cgillum** [comment]
Sounds like strong arguments for making this change. I say lets go ahead and do it. How much extra work and/or complexity would be involved if we add a config option to turn it off?

**Comment by sebastianburckhardt** [comment]
We will probably need more configuration options for entity state in the future (for example, to configure custom storage providers). Perhaps we could introduce an `EntityStateOptions` class and add this options (and others in the future). Users could then change the default options with something like
```csharp
ctx.SetStateOptions(new EntityStateOptions() { RollbackOnExceptions = false; })
```
which is stable even if we add more options later on.

This is pretty easy to provide and use. The disadvantage is that this is called every time the operation executes. Another idea is to use a globally injected class, e.g. `IEntityStateOptionsProvider`. Not sure how well that works for extending the set of options later on though.

If anyone knows a good pattern for this type of configuration please chime in.

**Comment by cgillum** [comment]
My vote would be to make this a app-level setting. Something we can add to [host.json](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#durable-functions-2-0-host-json).  It would be as simple as adding a new property to [DurableTaskOptions.cs](https://github.com/Azure/azure-functions-durable-extension/blob/88084dc6a4a7c0ccecac1ce265f92539b2acedda/src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs#L17). Something like this:

```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "MyDFHub",
      "rollbackEntityStateOnExceptions": true
    }
  }
}
```

**Comment by sebastianburckhardt** [comment]
can we change the options format without creating breaking changes?

**Comment by cgillum** [comment]
Yes, new properties are non breaking and we can choose any default we want.
