### ISSUE TITLE
Ability to override Input field from GetStatus HTTP API

### ISSUE THREAD

**Issue by FaithLV** [Azure/azure-functions-durable-extension#1226]
**Is your feature request related to a problem?**
We have an async HTTP endpoint to which we send sensitive data (authentication keys, etc.) in the request body, but when querying the status of the operation, it shows all the input values in plain-text.

```
            var requestBody = await req.Content.ReadAsStringAsync();
            var input = JsonConvert.DeserializeObject<AzureUserInput>(requestBody);
            string instanceId = await starter.StartNewAsync(AzureFunctionNames.InstanceOrchestrator, input);
            return starter.CreateCheckStatusResponse(req, instanceId);
```

**Describe the solution you'd like**
It would be useful if we could override the status query response to set custom Input values, I'd like to hide sensitive values, but keep other values intact.

**Comment by anthonychu** [comment]
`CreateCheckStatusResponse` returns an HTTP response that contains a 202 status code, a location header with a URL for the built-in HTTP APIs to get the status, plus a set of URLs for all possible operations on the built-in HTTP APIs. Both the `CreateCheckStatusResponse` method and the built-in HTTP APIs are included for convenience. It's entirely possible to build your own if you need custom behavior.

I have put together a [sample](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs) on how to do this.

I return a [custom check status response](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs#L42) from my HTTP starter function. The URLs in that payload point to a [custom HTTP triggered function](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs#L45-L62) that returns the status. You can implement any custom logic you want to see from your status endpoint here.

**Comment by anthonychu** [comment]
@cgillum Any thoughts on how we can give some control over what is returned from the built-in APIs?

**Comment by FaithLV** [comment]
@anthonychu Thanks for suggestion! After creating this issue I went to the documentation and created a custom endpoint just like you suggested.

Leaving this open as this would still come in handy.

**Comment by cgillum** [comment]
Thanks @anthonychu for the sample you put together! I would definitely recommend custom code for handling cases like this. I worry that the possible number of customizations we would need to add to `CreateCheckStatusResponse` would be fairly large, so if we have decent workarounds, I'd prefer we rely on workarounds and save API changes for cases where workarounds aren't simple or feasible. APIs like `CreateCheckStatusResponse` is really designed as a convenience method.

Happy to discuss further if there is disagreement.

**Comment by xmak** [comment]
> `CreateCheckStatusResponse` returns an HTTP response that contains a 202 status code, a location header with a URL for the built-in HTTP APIs to get the status, plus a set of URLs for all possible operations on the built-in HTTP APIs. Both the `CreateCheckStatusResponse` method and the built-in HTTP APIs are included for convenience. It's entirely possible to build your own if you need custom behavior.
> 
> I have put together a [sample](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs) on how to do this.
> 
> I return a [custom check status response](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs#L42) from my HTTP starter function. The URLs in that payload point to a [custom HTTP triggered function](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs#L45-L62) that returns the status. You can implement any custom logic you want to see from your status endpoint here.



> `CreateCheckStatusResponse` returns an HTTP response that contains a 202 status code, a location header with a URL for the built-in HTTP APIs to get the status, plus a set of URLs for all possible operations on the built-in HTTP APIs. Both the `CreateCheckStatusResponse` method and the built-in HTTP APIs are included for convenience. It's entirely possible to build your own if you need custom behavior.
> 
> I have put together a [sample](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs) on how to do this.
> 
> I return a [custom check status response](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs#L42) from my HTTP starter function. The URLs in that payload point to a [custom HTTP triggered function](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs#L45-L62) that returns the status. You can implement any custom logic you want to see from your status endpoint here.

@anthonychu I see your [custom HTTP triggered function](https://github.com/anthonychu/durable-custom-checkstatusresponse/blob/034ccc45e96f0e6e08b0cb72d6bc4ceeda9b002f/MyDurableApp.cs#L45-L62) check and returns only the status. How to do the same but for the output of an orchestrator.
