### ISSUE TITLE
Control queues keeps growing. Durable functions stuck on durable entity execution.

### ISSUE THREAD

**Issue by tbuha** [Azure/azure-functions-durable-extension#1233]
### Description
I've implemented durable function which calls durable entity (single instance), durable entity returns string result.

### Expected behavior
Multiple instances of orchestrator call singleton durable entity and receive result from it.

### Actual behavior
All orchestrators stuck on singleton durable entity call and cannot continue further execution.

### App Details

- **Durable Functions extension version 2.1.1**:
- **Azure Functions runtime version netcoreapp3.1**:
- **Programming language used C#**:

- **Timeframe issue observed**: from 02/21/2020 12:30:50 +02:00 
- **Function App name**: FxcoEmailDistributor
- **Function name(s)**: ScheduleOrchestrator
- **Azure region**: North Europe

**Comment by amdeel** [comment]
Hi @tbuha, do you have an orchestration/entity instanceId from that time period or any code that might help us in investigating this issue?
