### ISSUE TITLE
ListEntitiesAsync infinite looping with bad continuation token

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-functions-durable-extension#1236]
### Description
ListEntitiesAsync appears to be returning an invalid continuation token.

### Expected behavior
ListEntitiesAsync to return valid list of durable entities.

### Actual behavior
ListEntitiesAsync returns a result, with a non-null continuation token, but there's no values in the IEnumerable entities.

If I set the next query.ContinuationToken to the result.ContinuationToken, the code below will infinite loop.

NOTE: 
Running this locally using Azure Storage Emulator, and debugging in VS2019.

To validate I didn't have bad data, I also started clean before running this, so there aren't any entities.  No difference in behavior.

> func durable delete-task-hub --task-hub-name feeds

### Relevant source code snippets
```csharp
        [FunctionName("QueryFeeds")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "get", Route = "v1/feeds")] HttpRequest request,
            [DurableClient] IDurableClient client)
...
            using CancellationTokenSource source = new CancellationTokenSource();
            var token = source.Token;

            var query = new EntityQuery
            {
                PageSize = 100, // default
                FetchState = true
            };

            do
            {
                var result = await client.ListEntitiesAsync(query, token);
                var entities = result.Entities;

                query.ContinuationToken = result.ContinuationToken;

                // NOTE: my handler, and there's nothing in IEnumerable
                HandleEntities(entities, feeds);
            }
            while (query.ContinuationToken != null);
```

### Known workarounds
None

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.1.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0.13107
- **Programming language used**: C#/.NET Core 3.1

**Comment by amdeel** [comment]
Hey @kirk-marple, this looks like a known [issue.](https://github.com/Azure/azure-functions-durable-extension/issues/1174) Check to see if changing your while condition to the one suggested below fixes this for you:

`while (queryCondition.ContinuationToken != null && queryCondition.ContinuationToken != "bnVsbA==");`

**Comment by kirk-marple** [comment]
Great, thanks.  Yeah that's the same issue I saw.  Thanks for the workaround.
