### ISSUE TITLE
ReadEntityStateAsync does not support dependency injection constructors

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1238]
`IDurableClient.ReadEntityStateAsync()` cannot use dependency injection to create the object. See end of discussion at #960

**Possible solutions**
1. Add support for Dependency Injection on this method. Not sure of the feasibility of this given `DurableClient` is a binding, not a trigger, and also has strange implications if the application running the `IDurableClient` binding has different services injected than the one running the entity.
2. Instantiate the entity state with null parameters for the constructor. This could lead to unexpected behavior (null reference exceptions) for the customer.
3. Document this limitation, and provide workarounds.

**Comment by abbasc52** [comment]
@ConnorMcMahon  I had similar issue. Realized it was a limitation of Class based syntax. Moving to function based syntax worked for me.

**Comment by ConnorMcMahon** [comment]
Captured appropriately already via #1162.
