### ISSUE TITLE
Improved error messaging when using IO in an orchestrator

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-durable-extension#124]
The following function is not allowed. Despite reading that multiple times in the documentation, I did it anyway. Oops.

        [FunctionName("ProcessFile")]
        public static async Task Run(
            [OrchestrationTrigger] DurableOrchestrationContext context,
            IBinder binder,
            TraceWriter log)
        {
            var name = context.GetInput<string>();
            using (var input = await binder.BindAsync<Stream>(new BlobAttribute($"test/{name}", FileAccess.Read)))
            using (var output = await binder.BindAsync<Stream>(new BlobAttribute($"archive/0/test/{name}", FileAccess.Write)))
            {
                Console.WriteLine($"Archiving {name}...");
                await input.CopyToAsync(output);
            }
        }

The weird thing is that on the first BindAsync, I get the error message "System.ObjectDisposedException: 'Cannot access a disposed object.'". This error message is completely baffling in normal code. But there must be some kind of orchestrator enforcer coded to prevent IO calls. That's fine and all, but is there are way we can improve error messaging? Something like "System.InvalidOperationException: IO operations cannot be executed in this context."?

**Comment by cgillum** [comment]
I don't know why you are getting the ObjectDisposedException. Is there a callstack you can share?

The `[OrchestrationTrigger]` binding does not and cannot prevent you from doing any I/O in your orchestrator function. There's really no way for us to enforce this rule or throw any exception.

**Comment by MisinformedDNA** [comment]
The full code:

        [FunctionName("InjestFile_Error")]
        public static async Task Run(
            [BlobTrigger("test/{name}")] Stream input,
            string name,
            [OrchestrationClient] DurableOrchestrationClient starter)
        {
            await starter.StartNewAsync("ProcessFile_Error", name);
        }

        [FunctionName("ProcessFile_Error")]
        public static async Task Run2(
            [OrchestrationTrigger] DurableOrchestrationContext context,
            IBinder binder)
        {
            var name = context.GetInput<string>();
            using (var input = await binder.BindAsync<Stream>(new BlobAttribute($"test/{name}", FileAccess.Read)))    // line 28
            using (var output = await binder.BindAsync<Stream>(new BlobAttribute($"archive/1/test/{name}", FileAccess.Write)))
            {
                Console.WriteLine($"Archiving {name}...");
                await input.CopyToAsync(output);
            }
        }

The full error

> System.ObjectDisposedException
>   HResult=0x80131622
>   Message=Cannot access a disposed object.
>   Source=Microsoft.Azure.WebJobs.Host
>   StackTrace:
>    at Microsoft.Azure.WebJobs.Host.Bindings.Runtime.CollectingDisposable.Add(IDisposable disposable)
>    at Microsoft.Azure.WebJobs.Binder.<BindAsync>d__13`1.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.WebJobs.Binder.<BindAsync>d__12`1.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at DurablePoC.InvalidFunction.<Run2>d__1.MoveNext() in c:\users\50587\documents\visual studio 2017\Projects\DurablePoC\DurablePoC\InvalidFunction.cs:line 28
> 

Line 28 corresponds to the line
`using (var input = await binder.BindAsync<Stream>(new BlobAttribute($"test/{name}", FileAccess.Read)))`

**Comment by ConnorMcMahon** [comment]
We now detect many common IO operations at compile time with the analyzer, so I don't think this is as much of an issue anymore. I also know we have tackled a series of issues related to ObjectDisposedExceptions with the Azure Functions logging infrastructure.
