### ISSUE TITLE
Add webhook to rerun failed (or terminated) orchestrations

### ISSUE THREAD

**Issue by thdotnet** [Azure/azure-functions-durable-extension#1243]
At this moment, there are a few operations / endpoints when using Durable Functions (IDurableOrchestrationContext):

* statusQueryGetUri

* sendEventPostUri

* terminatePostUri

* purgeHistoryDeleteUri

I would like the possibility to re-execute a workflow, and the reason is as I'm not the caller of the Starter function so I cannot provide the same input parameters. I think this feature could be useful specially when due some activity exceeds the retry count, but after some time, there are no problems anymore and I need to reprocess.

**Comment by ConnorMcMahon** [comment]
It sounds like you want a retryOrchestration endpoint. I could potentially see the use in that.

@cgillum, thoughts?

In the meantime, you could implement something similar to this yourself with sub-orchestrations and events. I have written up some rough code that could accomplish what you are asking for.

```csharp
    public static async Task<string> AllOrchestratorActivityActions([OrchestrationTrigger] IDurableOrchestrationContext ctx)
    {
        var (orchName, input) ctx.GetInput<(string, object0>();
        try {
            await ctx.CallSubOrchestratorAsync(orchName, input);        
        } catch {
            ctx.SetCustomStatus("RetryableFailure");
            var restartEventTask = ctx.WaitForExternalEvent();
            var timerTask =  ctx.CreateTimer(ctx.CurrentUtcDateTime.AddDays(6));
            var winner = Task.WhenAny(timerTask, restartEventTask);
            if (winner == restartEventTask) {
                await ctx.CallSubOrchestratorAsync(orchName, input);
            } else {
                throw new Exception("Orchestration failed and not retried);
            }
        }
    }
```

**Comment by cgillum** [comment]
It's an interesting feature idea for sure. The closest thing we have today is the [Rewind API](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#rewind-instances-preview), which is designed to re-run only the most recent logic after a failure occurs. However, this is still in preview because there are a lot of edge cases where it doesn't work.

A **restart** API is interesting because it's conceptually very simple and would probably be easy to implement. Basically, we just need to query the input from the existing orchestration and then create a start message to restart it.

But given this, could you implement it yourself as well? For example:

```csharp
[FunctionName("RestartOrchestration")]
public static async Task<HttpResponseMessage> RestartOrchestration(
    [HttpTrigger(AuthorizationLevel.Function, methods: "post", Route = "orchestrations/{instanceId}/restart")] HttpRequestMessage req,
    [DurableClient] IDurableClient client,
    string instanceId)
{
    DurableOrchestrationStatus status = await client.GetStatusAsync(
        instanceId,
        showHistory: false,
        showHistoryOutput: false,
        showInput: true);

    // TODO: Check the runtime status to make sure it's in a restartable state

    await client.StartNewAsync(
        orchestratorFunctionName: status.Name,
        instanceId: status.InstanceId,
        status.Input);

    return client.CreateCheckStatusResponse(req, instanceId);
}
```

**Comment by cgillum** [comment]
The more I think about this, the more I think we should have this built in. It would be a great tool to help folks recover from problems, including stuck orchestrations, without necessarily needing to wait on support tickets. It would be interesting to see whether or how this might work for sub-orchestrations too.

/cc @anthonychu

**Comment by thdotnet** [comment]
Sorry, I'm late for the discussion... but I can provide more details if needed.

The rewind API is almost the same idea, however I would like the ability to reprocess any execution.

**Comment by anthonychu** [comment]
This is a good idea. What's the advantage of restarting the same orchestration, vs starting a new one with the same input copied from the original orchestration? I'm not opposed to restarting but it does feel weird from an event sourcing perspective to delete history and start over.

**Comment by thdotnet** [comment]
Both would work. In fact, I think it should start a new one with some kind of traceability

**Comment by raffi1965** [comment]
> It's an interesting feature idea for sure. The closest thing we have today is the [Rewind API](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp#rewind-instances-preview), which is designed to re-run only the most recent logic after a failure occurs. However, this is still in preview because there are a lot of edge cases where it doesn't work.
> 
> A **restart** API is interesting because it's conceptually very simple and would probably be easy to implement. Basically, we just need to query the input from the existing orchestration and then create a start message to restart it.
> 
> But given this, could you implement it yourself as well? For example:
> 
> ```cs
> [FunctionName("RestartOrchestration")]
> public static async Task<HttpResponseMessage> RestartOrchestration(
>     [HttpTrigger(AuthorizationLevel.Function, methods: "post", Route = "orchestrations/{instanceId}/restart")] HttpRequestMessage req,
>     [DurableClient] IDurableClient client,
>     string instanceId)
> {
>     DurableOrchestrationStatus status = await client.GetStatusAsync(
>         instanceId,
>         showHistory: false,
>         showHistoryOutput: false,
>         showInput: true);
> 
>     // TODO: Check the runtime status to make sure it's in a restartable state
> 
>     await client.StartNewAsync(
>         orchestratorFunctionName: status.Name,
>         instanceId: status.InstanceId,
>         status.Input);
> 
>     return client.CreateCheckStatusResponse(req, instanceId);
> }
> ```

client.GetStatusAsync always returns NULL
