### ISSUE TITLE
Add TaskHub name limitations to documentation

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1247]
Currently there are a large set of limitations to TaskHub names (alphanumeric characters, 3-45? characters, can't start with number, etc) that are not in our documentation. We should update the TaskHub section of documentation with these limitations.

**Comment by anthonychu** [comment]
@ConnorMcMahon Do you know where I'd look (docs or code) to figure out the rules?

**Comment by ConnorMcMahon** [comment]
I don't have a link to all of the official docs. [Here](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata) it is for blobs.

I believe following these two rules gives you a compliant TaskHub name

- Between 3 and 45 alphanumeric characters
- Cannot begin with a number

**Comment by anthonychu** [comment]
Docs updated.
