### ISSUE TITLE
Not able to Signal Entity Function using IDurableClient from different Function App

### ISSUE THREAD

**Issue by raggupta-ms** [Azure/azure-functions-durable-extension#1248]
### Description
I want to use IDurableClient from an EventHub triggered Function to Signal the Entity Function sitting in different Function App. I pass the Entity Function's Storage COnnection string and Taskhub name in DurableClient Attribute like this -
`[DurableClient(ConnectionName = "EntiyFunctionConnectionStringName", TaskHub = "RaghavTaskHub1")]`

When I try to Signal EF, it says it can't find the EF. Actual exception in below section. I have tried these cases -
1) Both the functions running locally at different ports. Both using Storage Emulator locally with `AzureWebJobsStorage = “UseDevelopmentStorage=true”.`
2) EF running in cloud with its own Storage and EH triggered Function running locally. 

Both of above ends up in same error.
However, note that I am successfully able to read Entity State using IDurableClient from different App. So the issue looks to be that for Signal call, Durable Extension is trying to search the EF in the same Function App. 
Also, I am able to signal across Function Apps using Http endpoint.

### Expected behavior
Entity Function should be found and Signal call to successfully return success code.

### Actual behavior
The Entity is "Circuit" in my code and here is the Exception on console -
![image](https://user-images.githubusercontent.com/35366762/75705479-4c096c80-5c70-11ea-84cf-856d6dc1c841.png)

### Relevant source code snippets
```csharp
[FunctionName(“IngestFunction”)]
public async Task Run(
     [EventHubTrigger("health_change", ConsumerGroup = "testcg", Connection = "EventHubConnectionString")] EventData[] events,
     [DurableClient(ConnectionName = "EntiyFunctionConnectionStringName", TaskHub = "RaghavTaskHub1")] IDurableEntityClient entityClient)
{
     await client.SignalEntityAsync(
                    new EntityId("Circuit", "IngestFunction"),
                    nameof(ICircuit.ReportOperationsStatus),
                    new CircuitBreakerRequest
                    {
                        RequestId = Guid.NewGuid().ToString(),
                        RequestTime = DateTime.UtcNow,
                        SuccessCount = 10,
                        FailureCounts = new Dictionary<string, int>
                        {
                            { "Different App DurableClient", 50 },
                        },
                    },
                    "RaghavTaskHub1",
                    "EntiyFunctionConnectionStringName");

}
```

### Known workarounds
Using Http endpoint to Signal instead of IDurableClient.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
Microsoft.Azure.Functions.Extensions = 1.0.0
Microsoft.Azure.WebJobs.Extensions.DurableTask = 2.1.1
Microsoft.Azure.WebJobs.Extensions.EventHubs = 4.1.1
Microsoft.NET.Sdk.Functions = 3.0.3

- **Azure Functions runtime version (1.0 or 2.0)**:
v3

- **Programming language used**:
C# (.Net Core 3.1)

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by ConnorMcMahon** [comment]
This seems like a simple fix for 2.2.0.

**Comment by raggupta-ms** [comment]
@amdeel @ConnorMcMahon I upgraded to v2.2.0 and still facing the same issue. I can do a ReadEntityStateAsync successfully but SignalEntityAsync fails with the same exception that it cannot find the entity function. 
Is there any thing that I need to do that I am missing. I am following the exact steps mentioned in this issue.

**Comment by amdeel** [comment]
Hi. If you remove the ConnectionName and TaskHub in your DurableClient attribute, this should work correctly. I didn't correctly fix this issue, but changing this in your client should be a workaround until I put another fix in. Sorry for the inconvenience.

Let me know if this fixes your issue for now!

**Comment by raggupta-ms** [comment]
@amdeel Yes, the workaround is working fine. Thanks!

**Comment by withinboredom** [comment]
It looks like the generic functions `.SignalEntityAsync<IEntityTest>(new EntityId("entitytest", "key"), test => test.GiveName(name));` are lacking the hub/connection arguments to make this work.

**Comment by raggupta-ms** [comment]
@withinboredom  Yes, I also noticed that. The interface based signal APIs do not have those arguments. I am using the non-interface based like this -

`.SignalEntityAsync(new EntityId("entitytest", "key)", nameof(IEntityTest.GiveName), name, TaskHubName, ConnectionString);

It needs a separate issue unless there are reasons to not to do that.
