### ISSUE TITLE
Durable Entity incomplete serialization after async

### ISSUE THREAD

**Issue by Lukkopera** [Azure/azure-functions-durable-extension#1254]
### Description
I have a durable entity with a method to initialize the entity from a database query, the query is run as async operation. After the query, entity parameters are set from the result. Problem is that the entity is not serialized correctly to the table storage, the shape is right, all fields are found, but some, or all, values are null.  The amount of null values changes on different entities. Next time the entity is accessed, these properties are then deserialized and stuff breaks.

### Expected behavior
Entity to be serialized properly after async operations.

### Actual behavior
Entity serialization is incomplete after async.

### Known workarounds
Make the query outside of the entity and pass the result to the signalled method.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
2.1.1
- **Azure Functions runtime version (1.0 or 2.0)**:
 3.0
- **Programming language used**:
C#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by Lukkopera** [comment]
It seems that this bug is happening only when debugging and a breakpoint is hit after a async. Without breakpoints, works as excepted.

**Comment by ConnorMcMahon** [comment]
@sebastianburckhardt, would you be able to take a look at this? If not I can.

**Comment by sebastianburckhardt** [comment]
Not sure what is happening here. I can try to repro based on your description. Perhaps you could give me some more details on what your code looks like (it's o.k. if you omit details such as what the actual query looks like). Are you using the class-based syntax with `DispatchAsync`? Are you initializing the entity prior to calling DispatchAsync, or as an entity operation?

**Comment by sebastianburckhardt** [comment]
Based on your description I tried a simple repro as below, setting a breakpoint after the async. But everything seems to work as expected. I think ill need more information to repro the problem you are seeing.

```csharp
    public class QueryResult
    {
        public string a;
        public int b;
        public DateTime c;
    }

    public class TestEntity
    {
        public QueryResult result;

        public async Task Init()
        {
            this.result = await QueryAsync();
        }

        public static async Task<QueryResult> QueryAsync()
        {
            await Task.Delay(10);
            return new QueryResult() { a = "hello", b = 333, c = DateTime.UtcNow };
        }

        [FunctionName(nameof(TestEntity))]
        public static Task Run([EntityTrigger] IDurableEntityContext ctx)
        {
            return ctx.DispatchAsync<TestEntity>();
        }
    }
 
    public static class HttpTriggers
    { 
        [FunctionName("SignalInit")]
        public static async Task<IActionResult> DoSomething(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest req,
            [DurableClient] IDurableClient client)
        {
            await client.SignalEntityAsync(new EntityId("TestEntity", "global"), "Init");
            return new OkResult();
        }
   }
```

**Comment by Lukkopera** [comment]
My code was basically similar, using the class-based syntax. Only difference was that the query was from Mongo driver and some light parsing on the result before return.
