### ISSUE TITLE
Durable Entities - "StartNewOrchestration" Not Starting Orchestration

### ISSUE THREAD

**Issue by Areson** [Azure/azure-functions-durable-extension#1259]
### Description
When making a call to `Entity.Current.StartNewOrchestration` the orchestration is not started when there are pending items in the control queue.

I'm attempting a sort of "fan-in" using durable entities to collect a group of records together prior to persisting them to some sort of storage. Records are added to the durable entity until either a timeout has expired or the number of records in the entity has reached a certain threshold. For simplification I'll use the case where the number of records exceeds some threshold. Inside the entity class:

```csharp
public void Add(T item)
{
    CurrentValue.Add(item);
    var aggregatorCount = CurrentValue.Count;

    if (aggregatorCount >= MaxItemCount && !IsFull)
    {
        IsFull = true;
        InitiatePersist();
    }
}


private void InitiatePersist()
{
    if (Entity.Current.HasState && !HasInitiatedHandler && (TimerExpired || IsFull))
    {
        Entity.Current.StartNewOrchestration(HandlerOrchestrationName, Entity.Current.EntityId);
        HasInitiatedHandler = true;
    }
}
```

The idea here is that once a threshold has been met that a durable orchestration is called to handle the entity. The orchestration locks the entity, pulls the current contents of the list of records, and then resets the entity state. Afterwards the orchestration will hand off the list of records to an activity to persist them.

In the debugger I can see that the call to start the orchestration is made and is put into a list (e.g. "outbox") for later processing, but that processing doesn't appear to take place as long as there are actions against the durable entity present in the control queue. This is a long-lived entity and I have 100+K entries in the control queue.

### Expected behavior
When making a call to `Entity.Current.StartNewOrchestration` the orchestration should be started within a reasonable time after making the call.

### Actual behavior
The orchestration is not called while there are items pending in the control queue.

### Known workarounds
None.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.1.1
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#/.Net Core 2.0

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 3/7/2020 00:00:00 -08:00 - 3/7/2020 08:00:00
- **Function App name**: 
- **Function name(s)**:
- **Azure region**: US-WEST
- **Orchestration instance ID(s)**:
- **Azure storage account name**: 

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.
I'll share the specifics at a later time if needed.

**Comment by Areson** [comment]
As a note, I'm not sure if the present behavior I'm seeing is because something went wrong initially, and now that the queue is full I'm seeing this behavior (e.g. a replay??) or if this is something that will always happen.

I have some ideas for some potential workarounds to mitigate this, such as creating new EntityId's based on timestamps to partition the data across multiple durable entities. I have not tried them yet but I was hoping to be able to avoid that and use a single, long-lived entity per message type I'm trying to fan-in.

**Comment by amdeel** [comment]
Hey @Areson I investigated your issue and found that you are using an old version of durable functions, as well as our default Task Hub name for your app. I recommend upgrading and specifying a Task Hub in your host.json. Let me know if that solves your issue!

I also found an exception in your code:
System.InvalidOperationException : Complex property AmazonAsin does not have a default constructor.
   at async AmazonPersistence.AmazonPersistence.HandleAmazonAsinDetail(Message message,ILogger log) at C:\Users\Ian - bg\Source\AmazonPersistence\AmazonPersistence\Amazon\AmazonPersistence.cs : 152

**Comment by Areson** [comment]
I had wondered that myself, and did briefly update the version of the durable functions library, but that did not help. I also tested with a name specified for the Task Hub in my host.json and that didn't help either.

My issue is this [this section](https://github.com/Azure/azure-functions-durable-extension/blob/cac24f8ec89bfe7f186a6020285f4e6a7a04224f/src/WebJobs.Extensions.DurableTask/Listener/TaskEntityShim.cs#L174) of the code. Starting orchestrations is a fire-and-forget operation, but it looks like the code that eventually sends the command to start the orchestration does so only after messages in the control queue have been processed. My application can generate a large volume of messages over a short period of time resulting in the orchestration not starting. Since I'm relying on the orchestration to start and to consume the contents of the durable entity, this causes the entity to simply grow larger and larger until timeouts start to occur.

While this may be the intended behavior, it seems problematic to have the orchestration be delayed in running for some unspecified period of time.

**Comment by Areson** [comment]
I'm re-evaluating this again to see if it is still an issue.

**Comment by amdeel** [comment]
@Areson Let me know if this is still an issue for you. If it is still an issue with 2.1.1, could you update me with a new instanceId and timeframe?

**Comment by Areson** [comment]
I'm still seeing this issue. Timeframe is the last 45 minutes (3/20/2020 1:45pm PST - 2:15pm PST). If a large number of messages are ready and quickly added to the durable entity, the orchestration isn't starting and the durable entity just times out trying to add all of the pending messages in the work queue. Same function app and storage as before. The durable entity instances are the only entries in the app instance table.

I'm turning off the app temporarily to disable the code that is using the durable entities so I can have the rest of the messages continue to process normally.

**Comment by Areson** [comment]
Any update on this? Do you need more recent examples?

**Comment by sebastianburckhardt** [comment]
I wonder if there is some misunderstanding as to how control queues work, or perhaps the control queue terminology? You mention that 

> the code that eventually sends the command to start the orchestration does so only after messages in the control queue have been processed. 

I don't think that is quite right - the code you are referencing sends the command after processing the current batch of operations being delivered to the entity (not after all messages in the control queue are processed). More likely is that the message for starting the orchestration is indeed sent, but is stuck in the control queue behind all the other messages. 

Messages are used for all communication between entities and orchestrations, including starting an orchestration from an entity, and all messages go through the control queues. Entities are implemented using orchestrations internally. So if messages are stuck in control queues, nothing can progress (new orchestrations cannot start, current orchestrations cannot progress, entities cannot receive operations). Control queues are roughly FIFO, so once they are full, new messages being sent will experience long delays in getting processed.

The question is, why are control queues getting so full in your scenario? This can be a symptom with many causes, it can be simply overload, or it could be a bug somewhere of course. 

If working as intended, control queues should remain short - that is the idea of this type of system architecture. If queues are filling up, more instances should start to keep them short. Of course there are some limits to what an implementation will scale to in practice; it can also depend on the number of control queues configured.

Can this help explain your observations?

**Comment by Areson** [comment]
Quite possibly. What I'm seeing makes sense if the message to start the orchestration is stuck behind other messages in the control queue.

As to why the control queues are getting so full, it's because I'm directing a large quantity of messages towards the durable entities. I'm attempting to create a method for doing a sort of "fan in" on a large set of messages that need to be persisted. Most of the "fan in, fan out" patterns in the documentation consist of a single messages spawning multiple, coordinated activities, which are waited on, consolidated, and then some action taken. 

In my case I have a large quantity of data being fed in via the service bus that needs to be persisted but there are throughput constraints, so trying to persist each individual piece of information is not feasible. My hope was to feed the messages through a durable entity, and have the durable entity persist groups of messages. As noted in the code snippet above I provided, the design was to have the durable entity start an orchestration once a certain threshold of messages was reached. If there are enough messages queued up for the entity, that orchestration never starts as the message to start it is buried behind thousands of messages for the durable entity. Eventually the function handling the durable entity times out because of the number of messages, and then restarts processing again, creating a loop that keeps going until I kill it.

As I noted earlier:

> While this may be the intended behavior, it seems problematic to have the orchestration be delayed in running for some unspecified period of time.

I still think this is true. While I think I understand better now why I'm seeing the behavior I'm seeing, it does seem to me that having orchestrations getting completely prevented from starting is not desirable.

Ultimately I need some way of doing a "fan in" like I described, and I had hoped that durable entities would solve the problem without needing to roll something more complicated. If that is not the case that's fine.

**Comment by Areson** [comment]
After reviewing this further I've decided that for now the number of messages that I'm trying to route through durable functions and/or entities is just too large over too short of a period of time. I know I can fall back to hosting something on-prem but I had hoped to avoid that. Per the discussion above there doesn't appear to be anything wrong with how things are working, and the issue I'm seeing is just a natural consequence of overloading the durable entities.

If anyone has suggestions as to where I could look to try and fine something to help with bundling/batching together groups of related messages at volume I would appreciate it. Otherwise this can be closed.
