### ISSUE TITLE
Orchestration stop working (stays in Running or Pending state)

### ISSUE THREAD

**Issue by stefrostik** [Azure/azure-functions-durable-extension#1265]
### Description

Hi, I have a solution with durable functions v2 and facing with a problem. In my implementation I have an orchestrator which waits for 5 external events to be received or timer fired (5 seconds). After that it sends a message to ServiceBus (aggregated response, is sending by separate ActivityFunction with output binding) .

To start orchestration I'm using EventHub trigger, so receiving one of 5 events from EventHub I'm checking if instance with specific (placed in event) id exists and creating new orchestrator if not exists + sending that event to newly created orchestrator. In case such orchestrator is already created (in case of receiving not the first of 5 event) I'm just sending that external event to orchestrator.

### Expected behavior
All event's are processed, all orhestrations completed and all notifications are sent to ServiceBus

### Actual behavior
In case of pushing events to event hub, time to time orchestration stopped working (there are a lot of Pending/Running instances which are not changing to Completed for a long time)

In case of sending events with a delay between them looks like in most of cases everything works.... But sometimes It stuck.

NOTE: sometime it works fine and able to process 500 events sent one by one and then stuck. Even restart of application doesn't help after that.. Need to clean up all azure tables and queues and start function again.

My questions are:

1) Is it known behavior?
2) Maybe I need to have some configuration for concurrency?
3) Maybe I need to have some 'Maximum running orchestrators' property?
4) Is it better to use v3 azure functions with v2 durable functions with aspnetcore3.1 or it is better to use old version V2 with aspnetcore 2.1?

### App Details
Tried both v2 and v3 azure function versions with v1 and v2 durable function versions and receiving the same problems in each case

### If deployed to Azure
It is deployed to Azure

### Code samples
![image](https://user-images.githubusercontent.com/20971368/76319208-8bc2fa80-62e7-11ea-8771-1cf43ded5b20.png)
![image](https://user-images.githubusercontent.com/20971368/76319744-54a11900-62e8-11ea-8927-c86fbd97e0c0.png)

**Comment by stefrostik** [comment]
I tried to simplified it a bit, and changed logic for waiting only for 2 external events. Then I did the test, pushed events to the event hub 1000 events (500 different orchestrators should be triggered as a result of if), I was pushing 4 events per second, and monitoring HubInstances. First time everything was fine, everything completes very fast, was only 1-2 Pending/Running orchestrator on each refresh of table, but after processing approx 200 event something went wrong and amount of Pending orchestrators started increasing. Each new event received become Pending orchestrator. After publishing all 1000 events to the event hub it takes some time all orchestrators completed. And after that I am able to process again first 200 events fast and after that it again started stuck in a Pending for some time.

![image](https://user-images.githubusercontent.com/20971368/76336445-afde0600-62fe-11ea-8224-db4747d811bb.png)

Can't understand, maybe there is some kind of resources lack. I'm using plan-bonuscalc-dev (S1: 1) appservice plan

**Comment by stefrostik** [comment]
Tried one more thing, changed EventHub trigger function to have an input as a batch (not to do checkpoints on each event, thought that maybe azure storage is a bottleneck), at the beginning again everything was fine, but then after 200 events problem reproduced. So still don't have a workaround.

**Comment by ConnorMcMahon** [comment]
@stefrostik 

Could you provide us with some sample orchestration instance ids that are stuck in the pending state, as well as timestamps and the region you are running in?

**Comment by stefrostik** [comment]
Hi @ConnorMcMahon , I have did the same test today (even increased amount of events, configured to wait for 5 external events). I run 1-s batch of 2500 events (500 unique orchestration), after completion of 100 orchestrators (500 events) amount of Pending and Running started growing up, and when load gone (sending events to event hub finished), in some time (5-10 minutes) almost most of them were completed. But still there are 3 orchestrators which are in Running state for now
[RunningAfterCompletedBatchOf2500Events.txt](https://github.com/Azure/azure-functions-durable-extension/files/4317163/RunningAfterCompletedBatchOf2500Events.txt)
I'm attaching file with examples
Region is: West Europe

**Comment by stefrostik** [comment]
After that I run one more batch of events (5000 events) and first 1000 of them were processed fine (right after sending to the event hub) and then again it starts being stuck for some time and after 10 minutes almost all orchestrators completed, but few of them are still running. My assumption that for some reasons azure storage queues are not working properly after some load..

**Comment by stefrostik** [comment]
Hi @ConnorMcMahon , do you have any updates on this?

**Comment by ConnorMcMahon** [comment]
@stefrostik 

Sorry for the delay. I am on call this week into next week, which has taken away time from my ability to investigate GitHub issues.

@amdeel, if you have bandwidth, could you help this customer out? Otherwise I will resume this investigation as soon as possible.

**Comment by stefrostik** [comment]
Hi @ConnorMcMahon and @amdeel. The issue still exists and reproducing most of the time after some load. (time to time only slow performance after some point, time to time some running orchestrators stuck). Would be nice if you can analyze it)

**Comment by stefrostik** [comment]
Looks like this problem occures when multiple messages comes concurrently for the same instanceId, and they are trying to be created at the same time. In this point, something went wrong, and orchestrators starting stuck. What i did: I used distributed lock with redis cache, and locked part of code which receives orchestrator status and creates new instance if it doesn't exists. After that change I wasn't able to reproduce my problem, and it's very strange than durable functions are not handling such situations in a proper way. Do you know why they can stuck after such situation, and can I somehow avoid this problem without locking on creating new instances?

**Comment by stefrostik** [comment]
Hi, @amdeel , any updates on this?

**Comment by amdeel** [comment]
Hi @stefrostik. Thanks for waiting for a response. I found this to be a known related to #367. The problem is that two instances with the same InstanceId are being started at the same time. This is leading to a lot of storage issues where message duplication is found.

This is why your solution appears to have worked to act as a global lock around starting a new orchestration instance. You could also try adding the [Singleton] attribute to your EventHubs trigger function or take a look at this solution for another option: https://github.com/Azure/azure-functions-durable-extension/issues/1272#issuecomment-601825205

**Comment by stefrostik** [comment]
Hi @amdeel , thank you for the response, I'm just wondering that DurableFunctions doesn't have such build functionality. Do you know if it is planned to implement this, at least not to stuck / slow down orchestrators in those situations?

**Comment by cgillum** [comment]
@stefrostik yes, this is something we plan on fixing. #367 tracks doing this work (we've been wanting to fix it for a long time, but have had trouble fitting it into our schedule).
