### ISSUE TITLE
[Doc] Create documentation for global limitations (persistence size, threading, timer duration,...)

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/azure-functions-durable-extension#127]
When using the Durable Functions out of the box, without looking at the internal implementation, understanding the limitations is not obvious.

For example, the event sourcing is happening inside Table Storage according to [this link](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview#storage-and-scalability), so it means that we are facing the constraint of the Table Storage table entity max size, as seen [here](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#storage-limits). For a Durable Function user, it means that the input/output states from the functions need to fit inside that 1MB limitation from Table Storage. Similar thing for input that goes into a Storage Queue, and so on.

Developers should not know the internal implementations to take decisions.

Related:  https://github.com/Azure/azure-functions-durable-extension/issues/26

**Comment by gled4er** [comment]
Hello @cgillum,

If you agree, I want to help with this issue.

Please let me know if you have any directions in order to shorten the review process. 

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

I think this is the only issue that is not assigned for the GA milestone.

Let me know if you have in mind high level instructions so I can help.

I am not sure how much time we will have to implement it but I can work on it from 10 AM JST if this is acceptable for you.

Thank you!

**Comment by cgillum** [comment]
I actually think we should already be covered for this.

* Message size limitations have been lifted per #26.
* Custom status query limitations are documented as part of this docs PR: https://github.com/MicrosoftDocs/azure-docs-pr/pull/39707
* All other limits, including throughput limits, should be covered by the performance documentation, which is going out for Build: https://github.com/MicrosoftDocs/azure-docs-pr/pull/38970

**Comment by SeanFeldman** [comment]
All PR links are broken @cgillum and no way to track down which documents include those changes.
