### ISSUE TITLE
Configure ManagedIdentityTokenSource to work with government clouds

### ISSUE THREAD

**Issue by bachuv** [Azure/azure-functions-durable-extension#1279]
This issue is pulled from a comment made in the ["Allow custom polling behavior in CallHttpAsync() for long-running endpoints"](https://github.com/Azure/azure-functions-durable-extension/issues/1183) issue.

The comments say:
"Finally, the `ManagedIdentityTokenSource` that you can provide doesn't let you override the `azureAdInstance` constructor for the underlying `AzureServiceTokenProvider`, which prevents you from using it against Azure Government."

**Comment by BlackstarSolar** [comment]
Additional the `ManagedIdentityTokenSource` does not allow access to the `tenantId` parameter of the underlying `AzureServiceTokenProvider.GetAccessTokenAsync`.
