### ISSUE TITLE
DurableFunctionsHubHistory is serializing inputs with the $type which could cause breaking changes.

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/azure-functions-durable-extension#128]
Hi! 

I just saw in the DurableFunctionsHubHistory table that serialization for Input of a workflow is using a '$type' property ("$type":"My.Namespace.ClassName, My.Assembly") for an EventType of ExecutionStarted, which in my view is usually a big "no" considering the unforeseen breaking changes that this kind of serialization provides. 

Considering that we are already providing the type when deserializing from the context that information is not necessary to keep in the payload. Moreover it means that fixing a typo in the class name or namespace that I use to generate the payload with be a breaking change which is not usually something expected with JSON payloads. 

Currently, when fetching my input from a workflow, I directly provide the class which I want to use for deserialization:
`var input = _orchestrationCtx.GetInput<My.Namespace.ClassName>();`

I think that issue adds more importance to issue #65, to prevent payload breaking changes by allowing developers to customize how to store and restore data over time.

**Comment by markheath** [comment]
Having `$type` annotations allows you to support the case where the object being serialized defines property with a base class, and the objects being serialized use a derived type.

And the presence of `$type` shouldn't prevent you from deserializing to an alternative type with the same property names. Newtonsoft supports this out of the box. 

The trouble is Newtonsoft doesn't let you have both behaviours at once. You need control over `JsonSerializerSettings.TypeNameHandling` on deserialization to choose whether to use the types or allow deserializing into a completely different type. So I agree that some kind of extensibility point as discussed in issue #65 would be helpful.

**Comment by cgillum** [comment]
Actually, for user-defined inputs and return values, we should already be using `TypeNameHandling.None`. Are you actually seeing `$type` annotations for your user-defined types?

I *do* expect to see `$type` annotations for certain built-in types, like `TaskMessage`, which is a wrapper object for inputs and return values. I don't expect to see `$type` annotations for the `Input` and `Result` fields of these types. If you are seeing those, then I agree we should fix that (I'm actually mostly concerned about the security implications of including `$type`).

**Comment by SimonLuckenuik** [comment]
I just had a look, for an EventType _ExecutionStarted_, the _Input_ property contains $type in the DurableFunctionsHubHistory table. I also have $type in an EventType _ContinueAsNew_ in the _Result_ property. For an EventType _ExecutionCompleted_, however, the _Result_ property doesn't contain $type.

**Comment by SimonLuckenuik** [comment]
The _DurableFunctionsHubInstances_ table is also saving the _Input_ property with $type.

**Comment by cgillum** [comment]
Agreed this is not ideal and that we should try to remove our usage of $type in places where it's not strictly needed.

**Comment by ConnorMcMahon** [comment]
You can now have more control over this yourself by injecting `IMessageSerializerSettingsFactory` (introduced in v2.1). Adding official documentation for this as a part of #1208

**Comment by ConnorMcMahon** [comment]
We now have serialization documentation.
