### ISSUE TITLE
taskhub.json blob not updating after increasing partition count.

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1285]
### Description
During an incident investigation, I found the case where an app still had a value for `PartitionCount` of 4 in their `taskhub.json` blob even though their app currently was using 16 partitions. This lead our scaling infrastructure to ignore 12/16 of the control queues, meaning the app could not activate for hours until an orchestration happened to fall in one of the 4 partitions the scale controller was looking at.

**Comment by ConnorMcMahon** [comment]
pushing out of 2.2.2.

**Comment by ConnorMcMahon** [comment]
The workaround for this is to manually edit the taskhub.json file. 

This bug should only impact consumption and premium plans.

**Comment by mpaul31** [comment]
@ConnorMcMahon I just ran into this as well. Nothing out of the ordinary, just updated the partitionCount in host.json.

is this the same issue where the code is looking for storageOptions instead of storageProvider?

the problem i am in now is i (developers) do not have access to manually modify taskhub.json.

**Comment by ConnorMcMahon** [comment]
@mpaul31,

I do not believe this is the same issue, as I found this separately. I will see if we can get this into 2.4.0 releasing at the end of the month.

**Comment by ConnorMcMahon** [comment]
Unfortunately, this will likely get pushed to October release. Hopefully the fix will be in early October, and we can do a prerelease version of DurableTask.AzureStorage on myget so people can get this fix shortly.

**Comment by ConnorMcMahon** [comment]
Tracking [here](https://github.com/Azure/durabletask/pull/469)

**Comment by ConnorMcMahon** [comment]
The pull request linked has been merged, and this will release with v2.4.0
