### ISSUE TITLE
Analyzer - Does not pick up activities found in dependencies

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-functions-durable-extension#1288]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

We currently have a number of function activities which we share code and reference using the `<FunctionsInDependencies>true</FunctionsInDependencies>` project setting. These activities seem to still show the DF109 warning from the analyzer

### Expected behavior
> A clear and concise description of what you expected to happen.

Checks are performed for activities found in dependencies and no warning shown

### Actual behavior
> A clear and concise description of what actually happened.

Warning is currently shown for activities found in dependencies

### Relevant source code snippets
```csharp
Project A

        var jobEntity = await context.CallActivityWithRetryAsync<JobEntity>("GetJobEntity", _retryOptions,
            new InvestigationJobMessage { InvestigationKey = message.InvestigationKey, JobNumber = message.JobNumber });

Project B, dependency of A
        [FunctionName(JobConstants.GetJobEntityActivityName)]
        public async Task<JobEntity> GetJob([ActivityTrigger] InvestigationJobMessage message, ILogger log)
        {
```

### Known workarounds
> Provide a description of any known workarounds you used.

None

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: .NET

### Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/4549796/77283777-266c0200-6d08-11ea-8834-de6205689b0a.png)

**Comment by amdeel** [comment]
Hello @wahyuen, our solution to this problem will come out in our next analyzer release (0.3.0).

If you are using <FunctionsInDependencies>true</FunctionsInDependencies>, put your function name in a constant variable. By doing this, we will "trust" the customer that this function does exist and will no longer flag this code with a warning when the function is not found in this project. Unfortunately, we will not be able to analyze the input or return type to these functions.

**Comment by wahyuen** [comment]
Hi @amdeel , thanks for the reply!

Just to clarify, we've noticed that seems to be a number of ways to reference a function. Would you be able to indicate, with your next set of changes, which of these should stop the warning from showing up?

1. Direct string reference (this **should** generate a warning??)
```csharp
await context.CallActivityAsync("SomeFunctionInAnotherDependency")
```

2. Reference a constant (this **should not** generate a warning??)
```csharp
const string foo = "SomeFunctionInAnotherDependency";
await context.CallActivityAsync(foo);
```

3. Reference based on `nameof` expression (I'm hoping this **should not** generate a warning??)
```csharp
await context.CallActivityAsync(nameof(SomeFunctionInAnotherDependency));
```

**Comment by amdeel** [comment]
Hey @wahyuen. Sorry about the delay, I missed this reply.

With this analyzer change (Analyzer version 0.3.0), we will no longer put warnings on constants used in CallActivityAsync. So, only #2 of your examples above would not generate a warning when calling a function that does not exist in the project.
