### ISSUE TITLE
Azure functions running location

### ISSUE THREAD

**Issue by Terricide** [Azure/azure-functions-durable-extension#129]
In the example BackupSiteContent.cs the file names are gathered in one function and uploaded in another function to blob storage.

Is there a guarantee that the two functions are running on the same instance? I mean if I upload to a temp folder in one azure function and then using that local file path use another azure function to upload it to blob storage would those for sure be running on the same instance/device/pc etc...

IE. E2_BackupSiteContent calling E2_CopyFileToBlob. 

Thanks,
Mark

**Comment by cgillum** [comment]
That's a good question to clarify. The assumption is that this sample is running either on a single machine (e.g. local debugging) or in the Azure Functions hosting environment. In the latter case, all instances share the same file system, so it doesn't matter whether the two function invocations are running on the same VM or not. The exception to this rule is if the content being backed up is from a machine-local location, like D:\local or %TEMP%. In that case, instances running on different machines will not see the same contents, and this sample will not work correctly.
