### ISSUE TITLE
SubOrchestrator gets stuck awaiting inside Task.WhenAll

### ISSUE THREAD

**Issue by ltrain777** [Azure/azure-functions-durable-extension#1291]
### Description
Main orchestrator is fanning out subOrchestration and waiting for the first one to complete with await Task.WhenAny(). SubOrchestration never returns (even through all the execution is launched and completed).  If I change the fan out to use ActivityTrigger, the Activity properly returns and await Task.WhenAny() properly give a task back. 

### Expected behavior
SubOrchestrator to return to WhenAny() once execution is done.

### Actual behavior
SubOrchestration is awaited and never returns.  This happens even though there is only one task to await.
comment out line 24 or 25 to repro SubOrch vs Activity.
I couldn't really tell if #698 is related as I couldn't see the code change the OP made.

### Relevant source code snippets
```csharp
using System.Collections.Generic;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;
using Microsoft.Azure.WebJobs.Extensions.Http;
using System.Linq;
using Microsoft.Extensions.Logging;
using System.Threading;

namespace Test
{
    public static class DurableFunctionsOrchestrationCSharp1
    {
        [FunctionName("DurableFunctionsOrchestrationCSharp1")]
        public static async Task<List<string>> RunOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            var outputs = new List<string>();
            var namesList = new List<string>(){ "Tokyo" };
            var taskList = new List<Task<string>>();
            var instanceId = context.InstanceId;
            foreach(var name in namesList){
                var subInstanceId = $"{instanceId}:{name}";
                var task = context.CallSubOrchestratorAsync<string>("DurableFunctionsOrchestrationCSharp1_HelloOrch", subInstanceId, name);
                // var task = context.CallActivityAsync<string>("DurableFunctionsOrchestrationCSharp1_Hello", name);
                taskList.Add(task);
            }
            Task<string> firstTask = await Task.WhenAny(taskList);
            var result = await firstTask;
            taskList.Remove(firstTask);
            outputs.Add(result);
            return outputs;
        }

        [FunctionName("DurableFunctionsOrchestrationCSharp1_Hello")]
        public static async Task<string> SayHello([ActivityTrigger] string name, ILogger log)
        {
            log.LogInformation($"Saying activity hello to {name}.");
            await doWork(name, log);
            return $"Hello activity {name}!";
        }

        [FunctionName("DurableFunctionsOrchestrationCSharp1_HelloOrch")]
        public static async Task<string> SayHelloOrch([OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
        {
            var name = context.GetInput<string>();
            log.LogInformation($"Saying orchestrator hello to {name}.");
            await doWork(name, log);
           //await context.CreateTimer(context.CurrentUtcDateTime.AddSeconds(5), CancellationToken.None);
            return $"Hello orchestrator {name}!";
        }

        static Task<bool> doWork(string name, ILogger log){
            
            log.LogTrace($"Start {name}");
            return Task.Run(() => {
                var random = new System.Random(1);
                var delay = random.Next(1, 10) * 5000;
                System.Threading.Thread.Sleep(delay);
                log.LogTrace($"Finished {name}");
                return true;
            });
        }

        [FunctionName("DurableFunctionsOrchestrationCSharp1_HttpStart")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestMessage req,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger log)
        {
            // Function input comes from the request content.
            string instanceId = await starter.StartNewAsync("DurableFunctionsOrchestrationCSharp1", null);

            log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

            return starter.CreateCheckStatusResponse(req, instanceId);
        }
    }
}
```

### Known workarounds
None for SubOrchestration. As stated above ActivityTrigger doesn't have this problem during fan-out with Task.WhenAny().  The reason I'm using SubOrchestration is to do some WaitForExternalEvent() in the fan-out.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.31" />
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
 <TargetFramework>netcoreapp2.1</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
- **Programming language used**: C# 
- I have .netcore 3.1.101 with older versions of .netcore 2.1 and 2.2

**Comment by ltrain777** [comment]
Ok, I think I figured it out. Orchestrators need to wrap awaited task in an Activity. Once I had my subOrchestrator await my Activity that called doWork, it the subOrchestrator returned properly from the Task.WhenAny().

Can I get a quick rundown on why the await has to happen in an activity?  Something to do with checkpointing?

**Comment by amdeel** [comment]
Awaits in an orchestrator on non-durable tasks wont work correctly because of the reply behavior. With an acitvity await, we will store the result of the activity in our history events. When you await a custom method like that, the orchestrator will just get stuck there and will never get the result.

This might be a good thing to add an analyzer for!
