### ISSUE TITLE
OrchestrationAnalyzer throwing InvalidCastException

### ISSUE THREAD

**Issue by seancolonello** [Azure/azure-functions-durable-extension#1292]
### Description
The below compile time warning occurs after upgrading to version 2.2.0.

Warning	AD0001	Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.OrchestratorAnalyzer' threw an exception of type 'System.InvalidCastException' with message 'Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.LocalFunctionStatementSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax'.'.

### Expected behavior
No warning, no exception thrown in analyzer.

### Actual behavior
A warning due to an analyzer exception.

### Relevant source code snippets
My best guess is that it's coming from the first line in the below method of OrchestrationAnalyzer.
```csharp
private void AnalyzeMethod(SyntaxNodeAnalysisContext context)
{
	var declaration = (MethodDeclarationSyntax)context.Node;
	if (!SyntaxNodeUtils.IsInsideOrchestrator(declaration)
		|| !SyntaxNodeUtils.IsInsideFunction(declaration))
	{
		return;
	}
	
	if (this.semanticModel == null)
	{
		this.semanticModel = context.SemanticModel;
	}

	this.orchestratorMethodDeclarations.Add(declaration);
}
```
### App Details
- Durable Functions extension version: 2.2.0
- Azure Functions runtime version: 2.0
- Programming language used: C#
- IDE: Visual Studio 16.5.1

**Comment by amdeel** [comment]
Thanks for bringing this to my attention!
