### ISSUE TITLE
404 Status from Table Storage every time a new orchestration is started

### ISSUE THREAD

**Issue by jenspettersson** [Azure/azure-functions-durable-extension#1297]
### Description
We have a Durable Function (orchestration) that starts once every hour (or manually via an HTTP trigger) and the actual behavior of the new orchestration works and completes successfully, but we always see a 404 in the logs every time a new orchestration is started. It's categorized as a "Failure" in a dependency when looking in the Azure Portal.

According to the logs, the table storage gets queried by an instance/partition key and when looking in the table, I can see the row afterwards, so it does get created.

### Expected behavior
Hard to say, but I wouldn't expect 404 failures in the logs

### Actual behavior
404 Status code from Table Storage call each time an orchestration is started

### Known workarounds
None, the orchestration is always started and finishes successfully. It's just a minor annoyance to see the "failures" in logs

### App Details

- **Durable Functions extension version**: v2.1.1 (Microsoft.Azure.WebJobs.Extensions.DurableTask)
- **Azure Functions runtime version**: 2.0
- **Programming language used**: C#

### Screenshots
![image](https://user-images.githubusercontent.com/125493/77736316-5a973980-700c-11ea-8dca-725ce41cb86c.png)
This is from the last 12 hours with 12 timer invocations and one manual, hence 13 "failures".

![image](https://user-images.githubusercontent.com/125493/77738058-6df7d400-700f-11ea-917c-042f49f1a764.png)
Detail

### If deployed to Azure
Can't show all the info here...

- **Timeframe issue observed**: Every hour last since first deploy (March 26)
- **Function App name**:
- **Function name(s)**:
- **Azure region**: West Europe
- **Orchestration instance ID(s)**: a52a23b1e4b5464e962ea7db073785ce (one of the 13)
- **Azure storage account name**:

**Comment by jenspettersson** [comment]
It's the request:

`GET {storageAccount}/{functionAppName}Instances` 

that returns 404

**Comment by amadard** [comment]
We ran into this as well, and dug into it to find out that there isnt any "Exists" command for the table, so the code is saying "Get, then check if Not Null", and it catches the 404.

**Comment by olitomlinson** [comment]
I'm wondering if you can register a custom App Insights `ITelemetryProcessor` that can filter out any 404 to your TaskHub Instances storage table?

**Comment by cgillum** [comment]
This issue gets raised a lot, and we're hoping to get it fixed soon. We have another issue tracking here: https://github.com/Azure/azure-functions-durable-extension/issues/593.
