### ISSUE TITLE
Full support for activity functions in languages other than C#

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#13]
Activity functions should be able to be written in languages other than C# since they don't have a hard dependency on any object model. We close to having this today, but some work is required in the binding extensibility provided by the WebJobs SDK.

The required WebJobs SDK issue can be found here: https://github.com/Azure/azure-webjobs-sdk/issues/1104 

With this fix, it should be possible to implement activity functions in all of our supported languages. Orchestrator functions will still need to be in C#.

**Comment by cgillum** [comment]
This is a breaking change because it fundamentally changes how return values are processed by bindings in Azure Functions.

**Comment by cgillum** [comment]
This is partially fixed in PR https://github.com/Azure/azure-functions-durable-extension/pull/18. However, there are still additional fixes required in the Azure Functions script host to fully enable cross-language support: https://github.com/Azure/azure-webjobs-sdk-script/issues/1422

**Comment by cgillum** [comment]
Katy, this is basically the work that you've already started regarding return values in JavaScript.

**Comment by nevercast** [comment]
Is this blocked by https://github.com/Azure/azure-webjobs-sdk-script/issues/1921 ?

**Comment by cgillum** [comment]
Yes, although I believe this blocking issue has already been fixed. @kashimiz can you confirm?

**Comment by nevercast** [comment]
If that's the case, there could be other things from Sprint 14 also not marked as closed. https://github.com/Azure/azure-webjobs-sdk-script/milestone/38

Will subscribe for updates,
Thanks.

**Comment by nevercast** [comment]
With https://github.com/Azure/azure-webjobs-sdk-script/pull/2049 and https://github.com/Azure/azure-webjobs-sdk/pull/1424 merged. Is this issue in scope for the near future?

**Comment by cgillum** [comment]
Yes, those were the main blockers. We should be able to handle the rest of the work in this repo.

The next step is for us to come up with a protocol which can translate the DTFx orchestration inputs/outputs to/from JSON. This will enable a cross-language story for writing orchestrations.

After that, we need to create the JavaScript-specific programming model for writing orchestrations which implements the JSON protocol. @christopheranderson has started some investigative work into this.

**Comment by kashimiz** [comment]
I'm actively working on this.

**Comment by cgillum** [comment]
And it's done! See here for details: https://github.com/Azure/azure-functions-durable-js
