### ISSUE TITLE
Azure Functions Durable Orchestration enhancements

### ISSUE THREAD

**Issue by MedAnd** [Azure/azure-functions-durable-extension#1305]
**Is your feature request related to a problem? Please describe.**

* [A] WaitForExternalEvent currently requires another function to call RaiseEventAsync(...) via a DurableClient whereas the run-time could facilitate routing based on inputs and filters.

* [B] Calling applications either have to continually poll a HttpTrigger function which in turn is using DurableClient GetStatusAsync or the HttpTrigger function has to internally poll via DurableClient GetStatusAsync, assuming the orchestration completes in under 90 seconds & the calling application does not bail on the HttpTrigger function. Both options feel like resource efficiency anti-patterns & vastly complicate logic. External calling functions may also require to report on & correlate progress whilst an orchestration is still running.

* [C] Attributes for 3rd party bindings such as TwilioSms cannot be overridden from within a function activity which complicates multi-tenant implementations. 

* [D] Durable Function capacity planning guidance does not seem to exist.

**Describe the solution you'd like**

* [A] Support various input bindings also for DurableOrchestrationContext WaitForExternalEvent, for true pub / sub. Consider a design similar to the BizTalk orchestration engine where bindings may have filters configurable at both design and run-time.

* [B] Create best practice documentation and c# samples clarifying how sync to async scenarios should be implemented where the caller is latency sensitive & requires more synchronous results. For example a complete sample using Azure Functions bindings for SignalR Service which returns results to the calling function else calling function receives a timeout. Improve existing samples and documentation with best practices around long running orchestrations and progress state correlation. Instead of RaiseEventAsync returning just a "A task that completes when the event notification message has been enqueued.", consider also supporting / returning some type of correlationId which the calling application can then use to track the internal progress of the Raised Event within an orchestration whilst the orchestration status is still Running. I have implemented this manually and can provide a working example to better clarify.

* [C]  Allow the TwilioSms From property to be overridden from within a function activity or remove this property and force each function to provide a value via other means.

* [D] Create capacity planning guidance & possibly a calculator with performance and load test results for Durable Functions so that customers can better plan what resources they need to deploy for production workloads.

**Links**

https://github.com/Azure/azure-functions-durable-extension/issues/1183

**Comment by ConnorMcMahon** [comment]
@MedAnd, I think this issue covers far too much ground to be covered in a single issue. I would file a separate issue/discussion for each of these.
