### ISSUE TITLE
Durable Functions - Installing runtime extensions is taking longer than expected 

### ISSUE THREAD

**Issue by prawin2k** [Azure/azure-functions-durable-extension#132]
Hi Team,
I'm getting the error "Installing runtime extensions is taking longer than expected" while creating the Durable Functions.

Thanks,
Praveen Kumar Sreeram
![durablefunctions-error](https://user-images.githubusercontent.com/10738750/34918441-73621b5e-f978-11e7-97b9-1665fe933cbc.png)

**Comment by cgillum** [comment]
This is a known issue with installing extensions in the Azure Portal. Unfortunately the extension installation process requires doing a lot of file I/O and the underlying file system for Consumption plans is quite slow in many cases. Does it eventually work if you continue to wait?

An alternative approach is to develop locally using VS Code and then deploy to Azure. Instructions for that can be found here: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-install#visual-studio-code

@paulbatum Is this issue tracked in any of the other functions repos? I would imagine people using any of our other extensions on v2 (graph binding, etc.) are hitting the same problems.

**Comment by prawin2k** [comment]
Hi Chris,
Thanks. It worked after sometime. 

Thanks,
Praveen
