### ISSUE TITLE
Possibility of accessfing FtpWebRequest in Activity function

### ISSUE THREAD

**Issue by madushann** [Azure/azure-functions-durable-extension#1327]
I have a requirement to use FtpWebRequest to download a file for FTP location and import the data to a database.

Is that possible to handle this kind of activity in side an activitytrigger function? I know there are limitations accessing IO operations. if you can please share a resource for more information about this limitations and how to handle it

**Comment by anthonychu** [comment]
The I/O restrictions are only for orchestrators, so you can use `FtpWebRequest` in an activity function like you can in a typical Azure Function.

**Comment by madushann** [comment]
Thank you for the information.

**Comment by madushann** [comment]
So Activityfunction operates same as the general azure function

**Comment by anthonychu** [comment]
Correct. Do try to limit the amount of data you pass to and return from the activity function, as those are passed on queues and tables behind the scenes and can add some overhead.

**Comment by anthonychu** [comment]
Closing this as resolved. @madushann please let us know or open a new issue if you have further questions.

**Comment by madushann** [comment]
Not for now. Close it. Thank you
