### ISSUE TITLE
Analyzer - DF0104 missing description?

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-functions-durable-extension#1329]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

The current version of the analyzer appears to be missing some descriptive text in the warning to tell the user what the issue is, and perhaps how to resolve the issue

### Expected behavior
> A clear and concise description of what you expected to happen.

Some indication of what the issue is and maybe how to solve it

### Actual behavior
> A clear and concise description of what actually happened.

Only seems to show the line of code affected and the warning code. I believe it should be along the lines of some threading issue and running async threads?

We fixed the warning by adding the `TaskContinuationOptions.ExecuteSynchronously` value to the `ContinueWith` call.

### Relevant source code snippets
```csharp
// insert code snippet here
findOrCreateTasks.AddRange(saveObjectsMessage.ObjectsToSave
                .Select(conversation => context.CallActivityWithRetryAsync<ICollection<Conversation>>("SaveConversationOrFindForUpdate", _retryOptions, conversation)
                    .ContinueWith(x =>
                    {
                        foreach (var dbConversation in x.Result)
                        {
                            conversationsToUpdateDictionary.AddOrUpdate(dbConversation.ObjectKey, dbConversation, (key, oldValue) => dbConversation);
                        }
                    })));
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: .NET

### Screenshots
> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/4549796/79713503-8c947680-8300-11ea-8102-fd90c507f387.png)

**Comment by amdeel** [comment]
Right now these OrchestratorAnalyzer deterministic code violations only are using a generic formatted message to describe the warning. 

'{0}' violates the orchestrator deterministic code constraint.

I think your message was cut off here. It might be a nice enhancement to add more descriptive warning messages, though.
