### ISSUE TITLE
Durable Functions - No Such API

### ISSUE THREAD

**Issue by prawin2k** [Azure/azure-functions-durable-extension#133]
Hi Team,
I'm getting a "No Such API" message when I try to run my Orchestrator function. Below is the response that I get when I run my HttpStarter funtion.
When I try to run my Status Query url, I get the "No Such APi" message.

{
    "id": "7ac705fbdd77412c8d1bb4e318f135dc",
    "statusQueryGetUri": "https://mydurablefunction.azurewebsites.net/runtime/webhooks/DurableTaskExtension/instances/7ac705fbdd77412c8d1bb4e318f135dc?taskHub=DurableFunctionsHub&connection=Storage&code=89OaH7ZIyAOI/7zaGfK6iBdzy4cfyaVSPJ2/Yu8wrlC0Nwk5Y6oPSg==",
    "sendEventPostUri": "https://mydurablefunction.azurewebsites.net/runtime/webhooks/DurableTaskExtension/instances/7ac705fbdd77412c8d1bb4e318f135dc/raiseEvent/{eventName}?taskHub=DurableFunctionsHub&connection=Storage&code=89OaH7ZIyAOI/7zaGfK6iBdzy4cfyaVSPJ2/Yu8wrlC0Nwk5Y6oPSg==",
    "terminatePostUri": "https://mydurablefunction.azurewebsites.net/runtime/webhooks/DurableTaskExtension/instances/7ac705fbdd77412c8d1bb4e318f135dc/terminate?reason={text}&taskHub=DurableFunctionsHub&connection=Storage&code=89OaH7ZIyAOI/7zaGfK6iBdzy4cfyaVSPJ2/Yu8wrlC0Nwk5Y6oPSg=="
}

Thanks,
Praveen

**Comment by cgillum** [comment]
How are you invoking the `statusQueryGetUri`? Is it possible that there might be a typo or you need to surround the URL with quotes (if invoking using the command-line)?

**Comment by prawin2k** [comment]
I'm invoking it using Postman. It worked many times earlier.

**Comment by tohling** [comment]
When polling the uri set in `statusQueryGetUri`, you need to use `GET`, not `POST`.  Using `POST` will return the message,

```
{
    "Message": "No such API"
}
```

**Comment by prawin2k** [comment]
I recieved the error while I was accessing it using get method only.
Probably there was a minor glitch at that point of time. It got fixed
later. Thank you.

On 03-Feb-2018 2:39 PM, "Ling Toh" <notifications@github.com> wrote:

When polling the uri set in statusQueryGetUri, you need to use GET, not POST.
Using POST will return the message,

{
    "Message": "No such API"
}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Azure/azure-functions-durable-extension/issues/133#issuecomment-362792377>,
or mute the thread

**Comment by tohling** [comment]
@prawin2k, awesome! I will close this issue then. Thanks for the quick response. :-)

**Comment by prawin2k** [comment]
Thank you so much for all the efforts that you guys are putting on the
awesome products and services :-)

Praveen Sreeram
