### ISSUE TITLE
Does Activity function timeout?

### ISSUE THREAD

**Issue by madushann** [Azure/azure-functions-durable-extension#1331]
I have a OrchestrationTrigger which calls the ActivityTrigger SingleFeedActivity, activity is a long running process which has some database operations, after azure function max timeout period is reached activity function also seems to be timedout with below message in output. I trigger the Orchestration trigger using a http trigger. 

Output error:
Orchestrator function 'GetSingleFeedDurable' failed: The activity function 'SingleFeedActivity' failed: "Timeout value of 00:10:00 was exceeded by function: SingleFeedActivity". See the function execution logs for additional details.

Hosted under Consumption)  plan , I know max timeout for the plan is 10m but doesn't durable functions allow to run long running task by default? 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#timeout

**Comment by anthonychu** [comment]
Durable Functions supports long running tasks by allowing you to decompose long running functions into shorter activity functions. The Activity functions themselves have the same timeout limitations as regular Azure Functions.

Are you able to split up the work in your activity function into multiple activity functions, possibly using a suborchestration, if necessary?

**Comment by madushann** [comment]
Yes, of cause. Will look for that pattern. Thank you for the information.
