### ISSUE TITLE
Durable Orchestration and Activities correlation in Application Insights.

### ISSUE THREAD

**Issue by tvperez76** [Azure/azure-functions-durable-extension#1334]
**Is your feature request related to a problem? Please describe.**
As for now, Durable Functions functionality doesn't correlate between Orchestrator and the Activities in Application Insights.  All of the functions appear to be disjointed and the only way to correlate parent and child invocations is to view the logs from my storage account.

**Describe the solution you'd like**
In the "Performance" table in Application Insights, I would like a end-to-end view of the all the API and durable function calls in hierarchical format, and not just to the HttpTrigger point.

**Describe alternatives you've considered**
Other than view the storage account logs, none.

**Comment by olitomlinson** [comment]
@tvperez76 It’s possible that your needs might be met in the next release 2.3.0 - with this https://github.com/Azure/azure-functions-durable-extension/pull/1270

**Comment by tvperez76** [comment]
This is great.  Thank you @olitomlinson.  Is there a timeline for this feature being made available via  NuGet package.

**Comment by ConnorMcMahon** [comment]
Adding @TsuyoshiUshio, the main developer for this feature

We are looking to do an alpha release for this feature in the next week.

It likely will not be officially merged into the main package until at least 2.3.0, which will be in late May at the earliest.

**Comment by cgillum** [comment]
You can find more information here about the end-to-end tracing alpha release: https://medium.com/@tsuyoshiushio/durable-functions-distributed-tracing-71426fe2246f

**Comment by cgillum** [comment]
Also, we're currently using https://github.com/Azure/azure-functions-durable-extension/issues/939 to track the release of this feature.

**Comment by ismaan1998** [comment]
I configured host.json as mentioned in this article for [c#](https://github.com/Azure/azure-functions-durable-extension/blob/dev/samples/correlation-csharp/getting-started.md) and it worked for Python as well. Please mentioned it somewhere in Python Durable function's documents as well.
