### ISSUE TITLE
How to purge durable entity history with record deletion

### ISSUE THREAD

**Issue by panicoenlaxbox** [Azure/azure-functions-durable-extension#1335]
Hi,

I have a doubt and before programming a solution I would like to know if it is right.

We use durable entities and we want to delete the records that are saved in the "history" table storage (and I don't want to delete the table vía Storage Explorer, this is the more hardcore choice). So, I'm afraid because with sometime later I will have a lot of empty records and perhaps the performance will not be the better.

We have tried several solutions but all are the same: A schedule signal of delete the entity (Entity.Current.DeleteState();) or even a powershell to delete all the entities.

```
function DeleteEntities 
{
    param (
        [string[]]$keys
    )
    foreach ($key in $keys) { 
        $signalEntityUri = "$baseUrl/runtime/webhooks/durabletask/entities/VoiceCallEntity/$key`?op=Delete&code=$code"
        Write-Output $signalEntityUri
        Invoke-WebRequest -Uri $signalEntityUri -Method POST
    }
}

function GetEntities 
{
    param (
        [string]$continuationToken
    )
    $baseUrl = "your_base_url_goes_here"
    $code = "your_code_goes_here"
    $listEntitiesUri = "$baseUrl/runtime/webhooks/durabletask/entities/VoiceCallEntity?code=$code"
    $response = Invoke-WebRequest -Uri $listEntitiesUri -Method GET -Headers @{'x-ms-continuation-token' = $continuationToken}
    $body = $response | ConvertFrom-Json
    $continuationToken = $response.Headers['x-ms-continuation-token']
    $keys = $body | select -ExpandProperty entityId | select -ExpandProperty key | where { $_ -ne '' }
    return @{ 'continuationToken' = $continuationToken; 'keys' = $keys }
}

$result = GetEntities('')
DeleteEntities($result.keys)
while($result.continuationToken -ne '') 
{
    $result = GetEntities($result.continuationToken)
    DeleteEntities($result.keys)
}
```

I have not found a way of delete the entire record vía API, so my last intent will be to create an azure function with a timer trigger and with the help of API table storage, delete definitely the records in this table with null state. 

Am I missing anything more simple to achieve this result?

Thank you so much.

**Comment by sebastianburckhardt** [comment]
Yes, deleting the entity state leaves some metadata behind.

You can call `purgeInstanceHistoryAsync` to forcefully delete all the state including the metadata; however there are some precautions to be aware of since the metadata is sometimes needed (for example if entities are called again soon after being deleted).

For more info see the comment and following discussion in 
https://github.com/Azure/azure-functions-durable-extension/issues/931#issuecomment-591470878 

FYI, we also have an open feature request on automatically deleting the metadata (#1065).

**Comment by panicoenlaxbox** [comment]
Hello, @sebastianburckhardt 

My mistake was to think that some built-in api endpoints only applied to durable functions, for example, like you said "_purge single instance history_" but I have checked that if I pass ```@entityName@entityKey``` in the ```instanceId``` parameter, all the records all deleted from both tables (History and Instances). My final reflexion is a durable entity is, for all intents and purposes, a durable function, so whatever applies to durable function applies to durable entities, too. At least, in relation with built-in api endpoints, right?

In the other side, I understand that it's a delicated operation so I will do this kind of clean up when I I know it's safe and I prefer to wait for #1065, thank you for your advice

Thank you again

**Comment by panicoenlaxbox** [comment]
Hello,

I think that everything it's clear now, I paste a new powershell script that helps to remove/purge a entity, but I will close the issue, thanks

```
function GetEntities 
{
    param (
        [string]$entityName,
        [string]$continuationToken
    )
    $listEntitiesUri = "$baseUrl/runtime/webhooks/durabletask/entities/$entityName`?code=$code"
    Write-Host $listEntitiesUri
    $response = Invoke-WebRequest -Uri $listEntitiesUri -Method GET -Headers @{'x-ms-continuation-token' = $continuationToken}
    $body = $response | ConvertFrom-Json
    $continuationToken = $response.Headers['x-ms-continuation-token']
    $keys = $body | select -ExpandProperty entityId | select -ExpandProperty key | where { $_ -ne '' }
    return @{ 'continuationToken' = $continuationToken; 'keys' = $keys }
}

# what entity do you want to purge?
$baseUrl = ""
$code = ""
$entityName = ''

$result = GetEntities $entityName ''
$keys = $result.keys

while($result.continuationToken -ne '') 
{
    $result = GetEntities $entityName $result.continuationToken
    $keys += $result.keys    
}

# https://github.com/Azure/azure-functions-durable-extension/issues/1335
foreach ($key in $keys) { 
  $purgeSingleInstanceHistoryUri = "$baseUrl/runtime/webhooks/durabletask/instances/@$entityName@$key`?code=$code"
  Write-Output $purgeSingleInstanceHistoryUri
  Invoke-WebRequest -Uri $purgeSingleInstanceHistoryUri -Method DELETE
}
```
