### ISSUE TITLE
Orchestration instance stuck in pending status - Functions v2

### ISSUE THREAD

**Issue by Arestis** [Azure/azure-functions-durable-extension#1337]
I use my localhost storage emulator and i see that i still have this issue. I just learn Azure Durable 
but if i saw in other cases i do the same
`  if(string.IsNullOrEmpty(instance))
            {
                instance = await starter.StartNewAsync(nameof(OrchestratorFunction), data);
            }
           await starter.RaiseEventAsync(instance, nameof(OrchestratorFunction.CommandTrigger), data);`

But it happens sometimes, sometimes all works fine.

**Comment by ConnorMcMahon** [comment]
Unfortunately there are different potential causes for this issue.

If you could reproduce this in Azure and give us an instance id, Azure region, and timestamp, we would be able to look at some telemetry to help diagnose the issue.

**Comment by Arestis** [comment]
Okay. I will deploy it
Thanks!
