### ISSUE TITLE
Slowly sending events

### ISSUE THREAD

**Issue by Arestis** [Azure/azure-functions-durable-extension#1338]
I have issue with sending ExternalEvent. it send slowly,  sometimes after 10-15 min OrchestrationFunction receive event
`await starter.RaiseEventAsync(id, FunctionName, data);`
and after 10-15 minutes it continue work in this 
`await context.WaitForExternalEvent<string>(FunctionName);`
I use localhost(storage emulator) for it. Maybe i should set up host
i did not find this info

**Comment by ConnorMcMahon** [comment]
What sort of load are you putting on your application?

Queue messages (including events sent) are handled in a FIFO ordering, so if you are putting extreme load on your application, it is possible it would take quite a bit of time to get through all of the events.

Otherwise, like I mentioned in a previous thread, reproing this in Azure and providing us with a region, timestamp, and instance id we can take a look to see what is causing the delay.

**Comment by Arestis** [comment]
> What sort of load are you putting on your application?
> 
> Queue messages (including events sent) are handled in a FIFO ordering, so if you are putting extreme load on your application, it is possible it would take quite a bit of time to get through all of the events.
> 
> Otherwise, like I mentioned in a previous thread, reproing this in Azure and providing us with a region, timestamp, and instance id we can take a look to see what is causing the delay.

External events are slowly in my localhost. I use local emulator. Sometimes my orchestration functions catch event after 10 minutes

**Comment by ConnorMcMahon** [comment]
@Arestis 

I am aware the issues you are experiencing are using the local emulator. Unfortunately, we do not have enough information to diagnose the issue at this time.

Your options are:

1. Give us a reproduction that we can run locally on our machines to debug. Ideally, this reproduction would involve the minimum amount of code/setup to actually reproduce the issues you are seeing.

2. Reproduce the issue in Azure, and provide us with the region, timestamp, and instance id so we can look at our telemetry.

Without those things, we can not help you diagnose the issue.

**Comment by Arestis** [comment]
Ok, thanks for answer
