### ISSUE TITLE
Orchestration started but status returns 404 until complete

### ISSUE THREAD

**Issue by vandersmissenc** [Azure/azure-functions-durable-extension#134]
I created a precompiled function with version `1.1.0-beta2 ` of durable task and deployed to azure functions on version `1.0.11388.0` and saw that I would receive a 202 response immediately but when hitting the `statusQueryGetUri` I would receive a 404.  It seemed similar to issue #126 but I was advised to create a different issue due to differences.

Checking the `DurableFunctionsHubHistory ` storage table there are no entries for the matching id returned in the 202. After the long running task completes I see an entry get created in the storage table and I no longer receive the 404 message. When running locally with the storage emulator these issues are not present and everything works as expected.

My orchestrator is almost identical to [HttpStart.cs](https://github.com/Azure/azure-functions-durable-extension/blob/master/samples/precompiled/HttpStart.cs) except that I read a specific type from the request content instead of an object. I just ran it and the instance ID was `7b8b6634-c30c-4be0-8c9f-5bf2cff58809` in `East US 2`. The orchestrator started at `2018-01-09T13:37:00.899` and completed at `2018-01-09T13:37:00.930` with a 202 response. I attempted to hit the `statusQueryGetUri `and received a 404. The function that it kicks off started at `2018-01-09T13:37:08.659` and completed at `2018-01-09T13:44:19.107` after which time I was able to hit the `statusQueryGetUri ` and receive a 200 response.

**Comment by cgillum** [comment]
The 404 behavior should be solved via this PR by @gled4er: https://github.com/Azure/azure-functions-durable-extension/pull/168

**Comment by SimonLuckenuik** [comment]
@cgillum, what is the expected release date for Beta 3?

**Comment by cgillum** [comment]
This week. It should be in the milestone description (I updated it yesterday).
