### ISSUE TITLE
Unit test - IDurableOrchestrationContext and CreateEntityProxy

### ISSUE THREAD

**Issue by madhumlr** [Azure/azure-functions-durable-extension#1340]
Hi
As I understand, to call or signal an entity from within an orchestration, CreateEntityProxy can be used, along with the interface type, to generate a proxy for the entity. This proxy can then be used to call or signal operations: ([https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities#accessing-entities-through-interfaces](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities#accessing-entities-through-interfaces)).

Documentation does not say anything about unit test cases and mocking up these proxy object.

Since CreateEntityProxy is just an extension, we will not be able to mock this method. Can you guide us how do we mock CreateEntityProxy method in IDurableOrchestrationContext ?

Regards,
Madhu

**Comment by olitomlinson** [comment]
@madhumlr  I believe this is being tracked here https://github.com/Azure/azure-functions-durable-extension/issues/1224

Until this has been reworked, the general guidance is to wrap the the call to `CreateEntityProxy` with your own interface, and then mock that interface in your test instead.

```
    public interface IFooEntityFactory
    {
        IFooEntity CreateEntityProxy(IDurableOrchestrationContext context, string id);
    }

    public class FooEntityFactory : IFooEntityFactory
    {
        public IFooEntity CreateEntityProxy(IDurableOrchestrationContext context, string id)
        {
            return context.CreateEntityProxy<IFooEntity>(new EntityId(nameof(FooEntity), id));
        }
    }
```

```
public class MyOrchestration 
{
        private IFooEntityFactory _fooFactory;
        public MyOrchestration(TelemetryClient tc, IFooEntityFactory _fooFactory = null)
        {
            _factory = factory;
        }
        [FunctionName("MyOrchestration")]
        public async Task<object> RunOrchestratorAsync([OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            ...
            var fooEntityProxy = _fooFactory?.CreateEntityProxy(context, fooId) 
                ?? new FooEntityFactory().CreateEntityProxy(context, fooId);
        }
}
```

I believe that there is no access to IDurableOrchestrationContext in the DI pipeline, so you have to do some form of hand-rolled DI like above.
