### ISSUE TITLE
Configure MaxQueuePollingInterval Differently in Stage and Prod Slots

### ISSUE THREAD

**Issue by roend83** [Azure/azure-functions-durable-extension#1341]
We're deploying our durable function using a slot swap deployment.  I would like to be able to configure the MaxQueuePollingInterval differently in the stage and prod slots.  I'm able to do this for settings like HubName because they can be configured in application settings and referenced using the "%SettingName%" syntax.  However, this approach does not work for MaxQueuePollingInterval because the value is parsed as a timespan.  Is there any way to get this to work without having to edit the host.json as part of the deployment?

**Comment by ConnorMcMahon** [comment]
That makes sense. It should be relatively straightforward to implement.

**Comment by olitomlinson** [comment]
@ConnorMcMahon kinda-related, I would like to be able to specify `partitionCount` via Env vars or App Settings, so I too could have different configurations for various environments. 

Chris tells me this can't be properly supported, something impacting the ability to scale correctly on consumption plan? Any thoughts?

**Comment by ConnorMcMahon** [comment]
I think we would be able to support it. Our scale controller logic looks at a taskhub.json file in your storage account to get some metadata about your taskhub (like partition count), so I see no reason why we couldn't populate the partition count in that json file. This is of course assuming you have two separate TaskHub + Storage Account combinations for your slots, which is always the recommendation.

Note that I have seen issues with this taskhub.json file being updated when partition count changes, so we would likely need to fix that bug in order for this situation to work cleanly (see #1285).

I may be missing some context however on why this wouldn't properly work however, so I can't make any guarantees.

**Comment by cgillum** [comment]
Can this be accomplished using slot-specific app settings? https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurefunctionsjobhost__

This approach won't work correctly for partition counts because the Scale Controller used in the Azure Functions Consumption and Elastic Premium plans won't understand this setting. However, for settings like the queue polling interval, I think it might just work.
