### ISSUE TITLE
DurableHttpRequest Throws Exception When Content Is Supplied

### ISSUE THREAD

**Issue by andyjmay** [Azure/azure-functions-durable-extension#1344]
### Description
After instantiating a DurableHttpRequest with content and calling CallHttpAsync an exception is thrown specifying a BadRequest was made.

### Expected behavior
The Content (JSON in this case) supplied to the initial DurableHttpRequest should not be passed to the new DurableHttpRequest created in the CreateLocationPollRequest method.

### Actual behavior
The Content from the original request is copied into this request that polls the Location URI returned 
in the header of the initial request. This causes an exception to the thrown and the Azure Function to terminate.

### Relevant source code snippets
```csharp
private DurableHttpRequest CreateLocationPollRequest(DurableHttpRequest durableHttpRequest, string locationUri)
{
	DurableHttpRequest newDurableHttpRequest = new DurableHttpRequest(
		method: HttpMethod.Get,
		uri: new Uri(locationUri),
		headers: durableHttpRequest.Headers,
		content: durableHttpRequest.Content, // This is the line causing the issue
		tokenSource: durableHttpRequest.TokenSource);

	// Do not copy over the x-functions-key header, as in many cases, the
	// functions key used for the initial request will be a Function-level key
	// and the status endpoint requires a master key.
	newDurableHttpRequest.Headers.Remove("x-functions-key");

	return newDurableHttpRequest;
}
```

### Known workarounds
After cloning this repo and referencing it in my project instead of the NuGet package I commented out the line using the initial Content and published my Azure function. It no longer throws an exception and correctly waits until the task (a CopyDatabase operation in my case) is complete.

**Comment by anthonychu** [comment]
Thanks @andyjmay. Agree that it shouldn’t be sending the body to the polling endpoint.

@ConnorMcMahon I don’t imagine that anyone is depending on this behavior as it’s a GET request, so I’m thinking it’s not a breaking change to remove the body. What do you think?
