### ISSUE TITLE
HTTP 404 status is returned in the middle of eventually successful orchestration

### ISSUE THREAD

**Issue by kiryvl** [Azure/azure-functions-durable-extension#1346]
### Description
I have noticed the failure like below in otherwise stably working orchestration workflow:
1. An HTTP triggered function started an orchestration ("O_ClaimVm_Orchestrator") and called CreateCheckStatusResponse to build its response.
2. The client of the HTTP trigger received the poll url from the Location header and started polling every 10 seconds.
3. It got 9 responses with "runtimeStatus"="Running" but on the 10th request it got HTTP 404 error.
4. From the AppInsights logs I can see that at that time an activity function ("A_ClaimVm_StartVm") failed with TaskCanceledException but was retried later as it was called by the orchestrator with CallActivityWith**Retry**Async method.
5. Orchestration completed successfully.

### Expected behavior
HTTP 404 error should not be returned in the middle of eventually successful orchestration.

### Actual behavior
The client side got HTTP 404 error while polling for eventually successful orchestration.

### Known workarounds
Handling possible 404 erorrs would be very ugly workaround.

### App Details

- **Durable Functions extension version v2.2.1**:
- **Azure Functions runtime version (3.0.7)**:
- **Programming language used**: C#

- **Timeframe issue observed**: 2020-05-06 08:54:00 - 2020-05-06 08:55:00 (UTC)
- **Azure region**: West Europe
- **Orchestration instance ID(s)**: 0000-eo4xgjzuz49btdpt

**Comment by ConnorMcMahon** [comment]
@kiryvl, I apologize for not following up on this investigation sooner.

Unfortunately, this telemetry no longer exists for us. Do you have a more recent case that we could take a look at?
