### ISSUE TITLE
Question: Concurrency behavior for StartNewOrchestration for same instance id

### ISSUE THREAD

**Issue by charleszipp** [Azure/azure-functions-durable-extension#1347]
Lets say I have the following orchestration

```csharp
// instance id is the Org Id
public async Task RetryOnOrgFixedAsync(
    [OrchestrationTrigger] IDurableOrchestrationContext context
    )
{
	// wait until the org info is fixed
    await context.WaitForExternalEvent("OrgFixed");

   // do some other stuff after the event occurs...
}
```

- Q1: If this function is started via `StartNewOrchestration` multiple times **using the same instance id** as one instance is already waiting on the external event, what is the expected behavior? 
- Q2: Will multiple instances of the orchestration be running concurrently or will they be turn-based due to them having the same instance id?
- Q3: Will there be multiple subscriptions to the same event? Or will only the first one be subscribed?

PS I could not find anything in the docs that explained expectations on concurrency for the same instance. If such a doc does exist feel free to refer me to that. If not, this probably needs to be outlined somewhere as it could have significant consequences if not understood what is expected to happen in this condition.

**Comment by charleszipp** [comment]
I did some testing on this condition here is what I found.

If the orchestration is running (i.e. waiting on the event), then subsequent starts of the same orchestration raise exception below:
System.Private.CoreLib: Exception while executing function: RetryOnOrgFixedHttp. DurableTask.AzureStorage: An Orchestration instance with the status Running already exists.

If I raise the event and allow the orchestration to complete, subsequent starts start with no exception

Based on that it would appear that multiple starts of the same orchestration instance are explicitly disallowed which makes Q2 & Q3 above irrelevant. If there is no other related/useful info on this, feel free to close. However, it might be worth mentioning this as a note in the [Singleton docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons?tabs=csharp) if it isnt already.

**Comment by olitomlinson** [comment]
Yes that is correct, you can't have two concurrent executions of the same instance (by using the same instance id)

As a side note, by default you can only restart an orchestration (using `StartNewAsync`) when the status of the existing Orchestration is in a state of 'terminated`, `failed`, or `completed`.

You _can_ change this behavior to allow restart on any state, by adding the following property to host.json ` "OverridableExistingInstanceStates": "AnyState"`

**Comment by charleszipp** [comment]
Thanks @olitomlinson. Closing this as the original question has been answered.
