### ISSUE TITLE
Traces with IsReplay=false not correctly filtered out in Application Insights

### ISSUE THREAD

**Issue by AtOMiCNebula** [Azure/azure-functions-durable-extension#1351]
### Description
`EndToEndTraceHelper` is not honoring the `TraceReplayEvents` option parameter for the following event types, due to what appears to be a copy-paste error:
* ExternalEventRaised
* ExternalEventSaved
* TimerExpired

As we scale up our durable function-using application, we've seen indications in App Insights that sampling is occurring, and we are seeing a ton of trace logging happening for replay events (even though that is disabled by default).  Over the last 24 hours, our app has collected 31K traces with IsReplay=true (should be 0 :innocent:), 27K with IsReplay=false, and 39K with IsReplay not specified (not all the trace helpers emit a value).

I'll be pushing a PR for this shortly. :smile:

### Expected behavior
Traces are not logged for replayed orchestrator events.

### Actual behavior
Traces _are_ being logged for replayed orchestrator events.

### App Details
- **Durable Functions extension version (e.g. v1.8.3)**: 2.2.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

**Comment by AtOMiCNebula** [comment]
@amdeel, looks like you've been helping with triaging lately.  Can you help me get some eyes on this? :smile:

**Comment by cgillum** [comment]
Thanks for reporting this and for the PR! We'll include this fix as part of our next planned release (v2.3.0).
