### ISSUE TITLE
[Question] Fidelity of CreateTimer()

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-functions-durable-extension#1361]
We have currently been prototyping some throttling code in order to not overwhelm calling out to other Azure services...as part of this work, we took the suggestions made from #596 and wanted to enhance it to not only thottle the number of 'started' activities, but also how many of these activities could be started per second (with the hope to mimic the transaction per second limits we see in Azure services).

We have previously achieved this using as Task list with a `Delay` task that we `await` for, but given the non deterministic nature of calling this in an orchestrator, we were looking at using something like this

`context.CreateTimer(context.CurrentUtcDateTime.AddSeconds(1), CancellationToken.None)`

Our question was, is this type of usage at the 1 second fidelity something that is able to be used well in an orchestrator? We could potentially have 150+ of these tasks triggering in quick succession and we are currently unsure if this type pattern was the intended use of the timer, or if it was meant for much larger timespans.

Current orchestration code snippet:
```csharp
var runningActivities = new List<Task>();
var ghostActivities = new List<Task>();

foreach (var message in messagesToProcess)
{
    var pendingOperations = runningActivities.Where(p => !p.IsCompleted).ToList();
    var pendingGhostOperations = ghostActivities.Where(p => !p.IsCompleted).ToList();

    if (pendingOperations.Count >= degreeOfParallelism)
    {
        await Task.WhenAny(pendingOperations);
    }

    if (pendingGhostOperations.Count >= transactionsPerSecondLimit)
    {
        await Task.WhenAny(pendingGhostOperations);
    }

    runningActivities.Add(context.CallActivityAsync(nameof(SomeActivityName), message));

    // is this something valid to be doing as many 1 second timers??
    var ghostResult = context.CreateTimer(context.CurrentUtcDateTime.AddSeconds(1), CancellationToken.None);
    ghostActivities.Add(ghostResult);
}

await Task.WhenAll(runningActivities);
```

**Comment by withinboredom** [comment]
I use something similar to globally rate limit some outgoing webhooks and use an entity to do the request. I'd be wary of having a loop like this in an orchestration since each replay would become progressively more and more expensive. It might be better to factor the loop out into an eternal orchestration, but I don't have the full context.
