### ISSUE TITLE
Passing null parameter into Activity causes exception

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-durable-extension#137]
If I add a new Function, choosing the Durable function template, I get an exception if I pass in null for the string.

    [FunctionName("Function1")]
    public static async Task<List<string>> RunOrchestrator(
        [OrchestrationTrigger] DurableOrchestrationContext context)
    {
        var outputs = new List<string>();

        outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", "Tokyo"));
        outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", ""));
        outputs.Add(await context.CallActivityAsync<string>("Function1_Hello", null));  // exception

        return outputs;
    }

    [FunctionName("Function1_Hello")]
    public static string SayHello([ActivityTrigger] string name, TraceWriter log)
    {
        log.Info($"Saying hello to {name}.");
        return $"Hello {name}!";
    }

> DurableTask.Core.Exceptions.TaskFailedException
>   HResult=0x80131500
>   Message=Exception while executing function: Function1_Hello
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskInternal>d__14.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at DurableTask.Core.TaskOrchestrationContext.<ScheduleTaskToWorker>d__13`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at DurableTask.Core.TaskOrchestrationContext.<ScheduleTask>d__12`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Azure.WebJobs.DurableOrchestrationContext.<CallDurableTaskFunctionAsync>d__53`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Microsoft.Azure.WebJobs.DurableOrchestrationContext.<CallActivityAsync>d__45`1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at FunctionApp1.Function1.<RunOrchestrator>d__0.MoveNext() in D:\Repos\XXXX\FunctionApp1\Function1.cs:line 21
>

**Comment by tohling** [comment]
Fix https://github.com/Azure/azure-functions-durable-extension/commit/4452a1a4823e4605e0605b45c5870a8bd049a7ea merged.

**Comment by ChrisProlls** [comment]
@tohling why not a CallActivityAsync methods without an input parameter. What if we want to call an activity without passing any arguments ?
