### ISSUE TITLE
NullReferenceException in Analyzer v0.2.3 (included in Durable Functions v2.2.2)

### ISSUE THREAD

**Issue by AtOMiCNebula** [Azure/azure-functions-durable-extension#1373]
### Description
I'm updating my project from v2.2.0 to v2.2.2 of Durable Functions, and am seeing the FunctionAnalyzer throw an NRE.  We're not blocked, but it would be nice to know a good way to disable the analyzer so that I can pick up the latest version of the package without stopping treating warnings as errors (couldn't figure out how to not let AD0001 be promoted to an error).

```
3>CSC : warning AD0001: Analyzer 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.FunctionAnalyzer' threw an exception of type 'System.NullReferenceException' with message 'Object reference not set to an instance of an object.'.
```

### Expected behavior
No NREs in analyzers.

### Actual behavior
NRE in analyzer!

### Relevant source code snippets
The code is not public, and is not in a position to be made public yet.  I also don't know how to provide a reduction, since I can't even get a stack trace out of the analyzer to know what part of my code it's choking on.  I did reach out to @amdeel a few minutes ago to share a ms-internal Azure DevOps link, so hopefully that's enough to go on.

### Known workarounds
None.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.2.2
- **Azure Functions runtime version (1.0 or 2.0)**: v3.0
- **Programming language used**: C#

**Comment by AtOMiCNebula** [comment]
If instructions on how I can get more actionable information on how to debug the analyzer can be shared, instead of expecting you/the team to debug my code, I'm happy to get better repro steps for you, but it sounds like analyzers are just tricky to debug. I spent 7.5 years working on the web platform at MS, and it feels really bad to not be able to provide a reduced repro. :innocent:

**Comment by TarekSalha** [comment]
agree, I am experiencing the very same error with similar setup:

<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.6"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.2.2"/>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" Version="0.2.3"/>
  </ItemGroup>

I tried to add Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers (0.2.3) as dependency, but it is throwing still the error.
