### ISSUE TITLE
Orchestration remains in Running status for several hours

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#1377]
_Originally posted by @Trixic in https://github.com/Azure/azure-functions-durable-extension/issues/1374#issuecomment-640554363_

Hi, @cgillum! I have a similar issue.
The problem is related to orchestration completing. When all suborchestration instances are completed main orchestration remains in Running status for several hours or even days.
The issue is reproduced when you have some number of suborchestrations with large input/outputs.

Code example that easily reproduces that stuck orchestration:
```csharp
[FunctionName(nameof(MainOrchestration))]
public static async Task<string> MainOrchestration([OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
{
    for (int i = 0; i < 20; i++)
    {
        var result =
            await context.CallSubOrchestratorAsync<string[]>(nameof(SubOrchestration),
                $"{context.InstanceId}:sub{i}", "input");
    }

    log.LogInformation("MainOrchestration finished");
    return "Completed";
}

[FunctionName(nameof(SubOrchestration))]
public static async Task<string[]> SubOrchestration([OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
{
    var largeOutput = Enumerable.Range(0, 1000000).Select(i => $"string{i}").ToArray();
    return largeOutput;
}
```

In my test app it's in Running state for a day already:
![image](https://user-images.githubusercontent.com/3503594/84024768-225c9180-a993-11ea-8059-57dd3d469357.png)

Could you take a look on app's logs?

### App Details

- **Durable Functions extension version**: v2.2.2
- **Azure Functions runtime version**: 2.0
- **C#**:

- **Timeframe issue observed**: 2020-06-07T13:02:51.606Z
- **Function App name**: odmpftvjo2hlqa7um2af
- **Function name(s)**: MainOrchestration, SubOrchestration
- **Azure region**: East US
- **Orchestration instance ID(s)**: 56eca7be5a6e4b1f82f8cec360ba3d27
- **Azure storage account name**: ogpfstuckdur

_Originally posted by @Trixic in https://github.com/Azure/azure-functions-durable-extension/issues/1374#issuecomment-640554363_

**Comment by cgillum** [comment]
@Trixic Quick update on this - the problem seems to be that this function app instance is continuously recycling. I'm not sure why it's recycling though since I don't see any errors in the Durable Functions telemetry. I'll continue to take a look and let you know if I find anything. You may be able to get more information if you visit the **Diagnose and Solve** blade in the Azure Portal while in the context of your function app.

**Comment by cgillum** [comment]
@Trixic Another update, it looks to me like your app keeps recycling because of high memory usage. Your orchestration keeps trying to execute but gets killed abruptly because it is using too much memory (the limit for the Azure Functions Consumption plan is 1.5 GB). I think this explains why it appears to be stuck and is consistent with the fact that your code is allocating very large messages in the sub-orchestration return values.

At this point, my suggestion is that you upgrade your plan to the Azure Functions Elastic Premium plan where you have more flexibility in terms of memory size (or find a way to refactor the app so that it doesn't allocate so much memory).

**Comment by andrewvanpersie** [comment]
Hello, @cgillum!

As we were able to find out it was possible to reproduce in Azure only.

**Comment by Trixic** [comment]
Locally I cannot reproduce this issue. But with Azure deployment it's reproduced every time consistently.

**Comment by Markd0ne** [comment]
Run into same issue on Azure, able to reproduce locally as well when dealing with suborchestrations with large input/outputs.

**Comment by nelsonmorais** [comment]
@cgillum 
We see that same behaviour (orchestration stays on the Running state even after all activities are completed with success) with DF 2.2.2.
We're rolling back to version 2.2.0 the verify if that behaviour is also visible with this version (we expect not to as this was the version we're using before). 
Me or a member of our team will post the results of this rollback.

**Comment by cgillum** [comment]
Thanks @nelsonmorais that would be really helpful!

**Comment by nelsonmorais** [comment]
@cgillum 
No luck, so same behaviour. But it seems like this isn't always the case or maybe it goes to a completed state after a longer period of time as I've seen that we have executions of the same Orchestrator in a Completed and in a Running state while we've used the same DF 2.2.2 version.

**Comment by cgillum** [comment]
@nelsonmorais indeed this looks similar. From telemetry I can see that `DA_0005427645-00-01-c0-25-bf-48` completed at successfully at `2020-07-13 08:17:46.7660393`.

However, one interesting thing I realized is that your orchestration is creating what looks like 4 durable timers (NOTE: this data is available to you in Application Insights):
```
1. CreateTimer:2020-07-19T08:17:46.5374467Z
2. CreateTimer:2020-07-19T08:17:49.3188261Z
3. CreateTimer:2020-07-13T08:28:56.4910999Z
4. CreateTimer:2020-07-19T08:29:23.5238980Z
```

I see that the 3rd timer for `2020-07-13T08:28:56.4910999Z` fired, but the others did not (their expiration time is still 4 days out). Did you cancel your durable timers 1, 2, and 4 before the orchestration completed?  If not, then it's currently a known issue that your orchestrator hasn't completed. We talk about this in our [Durable Timers documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-timers#usage-for-timeout).

> Use a `CancellationTokenSource` (.NET) or call `cancel()` on the returned `TimerTask` (JavaScript) to cancel a durable timer if your code will not wait for it to complete. The Durable Task Framework will not change an orchestration's status to "Completed" until all outstanding tasks are completed or canceled.

Please check to see if that could be the cause of the completion delay. Unfortunately we don't currently emit telemetry that tells us whether durable timers have been canceled (something I now want to fix!) so we have to rely on code inspection for this.

**Comment by cgillum** [comment]
@Markd-One you mentioned you could reproduce similar behavior as @Trixic locally? Do you happen to have any sample code I could try? I still want to try and figure out the original issue, especially if we think it's specific to large sub-orchestrator inputs or outputs.

**Comment by vperko** [comment]
@cgillum I am one of the developers working with @nelsonmorais. 

Thank you for the input, it helped us track and fix the issue.

One of our tasks which is using the WaitForExternalEvent on the DurableOrchestrationContext did not have a proper reference to a CancellationToken. Since WaitForExternalEvent is creating the timers implicitly, every time the orchestration was replayed a new one was created and was not cancelled properly. 
After correcting this we can confirm the orchestration ends up in "Completed" state.

**Comment by jy03189211** [comment]
Hi, should we wait for the next release of the durable extension for example 2.2.3 or it has already been fixed from Azure?

**Comment by romangobrey** [comment]
Have same issue here - https://github.com/Azure/azure-functions-durable-extension/issues/355
