### ISSUE TITLE
Is "Singleton" attribute supported by orchestrators

### ISSUE THREAD

**Issue by pierre-weceipt** [Azure/azure-functions-durable-extension#138]
Hi, I found that there is a singleton data attribute in regular functions (https://github.com/Azure/azure-webjobs-sdk/wiki/Singleton). Is it supported with orchestrators? Meaning if it was already started but not finished yet you don't start another one?

**Comment by cgillum** [comment]
This attribute isn't supported (and isn't supported by Functions at all), but we have another mechanism for implementing singletons using orchestrator functions. See this documentation: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-singletons.
