### ISSUE TITLE
Terminating an instance after introducing a breaking change

### ISSUE THREAD

**Issue by underscoreHao** [Azure/azure-functions-durable-extension#1381]
### Description
This question is connected a bit to #1118 because that's my current use case. So please take a quick look before continuing.

Recently I've introduced a breaking change in my durable function flow. I've renamed the durable function, removed some activity functions that are not used anymore etc. Essentially I've done every bit that constitutes a breaking change described in here - https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-versioning

As a top-level example I've changed the name of my durable function from **X** => **Y**

I've devised a mitigation strategy to essentially restart my old eternal functions without impacting the creation of new ones using the new code. The flow is essentially:

- I have a separate store with information about the events and their current durable instanceId. I get the currently active instances from there and poll for their status via the `GetStatusAsync`

```cs
if (!string.IsNullOrEmpty(instanceId.ToString()) && instanceId != default)
{
    // Get the status of the instance and if it's running terminate it
    var instance = await client.GetStatusAsync(instanceId.ToString(), false, false, true);
    if (instance != null)
    {
        if (instance.RuntimeStatus == OrchestrationRuntimeStatus.Running)
        {
            await client.TerminateAsync(instanceId.ToString(), reason);
            logger.LogInformation($"Terminated orchestration: taskId - {taskId} | instanceId - '{instanceId}'.");
        }
    }
}
```

- I terminate the old instance of the eternal orchestrator **_(this doesn't work)_**
- New instances with new instanceId are created

It turns out that calling `GetStatusAsync` and `TerminateAsync` from the **Y** version of my durable function is returning `null` if I poll for an instance that has the old name **X**. Calling just `TerminateAsync` with the old instanceId also fails, because it says it can't find the old instance.

At this stage my thinking is that well yeah they have two different names or even if they have the same name there's breaking changes between them so that means they're two different contexts all together. So then I reasoned that I don't care that the old ones will fail. They'll be marked as failed, because they'll say they don't know the function name or that it's not deterministic and will blow-up. I don't care because I've already created an eternal orchestrator with the new flow.

What doesn't make sense is that I have old instances waking up and going to sleep for around 10 minutes. They're always running and don't fail. When they wake up they just spew this message:

> "Message": "The function 'XYZ' doesn't exist, is disabled, or is not an activity function. Additional info: The following are the known activity functions: 'TerminateInstance'.",

I've seen this error while reading about it here #577 

My logs are polluted because of that, but I also would like to understand what's happening underneath.

![image](https://user-images.githubusercontent.com/5088351/84246644-d169ac00-aafe-11ea-8e17-27e0c06ec18e.png)

I've restarted this orchestrator 4 times now and it's an eternal orchestrator. However the original instance (the one with the **int** partition key at the bottom) is still running when it should've have failed because the code it executes is this:

```cs
try
{
    // some durable code
}
catch (Exception exception)
{
    // The function will be marked with 'RuntimeStatus' of 'Failed'
    logger.LogError(exception, $"An error occurred during queueing of task! | TaskId {taskId} | InstanceId {context.InstanceId} | Name {context.Name}");
    throw;
}
```

I think I'm missing something here so some clarification on what's the expected behavior here will be much appreciated!

**Comment by underscoreHao** [comment]
Thanks for the reply @ConnorMcMahon. 

Unfortunately the information you have requested is private to the company I work for and I'll have to ask for special permission to share it (I will do that though).

Changing the taskhub is valid approach for the problem at hand. I was more interested in the behaviour here. Can you confirm that my understanding about getting a status and terminating is correct in that example?

> It turns out that calling GetStatusAsync and TerminateAsync from the Y version of my durable function is returning null if I poll for an instance that has the old name X. Calling just TerminateAsync with the old instanceId also fails, because it says it can't find the old instance. At this stage my thinking is that well yeah they have two different names or even if they have the same name there's breaking changes between them so that means they're two different contexts all together.

What about that pesky `Running` function. Am I correct in my assumption that when it wakes up and throws the exception it should pass through the catch block and just fail?

**Comment by bendursley** [comment]
@ConnorMcMahon can we get some contact details for you or shall we raise a support request?

**Comment by ConnorMcMahon** [comment]
@underscoreHao 

Looking specifically at the issue you mentioned in this quote:

> It turns out that calling GetStatusAsync and TerminateAsync from the Y version of my durable function is returning null if I poll for an instance that has the old name X. Calling just TerminateAsync with the old instanceId also fails, because it says it can't find the old instance. At this stage my thinking is that well yeah they have two different names or even if they have the same name there's breaking changes between them so that means they're two different contexts all together.

To my knowledge, the `GetStatusAsync()` should not be broken on a rename, as that looks directly at our instance state table. 

`TerminateAsync()` I now realize is an entirely different case. When you call TerminateAsync(), what you are doing is sending an ExecutionTerminated message to your orchestrator. When that message is received, we will replay one more time, and after that replay, when we see the ExeuctionTerminated message, we will mark the orchestration as terminated and the runtime history will also accurately reflect that. When you renamed your function from X to Y, we can no longer replay Function X, which is why you are getting the errors.

My recommendation in this case would be to leave your old code in Function X, and then put your new code in Function Y. This way, you can successfully terminate the eternal orchestration running with Function X with a `TerminateAsync()` request, and you can start a new eternal orchestration with the same instance id on Function Y.

As for the `Running` function you still have, I believe I have enough information here to be able to look in our telemetry. I will take a look at that.

**Comment by ConnorMcMahon** [comment]
@underscoreHao,

Unfortunately, I lost track of this issue and was unable to investigate that Running function while we still had the telemetry. Are you still experiencing this issue. If you are, please provide some more recent telemetry for an orchestration so that I can resume this investigation.
