### ISSUE TITLE
Serialization Issue in 2.2.2

### ISSUE THREAD

**Issue by tolzon** [Azure/azure-functions-durable-extension#1389]
### Description
After upgrading to version 2.2.2, we receive the following exception when trying to run an Activity from an Orchestrator: "Exception binding parameter [parametername]", where the innerException is "Error reading JArray from JsonReader. Current JsonReader item is not an array: StartObject. Path '', line 1, position 1."

It appears that the framework serializes Activity parameters with " TypeNameHandling.Object", and tries to deserialize with whatever the system default it (in this case TypeNameHandling.All).  This is leading to a mismatch that newtonsoft cannot resolve.

Our app requires the following code in `Startup.cs` in order to deserialize out internal domain objects to/from Storage Queues correctly.

```
 public class MessageSerializerSettingsFactory : IMessageSerializerSettingsFactory
    {
        public JsonSerializerSettings CreateJsonSerializerSettings() => new JsonSerializerSettings
        {
            TypeNameHandling = TypeNameHandling.All
        };
    }
```
This is registered via:
```
 builder.Services.AddSingleton<IMessageSerializerSettingsFactory, MessageSerializerSettingsFactory>();
```

### Expected behavior
> An Activity parameter is successfully passed to an Activity from an Orchestrator.  Both deserialization and serialization should use the same TypeNameHandling settings.

### Actual behavior
> An exception is thrown because of a TypeNameHandling mismatch.

### Relevant source code snippets
Sample project here: https://github.com/tolzon/Function222Serilization

### Known workarounds
> none

### App Details

- **Durable Functions extension version 2.2.2**:
- **Azure Functions runtime version 3.1**:
- **Programming language used C#**:

**Comment by ConnorMcMahon** [comment]
Thanks for the repro @tolzon.

@amdeel, would you be able to take a look at this?

**Comment by amdeel** [comment]
Hey @tolzon, in 2.2.0 we added to our custom serializer settings feature to inject the custom settings to the Durable Task Framework. This means that after upgrading, your app was actually not using two different settings, as you mentioned, but using the settings you injected throughout. Interestingly, this is why it broke.

This exposes a bug in the Durable Functions extension where TypeNameHandling.All will serialize the activity input in an unexpected way which will throw an exception.

I recommend you inject a JsonSerializerSettings with TypeNameHandling.Objects instead.

**Comment by tolzon** [comment]
Hi @amdeel.  We are not able to inject TypeNameHandling.Objects, because we store typed objects on the ServiceBus, and they require TypeNameHandling.All in order to deserialize into the correct type.
