### ISSUE TITLE
ActivityTrigger not firing 

### ISSUE THREAD

**Issue by AlexeyEvlampiev** [Azure/azure-functions-durable-extension#139]
I've coded a fan-out orchestration function following the examples. The orchestration trigger is fired when a file is uploaded scheduling a number of activity tasks to be executed in parallel (I do see these events in DurableFunctionHubHistory). However the activity does not get executed at all.

`      
   [FunctionName("A")]
        public static async Task InitializeBulkUpload(
            [OrchestrationTrigger] DurableOrchestrationContext ctx,
            TraceWriter log)
        {
            // some business logic...

            var enqueueBatchTasks = new List<Task>();
            foreach (var item in collection)
            {
                    var batchTask = ctx.CallActivityAsync (
                        "B",
                        new Batch  {});

                    enqueueBatchTasks.Add(batchTask);             
            }

            await Task.WhenAll(enqueueBatchTasks);
        }

        [FunctionName("B")]
        public static async Task BatchEnqueueBulkImportMessagesActivity(
            [ActivityTrigger] Batch batch,
            TraceWriter log)
        {
            // code goes here...
                );
        }`

**Comment by cgillum** [comment]
Which version of the functions runtime are you using? 1.0 or 2.0 (beta)?

**Comment by MFurn** [comment]
I am seeing the same issue when using Task.WhenAll as above.  The activity trigger is fired if I await a single call but not if I add to a list and use Task.WhenAll.  

I am using Microsoft.Azure.WebJobs (2.1.0-beta4) and Microsoft.Azure.Webjobs.Extendions.DurableTask .1.0-beta2)

**Comment by cgillum** [comment]
The good news is that we've checked-in support for large messages this last week (https://github.com/Azure/azure-functions-durable-extension/issues/26), so issues related to large messages will be resolved in the next release.
