### ISSUE TITLE
Add Durable Entities templates

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-durable-extension#1404]
Create templates for Durable Entities.
* Bundles V2 (VS Code + Core Tools)
* VS - C# only

2 functions per language:
* Counter entity
* Http function

https://github.com/anthonychu/durable-entities-examples

https://github.com/Azure/azure-functions-templates

**Comment by anthonychu** [comment]
@cgillum Now that Bundles v2 is going to be released, we should add these templates. We can add quickstarts for them after they're done.

**Comment by cgillum** [comment]
@bachuv this might be a good one for you to tackle. I think we're still waiting for bundles v2 to be deployed and that will likely be a blocker, but @soninaren should be able to provide guidance.
