### ISSUE TITLE
WaitForExternalEvent cannot be awaited more than once using the same event name

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#141]
Consider the following example orchestration:

```csharp
[FunctionName("Loopy")]
public static async Task WaitForFiles([OrchestrationTrigger] DurableOrchestrationContext ctx)
{
    var receivedFiles = new List<string>();
    while (receivedFiles.Count < 3)
    {
        var file = await ctx.WaitForExternalEvent<string>("file");
        receivedFiles.Add(file);
    }

    // continue on...
}
```
It is designed to wait for three files to be delivered via `RaiseEvent` calls with the event name "file" before moving on to the next step.

### Expected
The orchestration should wait until three "file" events are sent to this instance using `RaiseEvent` before it moves to the next step.

### Actual
The orchestrator function goes into an infinite loop after receiving the first "file" event.

The problem is the internal implementation of `WaitForExternalEvent`. After the first event is received, subsequent calls to `WaitForExternalEvent` will return the same completed task instead of generating a new one.

This will be very important to fix for scenarios that rely on processing batches of external events.

### Workaround
If possible, refactor the orchestrator function and the client to ensure that each event has a unique name (this may not be possible in all scenarios).

**Comment by cgillum** [comment]
This has been fixed by @brandonh-msft. A "prerelease" version of this fix is available on myget: https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.1.1-beta2. More officially, this will go out with the Beta 3 release.

**Comment by stuartleeks** [comment]
Very happy to see this fixed and released!
Thanks @brandonh-msft  :-)
