### ISSUE TITLE
Function chaining not working with custom Task Hub name

### ISSUE THREAD

**Issue by tjkb** [Azure/azure-functions-durable-extension#1411]
### Description
I want to use [function chaining](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-sequence) in combination with setting the Task Hub name via `DurableClient` attribute to implement a timer. A client function starts an orchestration function that creates a timer, and after that it calls an activity function.

So my client function that starts the orchestration function has the following binding: `[DurableClient(TaskHub = "SomeName")] IDurableClient durableClient`. The orchestration function uses the binding `[OrchestrationTrigger] IDurableOrchestrationContext context`. The problem is now that as soon as I set the Task Hub name for the client function, the orchestration function is not called anymore. This makes perfectly sense since the orchestration function should use the same Task Hub name as the client function. But I don't see a way to set the Task Hub name for my orchestration function. The `OrchestrationTrigger` attribute provides no way to set the Task Hub name like the `DurableClient` attribute.

I know that I can globally set the Task Hub name in the `hosts.json` file, but I'd like to do it via attribute.

### Expected behavior
The orchestration function gets called by the client function, even if it sets the Task Hub name via `DurableClient` attribute.

### Actual behavior
The orchestration function does not get called by the client function.

### Relevant source code snippets
Client, orchestration and activity function.
```csharp
public static class Timer
{
  [FunctionName("Start")]
  public static async Task<IActionResult> Start(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequest req,
    [DurableClient(TaskHub = "SomeName")] IDurableClient durableClient)
  {
    var instanceId = Guid.NewGuid().ToString();
    await durableClient.StartNewAsync("Orchestrator", instanceId, req.Query["payload"]);
    return new OkObjectResult(instanceId);
  }

  [FunctionName("Orchestrator")]
  public static async Task Orchestrator([OrchestrationTrigger] IDurableOrchestrationContext context)
  {
    await context.CreateTimer(context.CurrentUtcDateTime.Add(TimeSpan.FromMinutes(1)), CancellationToken.None);
    await context.CallActivityAsync("Activity", context.GetInput<object>());
  }

  [FunctionName("Activity")]
  public static void Activity([ActivityTrigger] IDurableActivityContext context, ILogger logger)
  {
    logger.LogWarning($"Activity received {context.GetInput<object>()}");
  }
}
```

### Known workarounds
none

### App Details

- **Durable Functions extension version: 2.2.2**:
- **Azure Functions runtime version: ~3**:
- **Programming language used: C#**:

**Comment by cgillum** [comment]
Yes, orchestration and activity triggers only listen on the task hubs defined in host.json. The purpose of allowing the task hub to be specified on the _client_ binding is to allow one function app to manage orchestrations or entities that are defined in _another_ function app. It was not our intention to allow a single function app to process orchestrations and entities from multiple task hubs.

Can you tell us more about why you want to have a single function app handling multiple task hubs?

**Comment by tjkb** [comment]
I see, thanks for the explanation, Chris. We currently have the following setup: 1 single function app contains around 8 "regular" functions with an Event Grid binding, as well as 2 times a set of Client/Orchestration/Activity functions to implement timers.

We want to set the Task Hub name because when upgrading to version 2.2.2 of the durable functions extension we run into this error/warning that we should set the Task Hub name. 

What setup would you suggest us to use? Probably a single function app is not enough?

We like very much to have everything in a single function app because it makes developing, building, releasing and maintaining very easy.

**Comment by cgillum** [comment]
@tjkb sorry for the delayed response. Can you tell me more about the error/warning you saw about setting the Task Hub name?

The recommendation for adding a Task Hub value in host.json is to help avoid problems where multiple apps are configured with the same (default) task hub name. Multiple apps with the same name is not allowed because it will cause the apps to compete with each other. However, this change shouldn't normally require you to make any changes to your code.  The `[DurableClient]`, `[OrchestrationTrigger]` and `[ActivityTrigger]` bindings all will read the host.json value by default and you shouldn't need to explicitly specify a task hub name in your attributes.
