### ISSUE TITLE
External event not picked up by suborchestrator

### ISSUE THREAD

**Issue by stephaneey** [Azure/azure-functions-durable-extension#1416]
### Description
> External events picked up correctly by the main orchestrator but not by a sub orchestrator.

### Expected behavior
> Sub-orchestrator should pick the event

### Actual behavior
> When waiting for the event in the RunOrchestrator function, it works fine. The exact same piece of code within a sub-orchestrator fails listening properly to that very same event. Get this as an error:

_Function 'Monitoring (Orchestrator)' saved a 'step01' event to an in-memory queue. State: ExternalEventDropped._

It sounds pretty silly and simple but it fails. I'm using version 2.2.2 (latest stable).

### Relevant source code snippets
```csharp
[FunctionName("Monitoring")]
        public static async Task RunOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
        {            
           
            OrchestrationConfiguration process = context.GetInput<OrchestrationConfiguration>();

            foreach(OrchestrationStep step in process.steps)
            {   
                var result = await context.CallSubOrchestratorAsync<bool>(nameof(SingleStepOrchestration), step);                
               
            }            
        }

        [FunctionName(nameof(SingleStepOrchestration))]
        public static async Task<bool> SingleStepOrchestration(
           [OrchestrationTrigger] IDurableOrchestrationContext context,
           ILogger log)
        {           
            var step = context.GetInput<OrchestrationStep>();            
            var state = await context.WaitForExternalEvent<string>(
                step.stepName, TimeSpan.FromMinutes(2));
            
            //never reaches this place
        }
     [FunctionName("stepResultCallback")]
        public static async Task stepResultCallback(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestMessage req,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger log)
        {
            string eventName = req.RequestUri.ParseQueryString().Get("eventName");
            string status = req.RequestUri.ParseQueryString().Get("status");            
            await starter.RaiseEventAsync(req.RequestUri.ParseQueryString().Get("instanceId"), eventName, status);
        }
```

### App Details

- **Durable Functions extension version**:2.2.2
- **Azure Functions runtime version**:3.0.3
- **Programming language used**: .NET

### If deployed to Azure
> Debugging locally with VS 2029 & Storage Emulator

**Comment by cgillum** [comment]
According to this message:

> Function 'Monitoring (Orchestrator)' saved a 'step01' event to an in-memory queue. State: ExternalEventDropped.

It looks like you're sending the external event to the parent orchestrator (Monitor) instance instead of to the sub-orchestrator (SingleStepOrchestration) instance. The right way to do this would be to call `stepResultCallback` and provide an `instanceId` parameter value for the _sub-orchestration's_ instance ID.

To know the sub-orchestrator's instance ID, you'd either need to explicitly specify one in in your `CallSubOrchestrator` API call or have the sub-orchestrator broadcast it somehow so that external callers can learn about it after the sub-orchestration starts.

**Comment by stephaneey** [comment]
Hello @cgillum 

Just came back on my keyboard and figured it out as we speak, I was about to close the issue. Indeed, I was sending the wrong instance idea. Sorry for having made you lose time.

Thanks
Best Regards
