### ISSUE TITLE
Unable to write test cases for IDurableEntityContext.DispatchAsync

### ISSUE THREAD

**Issue by abbasc52** [Azure/azure-functions-durable-extension#1419]
Hi i am getting an error when i mock IDurableEntityContext and call DispatchAsync

```
 Message: 
    System.InvalidCastException : Unable to cast object of type 'Castle.Proxies.IDurableEntityContextProxy' to type 'Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableEntityContext'.
```

On looking at the source i found this which forces the input to be of type DurableEntityContext:
https://github.com/Azure/azure-functions-durable-extension/blob/affadf71b71d3711c3f57c9420b7e81a6e9ede1f/src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs#L78

Is there any way i can get around this?

**Comment by cgillum** [comment]
Hmm...I'm not sure if our current design allows this method to be mocked.

/cc @sebastianburckhardt

**Comment by abbasc52** [comment]
Can we replace `GetStateWithInjectedDependencies` with `GetState` ? The code is more or less same and can solve this issue with few minor changes.
I can help with raising a Pull request if needed.

**Comment by ConnorMcMahon** [comment]
Unfortunately this was missed in our attempt to move away from extension methods in 2.3.0.

It is something that should be fairly straightforward to move from an extension method to a direct interface method I believe.

@cgillum, should we consider this for our next release?

**Comment by ConnorMcMahon** [comment]
I think I may be able to fit this into v2.4.0.
