### ISSUE TITLE
Timer Trigger Not Firing and Durable Orchestration Function Not Executing on Time

### ISSUE THREAD

**Issue by AsifulNobel** [Azure/azure-functions-durable-extension#1423]
#### Investigative information

- Timestamp: 2020-06-30T12:01:11.5775837Z
- Function App version: 2.0.13900.0
- Function name(s) (as appropriate): TimedReportingStarter, TimedReportingOrchestration, TimedReportEmailingOrchestration
- Invocation ID: d4ce71c6-66b1-4e9a-b1c6-be67bed6444d
- Region: US-East

#### Brief overview of how my code works

I have a Timer triggered function(TimedReportingStarter) that runs every 30 minutes and schedules a Durable Orchestration function(TimedReportingOrchestration) to run. The Timer triggered function passes the current time to the Orchestration function. The Orchestration function then schedules a Sub-Orchestration function(TimedReportEmailingOrchestration) for each tenant with retries on exception atleast 3 times with backoff. Each Sub-Orchestration function then sends an email to specific email addresses according to schedule and passed down time is used to determine current time.

#### Expected behavior

The Timer triggers every 30 minutes. The orchestration function and sub-orchestration functions run within next 30 minutes.

#### Actual behavior

Timer is not always triggering on correct time. In the last 20 days, there were days such as 6/11, 6/22 and 6/29 when specific times such as 11 AM and 9 AM did not trigger and execute the function. There were periods from 6/12 to 6/16 and 6/24 to 6/29 when orchestration functions did not run at all. But on 6/17 and 6/29 after App restart, orchestration functions started to run in normal fashion again and started executing pre-scheduled orchestration functions from 6/11 and 6/24 respectively.

#### Related information 

The tenant number can range from 1-26 at any given interval. The Timer trigger does not have `runOnStartup` enabled. The function app is running on App Service Plan with single instance and manual scaling specified. I have run the Diagnostic Service on the app and did not find any issue. The function app is configured to be always on. There are no related error logs in Application Insights. There is a Durable Entity Function that handles events from EventHub. The events are published after sending each email.

* Programming language used: C#
* Bindings used: Timer

**Comment by cgillum** [comment]
@AsifulNobel for the most recent stuck orchestration on 7/29, can you provide us with the orchestration instance ID? I'd like to take a closer look at our internal telemetry to see what might be causing these delays, especially if you've already tried migrating to v2.2.2.

**Comment by AsifulNobel** [comment]
@cgillum I am posting the Support Engineer's findings with instance ID and timestamps.

> My understanding is that hang issue reoccurred on function TimedReportingOrchestration since 2020-07-29 11:30(UTC). No resource exhaustion detected.
> The issue was mitigated after scaling out to 3 instances around 2020-07-29 14:00.
> 
> Just some findings on this issue.
> 1.Checked backend logs from 2020-07-29 11:30(UTC) to 2020-07-29 14:00(UTC).
> (1) No high cpu or high memory. 
>      Worker process on new instance IN_2 was ready on 2020-07-29 13:36.
> (2) There were errors i.e. 'The method 'CleanupTimedReportingExternalEmailArtifactsAsync' cannot be found.' on function app.
>       In addition, internal warnings of durable task were observed, i.e 'GetMessage' did not complete in '00:02:00',  partition manager error.
>       
> 
> 2. Checked sample instance ids.
> (1) Instance 75964a1d0e4046e3a856db0e3c3e52d1 started on 2020-07-29 11:30:00.049
>       It looks like message was abandoned several times and it was processed correctly on IN_2.
> (2) Instance 104fc433cf704293b5f8fd7fc8626ab0 triggered on 2020-07-29 12:02:08.673.
>        The function was starting on 12:58.

'The method 'CleanupTimedReportingExternalEmailArtifactsAsync' cannot be found.' - this error is because I had renamed an existing function method in codebase, but have not got around to update it on the Functions app. The function with previous name is not referenced anywhere. The method not found issue only happens on startup.

Let me know if you need anything else.

**Comment by AsifulNobel** [comment]
This issue has not occurred again in the last 6 months after updating to Azure Functions v3!
