### ISSUE TITLE
Attempting to poll the result of CreateCheckStatusResponse can return 404

### ISSUE THREAD

**Issue by mark-r-cullen** [Azure/azure-functions-durable-extension#143]
Hi,

Running beta-2. I have run in to the same issue as #99 . It seems that the Azure Function can return before something, somewhere, is initialized, even with the RetryAfter set (admittedly to "just" 1 second).

e.g

```
var request = await req.Content.ReadAsAsync<...>().ConfigureAwait(false);

var instanceId = await starter.StartNewAsync("Orchestrator", request).ConfigureAwait(false);

var response = starter.CreateCheckStatusResponse(req, instanceId);
response.Headers.RetryAfter = new RetryConditionHeaderValue(TimeSpan.FromSeconds(1.0));

return response;
```

If the caller then polls the response Location header url, even taking in to account the initial 1.0 second delay, sometimes it will still get a 404.

Setting the RetryAfter to something larger, say 10 seconds, just to avoid this seems like a bit of a poor workaround? I would expect to be able to poll the URL in the location header immediately?

**Comment by cgillum** [comment]
Yes, ideally one should be able to query the instance immediately after querying it. Thanks for opening this as a separate issue. I think this will be an important fix for us to include in the GA release.
