### ISSUE TITLE
Please help .. orchestration function is not completing ..and inside the trigger function its showing this error 

### ISSUE THREAD

**Issue by VishalCodingNinja** [Azure/azure-functions-durable-extension#1435]
![image](https://user-images.githubusercontent.com/37198555/90393544-99f31f00-e0ae-11ea-90b4-86c00cda7d8b.png)

**Comment by cgillum** [comment]
Why is it not completing? Does this happen sometimes or all the time? What is your orchestrator code doing?

This screenshot is not enough information for us to help.

**Comment by ConnorMcMahon** [comment]
If you are trying to restart an orchestration in the running state with the same instance id, that will not work with Durable 2.x. In Durable 1.x, we would allow this behavior, but it would override the current state of the running orchestration instance. This led to lots of customers accidentally deleting running orchestrations, so in Durable 2.x we blocked that pattern.

Instead, you first need to terminate the instance, and then you can start an instance with the same instance id.

**Comment by VishalCodingNinja** [comment]
@cgillum 
here is the screenshot of the orchestrater function code 
![image](https://user-images.githubusercontent.com/37198555/90429592-a180eb00-e0e3-11ea-8462-99e0f2dd9ee9.png)


@ConnorMcMahon Thanks for reply :)

**Comment by ConnorMcMahon** [comment]
@VishalCodingNinja,

In general, that is a very large fan-out, fan-in orchestration, which is likely why it is stuck running for so long. We have made some performance improvements to this in recent releases, so you may want to look into upgrading to version 2.3.0 if you can. In general, with big fan-out/fan-in operations like this I highly recommend turning on [extended sessions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#extended-sessions) as well.

As a note, the way you are keeping track of how long your orchestration will not work correctly. It will only track how long the function was executing on the last replay of the orchestration. To make your timing logic more accurate across orchestration replay executions, try something like this.

```csharp
var startTime = context.CurrentUtcDateTime;
// Business logic here

var endTime = context.CurrentUtcDateTime;
log.LogInformation("Time elapse: {endTime.Subtract(startTime)}");
```
