### ISSUE TITLE
Better handling of undefined entity functions

### ISSUE THREAD

**Issue by sebastianburckhardt** [Azure/azure-functions-durable-extension#1443]
### Description
Strange error messages when using an entity for which there is no function defined.

### Expected behavior
Constructing an entity ID, and locking that entity, with a name for which there is no corresponding function is not an error. The function definition is only required when signalling or calling operations of the entity. 

In the latter case, a clear error message should be both logged and returned to the caller.

### Actual behavior
The log shows errors and warnings that look like internal bugs and will confuse users:

Unhandled exception with work item '@counter@aho': System.NullReferenceException: Object reference not set to an instance of an object.

Followed a while after by poison message:
@counter@aho: Message [EventRaised] with ID 20bc5349-4d55-4f53-a468-65b960458381 has been dequeued 20 times and is now considered poison
[8/19/2020 10:42:33 PM] @counter@aho: Abandoning [EventRaised] message back to stress-control-03 and setting a visibility delay of 600ms

**Comment by ConnorMcMahon** [comment]
Tracking this as #1190
