### ISSUE TITLE
Failed to deserialize exception from TaskActivity: Type: System.Web.Http.HttpResponseException

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-functions-durable-extension#1453]
### Description
If a HttpResponseException is thrown from an Activity function, it should have the correct exception (which is a `HttpResponseException` instead I am seeing `Failed to deserialize exception from TaskActivity: Type: System.Web.Http.HttpResponseException`.

###Stacktrace
> Failed to deserialize exception from TaskActivity: {"$type":"System.Web.Http.HttpResponseException, Microsoft.AspNetCore.Mvc.WebApiCompatShim","Response":{"$type":"System.Net.Http.HttpResponseMessage, System.Net.Http","Version":"1.1","Content":null,"StatusCode":400,"ReasonPhrase":"Bad Request","Headers":[],"TrailingHeaders":[],"RequestMessage":null,"IsSuccessStatusCode":false},"StackTrace":"   at \\ApplicationLevelStackOmitted\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 568\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 514\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, IFunctionOutputDefinition outputDefinition, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 460\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 270","Message":"Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib"},"InnerException":null,"HelpLink":null,"Source":"SomeOrchestrator","HResult":-2146233088}

### Relevant source code snippets
```csharp
// Caller
var retryOptions = new RetryOptions(firstRetryInterval: TimeSpan.FromSeconds(5), maxNumberOfAttempts: 3)
{
   Handle = ex => ex.InnerException is HttpResponseException // false which is wrong?
}
var someResult = await context.CallActivityWithRetryAsync<SomeResult>("MyActivityFunction", retryOptions, someInput);

// Actvity Function
[FunctionName("SomeActivityTask")]
public async Task<SomeResult> Run([ActivityTrigger] SomeInput someInput, ILogger log)
{
     throw new HttpResponseException(System.Net.HttpStatusCode.BadRequest);
}
```

### App Details

- Microsoft.Azure.WebJobs.Extensions.DurableTask: 2.2.2
- Azure Functions runtime version: v3
- Programming language used: C#

### Screenshots
![image](https://user-images.githubusercontent.com/5653381/91549860-bc711c00-e97b-11ea-90f0-293d2b5d0dac.png)

**Comment by ConnorMcMahon** [comment]
@jaliyaudagedara 

Behind the scenes, we use Newtonsoft.Json to serialize all of our inputs/outputs for activities, orchestrations, and entities, as well as all exceptions that are thrown by these functions. If your function throws an exception that is not serializable by our default settings, you have the following options:

1. Catch the `HttpResponseException` in your activity, and embed that information in an exception that is more friendly to serialization (either a custom exception you write, or something like `InvalidOperationException`.
2. Use [Azure Functions Dependency Injection](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection) to inject a custom `IErrorSerializerSettingsFactory` into Durable Functions, and we will use that instead of our default settings. We are tracking documenting this better as a part of #1208.

Hope that addresses your issue.

**Comment by jaliyaudagedara** [comment]
Thanks @ConnorMcMahon, makes sense!
