### ISSUE TITLE
/runtime/webhooks/durabletask/instances/<instanceid> documentation for Failed orchestrations incorrect

### ISSUE THREAD

**Issue by dixonte** [Azure/azure-functions-durable-extension#1469]
### Description
I have created a durable function to perform some action which may occasionally fail. To test this works as expected, I hard-coded an unhandled exception into the activity, then tested it in Postman. As expected, the orchestration retried the activity a number of times, and then failed. However, the status endpoint returns a 200 OK HTTP status when the orchestration fails.
This contradicts the documentation [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-instance-status) regarding response statuses.

### Expected behavior
As described in the documentation, I would expect the status endpoint to return 500 Internal Server Error because of the unhandled exception in my activity.

### Actual behavior
The status endpoint returns 200 OK when status of the task is 'Failed'.

### Relevant source code snippets
```csharp
       [FunctionName(nameof(SetColumnDefaultValues))]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Function, "post")] HttpRequestMessage req,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger log)
        {
            log.LogInformation($"Processing request on URI: {req.RequestUri}");

            // ... snip ...

            // Function input comes from the request content.
            string instanceId = await starter.StartNewAsync(nameof(SetColumnDefaultValues_Orchestration), null, input);

            log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

            return await starter.WaitForCompletionOrCreateCheckStatusResponseAsync(req, instanceId, timeout);
        }
```

```csharp
        [FunctionName(nameof(SetColumnDefaultValues_Orchestration))]
        public static async Task<string> SetColumnDefaultValues_Orchestration(
            [OrchestrationTrigger] IDurableOrchestrationContext context,
            ILogger log)
        {
            var input = context.GetInput<RequestModel>();

            // ... snip ...

            await context.CallActivityWithRetryAsync(nameof(SetColumnDefaultValues_SetDefaults), retryOptions, new SetDefaultsModel
            {
                Props = props,
                SiteUri = siteUri,
                List = input.List
            });

            return "All columns default value updated";
        }
```

```csharp
        [FunctionName(nameof(SetColumnDefaultValues_SetDefaults))]
        public static async Task SetColumnDefaultValues_SetDefaults(
            [ActivityTrigger] SetDefaultsModel input,
            ILogger log
        )
        {
            // ... snip ...

            throw new Exception("Hard-coded exception to test durable function status endpoint");
        }
```

### Known workarounds
I might try to work around this issue by implementing my own status endpoint, but as mentioned in #1449, the GetStatusAsync method returns null when an unhandled exception occurs. This would prevent said endpoint from offering any useful information.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.3.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

### Screenshots
https://imgur.com/a/g0n2Rga

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**: 2af205a644344b62ab43b9271daac930
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by amdeel** [comment]
Hey @dixonte, in this PR (https://github.com/Azure/azure-functions-durable-extension/pull/967) we added an option to opt-in to receiving a 500 when the orchestration fails. We added this optional parameter "returnInternalServerErrorOnFailure" to the CreateCheckStatusResponse APIs. You should be able to set this to true and have your expected behavior. It appears that our documentation is out of date for this, thank you for bringing this issue to our attention.

**Comment by dixonte** [comment]
@amdeel Is there any way to get this behaviour with WaitForCompletionOrCreateCheckStatusResponseAsync? I can see the option for CreateCheckStatusResponse but not WaitForCompletionOrCreateCheckStatusResponseAsync.

**Comment by ConnorMcMahon** [comment]
@dixonte,

Do you have control over your clients? If so, I would recommend that they look for the Status explicitly, as opposed to looking at the status code. We changed the default behavior for version 2.x of the extension as it is more clear from an API design perspective. You can see the discussion around that [here](https://github.com/Azure/azure-functions-durable-extension/issues/695).

As @amdeel mentioned, this definitely seems to be an area where our docs are out of date, so I will tag the issue as such.

I am going to open a separate issue for adding this option to `WaitForCompletionOrCreateCheckStatusResponseAsync`, so we can track that separately.

**Comment by dixonte** [comment]
@ConnorMcMahon My clients are mostly Logic Apps. So yes, I could check the status output, but doing so would mean adding a bunch of extra blocks. I would much rather just have the HTTP or Azure Fuction block just handle failure detection and retry automatically.

**Comment by cgillum** [comment]
I created a docs PR to document the `returnInternalServerErrorOnFailure` parameter here: https://github.com/MicrosoftDocs/azure-docs-pr/pull/137478.
