### ISSUE TITLE
Weird exception with URI when making DurableHttpRequest

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1473]
**DF extension version** 2.3.0

This is the first time I've used the `DuableHttpRequest` construct so I'm not sure if I'm doing something wrong here, but I get the following exception, when attempting to make a request to an external API. 

`{"Invalid URI: The format of the URI could not be determined."}`

However the API call actually completes successfully. It's a text message API and I get the SMS received to my phone so I know the request is actually successful. 

Any thoughts?

![image](https://user-images.githubusercontent.com/4224880/93004137-240e9600-f53c-11ea-8224-7de1c536541b.png)

**Comment by ConnorMcMahon** [comment]
@bachuv for visibility.

Given the symptoms you are describing, my guess is that the error is coming from our serialization (or deserialization) of the `DurableHttpResponse`, though I would expect that to appear in the stacktrace. Could you share more of the stacktrace with us, and if this is running in Azure, ideally an instance id + timestamp so we could look at our internal telemetry?
