### ISSUE TITLE
millisecond field in ISO8601 string value is changed unexpectedly between orchestrator and activity

### ISSUE THREAD

**Issue by horihiro** [Azure/azure-functions-durable-extension#1476]
### Description
When ISO8601 string `YYYY-MM-DDThh:mm:ss.SSS+hh:mm` is passed from orchestrator to activity and a millisecond field of the string ends with `0` in (ex, `.190`, `.300` and so on), the character `0` is omitted.
This behavior happens on even local debugging environment.

### Expected behavior
The activity can recieve the string value without any change.

### Actual behavior
As above, millisecond field of the string is changed, 

ex) when orchestrator passes string `2020-01-01T23:59:59.340+09:00`, activity receives string `2020-01-01T23:59:59.34+09:00`

### Relevant source code snippets
(orchestrator.ts)
```javascript
import * as df from "durable-functions"
 
const orchestrator = df.orchestrator(function* (context) {
  yield context.df.callActivity("activity", "2020-01-01T23:59:59.340+09:00"); 
  return;
});
```

(activity.ts)
```javascript
import { AzureFunction, Context } from "@azure/functions"
 
const activityFunction: AzureFunction = async function (context: Context): Promise<string> {
  context.log(context.bindings.msg);  // <-- "2020-01-01T23:59:59.34+09:00" is shown in console.
  return “”;
};
 
export default activityFunction;
```

### Known workarounds
The workaround should be done in function code level as followings.

  - break ISO8601 format before passing to activity in orchestrator by padding space
or
  - fix the string by padding `0` to the end of the millisecond field of the string in activity

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.3.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0 and 3.0
- **Programming language used**: javascript

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
This behavior can be reproduced on local debugging environment.

**Comment by davidmrdavid** [comment]
Hi @horihiro  ,

I _just_ made a release which should address this problem. Do you mind installing the latest release (1.4.4) and letting me know if it worked for you! Thanks :) 

⚡ ⚡

**Comment by horihiro** [comment]
Confirmed that this was fixed by https://github.com/Azure/azure-functions-durable-js/pull/217
