### ISSUE TITLE
How to use TaskHubClient?

### ISSUE THREAD

**Issue by klenium** [Azure/azure-functions-durable-extension#1489]
In [this](https://github.com/Azure/azure-functions-durable-extension/issues/65#event-2890633598) issue, they added support for custom JSON serialization settings. This is great.

But how can we use it? I can not find documentation for the use of TaskHubClient. Where does it come from? How can I configure it in my functions or startup?

My data passed to activities can have DateTimeOffset properties. I want to set up to handle them as UTC values automatically. How can I do that?

**Comment by amdeel** [comment]
To use your own JsonSerializerSettings, you can inject a custom IMessageSerializerSettingsFactory. This [link](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection) should help figure out how to use dependency injection with Functions. I believe the setting you are interested in is DateTimeZoneHandling specifically. You can check out our current default settings in this [file](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/MessageSerializerSettingsFactory.cs).

**Comment by klenium** [comment]
Thanks @amdeel this looks good for my work.
