### ISSUE TITLE
Orchestrations getting stuck for long period

### ISSUE THREAD

**Issue by kijujjav** [Azure/azure-functions-durable-extension#1491]
### Description
A lot of orchestrations are getting stuck for long periods before resuming the tasks.

examples : 1ffd0462ea804670842f04f6fc4b0f8b , cf395d161abe4aff99acdab85b5fc7d0, c192efd800d74bc7926b18536a535fec

### Expected behavior
Orchestrations should work as expected without any delay in between

### Actual behavior
> Observing long delays between sub-orchestrations

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.1.1
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: OnGoing
- **Function App name**: NetAssistStatefulWorkflow
- **Function name(s)**: ExecuteStatefulAction
- **Azure region**: 
- **Orchestration instance ID(s)**: West US
- **Azure storage account name**: functions use : netassistv2, Durable functions use : netassistv2durable

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by ConnorMcMahon** [comment]
This is being handled with an internal support ticket.
