### ISSUE TITLE
Too many control logs are shown

### ISSUE THREAD

**Issue by yuanweilei** [Azure/azure-functions-durable-extension#1497]
### Description
There are too many logs are shown in console, also in Application Insights after I update the Nuget to 
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.3.0 from 2.2.2
How I can disable them?
![image](https://user-images.githubusercontent.com/26296423/94503143-bef7b780-0240-11eb-82ed-ceb2b0a6c034.png)

I added these to host.json, but it doesn't work.
{
    "version": "2.0",
    "logging": {
        "logLevel": {
            "DurableTask.AzureStorage": "Warning",
            "DurableTask.Core": "Warning"
        }
    },

**Comment by cgillum** [comment]
This is a bug in the latest release of the Azure Functions Core Tools: https://github.com/Azure/azure-functions-core-tools/issues/2220. The next core tools release should include a fix that honors the logging settings that you specified.

@pragnagopa is there an ETA for the next core tools update that you can share which contains the fix for the logging issues?

**Comment by yuanweilei** [comment]
@cgillum Thank you very much!
I updated the Nuget from 2.2.2 to 2.3.0, to avoid deadlock issue (https://github.com/Azure/durabletask/pull/420), but now the latest Nuget takes my money because it stores lots of messages to Application Insights :(

Hopefully the team can fix this ASAP.

**Comment by pragnagopa** [comment]
Please find latest core tools here: https://github.com/Azure/azure-functions-core-tools/releases/tag/3.0.2931 until we officially update the tooling. 

ETA for release is by end of this week.

**Comment by yuanweilei** [comment]
Thank you @pragnagopa!
I am a beginner, could you please tell me if it means I don't need to do anything if I depoly my apps to Azure Function? (Just waiting the latest release?)
Or should I update some Nugets after the release?

**Comment by pragnagopa** [comment]
@yuanweilei  - please note that regression in core tools only affects when running locally and does not have any impact on apps running in Azure.

**Comment by yuanweilei** [comment]
Hi @cgillum 
I am so sorry I am confused because even my Azure Function apps get lots of logs as same as running locally, maybe I missed something?
![image](https://user-images.githubusercontent.com/26296423/94507503-dc318380-024a-11eb-8f6f-366e6d4f95fc.png)

![image](https://user-images.githubusercontent.com/26296423/94507724-595cf880-024b-11eb-8130-fe723eb7d9d9.png)

**Comment by yuanweilei** [comment]
Not only running locally but also in Application Insights.
I saw Verbose logs even I set Warning level.
"DurableTask.AzureStorage": "Warning",
"DurableTask.Core": "Warning"

**Comment by yuanweilei** [comment]
I am sorry, I injected TelemetryClient in Startup.cs which makes the host.json not working.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services

**Comment by cgillum** [comment]
Thanks @yuanweilei for letting us know that you found a solution!
