### ISSUE TITLE
Large dequeue counts on messages in task hub control queues

### ISSUE THREAD

**Issue by markheath** [Azure/azure-functions-durable-extension#150]
I've noticed both in local testing and with Azure deployed durable functions, that some messages seem to hang around in the control queues long after the workflows have (or should have) terminated with their dequeue counts slowly ramping.

I have to stop the function app to be able to examine the messages with Azure Storage Explorer, but when I do I can see that I have a bunch of messages relating to orchestrations I started two days ago whose dequeue counts are now 439.

Presumably these will eventually die when the message passes its expiration duration of a week, but what is causing them to stick around for so long?

Here's an example of one of the messages:

```
{  
   "$type":"DurableTask.AzureStorage.MessageData, DurableTask.AzureStorage",
   "ActivityId":"fdf2f734-811d-43b2-b194-dafd48a6f926",
   "TaskMessage":{  
      "$type":"DurableTask.Core.TaskMessage, DurableTask.Core",
      "Event":{  
         "$type":"DurableTask.Core.History.ExecutionStartedEvent, DurableTask.Core",
         "OrchestrationInstance":{  
            "$type":"DurableTask.Core.OrchestrationInstance, DurableTask.Core",
            "InstanceId":"b3c3e29336fd4c4bbe86bf61320cbd2d:0",
            "ExecutionId":"b8ad9f43cca940f6b9944c180c307d50"
         },
         "EventType":0,
         "ParentInstance":{  
            "$type":"DurableTask.Core.ParentInstance, DurableTask.Core",
            "Name":"ProcessVideoOrchestrator",
            "OrchestrationInstance":{  
               "$type":"DurableTask.Core.OrchestrationInstance, DurableTask.Core",
               "InstanceId":"54d934fa33e9460789832589fb15a470",
               "ExecutionId":"b3c3e29336fd4c4bbe86bf61320cbd2d"
            },
            "TaskScheduleId":0,
            "Version":""
         },
         "Name":"TranscodeOrchestrator",
         "Version":"",
         "Input":"\"example.mp4\"",
         "Tags":null,
         "EventId":-1,
         "IsPlayed":false,
         "Timestamp":"2018-02-01T21:02:09.0152661Z"
      },
      "SequenceNumber":0,
      "OrchestrationInstance":{  
         "$type":"DurableTask.Core.OrchestrationInstance, DurableTask.Core",
         "InstanceId":"b3c3e29336fd4c4bbe86bf61320cbd2d:0",
         "ExecutionId":"b8ad9f43cca940f6b9944c180c307d50"
      }
   }
}
```

If I query for the status of b3c3e29336fd4c4bbe86bf61320cbd2d it returns a 404 not found, but the parent instance of 54d934fa33e9460789832589fb15a470 returns a "running status"

The messages are for a variety of event types and relate to various orchestration ids. Here's another example

```
{  
   "$type":"DurableTask.AzureStorage.MessageData, DurableTask.AzureStorage",
   "ActivityId":"cf42b039-34cb-432e-a364-a66de7ffa189",
   "TaskMessage":{  
      "$type":"DurableTask.Core.TaskMessage, DurableTask.Core",
      "Event":{  
         "$type":"DurableTask.Core.History.SubOrchestrationInstanceFailedEvent, DurableTask.Core",
         "EventType":9,
         "TaskScheduledId":0,
         "Reason":"The activity function 'A_TranscodeVideo' failed. See the function execution logs for details.",
         "Details":null,
         "EventId":-1,
         "IsPlayed":false,
         "Timestamp":"2018-02-01T21:24:24.7455841Z"
      },
      "SequenceNumber":0,
      "OrchestrationInstance":{  
         "$type":"DurableTask.Core.OrchestrationInstance, DurableTask.Core",
         "InstanceId":"11e566cfd5cf46f3822428325d4406cd",
         "ExecutionId":"bbd76527ffbe4b0d8354986a4a340ba6"
      }
   }
}
```

In this case the instance id of 11e566cfd5cf46f3822428325d4406cd returns a status of completed if I query for workflow status.

Having messages like these stuck ones hanging around long-term in the queues means it is difficult to be confident that there are no workflows currently in progress costing you money or preventing you from upgrading to a new version of your workflows.

**Comment by cgillum** [comment]
Regarding this:

> If I query for the status of b3c3e29336fd4c4bbe86bf61320cbd2d it returns a 404 not found.

What happens if you query for **b3c3e29336fd4c4bbe86bf61320cbd2d:0** (including the **:0** at the end). The 404 is likely related to missing the **:0** suffix.

I assume you are using the latest 1.1.0-beta2 package? This might be the same issue that was mentioned here: https://github.com/Azure/azure-functions-durable-extension/issues/104. The short version is that messages were being added to the wrong queues, so we were failing to delete them properly.

Can you try adding the following package reference in you .csproj file?

```xml
<PackageReference Include="DurableTask.AzureStorage" Version="1.1.2-beta" />
```

This will update the version of the Durable Task Framework Azure Storage messaging layer used by Durable Functions. Note that you'll need to clear out your queues before upgrading to this version. Let me know if this resolves the issue. I'm going to try and get a new Microsoft.Azure.WebJobs.Extensions.DurableTask release out soon which will include this fix.

**Comment by markheath** [comment]
Yes, the **b3c3e29336fd4c4bbe86bf61320cbd2d:0** instance is found - it returns a `runtimeStatus` of "Failed" - hadn't twigged that ":0" was part of the id.

And yes, I'm using 1.1.0-beta2. I'll try the updated AzureStorage package and let you know how I get on.

**Comment by markheath** [comment]
OK finally got round to re-testing with the updated AzureStorage package and all is looking good. Ran a bunch of regular orchestrations plus an eternal one which I terminated, and have no leftover queue messages.

**Comment by cgillum** [comment]
This was fixed with the release of beta3.
