### ISSUE TITLE
Status endpoint extensibility

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [Azure/azure-functions-durable-extension#151]
Are there any plans to allow for some extensibility of the status endpoint?  E.g. it would be nice to be able to return some progress indicator for what ever long running process we have running.  That doesn't appear to be possible, currently.

**Comment by cgillum** [comment]
Would something like this work? https://github.com/Azure/azure-functions-durable-extension/issues/96

**Comment by Blackbaud-DanHamlin** [comment]
yes, that would be great. +1
