### ISSUE TITLE
Analyzer request: Emit a warning for usage of CancellationToken as a parameter in orchestrator functions

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#1526]
**Is your feature request related to a problem? Please describe.**
.NET Function Apps allow customers to bind to a [CancellationToken parameter](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-class-library#cancellation-tokens) to detect when the functions host is being shut down. We recently received a [question]() about whether this should be used for things like the `CreateTimer` API. My thinking is that customers should _never_ use this `CancellationToken` parameter in orchestrator function apps. I can't think of a scenario where it would not create problems.

**Describe the solution you'd like**
It would be great to have an analyzer rule that emits a warning if someone has a `CancellationToken` parameter in their orchestrator function.

**Comment by ConnorMcMahon** [comment]
I have definitely had customers cancel timers in a loop, and it caused the timer to always immediately return, resulting in an infinite loop in their code.

It was very hard to debug, so I am all for this.

**Comment by ConnorMcMahon** [comment]
I'm now not 100% positive that we want to emit a warning for all usages.

While I can't think of any cases where using a cancellation token would actually be helpful with the orchestration APIs, I'm fairly certain there are many cases where it is harmless. In fact, I think some examples of that are in our own samples/documentation, and we should definitely fix those if the cancellation tokens aren't actually providing value.

Introducing a warning for these harmless cases may cause customers with large code bases to turn off all of the Durable analyzers, as we have seen this happen in the past where we introduced false positives.
