### ISSUE TITLE
HTTP Raise Event Results in 404's Instead of 202's in ~5% of Instances

### ISSUE THREAD

**Issue by LeastOne** [Azure/azure-functions-durable-extension#1531]
### Description
I have a durable function orchestration which issues a call to an external service via `<CallHttpAsync>` passing the service a raise-event callback-url generated from `<CreateHttpManagementPayload>` and then waits for the response via `<WaitForExternalEvent>`. Meanwhile the external service completes its work immediately and issues a HTTP raise-event via the callback-url it received.

### Expected behavior
I would expect all of the HTTP raise-event callback invocations to be successful returning `202 Accepted` responses.

### Actual behavior
In approximately 5% of instances the callback returns `404 Not Found` instead of `202 Accepted` response. If I then repeat the call manually (e.g. via Fiddler) the second attempt always returns the expected `202 Accepted` response.

### Relevant source code snippets
The following is a simplified example which uses `<MockExternalCallWithCallback>` as the "external" service.

```csharp
using System;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.AspNetCore.Http;

using Newtonsoft.Json;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName(nameof(WorkflowTrigger))]
        public static async Task<HttpManagementPayload> WorkflowTrigger(
            [HttpTrigger(AuthorizationLevel.Function, "post")] HttpRequest request,
            [DurableClient] IDurableOrchestrationClient durableOrchestrationClient)
        {
            var baseUrl = $"{request.Scheme}://{request.Host}";
            var instanceId = await durableOrchestrationClient.StartNewAsync(nameof(WorkflowOrchestration), null, baseUrl);
            return durableOrchestrationClient.CreateHttpManagementPayload(instanceId);
        }

        [FunctionName(nameof(WorkflowOrchestration))]
        public static async Task<DateTime> WorkflowOrchestration(
            [OrchestrationTrigger] IDurableOrchestrationContext durableOrchestrationContext,
            [DurableClient] IDurableOrchestrationClient durableOrchestrationClient)
        {
            var baseUrl = durableOrchestrationContext.GetInput<string>();
            const string eventName = "external-invocation-complete";
            var httpManagementPayLoad = durableOrchestrationClient.CreateHttpManagementPayload(durableOrchestrationContext.InstanceId);
            var callbackUrl = httpManagementPayLoad.SendEventPostUri.Replace("{eventName}", eventName);
            await durableOrchestrationContext.CallHttpAsync(HttpMethod.Post, new Uri($"{baseUrl}/api/{nameof(MockExternalCallWithCallback)}"), callbackUrl);
            return await durableOrchestrationContext.WaitForExternalEvent<DateTime>(eventName);
        }

        [FunctionName(nameof(MockExternalCallWithCallback))]
        public static async Task MockExternalCallWithCallback(
            [HttpTrigger(AuthorizationLevel.Function, "post")] HttpRequest request)
        {
            var reader = new StreamReader(request.Body);
            var callbackUrl = await reader.ReadToEndAsync();
            var content = JsonConvert.SerializeObject(DateTime.UtcNow);
            await new HttpClient().PostAsync(callbackUrl, new StringContent(content, Encoding.Default, "application/json")); // <-- Results in 404's instead of 202's in aprox 5% of instances, why?
        }
    }
}
```

### Known workarounds
Inspecting the callback status code response for 404's I'm able to repeat the call until a non-404 is returned.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.3.0
- **Azure Functions runtime version (1.0 or 2.0)**: v2
- **Programming language used**: C#

### Screenshots
The following is a screenshot from Fiddler showing the 404 responses.
<img width="960" alt="Screenshot 2020-10-18 224029" src="https://user-images.githubusercontent.com/5291141/96399942-2d230080-1195-11eb-894a-3a5722017409.png">

### If deployed to Azure
Presently only run locally. Related to this the problem seems to be exacerbated when the Azure Storage Emulator has been cleared.

**Comment by olitomlinson** [comment]
@LeastOne 

Have you tried running your app locally but against a real Azure Storage Account? Its known that the Azure Storage Emulator is a little flaky, so its not recommended.

**Comment by LeastOne** [comment]
@olitomlinson thanks for your suggestion. I conducted three separate tests using new and existing storage accounts issuing several thousand requests and it worked flawlessly! Its good to know that the Azure Storage Emulator is flaky, I'll definitely keep this in mind in the future. This issue can be considered closed.

**Comment by olitomlinson** [comment]
@LeastOne glad I could help!

@cgillum do we have any guidance on the docs discouraging the use of the Local Storage Emulator? 

Or would a runtime/Roslyn warning be possible if it detects an emulator?

Also, has the landscape changed regards to supporting Azurite?
