### ISSUE TITLE
Durable Entity replays operations, returns incorrect result to caller

### ISSUE THREAD

**Issue by AdrianPell** [Azure/azure-functions-durable-extension#1533]
(Originally posted to azure-function-host. Moved here as a better repo)

Please provide the following:

- Timestamp: 2020-10-06T07:02:55.5527382Z
- Function App version: 3.0.14492.0
- Function App name: 
- Function name(s) (as appropriate): 
- Invocation ID: c9b533b1-dd82-5e9c-8641-8094083e714f
- Region: West US 2

This relates to Durable Entities. DEs should operate in a stateful manner - with synchronous execution and predicable results. We are seeing some cases where occasionally some operations on a DE are being run against a spurious instance (after checkpointing) and then replayed against the real instance ... which would be ok, except that the calling orchestrator had already received and acted on the result.

The invocation ID above was one of those replayed.

In detail:

- DE is checkpointed after operation b310797e-f3ee-4119-a626-9d151aff9902 (see log entry: totalRunning=4)
- Next operation c9b533b1-dd82-5e9c-8641-8094083e714f completes at 2020-10-06T07:02:55.5527382Z (log at start: totalRunning=0 - clean state, result: TRUE)
- ...
- DE checkpoints again after operation 039df537-c4a3-5f28-a524-523f43c862a1 (at 2020-10-06T07:02:55.5825952Z) (log: totalRunning=4)
- DE restarts with previous state
- ...
- Operation c9b533b1-dd82-5e9c-8641-8094083e714f completes again at 2020-10-06T07:02:58.3633326Z (this time: result: FALSE)

Calling orchestrator meanwhile had received the TRUE response and acted accordingly

Related information:

* Programming language used C#
<details>
<summary>Source for called function on Durable Entity</summary>

```csharp
        public Task<bool> StartInstance((string instanceId, int clientId) param)
        {
            var queue = QueueFor(param.clientId);
            logger.LogTrace($"StartInstance instanceId={param.instanceId} clientId={param.clientId} totalRunning={CurrentTaskCount} queueRunning={queue.TotalRunning} queueLength={queue.Queue.Count}");
            if (CurrentTaskCount < MaxTotalTasks && queue.TotalRunning < MaxTasksPerClient)
            {
                CurrentTaskCount++;
                queue.TotalRunning++;
                logger.LogTrace($"Return TRUE - totalRunning={CurrentTaskCount} queueRunning={queue.TotalRunning} queueLength={queue.Queue.Count}");
                return Task.FromResult(true);
            }
            else
            {
                queue.Queue.Enqueue(param.instanceId);
                logger.LogTrace($"Return FALSE - totalRunning={CurrentTaskCount} queueRunning={queue.TotalRunning} queueLength={queue.Queue.Count}");
                return Task.FromResult(false);
            }
        }
```
</details>

<details>
<summary>Extract from calling orchestrator</summary>

```csharp
            var proxyEntityId = new EntityId(nameof(SourceRequestController), message.ProviderName);
            context.SignalEntity(proxyEntityId, "Configure", (provider.MaxConcurrentRuns, provider.MaxConcurrentRunsPerClient));

            if (!(await context.CallEntityAsync<bool>(proxyEntityId, "StartInstance", (context.InstanceId, message.ClientId))))
            {
                if (!context.IsReplaying)
                    logService.Info($"Source report {message.Id} is waiting");
```
</details>

**Comment by AdrianPell** [comment]
I'm also seeing some (perhaps related) issues with the caller occasionally not receiving a reply from the durable entity.

**Comment by sebastianburckhardt** [comment]
Yes, this is a bug in how entities are persisted in the AzureStorage durability provider. DTFx should really be saving the result of an entity work item to storage *before* sending any messages produced by this work item (like the response sent back to the orchestrator).

**Comment by AdrianPell** [comment]
@sebastianburckhardt Ah - thanks. Any ETA on when that might get addressed? I'm currently working around it with some ugly timeout code ... but definitely not ideal!

**Comment by ConnorMcMahon** [comment]
@sebastianburckhardt, is this something we can fix in DurableTask.AzureStorage, or is this a case where changing the order would introduce a different set of trade offs that would manifest in some other way?

@AdrianPell, I will look at your specific case to see if this inconsistency is due to an app recycle, or if it is due to something like split brain. If it is caused by split brain, we recently introduce a new partition management strategy in v2.3.0 that should almost entirely reduce split brain. You can try this out by setting extensions.durableTask.storageProvider.useLegacyPartitionManagement=false in your host.json. This new strategy will be turned on by default in our very soon to be release 2.3.1 update.

**Comment by ConnorMcMahon** [comment]
@AdrianPell, a quick look into the internal telemetry verified that what caused this specific inconsistency was split brain (i.e. two workers trying to process the same entity at the same time). Following the instructions above should greatly reduce the frequency in which you see this error pop up.

**Comment by AdrianPell** [comment]
@ConnorMcMahon Thanks for the suggestion. I'll try that and see what happens!

**Comment by AdrianPell** [comment]
@ConnorMcMahon I've been running with the setting you suggested for the last few days and things are certainly better.  I've not seen any errors that could be directly attributed to the problem I mentioned. There have been a few cases where messages from a durable entity to an orchestrator are being lost - a few where the reply to a CallEntityAsync is never received, and one today where a RaiseEventAsync from the entity was never received. Should I raise a separate issue for those?

**Comment by ConnorMcMahon** [comment]
@AdrianPell,

Glad to hear that this resolved that specific issue. I would say we close this issue, and open up another with the relevant instance ids, and timestamps for expected events so that we can investigate that.

Thanks for your patience here. We are trying to hammer out the last of reliability bugs, and we have made good progress, but now and then we find a few stragglers!

**Comment by AdrianPell** [comment]
Closing for now. Still exploring other issues - will open new issue as appropriate.
