### ISSUE TITLE
With two functions in Azure, the one which doesn't have app lease occasionally runs an orchestration

### ISSUE THREAD

**Issue by bendursley** [Azure/azure-functions-durable-extension#1535]
### Description
I've noticed that we're seeing some of our Orchestrations running on the service which doesn't have the current app lease.  From my understanding, this shouldn't be possible, as only the app which has the lease should be able to run the orchestrations.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.3.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

Happy to privately share task hub name, function name and times.

**Comment by amdeel** [comment]
@bendursley Can you email me to share more details about this incident? Amanda.Deel@Microsoft.com

**Comment by bendursley** [comment]
Have worked with @amdeel and it's an activity running (see #1540) so it's fine on our side.  Going to close this now
