### ISSUE TITLE
[2.3.1] Possible regression - 6 day max timespan on WaitForExternalEvent Timeout.

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#1538]
This code was causing the orchestration to fail : 

` var result = context.WaitForExternalEvent<JObject>($"external_event_{eventId}", TimeSpan.FromDays(14), cancelToken: cts.Token);`

With the following exception : 

`The Azure Storage provider supports a maximum of 6 days for time-based delays (Parameter 'timeout')`

If I change the timeout to 6 days, it works as expected, no exceptions.

It was my assumption that the max limit on timers was lifted in 2.3.0, so this may be a regression.

**Comment by ConnorMcMahon** [comment]
Hmm, I believe this is a regression. Thanks for bringing this to our attention.

I will make sure we investigate this, add a test for this case, and fix the regression in v2.4.0.

**Comment by ConnorMcMahon** [comment]
Looks like this is not a regression, just a bug where we missed removing of a timer length validation check. I believe removing this no longer required validation should just make everything work, but I will write some tests to capture this.
