### ISSUE TITLE
Status query HTTP API should return a failure status code when the orchestrator fails

### ISSUE THREAD

**Issue by skype007** [Azure/azure-functions-durable-extension#154]
Hello to the team,

I'm working on a Logic App Workflow where it consists of sending an XML file (which comes from a SFTP server) into the container of a StorageAccount and then process it thanks to an Azure Function. I'm using Durable Functions because the task is to insert data from the XML file into a database. So I have 3 functions:
- Start (HttpTrigger)
- RunOrchestrator (OrchestrationTrigger)
- DoWork (ActivityTrigger)

In the workflow, it always launch the Start function :+1:  But most of the time it seems it doesn't run the Orchestrator (no logs in the monitor of the Azure Function in Azure portal)

Start:
```
public class ProcessRequest
{
    public string Data { get; set; }
}

[FunctionName("InsertDataInDatabase_Start")]
public static async Task<HttpResponseMessage> Run(
    [HttpTrigger(AuthorizationLevel.Function, "post")]HttpRequestMessage req,
    [OrchestrationClient]DurableOrchestrationClient starter,
    TraceWriter log)
{
    try
    {
        log.Info($"C# Http trigger InsertDataInDatabase_Start processed.");

        // Function input comes from the request content.
        var content = await req.Content.ReadAsStringAsync();
        ProcessRequest requestData = new ProcessRequest
        {
            Data = content
        };

        log.Info($"Calling orchestrator...");
        string instanceId = await starter.StartNewAsync("InsertDataInDatabase_Orchestrator", requestData);
        log.Info($"End call orchestrator");

        log.Info($"Started orchestration with ID = '{instanceId}'.");

        var response = starter.CreateCheckStatusResponse(req, instanceId);

        // I specify a response interval so the Logic App doesn't check the status
        // until after 10 seconds has passed. If work will be longer you can change this 
        // value as needed.
        response.Headers.RetryAfter = new RetryConditionHeaderValue(TimeSpan.FromMinutes(3));
        return response;
    }
    catch (Exception ex)
    {
        log.Error($"Error : {ex.Message}");
        return req.CreateResponse(HttpStatusCode.InternalServerError, ex.Message);
    }
}
```
RunOrchestrator:

```
    [FunctionName("InsertDataInDatabase_Orchestrator")]
    public static async Task<List<string>> RunOrchestrator(
        [OrchestrationTrigger] DurableOrchestrationContext context, TraceWriter log)
    {
        log.Info("Orchestrator running...");
        try
        {
            var outputs = new List<string>
            {
                await context.CallActivityAsync<string>("InsertDataInDatabase_DoWork", context.GetInput<ProcessRequest>())
            };
            return outputs;
        }
        catch (Exception ex)
        {
            log.Error($"ERROR: {ex.Message}");
            throw ex;
        }
    }
```

DoWork:

```
    [FunctionName("InsertDataInDatabase_DoWork")]
    public static async Task<string> DoWork(
        [ActivityTrigger] ProcessRequest requestData,
        TraceWriter log)
    {
        log.Info($"C# Http trigger function InsertDataInDatabase_DoWork Processed.");

        // Processing requestData

        return "Operation done.";
    }
```

The Logic App workflow tells me that the action "Launch Azure Functions" has a green check....but in the body indicates : 

```
{
  "runtimeStatus": "Failed",
  "input": {
    "$type": "MyFunctions.ProcessRequest, MyFunctions",
    "Data": "MOCKS_100K.xml"
  },
  "output": "The activity function 'InsertDataInDatabase_DoWork' failed. See the function execution logs for details.",
  "createdTime": "2018-02-14T17:02:39Z",
  "lastUpdatedTime": "2018-02-14T17:02:42Z"
}
```

Here's my environment:
- Microsoft.Azure.WebJobs.Extensions.DurableTask : version 1.1.0-beta2
- Azure Functions Runtime (Function App in Azure) : version 1.0.11535.0

**Comment by kashimiz** [comment]
Thanks for cross-posting this from [StackOverflow.](https://stackoverflow.com/questions/48775710/logic-apps-and-azure-functions-durable-functions-doesnt-fit-well/48778544#48778544) and providing logs. To make it easier to investigate this issue, could you provide the name of your Function App in Azure? You can do so without publicly sharing it by following the steps [here.](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately)

**Comment by skype007** [comment]
Hi @kashimiz, thank you for your quick reply :) Here's what you need : 

`2018-02-15T08:38:26  Welcome, you are now connected to log-streaming service.2018-02-15T08:38:28.073 [Info] Function started (Id=90987c48-b81d-4949-8fae-9b154ca14ea1)2018-02-15T08:38:28.073 [Info] C# Http trigger MasterdataSAPLoader_Start processed.2018-02-15T08:38:28.073 [Info] Calling orchestrator...2018-02-15T08:38:28.088 [Info] End call orchestrator2018-02-15T08:38:28.088 [Info] Started orchestration with ID = '538e71374472401abdf72c73e277510e'.2018-02-15T08:38:28.088 [Info] Function completed (Success, Id=90987c48-b81d-4949-8fae-9b154ca14ea1, Duration=15ms)`

**Comment by skype007** [comment]
@cgillum Thank you for your reply ;) Do you have more information about the exception ? It's strange because as I said  when I use the same file, the runtimeStatus could be either "Completed" or "Failed" (I didn't change a configuration ^^ )

I should tell you that some exceptions (System.Net.WebException for example) occured because I tried to launch it directly from the Azure Portal to provide you the logs needed to locate my function app ;)

**Comment by cgillum** [comment]
Hi @skype007 sorry once again for the delay. I went ahead and looked in our Azure telemetry and found the following error message for the run that you posted previously:

```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: MasterdataSAPLoader_DoWork ---> System.ArgumentException: The argument must not be empty string.
Parameter name: blobName
   at Microsoft.WindowsAzure.Storage.Core.Util.CommonUtility.AssertNotNullOrEmpty(String paramName, String value) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\Util\CommonUtility.cs:line 143
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.GetBlockBlobReference(String blobName, Nullable`1 snapshotTime) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Blob\CloudBlobContainer.Common.cs:line 263
   at Total.Backend.Functions.Masterdata.MasterdataSAPLoader.DoWork(ProcessRequest requestData, TraceWriter log)
```
As for App Insights, you should also be able to search for general error messages the same way you do for normal functions. You don't necessarily have to filter looking for Durable Functions events.

I'm not sure why you wouldn't be finding the data you're looking for in Application Insights. One thing you could try is disabling sampling in the Application Insights configuration in host.json to see if maybe that information is getting sampled out:

```json
{
  "applicationInsights": {
    "sampling": {
      "isEnabled": false
    }
  }
}
```

**Comment by skype007** [comment]
Sorry for the long delay @cgillum But I used as a workaround a ServiceBusTrigger.
But when I tested for fun the new version of the package (1.2.0-beta3), it's better than befoire :D  Hope it's right but if this new package really solves the problem, perhaps it's because of DurableTask.AzureStorage (https://github.com/Azure/azure-functions-durable-extension/issues/104). I followed your advice at a certain moment : it didn't work at the time but maybe it's because I forgot to clear the queues (in the StorageAccount).

Anyway, the improvement that should be done, is the LogicApp that returns Success whereas the Azure Function return : "runtimeStatus": "Failed"

**Comment by cgillum** [comment]
Thanks @gled4er for the PR to fix this! The change will go out with today's release.

**Comment by daharmon** [comment]
Did this ever make it out into the wild? We are trying to test how our logic app responds to errors. The logic app step shows "runtimeStatus": "Failed" for the orchestrator like it should but the status code is 200 so the logic app thinks everything is good and keeps moving on.

**Comment by amdeel** [comment]
Hey, @daharmon. We made the http status code for orchestrator failures configurable here: https://github.com/Azure/azure-functions-durable-extension/pull/967

To use this, set the optional parameter "returnInternalServerErrorOnFailure" to true on our CheckStatusResponse APIs.

**Comment by daharmon** [comment]
got it. Thanks! I have a question - what is a good use case for not having this value default to true?

**Comment by amdeel** [comment]
@daharmon Check this issue out for our reasoning: https://github.com/Azure/azure-functions-durable-extension/issues/695

**Comment by henrylinviolin** [comment]
it looks like the configurability is only added to the C# version of CheckStatusResponse. Any guidance on using the javascript version - client.createCheckStatusResponse(context.bindingData.req, instanceId);
