### ISSUE TITLE
Can not trigger durable function starter from CosmodDb change feed

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-functions-durable-extension#1548]
I want to start an orchestrator after CosmosDB change feed events but I am failing because of this error **Unable to load metadata for function**

What I have is durable function

```csharp
[FunctionName("LockMonitor")]
public static async Task<List<string>> RunOrchestrator(
[OrchestrationTrigger] IDurableOrchestrationContext context)
{
    var input = context.GetInput<dynamic>(); //not triggered
}

public static async Task Start(
[CosmosDBTrigger("TestDb", "ContainerName",
ConnectionStringSetting = "CosmosDbConnectionString",
LeaseCollectionName = "ContainerLeases",
CreateLeaseCollectionIfNotExists = true)] IReadOnlyList<Document> input,
[DurableClient] IDurableOrchestrationClient client,
ILogger logger)
{
     string instanceId = await client.StartNewAsync("LockMonitor", input);
}
```

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "CosmosDbConnectionString": "both emulator or azure hosted one have same issue"
  }
}
```

Debugger by Visual Studio 2019 Updated on Windows 10

So when I change a document in CosmosDB given container, I get this error:

```diff
-[2020-11-05T03:24:34.766Z] Host lock lease acquired by instance ID '0000000000000000000000008CC1CF71'.
-[2020-11-05T03:24:44.999Z] Executed 'LockMonitor.Start' (Failed, Id=17fa9cf0-2559-43e4-b2d6-7970ece39a47, Duration=52ms)
-[2020-11-05T03:24:45.002Z] Microsoft.Azure.WebJobs.Script.WebHost: Unable to load metadata for function 'Start'.
```

Two questions
- Am I designing it right? is this how a durable function delay should be?
- How to solve the error? I want the orchestrator to be triggered by CosmosDB and all online example are for HttpTrigger

**Comment by ConnorMcMahon** [comment]
Hmm, from what I can tell there is nothing wrong with the code you have provided that would cause this issue. It looks like this is related to [this code](https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Host/FunctionMetadataManager.cs) in the Functions runtime, rather than a bug with Durable Functions.

That being said, could you provide a minimal complete repro? I could use this to investigate why the FuncitonMetadataManager isn't finding your function metadata, and either get a developer from that repository to fix this bug or I can fix the bug myself. We could also hopefully provide you with a workaround in the meantime.

**Comment by MhAllan** [comment]
Hi @ConnorMcMahon ,

Thank you so much for your reply. While I was preparing demo for you I tried to add `[FunctionName]` to the starter function and that solved the problem.

**Comment by vllirette** [comment]
> Hi @ConnorMcMahon ,
> 
> Thank you so much for your reply. While I was preparing demo for you I tried to add `[FunctionName]` to the starter function and that solved the problem.

Thanks! While browsing the web for the same issue
```
[2021-03-10T21:32:18.573Z] Executed 'DurableJobsIngestion.RunScheduled' (Failed, Id=f4af6032-75d4-49f6-829e-e90ee43f3cae, Duration=729ms)
[2021-03-10T21:32:18.575Z] Microsoft.Azure.WebJobs.Script.WebHost: Unable to load metadata for function 'RunScheduled'.
```
I found this thread and adding `[FunctionName]` also fixed my issue 😃

**Comment by nnamacha** [comment]
Thanks helped me too

**Comment by ConnorMcMahon** [comment]
This is likely something that could be automatically detected with an analyzer for Functions (if you are using a binding attribute in a method parameter, that method should also use the FunctionName attribute).
