### ISSUE TITLE
Simple API to get status/terminate/raise-event URLs

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#155]
### Problem
HTTP triggers have a way to return an HTTP response with the get-status, terminate, and raise-event webhook URLs embedded in a JSON payload. However, there is no simple way to get this information for non-HTTP triggered functions. Even when using HTTP, there is no simple way to share these URLs with other systems.

### Suggestion
Create a `GetWebHookUrls` API which takes the instance ID as a parameter and returns a data structure containing the webhook URLs. This API could exist on `DurableOrchestrationClient`, `DurableOrchestrationContext`, and `DurableActivityContext` classes.

For non-.NET functions, we can consider using binding parameters to flow this information.

**Comment by cgillum** [comment]
However, thinking about this more, it's often simple enough to create new HTTP-trigger functions and call the corresponding `DurableOrchestrationClient` methods. We should weigh the benefit of this feature over the ability to implement this manually.

**Comment by gled4er** [comment]
Hello @cgillum,

I think this feature will be useful in cases we need to pass send event, status or terminate url-s from the orchestrator external systems. 

If you remember we had similar scenario when we needed to pass the send custom event url to a logic app that did few steps and then post back to the orchestrator. The issue in this case was that we couldn't retrieve the key from the orchestration context and we passed the url from the orchestration client back to the orchestrator. 

I am interested in your guidance on this feature.

Thank you!

**Comment by cgillum** [comment]
Great! Here is my thinking for this: Let's update [HttpApiHandler.GetClientResponseLinks](https://github.com/Azure/azure-functions-durable-extension/blob/aa4180cf457c2bf7e5cbdc3e971164e539d906a8/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L335) to accept a null `HttpRequestMessage` value. If it is null, then we can instead use the value in the `notificationUri` variable. This `Uri` should be used to replace our usage of `request.RequestUri` in this method.  Something like this:

```csharp
Uri notificationUri = this.config.NotificationUrl;
Uri baseUri = request?.RequestUri ?? notificationUri;

// e.g. http://{host}/admin/extensions/DurableTaskExtension?code={systemKey}
string hostUrl = baseUri.GetLeftPart(UriPartial.Authority);

// ...rest of the method...
```

We could then create a method similar to `GetClientResponseLinks`, but which instead returns a new data structure containing these three URLs. That could be exposed all the way up to our public methods - e.g. as a peer to `CreateCheckStatusResponse`.

One question is whether we want to expose this only to `OrchestrationClient` bindings or if we want orchestrator and activity functions to have this as well. If we want the others to be able to use it, then I think we just need to pass in empty parameters for `OrchestrationClientAttribute attribute` since those triggers won't have such an attribute. Even better if we can refactor the method so that it takes a `taskHub` parameter and a connection string name property instead of an `OrchestrationClientAttribute` (that would be cleaner).

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you very much for the detailed instructions!

I will work on implementing the design you set.

Thank you very much!
