### ISSUE TITLE
Expose setting retry options for CallHttpAsync method

### ISSUE THREAD

**Issue by gled4er** [Azure/azure-functions-durable-extension#1559]
**Is your feature request related to a problem? Please describe.**
We have an use case where the last step of an orchestration is PATCH request to a HTTP endpoint. We would like to set retry options to the `CallHttpAsync` method to ensure that the HTTP endpoint is called several times if it is not available. 

Currently the `CallHttpAsync` does not expose way to set retry options and for that we will need to use dedicated activity function to configure the retry options. 

**Describe the solution you'd like**
We would prefer `CallHttpAsync ` to expose configuring retry options as part of the method or new dedicated CallHttpWithRetryAsync

**Describe alternatives you've considered**
The only alternative we considered is to use dedicated activity function that will wrap the PATCH request.

**Comment by brandonh-msft** [comment]
<details><summary>Internal tracking</summary>
405440
</details>
