### ISSUE TITLE
Document strategy for handling confidential information data processed by Durable Functions

### ISSUE THREAD

**Issue by gled4er** [Azure/azure-functions-durable-extension#1560]
**Is your feature request related to a problem? Please describe.**
We have an use case in which we need to process PHI data with Durable Functions. The PHI files are bigger than 60 KB and they result as blob files in the storage account. One of the requirements we need to follow is to have the storage account with network restricted access. 

**Describe the solution you'd like**
It will be helpful to consider our approach and describe it as a guidance so more people can use it. We end up using two storage accounts for the Durable Function. The first one that is used for the history entries and is network restricted and set via the `AzureWebJobStorage` app setting. The second one is set via the `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` and only contains the deployment zip package. This storage account still needs to be open for access from all networks. The official Azure Function documentation recommends to use only open to all networks storage accounts. However, Durable Functions depends heavily on the history data and in our opinion requires additional guidance for setting up properly the environment to meet enterprise security requirements related to sensitive data. 

**Describe alternatives you've considered**
The alternatives we had was to build our own orchestration layer on top of Azure Functions and queues in between which is time consuming is error-prone.

**Comment by ConnorMcMahon** [comment]
In general, the recommendation for limiting network access to Azure Storage is to use Premium Functions (or a dedicated app service plan) with a VNET, and configure Service Endpoints for that VNET.

The dual storage account strategy that you mentioned is due to a limitation with Service Endpoints not working properly with Azure Files, though I believe that either recently or in the near future is being fixed via an App Service deployment. I will look into that.

**Comment by ConnorMcMahon** [comment]
The documentation for locking down storage accounts of an Azure Function app [now exists here](https://docs.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network). It also includes instructions for keeping content and the Durable Functions content on one storage account and having that account have network restricted access.
