### ISSUE TITLE
Activating a ADF with a queue and call an activity

### ISSUE THREAD

**Issue by pablocastillaquintas** [Azure/azure-functions-durable-extension#157]
Hi!

Maybe it is a trivial question but I haven't found the solution in the documentation also I haven't been able to do it in code.

Is it possible to create an orchestration by a queue trigger and call an activity using CallActivityAsync? It seems I don't have context to do it.

Thanks

**Comment by pablocastilla** [comment]
Ok, the only way is to call to StartNewAsync and later in the function you called you are in the "orchestration" context.

Also if you want to call from an external system using queues, imagine a web page, you have to call to a AF and raise an event with RaiseEventAsync or to call directly from the web page using REST.

Just for helping I miss a few things: 
- An example with a web page.
- A direct client for activating orchestrations out of any AF.
- Redefine the RaiseEventAsync to something like SendCommandAsync. In the future if we use this framework as orchestrations we will like to send events to multiple instances of different orchestrations. I don't see the instanceid in a RaiseEvent function. Take a look at NServiceBus or MassTransit, I feel how they define events and commands is the standard.

I think your work is really interesting, having orchestrations in AF is a crucial feature.

Thanks!

**Comment by cgillum** [comment]
We don't support calling activity functions outside of the orchestration context. It is an interesting idea, so I opened a separate issue to track the idea: https://github.com/Azure/azure-functions-durable-extension/issues/160

You raise another important issue though, which is the ability to create an instance of [DurableOrchestrationClient](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationClient.html) outside the Azure Functions context. It looks like we don't have a public constructor for this type, so it's not currently possible. However, I think it should be easy to add. Is this something interesting to you?

**Comment by pablocastilla** [comment]
Yes it is. I would like to create orchestrations directly from a client. That means sending a message to a queue, isn't it?

**Comment by cgillum** [comment]
We don't want to expose the details of the Azure Storage queues publicly, so instead we would need to create a new public API for this.  I've opened a separate issue for tracking: https://github.com/Azure/azure-functions-durable-extension/issues/161

Thanks for this great suggestion!
