### ISSUE TITLE
Event Trigger do not trigger Orchestration Method

### ISSUE THREAD

**Issue by ameitagarwal** [Azure/azure-functions-durable-extension#1587]
My ProcessJob_EventGrid gets fired on creation of new blob files which is as per my expectation , however the Orchestration method HelloWorld do not get fired. 

[FunctionName("ProcessJob_EventGrid")]
        public  async Task EventGridTest([EventGridTrigger] EventGridEvent eventGridEvent, [DurableClient] IDurableOrchestrationClient starter, ILogger log)
        {
            JObject objData = JObject.Parse(eventGridEvent.Data.ToString());

            // Tried all the below 3
            string instanceId = await starter.StartNewAsync("HelloWorld");
            //string instanceId = await starter.StartNewAsync("HelloWorld", JsonConvert.SerializeObject(objData)); // error
            //string instanceId = await starter.StartNewAsync("HelloWorld",null, JsonConvert.SerializeObject(objData));

            log.LogInformation($"Started orchestration with ID = '{instanceId}'.");
        }       

        [FunctionName("HelloWorld")]
        public  async Task<string> Run(
        [OrchestrationTrigger] IDurableOrchestrationContext context,ILogger log)
        {
            log.LogInformation("Orchestration Fired");
            string name = context.GetInput<string>();
            string result = await context.CallActivityAsync<string>("SayHello", name);
            return result;
        }

        [FunctionName("SayHello")]
        public string SayHello([ActivityTrigger] IDurableActivityContext helloContext)
        {
            string name = helloContext.GetInput<string>();
            return $"Hello {name}!";
        }

**Comment by ameitagarwal** [comment]
I could find the real issue here. Although the Orchestration do get trigger but the logs were not due to which I was in impression that the Orchestration never got triggered.

**Comment by ConnorMcMahon** [comment]
@ameitagarwal,

I apologize for the original mark of this issue to "Needs:Author Feedback", that was an accident, as we never properly triaged your issue.

To clarify, did you figure out how to get the logs working for your orchestration function?

**Comment by ameitagarwal** [comment]
No , Since the logging is not at all working with Durable functions. Although I plan to use some third party logging.

**Comment by ameitagarwal** [comment]
Closing the issue.
