### ISSUE TITLE
Durable Orchestrator keeps starting the same activity again and again

### ISSUE THREAD

**Issue by cenh** [Azure/azure-functions-durable-extension#1588]
### Description
I have a singleton durable function where I do (Omitted some code):

```csharp
[FunctionName("myStarter")]
         public static async Task<HttpResponseMessage> HttpStart(
             [HttpTrigger(AuthorizationLevel.Anonymous, methods: "post", Route = "CalculateLines/{instanceId}")] HttpRequestMessage req,
             [DurableClient] IDurableOrchestrationClient starter,
             string instanceId,
             ILogger log)
         {
             var existingInstance = await starter.GetStatusAsync(instanceId);
             if (existingInstance == null || existingInstance.RuntimeStatus == OrchestrationRuntimeStatus.Completed
             || existingInstance.RuntimeStatus == OrchestrationRuntimeStatus.Failed
             || existingInstance.RuntimeStatus == OrchestrationRuntimeStatus.Terminated)
             {
                 string jsonContent = req.Content.ReadAsStringAsync().Result;
                 await starter.StartNewAsync("RunOrchestrator", instanceId, jsonContent);
                 log.LogInformation($"Started orchestration with ID = '{instanceId}'.");
                 return starter.CreateCheckStatusResponse(req, instanceId);
             }
             else
             {
                    
                 return new HttpResponseMessage(HttpStatusCode.Conflict)
                 {
                     Content = new StringContent($"An instance with ID '{instanceId}' already exists."),
                 };
             }
         }
 [FunctionName("RunOrchestrator")]
     public static async Task RunOrchestrator(
         [OrchestrationTrigger] IDurableOrchestrationContext context)
     {
         if (!context.IsReplaying)
         {
             string body = context.GetInput<string>();
             await context.CallActivityAsync("ActivityRunner", body);
         }
     }
 [FunctionName("ActivityRunner")]
 public static void ActivityRunner([ActivityTrigger] string body, ILogger log)
 {
      log.LogInformation("Starting new activity");
      // do more
 }
```

### Expected behavior
When calling the Orchestration Trigger one orchestration will start, and that orchestration will only call one activity once.

### Actual behavior
The orchestration keeps starting the same activity over and over again.

### Relevant source code snippets
See above

host.json:
```
  "extensions": {
    "durableTask": {
      "storageProvider": {
        "workItemQueueVisibilityTimeout": "01:00:00",
        "controlQueueVisibilityTimeout": "01:00:00"
      },
      "hubName": "FameFunctionHub",
      "maxConcurrentActivityFunctions": 1,
      "maxConcurrentOrchestratorFunctions": 1
    }
  },
  "functionTimeout": "01:00:00"
```

### Known workarounds
None so far
    
### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.3.1
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots
![image](https://user-images.githubusercontent.com/6737225/100422760-2f795400-308b-11eb-8e9d-a5a049ce4a04.png)

### If deployed to Azure
- **Timeframe issue observed**: Currently (2020/11/26)
- **Function App name**: lbp-fame-fa-we-dev
- **Function name(s)**: CalculateLinesForDate (Activity) CalculateLines (HttpTrigger) RunCalculateLinesOrchestrator (OrchestrationTrigger)
- **Azure region**: WE
- **Orchestration instance ID(s)**: 1
- **Azure storage account name**: lbpfamefawedev

**Comment by pkwitbrod** [comment]
I am experiencing the same issue. It also happens locally in VSCode. It will attempt to start multiple instances of the trigger on startup and start more instances while the activity is running even though the trigger is only being hit once.

**Comment by ConnorMcMahon** [comment]
Investigating this now.

**Comment by ConnorMcMahon** [comment]
@cenh,

From what I can tell, our platform keeps killing your application because there is less than ~100 MB of physical memory free on the VM. When we hit this level, we automatically kill your app to avoid the VM from getting into a state where it is constantly page thrashing and we need to reboot the worker to recover it.

It looks like you are on E1 workers, which have 3.5 GB of physical memory.  As a short term mitigation, I would try upgrading to an E2 which should have ~7GB of physical memory. However, a single activity function consuming over 3GB of memory is concerning, so I would check your code to see if you can minimize that.

On a side note, your orchestration code violates our deterministic requirements. `context.IsReplaying` returns different values across different orchestration replays, so you should not use it for control flow. It is meant almost exclusively for logging statements, to avoid duplicate orchestration logs across replays.

**Comment by ConnorMcMahon** [comment]
@pkwitbrod 

Given what I found with the original poster's issues, it is very unlikely you are experiencing the same issue. Please file a separate issue and we can help you investigate that.
