### ISSUE TITLE
The new IDurableOrchestrationClient.RestartAsync() API only works inside your Function App's context

### ISSUE THREAD

**Issue by scale-tone** [Azure/azure-functions-durable-extension#1592]
### Description

Since internally it is nothing more than a call to .StartNewAsync(), same logic and same validation rules seem to be applied. Specifically, that the relevant orchestrator function must exist and be properly registered.

This sort of defeats the purpose, because when inside your Function App you can always re-trigger .StartNewAsync() with the same set of parameters, so no big need in a separate restart method. The typical challenge is to "fix the problem" from outside, e.g. with a script or a [monitoring tool](https://github.com/scale-tone/DurableFunctionsMonitor).

### Expected behavior
[.RestartAsync()](https://github.com/Azure/azure-functions-durable-extension/pull/1545) method succeeds, no matter whether the current .Net project has the corresponding orchestrator function defined in it or not.

### Actual behavior

An exception is thrown:

> System.Private.CoreLib: Exception while executing function: PostOrchestration. Microsoft.Azure.WebJobs.Extensions.DurableTask: The function 'ProcessAppointmentOrchestrator' doesn't exist, is disabled, or is not an orchestrator function. Additional info: No orchestrator functions are currently registered!.

### App Details

- **Durable Functions extension version**: 2.4.0
- **Programming language used**: C#

**Comment by cgillum** [comment]
Hey @scale-tone, thanks for this feedback. The purpose of this feature is really as a convenience. Like you said, someone could certainly implement it themselves but having it be built in reduces the amount of code a user needs to worry about and maintain.

That said, I can see how this might be even more useful if it can be invoked from a remote application (like [yours](https://github.com/scale-tone/DurableFunctionsMonitor)). Is your idea to inject an `IDurableClient` in a separate management app (like an ASP.NET Core app) and initiate a restart from there?

**Comment by scale-tone** [comment]
> this might be even more useful if it can be invoked from a remote application

Yes. Shouldn't it be as simple as bypassing this validation inside StartNewAsync() method?

> Is your idea to inject an IDurableClient in a separate management app (like an ASP.NET Core app) and initiate a restart from there?

As of today, DFM uses a normal Functions host and instantiates IDurableClient in a normal way - [via a binding](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.dotnetbackend/Functions/Orchestrations.cs#L26). This approach works so far (despite the obvious fact that the actual orchestrators/entities are missing), and I do dare to hope there will be no breaking changes that can potentially break it :)
The ability to [explicitly create](https://github.com/Azure/azure-functions-durable-extension/pull/1125) *multiple* instances of IDurableClient indeed looks promising, as it would allow to monitor all your TaskHubs with one single DFM deployment (or a single DFM backend process instead of one per TaskHub, when using [VsCode ext](https://marketplace.visualstudio.com/items?itemName=DurableFunctionsMonitor.durablefunctionsmonitor)). Would require some refactoring though...

**Comment by amdeel** [comment]
Hey, @scale-tone.

The RestartAsync API does use the same validation as the StartNewAsync API. However, we actually currently allow customers to start orchestrators that are defined in other function apps. If you are starting the orchestrator from another function app, you can specify the TaskHub/ConnectionName for the second app in the DurableClient attribute. If you're using an IDurableClientFactory, this should work as well (see our new ToDoList sample). The restart API should work in the same way.

Did you try specifying the TaskHub/ConnectionName of your second app in your DurableClient attribute when you saw this exception?

**Comment by scale-tone** [comment]
> Did you try specifying the TaskHub/ConnectionName of your second app in your DurableClient attribute when you saw this exception?

I am [indeed specifying TaskHub name via DurableClientAttribute.TaskHub](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.dotnetbackend/Functions/Orchestration.cs#L63). But it turned out that there was also an old unused **durableTask.hubName** setting left in my [host.json](https://github.com/scale-tone/DurableFunctionsMonitor/blob/master/durablefunctionsmonitor.dotnetbackend/host.json#L8). Once removed, the RestartAsync() method started working!

Great, we're now going to have a "Restart" button in DFM! Thanks a lot, @amdeel !
