### ISSUE TITLE
Azure Orchestrator App Service is using memory unpredictably

### ISSUE THREAD

**Issue by OlivierReddman** [Azure/azure-functions-durable-extension#1594]
### Description
I have an orchestration Function that calls several activity Functions (one of them several hundreds of times). The Function works well and seems to use a reasonable amount of memory, under 100MB with several spikes to a few hundred.

After noticing the available memory of the App Service is down to basically zero for several hours, I restart the App Service. This is while the Orchestrator has finished running. This has happened several times, and memory seems to have small random spikes at other times. It will occasionally even max out for several minutes and fall back down. App Insights shows no traces during this time.

### Expected behavior
Memory should increase during Function execution, then fall and remain low until the next execution

### Actual behavior
After several runs of the Orchestrator, memory has seemingly random spikes and occasionally gets maxed out

### Relevant source code snippets
```csharp
[FunctionName("MonitorStart")]
public async Task RunAsync(
    [TimerTrigger("%MonitoringTriggerTime%", RunOnStartup = false)]TimerInfo myTimer,
    [DurableClient(TaskHub = "backofficeHub")] IDurableOrchestrationClient starter)
{
    _logger.Trace($"C# Timer trigger function executed at: {DateTime.Now} (local time)");
    _logger.Info("[Monitoring] STARTED MONITORING");

    var siteList = await _siteManager.GetSiteList(1, 1).ConfigureAwait(false);
    var paginationInfo = siteList.PaginationInfo;

    var maxConcurrencyConfig = await _configurationProvider.GetMonitoringMaxConcurrency().ConfigureAwait(false);
    var maxConcurrency = int.Parse(maxConcurrencyConfig);

    await starter.StartNewAsync("MonitoringProcessOrchestrator",
        new MonitoringProcessParameters
        {
            StartTime = DateTime.UtcNow,
            PaginationInfo = paginationInfo,
            MaxConcurrency = maxConcurrency
        });
}

[FunctionName("MonitoringProcessOrchestrator")]
public async Task<string> MonitoringProcessOrchestrator([OrchestrationTrigger] IDurableOrchestrationContext context)
{
    LogOnce(context, _logger.Trace, "MonitorSites");
    var processParameters = context.GetInput<MonitoringProcessParameters>();

    var page = 0;
    var pageSize = _generalConfig.GetMonitoringConfigPageSize();

    bool moreRecords;
    var monitoringTasks = new List<Task<MonitoringResult>>();

    do
    {
        page++;

        if (monitoringTasks.Count(monitoringTask => !monitoringTask.IsCompleted) >= processParameters.MaxConcurrency)
        {
            await Task.WhenAll(monitoringTasks);
        }

        var pageMonitoringTask = context.CallActivityAsync<MonitoringResult>("MonitorPageActivity",
            new MonitorPageParameters
            {
                Page = page,
                PageSize = pageSize
            });

        monitoringTasks.Add(pageMonitoringTask);
        moreRecords = processParameters.PaginationInfo.TotalRecords > page * pageSize;
    } while (moreRecords);

    var results = await Task.WhenAll(monitoringTasks);

    await context.CallActivityAsync("SendMonitoringEmails",
        new MonitoringEmailParameters
            {
                Results = results,
                TotalPages = page,
                StartTime = processParameters.StartTime
            });

    return context.InstanceId;
}

private void LogOnce(IDurableOrchestrationContext context, Action<string> action, string message)
{
    if (context.IsReplaying) return;
    action.Invoke(message);
}
```

### Known workarounds
We monitor the memory usage and restart the app when necessary

### App Details

- **Durable Functions extension version**: 2.2.2
- **Azure Functions runtime version**: ~3
- **Programming language used**: C#

### Screenshots
![48h memory (2)](https://user-images.githubusercontent.com/75500476/101205681-fcf7ca00-363b-11eb-9790-e035b741fd78.PNG)

**Comment by ConnorMcMahon** [comment]
It's important to note that Durable Functions, when running an orchestration, has to store its entire history in memory. This includes activity and suborchestration inputs and outputs. If you have an orchestration with a very long history, a history with large inputs/outputs, or both, it is possible that this could be the culprit behind your spikey memory load. The way I would mitigate this would be to pass around smaller inputs/outputs (by passing around pointers/references to data rather than the data itself), or to use `.ContinueAsNew()` to clear the entire history periodically.

Note that due to how the Durable Task Framework handles replays, some of the tasks never get garbage collected, resulting in a small memory leak over time (see #340). I don't believe this is the root cause here, as I would expect that to be a slow and steady climb in memory usage rather than spikey usage like this.

If the above mitigations don't help out, I would recommend [taking a memory dump](http://jsandersblog.azurewebsites.net/2020/01/02/how-to-get-and-analyze-a-memory-dump-azure-app-services/) and opening a support ticket so the product team can take a closer look at what is going on.

**Comment by OlivierReddman** [comment]
Thank you for your response. I don't think our inputs and outputs are large enough to cause these issues. Looking at a typical Orchestration input in the HubInstances table, it has 352 characters.

Our last orchestration has 767 Table storage values. Could this be enough to cause a noticeable slowdown?

The HubHistory table has close to 400,000 entries. Could this degrade performance? I assumed not, since the previous orchestrations have completed by the time a new one runs.

I'm considering flushing the history table to see how it affects performance

**Comment by ConnorMcMahon** [comment]
@OlivierReddman,

Given what you described, it sounds like it isn't storing the queue messages or history in memory is the problem. The 400,000 entries should not be a concern, as you mentioned, as we should only be loading those for the current orchestration instance at a time.

I think the next step is to grab a memory dump during the high memory usage case. You can send it directly to me at Connor.McMahon@microsoft.com, or open a support case and tell them the product team told you to open a ticket against them.

**Comment by ConnorMcMahon** [comment]
@OlivierReddman,

Just checking in to see if you have been able to get a memory dump.

**Comment by OlivierReddman** [comment]
@ConnorMcMahon, I have taken one, but not during an elevated memory period. Based on the last thirty days, the worst events have happened three time exactly ten days apart. I will see if it happens again on Sunday (last time was November 23rd) and take a memory dump then.

In the mean time, I'm looking into anything on our end that happens every ten days

![memory profile](https://user-images.githubusercontent.com/75500476/101905841-13df7480-3b86-11eb-8de0-f9cba2a1713f.PNG)

**Comment by ConnorMcMahon** [comment]
@OlivierReddman,

I believe we are pursuing this conversation offline. I'm going to resolve this ticket for now, as it is unlikely to be helpful for other customers and these problems often need to be tackled on a case-by-case basis.
