### ISSUE TITLE
Can't get multi root workspace to work with multiple durable orchestrations

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/azure-functions-durable-extension#1596]
Hi

I have been trying for days to debug a multi root workspace which uses durable functions to communicate, I have got the http triggers to work on both roots, but i can't get the durable functions on multiple roots work.

Can you confirm this will work and hopefully point me in the right direction

Just to clarify I want an orchestration in one root to call an orchestration in a different root

**Comment by amdeel** [comment]
Hey, @EnenDaveyBoy. Just to clarify your question a little bit more, are you trying to raise an event with an orchestrator in another function app? If so, you can accomplish this by using our [RaiseEventAsync API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.raiseeventasync?view=azure-dotnet#Microsoft_Azure_WebJobs_Extensions_DurableTask_IDurableOrchestrationClient_RaiseEventAsync_System_String_System_String_System_String_System_Object_System_String_) on IDurableClient.

**Comment by EnenDaveyBoy** [comment]
thanks but that won't solve the issue, let me try to re explain.

Running in visual studio code, I have multi root workspace with project a and project b, these are both individual roots, so when i debug the solution they both have their own debugging sessions and urls.

so lets say they both have a httptrigger the urls might be

http://127.0.0.1:5067/api/projecta/products
http://127.0.0.1:5072/api/projectb/orders

however i have an orchestration function in projectb that i want to run from projecta, how do i do it?

**Comment by amdeel** [comment]
@EnenDaveyBoy If you are starting an orchestrator from another function app, you can specify the TaskHub/ConnectionName for the second app in the DurableClient attribute.

If this isn't helpful, can you provide more information on what exactly you're trying to do, what you've tried, and what errors you've seen?

**Comment by EnenDaveyBoy** [comment]
i have it working with context.CallHttpAsync, thanks for the help
