### ISSUE TITLE
Mono.Posix.NETStandard is making the deployment package size excessively large

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-durable-extension#1597]
**Is your feature request related to a problem? Please describe.**

`Mono.Posix.NETStandard` was included since Durable Functions v2.3.1, which increased the size of the deployment package by nearly three times.

Especially in the case of Windows, Mono.Posix is not necessary, only the size of the package will increase.

**Describe the solution you'd like**

`Mono.Posix.NETStandard` is used to perform rename in the `LinuxAppServiceFileLogger`, an implementation that can be replaced with a couple of lines of P/Invoke.

**test branch**
https://github.com/Azure/azure-functions-durable-extension/compare/dev...shibayan:remove-mono-posix

**Describe alternatives you've considered**

You can reduce the package size by downgrading to Durable Functions v2.3.0.

**Additional context**

**raw directory size**

![image](https://user-images.githubusercontent.com/1356444/101328038-d68f9400-38b2-11eb-8648-a326165ea3db.png)

**zipped package size**

![image](https://user-images.githubusercontent.com/1356444/101328306-2e2dff80-38b3-11eb-9e1a-b58b5424a555.png)

**Comment by davidmrdavid** [comment]
Thank you for raising this issue @shibayan! Indeed, the new dependency appears far too big to justify how little it's used. The only reason why we needed it was to ensure that the correct system signals are raised in UNIX, which had been a problem in the past. As you point out, P/Invoke _should_ be enough to provide this functionality. I'll make this a priority for our next release and should be able to start working on it in a few days!

Also, we should consider adding a package-size check to our release process, to avoid this in the future.

⚡  ⚡

**Comment by davidmrdavid** [comment]
Just a note to self, for documentation:
It seems that the changes suggested are the same as in the internal implementation of `Mono`, _which is great_: https://github.com/mono/mono/blob/da11592cbea4269971f4b1f9624769a85cc10660/mcs/class/Mono.Posix/Mono.Posix/Syscall.cs#L324

and this article (https://developers.redhat.com/blog/2019/03/25/using-net-pinvoke-for-linux-system-functions/) suggests the change should be safe.
