### ISSUE TITLE
Undesired behavior for durable entity with character '/' in entity key

### ISSUE THREAD

**Issue by hannaleena** [Azure/azure-functions-durable-extension#1601]
### Description
We are facing an issue with durable entites that have character '/' in their entity key, e.g. @entityname@test/test. We noticed this, when an entity operation failed for such an entity, and the entity kept on retrying the operation every 10 minutes. However, the entity is not visible in our Instances or History tables, nor is it returned with `IDurableOrchestrationClient's ListInstancesAsync` method or with _IDurableClient's ListEntitiesAsync_ method like other entities.

We tried to delete such entity's state with `Entity.Current.DeleteState()`, calling it with `IDurableEntityClient's SignalEntityAsyn`c method from a http triggered function (called DeleteEntityState). That results in the following error: `System.Private.CoreLib: Exception while executing function: DeleteEntityState. Microsoft.Azure.WebJobs.Extensions.DurableTask: entityKey (Parameter 'Entity keys must not contain /, \, #, ?, or control characters.')`.

We normally call (and create) entities with `IDurableOrchestrationContext's CallEntityAsync` method. And we can see entity operations running also with '/' in their key when checking `Entity.Current.EntityId.EntityKey` while debugging.

We would like to understand:
- Are there really some forbidden characters in entity keys as the `IDurableEntityClient `error implies? And why didn't we see any errors when creating the entity with `IDurableOrchestrationContext`?
- What makes it do these periodical retries? We haven't at least consciously defined any retry policies.
- And, most importantly, how can we make it just fail and stop retrying like the other entities? Or do we need to manually add a check for forbidden characters before calling any entities?

### Expected behavior
An entity should execute an operation once, unless instructed otherwise. Also, if entities are created, they should appear in lists and their state should be manageable. Or then entities should not be created.

### Actual behavior
When calling an entity with `IDurableOrchestrationContext's CallEntityAsync` method, you can create entities that keep on executing, and don’t get listed to tables or List queries.

### Relevant source code snippets
Example of creating a entity that will not show in Instance table, and will keep on executing the `EntityOperation`.
```csharp
    public class DummyEntity
    {
        private readonly ILogger _log;

        public DummyEntity(ILogger log)
        {
            _log = log ?? throw new ArgumentNullException(nameof(log));
        }

        [FunctionName(nameof(DummyEntity))]
        public static Task Run(
            [EntityTrigger] IDurableEntityContext context,
            ILogger log)
            => context.DispatchAsync<DummyEntity>(log);

        public void EntityOperation()
        {
            _log.LogInformation(Entity.Current.EntityKey);
        }
    }

    public static class TestFunctions
    {
        [FunctionName(nameof(StartDummyEntity))]
        public static async Task<HttpResponseMessage> StartDummyEntity(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequestMessage req,
            [DurableClient] IDurableClient client)
        {
            await client.StartNewAsync(nameof(DummyEntityOrchestrator));

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        [FunctionName(nameof(DummyEntityOrchestrator))]
        public static async Task DummyEntityOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            var entityKey = "test/test";
            var entityId = new EntityId(nameof(DummyEntity), entityKey);

            await context.CallEntityAsync(entityId, nameof(DummyEntity.EntityOperation));
        }
    }

```

### Known workarounds
-

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.3.1
- **Azure Functions runtime version (1.0 or 2.0)**: v3
- **Programming language used**: C#

### Screenshots
-

### If deployed to Azure
-

**Comment by ConnorMcMahon** [comment]
@hannaleena,

Thanks for filing this issue. I think this is already being tracked at #1579, so I am going to close this issue in an effort to keep all communication regarding this issue in one place.

That being said, I will post an update there this morning to come up with an action plan to reduce the pain this is causing.
