### ISSUE TITLE
Invest in CI reliability

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1602]
Our CI has been failing somewhat frequently recently.

We should investigate why, and continue to invest until our CI until we hit the below reliability criteria:

- Less than 1 in 20 CI runs that would have succeeded fail due to test flakiness.
- Our CI pipeline can tolerate multiple concurrent queued runs without increasing the likelihood of false negatives.

**Comment by davidmrdavid** [comment]
Transferring to release 2.4.2
