### ISSUE TITLE
New partition manager logs introduced in v2.3.1 are noisy

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1605]
### Description
Looking at the logs generated by the DurableTask.AzureStorage logging category in both internal telemetry and emitted to App Insights, the new partition management strategy seems to generate more logs without them being very useful in practice.

We should make an effort to reduce these logs to only events that are useful for diagnosing issues, or at least lower the level for many of these log statements.

**Comment by davidmrdavid** [comment]
Transferring to release 2.4.2
