### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by davidmrdavid** [Azure/azure-functions-durable-extension#1606]
As previously discussed and agree'd to, we'll be renaming the master branch to main.

We can probably just take this approach: https://www.hanselman.com/blog/easily-rename-your-git-default-branch-from-master-to-main 

**Out-of-Proc Requirements**
This ticket is not done until the renaming also occurs for JS and Python

**Question:**
This change will require updating our CI references to build from the right place. I believe that's all we need to do though, is there any thing else?

**Comment by davidmrdavid** [comment]
Folks will also need to update their local `origin` references to point to `main`. Just a heads up!

**Comment by cgillum** [comment]
Updating the Azure DevOps pipeline and local origin references is all that I'm aware of, based on my experience.

**Comment by davidmrdavid** [comment]
Created `main` branch alternatives in the following repos:

https://github.com/Azure/azure-functions-durable-extension/tree/main
https://github.com/Azure/azure-functions-durable-js/tree/main
https://github.com/Azure/azure-functions-durable-python/tree/main
https://github.com/Azure/durabletask/tree/main

The artifact-deployment pipeline for `durable-extensions` in Azure DevOps has also been updated to track `durable-extensions`'s `main` branch.

Two things remain:
(1) Updating the CI for DurableJS and DurablePython to track `main`. This might be already happening though.
(2) Changing the default branch for DTFx to be `main` in the GitHub UI. I don't have the permissions for this though. I would need access first :)

**Comment by davidmrdavid** [comment]
Completed!
