### ISSUE TITLE
Support creating DurableOrchestrationClient outside of Azure Functions

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#161]
This issue tracks the ability to create an instance of [DurableOrchestrationClient](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationClient.html) outside the Azure Functions context. It looks like we don't have a public constructor for this type, so it's not currently possible. 

Here is the relevant source code: https://github.com/Azure/azure-functions-durable-extension/blob/master/src/WebJobs.Extensions.DurableTask/DurableOrchestrationClient.cs#L27.

The challenge will be creating a very simple public constructor that only requires an Azure Storage connection string and a task hub name.

**Comment by ConnorMcMahon** [comment]
This is getting pushed to October release.

**Comment by cgillum** [comment]
The PR for this is merged and will go out with v2.4.0.
