### ISSUE TITLE
End to End Testing Bot ToDos

### ISSUE THREAD

**Issue by bachuv** [Azure/azure-functions-durable-extension#1610]
Goals for the end to end testing validation pipeline:
1. Enable automated end-to-end testing of Durable Functions from GitHub PRs​
2. Test against different functions versions (1.0, 2.0, 3.0) and app plans (Elastic Premium, Consumption, Windows, Linux)​
3. Create a suite of automated performance, stress, and fault-injection tests​
4. Get automated test results through AppLens

This issue will track the tasks to complete the Test Bot and integrate it into the durable-extension repo.

### Durable PowerShell Deployment Service
- [x] Create resource group function
- [x] Create storage account function
- [x] Create function app function (including specific functions versions and app plans)
  - [x] Add EUAP region
- [x] Create function app plan function (for EP Plans)
- [x] Delete resource group function

### Test Bot App
- [x] GitHub Bot Auth
  - [x] Implement auth flow with pfx file and access tokens
  - [x] Move pfx file and subscription ID to Azure Key Vault and read it from the Bot App
- [x] Edit PR comments with updates instead of creating new ones

### Other
- [x] AppLens detectors
- [x] ~~Add a copy of the queries used in AppLens to the GitHub PR update message~~ queries can be found in the AppLens detector's Data Sources tab
- [x] Integrate durable-bot into durable-extension repo

**Comment by davidmrdavid** [comment]
Transferring over to release 2.4.2
