### ISSUE TITLE
Sub-orchestrator function intermittently runs multiple times (including activity functions)

### ISSUE THREAD

**Issue by Methuselah96** [Azure/azure-functions-durable-extension#1612]
### Description

Every once in a while we have a sub-orchestrator function that executes multiple times and causes all of its activity functions to be run multiple times.

### Expected behavior

A replay of a sub-orchestrator should not cause its activity functions to re-run.

### Actual behavior

We see duplicate results of a sub-orchestrator's activity functions being re-run.

### Known workarounds

None.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.3.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

### If deployed to Azure

- **Timeframe issue observed**: 11/5/20 3:00PM-4:00PM ET
- **Function App name**: ComponentDesignProcessor
- **Function name(s)**: ComponentDesignProcessorMessageOrchestrator
- **Azure region**: East US 2
- **Orchestration instance ID(s)**: Not sure how to find this

**Comment by amdeel** [comment]
Hey @Methuselah96, could you provide an instanceId for the sub-orchestrator that you saw being rerun? InstanceId is ParitionKey in table storage.

**Comment by Methuselah96** [comment]
@amdeel The `instanceId` is `c35733ca631142969833d66c9a412f37:21`. Thanks!

**Comment by Methuselah96** [comment]
@amdeel This may or may not be helpful, but if I look in the logs for November 5 (in `AzureWebJobsHostLogs202011`) and filter by the `FunctionName` for one of the activity functions run by the sub-orchestrator, I see that the number of log statements is a multiple of 42 for each activity function, when each activity function should only be run 41 times (which was the number of sub-orchestrations that were requested).

**Comment by lilyjma** [comment]
@Methuselah96 -- Are you still experiencing this issue?

**Comment by Methuselah96** [comment]
We have greatly reduced our usage of Azure Functions due to issues like this, so no. :)

**Comment by davidmrdavid** [comment]
Sorry to hear that. Please do reach out again if we can be of help; this issue fell through the cracks. Thank you.
