### ISSUE TITLE
How to access DurableEntityClient in an injected class

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/azure-functions-durable-extension#1616]
**I cannot access the DurableEntityClient in a reference (injected) class**

I have an Azure Functions project that leverages Dependency Injection (`Startup` class injects services based on the different interfaces). Those services that implement the interfaces are using constructor dependency injection as well.

In one of those implementations, I want to call a method on a Durable Entity, but I prefer not to make the `DurableEntityClient` part of the method signature (as other implementations might not need the EntityClient at all). So therefore, I was hoping to see that `IDurableEntityClient` injected in the constructor of my implemented class.

But it turns out the value is `null` and it is not injected by the runtime yet.  Wondering if this is something that I can achieve myself and would be feasible? (to have a DI-friendly way of injecting classes that want to get the EntityClient for the Functions runtime they are running in)

**Solution I'd like**

_In Startup.cs_

```csharp
builder.Services.AddSingleton<IReceiver, TableReceiver>();
builder.AddDurableEntityClient(); // Having something like this would be nice
```

_Referenced class where EntityClient is needed_

```csharp
public class TableReceiver : IReceiver
{
    private IDurableEntityClient _entityClient;

    public TableReceiver(IDurableEntityClient client)
    {
        _entityClient = client; // client is null 
    }
}
```

_Actual function_

```csharp
public class ItemWatchHttpTrigger
{
    private IReceiver _receiver;

    public ItemWatchHttpTrigger(IReceiver receiver)
    {
        _receiver = receiver;
    }

    [FunctionName("item-watcher")]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Function, "get", Route = "item/{itemId}")]
        HttpRequest request, string itemId, [DurableClient] IDurableEntityClient client, ILogger logger)
    {
        // Actual implementation
    }
}
```

**Describe alternatives you've considered**

I could obviously make the methods of the `IReceiver` interface for my class in such a way that they receive the `IDurableEntityClient` as a method parameter, but that would mean that all my injected implementations would need to reference that package, which is something I prefer to avoid.

**Comment by olitomlinson** [comment]
@SamVanhoutte 

I believe you should be able to do this with the latest release of the Extension. Version 2.4.0. I don't think any official docs have been released yet.

Here is an example of how to do it in an ASP.NET project, but I imagine its the same in a Functions project.

https://github.com/Azure/azure-functions-durable-extension/blob/821b862f534684d8ffab5e58cddeb94b563e6c9b/samples/todolist-aspnetcore/Startup.cs#L27

https://github.com/Azure/azure-functions-durable-extension/blob/821b862f534684d8ffab5e58cddeb94b563e6c9b/samples/todolist-aspnetcore/Controllers/TodoController.cs#L25

**Comment by SamVanhoutte** [comment]
Awesome - that does the trick.  Thanks !

**Comment by olitomlinson** [comment]
@SamVanhoutte You're welcome!

**Comment by twiga2013** [comment]
Hi, I am getting Invalid container name. Check MSDN for more information about valid container naming. Here is my
localsettings.json 

{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "TaskHub": "E1_HelloSequence",
    "Storage": "DefaultEndpointsProtocol=https;AccountName=f******;AccountKey=******;EndpointSuffix=core.windows.net"
  },

public class ClientFunction
    {
        private readonly IDurableClient _client;

        public ClientFunction(IDurableClientFactory clientFactory, IConfiguration configuration, ILogger<ClientFunction> logger)
        {
          

            _client = clientFactory.CreateClient(new DurableClientOptions
            {
                
                 ConnectionName = "Storage",
                 TaskHub = configuration["TaskHub"],
                 IsExternalClient = true
            });
        }

**Comment by twiga2013** [comment]
Hi,

I got it to work but the OrchestrationRuntimeStatus is stuck on Pending. The Orchestrator Function never gets executed. What am I missing? Thanks
