### ISSUE TITLE
Upgrading from Microsoft.Azure.WebJobs.Extensions.DurableTask Version= 2.3.1 to version 2.4.0 creates compile conflict with System.Reactive 4.4.0

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-functions-durable-extension#1620]
### Description
Create a function project and reference both nuget packages mentioned in the title of this ticket. Write a piece of code like the following snippet:

```csharp
IObservable<T>.Subscribe(
				onNext: _ =>
				{
					//do something
				},
				onError: exception =>
				{
					//do something
				},
				onCompleted: () =>
				{
					//do something
				});
``` 
You will get the following compile error:

> Error | CS0121 | The call is ambiguous between the following methods or properties: 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>, System.Action<T>, System.Action<System.Exception>, System.Action)' and 'System.ObservableExtensions.Subscribe<T>(System.IObservable<T>, System.Action<T>, System.Action<System.Exception>, System.Action)' | 

### Expected behavior
There should not be a compile error.

### Actual behavior
The compile error quoted above happens.

### Relevant source code snippets
Already shared.

### Known workarounds
None

### App Details

- **Durable Functions extension version 2.4.0**:
- **Azure Functions runtime version 3.1**:
- **Programming language used**: C#

### Screenshots
n/a

### If deployed to Azure
No

**Comment by Arash-Sabet** [comment]
@cgillum Could you please have someone look into this issue? I have had to revert to version 2.3.1 of `Microsoft.Azure.WebJobs.Extensions.DurableTask` to avoid this conflict.

**Comment by Arash-Sabet** [comment]
@anthonychu Would you please let me know who the best person is to escalate this issue to? This issue is a blocker to progress further.

**Comment by ConnorMcMahon** [comment]
@Arash-Sabet 

So this looks like due to a dependency taken by DurableTask.Core (v2.5.0) on System.Reactive.Core v3.x. I don't think this dependency is required, as it builds without it, so we can likely remove this in a subsequent release.

As a workaround in the meantime, I found this [stackoverflow answer](https://stackoverflow.com/a/53106274/9035640).  You can either force System.Reactive.Core up to v4 by explicitly including it with v4.4.1 in your csproj, or you can use System.Reactive.Compatibility nuget package to resolve the issue.

**Comment by Arash-Sabet** [comment]
> @Arash-Sabet 
> 
> 
> 
> So this looks like due to a dependency taken by DurableTask.Core (v2.5.0) on System.Reactive.Core v3.x. I don't think this dependency is required, as it builds without it, so we can likely remove this in a subsequent release.
> 
> 
> 
> As a workaround in the meantime, I found this [stackoverflow answer](https://stackoverflow.com/a/53106274/9035640).  You can either force System.Reactive.Core up to v4 by explicitly including it with v4.4.1 in your csproj, or you can use System.Reactive.Compatibility nuget package to resolve the issue.

Thanks. I will have the workaround given a try. When do you think the new subsequent release will be ready after the removal of the dependency?

**Comment by ConnorMcMahon** [comment]
Currently targeting code freeze of tomorrow, release by January 20th.

**Comment by ConnorMcMahon** [comment]
It turns out that System.Reactive.Core _is_ required now by DurableTask.Core, so we will be adding System.Reactive.Compatibility as well to avoid the conflict.

**Comment by Arash-Sabet** [comment]
[The workaround](https://stackoverflow.com/a/53106274/9035640) caused some other changes in our code which are vaster than one area. A lot of changes need to be done in referenced libraries and therefore nuget packages to be updated and deployed. So, we have to wait for the new release by Microsoft. @ConnorMcMahon

**Comment by davidmrdavid** [comment]
Closing because the corresponding PR has been merged ⚡ ⚡
