### ISSUE TITLE
NullReferenceException in DurableClient created via IDurableClientFactory

### ISSUE THREAD

**Issue by JackSkylark** [Azure/azure-functions-durable-extension#1626]
### Description
I'm experiencing an unhandled `NullReferenceException` when trying to signal an entity from a durable client created by a `IDurableClientFactory`. The exception is coming from here:

https://github.com/Azure/azure-functions-durable-extension/blob/821b862f534684d8ffab5e58cddeb94b563e6c9b/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L302

### Expected behavior
I should be able to use the durable client in the same way that I'd use it from a bound function. In my case, I should be able to call `SignalEntityAsync` from a durable client created from `IDurableClientFactory`.

### Actual behavior
The `DurableClient` throws a `NullReferenceException` when calling methods if the client has been created from an `IDurableClientFactory`.

### Relevant source code snippets
From a quick glance at the source, it appears that this issue stems from the fact that the private field `config` on `DurableClient` is not set when created from the `DurableClientFactory`.

When resolving `DurableClient` from `DurableClientFactory`, the following constructor is called:

https://github.com/Azure/azure-functions-durable-extension/blob/821b862f534684d8ffab5e58cddeb94b563e6c9b/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L46

When resolving `DurableClient` from `DurableTaskExtension` the following constructor is called:

https://github.com/Azure/azure-functions-durable-extension/blob/821b862f534684d8ffab5e58cddeb94b563e6c9b/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L65

### App Details
PackageReferences
```
<ItemGroup>
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.2" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
</ItemGroup>
```

**Comment by ConnorMcMahon** [comment]
@JackSkylark,

Thanks for bringing this to our attention.

It looks like we are failing to check for the IsExternalClient field of the client before making this check, hence the null reference exception.

You may be able to get around this until 2.4.1 releases with a fix by configuring your `IOptions<DurableTaskOptions>` to have a different taskhub name than your `DurableClientOptions` (either the default options configured in `AddDurableTaskFactory` or the one provided in `IDurableClientFactory.CreateClient(DurableTaskOptions options)`). This should cause the conditional `this.ClientReferencesCurrentApp(durableClient)` to return false and avoid the null reference causing line entirely.

I would try adding something like this to your Startup.cs

```csharp
serviceCollection.Configure<DurableTaskOptions>(() => new DurableTaskOptions() {
    HubName = "dummyHubName",
});
```

**Comment by JackSkylark** [comment]
Changing the HubName doesn't help me in my situation because I am targeting entities that exist locally to the my function app.

For context, I'm using MassTransit and routing functions to consumers that won't have access to a durable client created via a binding. I'm looking into alternate workarounds now. I'll post back here if I find any.

**Comment by ConnorMcMahon** [comment]
Thanks for the clarification @JackSkylark.

In that case, the easiest solution would be to use the traditional `DurableClientAttribute` input binding to get your client. `IDurableClientFactory` was definitely more designed for client applications, hence why the `DurableClient` objects have `IsExternalClient` set to `true`. 

I think there are definitely uses for wanting an `IDurableClientFactory` that generates clients in the same way that we do for input bindings so people can make use of dependency injection more seamlessly. This will probably need to be revisited in our next minor release.

In general, I've been noticing a lot of confusion around clients and how to use them due to the number of options we provide, so I think our team needs to put together some more clear guidance on best practices, and cover any gaps in our scenarios.
