### ISSUE TITLE
[Question] How to notification activity function processing status to frontend

### ISSUE THREAD

**Issue by komayama** [Azure/azure-functions-durable-extension#1627]
I tried to create the `OrchestrationTrigger` and `ActivityTrigger` of Durable Functions the following documentat to visualize which functions processing. I understand that `OrchestrationTrigger` management processing status using by SetCustomStatus() method.But this mehod only use by  `OrchestrationTrigger` . When set SetCustomStatus() method from OrchestrationTrigger, ActiivityTrigger only notification Start and Complete for running function. 

While processing `ActivityTrigger` function, How do I get processing activity trigger status and return to the Frontend?
 (Frontend is another Azure Function App)

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-custom-orchestration-status?tabs=csharp#visualize-progress

```
context.SetCustomStatus("Tokyo");
```

**Comment by olitomlinson** [comment]
@komayama 

The `customStatus` is a great way to align completion of activities to an overall status.

```c#

await context.CallActivityAsync("Task1");
context.SetCustomStatus("20%");
await context.CallActivityAsync("Task2");
context.SetCustomStatus("40%");
await context.CallActivityAsync("Task3");
context.SetCustomStatus("60%");
await context.CallActivityAsync("Task4");
context.SetCustomStatus("80%");
await context.CallActivityAsync("Task5");
context.SetCustomStatus("100%");
```

You can then easily call the HTTP API from the server-side component of your Front End App to retrieve the `customStatus` of your orchestration

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-instance-status

Alternatively, if you are using ASP.NET for your front-end app, you can inject `DurableClient` into your controllers and use that. Explained here : https://github.com/Azure/azure-functions-durable-extension/issues/1616#issuecomment-748529560

**Comment by ConnorMcMahon** [comment]
It sounds like you want to get the status of an activity trigger intermittently? 

Unfortunately, activities don't have the ability to persist state mid execution, so we have no equivalent to `SetCustomStatus` like we do for orchestrations. If you really want status updates about progress on an activity, I would break that activity into multiple activities and set intermediate orchestration statuses like @olitomlinson mentioned above.

Another potential option is to have your frontend expose an endpoint that activity triggers can call when they hit various processing milestones. This would move your design from having your frontend poll for progress, to having your activity push progress notifications to the endpoint.

I would still recommend @olitomlinson's approach, as if subtasks in an activity are important enough to communicate back to your frontend, then they are probably worth being checkpointed by your orchestration in the case that your app crashes mid activity execution.

**Comment by komayama** [comment]
@olitomlinson @ConnorMcMahon 
Thank you for explaining me more detail information.
