### ISSUE TITLE
Orchestration instances stuck in pending status for too long

### ISSUE THREAD

**Issue by kedzior-io** [Azure/azure-functions-durable-extension#1628]
### Description
From time to time we get **some** durable tasks stuck for more than 20-30 minutes in pending state. No errors logged.
The function completes orders by updating records in SQL Server and sending notifications (normal execution time is about 1-2 seconds). 

Also when they finally process (we see execution completion in logs), storage table `DurableFunctionsHubInstances` keeps showing `Pending` state for the instance 20-30 minutes after but it finally gets updated.

### Expected behavior
> Executing durable tasks immediately 

### Actual behavior
> **Sometimes** durable tasks stuck for more than 20-30 minutes

### Relevant source code snippets

Code is copy paste from MS Docs: 

```csharp
        [FunctionName(nameof(CompleteOrderTriggerStart))]
        public static async Task CompleteOrderTriggerStart(
            [ServiceBusTrigger(ServiceBusQueue.CompletedOrders, Connection = "ServiceBusConnection")] string message,
            [OrchestrationClient] DurableOrchestrationClient starter,
            [Inject] ILogger logger)
        {
            try
            {
                var input = JsonConvert.DeserializeObject<CompleteOrderInput>(message);
                var instanceId = await starter.StartNewAsync(nameof(CompleteOrderRunOrchestrator), input).ConfigureAwait(false);
                logger.Information("<CompleteOrder> Started orchestration for {@Input} with {InstanceId}", input, instanceId);
            }
            catch (Exception ex)
            {
                logger.Error(ex, "An error occurred trying to started orchestration");
                throw;
            }
        }


        [FunctionName(nameof(CompleteOrderRunOrchestrator))]
        public static async Task CompleteOrderRunOrchestrator(
            [OrchestrationTrigger] DurableOrchestrationContext orchastrationContext,
            [Inject] ILogger logger)
        {
            try
            {
                var input = orchastrationContext.GetInput<CompleteOrderInput>();
                logger.Information("<CompleteOrder> Running orchestration for {@Input}", input);

                if (!orchastrationContext.IsReplaying)
                {
                    logger.Warning("<CompleteOrder> Calling CompleteOrderRunActivity for {@Input}", input);
                }

                await orchastrationContext.CallActivityAsync(nameof(CompleteOrderRunActivity), input);

                if (!orchastrationContext.IsReplaying)
                {
                    logger.Warning("<CompleteOrder> Calling CompleteOrderSendNotifications for {@Input}", input);
                }

                await orchastrationContext.CallActivityAsync(nameof(CompleteOrderSendNotifications), input.OrderId);

                Thread.Sleep(TimeSpan.FromSeconds(1));
            }
            catch (Exception ex)
            {
                logger.Error(ex, "An error occurred trying to run orchestrator");
                throw;
            }
        }
```

### Known workarounds
> Built a function that keeps an eye on instances in pending state. See details below.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 1.8.6 (can't update due to dependencies on .NET FF)
- **Azure Functions runtime version (1.0 or 2.0)**: 1.0
- **Microsoft.NET.Sdk.Functions**: 1.0.24
- **Programming language used**: C#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Azure region**: EastUS
- **Orchestration instance ID(s)**:  

3c0d9b3f617d45d39c606e6c355938ca | 04/01/2021 11:53
643b5b97c2244f07af1eddc59a709022 | 04/01/2021 11:45
7941cfc304744070b979626da8f0b22b | 04/01/2021 12:03
807e02e9b7a24d07899db585cf4b4b31 | 04/01/2021 11:49
87583d3b508940a39525ecf72ec048d6 | 04/01/2021 11:49
c3349d7450bb4989aaefa326f508d089 | 04/01/2021 11:50
c7d7b9b97e4248b0a9104d4f016f1981 | 04/01/2021 11:39

34d73a636bcc4691b8bf7c5974b571e2 - delayed pending status update.

Additional info: 
I built a separate function to monitor instances in pending state and send us Slack message but no matter what the result always returns an empty list. (I ran this during the 20 minutes when durable tasks tried to complete)

```csharp
    [ServiceBusAccount("AzureWebJobsServiceBus")]
    public static class OrderCompleteMonitor
    {
        [FunctionName(nameof(OrderCompleteMonitor))]
        public static async Task RunAsync(
            [TimerTrigger("0 */1 * * * *")] TimerInfo timer,
            [DurableClient] IDurableOrchestrationClient client,
            [ServiceBus("outbound-slack")] IAsyncCollector<string> serviceBusCollector,
            ILogger log, CancellationToken cancellationToken)
        {
            var queryFilter = new OrchestrationStatusQueryCondition
            {
                RuntimeStatus = new[]
                {
                    OrchestrationRuntimeStatus.Pending
                },
                ShowInput = true,
                PageSize = 100
            };

            var result = await client.ListInstancesAsync(queryFilter, cancellationToken);

            log.LogInformation("<{FunctionName}> Found {PendingOrderCount} pending orders", nameof(OrderCompleteMonitor), result.DurableOrchestrationState.Count());

            foreach (var instance in result.DurableOrchestrationState) 
            {
                var text = $":tired_face: A pending order completion instance has been detected: [{instance.CreatedTime}] {instance.Name} - {instance.InstanceId} - {instance.Input} <!here>";
                await SendSlack(serviceBusCollector, text, cancellationToken);
            }
        }
    }
```

Details of above function: 
- **Microsoft.Azure.WebJobs.Extensions.DurableTask**: 2.4.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Microsoft.NET.Sdk.Functions** 3.0.11
- **Programming language used**: C#

**Comment by kedzior-io** [comment]
Thanks! @cgillum . Will check it tomorrow and will post the results. 
Also, any idea why my `OrderCompleteMonitor` returns 0 results while querying pending tasks?

**Comment by cgillum** [comment]
@kedzior-io I'm not sure why your query would always return 0 results. Seems like it should just work. Would you mind opening a new issue to track that separately from this issue?

**Comment by kedzior-io** [comment]
> Hi @kedzior-io, thanks for these details. I checked our internal telemetry and it looks like you have two different function apps reading from the same task hub and storage account.
> 
> * b******-functions-full-framework
> * b******-functions-net-standard
> 
> This is an easy mistake to make when using v1.x of the Durable extension and can be very tricky to diagnose. You would have only noticed it if you happened to look for warnings in the _functions-net-standard_ app (it's complaining that it can't find an orchestration named "CompleteOrderRunOrchestrator").
> 
> What's happening is that both apps are competing for the same queue messages, but only one of them knows how to correctly process those messages. After about 20-30 minutes, the correct app finally receives the message and your orchestrators start running.
> 
> You can resolve this issue by ensuring that your two function apps are configured with either different storage accounts or different task hub names. More information here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs. In v1.x of the extension, if you don't specify a task hub name in **host.json**, we default to "DurableFunctionsHub". This is why two apps using the same storage account can easily run into task hub conflicts. Starting in v2.x, we changed our default task hub name to be the name of your app to make it harder to run into this kind of conflict. However, I realize that you're currently stuck on v1.x so you'll need to use the workaround I described previously.
> 
> Let us know if this resolves your issue.

FYI: we had it running for few days on different hub name and issue seems to be solved. 
One thing I'm not clear about or maybe not understanding is the part of documentation stating this: 

![image](https://user-images.githubusercontent.com/40808369/104284084-c0788300-54b1-11eb-8ebe-fb70b1df3c4b.png)



This is exactly our case, one function app on 1.x and another 2.x so in theory when deployed they should be using different task hubs names by default? So why the need for explicit config?
