### ISSUE TITLE
Allow function apps to be used exclusively as a client

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1629]
**Is your feature request related to a problem? Please describe.**
It is a common ask for customers to have a separate function application for their durable client functions and for their actual Durable Functions (activities, orchestrations, entities). However, the very act of installing the Durable Functions extension will cause us to spin up a TaskHubWorker for the specified (or default) storage account and task hub name.

In the worst case, where the customer specifies the same task hub name and storage account in their client app and server app, their client app will try to process orchestration, entity, and activity functions that it may not have access to. Even in the best case, where the customer uses a separate/dummy storage account or task hub name, we are creating unnecessary storage resources and doing lease management operations.

**Describe the solution you'd like**
An optional field on the host.json that will allow customers to use the app exclusively as a client, so that we don't spin up a TaskHubWorker and do unintentional work on the storage account.

There may also need to be additional work on the sync triggers functionality in the Azure Functions host and the Scale Controller to ensure that we don't scale this function app when the task hub is seeing activity.

**Current workaround**
An application can use an alternative storage account and/or taskhub name, and then reference the "server" app's taskhub + storage account name in their Durable Client binding and/or durable client API calls.

**Comment by cgillum** [comment]
The design of the durable extension is supposed to only spin up a task hub worker if a durable trigger is present ([reference](https://github.com/Azure/azure-functions-durable-extension/blob/faa0ccd9e5a6596365e8109c2ce6c4745e19c67d/src/WebJobs.Extensions.DurableTask/Listener/DurableTaskListener.cs#L65-L68)). What you're describing doesn't match this, so I'm curious to understand how this problem is occurring.

**Comment by ConnorMcMahon** [comment]
Wow, I can't believe I missed that. In that case, this issue is likely not necessary.

There is still the case where we have customers pointing their client app at the same task hub + storage account as the server app, and us failing to schedule orchestrations/entities due to our checks that the function exists in their app. That is a slightly different issue, but I think it's worth revisiting that check to see if it is causing more harm than good.
