### ISSUE TITLE
Azure Functions Control Queue Message Dequeue Count Increase over Time

### ISSUE THREAD

**Issue by OTedikov** [Azure/azure-functions-durable-extension#1630]
Azure Functions v3, C#, Runtime Version 3.0.15193

We are using Azure Durable Functions in the following way:
Orchestrator Function
Activity Functions (5-20) 
Activity Functions are executed in a specific order, according to Pattern 1: Function chaining
Control Queues Count: 8
Control Queue Visibility Timeout: default 5 minutes
Number of Orchestrator Function Executions: ~100 per minute
Elastic Premium Plan Run Duration: 30 minutes 
Typical Activity: Upload / Download from / to Blob, Read / Write from / to Database, Call External Api, ..., with duration 5 - 60 seconds under normal conditions, less often 1 - 10 minutes.

For the recent week we noticed that some of Control Queues started having number of Messages increased over time up to 5000 - 15000 each, while other Control Queues were either empty or with ~100-200 messages. Also each Control Queue messages Dequeue Count also started increasing each 5 minute and messages started returning back to Control Queue.
Having that more and more Orchestrator Functions started not being able to finish properly executing all Activities Functions and were "stuck" with having Activity messages returning back to Control Queue after 5 minutes and executing further again and again.

Also from our observations we started receiving larger input for Orchestrator Function, ~75-90 MB as file reference in Azure Storage Blob, while normally we have ~ 5-100 KB and very rare 20-30 MB, which means each Activity execution could take longer than usual.

Also what helped us to mitigate this issue is constant Redeployments and in the end clearing Control Queues with only messages with Dequeue Count greater than 0.

What could cause such behavior and why Control Queue message are not renewed if Activity could be still executing?
And what in general could cause Control Queue message return back to Queue if Activity is not finished?

What we also noticed is that we had OutOfMemory Exceptions, due to 
```
Exception:
Exception of type 'System.OutOfMemoryException' was thrown.
Exception:
Error while handling parameter $return after function returned:
Exception:
The activity function '...ActivityFunction' failed: "Error while handling parameter $return after function returned:". See the function execution logs for additional details.
at System.Text.StringBuilder.ToString()
   at DurableTask.Core.Serializing.JsonDataConverter.Serialize(Object value, Boolean formatted) in C:\source\durabletask\src\DurableTask.Core\Serializing\JsonDataConverter.cs:line 77
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.MessagePayloadDataConverter.Serialize(Object value, Int32 maxSizeInKB) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\MessagePayloadDataConverter.cs:line 45
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.MessagePayloadDataConverter.Serialize(Object value) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\MessagePayloadDataConverter.cs:line 33
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableActivityContext.SetOutput(Object output) in d:\a\r1\a\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableActivityContext.cs:line 142
```

At which size the response could start not being deserialized properly and could cause such OutOfMemory exception?

Thank you

**Comment by cgillum** [comment]
Hi @OTedikov, thanks for these details. There may be some confusion with terminology, so let me try to clarify that problem you're seeing.

> Having that more and more Orchestrator Functions started not being able to finish properly executing all Activities Functions and were "stuck" with having Activity messages returning back to Control Queue after 5 minutes and executing further again and again.

Activity functions are triggered by messages in the **work-item** queue. The **control queues**, however, are used to trigger orchestrations to run. Control queues contain orchestration start, external event, activity response messages, etc. I wanted to clarify this to make sure we're investigating the correct thing. Based on the error call stack you reported, I would expect the dequeue count to be continuously increasing for messages it the **work-item** queue.

> What could cause such behavior and why Control Queue message are not renewed if Activity could be still executing?

As I mentioned, activity functions are triggered by the work-item queue. If an activity function is still running, these messages will be renewed automatically every 30 seconds. I don't think message renewal is related to your problem, however.

> And what in general could cause Control Queue message return back to Queue if Activity is not finished?

Again, I'll assume we're talking about the work-item queue. A message could be returned to this queue with an increased dequeue count of there is a major failure. For example, if the underlying VM were to fail or if the Functions host crashed, this would be expected. In your case, I think the OutOfMemoryException is resulting in this same problem. Your app may not be configured with enough memory to serialize the activity function output and this is causing a repeated failure to complete the activity function.

> At which size the response could start not being deserialized properly and could cause such OutOfMemory exception?

This depends on what Azure Functions hosting plan you are using. For example, the Azure Functions Consumption plan has a limit of 1.5 GB per app instance. Exceeding this could cause out-of-memory failures and could also cause the app instance to recycle, interrupting any functions that are currently executing. You can increase your memory limit by using a different hosting plan, such as Elastic Premium or by using an App Service plan with higher memory limits.  More information can be found in the Azure Functions documentation: https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#service-limits

Let us know if you have additional questions.

**Comment by OTedikov** [comment]
@cgillum Thank you for explanation. Will add few clarifications and ask questions.

I messed up **control** and **work-item** queue intention and type of work each one is responsible for while describing the issue, but actual number of messages I've noticed for the recent work is correct.

So we have 8 **control** queues and 3 of them had ~5000 - 15000 messages, while other 5 had only ~100 - 200 messages at a time, and number of messages per **control** queue was growing over time, but only rather for 3 ones, which had the large number of messages.
And dequeue count I've noticed continuously increasing is for **control** queues, more specifically for messages within those 3 **control** queues with large number of messages.

There were no issues with work-item queue, there were no more then 30-50 messages at a time and no messages with dequeue count more than 0.

So will rephrase question:
- What in general could cause control queue message return back to queue in 5 minutes?
- Should we in general increase visibility timeout for control queue and in which cases it is applicant?

According to our practical experience we noticed that Azure Functions tend to fail and start having out of memory exceptions while working with large request and response (> 10 MB), although Azure Functions Runtime should more or less do the same using **-largemessages** blob container, we introduced own mechanism to write large response to Azure Storage Blob and read from Azure Storage Blob for large request to mitigate issues with handling large files.

We investigated and found that we did not handle some cases while working with large files, so it seems this issue is back and started again causing OutOfMemory exceptions, when Activity Request and Response are rather large, > 10 MB and not us, but Azure Runtime is responsible for serialization and deserialization.

Regarding hosting plan, we are using Elastic Premium P1 / P2.

Thank you

**Comment by cgillum** [comment]
@OTedikov thanks for the update. Let me try to answer your questions:

> What in general could cause control queue message return back to queue in 5 minutes?

Internal failures in the Functions runtime or Durable extension (like OOM or [de]serialization issues), or process crashes/recycles/hangs can cause control queue messages to back to the queue in 5 minutes. This is also possible if an orchestrator function replay runs for longer than 5 minutes, but this should never happen since orchestrator functions should never be doing I/O or blocking.

> Should we in general increase visibility timeout for control queue and in which cases it is applicant?

Orchestrator functions almost always execute very quickly since they never do I/O or blocking (if they are implemented correctly). For this reason, you should never need to increase the lock duration for orchestrator functions.

If you can share more information about the orchestrator functions that are having issues, we can use our service telemetry to help you investigate. Specifically, we would need to know the region of your app, an approximate time range, and the instance ID of an orchestration that is running into trouble. You can find the orchestration instance ID in any of the messages. Alternatively, if you can tell me the name of your function app or the name of the storage account, then I can probably find the information I need.

**Comment by OTedikov** [comment]
@cgillum Thank you for clarifications.

**Application Region:** UK South
**Time Range:** 25 December 2020 12:00 AM - 26 December 2020 12:00 AM
**Instance IDs:** 8d9681ef-b0d2-40a7-b2a0-ddb9df36f62f, e005b19e-c80c-4c52-889c-dce9d5a695b2, 752239c4-3da5-4b77-9a09-f0859667516c, 002797ce-f245-42e4-a2e1-b62b973f126a

**Comment by Shishkovskiy** [comment]
@cgillum  Do u have any updates related to that issue?

**Comment by OTedikov** [comment]
@cgillum Did you have a change to take a look?

**Comment by ConnorMcMahon** [comment]
Sorry for not following up on this issue. @OTedikov, we only have the past 60 days of telemetry, would you be able to share a more recent TIMESTAMP + Instance ID(s)?

**Comment by OTedikov** [comment]
@ConnorMcMahon As of now this is rather will be hard to reproduce, since quite a lot has changed since this time.
Please take a look at this issue https://github.com/Azure/azure-functions-durable-extension/issues/1896, which is relevant as of now.

Thank you
