### ISSUE TITLE
Cannot Create a DurableClient using DurableClientFactory from MsTest project

### ISSUE THREAD

**Issue by mreyeros** [Azure/azure-functions-durable-extension#1640]
I have an MSTest project that runs through functional tests for our solution.  These tests include calls out to our main API as well as to our FunctionApp hosting our Durable Functions/Orchestration.  As part of these tests we are adding some test "cleanup" logic to purge cosmos/storage records created as part of our teardown logic.  I have attempted to follow the sample code [here ](https://github.com/Azure/azure-functions-durable-extension/tree/dev/samples/todolist-aspnetcore) for obtaining a DurableClient outside of the context of a function app with little luck.  When my code attempts to create a durable client via the DI injected IDurableClientFactory, the call to CreateClient fails with the below exception.  I have attempted to load configuration via a Startup class that configures the DI ServiceProvider for the test project, but it appears that the configuration that is used by the DurableClientFactory may not be using the same configuration at runtime.

`System.InvalidOperationException: 'Unable to find an Azure Storage connection string to use for this binding.'`

**Expected behavior**
Expectation is that calling IDurableClientFactory.CreateClient would create a durableClient that could then be used for calling PurgeInstanceHistory

**Actual behavior**
System.InvalidOperationException is thrown while attempting to obtain the connection string from configuration.

### Relevant source code snippets
```    
public class Startup
    {
        public static ServiceProvider ServiceProvider { get; private set; }

        public void ConfigureServices(IDictionary contextProperties)
        {
            var services = new ServiceCollection();

            services.AddOptions();

            var configuration = new ConfigurationBuilder()
                .AddInMemoryCollection(ToKeyPairs(contextProperties))
                .AddEnvironmentVariables()
                .AddJsonFile("appsettings.json")
                .Build();

            services.AddSingleton<ILoggerFactory>(_ => new LoggerFactory());
            services.AddSingleton(configuration);
            
            services.Configure<DurableClientOptions>(options =>
            {
                options.ConnectionName = "AzureWebJobsStorage";
                options.TaskHub = configuration["TaskHubName"];
                options.IsExternalClient = true;
            });

services.AddDurableClientFactory();
...
}
}
```
App Details

- **Durable Functions extension version (2.4.0)**:
- **Azure Functions runtime version (2.0)**:
- **Programming language used: C#**:

Screenshots
![image](https://user-images.githubusercontent.com/964690/104236956-51ede380-5425-11eb-85a9-38a589061838.png)

**Comment by cgillum** [comment]
@bachuv this might be a good one for you to take a look at.

**Comment by bachuv** [comment]
Hi @mreyeros, I've looked into the issue you're having and it seems like the storage connection string value from `appsettings.json` can't be resolved. Can you share the contents of your `appsettings.json` file (removing any sensitive information)? Thank you!

**Comment by stevie1706** [comment]
I am experiencing the same issue @bachuv.
What I am trying to achieve is to use a custom connection string name and taskhub name.

So I want the DurableClientFactory.CreateClient() method to honor both of these values.

I have tried to configure this in startup as follows:

`services.AddDurableClientFactory((config)=> {
                config.ConnectionName = "MyCustomConnectionStringName";
                config.TaskHub = "MyTaskHubName";
            });`

In this scenario the taskhub name is honoured but the connection is not.  I created my own implementation of IConnectionStringResolver and was able to see the ConnectionStringName which was passed to this service was named "Storage".

After a little digging through the source code I tried the following:

`            services.Configure<DurableTaskOptions>(config => {
                config.StorageProvider.Add("ConnectionStringName", "MyCustomConnectionStringName");
            });`

After doing this the connection string is now honoured but is requiring a TaskHub name to be configured.  

I cannot no matter what I try get both of the values to be configured with my custom values.  

I have even tried passing values directly to the CreateClient method on the DurableClientFactory class:
`            _durableClientOptions = new DurableClientOptions
            {
                ConnectionName = "MyCustomConnectionStringName",
                TaskHub = "MyTaskHubName"
            };

            var durableClient = _durableClientFactory.CreateClient(_durableClientOptions);
`

In this case again the ConnectionName is ignored and replaced with "Storage".

Thanks in advance for any help that can be provided.

**Comment by stevie1706** [comment]
After pulling down the source code and debugging through it appears that this function in AzureStorageDurabilityProviderFactory.cs

`        public virtual DurabilityProvider GetDurabilityProvider()
        {
            this.EnsureInitialized();
            if (this.defaultStorageProvider == null)
            {
                var defaultService = new AzureStorageOrchestrationService(this.defaultSettings);
                this.defaultStorageProvider = new AzureStorageDurabilityProvider(
                    defaultService,
                    this.defaultConnectionName,
                    this.azureStorageOptions);
            }

            return this.defaultStorageProvider;
        }`

invokes this.EnsureInitialized();

which in turn invokes the following method in the same class.
`                this.defaultSettings = this.GetAzureStorageOrchestrationServiceSettings();`

As you can see the method takes in no parameters and the method itself is described as follows:

`        internal AzureStorageOrchestrationServiceSettings GetAzureStorageOrchestrationServiceSettings(
            string connectionName = null,
            string taskHubNameOverride = null)
        {
            connectionName = connectionName ?? this.defaultConnectionName;

            string resolvedStorageConnectionString = this.connectionStringResolver.Resolve(connectionName);

            if (string.IsNullOrEmpty(resolvedStorageConnectionString))
            {
                throw new InvalidOperationException("Unable to find an Azure Storage connection string to use for this binding.");
            }
......`

As you can see this will always throw an error if there is no default connection string name "Storage" which is the value set in this.defaultConnectionName.

In addition when consuming this service via non web job (standard aspnet application) the extention method defaults to using the implementation of IConnectionStringResolver as StandardConnectionStringResolver.

After looking the source code it appears that the standard implementation would be better suited using WebJobConnectionStringResolver as this will locate connection string via both local.settings.json:Values:ConnString in webjob and appsettings.json:ConnectionStrings:ConnString in standard ASP.NET application and therefore feels like the naming convention of these implementations are reversed.

**Comment by stevie1706** [comment]
Created new ticket as not sure if it is directory related..

https://github.com/Azure/azure-functions-durable-extension/issues/1656

**Comment by bachuv** [comment]
@stevie1706, thank you for creating a new GitHub issue! I will look at it and follow up in that thread.

**Comment by twiga2013** [comment]
Hi,

I have ran into the same issue. What was the solution? Thanks

**Comment by robvangeloven** [comment]
@bachuv   the bug is still there unfortunately. In AzureStorageDurabilityProviderFactory.cs line 108 we have this function:
```csharp
// This method should not be called before the app settings are resolved into the options.
        // Because of this, we wait to validate the options until right before building a durability provider, rather
        // than in the Factory constructor.
        private void EnsureDefaultClientSettingsInitialized()
        {
            if (!this.hasValidatedOptions)
            {
                if (!this.options.IsDefaultHubName())
                {
                    this.azureStorageOptions.ValidateHubName(this.options.HubName);
                }
                else if (!this.azureStorageOptions.IsSanitizedHubName(this.options.HubName, out string sanitizedHubName))
                {
                    this.options.SetDefaultHubName(sanitizedHubName);
                }

                this.defaultSettings = this.GetAzureStorageOrchestrationServiceSettings();
                this.hasValidatedOptions = true;
            }
        }
```
here GetAzureStorageOrchestrationServiceSettings is called without parameters and defaults to null, which defaults to "Storage"
