### ISSUE TITLE
Reliability: Improve concurrency defaults for Consumption plan hosting

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#1646]
Some of the default concurrency settings do not work well for the Consumption plan. In particular, it's very easy to exceed TCP connection limits on Windows due to large numbers of concurrent Azure Storage queue operations. See [this customer support incident](https://portal.microsofticm.com/imp/v3/incidents/details/221648212/home) (requires MSFT credentials) as a reference.

My specific recommendation:
* Reduce the default value of `controlQueueBufferThreshold` from 256 to **32**. This ensures we don't do too many concurrent delete operations at once.
* Reduce the default value of `maxConcurrentOrchestratorFunctions` to **5**. This ensures fan-out operations do not create too many concurrent network connections.
* Reduce the default value of `MaxStorageOperationConcurrency` to **25**. It's currently derived from the CPU count, which is misleading in the Consumption plan. This setting may not be exposed to developers, but it probably should be.

The current defaults are fine for non-Consumption plans. These recommendations are specifically for Consumption because of tighter network resource restrictions. The extension code therefore needs to be aware of what the current plan is before making these settings changes (I assume this is possible at runtime, but not 100% sure).

**Comment by sebastianburckhardt** [comment]
I tried to find more information on how Azure Storage SDKs support connection pooling; as connection pooling is the most logical solution to avoid exceeding the TCP connection limits.

Apparently it depends: https://devblogs.microsoft.com/azure-sdk/net-framework-connection-pool-limits/

If I read this correctly:
- on .NET framework, there is a globally shared connection pool with a rather low default limit.
- on .NET core there is a connection pool per HttpClient. 

In that situation it seems that one would easily end up with not enough connections on .NET framework / with too many connections on .NET core. So most likely we would want to
- increase the connection pool size of the shared connection pool on .NET framework
- use a shared HttpClient for all Azure Storage connections on .NET core, with a reasonably large connection pool

**Comment by cgillum** [comment]
Having a small number of TCP connections is not necessarily an issue. The problem is when the storage SDK creates _too many_ TCP connections. The Azure App Service sandbox on Windows VMs will fail outbound TCP connections beyond 600 and the Functions host will recycle the process if this is detected, resulting in mid-execution failures and potential duplicate work after recovering. The suggested fix is to reduce storage SDK concurrency in our own code to ensure the Storage SDK doesn't try to create this many connections in its connection pool.

As an alternative to reducing these default configuration values, we could instead refactoring our existing `MaxStorageOperationConcurrency` implementation to be global for all operations in the process. Currently it only works for a single instance, which is why it's not particularly effective.

**Comment by ConnorMcMahon** [comment]
Do we want this issue to cover the out-of-proc concurrency defaults as well, or should that be tracked as a separate issue?

**Comment by cgillum** [comment]
@ConnorMcMahon I would track out-of-proc defaults separately. The spirit behind this issue is about not opening up too many TCP connections. We can probably update the title to reflect this.

**Comment by davidmrdavid** [comment]
Created a kind of _draft_ issue to track the OOProc ticket here: https://github.com/Azure/azure-functions-durable-extension/issues/1700

If don't have enough context to fully describe that work item so I would appreciate if one of y'all could help provide more context about that that work item entails in the ticket itself. _Thanks!_
