### ISSUE TITLE
Python Durable Function,maxConcurrentActivityFunctions ,instance scaling,temp folder

### ISSUE THREAD

**Issue by maccoy** [Azure/azure-functions-durable-extension#1649]
We are trying to Port one of our application to Durable Function using Fan out Pattern to gain performance benefits.
When we process an 4 files, We expect it to spawn 4 instance (F2 is implemented to process the fies).
But we observed this is not happening by default, if we force it using ‘maxConcurrentActivityFunctions": 1’
then F2 function is not able to find the files written in the temp folder(which was written by another activity function(F1) before calling F2)
is it because F1 and F2 are running in 2 different instances and do not have access to each others temp folder?
Is there any setting or we have to write the files to blob in F1 and read from blob in F2?

**Comment by maccoy** [comment]
@cgillum I saw in the video in https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp, when refering to Fan out pattern you have shown a sample which is very similar to what we are trying to do.
But we face some issue.

**Comment by anthonychu** [comment]
@maccoy Yes the temp storage is per instance. Try storing your files into Blob storage from your activity functions using the Storage SDK or output bindings, or [mount a file share or a storage container](https://docs.microsoft.com/en-us/azure/azure-functions/scripts/functions-cli-mount-files-storage-linux) and write to it instead of the temp folder.

**Comment by maccoy** [comment]
@anthonychu , Thanks for the info. will look into it.
Is this instance have any relation with the 'Scale out' instance we configure for the Function App? or the Durable Function instance scale automatically. Meaning if  I set the Manual Instance of  my Function App at 5, will this limit the durable function to 5 or it can scale to 10 also?

**Comment by cgillum** [comment]
@maccoy Writing to a blob is probably the most performant option, so if it's working for you now then I would stick with it.

For more information on scaling, see this Azure Functions documentation. It also applies to Durable Functions: https://docs.microsoft.com/en-us/azure/azure-functions/event-driven-scaling. The term "instance" in the context of Anthony's response means a scaled-out instance of your function app. Whether and how it scales out depends on the hosting plan you chose. The documentation above should help clarify some of that.
