### ISSUE TITLE
Question: schema migration - durable entities

### ISSUE THREAD

**Issue by robinfehr** [Azure/azure-functions-durable-extension#1650]
Hi, 

I'm trying to wrap my head around the docs but don't yet understand how to approach schema migrations when we introduce a breaking change. For example, when having a state in v1 of an entity, we introduce a breaking change and need to deploy a v2 of it. How could we then migrate the state from the schema of v1 to the schema of v2? In a streaming world (event sourced with an event log), we would replay all recorded events over time and letting v2 rebuild the state with a new schema from scratch. What is the correct way to deal with that by design currently?

Thank you.

**Comment by olitomlinson** [comment]
@robinfehr 

I would do this by putting all the migration logic in a method on the entity, and call this migration method at the start of every one of the existing entity interface methods.

The migration method would first check a new `version` property (don’t forget to include this in the entity state) that is introduced in the new entity code. 

If the version property is null, this entity hasn’t been upgrade yet, so run the necessary migration logic and set the `version` to something significant. I.e `1`

You can then use the `version` property throughout your entity code to branch your logic where necessary if it can’t be upgraded.

Depending on your scenario, you may have entities that don’t get activated frequently and therefor don’t get migrated. It’s worth considering how long you are okay for old code to clutter the entity, waiting for all migrations to happen. It might be worth developing a way to activate any dormant entities with some kind of `noop` method which can be called purely to get the migration code to run. 

Or even better, delete the entity completely if it is truly obsolete, but that’s entirely down to you to evaluate the suitability of that option.

It’s also worth considering that if you rollback your breaking change code for whatever reason, you will loose any new serialised data for newly introduced  properties. So it’s worth considering a roll-forward plan if data loss is unacceptable.

**Comment by mpaul31** [comment]
i just ran into something similar recently but the problem we encountered was the migration also had to change how we identify our entities (EntityId). The way we are going to solve this problem is by creating an ingestion service that appends the external messages to an immutable log (document store). 

I am most likely going to make this part of the "cold" path that would allow replays to rebuild our entities as opposed to a more "hot" path where we would tail the log and signal our entities to avoid the additional latency and complexity / overhead.

**Comment by cgillum** [comment]
Thanks @olitomlinson and @mpaul31 for your suggestions! I think these are smart strategies. I'll go ahead and close this issue since the main question was answered with a concrete recommendation. However, others can feel free to add on.

FYI @sebastianburckhardt since this is an interesting topic.
