### ISSUE TITLE
DurableClientOptions not honoured if using custom connection string name in aspnet core app when using AddDurableClientFactory extention method

### ISSUE THREAD

**Issue by stevie1706** [Azure/azure-functions-durable-extension#1656]
What I am trying to achieve is to use a custom connection string name and taskhub name.

So I want the DurableClientFactory.CreateClient() method to honor both of these values.

I have tried to configure this in startup as follows:

`services.AddDurableClientFactory((config)=> {
                config.ConnectionName = "MyCustomConnectionStringName";
                config.TaskHub = "MyTaskHubName";
            });`

In this scenario the taskhub name is honoured but the connection is not.  I created my own implementation of IConnectionStringResolver and was able to see the ConnectionStringName which was passed to this service was named "Storage".

After a little digging through the source code I tried the following:

`            services.Configure<DurableTaskOptions>(config => {
                config.StorageProvider.Add("ConnectionStringName", "MyCustomConnectionStringName");
            });`

After doing this the connection string is now honoured but is requiring a TaskHub name to be configured.  

I cannot no matter what I try get both of the values to be configured with my custom values.  

I have even tried passing values directly to the CreateClient method on the DurableClientFactory class:

`_durableClientOptions = new DurableClientOptions
  {
      ConnectionName = "MyCustomConnectionStringName",
      TaskHub = "MyTaskHubName"
  };
`
` var durableClient = _durableClientFactory.CreateClient(_durableClientOptions);`

In this case again the ConnectionName is ignored and replaced with "Storage".

----------------------------

After pulling down the source code and debugging through it appears that this function in AzureStorageDurabilityProviderFactory.cs

```
public virtual DurabilityProvider GetDurabilityProvider()
        {
            this.EnsureInitialized();
            if (this.defaultStorageProvider == null)
            {
                var defaultService = new AzureStorageOrchestrationService(this.defaultSettings);
                this.defaultStorageProvider = new AzureStorageDurabilityProvider(
                    defaultService,
                    this.defaultConnectionName,
                    this.azureStorageOptions);
            }
return this.defaultStorageProvider;
}
```

invokes `this.EnsureInitialized();`

which in turn invokes the following method in the same class.
`                this.defaultSettings = this.GetAzureStorageOrchestrationServiceSettings();`

As you can see the method takes in no parameters and the method itself is described as follows:

```       
internal AzureStorageOrchestrationServiceSettings GetAzureStorageOrchestrationServiceSettings(
            string connectionName = null,
            string taskHubNameOverride = null)
        {
            connectionName = connectionName ?? this.defaultConnectionName;

            string resolvedStorageConnectionString = this.connectionStringResolver.Resolve(connectionName);

            if (string.IsNullOrEmpty(resolvedStorageConnectionString))
            {
                throw new InvalidOperationException("Unable to find an Azure Storage connection string to use for this binding.");
            }
......
```

As you can see this will always throw an error if there is no default connection string name "Storage" which is the value set in this.defaultConnectionName.

In addition when consuming this service via non web job (standard aspnet application) the extention method defaults to using the implementation of IConnectionStringProvider as StandardConnectionStringProvider.

After looking the source code it appears that the standard implementation would be better suited using WebJobsConnectionStringProvider this will locate connection string via both local.settings.json:Values:ConnString in webjob and appsettings.json:ConnectionStrings:ConnString in standard ASP.NET application and therefore feels like the naming convention of these implementations are reversed.

**Comment by bachuv** [comment]
@stevie1706, thank you for opening this issue! I was able to reproduce the issue using custom connection string names with `DurableClientOptions`. I've added this issue to work on for the next release. I will also look into using `WebJobsConnectionStringProvider`.

**Comment by NickSevens** [comment]
+1
I assumed the "default" connectionStringName would be `AzureWebJobsStorage` and not just `Storage`. And indeed, I'm unable to change this using configuration in an asp.net core app.
Looking forward to the fix :)

**Comment by channeladam** [comment]
+1

**Comment by hanzwo-m4m** [comment]
There is a workaround:

It's looking for the Storage key in configuration to ensure initialisation. But after that it's checking you're given parameters. So if you add both keys to your configuration, it works.

`
  "Storage": "EmptyStorageConnection",
  "NotificationsStorageConnection": "AccountName=devstoreaccount1;xxxxxxxxxxxxxxxxx",
`

`var client = _clientFactory.CreateClient(new DurableClientOptions
 {
                TaskHub = "NotificationsHub",
                ConnectionName = "NotificationsStorageConnection"
 });`

**Comment by jriouxrandstadca** [comment]
+1

**Comment by michc-msft** [comment]
@hanzwo-m4m Using your workaround, do you just put anything into the `Storage` configuration value? Could it be an empty string as well?

I'm also curious if you could also set your connection string as the value to `Storage`? And then specify no `ConnectionName` in the `DurableClientOptions`.

**Comment by hanzwo-m4m** [comment]
> @hanzwo-m4m Using your workaround, do you just put anything into the `Storage` configuration value? Could it be an empty string as well?
> 
> I'm also curious if you could also set your connection string as the value to `Storage`? And then specify no `ConnectionName` in the `DurableClientOptions`.

Not empty, just a random string.
