### ISSUE TITLE
Ability to select alternate storage backend in host.json

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#1666]
Soon we will be ready to release new backends for Durable Functions: a Microsoft SQL Database backend and a Netherite backend. To make it easier for customers to opt-into these new backends, we want to include them in the default Azure Functions extension bundles. However, the backend extensibility design does not currently allow you to choose the backend you want using configuration. Rather, it relies on the user to selectively load the backend extension and this won't work well if we need to ship all backends together in the same extension bundle.

**Describe the solution you'd like**
We would like a way to select which Durable backend to use in host.json, with the default being the Azure Storage backend. For example, it could be as simple as a `type` field under `durableTask/storageProvider`:

```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "storageProvider": {
        "type": "MicrosoftSQL",
        "connectionStringName": "SQLDB_Connection"
      }
    }
  }
}
```

If a backend provider is registered with type "MicrosoftSQL", that provider will be loaded. If no provider is found with the specified name, then an exception is thrown. If no type is specified, the Azure Storage backend is used.

**Describe alternatives you've considered**
Alternatively we could require that alternate backends get deployed to separate bundles. However, this requires the bundles infrastructure and related tools to be updated to support alternate backends, which would be a time-consuming project.

**Comment by ConnorMcMahon** [comment]
Given the soft timeline of supporting bundles by May, we likely need to have this solution ready by April. That gives us one, maybe two releases to solidify this, but in the interest of time we should probably try to tackle this in the next release. Thoughts?

**Comment by sebastianburckhardt** [comment]
I like the "type" argument to switch backends, it is simple and reasonably flexible.

 I already have logic that reads the content of the "storageProvider" section to extract Netherite-specific settings, so I can provide this quickly.
