### ISSUE TITLE
Question: How best to handle "dead-lettering" failed orchestrations?

### ISSUE THREAD

**Issue by ma499** [Azure/azure-functions-durable-extension#1670]
**Is your feature request related to a problem? Please describe.**
We are starting to use Durable Functions in a message-driven system where our error handling and monitoring stratagies relies on dead-lettering of exceptions which require human intervention. When using durable functions we are unable to deadletter the trigger message as it was completed when the orchestrator was started - we recognise this is by design.

**Describe the solution you'd like**
An easy way (i.e. a method to invoke) for a developer to somehow get the message into the DLQ when encountering an error that cannot otherwise be handled.

**Describe alternatives you've considered**
We are investigating some techniques for doing this but would like to either extend this project, or build an add-on library, to abstract this problem for developers. We are happy to contribute a PR if we get some guidance, reassurance that it's likely to be accepted.

Ideas we're looking at:
1. Save a copy of the original message in orchestrator state. When required, post a copy of the message directly to DLQ on trigger subscription/queue.
1. Save a copy of the original message in orchestrator state. When required, schedule a copy of the original message with a custom header to indicate it failed. When the starter function resumes detect that it's a failed re-submission and dead-letter.
1. Save a copy of the original message in orchestrator state. When required, schedule a copy of the original message and update the custom state of the orchestrator to indicate it failed. When the starter function resumes detect that it's a failed re-submission and dead-letter.

We shall spike the above techniques but appreciate any feedback in the meantime.

**Additional context**
This was previous raised as a bug #560. The discussion includes a workaround which is similar to one of the ideas above.
Scheduling a copy of the message, and then dead-lettering is [one of the official workarounds proposed on Microsoft Support Q&A for this topic](https://docs.microsoft.com/en-us/answers/questions/39334/azure-durable-function-service-bus-trigger-peekloc.html).

**Comment by ConnorMcMahon** [comment]
I think that @olitomlinson nails this issue on the head. In general, the restart API should mitigate a lot of the pain of the logistics of restarting  an orchestration, as you no longer need to maintain your original message. At that point, you just need some way of knowing when your orchestration fails.

We currently provide two main ways to identify failed orchestrations:

1. Our orchestration management APIs (HTTP or the DurableClient objects in .NET/Javascript/Python).
2. Orchestration lifecycle events via [EventHub](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-event-publishing?tabs=csharp-script)

There are also some very helpful open source tools written by third parties, like [Durable Functions Monitor](https://github.com/scale-tone/DurableFunctionsMonitor).

@olitomlinson, I remember us having a discussion regarding better Azure Monitor integration a long time ago, but I can't seem to find what issue we had that discussion under. I think having an issue for that enhancement would be super helpful, as generally we decide on what new features to work on based on user engagement with the top level tickets.

**Comment by olitomlinson** [comment]
@ConnorMcMahon
 
Not quite the same, but this one comes to mind https://github.com/Azure/azure-functions-durable-extension/issues/1527#issuecomment-718249790

I think we need an Issue in general for first-class Azure Monitor integration with DF and then we can build a list of various telemetry series to emit.

**Comment by ma499** [comment]
Thank you for the suggestions @ConnorMcMahon @olitomlinson. We have taken on your points on board and are spiking the suggestions above to explore the possible solutions.
