### ISSUE TITLE
Orchestration Passing null on Replay

### ISSUE THREAD

**Issue by sejohnson-at-griffis** [Azure/azure-functions-durable-extension#1671]
### Description
When running an Action for the first time, everything runs as expected. When it replays, it feeds nulls into the constructor of one of my objects (but not another, which is going through a similar process and has the same inheritance!). Code details below.

### Expected behavior
Class constructor does not receive null on replay.

### Actual behavior
I have the following set of SQL requests being sent out by an Activity:
```csharp
            var marketingAmenitiesTask = context.CallActivityAsync<IList<MarketingAmenity>>(
                "GetMarketingAmenitiesFromSql", 
                "SELECT * FROM integration.manual_MarketingAmenities");
            var internalAmenitiesTask = context.CallActivityAsync<IList<InternalAmenity>>(
                "GetInternalAmenitiesFromSql",
                "SELECT * FROM integration.manual_InternalAmenities");
            var propertyUnitAmenitiesTask = context.CallActivityAsync<IList<PropertyUnitAmenities>>(
                "GetPropertyUnitAmenitiesFromSql",
                "EXEC dbo.sp_GetCurrentAmenitiesForAPI");
            await Task.WhenAll(marketingAmenitiesTask, internalAmenitiesTask, realPagePropertyUnitAmenitiesTask);

            log.LogInformation("Got all amenities successfully.");
            var marketingAmenities = marketingAmenitiesTask.Result;
            var internalAmenities = internalAmenitiesTask.Result;
            var propertyUnitAmenities = realPagePropertyUnitAmenitiesTask.Result;
```

On the other side, the implementation is very similar between these three functions (I'd write it as a generic, but Activity functions don't like that):
```csharp
        [FunctionName("GetInternalAmenitiesFromSql")]
        public static async Task<IList<InternalAmenity>> GetMarketingAmenitiesFromSql(
            [ActivityTrigger] IDurableActivityContext ctx)
        {
            var sqlCommand = ctx.GetInput<string>();
            var mapper = new InternalAmenityRowMapper();
            var records = await Utilities.GetRecordsFromSql(sqlCommand, mapper);
            return records;
        }
```

Where the implementation of GetRecordsFromSql looks like this:
```csharp
        public static async Task<IList<TRecord>> GetRecordsFromSql<TRecord>(string sqlCommand, ISqlRowMapper<TRecord> mapper)
        {
            var resultList = new List<TRecord>();
            using (var sqlConn = GetSqlConnection())
            {
                sqlConn.AccessToken = await GetSqlToken();
                await sqlConn.OpenAsync();
                using (var cmd = new SqlCommand(sqlCommand, sqlConn))
                {
                    using (SqlDataReader reader = await cmd.ExecuteReaderAsync())
                    {
                        while (await reader.ReadAsync())
                        {
                            TRecord entity = mapper.Map(reader);
                            resultList.Add(entity);
                        }
                    }
                }
            }
            return resultList;
        }
```

And the implementation of a mapper looks like this:
```csharp
    public class InternalAmenityRowMapper : ISqlRowMapper<MarketingAmenity>
    {
        public InternalAmenity Map(SqlDataReader sqlDataReader)
        {
            return new InternalAmenity(sqlDataReader.GetString(0), sqlDataReader.GetString(1));
        }
    }
```

To be clear: This mapper is currently the ONLY place in my code where the constructor for InternalAmenity is called, so this issue could not be caused by any other line of code.

What's happening is, when I hit `await Task.WhenAll(...)`, it replays the three async actions ahead of it. When it replays these actions, it tries to initialize InternalAmenity with null arguments to both of its constructor parameters. This fails because the second argument is turned into a Regex object, which doesn't allow nulls.

I have confirmed that it SUCCESSFULLY initializes the InternalAmenity object when it actually runs the function -- it only fails on replay. I'm beating my head on a wall trying to figure out what's causing this, especially since the same error doesn't affect either of the other calls to what amount to basically the same methods.

### Known workarounds
I've added a coalesce to an empty string in the constructor call to InternalAmenity. Not ideal, but it's a stopgap.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.4.1
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### If deployed to Azure
I'm happy to deploy this and let it fail so you can see the telemetry, though I would have to communicate the details privately.

**Comment by ConnorMcMahon** [comment]
@sejohnson-at-griffis

What does your `InternalAmenity` class look like? 

Behind the scenes, we are serializing the object and deserializing the object using Newtonsoft, so it's possible something unusual is happening there. I would also recommend maybe using an explicit `List` type instead of `IList`, as that may be confusing Newtonsoft when deserializing the results of your activity functions.

**Comment by sejohnson-at-griffis** [comment]
@ConnorMcMahon 

Sorry for the delay!

```csharp
public class InternalAmenity : AmenityMatcher
    {
        /// <summary>
        /// Returns a new InternalAmenity given an amenity name and a regex pattern to recognize that amenity by.
        /// </summary>
        /// <param name="amenityName"></param>
        /// <param name="regexPattern"></param>
        public InternalAmenity(string amenityName, string regexPattern)
        {
            Name = amenityName;
            Regex = new Regex(regexPattern, RegexOptions.Compiled | RegexOptions.IgnoreCase);
        }
    }
```

```csharp
public abstract class AmenityMatcher : IAmenityMatcher
    {
        /// <summary>
        /// A name describing the Regex pattern this AmenityMatcher uses.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// The Regex pattern that applies to this Amenity.
        /// </summary>
        [JsonProperty("regex")]
        public Regex Regex { get; internal set; }

        /// <summary>
        /// Given an amenity name, determine if that name qualifies as an Amenity.
        /// </summary>
        /// <param name="amenityName"></param>
        /// <returns>True if the amenity name matches this AmenityMatcher's pattern, false if not.</returns>
        public bool IsAmenityMatch(string amenityName)
        {
            if (Regex.IsMatch(amenityName))
            {
                return true;
            }
            return false;
        }
    }
```

I'm aware of the dependency Durable Functions takes on Newtonsoft, but I don't see anywhere here where that could be causing a problem -- I _am_ specifying different names for serialization, but that should apply in both directions. The only areas where I've seen Newtonsoft issues with Durable Functions is if fields are `[JsonIgnore]`ed.

**Comment by ConnorMcMahon** [comment]
@sejohnson-at-griffis,

It turns out you can fix the issue by giving `InternalAmenity` a parameterless public constructor. According to the below quote from this [SO answer](https://stackoverflow.com/a/36871402/9035640),

> If your type does not have a public parameterless constructor, but does have a single public constructor with parameters, JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters() will call that constructor, matching the constructor arguments to the JSON properties by name and using default values for missing properties. Then afterwards any remaining unused JSON properties will be set into the type.

Essentially, Netwonsoft.JSON has to use a constructor, and so it will use the first public one available, trying to route the right parameters. Since `amenityName` and `regexPattern` don't match the JSON property names, Newtonsoft.JSON will pass in null for these values. Therefore, your constructor needs to gracefully handle null values, or provide an alternate constructor for Newtonsoft to use.

**Comment by sejohnson-at-griffis** [comment]
Wow, that's incredible. 😂 Thanks so much for figuring this out -- I'll be sure to give any classes that may be serialized/deserialized through Durable Functions a public parameterless constructor from now on.

All the best!

**Comment by ConnorMcMahon** [comment]
Happy to help! Serialization/deserialization can be surprisingly tricky, especially with nuanced situations like this!
