### ISSUE TITLE
Unable to overwrite default serialization settings

### ISSUE THREAD

**Issue by NickSevens** [Azure/azure-functions-durable-extension#1675]
### Description
I'm returning abstract types and interfaces from my Activities, which can't be deserialized without implementing a custom `JsonConverter`. However, it seems there is no way to overwrite the default JSON settings, so the custom converters are not used by the orchestration.

### Expected behavior
I want to be able to overwrite the default JSON serialization settings so my custom JsonConverter is used by the Orchestration.
(E.g. when using `context.CallActivityAsync<IMyInterface>("myactivity", null);`)

### Actual behavior
The JsonConvert I implemented to be able to deserialize my interfaces is ignored.
Adding the converter to `JsonConvert.DefaultSettings` does not seem to be honoured.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.4.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: C#

**Comment by amdeel** [comment]
Hey @NickSevens, you can actually inject your own IMessageSerializerSettingsFactory with Functions dependency injection. This will let you add your own JsonSerializerSettings. Let me know if you have any problems with this!

**Comment by ConnorMcMahon** [comment]
To add, I am in the process of adding some documentation of how to tackle this problem. It is incomplete, but I'm thinking that I should push what I have shortly instead of letting perfect be the enemy of good.

**Comment by NickSevens** [comment]
@amdeel works perfectly! 👍 exactly what I was looking for! Thanks for the help.
