### ISSUE TITLE
Azure Durable Functions Performance and Scale

### ISSUE THREAD

**Issue by Shishkovskiy** [Azure/azure-functions-durable-extension#1686]
Hi there, I'd like to clarify a few questions related to Durable Functions, I've read the documentation, and I`m confused a little)

Copy from the documentation :

- Because the orchestrator and entity function instances are stateful singletons, it's not possible to use a competing consumer model to distribute load across VMs. 

- Use a random identifier for the instance ID. Random instance IDs help ensure an equal load distribution when you're scaling orchestrator functions across multiple VMs. 

To tell the truth I've not got the point how the Orchestration Functions scale-out.

If I understood correctly the whole flow, it works something like this :

We have a trigger that can create a new instance, then a message is sent to the control queue to run Orchestrator plus a new message will appear in Instance Table that Orchestrator is started.

Let's imagine that we have a few Activity Functions and use the changing pattern: 

- When we bump into the first Activity function the message will be added to the Instance Table that the first Activity Function is Scheduled and then Orhestator goes to sleep when the Activity Function is running.

- When Activity Function is completed, the result of execution is added to the History Table and a message will be sent to the control queue then the Orchestrator will be triggered to start working again, when it bumps into the first Activity Function it goes to the History Table to get the result of execution if there is any result, the same actions with others.

And my question is if Activity functions are stateless and scaled out automatically by adding VMs, How Does the Orchestrator scale based on the number of control queues? 
Because each Orcheattor has its own control queue and each VM locks a single control queue.

**Comment by olitomlinson** [comment]
@Shishkovskiy 

Orchestrations are essentially allocated to a ‘partition’ via a deterministic hash of the Orchestration ID. Each partition is 1 to 1 with a control queue.

You can have an infinite amount of Orchestrations spread across up to 16 partitions.

In a fully scaled out scenario, each partition will be allocated to an individual Node/worker to achieve full throughput of orchestration code. A partition can’t be allocated to more than one node/worker.

During low traffic/scaled-in scenario, many partitions will be packed onto one or a few node/Workers.

Running along side all of this, you have Activities which can essentially scale to the full scale of the Consumption plan, using a competing consumer model.

I hope this helps, but if not happy to guide further!

**Comment by ConnorMcMahon** [comment]
@olitomlinson pretty much struck the nail on the head with this. 

@Shishkovskiy, any recommendations of how we can make this more clear in our documentation? Were any existing sections that made this confusing, or is it just a matter of being more explicit about this?

**Comment by Shishkovskiy** [comment]
@ConnorMcMahon  
 
Copy from the documentation :

- Because the orchestrator and entity function instances are stateful singletons, it's not possible to use a competing consumer model to distribute load across VMs.

- Use a random identifier for the instance ID. Random instance IDs help ensure an equal load distribution when you're scaling orchestrator functions across multiple VMs.

To tell the truth, it confused me slightly, because, on the one hand, we not possible to use a competing consumer model to distribute load across VMs, on the other hand, we should use a random identifier for the instance ID. Random instance IDs help ensure an equal load distribution when you're scaling orchestrator functions across multiple VMs. 

After that, I`m fully confused about how the Orchestration could scale, and could it load across multiple  VMs  :)

**Comment by olitomlinson** [comment]
@Shishkovskiy 

I've whipped up a few diagrams that might help to explain this visually. If it helps, please let us know!

**Given a Function App where the `partitionCount` in `host.json` is set to `3`**

---

During a low traffic / scaled-in scenarios, Partitions will be packed onto a minimum number Workers. _Remember Orchestrations Functions are allocated to a Partition via a consistent hashing of the `Orchestration ID`_ - this is essential for the stateful singleton concept of an Orchestration.

![image](https://user-images.githubusercontent.com/4224880/108198022-02c95b80-7113-11eb-8cc4-1769906126b6.png)

---

As traffic increases and the underlying Workers begin to scale-out, Partitions will _eventually_ rebalance over the available Workers, up to a point where one Worker contains a single Partition. This is what is meant when the documentation describes _"scaling orchestrator functions across multiple VMs."_

![image](https://user-images.githubusercontent.com/4224880/108198775-f5f93780-7113-11eb-854f-223b3168fb05.png)

**Note**  Activity functions have no link to Partitions. Activities are allocated to workers purely by virtue of the competing consumer model.

**Comment by ConnorMcMahon** [comment]
I think the answer is that we need to correct the below statement so that it is more clear.

> Because the orchestrator and entity function instances are stateful singletons, it's not possible to use a competing consumer model to distribute load across VMs. Instead, orchestrator and entity messages are load-balanced across the control queues.

Maybe something like this:

> Because the orchestrator and entity function instances are stateful singletons, it is important that each orchestration/entity is only processed by one worker at a time. To achieve this, each orchestration instance and entity are assigned to a single control queue. These control queues are load balanced across workers to ensure that each queue is only processed by one worker at a time.

**Comment by atoader** [comment]
I think that adding an example or a few scenarios in the documentation might help explaining this scenario. I have the following scenario which I am prototyping and measuring throughput for.
DispatchJob [Orchestrator]
   -> CreateJob [Activity] -> Returns one object
   -> RunJob [Orchestrator] 

RunJob [Orchestrator]
  -> CreateSubJobs [Activity] -> Returns list of jobs
  -> 1..n RunJob [Orchestrator] -> Each job can have subjobs so I am calling into RunJob again. Task.WhenAll() is used to wait for all of them. n ranges from 100 - 30000 depending on the environment. 
  -> CompleteJob [Activity] -> Take the results from RunJob and aggregate

If the job doesn't have subjobs, RunJob follows this flow:
RunJob [Orchestrator]
  -> CreateSubTasks [Activity] -> Returns list of jobs
  -> 1..n RunTask [Activity] -> Each job can have multiple tasks, between 0-100
  -> CompleteJob [Activity] -> Take the results from RunTask and aggregate

A few things that I could not figure out from the docs:
- Is a Control-Queue owned by an orchestrator instance or a orchestrator function? In the case of RunJob, if I have 10 instances of RunJob running, will 9 instances wait while the 1st one finishes or is it that messages for all 10 instances will be processed?
- When you say that an Orchestrator is a stateful singleton, does that mean there can only be a single instance of it executing at any point in time? Could you maybe help me understand what will happen in my recursive call to RunJob?

I am currently experimenting with increasing the number of control queues hoping that different instances of RunJob will be able to use different control queues. I am also considering splitting the 100-30000 subjobs into batches of n where n optimizes throughput.

**Comment by olitomlinson** [comment]
- a Control queue is only consumed by its equivalent partition. `control-queue-1` is only consumed by `partition 1` etc 
- An orchestrations ID is hashed, to one of the available partitions. An orchestration can’t ever change partition.
- Think of an orchestration as a class or blueprint, and you can create a virtually infinite number of ‘instances’ of these orchestrations. 
- The amount of concurrent orchestrations executing code at any one time is equal to the number of partitions. The max is 16. But remember orchestrations execute very quickly as they don’t do IO, or anything intensive. Anecdotally, In my use case I’ve seen 10,000 short-lived orchestrations start and complete in just 60 seconds.

**Comment by atoader** [comment]
I think it is clear now! The diagram above and this explanation helped. Your point on 10,000 short-lived orchestrations starting and completing in 60 seconds is an interesting aspect. 

I have another question related to scaling. The maximum number of activities per app instance can be controlled through these settings: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#functions-20 . In my example, I have activities such as CreateJob/CreateSubJobs which can scale up to 10x per core and maybe even more as they are short lived and fast to execute, but I also have activities such as RunTask which are compute intensive and having more than 1 per core would significantly degrade performance. 

Is there anyway to control scaling for the individual activities?

**Comment by sebastianburckhardt** [comment]
I believe we currently we don't have a feature for controlling the concurrency of activity functions individually. 

I think we should seriously consider adding a feature that can support these types of scenarios. It seems quite important for achieving scale-out.

**Comment by davidmrdavid** [comment]
Really insightful discussion here, and thank you @olitomlinson for those diagrams. I really think our docs would benefits from a visualization like that. Currently, we only have the scaled-out scenario visualized [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#durable-functions-1x-1) but also visualizing the scaled-in setting, as your diagrams do, would help complete the picture.

**Comment by mpaul31** [comment]
So obviously there is danger in decreasing the `partitionCount` after an application has been released but what about increasing the value? Are there any dangers?

**Comment by olitomlinson** [comment]
@mpaul31 

You will risk orphaning many in-flight orchestrations by changing the initial partitionCount, so it’s strongly recommended against doing so.

Increasing is just as dangerous as decreasing as either will change the partition ranges.

**Comment by mpaul31** [comment]
Hmm...then unless I missed it this should _definitely_ be called out in the documentation. So what would be the recommend way to change the partitionCount when scaling requirements change? A coordinated release where there are no in-flight orchestrations? moving to a new storage account wouldn't work when you are using entities and all the state lives in original storage account. 

Thoughts?

**Comment by olitomlinson** [comment]
I’m not an authority on this but my understanding is that you need to get to a stage where all the control queue lengths are 0, and you can guarantee new work won’t be added to the control queues while you make the change. 

I think you also need to recycle the app as well to unload any orchestrations from memory, which should be achieved by simply stopping the App.

Approaches for draining the control queues may vary, depending on how complex your orchestrations are, and how long their lifetime is.

**Comment by mpaul31** [comment]
Once again, thanks @olitomlinson for clearing this up!

**Comment by davidmrdavid** [comment]
Assigning this to myself to make sure we follow-up with some docs improvements :) . We'll be back with updates

**Comment by davidmrdavid** [comment]
Hey all, we _just_ released **updated** scaling docs here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale ✨ 

Thank you all for this discussion, it informed the changes we made. @olitomlinson, we liked your graphics a lot and ended up using them! **Thank you for this contribution**. We did modify one of them, and also corrected a few minor technicalities that were off in this discussion. Please see the new docs for an up-to-date, and thoroughly scrutinized, description of these features.

I'll be closing this issue for now, thanks all!

**Comment by olitomlinson** [comment]
@davidmrdavid 

Great stuff! Super cool that you used my diagrams! 😄

**Comment by olitomlinson** [comment]
@davidmrdavid 

Just re-reading these docs, and could do with a bit of clarity on how 'active' is defined.

> The upper-bound of the maximum number of concurrent _active_ orchestrations at any given time is equal to the number of workers allocated to your application times your value for `maxConcurrentOrchestratorFunctions`. 

Does active mean in a `Running` state? 

It is my understandign that `Running` can be either
- Currently in memory and executing, `awaiting` on an Activity Result or External Event.
- Unloaded from memory and `await`ing on an Activity Result or External Event.

Given that if the `maxConcurrentOrchestratorFunctions` for a given host is 10, and there are exactly 0 in memory and 10 orchestrations that are **unloaded** from memory as they are waiting for an Activity Result or External Event, no further Orchestrations will be started? until at least one of those orchestrations has been loaded into memory and Completed?

Or is this limit only for Orchestrations that are **presently** occupying memory in the host and are in any kind of Running state (whether they are awaiting or not) ?

**Comment by davidmrdavid** [comment]
Hi @olitomlinson,

By 'active' orchestrations I was referring to orchestrators that are currently **in memory** doing some kind of processing. Broadly speaking, those orchestrations would either be (1) replaying their history because some of their work items returned or (2) scheduling new work items.

For correctness' sake, @cgillum please let me know if this is what you understand by 'active orchestrations' as well.

Does that answer your question? Maybe I should make a quick patch to the docs to clarify that terminology further 🤔

Also, it's my understanding that orchestrations that are `awaiting` some Result are not in memory _unless that Task has already completed_, at which point I wouldn't consider that thread to be `awaiting` any more since now it's simply executing. Maybe I'm wrong about that, so I'd love to get a second opinion here.

**Comment by cgillum** [comment]
Yes _active_ in this context means in-memory. It is NOT the same as `Running`. Maybe we can rephrase the above statement like:

> The upper-bound of the maximum number of _**orchestrations that can be loaded into memory**_ at any given time...
