### ISSUE TITLE
Improve Error Handling of Calling Functions Missing FunctionName Attribute

### ISSUE THREAD

**Issue by kaftw** [Azure/azure-functions-durable-extension#169]
Occasionally, I'll forget to add the FunctionName attribute to a function that's called from an orchestrator function.  What happens is a NullReferenceException with a deep and confusing stack trace that makes it difficult to debug.  It'd be great if this case could be caught and the exception message made clearer.

**Comment by cgillum** [comment]
Interesting. I would have expected an `ArgumentException` saying it couldn't find a function with the given name (that's the design, anyway). That's not what you're seeing? I'll see if I can reproduce it.

Also, just to make sure, are you using the latest version of the Microsoft.Azure.WebJobs.Extensions.DurableTask package (1.1.0-beta2)?

**Comment by kaftw** [comment]
Ah, this one is still using 1.0.0-beta-04.  I'll upgrade the package and see if I get the same repo.

**Comment by kaftw** [comment]
Using the latest version of the NuGet packaged, I get the following error, which is clearer than previous versions but could still use a little work: 

> [2/27/2018 21:09:25] 1680db3435af4cb5bbc1c16dca5dba5e: Function 'TestManagerSourceAssignments (Orchestrator)', version '' failed with an error. Reason: Microsoft.Azure.WebJobs.FunctionFailedException: The activity function 'CreateCompanyAsync' failed. See the function execution logs for details. ---> DurableTask.Core.Exceptions.TaskFailedException: Object reference not set to an instance of an object.

**Comment by cgillum** [comment]
This doesn't sound like the same problem. In this case, it sounds like we successfully invoked *CreateCompanyAsync*, but it failed with an unhandled exception - e.g. a null-ref inside the activity code.  Can you confirm?

**Comment by kaftw** [comment]
If I set a breakpoint at the beginning of the function, it's never hit.  All I did was comment out the FunctionName attribute to reproduce.

**Comment by cgillum** [comment]
Ah, so it could be a bug in the dispatch later for activity functions. I'll try and see if I can reproduce it.

**Comment by cgillum** [comment]
I investigated this further and it looks to be a bug in the Azure Functions host: https://github.com/Azure/azure-functions-host/issues/2785. Unfortunately I don't think there is anything we can do to mitigate this problem except to get a fix from the host, after which this issue should resolve itself.
