### ISSUE TITLE
Distrubted tracing fails on local debug if instrumentation key not set

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-durable-extension#1694]
With the following host.json settings the function fails during startup for local debug because the Instrumentation Key isn't defined.  In all other function experiences running without an instrumentation key just doesn't emit logs, but doesn't block startup.  Maybe this should be a warning instead of an error?

```json
{
    "version": "2.0",
    "extensions": {
        "durableTask": {
            "tracing": {
                "distributedTracingEnabled": true,
                "distributedTracingProtocol": "W3CTraceContext"
            }
        }
    },
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": false
            },
            "httpAutoCollectionOptions": {
                "enableW3CDistributedTracing": true
            }
        }
    }
}
```

**Comment by cgillum** [comment]
FYI @davidmrdavid and @TsuyoshiUshio. I agree this shouldn’t cause a failure.

**Comment by davidmrdavid** [comment]
Thanks for pointing this out! My reasoning here would be that having `"distributedTracingEnabled": true` wihtout the instrumentation key is incomplete (misleading even) config, and that a raising an error would help customers "_fall into success_".

But I trust y'alls judgement and y'all point out that there's precent for this so I'll turn this into a warning :) . Let's schedule it for the next extension release.

**Comment by jeffhollan** [comment]
Yep I get your point / concern - today though for better or worse our dev flows don't include App Insights, and we don't inject it until you publish. But we do inject App Insights by default through all tools now.  So a warning hopefully let's people know "hey you turned this on but you aren't actually using it yet", while still sticking with the default flow we have today.  If we see incidents of folks opening tickets and such wondering why this feature isn't working, I'd be open to moving it back to an error -- ideally paired with a feature to make it much easier to get App Insights key into a local dev environment.

**Comment by TsuyoshiUshio** [comment]
Good point. Probably, in here or TelemetryActivator we can make it not throw the Exception.  By default, All the logic of Distributed Tracing as turned off. We can keep it off if there is no AppInsights settings. It might be great if we add some telemetry to the telemetryActivator for debugging and notify people that is configured/not configured. It also helps our ICM work.
