### ISSUE TITLE
The 'FunctionName' function is in error: The method 'FunctionName' cannot be found.

### ISSUE THREAD

**Issue by vbhupathi** [Azure/azure-functions-durable-extension#1695]
### Description
Getting this _The 'FunctionName' function is in error: The method 'FunctionName' cannot be found._ error while doing the
 `func start` on durable functions (starter is a ServiceBusTrigger).

### What I tried so far
 Followed this #667 and cleared all NuGet caches using `dotnet nuget locals all --clear` but still getting the same error

**Comment by cgillum** [comment]
@vbhupathi can you share an example of how to reproduce this problem, including information about which version of the nuget extension your app is using?

**Comment by vbhupathi** [comment]
Thanks for the response @cgillum.  I just figured out that the functions should be declared as `public ` even they are in the same class. Changing the access modifier to `public ` fixed this issue.

**Comment by cgillum** [comment]
Thanks for confirming @vbhupathi - glad you got it working.

FYI @amdeel @ConnorMcMahon this might be another thing the analyzer could detect.
