### ISSUE TITLE
Be able to use distributed tracing without APPSINSIGHTS_INSTRUMENTATIONKEY

### ISSUE THREAD

**Issue by koolhead7** [Azure/azure-functions-durable-extension#1697]
### Description
Currently in our services, the correlation is broken. I updated the durabletask framework to 2.4.1 and enabled the distributed tracing. On initializing the host, there is a null pointer exception while creating the TelemetryClient in TelemetryActivator.cs (line 98).
This is primarily because APPINSIGHTS_INSTRUMENTATIONKEY is not available in the environment variable. If I set it, the exception doesn't occur.

Questions:
What are the other ways of setting APPINSIGHTS_INSTRUMENTATIONKEY? Is it possible to set it through options/durabletask initialization?

### Relevant source code snippets
In the service, durabletask is set as below:
```
                    webjobs.AddDurableTask(durables =>
                    {
                        durables.HubName = "value";
                        durables.LocalRpcEndpointEnabled = true;
                        durables.UseGracefulShutdown = true;
                        .....
                        // adding distributed tracing for correlation
                        durables.Tracing.DistributedTracingEnabled = true;
                        durables.Tracing.DistributedTracingProtocol = "W3CTraceContext";
                    });
```

### Known workarounds
Set APPINSIGHTS_INSTRUMENTATIONKEY as part of environment variable.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
- **Azure Functions runtime version (1.0 or 2.0)**:
- **Programming language used**:

**Comment by cgillum** [comment]
Possible duplicate: https://github.com/Azure/azure-functions-durable-extension/issues/1694

**Comment by davidmrdavid** [comment]
Hi @koolhead7,

Another alternative, and the one I've used in the past, is to set it in your `local.settings.json`, as described here: https://github.com/Azure/azure-functions-durable-extension/blob/dev/samples/correlation-csharp/configuration.md#appsettings

I don't believe it can be set through DurableTask options since there's no key for it here: https://github.com/Azure/azure-functions-durable-extension/blob/3f4b27e722ced6a1eb8999bb7d934b21179f5f11/src/WebJobs.Extensions.DurableTask/Options/DurableTaskOptions.cs#L18

There could be other ways, but I would first need to understand your use-case a little better. Are you looking to manage your instrumentation key in some particular way or are you just interested in a listing of alternative ways of setting this value?

**Comment by koolhead7** [comment]
Thanks @davidmrdavid for swift response. In my case, there is a separate package shared by all microservices to set up telemetry client and it is dependency injected in the service.

To use durabletask, I have to pass this APPINSIGHTS_INSTRUMENTATIONKEY separately.
I am not sure (and don't think) if durable framework can use the telemetryclient instance already created.
At least there should be a generic way to pass the APPINSIGHTS_INSTRUMENTATIONKEY (like traceoptions) rather than just env variable.

**Comment by davidmrdavid** [comment]
Hmm, I see your point. I'm unsure if there's a good to answer to this as the instrumentation key is set in `local.settings.json` instead of `host.json`. @ConnorMcMahon do you know if there's a way to do what @koolhead7's asking for?

**Comment by ConnorMcMahon** [comment]
@koolhead7, I would need to know more about how  you are injecting your own telemetry client to know how we would interact with it for distributed tracing. In general, I know the functions runtime is very picky about how you use app insights with our dependency injection. You can read more about that [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#logging-services).

**Comment by davidmrdavid** [comment]
We're still tracking this issue. Posting to avoid auto-closing
