### ISSUE TITLE
Fix nuget package metadata to reflect the fact that package is MIT licensed

### ISSUE THREAD

**Issue by yuanweilei** [Azure/azure-functions-durable-extension#1701]
### Description
Question: What the license of Microsoft.Azure.WebJobs.Extensions.DurableTask, EULA or MIT?

Steps
- Using Visual Studio and download Microsoft.Azure.WebJobs.Extensions.DurableTask 2.3.1
- Noticed that "License: View License" link shows the license is EULA 
https://www.microsoft.com/web/webpi/eula/aspnetcomponent_rtw_ENU.htm
- But If I go to the "Project URL", it shows the license is MIT 
https://github.com/Azure/azure-functions-durable-extension

![image](https://user-images.githubusercontent.com/26296423/109447890-203de400-7a88-11eb-90ea-d39beb82b6f0.png)

**Comment by ConnorMcMahon** [comment]
@anthonychu, we should definitely make sure this is correct in future release. I'm guessing that the license should be MIT, but I want to verify.

**Comment by yuanweilei** [comment]
Hi @ConnorMcMahon 
Thank you very much! My team wants to use this for commercial using so if it is MIT everything is fine.
Just curious, if you change it to "MIT in future release.", what's the license of exist versions?

**Comment by ConnorMcMahon** [comment]
@yuanweilei, you can consider this release and all of our previous releases to be MIT licensed. We will update our nuget package metadata for all future releases to accurately reflect this.
