### ISSUE TITLE
Verbose Logging App Insights

### ISSUE THREAD

**Issue by RichardBurns1982** [Azure/azure-functions-durable-extension#1703]
We have just started using an Azure Durable Orchestration Function which is linked to application insights.

The telemetry is filling up with logs we cannot seem to stop:

> Time 16:51:03 Message funcname-applease: Starting lease renewal with token xxxxxxxxxxxxxxxxxx Category DurableTask.AzureStorage EventId 123 ProcessId 8964
> 
> Time 16:51:03 Message funcname-applease: Lease renewal with token xxxxxxxxxxxxxxxxxx succeeded Category DurableTask.AzureStorage EventId 124

We are getting 100s a minute and despite our Logging settings they are not stopping:

```
{
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "messageHandlerOptions": {
        "maxConcurrentCalls": 1
      }
    }
  },
  "functionTimeout": "00:04:59",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "maxTelemetryItemsPerSecond": 20
      }
    },
    "logLevel": {
      "default": "Information",
      "Function": "Information",
      "Host.Results": "Information",
      "Host.Aggregator": "Information",
      "Host.Triggers.DurableTask": "Error",
      "DurableTask.AzureStorage": "Error",
      "DurableTask.Core": "Error"
    }
  }
}
```

These messages do not appear to have a LogLevel and despite setting all of these to none through to only error they still keep coming in the Live Metrics.

Does anyone know how to stop these logs?

**Comment by ConnorMcMahon** [comment]
You should not be getting those logs, as they are in the DurableTask.AzureStorage category, but those are Verbose/Information logs you are seeing.

My guess is that this is an issue with the Functions runtime not properly filtering log categories by the levels you have configured.

A couple of questions:

- What version of the functions host are you using?
- Is this happening when hosted in Azure, running locally, or both?
- Do you have any custom logic in your Startup.cs that touches logging?

**Comment by RichardBurns1982** [comment]
Thanks for getting back to me, answers below:

1. I can't seem to find the exact host version shown anywhere but under configuration:

![image](https://user-images.githubusercontent.com/67505780/109709077-0d183a80-7b94-11eb-83f0-a33110c229f6.png)

2. Happening in Azure, not hooked up to application insights locally.

3. No code in startup around logging.

**Comment by ConnorMcMahon** [comment]
Can you share an instance id for one of your orchestrations, along with a region + rough UTC timestamp?

That can help me find your application in our telemetry, and I can see if something odd is going on.
