### ISSUE TITLE
Durable Client for SeriveBusTrigger is not calling Orchestrator

### ISSUE THREAD

**Issue by srishtipurohit** [Azure/azure-functions-durable-extension#1708]
I am trying to write a workflow to listen serviceBustrigger using durable azure functions. But client running without orchestrator. Neither throwing any error. Can anyone tell what am i missing to enable seriveBusTrigger in durable function?
Following is the client function code :
```csharp
        [FunctionName("UpdateGlobalRatesOnRSLs")]
        public static async Task Run(
            [ServiceBusTrigger("%EventMessageTopic%", "%Subscriber%", Connection = "ServiceBus")] string message,
            MessageReceiver messageReceiver,
            string lockToken,
            [DurableClient] IDurableOrchestrationClient starter, ILogger log)
        {
            log.LogInformation($"message - " + message);
            if (string.IsNullOrWhiteSpace(message)) await messageReceiver.DeadLetterAsync(lockToken, "Message content is empty.", "Message content is empty.");

            var orchestrationInput = JsonConvert.DeserializeObject(message);
            string instanceId = await starter.StartNewAsync<object>("UpdateGlobalRatesOnRSLs_OrchestrationFunction", orchestrationInput);
            log.LogInformation($"Orchestration Started with ID: {instanceId}");
            
        }
````
Or please share any working code sample.

**Comment by cgillum** [comment]
@srishtipurohit can you provide more information, such as whether you are running this app locally or in Azure?  If it is in Azure, can you provide the name of the app and an approximate time range where we can investigate?

Also, can you confirm whether your Service Bus trigger is getting invoked and whether it is completing successfully? It would also help if you could share any logs that you have collected.

**Comment by srishtipurohit** [comment]
> @srishtipurohit can you provide more information, such as whether you are running this app locally or in Azure? If it is in Azure, can you provide the name of the app and an approximate time range where we can investigate?
> 
> Also, can you confirm whether your Service Bus trigger is getting invoked and whether it is completing successfully? It would also help if you could share any logs that you have collected.

I am running it from my local only. It is reading service bus message fine but when it is reaching to "starter.StartNewAsyn("orch") call, control is not moving to orchestrator function definition. Hence no action is happening post client call neither any failure/exception is coming up.

**Comment by ConnorMcMahon** [comment]
Is your function UpdateGlobalRatesOnRSLs finishing?

Also, are you using the Azure Storage emulator, or using a connection string for a real Azure Storage account? Either way, you can use Azure Storage Explorer to look at the storage account and see if we added a message to any of the control queues we create? Note that all of the resources we create in your storage account have the prefix of your task hub name.
