### ISSUE TITLE
Specifying hubName in the function itself doesn't work (Orchestration never starts)

### ISSUE THREAD

**Issue by jayserdny** [Azure/azure-functions-durable-extension#1714]
### Description
Whenever I put the name of the Task Hub directly in the DurableClient function, the orchestrator never starts. When I do it in host.json, it does start.

I have a single Function Apps with N orchestrations so I cannot specify it in host.json

### Expected behavior
I expect to be able to specify the TaskHub name in my DurableClient function instead of globally at host.json.

### Actual behavior
When specifying the TaskHub name at the DurableClient function level, the orchestration enters an infinite pending status. It works when specifying it globally at host.json

### Relevant source code snippets
```csharp
public async Task EventTrigger(
            [QueueTrigger(
             queueName: "%AzureQueue:ClientRequestQueueTrigger%",
             Connection = "QueueConnectionString")] string eventMsg,
            [DurableClient(
             TaskHub = "%DurableFunctions:ClientHandlerHubName%")] IDurableOrchestrationClient starter,
             ExecutionContext executionContext, string id,
             int dequeueCount, DateTimeOffset insertionTime)
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.4.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0.11
- **Programming language used**: C#

**Comment by amdeel** [comment]
Hey, @jayserdny. Task hubs are meant to be containers that are associated with your app, not individual to each orchestration. All of the orchestrations in your function app will be associated with your task hub. Being able to specify a task hub in the DurableClient attribute is meant to be used when trying to start orchestrators that are in another app.

So in your case, you need a task hub in your host.json and you will not need to specify a task hub in your DurableClient attribute. If you want to separate your orchestrations in multiple apps, you can use the task hub name in your DurableClient attribute as one way to communicate with them (optionally, you can pass this string in as a parameter to the StartNewAsync method).

**Comment by jayserdny** [comment]
Hello @amdeel oh that makes sense. I got that concept wrong. Thanks.

One more question related to this, if I have an Azure Functions that contains multiple orchestrations as well as multiple durable clients, wouldn't they run into conflict since they are all using the same task hub?

**Comment by amdeel** [comment]
No, they will not interfere. Messages for each orchestration will be associated with unique instance ids.

**Comment by jayserdny** [comment]
That makes sense. That answered all my doubts. Thank you! Closing this now.
