### ISSUE TITLE
Eternal Orchestration stuck after timer expired

### ISSUE THREAD

**Issue by js8383** [Azure/azure-functions-durable-extension#1722]
### Description
I have an eternal orchestrator that does periodic job status polling and exits only when certain conditions are met.

### Expected behavior
After a timer expires, the orchestrator continues to the next execution by `context.ContinueAsNew`

### Actual behavior
The orchestrator got stuck after the time expired. It never went to the next execution, and its runtimeStatus remained at `Running`. 

### Relevant source code snippets
Removed some unrelated info and ops.
```csharp
public static async Task JobStatusPolling(
    [OrchestrationTrigger] IDurableOrchestrationContext context,
    ILogger log)
{
    log = context.CreateReplaySafeLogger(log);
    
    var state = context.GetInput<JobStatusPollingState>();
    var status = // call another activity function to get status

    if (status == JobStatus.Completed)
    {
        return;
    }
                
    // Retry with exponential backoff
    var waitTime = TimeSpan.FromSeconds(5) + TimeSpan.FromMilliseconds(Math.Pow(2, Math.Min(16, state.RetryIndex * 0.25)));
    log.LogInformation($"Status is {status} - next poll in {waitTime.TotalSeconds} seconds");

    await context.CreateTimer(context.CurrentUtcDateTime.Add(waitTime), System.Threading.CancellationToken.None);

    state.RetryIndex++;
    log.LogInformation($"Polling again ({state.RetryIndex})");
    
    context.ContinueAsNew(state);
}
```

### App Details

- **Durable Functions extension version**: 2.4.1 
- **Azure Functions runtime version**: 3.0
- **Programming language used**: C#

### Screenshots
![image](https://user-images.githubusercontent.com/6410865/110842643-31db7480-825c-11eb-8dab-4f299ad3779a.png)

The orchestration stuck after the row with EventType "TimerCreated".

### If deployed to Azure
- **Timeframe issue observed**: 2021-03-10T23:21:31Z
- **Azure region**: WestUS2
- **Orchestration instance ID(s)**: s-cbevan-20210310-232123:Polling

Can provide more info if needed.

**Comment by ConnorMcMahon** [comment]
@js8383 

So sorry for the delay here. I started a response for this back in March but I didn't quite finish the reply, and now it's lost.

I don't remember the exact details of this case, but I do know that the TimerFired event was visible, but your app was repeatedly dismissing it for some reason. I wish I could look into the details again, but unfortunately the timerange you have provided has fallen out of our logs.

If you could provide another timestamp + instance id, I would be happy to offer more help.
