### ISSUE TITLE
Improve handling of in-flight orchestrations with deleted/disabled/renamed functions

### ISSUE THREAD

**Issue by vigouredelaruse** [Azure/azure-functions-durable-extension#1729]
like it says i have some orchestrations that cannot be terminated - 

during boot of the test docker container, here's the complaint about a missing function
[2021-03-13T00:53:03.018Z] The function 'azure_table_retention' doesn't exist, is disabled, or is not an orchestrator function. Additional info: The following are the known orchestrator functions: 'DiscoverEnvironmentWithDefaultWADiagnosticsPolicy'.. InstanceId: d59aeaeab89340738969faf0c5e08d10. Function: azure_table_retention. HubName: TestHubName. AppName: . SlotName: . ExtensionVersion: 2.4.1. SequenceNumber: 39.

and here's the output of querying the status of orchestrations
{
    "durableOrchestrationState": [
        {
            "name": "azure_table_retention",
            "instanceId": "74abf8d69af24d0db5a71b954eb44b78",
            "createdTime": "2021-03-06T05:51:34.7299593Z",
            "lastUpdatedTime": "2021-03-06T05:51:37.3906088Z",
            "input": null,
            "output": null,
            "runtimeStatus": 0,
            "customStatus": null,
            "history": null
        },
        {
            "name": "azure_table_retention",
            "instanceId": "b3633997f6b641bba5facf9a6a5f6bae",
            "createdTime": "2021-03-09T04:58:08.4021799Z",
            "lastUpdatedTime": "2021-03-09T04:58:16.8892156Z",
            "input": null,
            "output": null,
            "runtimeStatus": 0,
            "customStatus": null,
            "history": null
        },
        {
            "name": "azure_table_retention",
            "instanceId": "d59aeaeab89340738969faf0c5e08d10",
            "createdTime": "2021-03-06T05:51:23.955782Z",
            "lastUpdatedTime": "2021-03-06T05:51:34.4413644Z",
            "input": null,
            "output": null,
            "runtimeStatus": 0,
            "customStatus": null,
            "history": null
        },
        {
            "name": "azure_table_retention",
            "instanceId": "ef671451cb38468ca19f44cea538e58c",
            "createdTime": "2021-03-09T04:15:09.5547543Z",
            "lastUpdatedTime": "2021-03-09T04:15:14.7509292Z",
            "input": null,
            "output": null,
            "runtimeStatus": 0,
            "customStatus": null,
            "history": null
        },
        {
            "name": "azure_table_retention",
            "instanceId": "fc9a33bcf51c4a0fa80ca35a9d382b57",
            "createdTime": "2021-03-06T05:54:21.0588647Z",
            "lastUpdatedTime": "2021-03-06T05:54:25.1124963Z",
            "input": null,
            "output": null,
            "runtimeStatus": 0,
            "customStatus": null,
            "history": null
        }
    ],
    "continuationToken": null
}

and after running terminate async, the following query is run
           var queryFilter = new OrchestrationStatusQueryCondition
            {
                RuntimeStatus = new[]
                {
                    OrchestrationRuntimeStatus.Terminated
                },
                CreatedTimeFrom = DateTime.UtcNow.Subtract(TimeSpan.FromDays(999)),
                CreatedTimeTo = DateTime.UtcNow.Subtract(TimeSpan.FromDays(1)),
                PageSize = 100,
            };

and produces empty results
{
    "durableOrchestrationState": [],
    "continuationToken": null
}

i cannot delete the zombies - please advise

**Comment by ConnorMcMahon** [comment]
In general, you should not delete, rename, or disable functions for in-flight orchestrations without following [our versioning techniques](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-versioning). That being said, we should expect that people may accidentally do this, and end up in  bad state.

I think this ties in pretty closely with #1190. In general, we should probably automatically detect a situation where the function we are trying to execute no longer exists, and mark the orchestration as failed in that case.

@vigouredelaruse, I would recommend deploying again with some dummy version of these functions that just throw an exception. You will then either cause these orchestrations to fail with that exception, or possibly with a non-determinism exception. Either way, it will cause the orchestrations to no longer be in the running state.

**Comment by vigouredelaruse** [comment]
yeeeaah i remembered skimming right past the versioning documentation so my bad there. but thanks for triaging it at least to get that code path tidy
