### ISSUE TITLE
Azure durable function orchestration stuck in running state

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-functions-durable-extension#1748]
I've implemented a fan-out/fan-in pattern to download exactly 30000 files to blob storage, parse them into DataSets and then run some processing once all 30000 are downloaded and parsed. (In production there will be up to 500000 files)

### Expected behavior
The suborchestrator 'GetDocumentDetailDataSets' completes downloading the files and returns the 30000 data sets to the calling orchestrator. I've used a Task.WhenAll() to achieve this (code below).

### Actual behavior
The download happens sporadically, doesn't seem to scale and then just stops.
There are no exceptions thrown, no logs giving me a hint as to what has happened.
The orchestration just seems to fizzle out, over a period of about 30 hours it keeps sporadically coming back to life and downloading a few more files but then going quiet again.
I've left it for a few days and the sub orchestration GetDocumentDetailDataSets is still in 'running' state but nothing appears to be happening.
Downloading the contents of fadxrcrs0Instances shows all 30000 files have been downloaded successfully, but the GetDocumentDetailDataSets  never completed.

The  sub orchestration function:
```
        [FunctionName("GetDocumentDetailDataSets")]
        public static async Task<DataSet[]> GetDocumentDetailDataSets(
            //[ActivityTrigger] List<DocumentListItemModel> documentListItemModels,
            [OrchestrationTrigger] IDurableOrchestrationContext context,
            ILogger log
            )
        {
            log = context.CreateReplaySafeLogger(log);
            var dto = context.GetInput<GetDocumentDetailDTO>();

            log.LogInformation($"GetDocumentDetailDataSets starting");

            var retryOpts = new RetryOptions(new TimeSpan(0, 0, 0, 0, 100), 5)
            {
                BackoffCoefficient = 5,
            };


            var taskList = new List<Task<DataSet>>();
            var createdDate = dto.CreatedDate.ToString("yyyyMMddhhmmss");
            var fileName = "";
            var project = "";

            foreach (var report in dto.DocumentListItemModels)
            {
                try
                {
                    if (string.IsNullOrEmpty(project))
                    {
                        project = dto.Project;
                    }


                    fileName = $"/Archive/{dto.StoragePath}/{dto.Project}/DocumentDetail/{report.Int_Key}_{createdDate}.xml";

                    var outputMessage = new DocumentBlobParserMessage()
                    {
                        //DocumentType = queueItem.DocumentType,
                        Int_Key = report.Int_Key.ToString(),
                        Created = createdDate,
                        Project = dto.Project,
                        StoragePath = dto.StoragePath,
                        DetailBlobFileName = fileName,
                        SessionKey = dto.SessionKey
                    };

                    log.LogInformation($"GetDocumentDetailDataSets calling DownloadandParseDocumentDetail File: {fileName}");
                    taskList.Add(context.CallSubOrchestratorWithRetryAsync<DataSet>("DownloadAndParseDocumentDetail", retryOpts, outputMessage));

                }
                catch (Exception ex)
                {
                    log.LogError($"GetDocumentDetailDataSets failed DownloadandParseDocumentDetail File: {fileName}");
                }

            }

            log.LogError($"GetDocumentDetailDataSets waiting for all tasks to complete");
            var dataSetsArray = await Task.WhenAll(taskList);
            log.LogError($"GetDocumentDetailDataSets all tasks to complete");
            return dataSetsArray;
        }

```

### Known workarounds
Running with a smaller dataset (tested up to 1000 files) works fine

### App Details

.Net Core 3.1
Microsoft.Azure.Functions.Extensions v1.1.0, 
Microsoft.Azure.WebJobs.Extensions.DurableTask v2.4.1
Microsfot.Net.Sdk.Functions v3.0.11

- **Azure Functions runtime version (1.0 or 2.0)**: ~3

- **Programming language used**: C#

### If deployed to Azure

- **Timeframe issue observed**: GetDocumentDetailDataSets was created 2021-03-22T08:09:34.305Z
- **Function App name**: fa-d-lxr-crs01
- **Function name(s)**:    
Durable function: SplitDocumentListFunction
Orchestrations: DocumentDetailOrchestrator
SubOrchestration: GetDocumentDetailDataSets (this is the one which doesnt complete)

- **Azure region**: Australia East
- **Orchestration instance ID(s)**: 6821c8b2bf2b46a1ba05f46e6de9d837:1 (GetDocumentDetailOrchestrator partitionID)
- **Azure storage account name**: sadlxrauecrs01

**Comment by cgillum** [comment]
FYI @ConnorMcMahon since I know you were investigating another report of sub-orchestration issues.

**Comment by vigouredelaruse** [comment]
what do the azure monitor graphs look like for this deployment? what is the profile of memory use, network traffic, disk etc?

**Comment by ConnorMcMahon** [comment]
Sorry for the delay here, investigating now.

**Comment by ConnorMcMahon** [comment]
@RDavis3000 

At 3/22 ~9 AM UTC, it looks like your application has both high CPU usage and memory usage. This lead to a couple of different consequences:

- Our lease renewal thread on some of the workers that is supposed to run every 10 seconds didn't run for 1.5 minutes. Therefore it could not attempt renew the lease (or see that it no longer renewed the lease). This lead to two workers trying to execute `6821c8b2bf2b46a1ba05f46e6de9d837:1` at the same time, which is known as "split brain". In rare cases, this can lead to data corruption, but there were enough other issues going on with the app at this time I couldn't validate whether this happened or not.
- At some point, the app's memory consumption was regularly exceeding the 1.5 GB maximum that the consumption plan allows, causing the app to get recycled. 

This looks like it happens through around 9:45 AM UTC and then the instance is stopped processing for a couple of day, until we see a brief period of similar memory issues at 2021-03-24 10:15 UTC.

Finally, starting at ~2021-03-25 07:00:00 UTC, it looks like you disabled the suborchestration function, causing us to endlessly loop through the messages still scheduled on the taskhub.

**Action Items:**
- You can easily avoid disabling an orchestrator (or activity/entity function for that matter) while there are still in-flight operations that need to be done. We do have work tracked against an upcoming release to better handle this scenario so the events do not get repeatedly processed (#1190)
- Memory consumption for your application needs to go down. In general, this is often a problem for large fan-out/fan-in operations like this. It is worth noting that we recently made changes to our concurrency thresholds for Consumption apps in v2.4.2, and I suspect that this would greatly help with the high memory and high CPU consumption on your app. It's worth noting that this may not fix the problem entirely, as we still need to load the entire history into memory at some point, but you can reduce concurrency even further or try passing around references to your data if that still doesn't help (see #1682 for discussion around a feature that will make this easier in the near future).
- Our leasing logic needs to account for the fact that high CPU usage may interfere with a worker's ability to detect when it has lost a lease to help prevent split brain.
