### ISSUE TITLE
Support APPLICATIONINSIGHTS_CONNECTION_STRING for distributed tracing

### ISSUE THREAD

**Issue by guythetechie** [Azure/azure-functions-durable-extension#1752]
Thanks for implementing distributed tracing with Durable Functions - much appreciated!

As it stands though, it seems this feature requires the APPINSIGHTS_INSTRUMENTATIONKEY variable to work. Can't debug without setting it (#1694), and a deployed function that tries to use distributed tracing without specifying the variable gives this error:

![image](https://user-images.githubusercontent.com/31325620/112740697-23c07000-8f4d-11eb-886f-d8601d2407ce.png)

Requiring this prevents us from using distributed tracing in environments where the instrumentation key isn't sufficient (sovereign clouds come to mind). The [APPLICATIONINSIGHTS_CONNECTION_STRING variable](https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=net), on the other hand, covers more scenarios and is supported by Azure Functions without extra configuration.

I'm not sure how Durable Functions distributed tracing works behind the scenes, but if it just taps into Azure Functions's support for Application Insights, it may be trivial to implement this. Of course, things are often more complex than they appear at first glance...

Thanks for the consideration!

**Comment by guythetechie** [comment]
Did a bit more digging, and it looks like setting both APPINSIGHTS_INSTRUMENTATIONKEY and APPLICATIONINSIGHTS_CONNECTION_STRING does the trick. As per [these release notes](https://github.com/Azure/azure-functions-host/releases/tag/v2.0.12998), Azure Functions will prioritize the connection string variable and use the instrumentation key as a fallback.

I suppose the ask now is to drop the APPINSIGHTS_INSTRUMENTATIONKEY requirement for distributed tracing debugging and deployment, at least if the APPLICATIONINSIGHTS_CONNECTION_STRING variable is set. This may already be covered by the discussion in #1694, so happy to have this marked as a duplicate.

Thanks!

**Comment by ConnorMcMahon** [comment]
I think this ticket is likely a super set of #1694, but we will track both until we have a chance to investigate that to make sure.

**Comment by mauve** [comment]
`APPINSIGHTS_INSTRUMENTATIONKEY` is deprecated in favor of `APPLICATIONINSIGHTS_CONNECTION_STRING`, are there any plans to support connection strings? (refer: https://docs.microsoft.com/en-us/azure/azure-monitor/app/sdk-connection-string?tabs=net#overview)

**Comment by bachuv** [comment]
`APPLICATIONINSIGHTS_CONNECTION_STRING` is supported in Durable Functions Distributed Tracing V2.
