### ISSUE TITLE
FetchLargeMesssagesAutomatically not respected for Orchestrations in pending state

### ISSUE THREAD

**Issue by ConnorMcMahon** [Azure/azure-functions-durable-extension#1786]
### Description
As discussed [here](https://github.com/Azure/azure-functions-durable-js/issues/254), even when `FetchLargeMessagesAutomatically` is set to `true` (the default experience), IDurableClient.GetStatusAsync() returns a link to a large message instead of the large message itself when the data exceeds the ~45KB limit for queues/tables.

### Current Behavior 
When a 100 KB string is returned as orchestrator output and FetchLargeMessagesAutomatically is true, a link to the blob containing that message is returned in IDurableClient.GetStatusAsync().

### Expected Behavior
When a 100 KB string is returned as orchestrator output and FetchLargeMessagesAutomatically is true, the raw message is returned in IDurableClient.GetStatusAsync().

**Comment by scale-tone** [comment]
Any news on this, @ConnorMcMahon ?
I can see it was assigned to v2.5.1 milestone. Was it anyhow fixed in that version?

**Comment by ConnorMcMahon** [comment]
Sorry @scale-tone, didn't have time to get this into 2.5.1.

I will push it to our next release.

**Comment by ConnorMcMahon** [comment]
Interestingly, the scope of this bug seems limited. 

So it appears that the issue is that while the orchestration is still in the pending state, the Input is of the form: `<instance-id>/message-<message-id>-ExecutionStarted.json.gz`

However, once it moves from `Pending` to `Running` (or possibly from `Pending` to `Completed`), we use the history table version of the blob of the form `https://<taskhub>.blob.core.windows.net/testhubname-largemessages/<instance-id>/history-<taskid>-ExecutionStarted-Input.json.gz`.

FetchLargeMessagesAutomatically only works for absolute URIs, so it doesn't fetch while the orchestration is still pending. I think if we write the entire queue message blob URL instead of the relative path there, we would solve this bug.

**Comment by ConnorMcMahon** [comment]
Here is a fix: https://github.com/Azure/durabletask/pull/607.

**Comment by scale-tone** [comment]
@ConnorMcMahon , looks like you've discovered a different issue (which is an issue nevertheless).

In my original [#254](https://github.com/Azure/azure-functions-durable-js/issues/254) I was concerned aboud *Entities*, not orchestrations. For entities with large state GetStatusAsync() still returns absolute links instead of actual state in `Input` field. I still have an example of such entity, see coordinates in my original bug. That one has a state of around 80K symbols.

**Comment by ConnorMcMahon** [comment]
@scale-tone, I am reframing this issue to be about the pending orchestration bug, and will reply on your original ticket.

**Comment by scale-tone** [comment]
Did this also not make it into v2.6.0 ? :(

**Comment by cgillum** [comment]
From what I can tell, https://github.com/Azure/durabletask/pull/607 covers this issue and made it in for v2.6.0.

(Connor is currently on extended leave and I don't expect he'll be monitoring these GitHub issues).
