### ISSUE TITLE
Scaling in consumption plan doesn't work when using different storage account

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-functions-durable-extension#179]
My function app is deployed on a consumption plan and in the appsettings the connection string for AzureWebJobsStorage and AzureWebJobsDashboard point to storage account A.

In the host.json I use the following settings:
`"durableTask": {
    "AzureStorageConnectionStringName" : "DurableFunctions" 
  }`

In the appsettings I have configured the connection string DurableFunctions to storage account B.

This setup works, the durable functions are executed, but when I use a fan-out scenario with 400+ jobs no additional servers are provisioned. When I remove the AzureStorageConnectionStringName setting from host.json, the fan-out works as expected (a total of 12 servers is provisioned).
It seems like the Azure Functions scale controller doesn't monitor the work-item queue in storage account B

**Comment by cgillum** [comment]
I think you may be right that the scale controller probably isn't considering the alternate connection string. Thanks for reporting this. We'll take a look.

**Comment by mlankamp** [comment]
Found an additional problem with this configuration, because of scaling issues you are required to use AzureWebJobsStorage connection. But because of the way slots are handled in Azure functions, my secondary slot uses the same connection.

**Comment by cgillum** [comment]
Can't you just specify a different value for AzureWebJobsStorage across the different slots (and make them slot sticky)?

**Comment by mlankamp** [comment]
Thats what I did, but on a swap the values are reset. I will try again later
