### ISSUE TITLE
Durable Function TaskHub Supports Managed Service Identity to connect to storage

### ISSUE THREAD

**Issue by michc-msft** [Azure/azure-functions-durable-extension#1793]
From the docs I've seen, currently Durable Function Taskhubs support a connectionName value or uses the default AzureWebJobsStorage value to connect to the storage account that houses the TaskHub. Using connection strings is not ideal for us because we're being forced to auto-rotate storage connection strings every 2 years, which makes maintaining and scaling Durable Functions quite hard. There's an [open item](https://github.com/Azure/azure-functions-host/issues/6423) for Azure Functions themselves to support Managed Identity, and I'd love to see the same thing for Durable Functions.

**Comment by ConnorMcMahon** [comment]
This is in the plans, but I don't think we have an existing work item for it yet.

Relies on this work item first: https://github.com/Azure/durabletask/issues/516.

**Comment by mauve** [comment]
Now that azure functions supports using managed identity to talk to storage, by setting `AzureWebJobsStorage__accountName` instead of `AzureWebJobsStorage`, we are currently blocked to switch to managed identity because of durable functions.

Is there a timeline for adding this support?

**Comment by cgillum** [comment]
@mauve the work to enable managed identity for our Azure Storage provider is a top priority for the team and will be done by no later than the end of this calendar year.

As an aside for folks who may be interested, Durable Functions also supports a [SQL Server storage provider](https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-storage-providers#mssql) for Durable Functions (currently in public preview), which currently supports managed identities for Azure SQL Database.

**host.json**
```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "storageProvider": {
        "type": "mssql",
        "connectionStringName": "SQLDB_Connection_NoCreds",
        "azureManagedIdentityEnabled": true,
        "azureManagedIdentityResource": "https://database.windows.net/.default"
      }
    }
  }
}
```

**Comment by Joehannus** [comment]
Is there an update regarding this functionality now that the storage extension is publically available. We switched to vnet integration in our Azure Functions and it looks as if using managed identities is mandatory for connections to vnet integrated data services. But we have regular as well as durable functions in our project. And it seems using managed identities is still not suppoted in durable functions.

**Comment by cgillum** [comment]
Adding @AnatoliB

**Comment by wsugarman** [comment]
@cgillum I've created a PR with my first swing at this functionality. Let me know what you think!

**Comment by dxynnez** [comment]
Hi guys, I have a quick question - since the new storage SDK changed the default message encoding to none, what would be encoding for the storage client that durable taskhub uses? Would changing the queues extension's '[messageEncoding](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue#hostjson-settings)' affect the durable taskhub's storage client? If not, would there be a separate setting to support changing the encoding method for durable taskhub's storage queue?
