### ISSUE TITLE
Detector to warn of large orchestration histories

### ISSUE THREAD

**Issue by davidmrdavid** [Azure/azure-functions-durable-extension#1795]
**Is your feature request related to a problem? Please describe.**
Customers are have to be mindful of the size of activity return values when writing orchestrations, as these are "cached" in our orchestration history and, in the presence of very large values, the orchestration history can blow up to the point of creating out-of-memory exceptions. We recently got a case like this, and customers don't readily have a way of diagnosing this.

**Describe the solution you'd like**
A detector on our internal dashboards and, ideally, also in the customer portal, that tracks an orchestration's history memory usage / size over time. It can help to warn customers of bad practices, and recommend mitigations / alternative designs.

Chances are that this will need an extra layer of telemetry, maybe an optional one. I also wonder if the detector can help catch this  issue, although I don't think we can detect this statically.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ConnorMcMahon** [comment]
This actually already exists thanks to @cgillum.
