### ISSUE TITLE
Fix support for ETW tracing on linux and custom backends

### ISSUE THREAD

**Issue by sebastianburckhardt** [Azure/azure-functions-durable-extension#1796]
### Description

There's a bug in the linux trace collection which means ETW event sources inside custom backends are not collected.

The problem is in EventSourceListener.cs. Specifically, OnEventSourceCreated is called before the constructor EventSourceListener is called, thus the field durabilityProviderEventSourceName has not been initialized yet. So the comparison always fails.

**Comment by ConnorMcMahon** [comment]
@bachuv, I believe this is related to your recent change. We will want to make sure we fix this before we have a bundles release that could break linux logging for existing Linux consumption customers.

**Comment by bachuv** [comment]
@ConnorMcMahon It looks like there is a delay for when `durabilityProviderEventSourceName` gets assigned so any calls to `OnEventSourceCreated` before that will evaluate `eventSource.Name == this.durabilityProviderEventSourceName` as false. Before updating this condition to use `durabilityProviderEventSourceName`, there were comparisons between `eventSource.Name` and hard coded event source name values (e.g. "DurableTask-AzureStorage"). The reason we added this field was to support a variety of durability providers and allow customers to configure their own durability provider. Maybe we go back to having a list of hard coded values for supported durability providers and if a customer uses another durability provider then they set an additional environment variable with the event source name?
