### ISSUE TITLE
Create separate "Instances" table for storing orchestration status

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#183]
Separate from the **History** table, which should introduce an **Instances** table. Each row in this table will represent a single orchestration instance in the task hub. Each row should have all the information necessary to make the `GetStatusAsync` API work (with the exception of history querying).

This will provide three primary architectural benefits:

1. The `StartNewAsync` API does not need to wait for the orchestrator to actually start and persist.
2. Status query APIs can be made faster, because they don't need to scan the history table.
3. Allows users to easily see the status of all orchestrations in a single view.

One way to think of this work is that it gives Durable Functions a more CQRS-style architecture, where the runtime relies on the **History** table and queries can go against the **Instances** table.

**Comment by gled4er** [comment]
Hello @cgillum ,

Thank you very much for providing additional details and assigning the issue to me.

Thank you!

**Comment by cgillum** [comment]
This has been checked-into **dev** and will go out with the next release.
