### ISSUE TITLE
Longer running time after updating to version 2.4.3

### ISSUE THREAD

**Issue by sasoripathos** [Azure/azure-functions-durable-extension#1842]
### Description
When using version 2.4.1,  my durable function took about 8-9 mins to finish. After updating to version 2.4.3, the same durable function took about 50 mins to finish.

### Expected behavior
The time to complete the same durable function should not have much difference after updating the package version.

### Actual behavior
The time to complete the same durable function increased dramatically .

### Relevant source code snippets
Company code, cannot share.

### Known workarounds
Revert back to version 2.4.1

### App Details

- **Durable Functions extension version**: 2.4.1, 2.4.3
- **Azure Functions runtime version**: 3.0
- **Programming language used**: C#

### Screenshots
Running time using version 2.4.3
![image](https://user-images.githubusercontent.com/21251857/118850830-27aea580-b89f-11eb-9e2f-52ca4ad5bcbe.png)
![image](https://user-images.githubusercontent.com/21251857/118851794-25008000-b8a0-11eb-84e9-26383834c2f5.png)

Running time using version 2.4.1
![image](https://user-images.githubusercontent.com/21251857/118850955-490f9180-b89f-11eb-93d2-4bd3ddeb8b02.png)
![image](https://user-images.githubusercontent.com/21251857/118851640-fd111c80-b89f-11eb-82a0-06ae26ca1b56.png)

### If deployed to Azure
- **Timeframe issue observed**: updated to version 2.4.3 on May 13 and then issue observed, reverted to version 2.4.1 on May 18
- **Function App name**: GetGroupsFromKusto-FunctionApp
- **Azure region**: East US 2
- **Orchestration instance ID(s)**: example using 2.4.1: _e451c3526c9544439e3cff9b23994f90_; example using 2.4.3: _22820c87de64475bb5eab32cd11ba097_
- **Azure storage account name**: storage account for function app: _groupfromkustosaprod_; durable task storage provider: _groupfromkustodtsaprod_

**Comment by mpaul31** [comment]
@sasoripathos Is this app running on consumption? If so, the some of the scaling defaults have been toned down a bit, so you might want to look into tweaking them a bit.

https://github.com/Azure/azure-functions-durable-extension/pull/1706

**Comment by cgillum** [comment]
FYI @davidmrdavid

**Comment by davidmrdavid** [comment]
Thanks for the ping @cgillum.

Hi @sasoripathos, thank you for reaching out. I'll be taking a look at your logs internally. In the meantime, can you tell me a bit more about your application's usage patterns? Is it a simple fan-out-fan-in scenario, or how would you describe a high-level sketch of your orchestration? Thanks!

**Comment by sasoripathos** [comment]
@mpaul31 Yes, this app is running on Consumption plan. There is no explicit setting in host.json about `controlQueueBufferThreshold` and `maxConcurrentOrchestratorFunctions`. I may tweak them and test if it helps

**Comment by sasoripathos** [comment]
@davidmrdavid This durable function first has two chaining activities to read data, then fan out/fan in on each piece of data which meets a condition.

**Comment by davidmrdavid** [comment]
Thank you for the quick response @sasoripathos!

Looking at your application's logs, it appears to me that all of your activities finished quite quickly with version 2.4.3, but that the orchestrator took much longer to acknowledge that they had all completed. This most likely due to the decrease in the default value of `controlQueueBufferThreshold` as of version 2.4.3.  This gives me reason to reconsider the new default value we chose for it, so I'm sorry to hear it had a negative impact for your use case.

@sasoripathos, it would help us to perform two experiments around tweaking  `controlQueueBufferThreshold`.

A first experiment to try setting it to `256`  (the previous default value) and see if that speeds up your orchestration to a level comparable to what it was before 2.4.3. 

Then, if possible, it would help me to know what performance you get with a more conservative value of `96`, which was another value we considered as a default in: https://github.com/Azure/azure-functions-durable-extension/pull/1706

**Comment by sasoripathos** [comment]
@davidmrdavid Thanks for your advice! I will try and let you know the result in the next few days.

**Comment by sasoripathos** [comment]
@davidmrdavid I have tried out the 2 settings you suggested. With `controlQueueBufferThreshold = 256` in 2.4.3, the finishing time of my orchestration is about the same as using 2.4.1. (sample instance Id: _698b9ca66a214f7a892c4433c56125dc_)
![image](https://user-images.githubusercontent.com/21251857/119373142-193d0100-bc86-11eb-856c-45c1a38d12c1.png)

When `controlQueueBufferThreshold = 96` in 2.4.3, the finish time is about 18 mins. (sample instance Id: _0b64f878f37b459ab0ad119bd17a43e2_ )
![image](https://user-images.githubusercontent.com/21251857/119373527-80f34c00-bc86-11eb-92ed-51ac62129502.png)

**Comment by davidmrdavid** [comment]
Thank you @sasoripathos.
It seems then that perhaps the decrease in `controlQueueBufferThreshold` in 2.4.3 was too aggressive. Just to confirm, you're unblocked now that we've found a way to bring the performance back to the expected runtime, correct? Just making sure!

In the meantime, we'll look into potentially increasing the default value of `controlQueueBufferThreshold` to mitigate issues moving forward. Just an FYI to @ConnorMcMahon.

**Comment by sasoripathos** [comment]
Thank you @davidmrdavid. I am unblocked. The finishing time of this orchestration doesn't have much impact on my current use case since each activity finishes quickly. But I agree that the adjustment in 2.4.3 was too aggressive. It slows down the process in many use cases where users wait for the orchestration completion.

If possible, can I know when the potential increment of `controlQueueBufferThreshold` will be released?

**Comment by davidmrdavid** [comment]
Good to hear!
@sasoripathos, as for an ETA, that's hard to guesstimate, so I'd prefer not to give any specific timeframes.

The biggest challenge would be whether or not that _potential_ change would be bundled with a regularly-scheduled release, meaning that it would take a few week's time before being released, or if we'd release it as a hot-patch, which means I could release it as soon as it's ready.

I'll have to sync with @ConnorMcMahon about it. I'll look to keep this thread updated with our plans.

**Comment by ConnorMcMahon** [comment]
Fixed in upcoming 2.5.0 release
