### ISSUE TITLE
Using DurableFunctions.TypedInterfaces as a NuGet package breaks unit tests

### ISSUE THREAD

**Issue by KeesV** [Azure/azure-functions-durable-extension#1867]
### Description
When using the `DurableFunctions.TypedInterfaces` NuGet package (version 0.1.0-preview), the generated interfaces are not mockable. However, when referencing the project directly (taking the source from this Git repo), everything works as expected. I first stumbled upon this issue in my own project, but the example project from this repo exhibits the same behavior.

### Expected behavior
I've been using the example solution at `src/DurableFunctions.TypedInterfaces/WebJobs.Extensions.DurableTask.CodeGen.sln` in this repo. In that solution:
- `DurableFunctions.TypedInterfaces.Example` has a project reference to `DurableFunctions.TypedInterfaces`, like this: 
```xml
<ProjectReference Include="..\sourcegenerator\DurableFunctions.TypedInterfaces.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
```
- `DurableFunctions.TypedInterfaces.Examples.Test` has a project reference to `DurableFunctions.TypedInterfaces.Example`, and contains a unit test that mocks the interface generated by `DurableFunctions.TypedInterfaces`
Mocking works, and the tests run correctly.

Now, I remove the project reference to `DurableFunctions.TypedInterfaces` from `DurableFunctions.TypedInterfaces.Example`, and instead add a Packagereference like this:
```xml
<PackageReference Include="DurableFunctions.TypedInterfaces" Version="0.1.0-preview" />
```
After this, the test project does not compile anymore. Expected behavior: it still works as before.

### Actual behavior
After replacing the project reference with a package reference, the test project does not compile anymore. Error messages:
```
Error CS1061 'ITypedDurableActivityCaller' does not contain a definition for 'Add' and no accessible extension method 'Add' accepting a first argument of type 'ITypedDurableActivityCaller' could be found (are you missing a using directive or an assembly reference?)	DurableFunctions.TypedInterfaces.Examples.Test (netcoreapp3.1)	D:\Git\azure-functions-durable-extension\test\CodeGen.Example.Test\CalculatorTests.cs

Error CS1503 Argument 1: cannot convert from 'Microsoft.Azure.WebJobs.Extensions.DurableTask.TypedInterfaces.ITypedDurableOrchestrationContext [DurableFunctions.TypedInterfaces.Examples.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289]' to 'Microsoft.Azure.WebJobs.Extensions.DurableTask.TypedInterfaces.ITypedDurableOrchestrationContext [DurableFunctions.TypedInterfaces.Example, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]'	DurableFunctions.TypedInterfaces.Examples.Test (netcoreapp3.1)	D:\Git\azure-functions-durable-extension\test\CodeGen.Example.Test\CalculatorTests.cs
```

### Relevant source code snippets
Code used for mocking:
```csharp
var mockActivityCaller = new Mock<ITypedDurableActivityCaller>();
mockActivityCaller.Setup(c => c.Add(It.IsAny<int>(), It.IsAny<int>())).ReturnsAsync((int a, int b) => a + b);
```
I forked this repo and published a branch that demonstrates the problem:
https://github.com/KeesV/azure-functions-durable-extension/tree/typedinterfaces-nuget-bug/src/DurableFunctions.TypedInterfaces

### Known workarounds
Don't use a PackageReference for `DurableFunctions.TypedInterfaces`, but instead copy the project from this git repo and include that in my own project as a ProjectReference.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.5.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots
_Not relevant_

### If deployed to Azure
_Not relevant_

**Comment by alvpickmans** [comment]
I just came across the same issue a few minutes ago, first was a "oh damn" reaction but then I remembered `ITypedDurableOrchestrationStarter`, `ITypedDurableOrchestrationCaller` and `ITypedDurableActivityCaller` are marked as partial. My immediate use is to test the initialisation of a new Orchestration, so I extended `ITypedDurableOrchestrationStarter` with a custom interface that has the same contract and use that as input argument instead. 
I am testing a handler and not the actual Durable Orchestration Function, so I can pass in `ITypedDurableOrchestrationStarter.Orchestrations` to my handler. This solution woudn't work to test the actual durable orchestration function.

```csharp
using System.Threading.Tasks;

namespace Microsoft.Azure.WebJobs.Extensions.DurableTask.TypedInterfaces
{

    public interface ICustomOrchestrationStarter
    {
        Task<string> StartCustomOrchestration(CustomRequest request, string instance = null);
    }

    public partial interface ITypedDurableOrchestrationStarter : ICustomOrchestrationStarter
    {
    }
}

```

This is a temporary solution until this issue gets some attention, as the drawback is any change on the generated interfaces will need to be reflected on the custom one.

**Comment by cgillum** [comment]
(Revisiting issues that fell through the cracks)

This version of typed interfaces was a community contribution that our team hasn't been actively maintaining. We're thinking of deprecating this feature since we have a fully supported replacement in the .NET Isolated worker, which is intended to be the future of DF in .NET anyways.

Let us know if you feel strongly about this issue. Otherwise, I think we'd prefer to leave it up to the community to provide a PR that addresses this issue.

**Comment by KeesV** [comment]
Thanks for the feedback @cgillum ! For us it'd be fine to deprecate `DurableFunctions.TypedInterfaces`. It seemed like a promising thing back then, but we've actually moved away from it due to (among others) this issue and the perceived lack of active maintenance on it. It's good to get some confirmation on that 👍 .

**Comment by alvpickmans** [comment]
Agree, I moved from this approach a while ago and if the Isolated model is the way to go, more than welcomed.

Not that I have any saying on this matter though!😅
