### ISSUE TITLE
Typed Interfaces: Activity input parameters are not generated if they are part of the method signature

### ISSUE THREAD

**Issue by cjaliaga** [Azure/azure-functions-durable-extension#1870]
### Description
On Activities, the input parameters can be defined via `IDurableActivityContext.GetInput<T>()` and also as part of the method signature:

```csharp
[FunctionName("DurableFunctionsOrchestrationCSharp1_HelloParam")]
public static string SayHelloWithParam([ActivityTrigger] string name, ILogger log)
{
    log.LogInformation($"Saying hello to {name}.");
    return $"Hello {name}!";
}
```
On the latter, when using TypedInterfaces, the generated Activity caller doesn't contain any parameter:

```csharp
/// <summary>
/// See <see cref = "DurableTypedInterfacesTests.DurableFunctionsOrchestrationCSharp1.SayHelloWithParam"/>
/// </summary>
Task<string> DurableFunctionsOrchestrationCSharp1_HelloParam();
```
### Expected behavior
The ActivityCaller generated by the SourceGenerator should also generate the activity input parameters if they are defined as part of the method signature (the one marked with the `ActivityTrigger` attribute):

```csharp
[FunctionName("DurableFunctionsOrchestrationCSharp1_HelloParam")]
public static string SayHelloWithParam([ActivityTrigger] string name, ILogger log)
{
    log.LogInformation($"Saying hello to {name}.");
    return $"Hello {name}!";
}
```

```csharp
/// <summary>
/// See <see cref = "DurableTypedInterfacesTests.DurableFunctionsOrchestrationCSharp1.SayHelloWithParam"/>
/// </summary>
Task<string> DurableFunctionsOrchestrationCSharp1_HelloParam(string name);
```

### Actual behavior
The generated code doesn't contain any input parameters:

```csharp
/// <summary>
/// See <see cref = "DurableTypedInterfacesTests.DurableFunctionsOrchestrationCSharp1.SayHello"/>
/// </summary>
Task<string> DurableFunctionsOrchestrationCSharp1_HelloParam();
```

### Relevant source code snippets
Created a sample reproducing the issue: https://github.com/cjaliaga/DurableTypedInterfacesTests/

### Known workarounds
Defining the input parameters using `IDurableActivityContext.GetInput<T>()`:

```csharp
[FunctionName("DurableFunctionsOrchestrationCSharp1_Hello")]
public static string SayHello([ActivityTrigger] IDurableActivityContext context, ILogger log)
{
    var name = context.GetInput<string>();
    log.LogInformation($"Saying hello to {name}.");
    return $"Hello {name}!";
}
```

```csharp
/// <summary>
/// See <see cref = "DurableTypedInterfacesTests.DurableFunctionsOrchestrationCSharp1.SayHello"/>
/// </summary>
Task<string> DurableFunctionsOrchestrationCSharp1_Hello(string name);
```

### App Details

- **Durable Functions extension version**: 2.5.0
- **Azure Functions runtime version**: 3.0.15584
- **Programming language used**: C#

**Comment by jdluzen** [comment]
I've also ran into this. Thanks for the workaround. More info: the workaround needs `context.GetInput<...>()` on its own line, otherwise it won't detect it either.

**Comment by cgillum** [comment]
(Revisiting issues that fell through the cracks)

This version of typed interfaces was a community contribution that our team hasn't been actively maintaining. We're thinking of deprecating this feature since we have a fully supported replacement in the .NET Isolated worker, which is intended to be the future of DF in .NET anyways.

Let us know if you feel strongly about this issue. Otherwise, I think we'd prefer to leave it up to the community to provide a PR that addresses this issue.

**Comment by cjaliaga** [comment]
Sounds good. From my point of view the replacement in the .NET Isolated worker is very powerful and for this issue we have a workaround already.
