### ISSUE TITLE
Accessing durable entities within Console Application

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-functions-durable-extension#1880]
### Discussed in https://github.com/Azure/azure-functions-durable-extension/discussions/1877

<div type='discussions-op-text'>

<sup>Originally posted by **ddobric** June 20, 2021</sup>
When working with durable task framework inside of the console application, we can easily create the client and do the following:
```csharp
var client =new ServiceBusOrchestrationService(serviceBusConnectionString, taskHubName, instanceStore, null, null);
var client = new TaskHubClient(orchestrationServiceAndClient);            
var instance = taskHubClient.CreateOrchestrationInstanceAsync(typeof(HelloOrchestration), new Random().Next().ToString(), null).Result;
```

Durable Entities also offers a similar way by using  *IDurableEntityClient*. The *IDurableEntityClient* is designed for injection, which works fine in frameworks like ASP.NET and AzFunctions. I tried to create the instance of the IDurableEntityClient in the same way as the instance of the TaskHubClient shown in the code above and find it very difficult.

For this reason, I'm asking what is the right way to instantiate the IDurableTaskClient? We are missing that part of the documentation at all.

For example:

~~~csharp
void Main(string[] args)
{
       IDurableEntityClient client = new XYZ(ConfigXyz);
       client...
}
~~~

By following this, it would also be helpful to provide a document that shows how all of IXYClients in DurableFunction-world can be used inside of the console application including the configuration of all existing backend providers.

Thanks</div>

**Comment by ConnorMcMahon** [comment]
This should be more possible with the ability we added in v2.4.0 (or so) that allows you to inject a IDurableClientFactory using dotnet core dependency injection.

You just need to follow the documentation for adding the `IDurableClientFactory` [to your service collection](https://github.com/Azure/azure-functions-durable-extension/blob/dev/samples/todolist-aspnetcore/Startup.cs#L27) as shown in our sample, and then you can access an IDurableClientFactory from that service collection. Our sample shows this for a ASP.NET Core application, but you can tweak it to [support DI for console apps](https://andrewlock.net/using-dependency-injection-in-a-net-core-console-application/).
