### ISSUE TITLE
AddDurableTask does not resolve on a project targeting .NET FX 4.8

### ISSUE THREAD

**Issue by jayman-dalal** [Azure/azure-functions-durable-extension#1909]
### Description
Looking to use DurableTask Framework with Azure WebJobs targeting .NET Fx 4.8. Following instructions from:
* https://docs.microsoft.com/en-us/azure/app-service/webjobs-sdk-how-to
* https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-webjobs-sdk

My read of from the link and samples out there is that HostBuilder is the choice of adding DurableTask Fx to console applications and JobHostConfiguration is the older way. But neither of them seems to be resolving when we use the latest Microsoft.Azure.WebJobs.Extensions (4.0.1), Microsoft.Azure.WebJobs.Extensions.Storage(4.0.4) and Microsoft.Azure.WebJobs.Extensions.DurableTask (2.5.1), if the target framework is 4.8. If I change the target framework to .NET Core 3.1 or .NET 5.0, AddDurableTask with aforementioned versions of packages resolves on HostBuilder. Is this expected?

### Relevant source code snippets
```csharp
// insert code snippet here
var builder = new HostBuilder();
  builder.UseEnvironment(EnvironmentName.Development);
  builder.ConfigureWebJobs(b =>
  {
      b.AddAzureStorageCoreServices();
      b.AddAzureStorage();
      b.AddTimers();
      b.AddDurableTask(o =>
      {
          o.HubName = "MyTaskHub";
          o.StorageProvider = new Dictionary<string, object>() { ["ConnectionStringName"] = "AzureWebJobsStorage" };
      });
  })
```

**Comment by cgillum** [comment]
If you're targeting .NET Framework, my recommendation is to use `JobHost`, as described here: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-webjobs-sdk#jobhost-code. It's old, but it's designed specifically to work with the full .NET Framework and is what we use for the Durable Functions automated tests that target the .NET Framework (specifically .NET 4.6.1).

In case it's useful, here is some of our test code that uses JobHost: https://github.com/Azure/azure-functions-durable-extension/blob/dev/test/FunctionsV1/PlatformSpecificHelpers.FunctionsV1.cs
