### ISSUE TITLE
IDurableClientFactory used within same orchestration service fails to Start new orchestration

### ISSUE THREAD

**Issue by alvpickmans** [Azure/azure-functions-durable-extension#1913]
### Description
Trying to use `IDurableClientFactory` as means to be injected and used to create an `IDurableClient`, representing the host orchestration service to initialise new orchestrations outside of the normal entry point from an azure function.

### Expected behavior
Creating a new `IDurableClient` from `_durableClientFactory.CreateClient(new DurableClientOptions{...})`, with options as `ConnectionString="Storage"`, `IsExternalClient = false` and `TaskHubName = "MyCustomHub"` (same as defined in host.json), should allow to start a new orchestration with `_durableClient.StartNewAsync()`

### Actual behavior
The created client throws an Object null exception when calling `_durableClient.StartNewAsync()`

### Relevant source code snippets
```csharp
var durableClient = _durableClientFactory(new DurableClientOptions{
    ConnectionName = "Storage",
    TaskHub = "MyCustomHub", // same as specified in host.json,
    IsExternalClient = false
});

await durableClient.StartNewAsync("customOrchestration", "instanceId1234", "input"); // <- this throws an Object null exception
```

### Known workarounds
No workaround, but it fails here https://github.com/Azure/azure-functions-durable-extension/blob/d8186d84c51a982929debf7b5b6186ca236d4822/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L137, being `this.config` null. 

It seems that `IDurableClientFactory` uses [this constructor](https://github.com/Azure/azure-functions-durable-extension/blob/d8186d84c51a982929debf7b5b6186ca236d4822/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L46) instead of the overload that accepts a `DurableTaskExtension` as input.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.5.1
- **Azure Functions runtime version (1.0 or 2.0)**:  3.0
- **Programming language used**: c#

**Comment by cgillum** [comment]
Tagging @bachuv

**Comment by cgillum** [comment]
@alvpickmans I'm not an expert in this area, but had a few clarifying questions:

1. You mentioned that you want to run this code outside the context of a function. Where exactly are you running this code?
2. Why did you specify `IsExternalClient = false`?  Does it work if you specify `IsExternalClient = true`?

**Comment by alvpickmans** [comment]
To clarify, with "outside the context of a function" I mean being able to use or inject an `IDurableClient` on a method not tagged as `[FunctionName]` and without the `[DurableClient]` attribute, but instead used within a command handler using mediator for example.

The below code is an example of an activity function using mediator to perform some actions (start another orchestration) on its handler. Last year I used a similar pattern but ended up adding an `IDurableClient` property into each command and passing it that way to handlers instead of using DI as I think `IDurableClientFactory` was not yet introduced.

From the xml docs, `IsExternalClient` is defined with `Indicate if the client is External from the azure function where orchestrator functions are hosted.`, so I assumed this flag determines the created client targets orchestrations on a different azure functions project deployment, not the current host instance. I've just tried now setting it to `true` and it works (see below).

<details>
  <summary>1. Orchestrations and activity functions </summary>

```csharp
public class Function1
    {
        private readonly IMediator _mediator;

        public Function1(IMediator mediator) => _mediator = mediator;


        [FunctionName(nameof(FirstOrchestration))]
        public async Task<string> FirstOrchestration(
            [OrchestrationTrigger] IDurableOrchestrationContext context,
            ILogger log)
        {
            var request = context.GetInput<string>();
            log.LogInformation($"Start message: {request}");

            var command = new StartOrchestrationCommand
            {
                Name = nameof(OrchestrationFromHandler),
                Input = "Los Pollos Hermanos"
            };

            var orchestrationId = await context.CallActivityAsync<string>(nameof(CallOrchestrationViaHandler), command);

            return $"Orchestration [{orchestrationId}] started";
        }

        [FunctionName(nameof(OrchestrationFromHandler))]
        public static async Task<string> OrchestrationFromHandler(
            [OrchestrationTrigger] IDurableOrchestrationContext context,
            ILogger log)
        {
            var request = context.GetInput<string>();
            log.LogInformation($"End message: {request}");
            return request;
        }


        [FunctionName(nameof(StartOrchestration))]
        public static async Task<HttpResponseMessage> StartOrchestration(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "orchestrations")] HttpRequestMessage req,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger log)
        {
            // Function input comes from the request content.
            string instanceId = await starter.StartNewAsync(
                nameof(FirstOrchestration),
                null,
                $"Test scheduled at {DateTime.UtcNow}");

            return starter.CreateCheckStatusResponse(req, instanceId);
        }

        [FunctionName(nameof(CallOrchestrationViaHandler))]
        public Task<string> CallOrchestrationViaHandler([ActivityTrigger] StartOrchestrationCommand command)
            => _mediator.Send(command);
    }
```
</details>

<details>
<summary>2. Command handler</summary>


```csharp
    public struct StartOrchestrationCommand : IRequest<string>
    {
        public string Name { get; set; }
        public object Input { get; set; }
    }

    public class StartOrchestrationHandler : IRequestHandler<StartOrchestrationCommand, string>
    {
        private readonly IDurableClient _client;

        public StartOrchestrationHandler(IDurableClient client) => _client = client;

        public Task<string> Handle(StartOrchestrationCommand request, CancellationToken cancellationToken)
            => _client.StartNewAsync(request.Name, null, request.Input);
    }
```
</details>

<details>
<summary>3. Startup</summary>


```csharp
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services
                .AddMediatR(typeof(Startup).GetTypeInfo().Assembly)
                .AddSingleton<IDurableClient>(provider =>
                     provider
                         .GetRequiredService<IDurableClientFactory>()
                         .CreateClient(new DurableClientOptions
                         {
                             ConnectionName = "Storage",
                             TaskHub = "MyCustomHub",
                             IsExternalClient = true
                         })
                );
        }
    }
```
</details>

**Comment by sebastianburckhardt** [comment]
What is suggested here seems to be related to #2365, and would be addressed by a solution to the latter.
