### ISSUE TITLE
PurgeInstanceHistoryAsync does not remove the old records from history

### ISSUE THREAD

**Issue by vany0114** [Azure/azure-functions-durable-extension#1915]
### Description
Hi guys, I'm trying to use the `PurgeInstanceHistoryAsync` but it does not work, I have a timer trigger to do so, but every time the function is fired it says: `Purged instance history data for 0 instance(s)` I'm wondering if it could be because of the fact that the history and instances tables don't have the default name:

![image](https://user-images.githubusercontent.com/12032625/129128852-b17fdee8-c1b1-4bbf-b61e-0848bc9a78c9.png)

The `TestHubNameHistory` and `TestHubNameInstances` are empty. We have another orchestrator (a Node JS one) in a different function app and different storage account and the `purgeInstanceHistoryBy` works as expected. The only difference I can see in terms of the storage account are the names of the history and instances tables:

![image](https://user-images.githubusercontent.com/12032625/129129126-6dfb3a29-bf16-4788-8542-c505ac339a3e.png)

### Expected behavior
I'd expect the old records in the history table is deleted, but it's not.

### Actual behavior
After executing the `PurgeInstanceHistoryAsync` always says: `Purged instance history data for 0 instance(s)` and after double-checking the `TestHubNameHistory` table I can see the old records there.

### Relevant source code snippets
```csharp
[FunctionName("PurgeOrchestratorHistory")]
public static Task Run([DurableClient] IDurableOrchestrationClient client, [TimerTrigger("30 13 21 * * *")] TimerInfo timerInfo, ILogger logger)
{
    return client.(
        DateTime.MinValue,
        DateTime.UtcNow.AddDays(-30),
        new List<OrchestrationStatus> { OrchestrationStatus.Completed });
}
```

### App Details

- **Durable Functions extension version**: 2.5.1
- **Azure Functions runtime version**: 3.0
- **Programming language used**: C#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Function App name**: infra-integrations-orchestrator
- **Function name(s)**: PurgeOrchestratorHistory
- **Azure region**: West US

**Comment by amdeel** [comment]
Hey @vany0114. Just to make sure I understand, you are expecting PurgeInstanceHistory to remove records from your TestHubName tables?

Your app is associated with the task hub starting with "infra" so it would be expected that PurgeInstanceHistory would be able to purge only from that task hub and not be able to purge instance history from the tables starting with "TestHubName."

**Comment by vany0114** [comment]
Hi @amdeel I just would expect that the `PurgeInstanceHistory` clean the history regardless of the table names, I don't even know why or how it internally named those tables, in this case I don't know why in one storage account it named the tables with the function app name (infra...History) and in the other one it was named the tables `DurableFunctionsHubHisory` or `TestHubNameHistory`, but the thing is that it is not cleaning the history, if you double-check you'll realize that the whole history is still there, even tho this function runs on a daily basis, could you help please?

**Comment by amdeel** [comment]
@vany0114 The tables are named based on the task hub name. Each app is associated with a task hub. This means that there is or was another app that used "TestHubName" as a task hub name associated with your storage account.

And, again, your app infra-integrations-orchestrator uses the task hub starting with "infra" so it only can delete history from the tables starting with "infra."

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-task-hubs?tabs=csharp

**Comment by vany0114** [comment]
@amdeel thanks for the reply, I get it, but why does the data is still in the "infra" tables then? When I run the `PurgeInstanceHistoryAsync`  it always says "Purged instance history data for 0 instance(s)"

**Comment by amdeel** [comment]
@vany0114 Does it purge instance history and report that it purged history data for 0 instances? Or are you claiming it is not purging instance history on your infra table when, given the parameters of PurgeInstanceHistory, there are valid records to delete?

Could you provide a specific timestamp when you are calling PurgeInstanceHistory, the expected time range of instances that are to be purged, and the specific results in your infra table that are not being purged?

**Comment by vany0114** [comment]
@amdeel actually I was reviewing our logs vis Application Insights earlier this morning and I found that for the first time the timer trigger got fired and it performs the purge. and as you can see in the image attached below it performed the deletion of the old records. 
![image](https://user-images.githubusercontent.com/12032625/130280132-1e5bf424-167c-458a-be3a-43ce4d9565ff.png)


However, looking at the tables it seems it left some records from February and March as you can see: 

![image](https://user-images.githubusercontent.com/12032625/130280328-086f655c-b0aa-43bc-8f30-09b5f0ed03c5.png)

![image](https://user-images.githubusercontent.com/12032625/130280354-746a64cc-ea32-424f-ad4c-adeb645dd7a1.png)

Other than that it worked pretty well. My question is why does the timer trigger never got fire before? (we're using this binding `[TimerTrigger("0 0 0 * * *")]`) or maybe it was getting triggered but was taking too long? but if so why didn't leave any trace?

![image](https://user-images.githubusercontent.com/12032625/130280563-a6e1f20a-80bf-4f63-ae57-bf400336fe0d.png)

And why didn't remove the records from February and March? As you can see in the code snippet I provided, we're only keeping the history from the prior month.

**Comment by amdeel** [comment]
It looks like you might have been running into a timeout issue by attempting to delete too many records. This is on our radar as a fix to redesign the purge API.

I'm closing this issue in favor of https://github.com/Azure/azure-functions-durable-extension/issues/2200

If you experience additional issues using the Purge API please open a new issue.
