### ISSUE TITLE
Microsoft.WindowsAzure.Storage.StorageException socket exceptions when writing to History Table

### ISSUE THREAD

**Issue by brrusino** [Azure/azure-functions-durable-extension#1919]
In one of our services running DTFx, we saw the following socket exceptions in our Kubernetes container logs:
```
Failed during intent acquisition: Microsoft.WindowsAzure.Storage.StorageException: The operation was canceled.
Line 30725: ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
Line 30726: ---> System.IO.IOException: Unable to read data from the transport connection: Operation canceled.
Line 30727: ---> System.Net.Sockets.SocketException (125): Operation canceled
Line 30728: --- End of inner exception stack trace ---
Line 30729: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
Line 30734: --- End of inner exception stack trace ---
Line 30742: --- End of inner exception stack trace ---
```

Upon further investigation, this seems to have occurred when attempting to write to our durable hub's history table after successfully writing to the instance table. The flow is as follows:
1. Service Bus message enters our trigger, starts the given orchestration successfully and issues an instanceId (can confirm that instance row exists in table under given partitionKey).
2. Write to history table fails due to socket exception - nothing for given instanceId/partitionKey is written to history table.
3. Instance remains in "Pending" RuntimeStatus and work is never executed because there are no rows in the history table.

After rebooting the given DTFx workers, we can see that the offending instances start successfully (eventually reach a RuntimeStatus of "Completed") and we can then see history for the instance. I have a few questions as a result of this:

1. Do you have any context on what may lead to these socket exceptions from a DTFx implementation level? We don't have control of DTFx's storage client usage (how HttpClient is being managed, whether the client is being disposed, etc) so any context would be helpful.
2. Is there an automatic cleanup on DTFx service reboot that restarts processing for instances with a "Pending" RuntimeStatus? If yes, this would align with the behavior we saw on reboot.
3. These socket exceptions show up in our container logs but we are not able to catch them currently in our managed DTFx service code - do you have any suggestions for handling exceptions fired from the DTFx library itself (expecially regarding connections to Azure Storage and Service Bus)?

We're using Dotnetcore 3.1 and the following versions of the WebJobs/Durable Task libraries:
```
    <PackageReference Include="Microsoft.Azure.WebJobs.Core" Version="3.0.27" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="4.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" Version="0.4.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.4" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.2.3" />
```

Thanks in advance!

**Comment by ConnorMcMahon** [comment]
Can you try upgrading to v2.5.1 of Durable Functions?

We have a known issue [that was fixed](https://github.com/Azure/durabletask/pull/568) that caused long-running instance status query for ExecutionStarted events.

We saw an internal ticket that experienced that bug, and they saw similar TaskCancelledExceptions issue to yours, though that was while trying to fetch the instance history, not write it. When they upgraded to v2.5.1 that had the long-running instance status query fixed, the TaskCanceled exceptions also went away.

**Comment by brrusino** [comment]
@ConnorMcMahon We've now updated all of our DTFx worker services to use v2.5.1. This sounds like a reasonable potential mitigation, but is there any deeper understanding of why the Storage Account client was experiencing socket exceptions? I'm hesitant to assume this is fixed without more of a RCA there.
