### ISSUE TITLE
Intermittent orchestrator delay

### ISSUE THREAD

**Issue by mengschin** [Azure/azure-functions-durable-extension#1923]
Good day @ConnorMcMahon @cgillum 

I`m seeing an intermittent orchestrator delay to kick off in durable function lately.

Couldn't find much info from my end regarding the delay, but it'll continue to run whenever there is a function restart.

Can you assist to check for any culprit from your end?

Workflow InstanceId: e356d4e0-f641-4136-b4e7-a9f88002d989_0_2 
Region: WUS
Time: 2021-08-02T10:28:05.867Z

Notice on the delay for OrchestratorStarted event below, the Orchestrator started on the next day(due to function restart)
![image](https://user-images.githubusercontent.com/59546764/130002449-56a813c2-6866-4b13-927d-ad298f7ae0d0.png)

My host.json as below:
`"durableTask":{"hubName":"xxxxxxEngine","tracing":{"traceInputsAndOutputs":false},"storageProvider":{"connectionStringName":"DurableFunctionsStorage","controlQueueBatchSize":32,"controlQueueVisibilityTimeout":"00:05:00","partitionCount":4,"workItemQueueVisibilityTimeout":"00:05:00"},"extendedSessionsEnabled":true,"extendedSessionIdleTimeoutInSeconds":30,"maxConcurrentActivityFunctions":30,"maxConcurrentOrchestratorFunctions":30}`

**Comment by cgillum** [comment]
Hi @mengschin, I noticed you're running a pretty old version of the Durable Functions extension (v2.2.1). There have been a significant number of performance and reliability improvements that have been released since then. For example, previous builds would periodically run into long stalls like these because of deadlocks in the version of the Azure Storage SDK we depend on. Subsequent releases have added mitigations for these deadlocks. There are also many telemetry improvements since then that will make it much easier for us to help debug issues. I recommend upgrading to the latest released version (v2.5.1) and seeing whether you still experience these delays.

**Comment by mengschin** [comment]
Hi @cgillum, thanks for the response.
Reason of raising this ticket is because I would like to know whether anything unusual detected from your end for this particular workflow instance as it seems this delay only started on the last few weeks. Also, making sure upgrading to latest version will cater it.
Upgrading to latest released version (v2.5.1) is one of the thing I`m looking into currently.

**Comment by mengschin** [comment]
Hi @cgillum  , I've upgraded to version v2.5.1 and performed some tests recently.
I`m still seeing some orchestrators delayed to kick off in some of my instances.

Some sample workflow instance ids that encountered orchestrator's delay:
1. Workflow InstanceId: 16a6c384-82f5-4dd9-bbb0-f91e9de70663_0_1
Region: AUS
Time: 2021-12-17T06:31:03.905Z
![image](https://user-images.githubusercontent.com/59546764/146712755-2ad2f37d-0211-46ff-bc91-6b94538a8c2a.png)

2. Workflow InstanceId: ee356fdf-e12a-4d12-8a88-f365f757f120_0_1
Region: AUS
Time: 2021-12-17T07:03:29.672Z
![image](https://user-images.githubusercontent.com/59546764/146712963-5ff431e2-04f9-4cbc-8697-e889ddbca74f.png)

3. Workflow InstanceId: dae55ece-da48-4d1b-bca3-108d46a11230_0_1
Region: AUS
Time: 2021-12-17T08:37:22.376Z
![image](https://user-images.githubusercontent.com/59546764/146716246-144bf8b1-3ab1-49a1-8b65-24dc67f3fab7.png)

I`m not able to find anything unusual from function app diagnostic tools or App insight that could relate to the delay.
One thing in common on these instances, they encountered _Timeout value of 00:10:00 exceeded by function 'WorkflowExecution' (Id:xxx'). Initiating cancellation._

For these workflow instances, could you please check if anything unusual from your end? Thanks and appreciate.

**Comment by cgillum** [comment]
Hi @mengschin. I may need a bit more context. Nothing in your screenshots look unusual to me. It appears that these orchestration instances were waiting a long time for some external event, and the event arrived after about a day. The delay therefore seems to be external to your orchestration.

Just in case this might be confusion about how to read the history table, I recommend reading through [this README](https://github.com/Azure/durabletask/blob/main/src/DurableTask.Core/History/README.md) to make sure you fully understand what each of these events are describing. For example, `OrchestratorCompleted` and `OrchestratorStarted` are intermediate events that describe when an orchestrator starts and finishes processing a new set of events. They aren't related to when the orchestration actually starts running from the beginning (captured by `ExecutionStarted`) or when it runs all the way to the end (`ExecutionCompleted`).
