### ISSUE TITLE
Instances keep getting stuck in Pending

### ISSUE THREAD

**Issue by chris9263** [Azure/azure-functions-durable-extension#1925]
### Description
The solution runs on a timertrigger every 20 minutes. We set our own instanceId and checks if there are any similar running instances before calling the orchestration. The solution works fine but at random intervals the instance gets stuck in pending and nothing is run before we restart the function app.  Tried adding a cleanup of running or pending instances older than 20 minutes but it keeps getting stuck in pending. Have also upgraded Microsoft.Azure.WebJobs.Extensions.DurableTask to 2.5.0 with no luck. Also double checked that Microsoft.Azure.DurableTask.AzureStorage is version 1.8.6. 

### Expected behavior
No pending intances that blocks the whole solution. 

### Actual behavior
Instances gets stuck in pending at irregular intervals, restarting the function app terminates the pending instance and fixes the problem.

### Relevant source code snippets
```csharp
[FunctionName(nameof(ObosSeTimerStart))]
        public async Task ObosSeTimerStart(
            [TimerTrigger("0 15/20 6-23 * * *")] TimerInfo timerInfo,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger logger)
        {
            var log = new Dictionary<string, string>();

            var instanceId = "singletonLockObosSe";

            try
            {
                if (starter == null)
                {
                    throw new ArgumentNullException(nameof(starter));
                }

                _ = await starter.StartNewAsync(nameof(Orchestrations.GetAllObosSeSalesAssignments.RunGetAllObosSeSalesAsignments), instanceId).ConfigureAwait(false);
                LogStarted(log, instanceId);
            }
            catch (InvalidOperationException ie)
            {
                if (ie.Message?.ToLower().Equals("An Orchestration instance with the status Running already exists.".ToLower()) == true ||
                    ie.Message?.ToLower().Equals("An Orchestration instance with the status Pending already exists.".ToLower()) == true)
                {
                    var status = await starter.GetStatusAsync(instanceId);

                    if (status.CreatedTime.ToUniversalTime() < DateTime.UtcNow.AddMinutes(-19))
                    {
                        await starter.TerminateAsync(instanceId, "CLEANUP");
                        var purgeResult = await starter.PurgeInstanceHistoryAsync(instanceId);
                        if (purgeResult.InstancesDeleted != 0)
                        {
                            _ = await starter.StartNewAsync(nameof(Orchestrations.GetAllObosSeSalesAssignments.RunGetAllObosSeSalesAsignments), instanceId).ConfigureAwait(false);
                            LogStarted(log, instanceId);
                        }
                        else
                        {
                            LogSkipped(log, status, timerInfo);
                        }
                    }
                    else
                    {
                        LogSkipped(log, status, timerInfo);
                    }
                }
                else
                {
                    LogError(log, ie);
                }
            }
            catch (Exception e)
            {
                _logger.LogTraceException(nameof(ObosSeTimerStart), e, $"Failed to start orchestration", SeverityLevel.Information, log);
            }
        }
```

### App Details

- **Microsoft.Azure.WebJobs.Extensions.DurableTask 2.5.0**:
- **Azure Functions runtime version 3**:
- **netcoreapp3.1**:

### If deployed to Azure

- **Timeframe issue observed**: 12:55 - 13:30, Date:19.08.21, time from Splunk so should be UTC. It also happend between 06:00 and 09:00 in the morning the same day.
- **Function App name**: obosit-prod-int-salesassignment-fa
- **Function name(s)**: ObosSeTimerStart
- **Azure region**: West Europe
- **Orchestration instance ID(s)**: singletonLockObosSe
- **Azure storage account name**: obositprodintsalesasas01

**Comment by cgillum** [comment]
The first thing I recommend is updating to v2.5.1. Some very important reliability fixes came in that release, and might be helpful for resolving your issue.  If that doesn't help, we can dive deeper to take a look and wee where things might be getting stuck.

**Comment by chris9263** [comment]
Okei, i have upgraded to v2.5.1, it might take a couple of days or weeks before we expirience the issues again. Will keep you posted.
