### ISSUE TITLE
Orchestrator taking long times executing activities after purging the history

### ISSUE THREAD

**Issue by vany0114** [Azure/azure-functions-durable-extension#1931]
### Description
After purging the orchestrator history it suddenly started to behave weird, and by weird I mean the response time increased tremendously. After taking a look at the logs and traces and trying to understand what is going on I found a consistent pattern there, basically, it was taking ~4.6 minutes between activity executions, funny thing is our orchestrator used to respond in ms (or in a couple of minutes in the worst-case scenario due to a custom timeout) because it is used to orchestrate a distributed transaction, we're not processing anything there. So that behavior showed up after purging the history the first time, which by the way we've been having [issues running the timer trigger](https://github.com/Azure/azure-functions-durable-extension/issues/1915) which performs the purging, not sure if that might be related to this, probably.

### Expected behavior
I would not expect any disruption in the orchestrator after purging the old history (older than one month) of the completed/failed instances, on the contrary, I'd expect the orchestrator to perform even better in terms of response time since the history was reduced after the purge, therefore, the lookup of the history when replaying should be better.

### Actual behavior
The response time of the orchestrator got degraded too much, it is taking up to 41 minutes.

### Known workarounds
I had to delete the storage account related to the function app as well as redeploy the function app and the storage account, after that the orchestrator backed to normal and started behaving as usual and being responsive.

### App Details

- **Durable Functions extension version**: 2.5.1
- **Azure Functions runtime version**: 3.0
- **Programming language used**: C#

### Screenshots
* Here you can see that it takes almost 5 minutes from the activity is scheduled and when it is actually executed. 
![image](https://user-images.githubusercontent.com/12032625/130856509-3bb403db-0a42-49fe-980d-8f691f3174c7.png)

* A couple of normal instance traces: 
![image](https://user-images.githubusercontent.com/12032625/130856855-094b0cac-2d75-46ee-80c7-a19ac69139d4.png)
![image](https://user-images.githubusercontent.com/12032625/130856878-b8688356-1769-4444-b741-c1f2e74e7453.png)

* A few of delayed instance traces:
![image](https://user-images.githubusercontent.com/12032625/130857180-de21dafb-1474-4a85-b287-adca46cc6a46.png)
![image](https://user-images.githubusercontent.com/12032625/130857188-8ce8959c-f54a-4d0b-8442-f9927e16aaf1.png)
![image](https://user-images.githubusercontent.com/12032625/130857246-9d98429d-b843-4e2a-a94e-1b8957f147e0.png)

* Finally here you guys can see that the response time degradation started after the history was purged (also notice that the timer trigger [was only fired two times](https://github.com/Azure/azure-functions-durable-extension/issues/1915#issuecomment-902894923) when it is supposed it should run every day)
![image](https://user-images.githubusercontent.com/12032625/130857664-970d0241-e2f7-4758-800c-038fd2c9dfd7.png)

* And this is how the response time looks like after I remove the storage account and re-deploy again:
![image](https://user-images.githubusercontent.com/12032625/130857814-ef3b41af-f98f-4eb3-8e0a-c4334ca36c51.png)

I appreciate any help on this since this happened in our production environment and it really caused issues on our end, and I'm afraid this might happen again.

**Comment by vany0114** [comment]
Hello guys, any update on this? it started happening again. 😨

**Comment by amdeel** [comment]
Hey @vany0114 Did you notice the increase in processing times associated with your PurgeInstanceHistory call or was it unrelated? Could you provide timestamps when your long orchestrator processing started on this new storage account?

**Comment by vany0114** [comment]
It is related as I show in the images above. It started on August 19th.

**Comment by vany0114** [comment]
@amdeel  Any updates on this? it's happening again 😞 
![image](https://user-images.githubusercontent.com/12032625/135281454-eb49c87f-2c72-49d3-be52-0807795c35c3.png)

**Comment by cgillum** [comment]
I suspect this is a result of storage account throttling. Purging instance state is a very expensive operation so I suspect this is why orchestration processing and timer triggers (which also depend on Azure Storage) are being impacted.

When this happens, how many instances are getting purged? Purging smaller batches of instances at a time might help mitigate this. Also, of you’re not doing so already, consider having a separate storage about used by Durable Functions from AzureWebJobsStorage.

**Comment by vany0114** [comment]
@cgillum I stopped purging that orchestrator a while ago (when this issue showed up), and yeah I have a dedicated storage account for this function app.

**Comment by cgillum** [comment]
@vany0114 Ah, apologies, I misunderstood. It's very odd that you'd have performance problems several days after a purge occurred. I'm wondering if some bad state might have been left behind in the storage account that is causing orchestration processing to slow down significantly. That would help explain why creating a new storage account mitigated the problem.

We'll investigate more closely to see whether this is being caused by a problem in the Durable Extension. It looks like your screenshots have enough information (app name, timestamps, etc.) for us to start looking.

**Comment by amdeel** [comment]
@vany0114 Could you please share more details about this most recent increase in execution time you're seeing? Could you share an instanceId of an affected orchestrator and the timestamps in UTC?

**Comment by vany0114** [comment]
@amdeel I removed the storage account and redeployed again, so I don't have the new instances id's, only the one that I shared in the first picture.

**Comment by amdeel** [comment]
@vany0114 Since you seem to be experiencing this issue repeatedly, even after changing storage accounts, could you please share specific details if this happens again for you? Specific instanceIds affected, specific timestamps in UTC, and any more details you might have about this issue? Another thing you can do is explicitly reference our latest version of DurableTask.AzureStorage (version 1.9.3) to make sure you have our latest updates.

**Comment by vany0114** [comment]
@amdeel I will, on the other hand, I was reviewing the references and we're not using that package, these are the references we have (I realized that we're using a couple of beta versions, including the storage package):

```
 <PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.1.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventGrid" Version="2.1.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0-beta.2" />
<PackageReference Include="Microsoft.Azure.WebJobs.ServiceBus" Version="3.0.0-beta8" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
``` 

We're using .Net Core 3.1 BTW, because back in the day we were moving to .Net 5 but we couldn't because of this other [issue](https://github.com/Azure/azure-functions-durable-extension/issues/1698) that I opened I while ago.

So please let me know which package and version should I use 🙏

**Comment by amdeel** [comment]
[Microsoft.Azure.WebJobs.Extensions.DurableTask](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask) 2.5.1 takes a dependency on [Microsoft.Azure.DurableTask.AzureStorage](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/) 1.9.0. Usually it references an up-to-date package, but we've been releasing fixes in DurableTask.AzureStorage faster than we release new version of the Extensions.DurableTask package. I released a new version of DurableTask.AzureStorage last week, version 1.9.3. You can explicitly add this reference to get this version instead.
