### ISSUE TITLE
When invoking ReadEntityStateAsync to read entity state while holding its lock will deadlock

### ISSUE THREAD

**Issue by ThomasBleijendaal** [Azure/azure-functions-durable-extension#1935]
### Description

I'm not sure if this is really a bug, or improper use of the SDK, but when calling `var state = await entityClient.ReadEntityStateAsync<T>(entityId);` inside `using (await context.LockAsync(entityId)) {  }` will deadlock the function. The `ReadEntityStateAsync` probably waits until the lock gets removed, but that will never happen.

I've read the [rules on preventing deadlocks in critical sections](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp#critical-section-rules) and this use case is not listed explicitly as forbidden but also does not throw `LockingRulesViolationException`. 

### Expected behavior
I would have expected to either get the entity state, or a `LockingRulesViolationException`. 

### Actual behavior
The critical section deadlocks.

### Relevant source code snippets
```csharp
var gameId = new EntityId(nameof(GameEntity), input.GameId);

using (await context.LockAsync(gameId))
{
    var game = context.CreateEntityProxy<IGameEntity>(gameId);
    var accepted = await game.AddPlayerAsync(input);
    if (accepted)
    {
        var gameStateResponse = await entityClient.ReadEntityStateAsync<GameState>(gameId);
        await signalr.AddAsync(new SignalRMessage
        {
            GroupName = gameId,
            Arguments = new object[] { gameStateResponse.EntityState },
            Target = "Broadcast"
        });
    }
}
```

### Known workarounds
Do not call `ReadEntityStateAsync` inside the critical section. 

### App Details
Microsoft.NET.Sdk.Functions: 3.0.13
Microsoft.Azure.WebJobs.Extensions.DurableTask: 2.5.1
Function Runtime: v4

**Comment by ThomasBleijendaal** [comment]
I think I found the reason why this happens. I call `entityClient.ReadEntityStateAsync<GameState>()` in which `GameState` is the base class of the `GameEntity`. `GameState` contains only the JSON properties, while `GameEntity` implements all the methods dictated by `IGameEntity`.

If I change the code to `entityClient.ReadEntityStateAsync<GameEntity>` then the deadlock does not occur. Question remains whether the use of `GameState` instead of `GameEntity` should be permitted or should result in a `LockingRulesViolationException`.

**Comment by davidmrdavid** [comment]
@sebastianburckhardt, could you please comment on this? I'm not personally familiar with the C# implementation of Entities ^. Thank you :)

**Comment by sebastianburckhardt** [comment]
@ThomasBleijendaal, there is a pretty simple explanation.

The problem comes from using `entityClient` from within an orchestration function. This is not how the SDK is meant to be used - from within orchestrations, application code must exclusively use the orchestration context `context`  to interact with other durable functions (orchestrations, entities, activities).  

Sorry for the confusion. Perhaps we could make this clearer in the documentation, or throw a runtime error with an indication.

**Comment by sebastianburckhardt** [comment]
In your specific situation, what you would probably want to do is

1. Add a new method to the `IGameEntity`  interface: 
```csharp 
    Task<GameState> GetState();
```

2. Implement that method in the entity implementation

3. Call the method from your orchestration:
```csharp
var state = await game.GetState();
```

**Comment by ThomasBleijendaal** [comment]
@sebastianburckhardt Thanks for the quick reply. It makes sense to only interact with other durable functions within orchestrations. The durable entity gives the impression that you talk to a concrete entity, but it is still a durable function after all.

I've updated the entity function to

```c#
[FunctionName(nameof(GameEntity))]
    public static Task GameEntityFunction(
        [EntityTrigger] IDurableEntityContext context,
        [SignalR(HubName = nameof(GameHub))] IAsyncCollector<SignalRMessage> signalr)
            => context.DispatchAsync<GameEntity>(signalr, context.EntityKey);
```

which allows me to access `signalr` within the durable entity. This completely removes the orchestration function as I can just signal events to the entity now, and simplifying everything. If I need orchestration I'll use your suggestion.

**Comment by davidmrdavid** [comment]
Thank you Sebastian :)
Glad to hear this issue seems resolved, @ThomasBleijendaal. Can we close this issue?

**Comment by ThomasBleijendaal** [comment]
Sorry forgot to get back at this. Yes I'll close the issue as it is resolved.
