### ISSUE TITLE
what algorithm used to generate return instanceId value from supplied instanceId in start new async?

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-functions-durable-extension#1942]
# Issue Transfer

This issue was transferred from the Azure SDK for .NET repository, [#23727](https://github.com/Azure/azure-sdk-for-net/issues/23727).

## Details

Dear support team

Can you please clarify how return value "instanceId" of type String is generated from supplied instanceId?

For the same supplied instanceId we get the same instanceId in response and wish to be able to generate it ourself to check for status.

Use case:
function uses singleton pattern for create/update of an object.  We know instanceId  upfront to query if existing function instance is null or running and to decide upon response if we want to trigger a new one.

sadly [DurableClient] IDurableClient starter cannot be inject in non-orchestration function so we cannot use it to query status.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a099555c-ed00-7bcf-18f4-464985b44c66
* Version Independent ID: 7d53592d-2f14-2955-5288-9b325e37030e
* Content: [IDurableOrchestrationClient.StartNewAsync Method (Microsoft.Azure.WebJobs.Extensions.DurableTask) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.startnewasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.WebJobs.Extensions.DurableTask/IDurableOrchestrationClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.WebJobs.Extensions.DurableTask/IDurableOrchestrationClient.xml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amdeel** [comment]
@boris-tarasov-maersk

The instanceId is optionally supplied when starting an orchestrator. If it is supplied as an input parameter, we will use that value as the instanceId. If it is not, we will generate an Id. The instanceId is always returned.

Let me know if that answers the question.

**Comment by boris-tarasov-maersk** [comment]
@amdeel 
Thank you for your quick response but it is not what I am asking.

My question is:

I supply **instance Id in a request** as "boris-dev_coreteam_dev6_boris2021-08-30-put" 
and **instance id in a response** is in a form like 
C5F58849E8F335AF547C31663CB71A4661691D04809ADFE6D981FD57CC63D5F9

I want to know how to generate response instance id from request instance id I supply myself. It seems it is the same id over and over again.

**Comment by boris-tarasov-maersk** [comment]
please put this issue on hold. I could be wrong and due to use of some extension methods we might have overwritten default behaviour.

**Comment by boris-tarasov-maersk** [comment]
please close this issue. sorry for the false case.
