### ISSUE TITLE
Use without functions?

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-functions-durable-extension#195]
Is it possible to use this without Azure Functions and just with the Webjobs SDK? It seems like it is built upon WebJobs only, but I don't see any explicit note about this.

**Comment by cgillum** [comment]
Yes, this is possible. I'm not sure whether we have documentation on how to load extensions in webjobs, but here is a snippet I use in my testing.

```csharp
using Microsoft.Azure.WebJobs.Extensions.DurableTask;

// ...

var config = new JobHostConfiguration { HostId = "durable-task-host" };
config.UseDurableTask(new DurableTaskExtension { HubName = "MyTaskHub" });

var host = new JobHost(config);
await host.StartAsync();
```

Let me know if this works for you.
