### ISSUE TITLE
Crashed orchestrators stay in "Running" status.

### ISSUE THREAD

**Issue by Ninlives** [Azure/azure-functions-durable-extension#1951]
### Description

Sometimes orchestrators crashed but stay in "Running" status rather than "Failed".

### Expected behavior

The crashed orchestrator result in "Failed" status.

### Actual behavior

The crashed orchestration stays in "Running" status.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.5.1
- **Azure Functions runtime version (1.0 or 2.0)**: 3.1
- **Programming language used**: C#

### If deployed to Azure

- **Timeframe issue observed**: 2021-09-14T07:24:35Z - 2021-09-14T15:24:35Z
- **Azure region**: East US
- **Orchestration instance ID(s)**: default-20210914072435-d28f9e05::EntryPoint

**Comment by Box-Of-Hats** [comment]
I've encountered similar issues where certain instances are forever stuck in `Running`, even months later

**Comment by ConnorMcMahon** [comment]
@Box-Of-Hats, if you have a similar scenario, I recommend posting a similar issue with a timestamp + instance id from the last 60 days. These stuck orchestrations mostly have different underlying causes, so we try to handle them on a case-by-case basis.

**Comment by Box-Of-Hats** [comment]
@ConnorMcMahon will do, thanks!

**Comment by lilyjma** [comment]
@Ninlives - apologies for the delayed response. Are you still experiencing this problem?
