### ISSUE TITLE
Orchestration instance started stuck in pending status.

### ISSUE THREAD

**Issue by graceishere** [Azure/azure-functions-durable-extension#1956]
### Description
After a release durable functions are getting stuck in the pending state, if I do not kill the instance it's never getting through it. Happens once in a day and sometimes with multiple instances sometimes with one instance. Checked app service with this function app, CPU and memory are good.
In this release, upgrade function app to V3 and Microsoft.Azure.WebJobs.Extensions.DurableTask is on 2.5.1
Also add one more durable function.

### Expected behavior
They should run normally without getting stuck in pending state.

### Actual behavior
Stuck on pending status for some instance once in a day.

### Relevant source code snippets
```csharp
private static async Task ExecuteSqlOrchestrator(this IDurableOrchestrationClient starter, string function, ILogger log)
{
    HashSet<AdlsFeed> feeds = await FHConfig.GetActiveSourceFeedCombinations().ConfigureAwait(false);
    List<Task> tasks = new List<Task>();
    foreach (AdlsFeed comb in feeds)
    {
        string instanceId = comb.ToEntityKey(function);
        DurableOrchestrationStatus existingInstance = await starter.GetStatusAsync(instanceId).ConfigureAwait(false);
        if (existingInstance == null || !InstanceRunning(existingInstance.RuntimeStatus))
        {
            tasks.Add(starter.StartNewAsync(nameof(InvokeSqlFunction), instanceId, (function, comb)));
            log.LogInformation($"Started instance: {instanceId}");
        }
    }

    await Task.WhenAll(tasks).ConfigureAwait(false);
}
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
- Microsoft.Azure.WebJobs.Extensions.DurableTask is on 2.5.1
- **Azure Functions runtime version (V3)**:
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: starting from 9/17
- **Function App name**: func-fraudhunterssql-pme-test-001
- **Function name(s)**: CosmosDBToSQLCastAsync
- **Azure region**: East US 2
- **Orchestration instance ID(s)**: ExcutionId? 9d89d806c0b442a1b4194ea7ade4a651,39af5ce95e8342499c346fabd547c719
- **Azure storage account name**:stfhsqltest001

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment]
Hi @graceishere, thanks for this detailed information. I went ahead and looked up your instances in our internal service telemetry, which is essentially the same trace data available to you in [Application Insights](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics#application-insights).

I took a look at your orchestration instance (Azure;Evaluation;CosmosDBToSQLCastAsync, with execution ID 9d89d806c0b442a1b4194ea7ade4a651) and I can see that it started executing at 2021-09-22 18:12:00, immediately transitioned from "Pending" to "Running", and then completed successfully at 2021-09-22 18:12:20 (20 seconds after it started).

Similarly, the instance Azure;PaymentAuth;CosmosDBToSQLCastAsync (execution ID 39af5ce95e8342499c346fabd547c719) was scheduled at 2021-09-22 18:12:00, transitioned immediately into the "Running" state, and completed at 2021-09-22 18:12:05, which is 5 seconds after it was scheduled.

In both of these cases, the instance was only in the "Pending" state for a few milliseconds. Are these not the right instances/execution IDs to be looking at?
