### ISSUE TITLE
Slow Orchestration Processing - Queue message delays

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-durable-extension#1976]
### Description
We are experiencing intermittent slow down of some workflows, where the workflow that usually takes minutes to process takes hours. It seems that the issue seems to be surrounding the scheduling of activities and orchestrations, which stay in a scheduled state, but are only processed minutes or sometimes hours later. 

All the application insight data we have inspected do not indicate a load issue that could be slowing down the processing of queue messages.

What could be the cause of these slow downs? We have submitted multiple support requests but have uncovered no discernible pattern? Can anyone from the development team guide us as to why are we seeing these delays?

### Expected behavior
Workflows complete in a timely manner

### Actual behavior
Scheduled queue messages seem to be delayed in being dequeued up by relevant activities and orchestrations.

### Relevant source code snippets
A workflow that normally takes a maximum of 10 minutes to complete, is taking more than 2hours to complete,
![image](https://user-images.githubusercontent.com/8879065/137349297-f6cab925-4ad5-4aa2-905c-9067ae8f6a07.png)

Example of a 20min delay between processing
![image](https://user-images.githubusercontent.com/8879065/137370063-55a93c3d-a3f9-44e4-8ae9-a2cff5f2c12c.png)

### Known workarounds
Increase global workflow timeout to avoid timeout exceptions.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.5.0
- **Azure Functions runtime version (1.0 or 2.0)**: V3.0
- **Orchestration instance ID(s)**: 3ef1d4d7-3a00-4867-bfa4-05abf93f602d
- **Azure storage account name**: efdynamoproduction

**Comment by gorillapower** [comment]
Great thank you, it doesnt seem obvious. We've moved from consumption plan to appservice plan as we suspected a load issue. This seemed to alleviate the problem temporarily, but now we are seeing them again. I wonder if it could be that we have a large table history?

Yes that is by design :) Its help us with tracing and diagnostics as those two orchestrations are related but indeed separate.

**Comment by cgillum** [comment]
So looking closely at this. I see some unusual slowdowns happening internally in the Durable Task Framework Azure Storage provider. I recall some of our customers ran into similar performance problems with the v2.5.0 extension version which were resolved in v2.5.1. The issue happened most frequently when multiple orchestrations were started around the same time. Can you try upgrading to the latest extension version to see if you still observe these slowdowns?

**Comment by gorillapower** [comment]
@cgillum since we updated to the latest version, we are not seeing this issue! Thanks for your quick attentive response as always. 🙌
