### ISSUE TITLE
Purge History HTTP Error 500

### ISSUE THREAD

**Issue by wboevink** [Azure/azure-functions-durable-extension#1978]
### Description
History purges tend to timeout and the history table keeps growing.
As of today I get a http 500 error when purging

### Expected behavior
Expected a HTTP 200 (OK)

### Actual behavior
HTTP Error 500 with response
{
    "Message": "Something went wrong while processing your request",
    "ExceptionMessage": "Not Found",
    "ExceptionType": "Microsoft.WindowsAzure.Storage.StorageException",
    "StackTrace": "   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)\r\n   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation, AzureStorageOrchestrationServiceStats stats, String clientRequestId)\r\n   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.DeleteAllDataForOrchestrationInstance(OrchestrationInstanceStatus orchestrationInstanceStatus) in C:\\source\\durabletask\\src\\DurableTask.AzureStorage\\Tracking\\AzureTableTrackingStore.cs:line 854\r\n   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.DeleteHistoryAsync(DateTime createdTimeFrom, Nullable`1 createdTimeTo, IEnumerable`1 runtimeStatus) in C:\\source\\durabletask\\src\\DurableTask.AzureStorage\\Tracking\\AzureTableTrackingStore.cs:line 803\r\n   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.PurgeInstanceHistoryAsync(DateTime createdTimeFrom, Nullable`1 createdTimeTo, IEnumerable`1 runtimeStatus) in C:\\source\\durabletask\\src\\DurableTask.AzureStorage\\Tracking\\AzureTableTrackingStore.cs:line 936\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.AzureStorageDurabilityProvider.PurgeHistoryByFilters(DateTime createdTimeFrom, Nullable`1 createdTimeTo, IEnumerable`1 runtimeStatus) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\AzureStorageDurabilityProvider.cs:line 137\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.Microsoft.Azure.WebJobs.Extensions.DurableTask.IDurableOrchestrationClient.PurgeInstanceHistoryAsync(DateTime createdTimeFrom, Nullable`1 createdTimeTo, IEnumerable`1 runtimeStatus) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\ContextImplementations\\DurableClient.cs:line 503\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleDeleteHistoryWithFiltersRequestAsync(HttpRequestMessage request) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 565\r\n   at Microsoft.Azure.WebJobs.Extensions.DurableTask.HttpApiHandler.HandleRequestAsync(HttpRequestMessage request) in D:\\a\\r1\\a\\azure-functions-durable-extension\\src\\WebJobs.Extensions.DurableTask\\HttpApiHandler.cs:line 355"
}

### Relevant source code snippets
```powershell
$response = Invoke-RestMethod 'https://func-smxsle-environmentalzone-service-westeurope-p.azurewebsites.net/runtime/webhooks/durableTask/instances?taskHub=EnvironmentalZoneHubV1&code=********&createdTimeFrom=2021-10-10T00:00:00Z' -Method 'DELETE' -Headers $headers
$response | ConvertTo-Json
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.5.1 (Microsoft.Azure.WebJobs.Extensions.DurableTask)
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### If deployed to Azure
- **Function App name**: func-smxsle-environmentalzone-service-westeurope-p
- **Azure region**: WESTEU
- **Azure storage account name**: smxslepenvironmentalzone

**Comment by AnatoliB** [comment]
@wboevink Is this still happening to you on a more recent version (2.6.1 or greater)?
