### ISSUE TITLE
IDurableEntityClient.CleanEntityStorageAsync() doesn't delete the entity from storage

### ISSUE THREAD

**Issue by yashvardhan90** [Azure/azure-functions-durable-extension#1990]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

[IDurableEntityClient.CleanEntityStorageAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableentityclient.cleanentitystorageasync?view=azure-dotnet) doesn't delete the entity from the storage account. It only deletes the ```{"exists":true}``` field. This causes the ListEntities function to return all the entities. 

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

### Expected behavior
> A clear and concise description of what you expected to happen.

It should delete all empty entities.

### Actual behavior
> A clear and concise description of what actually happened.

Modifies a property of the entity but doesn't actually delete it.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.4.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0
- **Programming language used**: c#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 10/29/2021
- **Function App name**: LogManager-dev
- **Function name(s)**: LogManager
- **Azure region**: West US 2
- **Orchestration instance ID(s)**:
- **Azure storage account name**: dmflogsubscriptiondev
- **Table name: LogManagerAInstances

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment]
@sebastianburckhardt is this the expected behavior?

**Comment by olitomlinson** [comment]
duplicate https://github.com/Azure/azure-functions-durable-extension/issues/1364

**Comment by yashvardhan90** [comment]
Turns out the entities have had operations on them in the last 30 minutes that's probably why they weren't deleted. Closing the issue.
