### ISSUE TITLE
Corrupt Messages in WorkItems Queue -  System.FormatException: The input is not a valid Base-64 string

### ISSUE THREAD

**Issue by DonHurley** [Azure/azure-functions-durable-extension#1997]
### Description

We are having a problem where our functions will get an error deserializing what messages in the Workitems queue.  This is causing the functions to hang and stop processing. We have had to stop the functions copy the Instances table, and requeue all jobs that were in the running state.  This worked and all items processed, but now it is happening again.  This started when we upgraded our functions from .netstandard 2.0 to .netcore3.1 and functions v2 to v3.   

Here is the exception we are seeing:

An error occurred while processing messages on lensexchangefunctionscorehub2-workitems: System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.    at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)    at System.Convert.FromBase64String(String s)    at Microsoft.WindowsAzure.Storage.Queue.CloudQueueMessage.get_AsString()    at DurableTask.AzureStorage.Storage.QueueMessage..ctor(CloudQueueMessage cloudQueueMessage) in C:\source\durabletask\src\DurableTask.AzureStorage\Storage\QueueMessage.cs:line 23    at DurableTask.AzureStorage.Storage.Queue.GetMessageAsync(TimeSpan visibilityTimeout, CancellationToken callerCancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\Storage\Queue.cs:line 109    at DurableTask.AzureStorage.Messaging.WorkItemQueue.GetMessageAsync(CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\Messaging\WorkItemQueue.cs:line 39

![image](https://user-images.githubusercontent.com/80987707/140331889-2c9d506d-b453-4145-9cc7-61b20ce99258.png)

### Expected behavior
  Durable Functions should continue to process other orchestrations and there should be a way to recover or handle stuck orchestration

### Actual behavior
Orchestrations stopped processing.  

### Known workarounds
Delete task hubs and resubmit jobs that were running.

### App Details

    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" Version="0.4.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0" />

    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>

    c#

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

Orchestration Id:
3186be4d4d7043359e5de47d27f95008:2383

HostInstanceId:  
5167d5ba-c92d-4305-8506-a40106bd083d - 2021-11-04T13:53:21.7033516Z
11a6844f-d7a2-4ad7-86e4-ce9d508a84c8  - 2021-11-04T13:52:49.5361011Z

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by DonHurley** [comment]
We have had to rollback to previous versions to mitigate the issue:

    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>

    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" Version="0.4.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.8" />

@cgillum   I see your name on here a lot that is why I am tagging you.  Can someone take a look at this?

**Comment by cgillum** [comment]
Looking at the message, I see you're using the distributed tracing feature, which is currently preview. Are you able to reproduce the issue with the distributed tracing disabled? I don't know how these characters would have shown up in your message.

Poison message handling is on our radar, but we unfortunately haven't been able to get to it quite yet. There should be another GitHub issue tracking this as a general purpose feature.

**Comment by DonHurley** [comment]
Im not sure how poison handling would help in this case since the message is queued in the task hub queues.  I have a story this sprint to repro this.  I will need a few days to repro and then try with the distributed tracing disabled.

**Comment by DonHurley** [comment]
Can't repro
