### ISSUE TITLE
Orchestrator, distributed tracing and ServiceBus queues correlation

### ISSUE THREAD

**Issue by cyrilcathala** [Azure/azure-functions-durable-extension#1998]
# Context

I have a microservice A calling a microservice B which is durable function / orchestrator.
At the end of the orchestration, microservice B enqueues a message to a ServiceBus topic.
Microservice A is subscribed to this topic and waits for a callback through this topic.

Put simply:
`Microservice A ---[http]---> Microservice B (Orchestrator) ----[topic]---> Microservice A`

# Telemetry

I configured telemetry to use Application Insights and distributed tracing for the orchestration.
The request telemetry starts with microservice A, it follows with microservice B and distributed tracing works well within microservice B (great work on this part 🤗).

Unfortunately, the trace finishes when enqueuing the topic message. After that, it creates a new request that is not correlated with previous orchestration.

# Question

Is it a known behavior? Am I missing something? Is there any plan on this part?

**Comment by bachuv** [comment]
Hi @cyrilcathala, are you still experiencing this issue? If so, can you provide us with the following information? Also, just to let you know, we are working on releasing a new version of Distributed Tracing with OpenTelemetry support in the next few months. You can track the progress for that [here](https://github.com/Azure/durabletask/pull/648). Once that is available, we encourage you to use that feature. Thanks!

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
- **Azure Functions runtime version (1.0 or 2.0)**:
- **Programming language used**:

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.
