### ISSUE TITLE
Scaling orchestrators / entities and activities separately

### ISSUE THREAD

**Issue by yukscck** [Azure/azure-functions-durable-extension#2006]
### Discussed in https://github.com/Azure/azure-functions-durable-extension/discussions/1974

<div type='discussions-op-text'>

<sup>Originally posted by **yukscck** October 12, 2021</sup>
Looking at how Durable Functions work, I understand that orchestrators and entity functions work on messages in the control queues, whereas the activity functions work on messages the work item queue.

Would it be possible for me to create 2 separate functionapps - 1 dedicated to executions on the control queues, the other dedicated to executions on the work item queue?

In my project, I have a situation where the executions are expected to be very busy with orchestrating tasks. When there is a high incoming load of executions, the functionapp instances with leases to partitions would be busy orchestrating tasks, but at the same time, still required to process activities from the work item queue - resulting in these different types of functions competing for resources from the same functionapp instance. These are based on what I understand about how Durable Functions work, please correct me if my understanding up to this point is inaccurate.

Understand that we could control the executions by manipulating the `maxConcurrentOrchestratorFunctions`, `maxConcurrentActivityFunctions` and `partitionCount` to control the ratio of instances working on orchestrators and activities. Would this be a way for me to "dedicate" functionapps by role?

Also worth to call out that, however, `maxConcurrentOrchestratorFunctions` and `maxConcurrentActivityFunctions` have a minimum configurable value of `1`.

Some guidance would be much appreciated.</div>

**Comment by cgillum** [comment]
Sorry for missing your question. I responded in the discussion board.
