### ISSUE TITLE
PurgeInstanceHistoryAsync and azurite

### ISSUE THREAD

**Issue by bhugot** [Azure/azure-functions-durable-extension#2007]
### Description
Purge Instance history is not working when using azurite throwing a bad request for both methods.

### Expected behavior
Should purge instance

### Actual behavior
Throw a BadRequest

### Known workarounds
> Use AzureStorageEmulator.exe

**Comment by cgillum** [comment]
This is probably a bug in Azurite's table storage support, which is relatively new. Likely we'll need to open a bug against Azurite and provide either a simple repro for them that they can easily run on their machines or (preferably) share the HTTP network traces that demonstrate the issue (using a tool like Fiddler).

**Comment by sebastianburckhardt** [comment]
We encountered this in issue #1920. The request in question was:
```csharp
await this.InstancesTable.DeleteAsync(new DynamicTableEntity
                    {
                        PartitionKey = orchestrationInstanceStatus.PartitionKey,
                        RowKey = string.Empty,
                        ETag = "*"
                    });
```
We may be able to use this to create a quick repro.

**Comment by Bygdrift** [comment]
I have just moved from VS2019 to VS2022 that uses Azurite and then bumped in to this problem and have used some hours to detect the reason to why I no longer can run `PurgeInstanceHistoryAsync`.

Is it correct, that there is no other workaround for now, than to stop using Azurite?

**Comment by davidmrdavid** [comment]
_Assigning this to myself as a lot of OOProc dev scenarios depend on Azurite._

@Bygdrift: Unfortunately we, the Durable Functions team, have no ownership of Azurite so, at the moment, I can't think of another workaround than to stop using Azurite. That said, we should open a ticket against the Azurite team to get the fix tracked.

@Bygdrift: What OS are you working on? And can you please provide or attach a simple repro for this issue? Thanks!

**Comment by bhugot** [comment]
It seems it was fixed in https://github.com/Azure/Azurite/pull/1213 so we just need a new version of it and it's working
