### ISSUE TITLE
Orchestrator runs again after exception

### ISSUE THREAD

**Issue by alexsegura1** [Azure/azure-functions-durable-extension#2008]
### Description

We're seeing an issue where an Exception is bubbled up to the Orchestrator and we see the code in the Catch being called (just a log message).  We call our activities with Retry options where the maxNumberOfAttempts = 1 which we believe to mean only run the activity once with no actual retries.

Yet after an exception is thrown in an activity and it gets to the Orchestrator and logged we see the Orchestrator run again, and sometimes even another time after that.  Why?

The log that shows the activity is started says "IsReplay: False"

### Expected behavior
An exception bubbling up to the Orchestrator will not run the activity again if maxNumberOfAttempts = 1 and orchestrator will not run again with the same InstanceId.  

### Actual behavior
The Orchestrator runs again which starts the activity again.

### Relevant source code snippets
```csharp
var retryOptions = new RetryOptions(firstRetryInterval: TimeSpan.FromSeconds(5), maxNumberOfAttempts: 1);

var fileMetaData = await context.CallActivityWithRetryAsync<Models.FileOutputMetaData>(
                                  DurableFunctionNames.GenerateReport, retryOptions, reportToProcess);
```

### App Details

- ExtensionVersion: 1.7.1:
- Microsoft Azure Webjobs 2.3.0:
- C#:

### Screenshots

![image](https://user-images.githubusercontent.com/39310711/141354341-fa5be6e1-1f01-4dc4-875d-125a75742868.png)

**Comment by amdeel** [comment]
@alexsegura1 Using CallActivityWithRetryAsync will lead to activities being retried the amount of attempts as maxNumberOfAttempts. So maxNumberOfAttempts is the amount of times the activity is to be retried, in this case 1 retry. If you do not want the activity to be retried you should use CallActivityAsync instead.

**Comment by alexsegura1** [comment]
@amdeel The Catch block is hit in the orchestrator though.  Why would it retry the activity AFTER hitting the catch block?

Also it's not the Activity being retried, it's the **entire** orchestrator.  And it's retried **twice**

**Comment by amdeel** [comment]
@alexsegura1 Is your client code restarting or rewinding your orchestrator?

Also, it looks like you're using a really old version of Durable. You should update to our latest Durable v1 package, 1.8.7 with several bug fixes and performance improvements.

**Comment by alexsegura1** [comment]
@amdeel No we are not restarting anything in our own code.  If an exception is thrown we simply alert and let a person decide if they want to try the process anew.  

We can upgrade yes and see if that alleviates anything.
