### ISSUE TITLE
Error "The function 'xyz' doesn't exist, is disabled, or is not an activity function. Additional info: The following are the known activity functions: 'a', 'z' where bindings name in function.json contains underscore

### ISSUE THREAD

**Issue by corticalstack** [Azure/azure-functions-durable-extension#2012]
### Description
For Python runtime, create a very simple activity function with function.json, example below. Fails during trigger with "The function 'xyz' doesn't exist, is disabled, or is not an activity function.".

I remove the underscore from the bindings name _blob_info_ and it works. Naming convention restrictions?

function.json

```
{
    "scriptFile": "__init__.py",
    "disabled": false,
    "bindings": [
        {
            "name": "blob_info",
            "type": "activityTrigger",
            "direction": "in"
        }
    ]
}
```

and activity function

```
import azure.functions as func
import azure.durable_functions as df

import logging
logging.Logger.root.level = 10

import json

content_type_whitelist = ['application/pdf']

async def main(blob_info):
    blob_url = blob_info.get("blob_url")
    blob_content_type = blob_info.get("content_type")
    logging.debug(f"is-valid-document-type executed {blob_url} {blob_content_type}")

    if blob_content_type in content_type_whitelist:
        logging.debug(f"is valid")
        return True
    else:
        logging.debug(f"is invalid")
        return False

```

**Comment by davidmrdavid** [comment]
Hi @corticalstack,

Thank you for reaching out. At first glance, I'm not personally aware of any naming limitations that would apply here. However, looking at the sample code, I'm not exactly sure whether this Functions is meant to be invoked by an Orchestrator, or by a Blob Binding; so I worry there might be a logical error at play.

Can you please clarify how this Functions is meant to be invoked? Furthermore, a small reproducer project attached as a `.zip` would help me diagnose this further. Thanks!

**Comment by davidmrdavid** [comment]
Following up on this old issue after some GitHub clean-up.
It does seem that my Activity Functions fail if their activity parameter name have an underscore in them.

@vrdmr - do you know if this is a limitation of the Python worker?

I'm seeing the following error when I call an Activity Function with input-parameter `my_param`:

```
Azure Functions Core Tools
Core Tools Version:       4.0.4426 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.1.3.17473


Functions:

        http_function: [POST,GET] http://localhost:7071/api/orchestrators/{functionName}

        my_orch: orchestrationTrigger

For detailed output, run func with --verbose flag.
[2022-04-27T23:50:27.141Z] The 'hello_act' function is in error: The binding name my_param is invalid. Please assign a valid name to the binding.
[2022-04-27T23:50:27.310Z] Worker process started and initialized.
[2022-04-27T23:50:31.851Z] Host lock lease acquired by instance ID '000000000000000000000000135D7DF1'.
```

**Comment by davidmrdavid** [comment]
This is my `function.json` for this Activity:

```JSON
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "my_param",
      "type": "activityTrigger",
      "direction": "in"
    }
  ]
}

```

**Comment by davidmrdavid** [comment]
Just checked and apparently this is a general limitation of Functions, and it originates in the binding-name parsing regex defined here: https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/Utility.cs#L47

I'm making a note to triple check if this naming restriction is documented anywhere. It definitely should be.
