### ISSUE TITLE
FYI @davidmrdavid and @TsuyoshiUshio. I agree this shouldn’t cause a failure.

### ISSUE THREAD

**Issue by antonyggvzvmnxxcx** [Azure/azure-functions-durable-extension#2018]
FYI @davidmrdavid and @TsuyoshiUshio. I agree this shouldn’t cause a failure.

_Originally posted by @cgillum in https://github.com/Azure/azure-functions-durable-extension/issues/1694#issuecomment-782740038_

**Comment by davidmrdavid** [comment]
Thanks for reaching out @antonyggvzvmnxxcx!

I'll need more context on this one, are you still facing the issue listed in #1694? Thanks :)
