### ISSUE TITLE
Orchestrator stuck when processing High volume data (with source code to reproduce it)

### ISSUE THREAD

**Issue by luismanez** [Azure/azure-functions-durable-extension#2020]
### Description
Orchestrator gets stuck when processing high volume data. 

I hit the issue in a production environment, but I´ve been able to reproduce the issue with a "minimal" project that you can find in this GitHub repo:
[https://github.com/luismanez/high-volume-data-durable-function-test](https://github.com/luismanez/high-volume-data-durable-function-test)

See __Relevant source code snippets__ section and the source code in the repo for more information.

This has been tested in an EP1 service plan scaled out to 20 instances in the Maximum burst option, but also happens with just 2 instances.

Thank you for your help, and happy to provide any other information and change the architecture to whatever is recommended by the Durable functions team in order to deal with these kind of scenarios.

### Expected behavior
The sub orchestrator completes, and it returns control to the Orchestrator, to continue its workflow

### Actual behavior
The sub orchestrator stucks "running". Sometimes, the sub orchestrator completes, but the main orchestrator stucks "running".

### Relevant source code snippets

First, we have a Timer trigger that fires every 20 minutes. The trigger starts the main orchestrator, but follows the Singleton pattern (copy code from MS official docs), so it first checks if the Orchestration ID (a constant) is still running. if so, does nothing, otherwise, the main orchestrator starts.

This is the main orchestrator source code. You can get more info in source code comments

```csharp
// This sub-orchestrator just simulates the creation of a very long list of Items (models/SyncWorkspaceDto.cs)
var workspacesToSync = await context.CallGetWorkspacesToSyncSubOrchestrator();
log.LogInformation($"{nameof(WorkspacesSynchronisationOrchestrator)} got workspaces to process");

// This sub-orchestrator iterates the very-long list following fan-out/in pattern. 
// For each element, calls an Activity that simulates calling an external API to get more info about that specific item
// Then, the list is iterated again (applying some filter with the data obtained in previous foreach)
// and for each element, call an Activity that simulates calling another external API to get more info about the item
workspacesToSync = await context.CallGetWorkspacesDetailedInfoSubOrchestrator(workspacesToSync);
log.LogInformation($"{nameof(WorkspacesSynchronisationOrchestrator)} got detailed info for all workspaces to process");

// fan-out/in to Persist Workspaces to DB.
// Foreach item, it calls another Activity that simulates storing the item info in SQL and Azure Search
var workspacesToPersist = workspacesToSync; // in real project, we apply some filter here
var workspacesToPersistCount = workspacesToPersist.Count();
var workspacesToPersistTasks = new Task<bool>[workspacesToPersistCount];
var workspacesToPersistTaskNumber = 0;
foreach (var workspace in workspacesToPersist)
{
    workspacesToPersistTasks[workspacesToPersistTaskNumber] =
                    context.CallPersistWorkspaceActivity(workspace);
    workspacesToPersistTaskNumber++;
}
await Task.WhenAll(workspacesToPersistTasks);
```

The first sub-orchestrator just fires an Activity that simulates the creating of a very long list of items

```csharp
    [FunctionName(Constants.AzureFunctions.Orchestrators.GetWorkspacesToSyncSubOrchestrator)]
    public async Task<IEnumerable<SyncWorkspaceDto>> RunOrchestrator(
        [OrchestrationTrigger] IDurableOrchestrationContext context,
        ILogger log)
    {
        // Just calls an Activity that simulates the creating of a very long List (see Activity for more info)
        var workspacesToSync = await context.CallGetGroupWorkspacesFromGraphActivity();

        return workspacesToSync;
    }
```

```csharp
    [FunctionName(Constants.AzureFunctions.Activities.Synchronisation.GetGroupWorkspacesFromGraphActivity.Name)]
    public async Task<IEnumerable<SyncWorkspaceDto>> Run(
        [ActivityTrigger] IDurableActivityContext activityContext,
        ILogger log)
    {
        var totalWorkspacesToProcessCount = int.Parse(Environment.GetEnvironmentVariable("NumberOfItemsToProcess") ?? "3");
        log.LogWarning($"GetGroupWorkspacesFromGraphActivity_ItemsToProcess: {totalWorkspacesToProcessCount}. InstanceId: {activityContext.InstanceId}");

        var delay = int.Parse(Environment.GetEnvironmentVariable("GetGroupWorkspacesFromGraphActivityDelayInMiliseconds") ?? "10");
        await Task.Delay(delay);
        log.LogWarning($"GetGroupWorkspacesFromGraphActivityDelay: {delay}");

        var highVolumeList = new List<SyncWorkspaceDto>();

        // Simulate calling an external API and return a High volume list of data
        // The issue happens with about 25k items. Tests were done with 30k.
        // (we have other production environments with about 10k items and are working fine)
        for (var i = 0; i < totalWorkspacesToProcessCount; i++)
        {
            highVolumeList.Add(SyncWorkspaceDto.NewFakeWorkspaceDto());
        }

        return highVolumeList;
    }
```

Once the very long list of items is returned to the Main orchestrator, a second sub orchestrator is started. This sub-orchestrator does a couple of foreach iterating all the items in the very long list and calling another activity that simulates calling an external API to get more information about the Item.

```csharp
    [FunctionName(Constants.AzureFunctions.Orchestrators.GetWorkspacesDetailedInfoSubOrchestrator)]
    public async Task<IEnumerable<SyncWorkspaceDto>> RunOrchestrator(
        [OrchestrationTrigger] IDurableOrchestrationContext context,
        ILogger log)
    {
        var workspacesToGetDetailsFor = context.GetInput<IEnumerable<SyncWorkspaceDto>>();

        var workspacesToUpdateFromGraphCount = workspacesToGetDetailsFor.Count();
        var workspacesToUpdateFromGraphTasks = new Task<SyncWorkspaceDto>[workspacesToUpdateFromGraphCount];
        var workspacesToUpdateFromGraphTaskNumber = 0;

        foreach (var workspace in workspacesToGetDetailsFor)
        {
            workspacesToUpdateFromGraphTasks[workspacesToUpdateFromGraphTaskNumber] =
                            context.CallGetWorkspaceDetailedInfoFromGraphActivity(workspace);
            workspacesToUpdateFromGraphTaskNumber++;
        }
        await Task.WhenAll(workspacesToUpdateFromGraphTasks);
        var workspacesToUpdateWithDetailedInfo =
            workspacesToUpdateFromGraphTasks.Select(t => t.Result).Where(workspace => workspace != null);

        // repeat the fan out-in. In real project, we first apply a filter over "workspacesToUpdateWithDetailedInfo"
        // that filter returns most of the items in "workspacesToGetDetailsFor", but not all of them
        // that´s why we need a 2nd fan out-in to complete the filtered list items with info from another data provider
        var workspacesToUpdateFromSharePointCount = workspacesToUpdateWithDetailedInfo.Count();
        var workspacesToUpdateFromSharePointTasks = new Task<SyncWorkspaceDto>[workspacesToUpdateFromSharePointCount];
        var workspacesToUpdateFromSharePointTaskNumber = 0;

        foreach (var workspace in workspacesToUpdateWithDetailedInfo)
        {
            workspacesToUpdateFromSharePointTasks[workspacesToUpdateFromSharePointTaskNumber] =
                            context.CallGetWorkspaceDetailedInfoFromSharePointActivity(workspace);
            workspacesToUpdateFromSharePointTaskNumber++;
        }
        await Task.WhenAll(workspacesToUpdateFromSharePointTasks);

        var workspacesWithFullInfo =
            workspacesToUpdateFromSharePointTasks.Select(t => t.Result).Where(workspace => workspace != null);


        return workspacesWithFullInfo;
    }
```

According to my tests, it gets stuck in the first fan-out/in foreach. It iterates all the items and the Activity is called and works, but then, the secord foreach is not hit, and the sub-orchestrator and main orchestrator, are _running_ forever.

This is my host.json

```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingExcludedTypes": "Request",
      "samplingSettings": {
        "isEnabled": true
      },
      "httpAutoCollectionOptions": {
        "enableW3CDistributedTracing": true
      }
    },
    "logLevel": {
      "default": "Warning",
      "Function": "Information",
      "Microsoft": "Warning",
      "Host.Aggregator": "Warning",
      "Host.Results": "Error"
    }
  },
  "functionTimeout": "00:59:00",
  "extensions": {
    "queues": {
      "maxPollingInterval": "00:00:02",
      "visibilityTimeout": "00:00:30",
      "batchSize": 16,
      "maxDequeueCount": 5,
      "newBatchThreshold": 8
    },
    "durableTask": {
      "hubName": "WorkspacesSynchronisation",
      "tracing": {
        "distributedTracingEnabled": true,
        "distributedTracingProtocol": "W3CTraceContext"
      },
      "storageProvider": {
        "connectionStringName": "DurableStorageUsageConnectionString"
      }
    }
  }
}
```

### App Details

```xml
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
  </ItemGroup>
```

- **Durable Functions extension version (e.g. v1.8.3)**: 2.5.0
- **Azure Functions runtime version (1.0 or 2.0)**: v3
- **Programming language used**: c#

### Screenshots

![storage-table-instances](https://github.com/luismanez/high-volume-data-durable-function-test/blob/main/assets/storage-table-instances.png?raw=true)

The memory and CPU usage during the test:

![service-plan-metrics](https://github.com/luismanez/high-volume-data-durable-function-test/blob/main/assets/service-plan-metrics.png?raw=true)

### If deployed to Azure

- **Timeframe issue observed**: 2021-11-21T19:52:41.129Z - 2021-11-21T23:20:54.397Z
- **Function App name**: https://durablehighvolumedata.azurewebsites.net
- **Function name(s)**: WorkspacesSynchronisationOrchestrator, GetWorkspacesDetailedInfoSubOrchestrator, GetGroupWorkspacesFromGraphActivity
- **Azure region**: West Europe
- **Orchestration instance ID(s)**: 88ECDF24-9D6B-495F-B10B-87632AA0577C
- **Azure storage account name**: durablehighvolumedata

THANK YOU!

**Comment by cgillum** [comment]
Thanks for this really detailed report! I noticed that you reproduced this using the 2.5.0 version of the extension, which is missing some important fixes. Are you able to reproduce with the latest 2.6.0 version of the Durable extension?

**Comment by luismanez** [comment]
Hey Chris! ... so glad you´re here :) Thanks a lot!

Let me try with 2.6.0 (I´ll do it in a few hours though). In the meantime, do you see something "not so good" at this approach? Is there anything that you´d do in a different way for this scenario?

**Comment by cgillum** [comment]
I don't see anything explicitly wrong with what you're doing. In general, I'd try to be careful about how frequently you pass large amounts of data as inputs or outputs to functions. You can pass as much data as we can store in memory, but it can have a big impact on performance if you do it a lot. To reduce the impact of this and to speed up your fan-in, I suggest you set [`extendedSessionsEnabled`](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#extended-sessions) to `true` in your host.json.

**Comment by luismanez** [comment]
Thanks Chris. I´ve re-tested it with version 2.6.0 of the extension, but it´s still failing.

![image](https://user-images.githubusercontent.com/9392197/142933623-e6efc5da-eb05-4893-bba4-1ca667322005.png)

The control-03 queue contains 7466 messages (in this test, the DequeueCount is 1, but it will increase over time. In prod system, I saw a value greater than 70, then I stopped the Function App)

![image](https://user-images.githubusercontent.com/9392197/142934362-79446948-8315-467b-950f-9b015a85c3a6.png)

Service plan CPU/Memory metrics look fine again (below 80%).

However, in AppInsights, I can see this trace error message a bunch of times:

```
An unexpected failure occurred while processing instance '0b170208fde449e0a8fe2874df042489:1': DurableTask.AzureStorage.Storage.DurableTaskStorageException: The operation was canceled.
 ---> Microsoft.WindowsAzure.Storage.StorageException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.Storage.Table.<>c__DisplayClass24_0`1.<<ExecuteQueryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation, AzureStorageOrchestrationServiceStats stats, String clientRequestId)
   at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String operationName, String clientRequestId)
Request Information
RequestID:
RequestDate:
StatusMessage:
ErrorCode:

   --- End of inner exception stack trace ---
   at DurableTask.AzureStorage.Storage.AzureStorageClient.MakeStorageRequest[T](Func`3 storageRequest, String operationName, String clientRequestId) in /_/src/DurableTask.AzureStorage/Storage/AzureStorageClient.cs:line 115
   at DurableTask.AzureStorage.Storage.Table.ExecuteQueryAsync[T](TableQuery`1 query, CancellationToken callerCancellationToken)
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.GetHistoryEntitiesResponseInfoAsync(String instanceId, String expectedExecutionId, IList`1 projectionColumns, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs:line 248
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.GetHistoryEventsAsync(String instanceId, String expectedExecutionId, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/Tracking/AzureTableTrackingStore.cs:line 148
   at DurableTask.AzureStorage.OrchestrationSessionManager.ScheduleOrchestrationStatePrefetch(LinkedListNode`1 node, Guid traceActivityId, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/OrchestrationSessionManager.cs:line 470
```

I can also see a bunch of these messages:

```
[HostMonitor] Host CPU threshold exceeded (96 >= 80)

Possible thread pool starvation detected.
```

However, these warning messages start appearing once the orchestrator is already stuck for some time.

In case it gives you any clue, in previous tests (2.5.0 version), sometimes I also saw issues like:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Text.Encoding.GetBytes(String s)
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.CompressLargeMessageAsync(DynamicTableEntity entity) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1401
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.UpdateStateAsync(OrchestrationRuntimeState newRuntimeState, OrchestrationRuntimeState oldRuntimeState, String instanceId, String executionId, String eTagValue) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 1195
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.CompleteTaskOrchestrationWorkItemAsync(TaskOrchestrationWorkItem workItem, OrchestrationRuntimeState newOrchestrationRuntimeState, IList`1 outboundMessages, IList`1 orchestratorMessages, IList`1 timerMessages, TaskMessage continuedAsNewMessage, OrchestrationState orchestrationState) in C:\source\durabletask\src\DurableTask.AzureStorage\AzureStorageOrchestrationService.cs:line 1087
```

```
An unexpected failure occurred while processing instance '4f665a8831e84de78e73f0d33225bf18:1': Microsoft.WindowsAzure.Storage.StorageException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at DurableTask.AzureStorage.TimeoutHandler.ExecuteWithTimeout[T](String operationName, String account, AzureStorageOrchestrationServiceSettings settings, Func`3 operation)
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.GetHistoryEntitiesResponseInfoAsync(String instanceId, String expectedExecutionId, IList`1 projectionColumns, CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 273
   at DurableTask.AzureStorage.Tracking.AzureTableTrackingStore.GetHistoryEventsAsync(String instanceId, String expectedExecutionId, CancellationToken cancellationToken) in C:\source\durabletask\src\DurableTask.AzureStorage\Tracking\AzureTableTrackingStore.cs:line 161
   at DurableTask.AzureStorage.OrchestrationSessionManager.<>c__DisplayClass23_0.<<ScheduleOrchestrationStatePrefetch>b__0>d.MoveNext() in C:\source\durabletask\src\DurableTask.AzureStorage\OrchestrationSessionManager.cs:line 495
```

BTW, we tried the _extendedSessionsEnabled__ setting in our Prod environment. It helped a bit (we got further), but got stuck too.

Any idea? can I send you any other data to help you diagnose the issue?

Thanks again.

**Comment by cgillum** [comment]
Thanks for trying the update @luismanez! That helps narrow down the issue.

One thing I forgot to mention is that I recommend you take a look at the [Azure Functions Diagnose and Solve problems tool](https://docs.microsoft.com/en-us/azure/azure-functions/functions-diagnostics). We have automatic analysis of potential Durable Functions issues. I took a look at our internal view of this information and noticed a couple things (and have some new suggestions):

* It looks like you have multiple apps sharing the same task hub and storage account (`*-wsf-cp-qasr`, `*-wsf-ggs-prod`, `*wsf-cp-dev`, `*-wsf-cp-qa`, and `*-wsf-cp-secops`). This could definitely cause contention in your app. Normally we advise that each app have its own task hub at least. Since you're doing high-volume data processing, you may want to give each app its own storage account too.
* It looks like your sub-orchestrator `0b170208fde449e0a8fe2874df042489:1` might be having trouble loading its history. I'm seeing history lengths of around 55K at latencies over 100 seconds trying to read them all in. The long history lengths are probably creating a lot of memory pressure and storage throughput contention, not to mention any contention caused by other apps sharing the same account. In addition to my previous recommendation, I suggest reducing the breadth of your fan-out for creating sub-sub-orchestrators such that you're never fanning out to more than 1,000 tasks in a single orchestration instance.

**Comment by luismanez** [comment]
Thanks Chris.

About 1st point, unless I did something wrong, the Storage is only used by my test app. I created a brand new Resource Group with new Function App, Plan, Storage and App Insights. Maybe the confusion is because we have other environments with our solutions deployed, and the TaskHub name is always the same one "WorkspaceSynchronisation", and the same Orchestration ID. All those Storage acocunt that you mention, are other environments in a separate resource group, and some of them even a separate Az Subscription.

I´ve tried the "sub-sub-orchestrator" approach :), but it didn´t work either. 
In the _GetWorkspacesDetailedInfoSubOrchestrator_, instead of doing the fan out/in with the 30k items, I´m splitting in chunks of 1k items, and calling the sub-sub orch.

```csharp
            var workspacesToGetDetailsFor = context.GetInput<IEnumerable<SyncWorkspaceDto>>();

            //Splitting the total amount of workspaces into arrays of length 1000
            var workspacesToGetDetailsForPages = workspacesToGetDetailsFor.ChunkBy(1000);

            var workspacesToGetDetailsForPagesResults = new List<IEnumerable<SyncWorkspaceDto>>();
            foreach (var workspacesToGetDetailsForPage in workspacesToGetDetailsForPages)
            {
                var workspacesToGetDetailsForPageResult = await context.CallGetWorkspaceDetailedInfoFromGraphSubOrchestrator(workspacesToGetDetailsForPage);
                workspacesToGetDetailsForPagesResults.Add(workspacesToGetDetailsForPageResult);
            }

            var workspacesWithFullGraphInfo = workspacesToGetDetailsForPagesResults
                .SelectMany(t => t);

            //Splitting the total amount of workspaces into arrays of length 1000
            var workspacesToGetDetailsForSharePointPages = workspacesWithFullGraphInfo.ChunkBy(1000);

            var workspacesToGetDetailsForSharePointPagesResults = new List<IEnumerable<SyncWorkspaceDto>>();
            foreach (var workspacesToGetDetailsForSharePointPage in workspacesToGetDetailsForSharePointPages)
            {
                var workspacesToGetDetailsForSharePointPageResult = await context.CallGetWorkspaceDetailedInfoFromSharePointSubOrchestrator(workspacesToGetDetailsForSharePointPage);
                workspacesToGetDetailsForSharePointPagesResults.Add(workspacesToGetDetailsForSharePointPageResult);
            }

            var workspacesWithFullInfo = workspacesToGetDetailsForSharePointPagesResults
                .SelectMany(t => t);


            return workspacesWithFullInfo;
```

Then, the sub-sub orch, is the one doing the fan out/in (input will be just 1k items).

With this approach, we still get stuck, and I can see more _OutOfMemory_ issues in AppInsights

![image](https://user-images.githubusercontent.com/9392197/143030944-ac9fc6d9-69b7-4a8e-b476-1c43a4f93485.png)

![image](https://user-images.githubusercontent.com/9392197/143031134-738af811-aebf-4278-84ab-368e11309c12.png)

**Comment by cgillum** [comment]
> About 1st point, unless I did something wrong, the Storage is only used by my test app.

I took a second look and you're right. These storage accounts are not being shared. I think the logic which checks for this saw the same instance ID being used across all apps and made incorrect conclusions based on this. I'll look into having that detection updated.

> I´ve tried the "sub-sub-orchestrator" approach :), but it didn´t work either.

I can confirm that this at least fixed the long history load problems which were being reported earlier, so if nothing else there was at least some improvement. :)

At this point it might make sense for us to focus on the OutOfMemory exceptions. Looking at the specific exception messages, they appear to happen when trying to read the large payloads being passed between your functions. Reducing those payload sizes could help, but another thing we can try that doesn't involve changing your code is reducing some of the default concurrency settings. We document how to do this [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#concurrency-throttles). Can you try reducing orchestration and activity concurrency numbers in host.json to see if that helps? Specifically:

* maxConcurrentActivityFunctions
* maxConcurrentOrchestratorFunctions
* controlQueueBufferThreshold

See if setting those to really small numbers helps resolve the out-of-memory issues.

**Comment by luismanez** [comment]
I´ve tested it with the following values:

```json
    "durableTask": {
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 30,
      "maxConcurrentActivityFunctions": 2,
      "maxConcurrentOrchestratorFunctions": 1,
      "hubName": "WorkspacesSynchronisation",
      "tracing": {
        "distributedTracingEnabled": true,
        "distributedTracingProtocol": "W3CTraceContext"
      },
      "storageProvider": {
        "connectionStringName": "DurableStorageUsageConnectionString",
        "controlQueueBufferThreshold": 8,
        "controlQueueBatchSize": 4 // cannot be larger than "ControlQueueBufferThreshold"
      }
    }
```

but with no luck. A bunch of __OutOfMemory__ exceptions

![image](https://user-images.githubusercontent.com/9392197/143230495-656cd13a-ff24-4d3f-95bc-e125fc4f46ba.png)

![image](https://user-images.githubusercontent.com/9392197/143230026-f068447a-30e8-47a5-8050-1c8860115422.png)

Anything else we can try ??

**Comment by cgillum** [comment]
Looking at the callstack for the OutOfMemoryException, my guess is that some function input or output is so large that it's pushing us over the edge in terms of memory. Without digging further into that, the only other thing I can suggest is to try reducing `controlerQueueBufferThreshold` and `controlQueueBatchSize` both all the way down to `1`.  Otherwise, I think you may need to find a way to use smaller payloads.

As for the "Non-Deterministic workflow detected" error, this is possibly from an older orchestration instance that was created using an earlier version of your code which failed when the new version was deployed?

**Comment by luismanez** [comment]
Testing it right now with those 2 settings set to 1 ... it will take some time till get the results.

About the "Non-deterministic" issue. It shouldn´t be that case, as every time I push some new code, I stop the Function App, and remove Tables, Queues and Blobs, then I publish using VS, so, it shouldn´t be a _versioning_ issue... no idea :)

I´ll let you know how this new test goes (likely tomorrow. it´s 10 p.m here in Spain :D)

**Comment by luismanez** [comment]
Last test didn´t work either. It got stuck again after 5 hours processing. The curious thing is that now, I only see one __OutOfMemory__ exception (more or less the same timestamp it got stuck).

Also, I´m wondering why the sub-sub-orchestrator takes so long to complete. Here are some rows from the History table, and if you see the Created time, and the Completed time, it takes always more than 2 minutes to complete the sub-sub orch:

![image](https://user-images.githubusercontent.com/9392197/143409358-f81cb265-42ff-4c3d-88d2-4cf251dd9d17.png)

This sub-sub orch, is taking 1000 items, doing a foreach with fan-out/in approach, and for each element, the Activity invoked just waits for 5 ms. If we ignore the fan out-in, and we think about processing 1000 items and waiting 5ms per item, it means just 5 seconds to process 1000 items. I imagine there are IO operations with Tables, Queue, AppInsights... but 5 seconds vs almost 3 minutes, it´s a huge difference. Does it seem expected to you? or gives any other clue?

Making the objects smaller, is not an easy one. I´m gonna test a change in the overall process, in order to move less data (avoiding less List of WorkspacesSyncDto)... Let´s see how it goes.

Thanks again.

**Comment by cgillum** [comment]
Looking at the DurableTask.AzureStorage logs for 07a032b20e4c4d649794487be73d9990:0, it seems to me that the latency is caused by steadily increasing queue lengths. For example, your activities are getting queued up in the **workspacessynchronisation-workitems** queue but its taking time for your workers to pick them up and execute them. For example, I'm seeing delays of > 15 seconds for individual activity function calls waiting to be executed.

I suspect this could be related to the reduced value of `maxConcurrentActivityFunctions` in your host.json. The way to speed this up would be to either increase the concurrency of activity functions (which could put you at greater risk of out-of-memory problems if activity functions are a source of high memory usage) or scale-out to a larger number of worker instances. From what I can see, most of your activities are only running on one or maybe two worker instances, which means concurrency will be very poor, leading to poor throughput.

**Comment by luismanez** [comment]
Thanks Chris. We have finally managed to workaround-ed the problem by reworking the sub-orchestrators structure and we also set the host.json settings back to its defaults (no extended session nor concurrency limits).

We based the changes on the idea of avoiding a sub-orchestrator to have to handle an output greater than 1,000 activities. Besides, we also limit the concurrency in code to finish the processing of those 1,000 activities before queueing another batch.

The new structure is made of a main orchestrator, an intermediate sub-orchestrator and a sub-sub-orchestrator that makes calls to the activities. The new structure looks like this:
  - Main orchestrator
    - Loop of calls to "Intermediate sub-orchestrator", sending 330 elements each time (330 because we call 3 activities inside the orchestraror, and we want to avoid more than 1000 activities).
      - var batches = totalItems in chunks of 330 items
      - foreach (var batch in batches) { await context.IntermediateSubOrchestrator(batch) }
  - Intermediate sub-orchestrator
    - Fan in/out of "Sub-orchestrator" (concurrent). 990 (330 x 3) activities will be run in each sub-orchestrator concurrently.
      - foreach (var item in batch) { itemTasks.Add(context.SubOrchestrator(item)) }
      - await Task.WhenAll (itemTasks)
  - Sub-Sub-orchestrator
    - await Activity 1
    - await Activity 2
    - await Activity 3

Having this new structure we achieved the code to be running without any interrruptions for more than 3 days. Besides, no exceptions have been detected either (we didn't have CPU and memory issues).

Please, could you have a thought and let me know if your foresee any potential issue with this workaround ??

Also a couple of suggestions after all this journey:
  - I´d love to have a "real-world" sample from MS on processing High-volume data. I think my scenario is pretty common in large organizations moving data between systems, so you have a process that returns a huge list of data, and then you want to process each item as fast as possible. I´ve seen this sample [https://docs.microsoft.com/en-us/samples/azure-samples/durablefunctions-mapreduce-dotnet/big-data-processing-serverless-mapreduce-on-azure/](https://docs.microsoft.com/en-us/samples/azure-samples/durablefunctions-mapreduce-dotnet/big-data-processing-serverless-mapreduce-on-azure/) ... but this is not the same. It just processes 12 csv files, each csv file has thousands of rows, but all of them are processed in just one Activity.
  - As we saw in my sample. The problem is Huge volume data + big input/output objects. It´d be great to have some thresholds. I know it depends on the VM, but I guess you could provide some thresholds (i.e: the serialized object cannot be bigger than 1Mb...)

**Comment by luismanez** [comment]
Hi @cgillum 
I´d appreciate your last thought in this one, so we can close the issue. This is pretty critical for our product running in big clients.
Many thanks again.

**Comment by cgillum** [comment]
> Please, could you have a thought and let me know if your foresee any potential issue with this workaround ??

I don't foresee any issues with this workaround and I'm happy to hear that it seems to be working well so far (though I wish it weren't necessary to employ such workarounds - though that's something we need to find ways to improve on our side).

Feedback taken - we're aware that we need to produce more "real-world" samples, especially for workloads dealing with large batches of data. /cc @anthonychu.

Rather than introducing new thresholds, we're aiming to make scenarios "just-work" more reliably by introducing more memory efficiency, throttling, etc. so that folks don't have to worry as much about the size of their objects. There's technically no reason for us to introduce a threshold since we don't have any limits that force us to. Rather, the trick is ensuring that the system behaves in an expected way when objects do become too large (that said, we can certainly add some concrete recommendations in the docs).

**Comment by luismanez** [comment]
Many thanks for the final thoughts @cgillum. Makes sense, and I can´t agree more. Let me know if I can help you and @anthonychu with whatever (early tester :)). Closing the issue, and looking forward to hear from the team about improvements and new samples.
Best!
