### ISSUE TITLE
Scalability of Entity functions

### ISSUE THREAD

**Issue by yukscck** [Azure/azure-functions-durable-extension#2021]
### Description
I have an application that uses Entities to track the statuses of each orchestration of a process as they get executed. At the beginning of the orchestration, the application would signal the entity function indicating an orchestration has "Started", and as the orchestration goes down certain execution path, the entity function would be signaled again to update the orchestration's status, like "Terminated", "Completed", etc.

The purpose of the tracking is so that, when needed, the application could gather all orchestrations started for a process. For example, when an HTTP Trigger exposed in that application gets called, we could take actions based on the statuses tracked. The tracking entity function is designed with `UserId:ProcessId` as the format of the EntityId (i.e. `@OrchestrationTracker@<UserId>:<ProcessId>`) - so that we could find out information of all orchestrations started based on a specific process by a specific user.

In the event where a particular process starts a high number of orchestrations, it is noticeable from my monitoring that one of the control queues would have substantially more than the other queues. Through investigation, a big portion of the messages in the control queue mentioned are `DurableTask.Core.History.EventRaisedEvent` for the tracking entity function.

Based on my understanding, Durable Functions decide which control queue a message should be sent to by hashing the orchestration's instance ID. Same should apply to entity functions, since they are essentially a type of orchestration as well. In this particular case, for every orchestration of my process started, an entity function call is scheduled, and depending on the execution flow, more subsequent calls are scheduled to the same entity function. Unlike orchestration, where each execution is expected to have a unique identifier, an entity function relies on the same identifier to execute logic for the same entity, i.e. `@OrchestrationTracker@UserId:ProcessId`.

Usually, in the context of a queue-based application, when the application is under a high load, the application could be scaled out to have more workers to process tasks in the queue. However, in the case of Durable Functions, each control queue are leased and would be processed by a dedicated worker. In other words, scaling out the application would not increase the compute power, since each control queue could only be polled by one worker.

Is the use of Entity functions not suitable for such use cases? Appreciate advice how to better approach the design of this application.

### Known workarounds

I could put some rate limiter at the entry point where the application accepts requests to start orchestrations, but throughout the orchestration execution, entity functions are called at multiple places - making the rate where entity functions getting called less predictable.

One workaround on the design that I am currently looking at, is by using Activity functions for solving the problem with tracking above.

### Relevant source code snippets

Below are some sample codes I cooked up to help paint the picture of my use case.

```csharp
public class SubmitOrderAPI
{
    private readonly ILogger logger;

    public SubmitOrderAPI(ILogger<SubmitOrderAPI> logger)
    {
        this.logger = logger;
    }

    [FunctionName(nameof(SubmitOrderAPI))]
    public async Task<IActionResult> Run(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)] HttpRequest req,
        [DurableClient] IDurableOrchestrationClient client)
    {
        using StreamReader reader = new(req.Body);

        string stringBody = await reader.ReadToEndAsync();

        JObject body = string.IsNullOrWhiteSpace(stringBody) ? new JObject() : JObject.Parse(stringBody);

        string instanceId = await client.StartNewAsync<dynamic>(nameof(ProcessOrder), body);
        
        logger.LogInformation($"{nameof(ProcessOrder)} started. InstanceID: {instanceId}");

        return new OkObjectResult(new
        {
            instanceId,
        });
    }
}

public class ProcessOrder
{
    private readonly ILogger _logger;

    public ProcessOrder(ILogger<ProcessOrder> logger)
    {
        _logger = logger;
    }

    [FunctionName(nameof(ProcessOrder))]
    public async Task Run([OrchestrationTrigger] IDurableOrchestrationContext context)
    {
        _logger.LogInformation($"{nameof(ProcessOrder)} triggered.");

        JObject input = context.GetInput<JObject>();

        string customerId = input.Value<string>("customerId");
        string orderId = input.Value<string>("orderId");

        // Track the start of the "ProcessOrder" orchestration.
        context.SignalEntity(new EntityId(nameof(OrderTracker), customerId), nameof(OrderTracker.Track), (orderId, OrderStatus.Created));

        // More order processing logic.
        // ...
        // ...

        // Track the end of the "ProcessOrder" orchestration.
        context.SignalEntity(new EntityId(nameof(OrderTracker), customerId), nameof(OrderTracker.Track), (orderId, OrderStatus.Processed));
    }
}

public class OrderTracker
{
    public Dictionary<string, OrderStatus> Orders { get; set; } = new();

    public void Track((string OrderId, OrderStatus Status) order)
    {
        this.Orders[order.OrderId] = order.Status;
    }

    public Dictionary<string, OrderStatus> List()
    {
        return this.Orders;
    }

    [FunctionName(nameof(OrderTracker))]
    public static Task Run([EntityTrigger] IDurableEntityContext ctx) => ctx.DispatchAsync<OrderTracker>();
}

public enum OrderStatus
{
    Created = 0,
    Processed = 1,
}
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.5.1
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

**Comment by davidmrdavid** [comment]
Thanks for reaching out @yukscck!

Let me loop in @sebastianburckhardt as I believe he'd have the right context to answer this question.

**Comment by davidmrdavid** [comment]
In the meantime, I'll provide my perspective here.

I believe your summary of the scaling behavior is pretty much what we're describing in our [scalability and performance docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale). In general, if you're sending a lot of messages to the same entity, I'm not surprised that this entity's control queue is getting a disproportionate number of messages.

Also, when you say:
> In other words, scaling out the application would not increase the compute power, since each control queue could only be polled by one worker.

That rings correct to me. In general, "compute" under Durable Functions occur via Activities, which have different scaling characteristics compared to orchestrators/entities. Orchestrator and Entities aren't design to encapsulate compute-power, they're supposed to drive a workflow forward and encapsulate small pieces of state.

Finally, as for workarounds, I wonder if the issue here is in the **direction** of requests. It seems that, in your current arrangement, orchestrators are requesting Entities to do work at arbitrary intervals, which is overloading that Entities' control queue. A different approach would be if the Entity instead requested the state of its associated orchestrators at a regular time interval. So, instead of orchestrators telling Entities to update its state, the Entity updates its state in some time interval by "pinging" orchestrators for their current state. I think this would mitigate the scalability problem you're seeing. For this, I believe it should be possible to use the [ListInstancesAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.listinstancesasync?view=azure-dotnet) API from within your Entity.

Please let me know what you think! Thanks :)

**Comment by sebastianburckhardt** [comment]
Yes, you are right, @yukscck using a single entity to process a lot of messages can create a bottleneck.

That said, engineering is about picking the simplest solution that will scale *sufficiently* for your application. Nothing scales to infinity anyway. So, before doing something significantly more complicated than what you have now, it makes sense to confirm that you really do need that extra scale.   

Depending on what your actual load is, a single entity may still be enough. The Azure Storage backend is known to have limited scalability (in particular, control queue throughput is not stellar). Our [new storage providers] (https://techcommunity.microsoft.com/t5/apps-on-azure/new-storage-providers-for-azure-durable-functions/ba-p/2382044), (in particular the Netherite provider) can process many more entity messages per second, even on a single entity.

If you are looking for a design that scales past the throughput limits of a single entity, the standard trick is to use *partitioning*. Here this means that you create some number of entities (e.g. 20) and have them share the load, by distributing the messages over them (for example, you can use hashing on the sending orchestration instance id to determine which entity to send information to, which balances the load somewhat evenly). Each of those entities can maintain its own count and do its own throttling if desired. 

Depending on what your actual load is, a single entity may still be enough. The Azure Storage backend is known to have limited scalability (in particular, control queue throughput is not stellar). Our [new storage providers] (https://techcommunity.microsoft.com/t5/apps-on-azure/new-storage-providers-for-azure-durable-functions/ba-p/2382044), (in particular the Netherite provider) can process many more entity messages per second, even on a single entity.

**Comment by yukscck** [comment]
Thanks @davidmrdavid @sebastianburckhardt for the quick response! I'm glad my understanding on how things work are correct.

The idea of reversing the direction of information sounds tempting. My concern with this will be the number of results the `ListInstancesAsync` would return would be very huge, and the application will need to perform quite some bit of filtering to get the orchestration instances that the request is interested in (i.e. `<UserId>:<ProcessId>` according to my initial message). Based on the `ListInstancesAsync` API doc, I could leverage `InstanceIdPrefix` as one of the filtering conditions, but looks like I will have to change the design of my main orchestrator to use a specific instance ID format for this to work.

As for the idea of partitioning to multiple entities, it sounds like a relatively smaller change to meet the objective of reducing contention on a specific control queue. Going back to the context of my use case, I imagine the part of the codes for signaling the Entity will be added with abstraction that handles partitioning on `EntityId` (i.e. `<UserId>:<ProcessId>:<Partition>`), and whereas the HTTP Trigger that reads the Entity will now be fetching and aggregating information all the partitions.

Really appreciate the suggestions you have provided - I will bring these ideas to my team!

Allow me to ask another related question, which doesn't seem like an existing feature, so I guess probably more around the future of the Durable Functions. In my application, I have the main orchestrator that is in charge of executing the main processes that are critical to the business process, along with activity functions to help with the process. The tracker entity function, along with some other functions (e.g. cleanup functions) are what I'd consider "auxiliary functions" to my application.
The issue brought up in this thread where the tracker entity function clogging the queue has caused a portion of the main, critical orchestration to be held up. As a result, users were complaining their processes got delayed.

I have been considering moving these "auxiliary functions" out to a separate task hub, so that the main functionapp continues to service the critical work load, whereas the other functionapp servicing the task hub with "auxiliary functions" can work on a different pace. I understand that, today, `IDurableClient` is capable of scheduling tasks across separate task hubs. This has provided great flexibility to call `SignalEntityAsync` or `StartNewAsync`, for example, on a separate task hub. However, using `IDurableClient.SignalEntityAsync` seems to be violating the orchestration constraint (using non-DurableOrchestrationContext Async APIs).

Is it in the roadmap of Durable Functions to add support for `SignalEntityAsync` for cross-functionapp scenarios? Or, alternatively, is there a _safe_ way which I could make a call to either `CallActivityAsync` or `CallHttpAsync`, that has similar fire-and-forget characteristics like the `SignalEntity` in `DurableOrchestrationContext`?

**Comment by olitomlinson** [comment]
@yukscck Moving those "auxiliary" behaviours out of the core application is exactly what I was going to suggest.

---

> "so that we could find out information of all orchestrations started based on a specific process by a specific user"

It seems like you have an observability problem here!

If you are _only_ interested in observing the Orchestration run time status changes (i.e. starting, running, completed, failed etc) I would recommend utilising the [Orchestration lifecycle events](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-event-publishing?tabs=csharp-script) to get Orchestration status changes "out" of your core application. 

Then, The world is your oyster with regards to how you parse & aggregate these events into the various metrics that you need to address your original observability goal.

My first attempt would be to recycle your existing work with Durable Entities and see if you get a decent solution from that.

Alternatively, you could do really cutting edge stuff such as connecting the Lifecycle Grid Events to Azure Stream Analytics (via Event Hubs) and then using ASA to generate aggregates on the fly using temporal windows which you can push straight to your dashboards or other monitoring systems etc etc <-- I did a similar thing so I could see the rate of Orchestrations in-progress and completing per 10 second window, which was for a high-throughput Durable Functions based system.

**Comment by davidmrdavid** [comment]
Thanks everyone for your input, and +1 to @olitomlinson's suggestion.

@yukscck, before answering your question about future Durable Function APIs, can you please clarify what you meant by "using IDurableClient.SignalEntityAsync seems to be violating the orchestration constraint (using non-DurableOrchestrationContext Async APIs)." ? It's not immediately obvious to me what constraint is being violated.

I think that an illustrating example would help, thanks!

**Comment by yukscck** [comment]
Sure @davidmrdavid. What I meant was, in an orchestrator, we are not supposed to be making calls to any async methods and await for them, unless they are async methods in `DurableOrchestrationContext`.

For example,
```
[FunctionName(nameof(ProcessOrder))]
public async Task Run(
    [OrchestrationTrigger] IDurableOrchestrationContext context,
    [DurableClient] IDurableClient client)
{
    // Some logic here.

    // This is valid.
    await context.CallEntityAsync(new EntityId(nameof(OrderTracker), customerId), nameof(OrderTracker.List), (orderId, OrderStatus.Created));

    // This is illegal.
    await client.SignalEntityAsync(new EntityId(nameof(OrderTracker), customerId), nameof(OrderTracker.List), (orderId, OrderStatus.Processed));
}
```

**Comment by olitomlinson** [comment]
@yukscck 

I believe you could move the call to `IDurableClient.SignalEntityAsync` into a standard `Activity`.

If you really did want this aspect of the code to be truly fire and forget then you could wrap the Activity call in a `try..catch` block and simply swallow any Exception.

**Comment by yukscck** [comment]
@olitomlinson thanks for the suggestion!

Relating back to the question I originally posted, I was hoping to have a way to make a call to an Entity that's residing in a separate functionapp. Something like:
```
[FunctionName(nameof(ProcessOrder))]
public async Task Run(
    [OrchestrationTrigger] IDurableOrchestrationContext context,
    [DurableClient] IDurableClient client)
{
    // OrderTracker resides in another functionapp.
    await context.CallEntityAsync(new EntityId(nameof(OrderTracker), customerId), nameof(OrderTracker.List), (orderId, OrderStatus.Created));
}
```
I asked because `DurableClient` allows calling SignalEntity on entities that are on a different functionapp. I was hoping a similar level of functionality can be introduced in `IDurableOrchestrationContext` as well.

So based on your suggestion, I imagine it would be:
```
[FunctionName(nameof(ProcessOrder))]
public async Task Run(
    [OrchestrationTrigger] IDurableOrchestrationContext context,
    [DurableClient] IDurableClient client)
{
    // Schedule an activity to call the OrderTracker Entity which resides in another functionapp.
    await context.CallActivityAsync(nameof(CallOrderTrackerActivity), (orderId, OrderStatus.Created));
}
```

Will it be safe if the `context.CallActivityAsync` is not awaited, in this case?

**Comment by davidmrdavid** [comment]
cc'ing @cgillum for the question above ^.
@cgillum: The question is - can an Activity be invoked in a fire-and-forget manner by skipping the `await` statement. I believe the answer is 'no', but I want make sure.  Thanks!

**Comment by sebastianburckhardt** [comment]
As far as I know, it is safe to not await an activity result in the orchestrator.

**Comment by cgillum** [comment]
Correct, you can certainly skip the `await` statement. In fact, you must do this in order for fan-out to be possible.

One important caveat is that orchestrations will not transition from the "Running" state to the "Completed" state until all outstanding activity functions have completed, regardless of whether you await them or not. In that sense, it's not really "fire-and-forget" but more like "fire and do something else while it runs".

**Comment by lilyjma** [comment]
@yukscck - I'm closing this issue because you question seems to have been answered. Please reopen if needed. Thanks!
