### ISSUE TITLE
Poor exception message when entity function binding fails

### ISSUE THREAD

**Issue by ahaeber** [Azure/azure-functions-durable-extension#2023]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

When the binding in an entity class fails the exception message is very hard to understand.

### Expected behavior
> A clear and concise description of what you expected to happen.

An exception message that makes it clear that there was an error with creating the binding. I was mislead to believe that it couldn't resolve the type for the binding.

If possible, more details from the binding itself (in this case Azure Storage) could be helpful since it probably knows what went wrong. I looked at the stacktrace and although there are inner exceptions I couldn't find anything related to Azure Storage itself.

### Actual behavior
> A clear and concise description of what actually happened.

When the binding in an entity class fails the exception message is very hard to understand:
`System.Private.CoreLib: Exception while executing function: MyEntity. Microsoft.Azure.WebJobs.Extensions.DurableTask: One or more operations failed. (Failed to construct entity state object: Unable to resolve service for type 'Microsoft.Azure.Storage.Blob.CloudBlobContainer' while attempting to activate 'Whatever.Entities.MyEntity'.) `

Documentation for binding in entity classes can be found at https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities#bindings-in-entity-classes

The wording in `Unable to resolve service for type 'Microsoft.Azure.Storage.Blob.CloudBlobContainer'` suggests to me that it could not find the type. Because there are multiple SDKs for Azure Storage, e.g. Microsoft.Azure.Storage.Blob vs Microsoft.WindowsAzure.Storage.Blob, I thought the problem was using the wrong class. Actually what was wrong here was that the blob container in the path did not exist and the file access was set to read-only.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.6.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3.0.3904
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment]
@ahaeber can you share the code you wrote that reproduces this problem? Also, is this issue reproducible in non-entity function types, like HTTP-trigger functions?

**Comment by ahaeber** [comment]
Unfortunately I failed to reproduce this in a separate project.
