### ISSUE TITLE
Durable Functions v4 Task Stays Scheduled

### ISSUE THREAD

**Issue by marcroussy** [Azure/azure-functions-durable-extension#2037]
### Description
We have a durable functions project running in .NET 6, with 64 bit enabled on the Function App, that seems to hang when scheduling a task. 

### Expected behavior
The task should either complete successfully or fail.

### Actual behavior
The task remains in the TaskScheduled state as seen in Durable Functions Monitor. 

### Known workarounds
Setting the function app & code to run in 32bit instead of 64bit seems to solve the problem.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.6.0
- **Azure Functions runtime version (1.0 or 2.0)**: 4
- **Programming language used**: C# .NET 6

### Screenshots
We've discussed this issue Maxime Rouiller and he can provide screenshots and a video as well as telemetry information retrieved from application insights and the storage account where the function app is running.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Azure region**: East US 2
- **Orchestration instance ID(s)**: 2f6f1237c1694ca39540b5eb1b949f77

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by MaximRouiller** [comment]
Thanks @marcroussy for taking the time to do this. I've tagged the team internally with the private info you sent me.

**Comment by amdeel** [comment]
Hey @marcroussy. It looks like you were experiencing OutOfMemoryExceptions during this time. Just checking in to make sure, you haven't experienced this issue again since switching your app to 32bit, correct?

**Comment by marcroussy** [comment]
That's correct, the issue goes away when on 32bit. 

My main concern is there doesn't appear to be any way for us to see that it encountered an out of memory exception. In the video that Maxime made available to you, that was the first time I actually saw that it was an OutOfMemory that's happening. Most of the time, it just looks like the task is stuck in TaskScheduled.

**Comment by cgillum** [comment]
Closing since the issue appears to be understood.

**Comment by MaximRouiller** [comment]
@cgillum So, if a task reach an OutOfMemory and doesn't resume execution seems to be a problem, no? I just want to have the opportunity to discuss this before we close this issue permanently. 

Thanks
