### ISSUE TITLE
Race condition: HTTP triggers fail on cold-starts

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#205]
When running in the consumption plan, I sometimes notice that HTTP requests to start new orchestration instances fail because the target orchestration is not known.  If I wait a few seconds and try again, it succeeds.

I believe this is a race condition in the startup path of the Azure Functions host, where HTTP triggers can start executing before all extensions have finished loading. To fix this, the `DurableOrchestrationClient` and potentially the `DurableOrchestrationContext` API calls should have logic to wait for the listener to finishing starting up before attempting to perform their respective actions.

**Comment by cgillum** [comment]
I think the fix requires coordination between calls to StartNewAsync, CallActivityAsync, CallSubOrchestrationAsync, etc. with listener startup. Specifically, these calls should block until _at least_ [DurableTaskExtension. StartTaskHubWorkerIfNotStartedAsync](https://github.com/Azure/azure-functions-durable-extension/blob/master/src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs#L448) is called. A [ManualResetEvent](https://docs.microsoft.com/en-us/dotnet/standard/threading/manualresetevent-and-manualreseteventslim) could be used as a simple coordination primitive to block calls to [AssertOrchestratorExists](https://github.com/Azure/azure-functions-durable-extension/blob/f2b342eb922b766d47312f1b4723b9ac15ff997c/src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs#L395) or [ThrowIfInvalidFunctionType](https://github.com/Azure/azure-functions-durable-extension/blob/f2b342eb922b766d47312f1b4723b9ac15ff997c/src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs#L408)

But even this is imperfect. It's possible that the extension's internal task hub worker has finished starting up, but not all the orchestrator or activity functions have been registered. I don't know how likely this is, but it seems possible. Unfortunately the only way to truly fix this would be to know when the functions host is done initializing. I don't believe any such hook exists today in the functions host, which is the big challenge. If we can't get such a hook, then we should consider waiting up to 5 seconds after our internal task hub worker finishes completing before throwing these validation exceptions.

**Comment by gled4er** [comment]
Hello @cgillum ,

Thank you very much for assigning the issue for me.

It sounds very exciting! 

May I ask you for recommendation who will be a good contact in Azure Functions team to check about the hook?

Thank you!

**Comment by cgillum** [comment]
@mathewc, any thoughts on this scenario? I assume HTTP triggers are allowed to run before the host finishes initializing to make cold-start faster, but in my case this creates some pretty ugly race conditions for my built-in web hooks.

Would it be possible to add a simple hook or notification that my extension code could use to know when the host has finished initializing? More specifically, I need to know when all the functions have been indexed.

**Comment by mathewc** [comment]
You are right - http functions are delayed until the host is initialized just enough to enable direct function invocations (listeners not started yet). This is based on [ScriptHostManager.CanInvoke](https://github.com/Azure/azure-functions-host/blob/749564ab175f7c0d2e4ef811cb33f354e460803f/src/WebJobs.Script/Host/ScriptHostManager.cs#L144). This will return true once function indexing has happened in the core SDK and extensions have been loaded. However it doesn't wait for listeners to start.

**Comment by cgillum** [comment]
Thanks, so is there any way for us to know when the listeners have all started or would that be a new feature request on the host?  Or are you saying `OnHostInitialized` can give us that signal?

**Comment by gled4er** [comment]
Hello @mathewc ,

I just wanted to follow up on this discussion and get your opinion if we can use `OnHostInitialized` or actually we will need to request a new feature.

Thank you!

**Comment by mathewc** [comment]
Chris and I discussed, and I explained that the initialization he is doing really belongs outside of the listener startup phase of host initialization. I think the plan is to refactor the binding to do the initialization at index time which should resolve this issue without any platform changes (i.e. no new feature needed).

**Comment by cgillum** [comment]
This basically requires some refactoring.

@gled4er, right now we call [RegisterActivity](https://github.com/Azure/azure-functions-durable-extension/blob/62b95a022ffe9201dcb43a349e1fa3237031d410/src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs#L392) and [RegisterOrchestration](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs#L379) as part of [DurableTaskListener.StartAsync](https://github.com/Azure/azure-functions-durable-extension/blob/62b95a022ffe9201dcb43a349e1fa3237031d410/src/WebJobs.Extensions.DurableTask/Listener/DurableTaskListener.cs#L37). Instead, I believe we need to do the registration much earlier, like in [OrchestrationTriggerAttributeBindingProvider.TryCreateAsync](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/Bindings/OrchestrationTriggerAttributeBindingProvider.cs#L32) and [ActivityTriggerAttributeBindingProvider.TryCreateAsync](https://github.com/Azure/azure-functions-durable-extension/blob/62b95a022ffe9201dcb43a349e1fa3237031d410/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs#L36).

This needs to be done carefully to consider the case where the host recycles or when function.json is modified. I believe those actions cause the listeners to recycle, and that impacts the registration status of activity and orchestrator functions. We basically need to make sure these scenarios continue to work even though we're moving indexing into the indexing stage of host startup.

**Comment by gled4er** [comment]
Hello @mathewc  and @cgillum ,

Thank you very much for the explanations.

They are really helpful.

I will start working on the required changes.

Thank you very much!

**Comment by cgillum** [comment]
The associated PR has been merged. This will go out with the next release.
