### ISSUE TITLE
Activity function returns object with null properties

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-functions-durable-extension#2051]
### Description
My ActivityFunction returns a Azure.Storage.Blobs.Models.BlobDownloadResult
When debugging inside the ActivityFunction at the return line the object has its Content and Details properties set as exoected.
In the calling orchestrator, the object is set but its properties are null.

### Expected behavior
The same property values from the ActivityFunction object be present in the returned object.

### Actual behavior
The properties are null.

### Relevant source code snippets
```csharp
// insert code snippet here
From the orchestrator:
```
                    var blobResult = await context.CallActivityWithRetryAsync<BlobDownloadResult>(FunctionNames.ITwoCXDocSettingsDownloadBlobActivity, retryPolicy, (ingestionRequestInstanceStepModel.InstanceTrackingInfo(),instanceTrackingEventModel.EventModel.DocSettingFileName));//the blobResult has null properties

                    docSettingAggregate = blobResult.Content.ToObjectFromJson<DocSettingAggregate>(); //throws exception
```

The activity function
```
        [FunctionName(FunctionNames.ITwoCXDocSettingsDownloadBlobActivity)]
        public async Task<BlobDownloadResult> ITwoCXDocSettingsDownloadBlobActivity(
        [ActivityTrigger] (string trackingInfo, string fileName) payload,
        ILogger log)
        {
            var fileName = payload.fileName;
            var trackingInfo = payload.trackingInfo;
            //read document from blob
            try
            {
                var blobNullRetryPolicy = Policy.Handle<Azure.RequestFailedException>((e)=>e.Message.Contains("The specified blob does not exist."))
                    .OrResult<BlobDownloadResult>(r => r.Content == null)                    
                    .WaitAndRetryAsync(
                        6,
                        (c) => new TimeSpan(0, 0, (int)Math.Pow(2,c)),
                        (result, timeSpan, retryCount, context) => log.LogWarning($"{FunctionNames.ITwoCXDocSettingsDownloadBlobActivity} {trackingInfo} null content blob:{fileName} will retry {3 - retryCount} more times.")
                    );

                //read document from blob
                var blob = await blobNullRetryPolicy.ExecuteAsync(() => blobService.ReadBlobAsync(fileName));

                //var blob = await blobService.ReadBlobAsync(fileName);                
                log.LogInformation($"{FunctionNames.ITwoCXDocSettingsDownloadBlobActivity} {trackingInfo} downloaded {fileName}");
                return blob;//the properties are populated here as expected
            }
            catch (Exception e)
            {
                log.LogError(e, $"{FunctionNames.ITwoCXDocSettingsDownloadBlobActivity} {trackingInfo} error downloading {fileName}");
                throw;
            }
        }
```
### App Details

Azure.Storage.Blobs, Version=12.10.0.0
Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.6.0
(metadata says Assembly Microsoft.Azure.WebJobs.Extensions.DurableTask, Version=2.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289 but I installed the latest nuGet?)
Microsoft.Azure.Functions.Extensions 1.1.0

    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>


### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 2022-01-12T 04:00:00Z
- **Function App name**:  rg-d-lxr-aue-ingestion
- **Function name(s)**: 
- ITwoCXDocSettingsDBStorageOrchestrator
- ITwoCXDocSettingsDownloadBlobActivity
- **Azure region**: Australia East
- **Orchestration instance ID(s)**:
Not sure, I've attached some rows out of the Instances table, hopefully that is enough!
- **Azure storage account name**:
sadlxraueingestion
> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.
[fadlxraueingestionInstances-failed.csv](https://github.com/Azure/azure-functions-durable-extension/files/7852516/fadlxraueingestionInstances-failed.csv)

**Comment by cgillum** [comment]
My guess based on the description is that `blob` is either not fully compatible with the Newtonsoft.Json serializer we use to pass data between activity and orchestrator functions. You can find some documentation on how we do serialization [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence?tabs=csharp).

The simplest workaround would be to use your own custom types as the return value for your activity function (copying only what you need from the `blob` result). As long as your custom type has simple properties with getters and setters, it should be able to serialize just fine.

**Comment by RDavis3000** [comment]
Hi @cgillum yep you're right.
The BinaryData property doesn't have a parameterless public constructor.
Would be great if it didn't swallow the Newtonsoft exception when it hits a property it cant serialize.
I replaced the BlobDownloadResult with a custom type and its all working now.
Thanks for the link, considering serializability is something I'll keep in mind in future
Thanks
