### ISSUE TITLE
ETA for Durable Functions moving from Preview to GA

### ISSUE THREAD

**Issue by MicahMcKittrick-MSFT** [Azure/azure-functions-durable-extension#209]
We recently had a question come in on the following MSFT doc: 
[Durable Functions Overview - Azure (preview)
](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview)

Do we have an ETA on when Durable Functions will move from Preview to GA? If so, can you please share that information? 

Question reference: MicrosoftDocs/azure-docs#6323

**Comment by tohling** [comment]
Durable Functions is scheduled to GA at //build 2018, so the first week of May 2018.

**Comment by MicahMcKittrick-MSFT** [comment]
Great thank you @tohling !

**Comment by cgillum** [comment]
To clarify, this is when we hope to GA (internally) but "official" messaging is that we will GA in late Spring.

**Comment by cgillum** [comment]
For anyone who arrives here from search engine results, Durable Functions was announced as "GA" at Build 2018. Details can be found here:

* **Blog post**: https://azure.microsoft.com/en-us/blog/break-through-the-serverless-barriers-with-azure-functions/
* **Release notes**: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.4.0
