### ISSUE TITLE
The Azure Durable Orchestration goes in Pending state for long - Python 

### ISSUE THREAD

**Issue by ravz4010** [Azure/azure-functions-durable-extension#2090]
### Description
>  A below representation of 

The azure durable functions which are used commonly for several activity funtion are frequently getting stuck for long in Pending state causing a lot of trouble to us . Our function app is hosted in the West europe region .  Please find details of one such Pending instance along with the timing in UTC when of today . This is a very frequently occuring scenario 

![image](https://user-images.githubusercontent.com/84508791/154646855-43af711f-933f-4574-a57f-7bf8c518032c.png)
 

> 

### Expected behavior
>  The durable functions should have ideally finished within 4-6 minutes ( Should have gone immediately from Pending to Running)

### Actual behavior
> The functions got stuck in Pending state .

### Relevant source code snippets
```orchestrator function code here (Python)
// insert code snippet here
```import logging
import json
import azure.functions as func
import azure.durable_functions as df

def orchestrator_function(context: df.DurableOrchestrationContext):
    context_body = context.get_input()
    function_name = context_body.get("function_name")
    result = yield context.call_activity(function_name, context_body)
    return result

main = df.Orchestrator.create(orchestrator_function)

### Known workarounds
> Normally i resolve this by cancelling all the pending runs from adf and restarting the function app .

### App Details

- Durable Functions extension version (2.6.1):
- Azure Functions runtime version (3.4.2.0):
- Programming language used -Python 3.8:

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

Provided the details above as screenshots
- **Timeframe issue observed**:
- **Function App name **:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by davidmrdavid** [comment]
Hi @ravz4010, thanks for reaching out. Can you please provide us with **all** the following information? I realize you provided _some_ of it via the screenshot, but we still need the application name, as well as an approximate start time of when this issue began occurring. Thanks!

Provided the details above as screenshots
- **Timeframe issue observed**:
- **Function App name **:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

**Comment by ravz4010** [comment]
Sure @davidmrdavid the function app name happens to be  : dtc-ecommerce-functions-prod .

The latest this issue we faced was on 17th Feb 10:11 pm UTC .

**Comment by ravz4010** [comment]
For todays instance  of the durable task being stuck in pending status issue please find the Orchestration id details and time details in UTC  
"name":"durable_functions_orchestrator","instanceId":"16de27edf4fb4a7faa5e05773eda1b21","createdTime":"2022-02-21T01:56:32Z"

**Comment by ravz4010** [comment]
I also want to draw some attention to a particular instance which was stuck for long in Running state .  When i restarted the function app and cancelled the pipeline run from ADF it was then the instance failed . "name":"durable_functions_orchestrator","instanceId":"8ce900691c70455aa1873ad6479475d1"  . The orchestrator runs the activity function which submits sql on snowflake .

**Comment by ravz4010** [comment]
I think i have done some deep dive into the insights and have some thoughts on this @davidmrdavid  , Is there a way we can connect on a teams/ zoom call whenever u have some time for you to run through my analysis .

**Comment by davidmrdavid** [comment]
@ravz4010 - I'm so sorry for my delay here, I away from the office for a few weeks and just caught up with this thread. A few questions:
*  Is this issue still happening or has it been resolved?
* Can you provide me with the latest instanceId and timestamp for this issue? Have you found any mitigations or workarounds? 

Thanks!

**Comment by ravz4010** [comment]
The issue has not been resolved

**Comment by davidmrdavid** [comment]
@ravz4010 , I've re-opened the issue.

Could you please provide me with the latest instanceId and timestamp for this issue? I realize you provided this on Feb 20, but having newer data will make it easier to inspect our telemetry.

**Comment by ravz4010** [comment]
Hi , It has reoccured today .Please find the instance id snip and the latest timestamp value ( IN UTC ) 

![image](https://user-images.githubusercontent.com/84508791/167074198-d68a5f6e-1e0d-437b-a408-d1d5546c50d5.png)

**Comment by ravz4010** [comment]
HI @davidmrdavid 
Putting out the values here for you to be able to easily copy them out 
"instanceId":"0fc7b65b827b478cb77b750f15e23d63" 
"createdTime":"2022-05-06T05:29:56Z",
"lastUpdatedTime":"2022-05-06T05:46:01Z"

**Comment by ravz4010** [comment]
HI @davidmrdavid  we seeing again today some of our Durable functions going in pending state. Details as below :

"instanceId":"bba7753a2e764f9e9d185fef8a394045",
"runtimeStatus":"Pending",
createdTime":"2022-05-11T07:01:04Z",
"lastUpdatedTime":"2022-05-11T07:01:04Z"

**Comment by ravz4010** [comment]
I typically restart manually the function app and then slowly see the problem to recede

**Comment by davidmrdavid** [comment]
Hi @ravz4010.

I'm still investigating, but at the moment nothing in our telemetry stands out to me as evidence of a problem at the Durable Functions-level, although I do see your orchestrator being in the `Pending` state for a long time. My suspicion is that the Python worker performance settings may be preventing your orchestrator from triggering as early as it could.

Just as a sanity check, have you configured the values for `FUNCTIONS_WORKER_PROCESS_COUNT` and `PYTHON_THREADPOOL_THREAD_COUNT` as described here: https://docs.microsoft.com/en-us/azure/azure-functions/python-scale-performance-reference ?

In my experience, looking at other cases where DF Python apps aren't getting the performance we expect, these settings being left to their default values often explains missing performance. Please let me know if you've configured these and, if you have not, please look to performance tune them using the guidance described above. Thanks!
