### ISSUE TITLE
Eternal orchestrations stopped randomly

### ISSUE THREAD

**Issue by Genslus** [Azure/azure-functions-durable-extension#2093]
### Description
I got a problem with an eternal orchestration which seems to stop randomly. 

**Use Case**

- I start an orchestration with the [singelton](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons?tabs=javascript) pattern
- the involved functions (not all listed):
  - initial function (_detectContentTypeChanges_)
    - triggered via external Webhook
    - checks if the orchestration is already running (if not it starts it)
      - the orchestrator function name is _readContentTypeChangeEntity_
    - will create entries in a [durable entity](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=javascript)
  - orchestration trigger function (_readContentTypeChangeEntity_)
    - checks the content of the durable entity 
    - based on the result it may call an activity function
    - based on the result it may remove entries from the durable entity
    - it will create a timer (60s added to the currentUtcDateTime)
      - `yield context.df.createTimer(nextRun.toDate());`
    - it will call _continueAsNew_ (eternal)
      - `yield context.df.continueAsNew(undefined);`

The problem I have is that the _readContentTypeChangeEntity_ function, which should run every minute, will randomly stop until I terminate and restart it manually again. Sometimes it runs for several days without issue but sometimes it stops after a few hours. 
In the log there are no exceptions or anything indicating why it stopped. 
It just seems that the timer was not created (which should not happen since I put the creation in the finally block of a try/catch) or the event from the timer was not "consumed"?! So this function is then never called again and basically stuck until I manually restart it. 

Probably worth to mention that I run the same use case on two separate storage accounts (one for _dev_ and one for _prod_) and the issue occurs on both instances (at different times). 

Both instances run in EUW and the id(s) of the singelton orchestrations are: 
- singletonReadContentTypeChangeOrchestration-dev
- singletonReadContentTypeChangeOrchestration-prod

If necessary I can post the complete code of both functions.

### Expected behavior
> I would expect the orchestration trigger function (_readContentTypeChangeEntity_) to basically run forever (if no error occurs)

### Actual behavior
> The orchestration trigger function (_readContentTypeChangeEntity_) stops randomly without error. The timeframe in which it runs without a problem vary. Sometimes it runs for a few hours until it stops but it also ran for several days until it stopped randomly. Lately it usually stops after a few hours. 

### Known workarounds
> A workaround I used is to terminate and restart the orchestration trigger function (_readContentTypeChangeEntity_) manually. Then it will run again but until now stop again after some time. 

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 1.5.4
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: JS

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

#### PROD
- **Timeframe issue observed**: the orchestration is currently stuck since _2022-02-19T06:10:01.0700225Z_ (I have not restarted it manually yet)
- **Function App name**: -
- **Function name(s)**: -
- **Azure region**: EUW
- **Orchestration instance ID(s)**: singletonReadContentTypeChangeOrchestration-prod
- **Azure storage account name**:

#### DEV
- **Timeframe issue observed**: the orchestration is currently running but the last time it was stuck (before I manually restarted it) was around _2022-02-21T10:24:01.0700225Z_  
- **Function App name**: -
- **Function name(s)**: -
- **Azure region**: EUW
- **Orchestration instance ID(s)**: singletonReadContentTypeChangeOrchestration-dev
- **Azure storage account name**:

**Comment by JosieW** [comment]
I had a similar issue with an orchestrator hanging (usually after calling an entity).

Could it be this bug? https://github.com/Azure/durabletask/pull/657
It's been fixed in this version of the DurableTask: https://github.com/Azure/azure-functions-durable-extension/releases

However this is not available in any of the Extension Bundles yet: https://github.com/Azure/azure-functions-extension-bundles/releases

So instead I updated my app to explicitly install the versions of each extension that's needed:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register#explicitly-install-extensions

**Comment by Genslus** [comment]
Thank you. That actually sounds like it could be the issue. Unfortunately this was an urgent issue so we found another workaround (by no longer using entities). 
So for now I would close this issue and maybe try the fix/version you described.
