### ISSUE TITLE
Sharing multiple Task hub with same storage account

### ISSUE THREAD

**Issue by sathishkumarrjp** [Azure/azure-functions-durable-extension#2095]
Team ,

Kindly help here for this issue.

I don't find any example which is useful for sharing the same storage account with multiple Task hub in **Host.json** file.  I am having **2.0.0** version of Durable function. Any example would be really helpful. 

Inside the Host.Json file if I tried to create **multiple Task hub** its not working properly, the **durableTask** property accepting only one **durable task object**.

**NOT WORKING**

"extensions": {
    "durableTask":
  [
    {
      "hubName": "durableHub1",
      "connectionStringName": "SampleAzureStorageAcct",
      "maxConcurrentActivityFunctions": 10,
      "maxConcurrentOrchestratorFunctions": 5
    },
   {
      "hubName": "durableHub2",
      "connectionStringName": "SampleAzureStorageAcct",
      "maxConcurrentActivityFunctions": 10,
      "maxConcurrentOrchestratorFunctions": 5
    }
  ]
  }

**WORKING**

"extensions": {
    "durableTask": {
      "hubName": "durableHub1",
      "connectionStringName": "SampleAzureStorageAcct",
      "maxConcurrentActivityFunctions": 10,
      "maxConcurrentOrchestratorFunctions": 5
    }
  }

**Comment by sathishkumarrjp** [comment]
We are facing production issue for this durable function kindly provide some help here.

**Comment by cgillum** [comment]
Multiple task hubs in the same host.json is not supported. You’ll need to create two different apps if you need to process two different task hubs.
