### ISSUE TITLE
Durable Functions on AKS with KEDA Scaler - Drain Mode

### ISSUE THREAD

**Issue by lak-amith531** [Azure/azure-functions-durable-extension#2126]
### Description
We have deployed durable functions docker container into Kubernetes. Orchestrator is started by a queue trigger and entire deployment is being scaled from 0 based on the number of queue messages. Drain mode is being enabled at times stopping all the triggers and terminating the container. I haven't been able to replicate the same behavior neither on my local system with `func start` or in container on docker desktop. Frequency of this event feels completely random and the same queue message when put back again works fine. 

### Expected behavior
After creation Orchestrator instance, it should run all the activities. RuntimeStatus in TaskHubInstances should be `Completed`

### Actual behavior
After the orchestrator instance is created, the following is happening.
```
Task hub worker started. Latency: 00:00:04.7909584. InstanceId: . Function: . HubName: ****TaskHub. AppName: . SlotName: . ExtensionVersion: 2.6.1. SequenceNumber: 2
Job host started
Host started (5785ms)
8ab0e881828d4811867fa28a98d9799a: Function 'processOrchestration (Orchestrator)' scheduled. Reason: NewInstance. IsReplay: False. State: Scheduled. HubName: ****TaskHub. AppName: . SlotName: . ExtensionVersion: 2.6.1. SequenceNumber: 3.
DrainMode mode enabled
Application is shutting down...
Requesting cancellation for function invocation 'a2b00c4e-f58b-489b-baa4-f9feec10c58c'
Calling StopAsync on the registered listeners
Started orchestration with ID = '8ab0e881828d4811867fa28a98d9799a'
Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskListener' for function 'processOrchestration'
Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskListener' for function 'databaseIngestion'
Stopping the listener 'Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskListener' for function 'dataTransformation'
Stopping task hub worker. IsGracefulStop: True. InstanceId: . Function: . HubName: ****TaskHub. AppName: . SlotName: . ExtensionVersion: 2.6.1. SequenceNumber: 4.
Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskListener' for function 'processOrchestration'
Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskListener' for function 'databaseIngestion'
Stopped the listener 'Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskListener' for function 'dataTransformation'
Call to StopAsync complete, registered listeners are now stopped
```
Even when the orchestrator runs successfully, RuntimeStatus in TaskHubInstances is still `Running`
### App Details

- **[2.*, 3.0.0))**:
- **2.0**:
- **Programming language used**: Python

**Comment by cgillum** [comment]
@lak-amith531 thanks for opening this issue. A few questions for you, if you don't mind:

1. Can you share your host.json configuration?
2. Also, are you using the `func kubernetes` command to deploy this app or are you setting it up some other way?
3. Does the container come back up after draining and complete the orchestration or is it stuck indefinitely?

This behavior definitely seems problematic - I'm just trying to reason about the root cause and who needs to be involved in figuring out how to correct it.

**Comment by lak-amith531** [comment]
>Can you share your host.json configuration?
```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    },
    "extensions": {
        "queues": {
            "maxPollingInterval": "00:00:30",
            "batchSize": 2,
            "maxDequeueCount": 1,
            "newBatchThreshold": 1
        },
        "durableTask": {
            "hubName": "****TaskHub",
            "useAppLease": false,
            "useGracefulShutdown": true
        },
        "functionTimeout": "00:59:59"
    },
    "extensionBundle": {
        "id": "Microsoft.Azure.Functions.ExtensionBundle",
        "version": "[2.*, 3.0.0)"
    },
    "functions": [
        "processInitialization",
        "processOrchestration",
        "dataTransformation",
        "databaseIngestion"
    ]
}
```
> Also, are you using the func kubernetes command to deploy this app or are you setting it up some other way?

We are using HELM to deploy it to the cluster

> Does the container come back up after draining and complete the orchestration or is it stuck indefinitely?

Container does not come back up after draining. Orchestrator is stuck in either Pending or Running state indefinitely for the latest run.

**Comment by lilyjma** [comment]
@lak-amith531 -- what scaler are you using?

**Comment by raorugan** [comment]
Hi @lak-amith531 , Can you please let us know if the container is running with root permissions? If not can you please try running your container with root perms and let us know.Thanks, Ramya

**Comment by lak-amith531** [comment]
@raorugan Yes, container is running with root permissions, UID 0.

**Comment by krishna-kariya** [comment]
Hi @lak-amith531, 
I tried to reproduce this issue but was not able to do so. I used the same host.json and scaled-object configuration as yours. I am sharing the deployment I used to create the container for reference. 

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <name-of-app>
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <name-of-app>
  template:
    metadata:
      labels:
        app: <name-of-app>
    spec:
      containers:
      - env:
          - name: AzureWebJobsStorage
            value: <secret-ref>
          - name: WEBSITE_HOSTNAME
            value: localhost:7071
        image: <image-name>
        imagePullPolicy: Always
        name: <name-of-app>
```

Can you please share the steps to reproduce this issue?

**Comment by lak-amith531** [comment]
I have managed to identify the root cause. If the queue is empty when polling happens, durable function runs till the end of `cooldownPeriod` and drain mode is enabled, completely ignoring `terminationGracePeriodSeconds`. In case of normal function, it waits till the end of `terminationGracePeriodSeconds`. I had to increase the `cooldownPeriod` to overcome this issue.

**Comment by paravatha** [comment]
@raorugan @davidmrdavid @lilyjma @cgillum  
I am trying to run Durable function using DurableTaskListener on AKS using KEDA as a `non-root` user and getting the same error message as above. 
Just wanted to clarify, does Durable function using DurableTaskListeners needs to run as `root` user? no way around to run as `non-root` user?

**Comment by paravatha** [comment]
nvm, figured out the solution based on the blog here https://devblogs.microsoft.com/dotnet/securing-containers-with-rootless/#switching-to-port-8080

here is the part of the docker file

```
ARG JAVA_VERSION=21
FROM mcr.microsoft.com/azure-functions/java:4-java$JAVA_VERSION-appservice

ENV FUNCTION_APP_DIRECTORY=/home/site/wwwroot
# Use a port other than 80 to avoid conflicts with the Azure Functions runtime
# Reference https://devblogs.microsoft.com/dotnet/securing-containers-with-rootless/#switching-to-port-8080
ENV PORT=8080
ENV ASPNETCORE_URLS=http://*:${PORT}

# Set environment variables for the Azure Functions runtime
ENV AzureWebJobsScriptRoot=${FUNCTION_APP_DIRECTORY} \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

# Set app user permissions for the function app directory
RUN chmod -R 755 ${FUNCTION_APP_DIRECTORY} \
    && chown -R app:app ${FUNCTION_APP_DIRECTORY}

# Copy the built function app from the installer environment to the runtime image
COPY --from=installer-env ${FUNCTION_APP_DIRECTORY} ${FUNCTION_APP_DIRECTORY}

# Switch to the existing non-root user in the appservice image
USER app

# Use a port other than 80 to avoid conflicts with the Azure Functions runtime
# Reference https://devblogs.microsoft.com/dotnet/securing-containers-with-rootless/#switching-to-port-8080
EXPOSE ${PORT}
