### ISSUE TITLE
Brand new Durable Function Project from VS 2022 template does not call orchestrator

### ISSUE THREAD

**Issue by spearsonwork** [Azure/azure-functions-durable-extension#2127]
I have a problem with my Durable functions run locally being triggered but not having their orchestraters called and therefore being seemingly permanently stuck in a "pending" state.

In visual studio 2022, I create a new Azure Functions application and select Durable Functions Orchestration.  

Without making any changes, I build the project and select "Start without Debugging".

The console shows that the trigger is called and that an instanceId has been created.

Checking any statusQueryGetUri  shows that the runtimestatus is "pending".

The template uses 
Net 6.0.
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.6.1
Microsoft.Net.Sdk.Functions 4.0.1

**Comment by cgillum** [comment]
I tried following your repro steps but wasn't able to reproduce the problem - things ran just fine for me (VS2022, new function app, new Durable Functions orchestration from template), "Start without Debugging".

A few questions that might help narrow down the problem:

- How did you start the orchestration? You didn't actually mention that in your description.
- Are you using a storage emulator?
- Is the behavior any different if you update your host.json to look something like the following?

```json
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "DurableTask.AzureStorage": "Warning",
      "DurableTask.Core": "Warning"
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false
      }
    }
  },
  "extensions": {
    "durableTask": {
      "hubName": "SomeUniqueValue"
    }
  }
}
```

The above host.json does two important things:
1. Enables additional warnings/errors that might give hints about what's going on.
2. Ensures that you're not potentially running into conflicts with other Durable projects running on the same machine (i.e. projects using the same implicit task hub name).

**Comment by spearsonwork** [comment]
I was starting to get error messages for completely different earlier durable function instances which seemed to suggest that I was running into conflicts.  It then seemed to right itself, although I have added the hubName to my host.json as suggested as this sounds like it would prevent this conflict happening in the future.   Thanks.
