### ISSUE TITLE
Delete Task hub from CLI ignores host.json partitionCount  

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-durable-extension#2130]
### Description
It looks like the delete command will use the default settings for partition count, not from the host.json. Im seeing orphaned queues when deleting a task hub from the CLI my partition count is greater than 4

### Expected behavior
It would be helpful if the CLI considers the partition count specified in the host.json so that the queues are correctly deleted.

### Actual behavior
When deleting a task hub using the Function Tools CLI with a partition count of greater than the default (currently 4), only the default number of partitions is considered, resulting in a orphaned queues in the Azure Storage account.

### Known workarounds
> Manually delete the orphaned queues using storage explorer

**Comment by gorillapower** [comment]
[#](https://github.com/Azure/azure-functions-core-tools/pull/3014)

**Comment by davidmrdavid** [comment]
Hi @gorrilapower,

Thanks for reaching out, and thanks for being proactive and creating a PR in the core-tools repo. 
Just for validation's sake, can you provide me the specific core-tools commands you executed to repro this incident? I'll need them to give the core-tools the approval that your PR performs the appropriate fix.

In short, a set of instruction to easily repro this (and to test your fix) would help. Thanks again.

**Comment by gorillapower** [comment]
@davidmrdavid no problem, thank you.

*Repro Steps*
1. When using the default AzureStorage StorageProvider 
2. Set partitionCount in host.json to something greater than 4, ie
```javascript 
{
    "version": "2.0",
    "extensions": {
        "durableTask": {
            "storageProvider": {
                "partitionCount": 12
            }
        }
    }
}
```

3. Run the Function and observer that the respective control queues are created
![image](https://user-images.githubusercontent.com/8879065/162212123-186abb31-a494-4f09-b489-54afd39de32b.png)

4. Navigate to the root folder of the function, run the CLI command
`func durable delete-task-hub` 

5. Observe that that only the first 4 control queues have been removed and the partitionCount in the host.json has not been taken into account.

6. The fix in the PR will resolve this by referencin the partitionCount in the host.json and therefore remove all the control-queues accordingly.

**Comment by davidmrdavid** [comment]
Thanks @gorillapower. I've been able to repro this bug. I'll notify the core-tools team about it. Thanks so much!

**Comment by davidmrdavid** [comment]
Closing as https://github.com/Azure/azure-functions-core-tools/pull/3020 has been merged
