### ISSUE TITLE
Large gap between orchestration being scheduled and being started

### ISSUE THREAD

**Issue by fiddlerpianist** [Azure/azure-functions-durable-extension#2154]
### Description
We are occasionally experiencing large gaps in time (15+ minutes) between the scheduling and the starting of durable orchestrations. There is virtually no load on the Function App when this occurs, and in fact other instances of the same orchestration trigger are scheduled and complete, like so:

9:28:00am: Orchestration instance A scheduled
9:28:01am: Orchestration instance B scheduled
...
(no other orchestrations)
...
9:29:00am: Orchestration instance C scheduled
9:29:03am: Orchestration instance C started
9:29:30am: Orchestration instance C completed
...
(no other orchestrations)
...
9:45:00am: Orchestration instance A started
9:45:00am: Orchestration instance B started
9:45:27am: Orchestration instance A completed
9:45:27am: Orchestration instance B completed

There are no errors being logged, or any indication from the host app as to why there is such a long pause.

Other times, execution occurs normally and this does not happen at all.

### Expected behavior
We expect that, under no load, there should not be more than a few seconds of a gap between an orchestration being scheduled and started.

### Actual behavior
We've seen a gap as large as 17 minutes between an orchestration being scheduled and started.

### Relevant source code snippets
```csharp
string workflowOrchestrationId = await starter.StartNewAsync("RunWorkflowOrchestration", eventPayload);
```

### Known workarounds
No identified workarounds (other than just waiting and hoping that they eventually execute).

### App Details

- **Durable Functions extension version**: 2.6.1
- **Azure Functions runtime version**: 4.0
- **Programming language used**: .NET (C#)

### Screenshots
N/A

### Azure Details

- **Timeframe issue observed**: April 26th, 2022, roughly 9:25am-9:45am America/Chicago TZ
- **Function App name**: connectx-egress-stg
- **Function name(s)**: HttpTriggerEvent, RunWorkflowOrchestration
- **Azure region**: East US
- **Orchestration instance ID(s)**: 4ae680bc038145f893e303167b515982, 37e6e70598284bd09a06d9cfdf5557ac
- **Azure storage account name**: strgecnctxstgegress

**Comment by fiddlerpianist** [comment]
Hi, I'm wondering if anyone has had a chance to take a look yet? We're really at a loss with this one, and our official support channel has not been particularly helpful.

**Comment by cgillum** [comment]
Sorry for the delayed response! Do you have a support case number from Azure support? If so, we might be able to check on the status to see how much investigation has happened.

I did a quick check with our automated analysis and no problems came up for your app (hopefully I searched for the right time period - all of our tooling only works with UTC and I have no ability to search using America/Chicago TZ). I will mentioned that there is a newer extension release, v2.7.0 that has some improvements, but obviously we need to confirm what the problem is before we know whether updating will be helpful for you.

The fact that both orchestration instances started at around the exact same time leads me to believe that this is likely a case where your app got into some stuck state temporarily. We've been seeing cases like this lately, and it has to do with corner case bugs in our partition management. v2.7.0 fixes some of those issues but we also have another fix in the pipeline for v2.7.1, which we hope to get out soon.  In the meantime, we'll try to follow up to more closely diagnose your case.

**Comment by fiddlerpianist** [comment]
The ticket that we had opened some time ago for this is 2202220040006152. It appears to be a slightly different situation, but it does seem to have the same underlying issue of orchestrations (or sub-orchestrations) not being started after they had been scheduled (in the case of the ticket, a Function App restart solved the problem). Since the ticket was opened, we have upgraded our app in a couple of ways (i.e., upgraded to 2.6.1, changed our logging via an API to be an Activity Function... we chatted about that in a different issue). We had thought we'd seen the end of it, but now we are seeing a very similar pattern.

Since all we've seen is silence in the logs when this occurs, it's hard to know exactly how often this happens, or even how to reproduce the issue.

It's good to know that 2.7.0 improves on this. We just upgraded this in our mainline, and we'll be on the lookout for 2.7.1 and will upgrade when that comes out as well.

**Comment by cgillum** [comment]
I just realized that @davidmrdavid has already started an investigation into your case from the original GitHub posting and shared a bunch of notes internally. Indeed, your case looks like a known issue related to problematic partition management. Adding @amdeel and @sebastianburckhardt as well, who have been helping investigate this.

**Comment by a3y3** [comment]
Thanks for being so active on this, @cgillum! Excited to see if 2.7.1 fixes the issue.

**Comment by fiddlerpianist** [comment]
Thanks!

Is there anything we can do to minimize this occurring in the meantime? Perhaps there are best practices with our storage account we should be taking but aren't? In the case where we would otherwise start 2 orchestrations back to back, should we instead start 1 orchestration that kicks off 2 sub-orchestrations? (It's also fine if none of this will help, just want to know.)

**Comment by cgillum** [comment]
Unfortunately, there's no simple workaround for this. The best option to minimize this is to use a fixed number of dedicated VMs instead of a variable number of transient VMs. This helps because it keeps partitions from moving, which is an important aspect of the problem. However, I realize this may not be practical for many folks.

**Comment by cgillum** [comment]
@fiddlerpianist @a3y3 we have a set of fixes ready that we hope to include in the v2.7.1 release. However, it will take some time before we can complete a full release. Would you be willing and able to use a private nuget package to test in your environment? We typically post such private releases to a publicly accessible nuget feed on myget.org. If you're interested, I can make this available.

**Comment by a3y3** [comment]
@cgillum that sounds good to us, thanks!

**Comment by fiddlerpianist** [comment]
We use DevOps Artifact Feeds, so if there's a way for us to hook into this nuget feed, that should work. Just let me know.

**Comment by cgillum** [comment]
Can you try adding a reference to the following nuget package: https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.DurableTask.AzureStorage/1.11.1-preview

This particular package is normally picked up as a transient dependency of Microsoft.Azure.WebJobs.Extensions.DurableTask. However, it can also be referenced directly, which is useful if you need to use newer versions. In particular, this package controls all the interactions with Azure Storage, including things like lease and partition management. This preview build contains a variety of fixes designed to remove delays related to partition movement. Let us know if this helps resolve any of the issues you've been seeing.

**Comment by fiddlerpianist** [comment]
We were able to get this installed by adding this directly to our `nuget.config`. So far we haven't been able to reproduce the issue with the preview package, but we haven't really tried to reproduce it yet with 2.6.1. We'll do some A/B testing and will let you know.

Thanks again!

**Comment by cgillum** [comment]
@fiddlerpianist thanks for letting me know. This at least gives me some confidence that we haven't made things worse. :) I look forward to your update. We're hoping to make a release very soon and would feel much better if we had your unofficial signoff.

**Comment by fiddlerpianist** [comment]
So this isn't exactly the data point you are looking for, but I was (somewhat) able to reproduce the gap using 2.7.0. In this case, it looks like the gap was about a 35-second delay. I tried to hit the HTTP trigger which kicks off the Durable orchestration as hard as I could.
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/5559537/167490894-7f4650c4-38d6-45f2-a540-a0c069c94da7.png">

I will try this with the preview release and see if this improves.

**Comment by fiddlerpianist** [comment]
Good news! I was able to run a bunch of orchestrations through our system today with the preview release, and we were unable to reproduce the appreciable delay between scheduling and execution.

Do you have a general timeline for when 2.7.1 will be released? We release into our production about once a month (and we just released a few days ago), so if you think it will be within a couple of weeks, that would be helpful for us to know.

**Comment by davidmrdavid** [comment]
@cgillum, do we think we're good to close this issue?

**Comment by fiddlerpianist** [comment]
Great, thanks!
