### ISSUE TITLE
'Azure.WebJobs.Extensions.DurableTask' should depend on newer version of 'Azure.Identity'

### ISSUE THREAD

**Issue by julealgon** [Azure/azure-functions-durable-extension#2158]
The `Microsoft.Azure.WebJobs.Extensions.DurableTask` package currently depends on `Azure.Identity > 1.1.0`. This causes problems for projects that don't explicitly add `Azure.Identity` and rely on the transitive v1.1.0: that version has problems properly resolving multiple logged in accounts in Visual Studio for example, resulting in exceptions like:

> SharedTokenCacheCredential authentication unavailable. Multiple accounts were found in the cache. Use username and tenant id to disambiguate.

I think a much safer alternative would be to update the minimum version required by the DurableTask package to a more up-to-date version of `Azure.Identity` that doesn't suffer from these bugs.

I think being forced to add an explicit dependency to a more up-to-date `Azure.Identity` package is not good enough (even though it works as a workaround).

Related response here:
- https://stackoverflow.com/a/65819015/1946412

In particular, it appears that there were significant changes in `Azure.Identity` v.1.2.0+ to fix this problem:
- https://github.com/Azure/azure-sdk-for-net/blob/Azure.Identity_1.3.0/sdk/identity/Azure.Identity/CHANGELOG.md#new-features-7

**Comment by cgillum** [comment]
(Transferred to correct repo)

**Comment by cgillum** [comment]
@julealgon in the latest release (v2.7.0) we actually upgraded to Azure.Identity v1.5.0 for Azure Functions V2 and above: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.7.0.  Are you having this problem on the latest version, or are you perhaps using Functions V1 on .NET Framework?

**Comment by julealgon** [comment]
@cgillum Oh I see now. 2.7.0 was released 11 days ago and bumps it on .NET Standard. 

I was still using 2.6.1 and misread the dependencies page when checking this today on nuget.org: at first glance I also though 2.7.0 still pointed to Azure Identity 1.1.1 but I was incorrectly checking the dependencies for .NET Framework there instead of checking for .NET Standard version of the package... 

Looks like this has already been taken care of then! I'll update to 2.7.0 instead of updating `Azure.Identity` manually.
