### ISSUE TITLE
Post orchestration lifecycle events to Azure Event Grid

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#216]
There are various scenarios where it would be useful to have an external system subscribe to orchestration lifecycle events. The most interesting events would probably be **orchestration started** and **orchestration completed** (success or fail).

One idea is to allow configuring an Event Grid SaS key as an application setting, and the extension could then post to the corresponding topic.

**Comment by TsuyoshiUshio** [comment]
I'd love to contribute this as a DevOps guy. :)

**Comment by cgillum** [comment]
よろしくお願いします！:)

**Comment by TsuyoshiUshio** [comment]
Hi @cgillum I have a question.
For sending event to EventGrid Topic, we can use SDK or implement REST by myself. When I see the dependency, Durable doesn't have a lot of dependency. Can I use SDK with new nuget package or prefer to keep less dependency of nuget with direct REST call?

**Comment by cgillum** [comment]
What is the nuget pack for the SDK? Is it [Microsoft.Azure.Management.EventGrid
](https://www.nuget.org/packages/Microsoft.Azure.Management.EventGrid)? I looked at these dependencies and I'm a little worried about them. For this particular case, I would be more comfortable with targeting the REST API.

**Comment by TsuyoshiUshio** [comment]
Sure!

**Comment by brandonh-msft** [comment]
How would we feel about an Event Grid output binding? https://github.com/brandonh-msft/Functions.Bindings.EventGrid

**Comment by yuka1984** [comment]
I'm seeking opinions on the behavior when an Exception occurs when accessing EventGrid's API with HttpClient.

https://github.com/TsuyoshiUshio/azure-functions-durable-extension/blob/feature/lifecycledev/src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs#L464

**Comment by cgillum** [comment]
I went ahead and merged this PR. Thanks for this great contribution! I opened up a separate GitHub issue for tracking error handling strategies: https://github.com/Azure/azure-functions-durable-extension/issues/241

**Comment by CastleArg** [comment]
Hi guys, this is great that this feature exists, I just came to request it after a lot of google fu got me nowhere.
Is it due to go G.A and be documented anytime soon?  I'm a bit wary of installing r.c version.
Essentially I want to trigger functions on error AND have realtime web dashboard for some long running task status so pub sub would be ideal.
Cheers!

**Comment by akourbat** [comment]
Is this feature working?  I cannot get it to work at all

**Comment by brandonh-msft** [comment]
> Is this feature working? I cannot get it to work at all

Assuming you're following [the docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-event-publishing) I don't know of any reason for it not to work.

paging @TsuyoshiUshio

**Comment by cgillum** [comment]
@akourbat If you’re running into problems, please open a new issue and let us know what version of Azure Functions runtime and what version of the Durable extension you are using.

**Comment by akourbat** [comment]
I actually got it working now, but the host.json that is indicated in the docs is obsolete.  Instead of 
{
    "durableTask": {
        "eventGridTopicEndpoint": "https://<topic_name>.westus2-1.eventgrid.azure.net/api/events",
        "eventGridKeySettingName": "EventGridKey"
    }
}
as suggested in the docs, one should use newer version -
{
  "durableTask": {
    "hubName": "MyTaskHub",
    "notifications": {
      "eventGrid": {
        "topicEndpoint": "https://topic_name.westus2-1.eventgrid.azure.net/api/events",
        "keySettingName": "EventGridKey",
        "publishRetryCount": 3,
        "publishRetryInterval": "00:00:30",
        "publishEventTypes": [
          "Started",
          "Pending",
          "Failed",
          "Terminated"
        ]
      }
    }
I also think "Failed" is not being published.

**Comment by CastleArg** [comment]
the docs still contain open feedback that the feature does not work when set up as per the docs.
@akourbat or anyone who has actually successfully used this it would be great if you could make a pull request to the docs with updated info once you have it running!
