### ISSUE TITLE
Fan Out Orchestration for ~4000 activities With Heavy Http Get Workload causing DF to Get Stuck

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-functions-durable-extension#2161]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

We have a basic ETL process implemented as an orchestration.  It calls an activity to identify candidates, then each candidate is fan'd out to activities to perform the transform and delivery, and then a fan in to collect and report issues in a durable entity.  When our candidates gets to ~4000 DF starts behaving very poorly.  This mostly seems to be because consumption plan is exhausting the 600 outgoing ports and scale monitor isn't spinning up new instances, but wondering what can be done as DF NEVER seems to recover once this happens which seems..bad.

Our activities have to fetch a lot of data from different http places, and we've done about all the cacheing we can to avoid as many calls as we can.  The calls themselves are extremely fast.  We are leveraging IHttpFactory so believe we're appropriate avoiding the common causes of port exhaustion, and this isn't really about that specifically.  We could put a semaphore in place to try to limit the ports, but what we rally want is to scale when this burst happens.

There's 6 ETL processes that run every 5'ish minutes offset. Once we get in this bad state, maybe 1 out of 10 never leaves the pending state, and 1 out of 25 stick in running forever.

We see the ~4000 entries going into the workitem queue and being worked.  Then we see the control queue balloon up.  So far we've only observed all the control messages appearing in a single control queue (0).  and the other 3 seem to go unused, which makes me think upping the partition count won't help me here.

It seems to behave better if we don't update the status durable entity, but it can still hang.  Suspect because these durable entity updates effectively doubles the number of messages sent to the queue as every activity now has a paired update dispatch to the entity.

Our only remedy is to clear the queues and then purge the hung orchestrations.  They don't seem to respond to 

Anecdotally, we've notice that a deployment sometimes seems to rework the queue and process the stuck orchestrations.  But a start/stop or normal tear down/host startup from consumption plan doesn't seem to re-kick the process.  This kinda seems like the scale controller behaves differently for a deploy.  Haven't recreated this enough to be on firm ground here.

All our config is default AFAIK.

Wondering if 
* there's something we can change to let the scale controller know for these bursts to scale up a bit as our activities themselves are not queued very long.  
* Also looking for any hints to free up ports from IHttpClientFactory after we get our responses (but that only gets us so far...if we close ports twice as fast, and have twice as many candidates, we're back in the same issue.)
* There's a better fanout batching strategy, or batching strategy for the durable entity updates (other than just coding it specifically)
* why DF isn't recovering once this happens and the port count drops back to near 0?
* is there a way to get the scale controller to behave like it does on a deploy (if anecdotal observations end up being reasonable)
* is 4000 activities a lot?  Doesn't seem like it's a lot, evidenced by all messages in a single control queue.

We did open a support case for this.

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

### Expected behavior
> A clear and concise description of what you expected to happen.

Expect DF to not hang beyond the period when port exhaustion occurs when activities fan out to more than 4000

### Actual behavior
> A clear and concise description of what actually happened.

many orchestrations stuck in pending and running states long after the port exhaustion happens.

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
> Provide a description of any known workarounds you used.

clear the control queues, purge affected orchestrations

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.7.0
- **Azure Functions runtime version (1.0 or 2.0)**: 3
- **Programming language used**: c#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:  4/28-5/3
- **Function App name**: usop1fap00-tecsys-middleware-integrations-prod
- **Function name(s)**: DoProcessPOs
- **Azure region**: uswest
- **Orchestration instance ID(s)**:
* 431640572ee04ee890828c7942e8f748
* 0304090d225c4862bc5e93637cd8dab3
* 58e67045c65f4f7ab7b5b7c2994770b6
* 166a32ba0a1644a39b45b89417413720
* 4f3e20294c7041e3a73256d57335ae2c
* cc9f490e33ce4d6fbef969ee7cd17686
* 127171ca109a4ec28a40317ec21ca38b
* 21fadec32b6240b9ae9ced2216b59594
* ac1761956b5d4bc2b0ffd661663c102a
* ad7cd7dfb8e74b6e91d25564711a764d

- **Azure storage account name**: usop1str00tecsysintegrat

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by davidmrdavid** [comment]
Hi @drdamour, thank you for reaching out.

Hmm, there's a lot of questions here :-) .

As a starting point: DF _should_ be able to recover from **temporary** resource-exhaustion problems, especially after an application/ Functions Host restart. So if this is not happening, that's something we should investigate. 

I can't say with certainty whether 4k activities is too much: it depends. However, history size (both in number of entries as well as the size of each individual entry) can affect the performance of your orchestrator. **Assuming you aren't doing this already: it would be worthwhile to see if you're able to circumvent these issues by splitting up some of this work into sub-orchestrations.** Sub-orchestrations reduce the History-size pressure on any given orchestration, so they're a useful optimization when you suspect your workload might be getting too large for a single orchestrator to handle. I think this may cover your question on a  fan-out batching strategy, if I understood it correctly.

> there's something we can change to let the scale controller know for these bursts to scale up a bit as our activities themselves are not queued very long.

I'll have to defer to folks with more experience on the scale controller. @bachuv, do you know?

> why DF isn't recovering once this happens and the port count drops back to near 0?

That's the core issue here, I believe. So I'd like to focus on this.

@drdamour: I took a first look at our telemetry for InstanceID `431640572ee04ee890828c7942e8f748` and saw that it only schedules two activities, and its Function name didn't match the provided `DoProcessPOs` name. This also seemed true of other instanceIDs in your list; I checked the first 3.

Can you please validate that these are the correct instanceIDs for the right appname? 
It would also help me to have a breakdown of your orchestrator structure: how it uses the DF APIs, what Function names are expected to be executed at any point in the orchestrator, etc. Sketching out some pseudocode here would be really helpful :).

Thanks!

**Comment by drdamour** [comment]
@davidmrdavid the instances shared were all the ones that were stuck once the DoProcessPOs with the thousands of actives hung.  Once it goes bad..all orchestrations seemed to be sufferring.

If you look at the logs youll see those started hours before their first activity finally got scheduled..which only happened because i deployed the app.

I can put some pseudo code together tomorrow. Theres 6 different orchestrations that generally do the same thing.

**Comment by davidmrdavid** [comment]
Oooh, I see now. Once `DoProcessPOs` get stuck, the whole app breaks. Hmm, I wonder if that could be related to the behavior we're trying to fix in this PR: https://github.com/Azure/azure-functions-durable-extension/pull/2156

Yes, pseudocode for `DoProcessPO`, and at least another affected orchestrator of your choosing would be helpful. It would also be helpful to have a highlighted instanceId for `DoProcessPO`, so we can filter our view to see how its telemetry correlates to the global behavior. Thanks!

**Comment by drdamour** [comment]
ok here goes

this is the heart of the orchestration

```c#
[FunctionName(nameof(DoProcessPOs))]
public async Task<IEnumerable<PurchaseOrderResult>> DoProcessPOs(
    [OrchestrationTrigger] IDurableOrchestrationContext context,
    ILogger log
)
{
    var input = context.GetInput<ProcessPurchaseOrdersInput>();
    log = context.CreateReplaySafeLogger(log);

    var statusEntityId = input.Watchable ?
        new EntityId(
            nameof(PurchaseOrdersRun),
            context.InstanceId
        )
        :
        (EntityId?)null;


    if (statusEntityId.HasValue)
    {
        var hrefBuilder = new UriBuilder(dfHrefProvider.MakeBaseEntitiesHref<PurchaseOrdersRun>());
        hrefBuilder.Path = hrefBuilder.Path.EnsureEndsInSlash() + statusEntityId.Value.EntityKey;


        context.SetCustomStatus(
            (await context.CallEntityAsync<PurchaseOrdersRun>(
                statusEntityId.Value,
                nameof(PurchaseOrdersRun.SetEntityStatusHref),
                hrefBuilder.Uri
            ))
            .ToStatusSummary()
        );
    }



    var candidates = await context.CallActivityAsync<ClsAPIPurchaseOrder[]>(
        nameof(FetchPurchaseOrderCandidates),
        input
    );

    if (statusEntityId.HasValue)
    {
        context.SetCustomStatus(
            (await context.CallEntityAsync<PurchaseOrdersRun>(
                statusEntityId.Value,
                nameof(PurchaseOrdersRun.SetCandidatesCount),
                candidates.Length
            ))
            .ToStatusSummary()
        );
    }

    //early exit if there were no candidates
    if (candidates.Count() == 0)
    {
        if (!input.Watchable)
        {
            context.SetCustomStatus(
                StatusSummary<PurchaseOrderResult.ResultStatus>.Simple(
                    Enumerable.Empty<PurchaseOrderResult>(),
                    r => r.Status
                )
            );
        }

        return new PurchaseOrderResult[0];
    }

    if (statusEntityId.HasValue && classifiedCandidates.ignored.Count() > 0)
    {

        var statusEntity = await context.CallEntityAsync<PurchaseOrdersRun>(
            statusEntityId.Value,
            nameof(PurchaseOrdersRun.NewResults),
            classifiedCandidates.ignored
        );

        context.SetCustomStatus(
            statusEntity.ToStatusSummary()
        );
    }


    var executions = candidates.Select(
        candidate =>
        {
            return (
                po: candidate,
                //No await here so all tasks can be submitted
                task: context.CallActivityAsync<PurchaseOrderResult>(
                    nameof(DoProcessPO),
                    (
                        candidate
                    )
                )
            );
        }
    )
    //Collect all tasks before awaiting any so DF lets them all get submitted
    .ToList()
    .Select(
        async pair =>
        {
            PurchaseOrderResult results;

            try
            {
                //we await here instead after all the tasks have been submitted
                results = await pair.task;
            }
            catch (Exception e)
            {
                log.LogError(
                    e,
                    "error processing PO [{poNumber}]",
                    pair.po.PONumber
                );

                results = new PurchaseOrderResult(
                    e,
                    pair.po
                );

            }

            if (statusEntityId.HasValue)
            {
                var statusEntity = await context.CallEntityAsync<PurchaseOrdersRun>(
                    statusEntityId.Value,
                    nameof(PurchaseOrdersRun.NewResult),
                    results
                );

                context.SetCustomStatus(
                    statusEntity.ToStatusSummary()
                );
            }

            return results;
        }
    );

    var results = (await Task.WhenAll(executions))
        .Concat(classifiedCandidates.ignored)
        .OrderBy(
            r => r.Status
        );

    //Summarize if we haven't been along the way
    if (!input.Watchable)
    {
        context.SetCustomStatus(
            StatusSummary<PurchaseOrderResult.ResultStatus>.Simple(
                results,
                r => r.Status
            )
        );
    }

    return results;
}
```


this is the what that durable entity Run is
```
public class PurchaseOrdersRun
{
    [FunctionName(nameof(PurchaseOrdersRun))]
    public static Task Run(
        [EntityTrigger] IDurableEntityContext ctx
    ) => ctx.DispatchAsync<PurchaseOrdersRun>();

    public List<PurchaseOrderResult> Results { get; set; } = new List<PurchaseOrderResult>();
    public int? CandidatesCount { get; set; }
    public Uri EntityStatusHref { get; set; }

    public Task<PurchaseOrdersRun> NewResult(
        PurchaseOrderResult result
    )
    {
        Results.Add(result);

        return Task.FromResult(this);
    }

    public Task<PurchaseOrdersRun> NewResults(
        IEnumerable<PurchaseOrderResult> results
    )
    {
        Results.AddRange(results);

        return Task.FromResult(this);
    }

    public Task<PurchaseOrdersRun> SetEntityStatusHref(
        Uri entityStatusHref
    )
    {
        this.EntityStatusHref = entityStatusHref;

        return Task.FromResult(this);
    }

    public Task<PurchaseOrdersRun> SetCandidatesCount(
        int count
    )
    {
        this.CandidatesCount = count;

        return Task.FromResult(this);
    }

    public StatusSummary<PurchaseOrderResult.ResultStatus> ToStatusSummary()
    {
        return new StatusSummary<PurchaseOrderResult.ResultStatus>(
            EntityStatusHref,
            CandidatesCount,
            Results.Count,
            Results
                .GroupBy(
                    r => r.Status
                )
                .ToDictionary(
                    g => g.Key,
                    g => g.Count()
                )
        );


    }
}
```

things go bad when we approach 4000 candidates.

The activities just make a lot of http calls that cause the connection exhaustion.  Pretty sure we found the culprit in there (some WCF client programmed to pool incorrectly, was probably never related to the IHttpClientFactory stuff at all) but that was never really my main issue.  

You've given useful answers on a few questions/issues, thx.  My remaining questions/issues are:
* why doesn't df recover fully after such an event, even when connection count gets back to near 0 in the idle state (current theory may be related to fixed in 2.7.1)
* is there any way to trigger the scale controller to start up new instances in such an event (EG by connection use or noticing the control queues not being processed)
* why does a deploy seem to "fix" the issue (again anecdotally noticed) when stop/start nor the consumption host switching (Based on host id logs)

you may notice the entity only gets involved if the input has it as watchable...the problem gets worse if we trigger it with watchable (almost on demand it causes DF to totally hang), but it happens even without all that entity messaging happening...though much more rarely (every couple of months).

**Comment by davidmrdavid** [comment]
Hi @drdamour, thank you for the update here. I understand that you're also already in touch with Azure support representatives, as they've been reaching out to me internally about this issue. We've asked them to elevate this issue so that we have direct access to this support incident. Just a heads up.

I can't quite yet answer the remaining questions, as I just realized that incident timerange you shared was using DF Extension 2.4.1. Can you please provide a timerange and corresponding instanceIds that utilize DF Extension 2.7.0? This will make sure I have the right mental model on what the code is supposed to do.

> why doesn't df recover fully after such an event, even when connection count gets back to near 0 in the idle state (current theory may be related to fixed in 2.7.1)

Can you clarify what you mean by this? What is your theory?

> is there any way to trigger the scale controller to start up new instances in such an event (EG by connection use or noticing the control queues not being processed)

You might be able to trigger the scale controller to scale up by limiting the concurrency per VM, but I'd like to hold off on this until we're able to make a more accurate diagnosis of what's going on, for which we'll need your instanceIds for 2.7.0

In the meantime, I'll see if there's anything more I can glean from the logs. Thanks!

**Comment by drdamour** [comment]
Cool. I was able to trigger it in with 2.7.0 but it was during production hours and i needed to clear it out and get things working again and wasnt able to capture those events and instance ids.  My next window to recreate will be this sunday.

i do have two stuck in our preprod, but they are a little different in that they arent causing other orchestrations to get stuck in pending.  I will follow up with their info.

Re the recovery.  What seems to be happening to me is once an instance nears the 600 connections the df internals cant function correctly. Things start failing.  Then i watch the connection count drop cia the metrics and i see other orchestrations start working..but the stuck ones stay stuck and in prod others get stuck in pending.  I see messages in the control queues but nothing is processing them it seems.

**Comment by drdamour** [comment]
fap is usos1fap02-tecsys-middleware-integrations-preprod storage account is usos1str02tecsysintegrat and two stuck instance id's are :
* 200d3e9a54dc4f079a4cfc94f51ebca7
* 5e699afaed4348c08137326d14586ff3

**Comment by davidmrdavid** [comment]
Hi @drdamour,

I took a look at the stuck instanceIDs you provided in the meantime. From my end, it looks like these orchestrators are getting stuck due to out-of-memory exceptions. In particular, from looking at the logs in the workers that are running your app, I see you're constantly hitting the memory limit during execution, which will cause the Functions Host service to restart, preventing your orchestrators from making progress past the point of the OOM-exception.

For example, starting at 2022-05-06T23:47:55.7473809Z UTC, I see that orchestrators reading from control queue usos1fap02tecsysmiddlewareintegrationspreprod-control-03 are frequently failing with the following exception:

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Newtonsoft.Json.JsonTextReader.PrepareBufferForReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at DurableTask.AzureStorage.MessageManager.DeserializeQueueMessageAsync(QueueMessage queueMessage, String queueName) in /_/src/DurableTask.AzureStorage/MessageManager.cs:line 137
   at DurableTask.AzureStorage.Messaging.ControlQueue.<>c__DisplayClass11_0.<<GetMessagesAsync>b__0>d.MoveNext() in /_/src/DurableTask.AzureStorage/Messaging/ControlQueue.cs:line 108
```

It would appear that the Functions Host restarts shortly after, initiating the cycle again.

At the moment, I don't know what is causing your app to run out of memory, but I can provide a few things to try in order to reduce the memory pressure from your app.

As a guiding principle, we should look to minimize the memory footprint of your orchestrators' History data structure. There are two main ways of doing this.

(1) To ensure each entry in the History is small. To do this, you need to keep inputs and outputs to activities (and other DF APIs) small. In general, each input and output to a DF API is serialized to storage, and read during orchestrator replay. So, in order to ensure the History size doesn't blow up, you want to keep inputs and outputs lightweight. By doing this, you'll also be keeping inputs and outputs to our work and control queues small.

(2) To ensure the History doesn't grow too large. To do this, you'll want to make use of SubOrchestrators, which provide a way to divide a large workflow into smaller, cooperating, workflows. Can you try to batch your 4k Activity FanOut into mid-size groups of Activities, and have them each be processed, ideally to completion, by a Sub-orchestrator? This will make sure each orchestrator's History remains at a manageable size.

This is where I would start. Again, from my perspective, I'm not yet seeing the connection-exhaustion problem you describe as causing this issue. Instead, it seems to me that your orchestrator is somehow running out of memory to complete your workflow.

Please let me know if you can try these mitigations, and whether they succeed. I'll also await your instanceIds on your prod app using 2.7.0. Thanks!

**Comment by cgillum** [comment]
Additional tips on memory management can be found in our [Performance and Scale documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale).
