### ISSUE TITLE
Azure Durable Entity cannot be reached anymore , seems like signals are being queued and not read

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/azure-functions-durable-extension#2166]
### Description
I am using Azure Durable Functions and have this running in production. All goes well, but for one specific Durable Entity, it seems I can no longer reach that entity anymore.  Signals, Calls... Everything seems to be ignored. And when using the DFM (Durable Functions Monitor), I remember seeing something like queue depth (or queue length) that was rather high.

### Expected behavior
When sending a signal to the entity, the logic to handle that signal should be performed.

### Actual behavior
No logic is being performed, as it seems all messages are queued / locked and not being picked up.

### Relevant source code snippets

I don't believe the code snippets will be that relevant, as it's always been working for that entity and others as well.  It seems to be more of an infrastructure issue.

```csharp
await _entityClient.SignalEntityAsync(CotacolUserEntity.GetUserEntityId(userId), nameof(CotacolUserEntity.AddBookmarksAsync), bookmarks);
```

### Known workarounds
- I would be happy to clear that queue and lose any existing signals. How could I do this?
- I would even be happy to clear/remove that entity, but even that does not seem possible, as I have only found to clear state of an entity from inside an entity itself.
- Is there any troubleshooting tips someone can give?

### App Details

- **Durable Functions extension version**: 2.6.1 
- **Azure Functions runtime version**: 3.5.2.0
- **Programming language used**: C# 8.0

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: since few weeks
- **Function App name**: cotacol-hunting-workers
- **Function name(s)**: CotacolUserEntity
- **Azure region**: West-Europe
- **Orchestration instance ID(s)**: @cotacoluserentity@4842724
- **Azure storage account name**: cotacolhuntingfx

**Comment by SamVanhoutte** [comment]
Is there any information or update on this one, please ?

**Comment by davidmrdavid** [comment]
Sorry for the late response, seems we accidentally missed this. @sebastianburckhardt, just a friendly ping here.

**Comment by sebastianburckhardt** [comment]
@SamVanhoutte, I took a look at the behavior of the instance "@cotacoluserentity@4842724" which I believe is the one you mentioned above. From what I can see so far, it seems to be processing messages normally. There have been many executions over the last 14 days and no obvious errors in the logs. 

I did notice error messages about a different entity, with id "@cotacoluserlistentity@CotacolUserListEntity" which appears to have entered a Failed state. Is this the entity that is causing your issues?

Regardless, entities are never supposed to enter a Failed state. I will keep investigating.

**Comment by sebastianburckhardt** [comment]
I found an out-of-memory exception at timestamp `2022-03-22 08:32:43.1703004` (almost a month ago). This happens during serialization of the entity state for `@cotacoluserlistentity@CotacolUserListEntity`, likely because that entity's state is too large. As a result, that entity then entered a "Failed" state, from which it can never recover.

This is definitely not the intended behavior. Exceptions that happen during the entity processing logic are intended to be handled either by retrying the entire work-item, or by failing the constituent operations and rolling back to the last good entity state.

**Comment by SamVanhoutte** [comment]
Is there anything I can do to change , recreate or delete the entity and get it away from the failed state?

**Comment by SamVanhoutte** [comment]
Any news or update on this one?  Seems problems are not getting better

**Comment by lilyjma** [comment]
@SamVanhoutte -- are you still experiencing the problem? Did Sebastian's suggestion help?

**Comment by davidmrdavid** [comment]
I believe @sebastianburckhardt's looking into this, but he's out of office for a few more days so he won't be able to provide an update if there's one.

I suggest to keep this issue open until then.

**Comment by sebastianburckhardt** [comment]
I am currently trying to get a local repro by manually injecting OOM faults.

**Comment by sebastianburckhardt** [comment]
I was able to get a local repro. The next step is to figure out how to best fix the problem.

**Comment by SamVanhoutte** [comment]
@sebastianburckhardt , thanks for the updates and the apparent fix.  is there something I should do, in order to have these changes applied?  
- is there a nuget package, I have to upgrade? 
- do I have to make any changes to my existing deployment?
- anything else that should be done from my side?

**Comment by SamVanhoutte** [comment]
@sebastianburckhardt : also : how can I query my task hub to get a list of all entities that are in a failed state?  I don't see the HTTP request available to do that (only for instances/orchestrations)

**Comment by davidmrdavid** [comment]
Hi @SamVanhoutte - as for the fix, it should be available in a matter of days on the standard NuGet package. If a delay comes our way, I can also prepare a private MyGet package for you to try out this patch.

On the other questions - I'll defer to @sebastianburckhardt. However, I'm under the impression that the same query that works for orchestrators, would work for entities (due to them sharing their underlying infrastructure). Though I haven't had the bandwidth to check that today.
