### ISSUE TITLE
ConfigureFunctionWorkerDefaults not found in Microsoft.Extensions.Hosting 5.0

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-functions-durable-extension#2170]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#28618](https://github.com/Azure/azure-sdk-for-net/issues/28618).

## Details

Trying to upgrade durable functions from .net core 3.1 to  net 6  and 
have added reference to package  Microsoft.Azure.WebJobs.Extensions.Storage

but this function is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3e2a02-640c-c537-48bb-e8f1b26c7b5d
* Version Independent ID: 3f8a0a7b-7d1e-735f-3098-cebc82e980df
* Content: [WorkerHostBuilderExtensions.ConfigureFunctionsWorkerDefaults Method (Microsoft.Extensions.Hosting) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.workerhostbuilderextensions.configurefunctionsworkerdefaults?view=azure-dotnet&preserve-view=true#Microsoft_Extensions_Hosting_WorkerHostBuilderExtensions_ConfigureFunctionsWorkerDefaults_Microsoft_Extensions_Hosting_IHostBuilder_)
* Content Source: [xml/Microsoft.Extensions.Hosting/WorkerHostBuilderExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Extensions.Hosting/WorkerHostBuilderExtensions.xml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by lilyjma** [comment]
Hi @megangerfen2 -- could you elaborate on what you meant by "this function is not available"? Thanks!

**Comment by kshyju** [comment]
@megangerfen2 The [ConfigureFunctionsWorkerDefaults ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.workerhostbuilderextensions.configurefunctionsworkerdefaults?view=azure-dotnet&preserve-view=true#Microsoft_Extensions_Hosting_WorkerHostBuilderExtensions_ConfigureFunctionsWorkerDefaults_Microsoft_Extensions_Hosting_IHostBuilder_)is a method used for bootstrapping an [isolated(out-of-process) dotnet worker function app](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide). Is your function app in-proc or out-of-process? For an in-proc app, you should not be using this method. As of today(5/20/2022), durable functions are not supported on isolated dotnet worker apps.

**Comment by serhatataman** [comment]
I am still experiencing the same issue on Azure Durable Functions 2.0 and .NET 6. 
![image](https://user-images.githubusercontent.com/38012961/214343094-4f036a97-cc88-43c6-be8c-ab1d621eb43b.png)

**Comment by cgillum** [comment]
@serhatataman what's your .csproj look like?

**Comment by serhatataman** [comment]
![image](https://user-images.githubusercontent.com/38012961/214851394-40638794-ba3d-44b3-acf1-1464a54e0f6e.png)

**Comment by cgillum** [comment]
@serhatataman it looks like your project is using the in-process model, so this extension method doesn't apply for your setup. @kshyju can confirm, but I don't believe Functions middleware is supported in the in-process .NET worker. You'd need to switch to the .NET Isolated worker project type to use middleware.
