### ISSUE TITLE
Support using Service Principle or Managed Identity when choose Azure Storage as storage provider

### ISSUE THREAD

**Issue by amsteel** [Azure/azure-functions-durable-extension#2171]
**Is your feature request related to a problem? Please describe.**
Using account key to access Azure storage is not allowed enterprise wide.

**Describe the solution you'd like**
Support using Service Principle or Managed Identity when choose Azure Storage as storage provider.

**Additional context**
Microsoft recommends  "Prevent Shared Key authorization for an Azure Storage account" as part of the best practice.
https://docs.microsoft.com/en-us/azure/storage/common/shared-key-authorization-prevent?tabs=portal

**Comment by cgillum** [comment]
FWIW, this is supported today in the v2.7.0 release of the Durable extension. Documentation is forthcoming. If you want to try it now, you can find setup information in this comments of this PR: https://github.com/Azure/azure-functions-durable-extension/pull/2014

**Comment by amsteel** [comment]
Thanks, will try it out. And please update the documentation.
