### ISSUE TITLE
What's the alternative for ExecuteMultipleRequest,ExecuteTransactionRequest

### ISSUE THREAD

**Issue by priyanksster** [Azure/azure-functions-durable-extension#2179]
I am using version 1.0.25 of XRM.Tools.CRMWebAPI with Durable Function using .Net Core 3.1 . Just wondering, does the CRMWebAPI offer any alternative to using ExecuteMultipleRequest or ExecuteTransactionRequest of [Microsoft.Xrm.Sdk.Messages] . My requirement is to create multiple entity records in one transaction so that if one fails , they all will be rolled over.

**Comment by cgillum** [comment]
Hi @priyanksster, we’re not familiar with XRM.Tools.CRMWebAPI and unfortunately can’t answer questions about it here. This question should be asked to the maintainers of that library.
