### ISSUE TITLE
Error indexing model

### ISSUE THREAD

**Issue by PGoodeBDO** [Azure/azure-functions-durable-extension#2192]
### Description
>I'm using Durable Functions, and have an orchestrator that inherits from a base orchestrator.   Everything seems to be written correctly, and the orchestration works, however, the framework prints an error indexing the method

### Expected behavior
> Durable functions framework should be able to index the method

### Actual behavior
> An error is shown:

Error indexing method 'Orchestrators.ProcessModel'
[2022-05-26T12:35:05.522Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'Orchestrators.ProcessModel'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'itm' to type JobItem. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

### Relevant source code snippets
```csharp
   public class BaseOrchestrator
    {
        protected async Task<List<ModelProcessorResponse>> RunOrchestration(
             [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            var config = context.GetInput<DbBuilderModelConfiguration>();
            var outputs = new List<Task<ModelProcessorResponse>>();

            foreach (var item in config.Contexts.SelectMany(i => i.Items))
            {
                var task = ProcessModel(context, item);               
                outputs.Add(task);
            }

            return (await Task.WhenAll(outputs.ToArray())).ToList();
        }

        protected async Task<ModelProcessorResponse> RunOrchestrationSingleModel(
            [OrchestrationTrigger] IDurableOrchestrationContext context, JobItem item)
        {
            var output = await ProcessModel(context, item);
            return output;
        }

        public virtual async Task<ModelProcessorResponse> ProcessModel([OrchestrationTrigger] IDurableOrchestrationContext context, JobItem itm)
        {
            throw new NotImplementedException();
        }
    }

   public partial class Orchestrators : BaseOrchestrator
    {
        [FunctionName("our name here")]
        public async Task<List<ModelProcessorResponse>> RunOrchestrator(
          [OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
        {
            return await base.RunOrchestration(context);          
        }

        public override async Task<ModelProcessorResponse> ProcessModel([OrchestrationTrigger] IDurableOrchestrationContext context, JobItem itm)
        {
            var response =  await context.CallActivityAsync<ModelProcessorResponse>("activity name here", itm);
        
            //var response = await context.CallActivityAsync<ModelProcessorResponse>("test name here", itm);
            return response;
        }
    }
```

### Known workarounds
> I just let the job run, and it runs fine

### App Details

- **Durable Functions extension version 1.1.0**:
- **Azure Functions runtime version 2.0**:
- **Programming language used** C#:

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- Any other way to not share publicly?
- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.
** How do you obtain the orchestration ID

**Comment by davidmrdavid** [comment]
Hi @PGoodeBDO, thanks for reaching out.

Would it be possible for you to attach a `.zip`'ed reproducer of this error? That would help us investigate this faster, and make sure we're working with the same dependencies as you are. Thanks!

**Comment by PGoodeBDO** [comment]
Hi, sure thank you for responding.  Is there a way I can send you something non publicly?  I cannot send this publicly.  Or, I can set up a test project.  Thanks

**Comment by cgillum** [comment]
Hi @PGoodeBDO. I think the issue is that you're putting the `[OrchestrationTrigger]` attribute on parameter methods that aren't supposed to be considered function trigger inputs. While it may seem harmless to add this attribute, it actually causes the Functions runtime indexer to try and do special processing of these methods, which fails because they don't follow the rules for normal function declarations.

To get unblocked, try removing `[OrchestrationTrigger]` from everything except the function trigger entry point. Here's a snippet that I expect will work correctly for you:

```csharp
public class BaseOrchestrator
{
	protected async Task<List<ModelProcessorResponse>> RunOrchestration(
		 IDurableOrchestrationContext context)
	{
		var config = context.GetInput<DbBuilderModelConfiguration>();
		var outputs = new List<Task<ModelProcessorResponse>>();

		foreach (var item in config.Contexts.SelectMany(i => i.Items))
		{
			var task = ProcessModel(context, item);               
			outputs.Add(task);
		}

		return (await Task.WhenAll(outputs.ToArray())).ToList();
	}

	protected async Task<ModelProcessorResponse> RunOrchestrationSingleModel(
		IDurableOrchestrationContext context, JobItem item)
	{
		var output = await ProcessModel(context, item);
		return output;
	}

	public virtual async Task<ModelProcessorResponse> ProcessModel(IDurableOrchestrationContext context, JobItem itm)
	{
		throw new NotImplementedException();
	}
}

public partial class Orchestrators : BaseOrchestrator
{
	[FunctionName("our name here")]
	public async Task<List<ModelProcessorResponse>> RunOrchestrator(
	  [OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
	{
		return await base.RunOrchestration(context);          
	}

	public override async Task<ModelProcessorResponse> ProcessModel(IDurableOrchestrationContext context, JobItem itm)
	{
		var response =  await context.CallActivityAsync<ModelProcessorResponse>("activity name here", itm);
	
		//var response = await context.CallActivityAsync<ModelProcessorResponse>("test name here", itm);
		return response;
	}
}
```
