### ISSUE TITLE
Durable Actors

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#22]
## Summary
Durable Functions supports "actor-style" (note the quotes) development today, but the experience has some rough edges and some key capabilities are missing, like the ability for one instance to create other instances.  This issue will track supporting a more native "actor" experience.

## Disclaimer
There are several powerful, fully-featured actor frameworks available to developers today, including [Orleans](https://dotnet.github.io/orleans/) and [akka.net](http://getakka.net/) for .NET developers, in addition to frameworks for other platforms. **There is no intention of replicating the feature set or the programming model of these existing actor frameworks**. Rather, the intent of this design is to enable a simple, baseline, Azure Functions-friendly actor implementation that will be useful for the most common scenarios.

## Motivation
The [Actor Model](https://en.wikipedia.org/wiki/Actor_model) is a popular and powerful form of stateful, scalable, distributed programming in the cloud. The Durable Task Framework (DTFx) already supports the most important capabilities of actors, including messaging, isolated state, concurrency, and global addressability, so extending Durable Functions to support the actor model in a more native way would be relatively trivial and should require few if any new concepts.

What's missing from existing actor frameworks is the "serverless" capability, which Durable Functions is uniquely positioned to deliver. Azure Functions also supports a variety of diverse programming languages. As that support is brought into Durable Functions, there is the possibility of enabling users to build actors on a single platform but in the language of their choice (including a mix of languages), which is also unique.

## Design Notes
There are a few things related to the programming model which should be considered in supporting the actor model in Durable Functions. Consider these suggestions.

* The `ContinueAsNew` API should not be required. As an alternative, a new trigger binding could be created that inherits from the orchestration trigger and automatically ensures that `ContinueAsNew` is called when the function exits.
* To better support actors creating other actors, a new primitive could be added to DTFx (and surfaced by Durable Functions) which allows creating new instances from within an existing instance and getting back the address. It's possible to implement this manually using an activity function as glue, but ideally there would be native support for this. Note that this is not the same as the planned [sub-orchestration](https://github.com/Azure/azure-functions-durable-extension/issues/15) feature.
* There is a known race condition where sending events to an orchestration instance which is currently executing the `ContinueAsNew` path can result in failures. This race would need to be addressed in order to support a usable actor model implementation.
* Stream processing scenarios would benefit from a model where the client doesn't need to know whether an instance exists before sending it a message. For example, consider a `RaiseEventAsync` method which creates an instance if it doesn't already exist and delivers the message to that instance.

## Drawbacks
* Other cloud-friendly actor model implementations already exist, including [Orleans](https://dotnet.github.io/orleans/), [Akka](http://akka.io/), and [Service Fabric Reliable Actors](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-reliable-actors-introduction), many of which are also open source and can be run in Azure. "Durable Actors" would be yet another implementation.
* While not required by the baseline actor model, other popular actor frameworks support RPC-style message handling with operations and state implemented using an object-oriented abstraction. Durable Functions (and Azure Functions, for that matter) cannot and would not support an object-oriented programming model, which may initially throw off some experienced actor developers.

**Comment by cgillum** [comment]
Per some internal discussion, it's not clear if this is the direction we want to go right now. Closing this for the time being (though others can feel free an comment if interested).

**Comment by amang2205** [comment]
I'm wondering it there's an update on this. "not clear if this is the direction we want to go right now" sounds bad :-)

**Comment by cgillum** [comment]
We're not considering this for GA. It's mostly for technical reasons. The Durable Task Framework is not designed for actor-style messaging patterns so it would be a significant effort to build this on a way that would actually work for folks who need cloud-scale actors in production.

That said, there is still a lot of interest so we could reconsider this in the future. But for now we're going to focus on building a great orchestration story.

**Comment by hoffmanic** [comment]
@cgillum understood, but the documentation still refers to actor-style messaging https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-singletons

Can you please remove this from the docs as it's confusing.

**Comment by cgillum** [comment]
We're currently looking into officially supporting actors again, so I'm re-opening this issue. There have been some significant fixes made in DTFx since we first closed this issue that were required for this, so the technical feasibility has increased quite a bit.

For anyone interested in Durable actors, we'd love to know more about your scenarios since we're still in the early design stages. Feel free to chime in.

**Comment by jedjohan** [comment]
What I would like Durable actors to do is very similar to Service Fabric - Stateful Reliable Services, a model I really like. The drawback of Service Fabric is that it is way to much infrastructure and plumbing. My hope is that it would allow me to implement the actor model complete with messaging (between actors) and that they keep their own state without depending on explicit persisting storage.

**Comment by cgillum** [comment]
We released our first version of the "Durable Actor" support as part of our [v2.0.0-alpha release](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.0.0-alpha) (rebranded as **Durable Entities**)!

It's still early days, and we're going to continue iterating on our model and taking feedback, but keep an eye out for future updates in our **2.x** release train.

**Comment by msajid** [comment]
It would be great if we can get EntityId of the parent DurableEntity (not Orchestrator) in a "context" of child DurableEntity. I am trying to implement Actor hierarchy and passing the parent id with each message to child Entities to achieve this.

**Comment by cgillum** [comment]
@msajid thanks for the suggestion. Would you mind opening a new issue to help us better track this request?
