### ISSUE TITLE
Hybrid mode with Azure Storage provider

### ISSUE THREAD

**Issue by petronellius** [Azure/azure-functions-durable-extension#2204]
### Description
I am trying to run my app in hybrid mode - run function app locally with real connection string to Azure Storage.

### Expected behavior
I would expect run it in hybrid mode. I tried the same with [Netherite](https://youtu.be/GRcHeZkmVcM?t=1019) and it seems to work. 

### Actual behavior
Starting of orchestrator is failing with error "The function "ABC" doesn't exist,..."

### Relevant source code snippets
local.settings.json
![image](https://user-images.githubusercontent.com/12825401/171852059-e83be7c8-e1f0-46a0-8c9f-07ad079319d5.png)

host.json
![image](https://user-images.githubusercontent.com/12825401/171852119-5d8353b1-21c3-4033-aadb-87077106f9a5.png)

DurableClientFactory registration
![image](https://user-images.githubusercontent.com/12825401/171852283-57e9e614-0b4b-43ab-94e5-e5b8f6506476.png)

IDurableClientFactory is then injected into the constructor of MediatR command handler where the instance of IDurableClient is created through IDurableClientFactory.CreateClient() method. The orchestrator is started in Handle method through IDurbaleClient.StartNewAsync() method. After that the execution finished and I can see the error message in instances table "Orchestrator function 'ABC' failed: The function 'ABC' doesn't exist, is disabled, or is not an orchestrator function.".

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.6.1
- **Azure Functions runtime version (1.0 or 2.0)**: 4
- **Programming language used**: C#

**Comment by cgillum** [comment]
I'll start with the obvious question, which is: do you have an orchestrator function named 'ABC' defined (and enabled) in your app?

My second question is: do you have more than one Durable app that's connecting to this same storage account + task hub combo?

**Comment by petronellius** [comment]
The second question will be correct. The previous version is already deployed on Azure with the same storage account. Is it enough to change just task hub name and use the same storage account also locally?

**Comment by cgillum** [comment]
Yeah, have the local app use a different task hub name and I suspect everything will work correctly. More info on task hub name conflicts here: https://docs.microsoft.com/azure/azure-functions/durable/durable-functions-task-hubs.

**Comment by petronellius** [comment]
Works perfectly. Thanks a lot!
