### ISSUE TITLE
OrchestrationFailureException even when Activity handles exception.

### ISSUE THREAD

**Issue by amadard** [Azure/azure-functions-durable-extension#2208]
### Description

I have an activity that is retrieving WorkItem details from Azure DevOps using the WorkItemTrackingHttpClient.  There is the possibility that the WorkItem ID passed in does not exist, so I have the call of the activity wrapped in a Try/Catch, and explicitly handle that specific exception, while throwing any other exceptions.  If there is no exception, a WorkItem is returned, if the exception is handled, null is returned.

I have an orchestration calling this activity, and it is encountering a DurableTask.Core.Exceptions.OrchestrationFailureException:

Exception while executing function: XXX Orchestrator function 'XXX' failed: The activity function 'GetWorkItemDetails' failed: "TF401232: Work item 18098 does not exist, or you do not have permissions to read it.". See the function execution logs for additional details. 

I have tested the activity code separately, and the Try/Catch is properly catching the exception, so the activity should be returning null, which the Orchestration is prepared to handle properly.

### Expected behavior
> The activity should be properly handling the exception so that the Orchestration does not fail due to the exception that was handled by activity.  The exception should not be marshalled back to the Orchestration.

### Actual behavior
> An exception is caught by the Activity, logged, and the activity returns null.  The Orchestration fails due to a OrchestrationFailureException, with the exception from the activity.

### Relevant source code snippets
```csharp
        [FunctionName("GetWorkItemDetails"]
        public Task<WorkItem> GetWorkItemDetails([ActivityTrigger] int Id, ILogger log)
        {
            try
            {
                return witClient.GetWorkItemAsync(Id, expand: WorkItemExpand.Fields);
            }
            catch (Microsoft.VisualStudio.Services.Common.VssServiceException vssEx)
            {
                if (vssEx.Message.Contains("TF401232"))
                {
                    //can't retrieve work item with PAT
                    //either doesnt exist, or insufficient permissions
                    log.LogError(vssEx, "Unable to GetWorkItemDetails");
                    return null;
                }
                else
                {
                    throw;
                }
            }
        }
```

**Comment by cgillum** [comment]
This appears to be a bug in your code. Try making your activity function definition `async` and calling `await` on the result of `GetWorkItemAsync`. Otherwise, the exception won't actually be observed by the catch block:

```csharp
[FunctionName("GetWorkItemDetails")]
public async Task<WorkItem> GetWorkItemDetails([ActivityTrigger] int Id, ILogger log)
{
    try
    {
        return await witClient.GetWorkItemAsync(Id, expand: WorkItemExpand.Fields);
    }
    catch (Microsoft.VisualStudio.Services.Common.VssServiceException vssEx)
    {
        if (vssEx.Message.Contains("TF401232"))
        {
            //can't retrieve work item with PAT
            //either doesnt exist, or insufficient permissions
            log.LogError(vssEx, "Unable to GetWorkItemDetails");
            return null;
        }
        else
        {
            throw;
        }
    }
}
```

**Comment by amadard** [comment]
Thanks, I totally overlooked the deferral of awaiting the call.  That was the issue.
