### ISSUE TITLE
Durable Entity operation not appearing to execute serially

### ISSUE THREAD

**Issue by amadard** [Azure/azure-functions-durable-extension#2212]
### Description
> I have a counter style durable entity that is keeping track of number of calls per time period to prevent exceeding rate limits on a dependent system.  My orchestration calls the durable entity, and proceeds to the activity if successful, and sets a timer to re-call the durable entity if not successful.  When running locally, my durable entity always keeps track accurately.  When deployed to Azure, the orchestrations are overrunning the limit.  It does not appear that the durable entity is processing the calls serially.  It may be an issue in my code, but I have not been able to recreate the issue when running locally.

### Expected behavior
> When fanning out sub-orchestrations, I expect the durable entity to receive and process the calls serially, and maintain an accurate state.

### Actual behavior
> The durable entity appears to be not keeping an accurate state and responding serially when called by a large number of orchestrations.

### Relevant source code snippets
```csharp
    public interface IAPILimiter
    {
        Task<bool> AllowedToRun(string InstanceId);
    }

    [JsonObject(MemberSerialization.OptIn)]
    public class APILimiter : IAPILimiter
    {
        [JsonProperty()]
        public List<LimitRecord> LimitRecords { get; set; } = new List<LimitRecord>();

        public Task<bool> AllowedToRun(string InstanceId)
        {
            var timestamp = DateTime.UtcNow;

            var record = new LimitRecord()
            {
                InstanceId = InstanceId,
                AllowedToRun = false,
                TimeStamp = timestamp
            };

            if (LimitRecords.Any(x => x.InstanceId == InstanceId))
            {
                record = LimitRecords.First(x => x.InstanceId == InstanceId);
            }
            else
            {
                LimitRecords.Add(record);
            }

            record.TimeStamp = timestamp;

            LimitRecords.RemoveAll(x => x.AllowedToRun &&
            x.TimeStamp <= timestamp.AddMinutes(-2));

            //actual is 100
            //set lower to prevent running into 100 limit and triggering 30 min wait
            if (LimitRecords.Count(x => x.AllowedToRun) >= 75)
            {
                record.AllowedToRun = false;
                return Task.FromResult(false);
            }

            record.AllowedToRun = true;
            return Task.FromResult(true);
        }

        [FunctionName(nameof(APILimiter))]
        public static Task Run([EntityTrigger] IDurableEntityContext ctx) => ctx.DispatchAsync<APILimiter>();
    }

    public class LimitRecord
    {
        public string InstanceId { get; set; }
        public bool AllowedToRun { get; set; }
        public DateTime TimeStamp { get; set; }
    }
	
	
	
	
	//Orchestration code
            var allowedToRun = await context.CreateEntityProxy<IAPILimiter>("GetBugsForProject")
                .AllowedToRun(context.InstanceId);

            while (!allowedToRun)
            {
                await context.CreateTimer(context.CurrentUtcDateTime.Add(TimeSpan.FromMinutes(2)), CancellationToken.None);
                allowedToRun = await context.CreateEntityProxy<IAPILimiter>("GetBugsForProject")
                    .AllowedToRun(context.InstanceId);
            }

            var (responseCode, content) = await context.CallActivityAsync<(HttpStatusCode, string)>
                  ("GetBugsForProject", project);
```

**Comment by davidmrdavid** [comment]
Thanks for reaching out @amadard.

Could you please clarify what you mean by "serially" in this case? Are you seeing entities respond in the wrong order? If so, could you provide an example?

Furthermore, if you have a reproducer on Azure, it would help us to have your application name, entity ID, and a timerange in UTC where we can observe this issue.

Thanks!

cc/ @sebastianburckhardt

**Comment by amadard** [comment]
As I was writing my response I realized a possible reason was a delay in the sub-orchestrators activating due to the size of the fan out and the queueing of the sub-orchestrator replays.  I added a method to the durable entity to "complete" instances, and that resolved my issue.
