### ISSUE TITLE
Durable entity gets stuck in scheduled state

### ISSUE THREAD

**Issue by vany0114** [Azure/azure-functions-durable-extension#2220]
### Description
Sometimes when a durable entity is signaled from an orchestrator client (EG trigger FWIW) the entity gets stuck in the `scheduled` status.

### Expected behavior
I'd expect that the durable entity status is `complete` after it was signaled. 

### Actual behavior
It seems that it is getting stuck at some point when the entity is signaled, not sure if there's something wrong with my implementation (maybe the async calls or it is swallowing an error?)

### Relevant source code snippets
```csharp
// Durable entity
public interface IOrder
{
    void Identify(OrderIdentifyInput input);

    Task Place(string orderId);

    Task Patch(PatchOrderInput input);

    Task TransitionStatus(TransitionOrderInput input);
}

[JsonObject(MemberSerialization.OptIn)]
public class Order : IOrder
{
    [JsonIgnore]
    private readonly ILogger<Order> _logger;

    [JsonIgnore]
    private readonly ICommandBus _commandBus;

    [JsonIgnore]
    private readonly IOptions<Settings> _settings;

    [JsonProperty("Id")]
    public string Id { get; set; }

    [JsonProperty("status")]
    public OrderStatus Status { get; set; } = OrderStatus.UNDETERMINED;


    [JsonProperty("pendingStatuses")]
    public List<(OrderStatus Status, string Traceparent)> PendingStatuses { get; set; } = new List<(OrderStatus, string)>();


    public Order(ILogger<Order> logger, IOptions<Settings> settings, ICommandBus commandBus)
    {
        _logger = logger;
        _settings = settings;
        _commandBus = commandBus;
    }

    public async Task TransitionStatus(TransitionOrderInput input)
    {
        // some logic to aggregate status in ProcessedStatuses
        ...

        foreach (var status in ProcessedStatuses)
        {
            Status = status.Status; 
            Source = status.Source;
            await SendTransitionOrderStatusCommand(); 
        }
    }

    private async Task SendTransitionOrderStatusCommand()
    {
        ...
        await _commandBus.Send("some-queue", command, options);
    }

    [FunctionName(nameof(Order))]
    public static Task Run([EntityTrigger] IDurableEntityContext ctx)
        => ctx.DispatchAsync<Order>();
}

// client
public static async Task OrderStatusTransitionedHandler([EventGridTrigger] EventGridEvent eventGridEvent, [DurableClient] IDurableEntityClient starter, ILogger log)
{
    var entityId = new EntityId(nameof(Order), "some-id");
    await starter.SignalEntityAsync<IOrder>(entityId, async order =>
    {
// maybe the issue could be here? I haven't seen this syntax (awaiting the method) in the samples, however, I haven't seen an async method in a durable entity in the examples.
        await order.TransitionStatus(new TransitionOrderInput
        {
	    Status = @event.Status
        });
    });
}
```

### Known workarounds
None

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: Microsoft.Azure.WebJobs.Extensions.DurableTask 2.5.1
- **Azure Functions runtime version (1.0 or 2.0)**: v3 and netcore3.1
- **Programming language used**: C#

### Screenshots
Notice how it got stuck in `Scheduled` status, the previous signal was processed correctly tho.
![image](https://user-images.githubusercontent.com/12032625/176334181-c738c033-3e9f-4be5-8314-8ed26debbb3c.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: within `2022-06-24 22:10:25.2738203` and `2022-06-25 04:53:30.5071382`
- **Function App name**: `infra-integrations-order-saga`
- **Function name(s)**:
- **Azure region**: westus
- **Orchestration instance ID(s)**: `@order@{"siteUID":"08bacd63-da28-47fb-881e-2c067998a744","checkNumber":"121638997","openedAt":"2022-06-25"}_qsr`
- **Azure storage account name**: fnappoqvyas2ldjjxc

**Comment by vany0114** [comment]
cc @cgillum

**Comment by cgillum** [comment]
@vany0114 Before anyone dives too deep into this, I highly recommend upgrading to a newer Durable extension version, like v2.7.1.  This will ensure you're not running into any bugs that have already been fixed. It will also help ensure that we have the best logs available to debug the issue if it still occurs.

**Comment by vany0114** [comment]
@cgillum Will do, but what about this syntax, is that correct or it should be used w/o the await:

``` 
await starter.SignalEntityAsync<IOrder>(entityId, async order =>
    {
        // maybe the issue could be here? I haven't seen this syntax (awaiting the method) in the samples, however, I haven't seen an async method in a durable entity in the examples.
        await order.TransitionStatus(new TransitionOrderInput
        {
	    Status = @event.Status
        });
    });
```

it should be like this?
``` 
await starter.SignalEntityAsync<IOrder>(entityId, order =>
    {
        order.TransitionStatus(new TransitionOrderInput
        {
	    Status = @event.Status
        });
    });
```

**Comment by cgillum** [comment]
@vany0114 hmm, I'm not sure what it means to pass an async lambda as a parameter to a method that takes an `Action<TEntityInterface>` in C#. The [implementation of SignalEntityAsync](https://github.com/Azure/azure-functions-durable-extension/blob/ab29ee8fc1a4904db16027081a362eeb17aaa906/src/WebJobs.Extensions.DurableTask/ContextImplementations/DurableClient.cs#L994-L1007) doesn't await anything, so I'm not sure what the expectation is. 🤔

**Comment by vany0114** [comment]
@cgillum  So it means that only sync operations can be signaled? I think that probably would be worth adding an overload that supports Func<Task> to allow handling the async code properly, not sure 🤔

**Comment by cgillum** [comment]
It does seem a little odd to me that only blocking client-side operations would be supported. Adding @sebastianburckhardt to get his opinion on this (though he's currently on vacation).

**Comment by cgillum** [comment]
I think he'll be back on Monday (but may need some time to get caught up on all the things he missed). :)

**Comment by sebastianburckhardt** [comment]
I had a closer look at our internal logs using the precise data you supplied (thanks!). It appears that the operation in question (marked with a red arrow in your screenshot) did in fact execute and complete successfully. Also, this is not the last operation that executed on this entity, there are more after that.

Therefore, I suspect that something is wrong with the trace in your screenshot - it is incomplete. To continue, I will need to know where this screenshot came from. Is this something you copied from the portal? If so, where? Or is this generated by the application code? In my personal experience, those traces are sometimes incomplete (for example, AppInsights sometimes summarizes events).

**Comment by vany0114** [comment]
@sebastianburckhardt thanks for looking into this, that's the query result of the queries suggested [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics?tabs=javascript). 

This is how the `host.json` looks like FWIW:
```
{
  "extensions": {
    "durableTask": {
      "tracing": {
        "distributedTracingEnabled": true,
        "distributedTracingProtocol": "W3CTraceContext"
      },
      "storageProvider": {
        "useLegacyPartitionManagement": false,
        "connectionStringName": "SAGA_ORCHESTRATOR_DUEABLETASK_STORAGE_CONNECTIONSTRING"
      },
      "useGracefulShutdown": true
    }
  },
  "logging": {
    "logLevel": {
      "default": "Information",
      "Function": "Information",
      "Host.Results": "Information",
      "Host.Executor": "Critical",
      "Host.Aggregator": "Information"
    },
    "applicationInsights": {
      "httpAutoCollectionOptions": {
        "enableW3CDistributedTracing": true
      }
    }
  },
  "version": "2.0"
}
``` 

BTW can you share the additional logs that you spotted 
> [...] Also, this is not the last operation that executed on this entity, there are more after that.

**Comment by sebastianburckhardt** [comment]
I think Application Insights may have dropped the trace events for some reason. One possible explanation is that it uses [sampling](https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2#configure-sampling) by default.

Adding this section to the host.json should disable sampling:
```json
{
  "logging": {
    "applicationInsights": {
      "sampling": {
        "isEnabled": false
      }
    }
  }
}
```

Let me know if you keep experiencing this problem even with sampling disabled.

> BTW can you share the additional logs that you spotted

In our internal traces these are the last few operations executed on this entity:
![image](https://user-images.githubusercontent.com/6415760/178836609-f1fd70fe-c061-410d-9f5a-0f08251cff2c.png)

**Comment by vany0114** [comment]
@cgillum @sebastianburckhardt we're seeing this issue again 😨 in our production environment...orchestrators getting stuck for hours, this is just an example:

instance id: `{"orderId":"14360566278389760","storeNumber":"16","brandId":"f6306b87-5975-ec11-aaad-0e885b099c11"}`
![image](https://user-images.githubusercontent.com/12032625/204152063-95fffc4d-0cab-4d0d-892b-3f43fd4c583d.png)

Can you guys please help look into it? we have faced this issue several times, we really need to get to the bottom of this because every time this issue comes impacts negatively our customers. For what is worth, to workaround it, I have to clean up the storage account by deleting it and then recreate it, same with the func app, which makes me wonder that for some reason the resources under the storage account that the orchestrator relies on get in a bad shape or something, or maybe the storage account gets to a point where it does not scale properly, I don't know.

You can see the behavior of several orchestrators we have:
![image](https://user-images.githubusercontent.com/12032625/204152975-56ab9c95-4c08-4013-ba71-c209da3fda73.png)

![image](https://user-images.githubusercontent.com/12032625/204152988-9cf76d6b-316a-4ff5-9532-9bb2041129ce.png)

![image](https://user-images.githubusercontent.com/12032625/204153000-2cadddff-1dd5-48c6-8dcf-cce833779312.png)

![image](https://user-images.githubusercontent.com/12032625/204153010-12003dac-c8b4-457d-b79c-01d85c11d163.png)

![image](https://user-images.githubusercontent.com/12032625/204153017-e7e28a36-8ac8-4f5e-8a46-66d505d8577a.png)

![image](https://user-images.githubusercontent.com/12032625/204153038-7c24eb43-4303-4150-9ec0-a222f3fc0be9.png)

**Comment by davidmrdavid** [comment]
Just noting that I'll be taking a look at this, though more eyes are always helpful.
FYI @sebastianburckhardt, as you helped investigate this thread early on

**Comment by lilyjma** [comment]
@vany0114 - apologies for the delayed response. Were you able to figure out the reason in the end? If not, are you still experiencing this problem?

**Comment by vany0114** [comment]
> @vany0114 - apologies for the delayed response. Were you able to figure out the reason in the end? If not, are you still experiencing this problem?

Yeah the issue is still there.

**Comment by davidmrdavid** [comment]
Thank you @lilyjma, for the ping, and apologies @vany0114 for the delay.
Since it's been a few months since the last update here, and our access to telemetry only goes back so far, we will need a newer instance of this issue to investigate.

@vany0114: Is it possible for you to provide us again with a handful of recent orchestrator instanceIDs, paired with timeranges showcasing this incident, that we may use to dive deeper into this? Thank you
