### ISSUE TITLE
Queue triggered durable function comes up with an error and does not create/write to storage account table

### ISSUE THREAD

**Issue by abcdef4422** [Azure/azure-functions-durable-extension#2230]
### Description

Queue triggered durable function comes up with an error and does not create/write to storage account table.

May be a configuration issue as it is the first time we're setting up durable functionality and the same behaviour occurs with http trigger on our instance.

### Expected behavior

Adding new message to the queue causes trigger function to run followed by orchestrator / activity functions.

### Actual behavior

Adding new message to the queue causes trigger function to run, but there is not indication that orchestrator / activity functions ran.

An error comes up in the logs: "General error: The operation 'Queue Create' with id did not complete in '00:02:00'. Hit maximum number (5) of timeouts. Terminating the process to mitigate potential deadlock."

Relevant storage account does not have any tables created. Only the trigger entry appears in AzureWebJobsHostLogscommon / AzureWebJobsHostLogs.

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
None

### App Details

- Microsoft.Azure.WebJobs.Extensions.DurableTask 2.7.2
- Microsoft.Azure.WebJobs.Extensions.Storage 4.0.4
- Functions runtime 2.0
- C#

### Screenshots
![host-json](https://user-images.githubusercontent.com/109607859/179800216-b74aece1-bee6-4a9a-bf58-edd7d66e13f8.png)

Storage account is configured on the functions app:
![image](https://user-images.githubusercontent.com/109607859/179800821-ed53f4ef-5f81-4dcf-8b3f-19c65de6f134.png)

Storage account tables:
![image](https://user-images.githubusercontent.com/109607859/179801860-4030a1b5-13c3-46af-8ebb-4013117eb2ff.png)

Storage account instances:
![image](https://user-images.githubusercontent.com/109607859/179802092-9f207df8-926f-47cb-b9c7-2bfa378639fd.png)

Timeout error:
![image](https://user-images.githubusercontent.com/109607859/179803352-21492c2f-174d-4776-8f72-35d8d358301c.png)

### If deployed to Azure

Deployed to Azure

**Comment by amdeel** [comment]
Hi @abcdef4422 it looks like you're experiencing a storage account deadlock for some reason. Are you sharing this storage account across multiple apps or have very high traffic on your storage account? Make sure storage accounts are not shared by function apps.

**Comment by lilyjma** [comment]
this seem to be resolved. Closing the issue.
