### ISSUE TITLE
Orchestrations performing very inconsistently

### ISSUE THREAD

**Issue by dylanhouston7** [Azure/azure-functions-durable-extension#2236]
### Discussed in https://github.com/Azure/azure-functions-durable-extension/discussions/2231

Hi, I figured I'd open an issue for what I described here. https://github.com/Azure/azure-functions-durable-extension/discussions/2231

That discussion has some other examples of long running orchestrations that I've run into. But I wanted to make this ticket as straightforward as possible, so I am just describing two orchestrations here. 

### Description
> My orchestrations are seeing widely different execution times. The orchestrator functions are running in a deployed Azure environment with an EP1 app service plan. It seems like there are significant delays in when orchestration steps are being started. From what I've seen, there isn't any clear pattern. My code's function execution times seem normal, once orchestration messages get picked up from the storage queue. 

### Expected behavior
> Orchestrations should perform consistently and reliably. I should not see widely different execution times. I was expecting some delays of 0-30 seconds per this thread https://github.com/Azure/azure-functions-durable-extension/issues/606, but I am experiencing performance issues that are very much outside this range. At a minimum, I need these orchestrations to execute in a minute or less.

### Actual behavior
> Some, but not all of my orchestrations are taking a long time to execute. For example, orchestration 1c381b2f3eeb40de8570becd7be02275 took about 20 seconds to execute on 7/27/22. 
On the other hand, orchestration 044df39b7ca7414bae5765820ad06ea2 took almost 7 minutes to execute on 7/21/22. 

### Relevant source code snippets
> N/A

### Known workarounds
> N/A

### App Details

- Microsoft.Azure.Functions.Extensions 1.1.0
- Microsoft.Azure.Webjobs.Extensions.DurableTask 2.7.2
- Azure Functions 4.0
- C# .NET 6

### Screenshots
> If applicable, add screenshots to help explain your problem.

Fast orchestration (~20 seconds)
Orchestration id 1c381b2f3eeb40de8570becd7be02275
![image](https://user-images.githubusercontent.com/20400168/181569423-d6b21d3b-b39a-49a3-97a8-41a7e6652c23.png)

Slow orchestration (~7 minutes)
Orchestration id 044df39b7ca7414bae5765820ad06ea2
![image](https://user-images.githubusercontent.com/20400168/181569610-6fa91bea-24b6-4f18-aa24-31f0678bd3b4.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

Fast orchestration
Orchestration id: 1c381b2f3eeb40de8570becd7be02275
Started 7/27/22 17:26:09:542Z

Slow orchestration
Orchestration id: 044df39b7ca7414bae5765820ad06ea2
Started 7/26/22 17:43:13.360Z

- **Timeframe issue observed**: Have been observing this behavior for months. The orchestrations noted were executed on 7/27/22 and 7/26/22, respectively.
- **Function App name**: Can't share due to not wanting to disclose company info
- **Function name(s)**: Can't share due to not wanting to disclose company info
- **Azure region**:  East US
- **Orchestration instance ID(s)**: 1c381b2f3eeb40de8570becd7be02275 (fast orchestration), 044df39b7ca7414bae5765820ad06ea2 (slow orchestration)
- **Azure storage account name**: Can't share due to not wanting to disclose company info

>My host.json file is as follows:

```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "%TaskHub%",
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 300,
      "useGracefulShutdown": true
    }
  },
  "functionTimeout": "00:00:30",
  "retry": {
    "strategy": "fixedDelay",
    "maxRetryCount": 3,
    "delayInterval": "00:00:30"
  },
  "logging": {
    "logLevel": {
      "default": "Information",
      "Microsoft": "Warning",
      "Azure.Messaging.ServiceBus": "Information",
      "Microsoft.Azure.WebJobs.Extensions.DurableTask": "Warning",
      "DurableTask.AzureStorage": "Warning",
    },
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  }
}
```

I am opening the ticket on behalf of the company that I work at (this is work related code, not personal), and we can open up an Azure ticket if we need to escalate this in order for it to get looked at.

Thanks for taking a look at this and your time.

Dylan

**Comment by davidmrdavid** [comment]
@lilyjma - can we please bring this up during our issue triage?

**Comment by dylanhouston7** [comment]
@davidmrdavid I went into the Azure portal yesterday and noticed something that I had set up incorrectly. When I went through the troubleshooting steps for performance issues in Azure functions, I noticed these warning messages, which stated that my function site names was too long:
![image](https://user-images.githubusercontent.com/20400168/182371166-343ee63a-a825-4dd7-9572-86a2bb7cde2c.png)
![image](https://user-images.githubusercontent.com/20400168/182371194-357f50a5-1fc6-47f5-b048-e68acf23e88e.png)

I've since redeployed the functions apps under new names and I ran through a couple orchestrations just now. I saw the best performance yet, where orchestrations were taking less than a second. I am thinking that the truncation issues were causing performance problems when the program would try to obtain a blob lease to get the orchestrator messages from storage? 

I am working on getting more data and will let you know one way or the other soon.

**Comment by davidmrdavid** [comment]
Hi @dylanhouston7,

Oh wow, that would be an interesting result if you manage to find a correlation between the "HostId Truncation" warning, and your performance. My understanding is that the two issues should be separate, but if your experience is that one controls the other, then that would be a good finding for us.

A few more questions for us to understand your scenario:
(1) Are you using deployment slots?
(2) What major version of the Azure Functions Host are you using? V2, V3, V4?
Thanks!

**Comment by dylanhouston7** [comment]
@davidmrdavid it is certainly interesting. If it help, here is an orchestration id for one of the fast running orchestrations after changing the function site name:
310b72d07da24e94be549e69e07ffe86

![image](https://user-images.githubusercontent.com/20400168/182622757-5cfef0a4-da42-48c2-b8a6-f29b00735134.png)

1) We are using deployment slots, and the slot is turned off after deployment 
2) We are using Azure Functions V4
![image](https://user-images.githubusercontent.com/20400168/182623568-8c480d78-7bb7-4199-9ff2-81b58dd1c487.png)

**Comment by mpaul31** [comment]
We witnessed the same type of performance increase after fixing our app names.

**Comment by dylanhouston7** [comment]
@mpaul31 @davidmrdavid Taking a look at orchestrations today it looks like performance is not an issue. I will continue to update the thread with more data. But it appears that there may be some sort of correlation here.

![image](https://user-images.githubusercontent.com/20400168/182682518-d40f4b3f-8230-4dac-80f0-5d7f89bdc80b.png)

**Comment by mpaul31** [comment]
From what I vaguely remember from looking through a bunch of documentation of git issues is the scale controller does not perform properly when host id collisions are encountered.

**Comment by davidmrdavid** [comment]
I see, I suppose that if another component, such as the scale controller, is acting up due to truncated names / host id collission, then that would explain your performance behavior.

I'll wait for your comment @dylanhouston7, but with @mpaul31's experience backing you up, it would seem like there's indeed a correlation here. If so, it may be worthwhile to call this out, perhaps in our docs.

**Comment by dylanhouston7** [comment]
@davidmrdavid @mpaul31 I've seen more orchestrations go through since last posting and every one of them has been extremely performant. I'm satisfied with the performance. Thanks @mpaul31 for posting about your experience and thanks @davidmrdavid for checking this out.

![image](https://user-images.githubusercontent.com/20400168/182894990-2efb4e96-4de3-475e-a06b-30bf96435d72.png)

@davidmrdavid  Some documentation would definitely be really appreciated. Fwiw I spent a lot of time on this page while trying to debug this: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale

**Comment by davidmrdavid** [comment]
Thanks all for the suggestions.
@lilyjma - can you please take note of the interaction between orchestrator performance and long site names (over 32 chars)? We should update our docs to reflect this, after some discussion and validation with the team. In the meantime, I'll be closing this issue; but I'll create a documentation task in our internal taskboard.
