### ISSUE TITLE
 Get TaskHubName with Durable OrchestrationClient

### ISSUE THREAD

**Issue by yuka1984** [Azure/azure-functions-durable-extension#224]
I think that there are many cases where you want to know TaskHubName in deployment.
And its realization is very easy.

https://github.com/TsuyoshiUshio/azure-functions-durable-extension/commit/c74c1b3211e98f8a22e70a5e8ad70e5bc15825de

**Comment by cgillum** [comment]
I agree this would be useful. @gled4er would you be interested in taking this? I think the commit that @yuka1984 pointed to looks good, although I would make it into a property rather than a method.

**Comment by gled4er** [comment]
Hello @cgillum,

Yes, I am interested in working on this issue.

Thank you for assigning to me!

Kanio

**Comment by cgillum** [comment]
This has been merged. It will be available in the next release. Thank you for the suggestion!
