### ISSUE TITLE
CreateCheckStatusResponse returns wrong status code

### ISSUE THREAD

**Issue by Skleni** [Azure/azure-functions-durable-extension#2240]
### Description
According to the documentation [here](https://github.com/Azure/azure-functions-durable-extension/blob/d9a254ee4cc8f8cfbfb15eebff3c3f4a38b1e7de/src/Worker.Extensions.DurableTask/DurableClientContext.cs#L42)
```csharp
/// <returns>An HTTP 202 response with a Location header and a payload containing instance control URLs.</returns>
```
and [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-features?tabs=csharp#async-operation-tracking)
> The target HTTP trigger returns an HTTP 202 response with a Location header that has the value "statusQueryGetUri".

`CreateCheckStatusResponse` should return a 202 (Accepted) status code.

However, the [`DefaultDurableClientContext`](https://github.com/Azure/azure-functions-durable-extension/blob/d9a254ee4cc8f8cfbfb15eebff3c3f4a38b1e7de/src/Worker.Extensions.DurableTask/DefaultDurableClientContext.cs#L52) creates a response with status code 201 (Created):
```csharp
HttpResponseData response = request.CreateResponse(HttpStatusCode.Created);
```

### Expected behavior
The response created by `CreateCheckStatusResponse` should have a status code of 202 (Accepted).

### Actual behavior
The response has a status code of 201 (Created).

### Known workarounds
You can overwrite the status code manually:
```csharp
response.StatusCode = HttpStatusCode.Accepted;
```

### App Details

- **Microsoft.Azure.Functions.Worker**: 1.8.0
- **Microsoft.Azure.Functions.Worker.Extensions.DurableTask**: 0.4.1-beta
- **Azure Functions runtime version**: 4.x
- **Programming language used**: C#

**Comment by davidmrdavid** [comment]
Hi @Skleni: It seems you're using a really old version of the Durable Functions Extension (0.4.1-beta). Is there a reason for this?
If not, could you please let us know if you still have this issue with the latest extension? Thanks!

**Comment by Skleni** [comment]
I'm using [this package](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.DurableTask/0.4.1-beta) for implementing durable functions in isolated mode, it's the newest there is.

See also https://github.com/microsoft/durabletask-dotnet

**Comment by davidmrdavid** [comment]
Thanks @Skleni for the clarification: I had misread your first post and somehow thought you were using a beta version of the Durable Extension, but instead it seems this version is for the new C-isolated SDK. My apologies, the names are a bit similar :-)

I'll tag @cgillum since he's most familiar with that implementation, though he's out on vacation for a few more days.

**Comment by Skleni** [comment]
No problem :)

**Comment by Skleni** [comment]
Also, it seems that the `returnInternalServerErrorOnFailure` parameter doesn't seem to have any effect. When passing `true`, the a request to the `statusQueryGetUri` returns 200 OK, even if the orchestration failed.

**Comment by jviau** [comment]
This can go either way - both 201 and 202 are applicable responses here, it all depends on what this orchestration is doing. If it is conceptually _creating_ something, like say you are an Azure Resource Provider and this orchestration is responsible for creating a resource, then `201Created` is correct. However, in other cases `202Accepted` is appropriate, to continue with the Azure RP example, if this orchestration is performing some operation on an existing resource, or updating an existing resource, then `202Accepted` is appropriate.

In the end, I think exposing a reasonable default but letting the caller adjust it as appropriate would be a good path.

**Comment by Skleni** [comment]
I'm not sure I agree, @jviau . IMO the status code here refers to the orchestration itself and not what it is doing. And even if it was - while it is running, it shouldn't return `201 Created`, even if that's going to be the end result.

[Azure Logic Apps](https://docs.microsoft.com/en-us/azure/connectors/connectors-native-http#asynchronous-request-response-behavior) have built-in support for asynchronous HTTP operations, but it only works when the result status code is `202 Accepted`.

**Comment by davidmrdavid** [comment]
@jviau: I changed the label for this ticket from "Needs: Attention" to "needs-discussion", as it doesn't seem to me like there's a need for an active investigation at this point. Quick question: has this behavior already been decided or is this still up for discussion? If it's been decided, I think we can close this issue, or at least label it according to its current status. Thanks!

**Comment by 1kevgriff** [comment]
just chiming it.  Moving to isolated Azure Functions broke a couple of our logic apps specifically because of this.  We had to add logic to change the status code before returning a response in order to get everything working again.

**Comment by davidmrdavid** [comment]
@1kevgriff: can you please tell us a bit more about how you're integrating Durable Functions with Logic Apps? Just trying to make sure we're all on the same page about the use case. Thanks!

**Comment by 1kevgriff** [comment]
In our case, we have a durable function that we use to do some calculations and return a response to a logic app that's running.  

However, since the isolated durable functions were returning a 201 instead of the 202, Logic Apps started breaking.  With a 201, Logic Apps assumed it was a regular HTTP call and tried to (incorrectly) pass the JSON response from the durable function to the next task in our logic app.

**Comment by jviau** [comment]
We will need to evaluate this method further. Overall, this is a very subjective area. There is no one single correct answer for how this should behave.

- Logic Apps may perform its LROs one way, but that is not the only way to do it.
    - `202Accepted` is not the only way to do LRO. `201Created` with `Location` header is an appropriate way to do LRO's in Azure.
    - But with that said, this endpoint doesn't correctly do _either_.
- Some users may want to treat the orchestration itself as the entity being tracked, so 201Created makes sense. Others may see the orchestration as an implementation detail and what the orchestration _does_ is what matters, in which it would be a case-by-case basis for if 201Created or 202Accepted is correct.
- The headers this method sets may also not be fitting for everyone. There is a TODO comment regarding reverse proxy headers, but that is also even an open-ended area. Different systems may have different ways for getting the correct base URL (ARM for example uses `Referrer`).
- This endpoint does not follow ARM LRO either.
- We are forcing `application/json` and don't use the object serializer in `WorkerOptions`. This may not be appropriate for everyone.

I could probably continue to find gaps in this helper method which shows it is not a perfect fit for everyone, and probably never will be. In the end, this is just a helper method that I would interpret as having a getting-started focus. If it does not fit your needs, it is trivial to duplicate the logic and customize to your needs.

I don't see it as high priority to change anything here as anyone seriously using this in production may be better off building entirely their own response. Or customizing this response object before returning. For example, [StatusCode is settable ](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Http/HttpResponseData.cs#L26), so if you want `202Accepted`, you can just set that.

**Comment by Skleni** [comment]
@jviau Thanks for your explanation. I understand that there can't be a solution that makes everyone happy, but if you have to choose one behavior, isn't being backwards compatible with in-process functions a good argument? The way it is implemented now, everyone porting an existing solution that relies on the status code (like when using in combination with Logic Apps) will trip over this issue.
