### ISSUE TITLE
if we try to hit same azure durable function more than once, it gets stuck at pending for long time

### ISSUE THREAD

**Issue by saitejamsft** [Azure/azure-functions-durable-extension#2242]
### Description
> We have a Python azure durable function v2 with consumption plan to execute some piece of code which takes more time(nearly 1 to 2 hours). with one request at a time, it behaves properly. but when we try to hit multiple times from different devices, Azure durable function stuck at pending state for long time, and then it goes into running

### Expected behavior
> My expectations were it will scale out and create a new instance to execute new triggers and have the status running

### Actual behavior
> But actually, it gets stuck at Pending state for long, I'm not exactly sure how many parallel triggers it will handle.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: V2
- **Azure Functions runtime version3.11:
- **Programming language used**: Python 3.7

### Deployed to Azure
> Below is the Orchestration instance id, which was in pending state for long time
- **Orchestration instance ID(s)**: -
            1. bceff1a3ee844fee9f3d8ccfb531c675 (after 2's completion, this execution will start)
            2. 55f50641d9bb46179f33da148affac66 (took 3mins)

**Comment by lilyjma** [comment]
@saitejamsft - could you provide timestamp information for the orchestration? And maybe the region as well.

**Comment by saitejamsft** [comment]
Please find the details
Region: Central US,
timestamp: 5th August 2022 4:18PM

**Comment by davidmrdavid** [comment]
@saitejamsft - is that timestamp in UTC? If not, can you please provide us with the UTC timestamp?

**Comment by saitejamsft** [comment]
UTC timestamp: Fri, 05 Aug 2022 10:48:00 GMT

**Comment by saitejamsft** [comment]
Please find the Epoch timestamp: 1659696480000

**Comment by davidmrdavid** [comment]
@saitejamsft: Apologies for the late response, since we missed this update. Is this issue still ongoing? If so, can you please provide me with a recent timestamp and orchestration instanceID? Thanks!
