### ISSUE TITLE
Serialization of DurableOrchestrationStatus instances ignores few properties using built in STJ

### ISSUE THREAD

**Issue by mnsrulz** [Azure/azure-functions-durable-extension#2250]
### Description
Serialization of `DurableOrchestrationStatus` instances ignores few properties using built in STJ.

### Expected behavior
`DurableOrchestrationStatus` instances should serializable using built in STJ

### Actual behavior
The JSON output is rendered as 

```json
{
  "name": "ProcessRefreshCount",
  "instanceId": "54dee4cecd9944dd9f766fc5011ebae3",
  "createdTime": "2022-08-17T16:49:46.6296605Z",
  "lastUpdatedTime": "2022-08-17T16:50:11.7844602Z",
  "input": [
    [
      []
    ],
    [
      []
    ],
    [
      []
    ]
  ],
  "output": [
    [
      []
    ],
    [
      []
    ]
  ],
  "runtimeStatus": 1,
  "customStatus": [],
  "history": null
}
```

### Relevant source code snippets
```csharp
using Microsoft.AspNetCore.Mvc;
using Microsoft.Azure.WebJobs.Extensions.DurableTask;
using Microsoft.Azure.WebJobs.Extensions.DurableTask.ContextImplementations;
using Microsoft.Azure.WebJobs.Extensions.DurableTask.Options;
using Microsoft.Extensions.Azure;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
builder.Services.AddDurableClientFactory();

builder.Services.AddScoped<IDurableOrchestrationClient>((sp) =>
{
    var clientFactory = sp.GetService<IDurableClientFactory>() ?? throw new Exception("Unable to resolve Durable Client Factory");
    var _client = clientFactory.CreateClient(new DurableClientOptions
    {
        ConnectionName = "AzureWebJobsStorage",
        TaskHub = "TaskHub" //configuration["TaskHub"]
    });
    return _client;
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.MapPost("/performCounts", async ([FromBody] RefreshCountRequest request, [FromServices] IDurableOrchestrationClient client) =>
{
    var instanceId = await client.StartNewAsync("ProcessRefreshCount", request);
    return new
    {
        instanceId
    };
}).WithName("Perform Durable Operation");

app.MapGet("/status/{instanceId}", async (string instanceId, [FromServices] IDurableOrchestrationClient client) =>
{
    var status = await client.GetStatusAsync(instanceId);
    return Results.Json(status);  //this is causing problem and returning improper json content
}).WithName("GetStatus");

app.Run();

public class RefreshCountRequest
{
    public int Id { get; set; }
    public string InstanceId { get; set; }
}
```

### Known workarounds
Using NewtonSoft Json can solve the problem.

### App Details

- **Microsoft.Azure.WebJobs.Extensions.DurableTask (v2.7.2)**:
- **ASPNET Minimal API (net 6.0)**:
- **C#**:

**Comment by cgillum** [comment]
I think the problem you're running into is that the `Input` and `Output` properties are `JToken`, which I don't believe is something STJ knows how to natively serialize since it is specific to Newtonsoft.Json.

Take a look at [this StackOverflow post](https://stackoverflow.com/questions/65386083/how-can-i-serialize-a-newtonsoft-jtoken-to-json-using-system-text-json), which provides a workaround for this problem of working with Newtonsoft JSON types in an application that uses System.Text.Json.

**Comment by mnsrulz** [comment]
@cgillum  thanks for sharing the sof post link. I believe for now I have a work around where in I can just use the newtonsoft library since there is a dependency on that anyway. However, is there a future roadmap of supporting STJ over Newtonsoft in this library is what I was looking for.

**Comment by cgillum** [comment]
We don't have any plans to change this for Microsoft.Azure.WebJobs.Extensions.DurableTask.  We do plan to change this for the Durable Functions SDK that runs in .NET Isolated (Microsoft.Azure.Functions.Worker.Extensions.DurableTask), but we haven't yet proposed the design for injecting this newer client into ASP.NET Core Web Apps.

/cc @jviau

**Comment by davidmrdavid** [comment]
For visibility: removing the "needs: attention" label as it seems this doesn't need a response at this moment.

**Comment by mnsrulz** [comment]
> We don't have any plans to change this for Microsoft.Azure.WebJobs.Extensions.DurableTask. We do plan to change this for the Durable Functions SDK that runs in .NET Isolated (Microsoft.Azure.Functions.Worker.Extensions.DurableTask), but we haven't yet proposed the design for injecting this newer client into ASP.NET Core Web Apps.
> 
> /cc @jviau

Any thread going on for the proposal to inject in .net core webapps?

**Comment by jviau** [comment]
@mnsrulz - can you clarify your ask? My understanding is that there are two asks here:

1. Replacing Newtonsoft.Json with System.Test.Json -> this is supported for the new out-of-proc worker. Actually, STJ is the default. Customizing it in Durable Functions out-of-proc is done by replacing [WorkerOptions.Serializer](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Hosting/WorkerOptions.cs#L18)
2. Using the client in AspNetCore -> using the client out of Durable Functions is supported, but in a preview state.
    1. You will need a [sidecar](https://www.nuget.org/packages/Microsoft.DurableTask.Sidecar) running
    2. Then you use [Microsoft.DurableTask.Client.Grpc](https://www.nuget.org/packages/Microsoft.DurableTask.Client.Grpc) in your `AspNetCore` application and connect to the sidecar. [Example here](https://github.com/microsoft/durabletask-dotnet/blob/acebb3a2445cb7a01fe1bbe9eefe7cb5c96265d7/samples/WebAPI/Program.cs#L18)

**Comment by mnsrulz** [comment]
> @mnsrulz - can you clarify your ask? My understanding is that there are two asks here:
> 
>     1. Replacing Newtonsoft.Json with System.Test.Json -> this is supported for the new out-of-proc worker. Actually, STJ is the default. Customizing it in Durable Functions out-of-proc is done by replacing [WorkerOptions.Serializer](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/src/DotNetWorker.Core/Hosting/WorkerOptions.cs#L18)
> 
>     2. Using the client in AspNetCore -> using the client out of Durable Functions is supported, but in a preview state.
>        
>        1. You will need a [sidecar](https://www.nuget.org/packages/Microsoft.DurableTask.Sidecar) running
>        2. Then you use [Microsoft.DurableTask.Client.Grpc](https://www.nuget.org/packages/Microsoft.DurableTask.Client.Grpc) in your `AspNetCore` application and connect to the sidecar. [Example here](https://github.com/microsoft/durabletask-dotnet/blob/acebb3a2445cb7a01fe1bbe9eefe7cb5c96265d7/samples/WebAPI/Program.cs#L18)

I don't think so I am using the out-of-proc worker to host my durable functions. I am fine with it though as the problem is not in the durable function host but rather in the aspnet core web api solution where I am trying to start a durable orchestrator by exposing an endpoint and also exposing an endpoint to get the status of the durable orchestrator. I have listed the example in my original post.

If you are saying to integrate it in AspNetCore application I have to change the solution to connect to sidecar, I guess my question is why I need a sidecar for this? My aspnet core app is hosted in IIS on prem and in app service in azure. This side car implementation sounds little overkill to me.

**Comment by jviau** [comment]
Closing as we have addressed this in dotnet isolated.
