### ISSUE TITLE
Terrible degrade of performance noticed with Durable Functions & Entities

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/azure-functions-durable-extension#2254]
### Description
I am using Azure Durable Functions in production for almost 2 years now.  And the performance of my orchestrations and activity functions has been dramatically degraded.  Orchestrations that used to take a few seconds (just some API calls) are now taking several hours, according to DFM.
I know this can be related to the storage account and purging of it, but I constantly keep getting timeouts, when trying to purge records (even if I just take a from-to timespan of 1 hours or so).

I don't have any idea how to troubleshoot or fix this, and the only result is that I keep getting complaints and support issues from my users.  

### Expected behavior
Execution time of the orchestrations should be acceptable (max 1 min)

### Actual behavior
See screenshot below of activity/workflow durations that take multiple hours.  The code for these workflows contains nothing more than a string calcuation and an external HTTP call.

<img width="890" alt="image" src="https://user-images.githubusercontent.com/3539605/185900403-273d6a8f-01ae-4b74-834c-584acaf73829.png">

A sequence diagram in DFM shows the time that is wasted in the durable functions runtime (queues/table/blob, no idea?)
<img width="589" alt="image" src="https://user-images.githubusercontent.com/3539605/185900695-c4cb30aa-fb30-41ed-9b22-a43c42a3dff5.png">

### Known workarounds
None.

### App Details

- **Durable Functions extension version**: Microsoft.Azure.WebJobs.Extensions.DurableTask : 2.6.1
- **Azure Functions runtime version (1.0 or 2.0)**: ~3
- **Programming language used**: csharp

### Screenshots
See above

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: past weeks, with past days things getting worse
- **Function App name**: `cotacol-hunting-workers`
- **Function name(s)**: `UserHistorySyncWorkflow` (but almost any async orchestration...)
- **Azure region**: west europe
- **Orchestration instance ID(s)**: many, but one example: `00a23a16-feef-5d3d-8000-9067e370fdc9` (UpdateStravaActivityDescriptionWorkflow)
- **Azure storage account name**: `cotacolhuntingfx`

**Comment by cgillum** [comment]
Have you had a chance to check out the Azure Functions Diagnose and Solve Problems tool? https://docs.microsoft.com/en-us/azure/azure-functions/functions-diagnostics. If you search for Durable Functions in the search box, you'' find a detector that can analyze your app and look for common issues that can result in problems like this.

One recommendation you'll see is to upgrade to the latest nuget package. I see you opened another issue, however, where you discovered a regression (please see my response), but often times big delays like this indicate an issue in the lower engine layer (out-of-memory exceptions, etc.). Taking a look at the [Durable Task Framework logs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics?tabs=csharp#durable-task-framework-logging) can also be very helpful in diagnosing these kinds of problems.
