### ISSUE TITLE
Error after nuget package upgrade: Unable to resolve the Azure Storage connection named 'Storage'.  

### ISSUE THREAD

**Issue by SamVanhoutte** [Azure/azure-functions-durable-extension#2255]
### Description
I have upgraded my function app (consumption plan) with a deployment that has changed the following nuget package versions in my functions project (csharp):

**Working before deployment:**
```
<PackageReference Include="DurableFunctionsMonitor.DotNetBackend" Version="5.1.1" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.6.1" />
```

**Failed after deployment:**
```
<PackageReference Include="DurableFunctionsMonitor.DotNetBackend" Version="5.5.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.7.2" />
```

After this, I get the following error in the azure portal: 

> Microsoft.Azure.WebJobs.Extensions.DurableTask: Unable to resolve the Azure Storage connection named 'Storage'.
 
It seems strange to see this breaking change, without finding any documentation about it.  Any insights?
I have the following app setting in the portal: `AzureWebJobsStorage` that has a valid KeyVault reference to the connection string for the storage account.  And I also tried to add `AzureWebJobsDashboard` in the app settings, with the same connection string, to no avail.

### Expected behavior
Upgrading the nuget package should just work, in case of no major version upgrade?

### Actual behavior
Function app becomes in an error state and returns `HTTP 503` in case of HTTP calls.

### Known workarounds
Rolling back to the initial package versions works, but I obviously want to benefit from the enhancements so far.

### App Details

- **Durable Functions extension version**: `2.7.2`
- **Azure Functions runtime version**: ~3
- **Programming language used**: csharp

### Screenshots
<img width="693" alt="image" src="https://user-images.githubusercontent.com/3539605/185922073-46ea1685-b25e-4976-8573-cba6b977628c.png">

### If deployed to Azure

- **Timeframe issue observed**: right now
- **Function App name**: cotacol-hunting-workers-tst
- **Function name(s)**: any , it's on app level
- **Azure region**: west europe
- **Orchestration instance ID(s)**: app level
- **Azure storage account name**: cotacolhuntingfxtst

**Comment by cgillum** [comment]
Possible duplicate of https://github.com/Azure/azure-functions-durable-extension/issues/2232?

**Comment by SamVanhoutte** [comment]
Agreed, seems to be duplicate (didn't find it) of that issue.
