### ISSUE TITLE
Durable.Task 1.2.2-beta3 + Functions 1.0.13 Breaks Simple Function

### ISSUE THREAD

**Issue by aherrick** [Azure/azure-functions-durable-extension#226]
I have a simple Durable Function example posted here:

[https://github.com/aherrick/DurableAF](https://github.com/aherrick/DurableAF)

It's running fine with these bits:

Microsoft.NET.Sdk.Functions => 1.0.8
Microsoft.Azure.WebJobs.Extensions.DurableTask => 1.2.0-beta3

When upgrading to latest it breaks:

Microsoft.NET.Sdk.Functions => 1.0.13
Microsoft.Azure.WebJobs.Extensions.DurableTask => 1.2.2-beta3

![2018-04-04_8-19-13](https://user-images.githubusercontent.com/586671/38307215-082c30f2-37e1-11e8-8f1b-cfc44087b1d1.png)

Is there something else I need to do? This is with both .9 and .10 Functions CLI.

**Comment by cgillum** [comment]
Hey @ahmelsayed do you know what can cause this problem? This project is targeting the full framework, and the durable extension was updated to target [Microsoft.Azure.WebJobs v2.2.0](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/), which I think could be related.
