### ISSUE TITLE
ContinueAsNew does not clear and reset eternal orchestration history

### ISSUE THREAD

**Issue by garytamdas** [Azure/azure-functions-durable-extension#2262]
### Description
> Hi,
We have an eternal orchestration function (queue worker) that is responsible to dequeue msg.  It is hosted inside a communication app that responsible to send sms message and email. We noticed that the performance of the app would deteriorate over time after a several blast of sms message. After some through investigate we have determined that this eternal orchestration function did not clear or reset the instance history even after function "ContinueAsNew" was executed hence severely slow down our app performance to dequeue msg.

Side note:
We notice that the instance history was clearing and resetting fine if we are only raising small amount of event to the worker. However if we are raising anything over 10 event at same time the history would not be cleared and it kept on piling up.

### Expected behavior
>Eternal orchestration function history should be cleared and reset after "ContinueAsNew" is executed.

### Actual behavior
>Eternal orchestration instance history keep on piling up and deteriorate the performance of the eternal orchestration function to stand still

### Relevant source code snippets
```csharp
        // one eternal orchestration instance of this for each "queue" which is the "from" prop of tracking
        [FunctionName(nameof(TrackingQueueWorker))]
        public async Task TrackingQueueWorker(
            [OrchestrationTrigger] IDurableOrchestrationContext context,
            ILogger log
         )
        {
            try
            {
                var input = context.GetInput<TrackingWorkerInput>();

                if(input == null)
                    input = await context.WaitForExternalEvent<TrackingWorkerInput>(nameof(Events.TrackingItemEnqueued));

                var done = await context.CallActivityAsync<bool>(nameof(PollQueue), input);

                var service = _trackers.Services[input.Type];
                var config = service.GetWorkerConfig();

                context.ContinueAsNew(done ? null : input);
            }
            catch(Exception ex)
            {
                log.LogCritical($"TrackingQueueWorker Failed:\n{ex.Message}\n{ex.StackTrace}");
                context.ContinueAsNew(null);
            }
        }
```

### Known workarounds
> When the performance of the eternal orchestration slowed down to almost stand still. We could manually purge the instsance with function "PurgeInstanceHistoryAsync". This workaround is not long term sustainable as our worker need to be live 24/7 in order to process sms communication.

### App Details

- **Durable Functions extension version (e.g. v2.5.1)**:

### Screenshots
Example screenshot show one of the eternal orchestration function has more than 10k history 
> ![image](https://user-images.githubusercontent.com/112533055/187600135-72fe20ab-c02b-4ce7-bc22-d744351046db.png)

**Comment by cgillum** [comment]
Hi @garytamdas. From the screenshot, it looks like this orchestration last ran ~5 months ago. Do you have a more recent reproduction of this using one of the newer extension versions (e.g., v2.8.0)?

It's definitely strange and unexpected to see so many `OrchestratorCompleted` records. One thing I'm wondering about is what happens if you get stuck in a long try/catch loop without hitting any awaits. Is it possible this may have something to do with the problem?

**Comment by garytamdas** [comment]
We are using v2.5.1, should we upgrade to 2.8? I have attached a more recent history here as a CSV file
[CommunicationApiHistory.csv](https://github.com/Azure/azure-functions-durable-extension/files/9464498/CommunicationApiHistory.csv)

**Comment by garytamdas** [comment]
@cgillum There's no exception raise from and by the eternal orchestration. Also the function went through the awaits just fine.

**Comment by garytamdas** [comment]
@cgillum Any update?

**Comment by cgillum** [comment]
@garytamdas Sorry, no updates yet. I've been focused on a separate high-pri issue and haven't had a chance to look into this further.

Would you be able to provide a reproducer app that I can run locally to observe this behavior? That would help speed up the investigation for me.

**Comment by garytamdas** [comment]
@cgillum  Sorry I haven't had a chance to write the reproducer app. Will get back to you asap.
