### ISSUE TITLE
CS8032 Warning for DependencyInjectionAnalyzer in version 2.8.0

### ISSUE THREAD

**Issue by seancolonello** [Azure/azure-functions-durable-extension#2263]
### Description
After upgrading to v2.8.0 I get the following code analysis warning in Visual Studio Community 2022.

`Warning	CS8032	An instance of analyzer Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.DependencyInjectionAnalyzer cannot be created from C:\Users\Sean\.nuget\packages\microsoft.azure.webjobs.extensions.durabletask.analyzers\0.5.0\analyzers\dotnet\cs\Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.dll: Could not load type 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers.DependencyInjectionAnalyzer' from assembly 'Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=014045d636e89289'..`

### App Details

- Durable Functions extension version:  2.8.0
- Azure Functions runtime version:  2.0
- Programming language used: C#

**Comment by amdeel** [comment]
@seancolonello This can sometimes happen but should disappear when closing and re-opening all instances of Visual Studio. Let me know if this doesn't resolve your issue.

**Comment by seancolonello** [comment]
@amdeel, that fixed it. I know I opened/closed the VS instance in question, but must have had other instances open. Thank you, the issue can be closed.

**Comment by amdeel** [comment]
@seancolonello Great, thanks for replying so quicky!
