### ISSUE TITLE
facing this issue while running azure function ->  Function 'ExecutionAPI_StartExecution (Activity)' failed with an error. Reason: System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by contactkanika12** [Azure/azure-functions-durable-extension#2265]
### Description
I am facing this error while executing my functionapp
![image](https://user-images.githubusercontent.com/40831239/188488337-e1383356-06a8-4272-9526-67604f6836e5.png)

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

### Expected behavior
I am using user managed identity to get access to log analytics 

my template is 
{
	"$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
		"sharedResourceGroup": {
			"type": "string"
		},
		"environmentName": {
			"type": "string"
		},
		"shortLocationId": {
			"type": "string"
		},
		"troubleshooterAppBinariesUri": {
			"type": "securestring"
		},
		"blobServiceSuffix": {
			"type": "string",
			"defaultValue": "core.windows.net"
		},
		"storageEndpointSuffix": {
			"type": "string",
			"defaultValue": "core.windows.net"
		}

	},
	"variables": {
		"AppName": "[concat('troubleshooter-', toLower(parameters('environmentName')), '-', parameters('shortLocationId'))]",
		"troubleshooterAppName": "[if(equals(parameters('environmentName'), 'dev'), 'cosmictroubleshooter', variables('AppName'))]",
		"troubleshooterUserAssignedIdentityName": "[concat('troubleshooter-id-', toLower(parameters('environmentName')))]",
		"TroubleShooterAppServicePlanName": "[concat('troubleshooter-asp-', toLower(parameters('environmentName')), '-', parameters('shortLocationId'))]",
		"appInsightsAccountName": "[concat('troubleshooter-appinsights-', toLower(parameters('environmentName')), '-', parameters('shortLocationId'))]",
		"storageAccountName": "[concat('troubleshooter', toLower(parameters('environmentName')))]"
	},
	"resources": [
		{
			"type": "Microsoft.Web/serverfarms",
			"sku": {
				"name": "P1v2",
				"tier": "PremiumV2",
				"size": "P1v2",
				"family": "Pv2",
				"capacity": 1
			},
			"kind": "app",
			"name": "[variables('TroubleShooterAppServicePlanName')]",
			"apiVersion": "2019-08-01",
			"location": "[parameters('shortLocationId')]",
			"properties": {
				"name": "[variables('TroubleShooterAppServicePlanName')]"
			},
			"dependsOn": []
		},
		{
			"type": "Microsoft.Web/sites",
			"apiVersion": "2022-03-01",
			"name": "[variables('troubleshooterAppName')]",
			"location": "East US",
			"kind": "functionapp",
			"identity": {
				"type": "UserAssigned",
				"userAssignedIdentities": {
					"[resourceId(parameters('sharedResourceGroup'), 'Microsoft.ManagedIdentity/userAssignedIdentities', variables('troubleshooterUserAssignedIdentityName'))]": {}
				}
			},
			"dependsOn": [
				"[resourceId('Microsoft.Web/serverfarms', variables('TroubleShooterAppServicePlanName'))]"
			],
			"properties": {
				"enabled": true,
				"name": "[variables('troubleshooterAppName')]",
				"serverFarmId": "[resourceId('Microsoft.Web/serverfarms', variables('TroubleShooterAppServicePlanName'))]",
				"httpsOnly": true,
				"clientAffinityEnabled": false,
				"siteConfig": {
					"appSettings": [
						{
							"name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
							"value": "[reference(resourceId('Microsoft.Insights/components', variables('appInsightsAccountName')),'2015-05-01').ConnectionString]"
						},
						{
							"name": "FUNCTIONS_EXTENSION_VERSION",
							"value": "~3"
						},
						{
							"name": "AZURE_CLIENT_ID",
							"value": "[reference(resourceId(parameters('sharedResourceGroup'), 'Microsoft.ManagedIdentity/userAssignedIdentities', variables('troubleshooterUserAssignedIdentityName')), '2018-11-30').clientId]"
						},
						{
							"name": "FUNCTIONS_WORKER_RUNTIME",
							"value": "dotnet"
						},
						{
							"name": "AzureWebJobsStorage",
							"value": "[concat('DefaultEndpointsProtocol=https;AccountName=', variables('storageAccountName'), ';AccountKey=', listKeys(resourceId(parameters('sharedResourceGroup'), 'Microsoft.Storage/storageAccounts', variables('storageAccountName')), providers('Microsoft.Storage', 'storageAccounts').apiVersions[0]).keys[0].value, ';EndpointSuffix=', parameters('storageEndpointSuffix'))]"
						},
						{
							"name": "WEBSITE_RUN_FROM_PACKAGE",
							"value": "1"
						},
						{
							"name": "IsDevelopment",
							"value": "false"
						}
					],
					"alwaysOn": true,
					"netFrameworkVersion": "v4.0",
					"phpVersion": "",
					"pythonVersion": "",
					"nodeVersion": "",
					"linuxFxVersion": "",
					"requestTracingEnabled": false,
					"remoteDebuggingEnabled": false,
					"httpLoggingEnabled": false,
					"detailedErrorLoggingEnabled": false,
					"use32BitWorkerProcess": false,
					"webSocketsEnabled": false,
					"ftpsState": "Disabled",
					"minTlsVersion": "1.2"
				}
			},
			"resources": [
				{
					"apiVersion": "2018-11-01",
					"name": "ZipDeploy",
					"type": "extensions",
					"dependsOn": [
						"[resourceId('Microsoft.Web/sites', variables('troubleshooterAppName'))]"
					],
					"properties": {
						"packageUri": "[parameters('troubleshooterAppBinariesUri')]"
					}
				}
			]
		}
	]
}

PLease let me know what am I missing
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
- **Azure Functions runtime version (1.0 or 2.0)**:
- **Programming language used**:

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment]
From the screenshot, it looks like there is an error in the library you are using (Microsoft.Office.Substrate.Cosmic...). I suggest you follow up with the owners of that library and provide them with a code snippet that demonstrates how you were able to see this error. It's very likely an issue with how you wrote your function code.
