### ISSUE TITLE
The function runtime is unable to start. Microsoft.Azure.WebJobs.Extensions.DurableTask: Method not found: 'Microsoft.Azure.WebJobs.Host.TraceWriter Microsoft.Azure.WebJobs.Host.Config.ExtensionConfigContext.get_Trace()'

### ISSUE THREAD

**Issue by Ryanman** [Azure/azure-functions-durable-extension#227]
My collection of web functions using the durable extension abruptly stopped yesterday. The error is in the title: 
    The function runtime is unable to start. Microsoft.Azure.WebJobs.Extensions.DurableTask: Method not found: 'Microsoft.Azure.WebJobs.Host.TraceWriter Microsoft.Azure.WebJobs.Host.Config.ExtensionConfigContext.get_Trace()'
![image](https://user-images.githubusercontent.com/1376624/38319090-f68f019e-37fe-11e8-8658-876698af436b.png)

I have 2 serious issues with this:

- I recieved no notification from application insights about my functions not running for a whole day, only a "smart alert" about a degredation in trace severity just before all my functions refused to start. I have alerts for when an exception occurs in each function. I'd like to know how to create an alert for exceptions like this that are deep enough to (presumably) be outside the scope of a function exception.
- Restarting the app functions, or stopping and then starting does nothing.
- There has been no deployment or changes at all on our side, this is a sudden occurance.

**Comment by cgillum** [comment]
Apologies for the bad experience. It looks like you're running into this issue: https://github.com/Azure/azure-functions-durable-extension/issues/210. You will need to update to the latest nuget package to get things working again.

Unfortunately I'm not familiar with how to set up alerts in Application Insights. I suggest opening an issue here https://github.com/Azure/azure-functions/issues to get the attention of the core functions team. There is probably some improvements that can be made to make it easier to detect issues like this where the functions host won't start for some reason.

**Comment by Ryanman** [comment]
Thanks for the update Chris, bummer that it happened. I'll open a ticket with them re: app insights.

**Comment by scholtes** [comment]
`Method not found: 'Microsoft.Azure.WebJobs.Host.TraceWriter Microsoft.Azure.WebJobs.Host.Config.ExtensionConfigContext.get_Trace()`

I think there might be a deeper issue not related to this durable functions extension (i.e., per #210).  We have this same problem trying to test v2.x Azure functions locally (without durable functions extension) with the 2.0.1-beta.26 runtime.

**Comment by Ryanman** [comment]
@scholtes That's exactly it I think - the underlying runtime changed the location of the TraceWriter. Any other extensions you use - including perhaps the local SDK or configurations (for instance) will have that problem. Update the NPM package to beta 28 and you may be good.
