### ISSUE TITLE
Overloading function app puts app in bad state

### ISSUE THREAD

**Issue by ethanroday** [Azure/azure-functions-durable-extension#228]
Yesterday, I simluated a load test for a function app where one client sent ~100 requests in 5 seconds. The load seems to have overwhelmed the app, and I started getting 502 responses with the following (somewhat unhelpful) error message:

    The specified CGI application encountered an error and the server terminated the process.

The error has been documented in a [number](https://blogs.msdn.microsoft.com/waws/2016/12/11/asp-net-core-slow-perf-issues-on-azure-websites/) of [other](https://github.com/aspnet/KestrelHttpServer/issues/939) [places](https://stackoverflow.com/questions/33645242/the-specified-cgi-application-encountered-an-error-and-the-server-terminated-the) but, unlike in those cases, restarting the app does not make the problem go away, and I have no `web.config` to modify.

Initially, looking at Application Insights about five minutes after the errors began, there were no exceptions or failed requests being reported. However, when I looked again this morning, I can see that exceptions were indeed logged in the form of timeout errors with the following message: `Timeout expired while waiting for the new instance to start. This can happen if the task hub is overloaded or if the orchestration host failed to process the start message. Please check the orchestration logs to see whether an internal failure may have occurred.` The orchestration logs do not show any errors, though, and there are no error messages or traces in the application logs themselves (i.e. anything in the `LogFiles` directory).

Beyond debugging difficulties, my app now seems to be in a bad state. All requests are resulting in 500 errors with no messages (but with the corresponding timeout exceptions in Application Insights), even for entirely new requests that would have no checkpoint history. The function app is clearly running, but I can't make any successful requests, even in the portal. The app service for the function app also shows a large (and increasing?) memory usage for about 12 hours after the load test, despite the fact that no new requests were made in that time (approximate time of the load test is circled in red):

![image](https://user-images.githubusercontent.com/896670/38318534-65a07e8e-37e4-11e8-8aef-c70892a56c50.png)

How can I mitigate this and/or avoid this in the future?

**EDIT:**

As additional information, the data in Azure Storage Explorer seems to indicate that the orchestration functions associated with this morning's requests (the ones returning 500 errors) actually executed successfully, and output the intended results, despite Application Insights showing timeout errors for those same orchestration functions. Directly querying the functions using the HTTP API also shows that they completed successfully with the intended output.

Azure Storage Explorer:
![image](https://user-images.githubusercontent.com/896670/38321749-4dca0ec0-37ed-11e8-802e-d6ef420fe644.png)

Application Insights:
![image](https://user-images.githubusercontent.com/896670/38321885-acb850cc-37ed-11e8-887c-e26dd6a78bcb.png)

**Comment by cgillum** [comment]
Interesting. Do you still have an app in this busted, high-memory state? I suspect the core functions team would be interested in capturing a crash dump to figure out why it's in a bad state.

The timeout message you highlighted means that we successfully enqueued the message to start the orchestration, but we didn't see it actually start in the 10 seconds or so that we wait before returning from the StartNewAsync call. It is expected that it will start eventually once the CPU returns to healthier levels. This is a frequent problem that people encountered in high load scenarios, so we created a workaround in the most recent release to avoid it. 

Are you running the latest version of the [Microsoft.Azure.WebJobs.Extensions.DurableTask](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/) extension? If so, take a look at the [release notes](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.2.2-beta3), which describe how to disable this timeout (relevant details copied here).

> For anyone impacted by the StartNewAsync timeout issue, you can add the following JSON configuration to your host.json file to work around the issue.
```json
{
  "durableTask": {
    "disableStartInstancePolling": true
  }
}
```
> The behavior you will observe is that DurableOrchestrationClient.StartNewAsync will return quickly, but the started instance may not be visible for several seconds. An improved fix is scheduled for the next release and the above configuration will no longer have any effect.

The next release will remove the need for this workaround and will also provide clear indications when the instance is in a "pending" state (i.e. scheduled but not yet started). Let me know if this is helpful.

**Comment by ethanroday** [comment]
I do still have the bad state. Happy to provide a dump.

Thanks for the clarifications and the workaround. More generally, is it expected that a function app end up in this kind of state after just 100 requests?

**Comment by cgillum** [comment]
I can't think of any reason why 100 requests in 5 seconds would put a function app into a bad state. Based on the error message, it seems like something caused the `dotnet.exe` process to crash. Do you specifically require Functions v2 for your app or are you able to try running functions v1 (which is more stable in general - the durable extension supports both)?

Another thing you can try which could help is to create an app setting named **WEBSITE_HTTPSCALEV2_ENABLED** and set it to **1**. That will enable our recently improved HTTP scaling algorithm and should help reduce load on your function app (note that this will be the default in the coming weeks).

For the process in a bad state, would you mind opening an issue and posting a link to the crash dump here? https://github.com/Azure/azure-functions-host/issues. Someone from the functions runtime team should be able to take a look. If you can also mention a timeframe, your app's region, and either your function app name or [some indicator the team can use to search for it](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately), that would help speed up the investigation.

**Comment by ethanroday** [comment]
Can you be more specific about what you mean by crash dump? Do you just mean the traces from the exceptions?

**Comment by cgillum** [comment]
No, I was referring to an actual memory dump. But thinking about this more, it would be safer if a member of the Functions/App Service team collected this for you to avoid publicly exposing connection strings, etc, so ignore that part. The relevant information is the increasing memory usage and the failure to send any requests, including from the portal.
