### ISSUE TITLE
All instances should return *all* instances

### ISSUE THREAD

**Issue by gregorybleiker** [Azure/azure-functions-durable-extension#2284]
### Description
Running a rest call like `runtime/webhooks/durableTask/instances?code=<code>&top=50&runtimeStatus=Running`
will return an empty list `[]`, however if you find out an instanceid by other means (e.g. the vscode extension), then `/runtime/webhooks/durableTask/instances/<instanceid>?code=<code>&top=20&runtimeStatus=Running` does return a task (with status `running`)

### Expected behavior
Either a very good explanation in the docs why this is happing or preferably *return all instances*

### Actual behavior
see above

### App Details

Azure cloud version ~4, 32 bit

**Comment by amdeel** [comment]
@gregorybleiker That should return all of the running orchestrators. The empty list should only be returned when there are no results.

Are you making the call to the app with the orchestrators you're monitoring? If not, you'll need to add taskHub and connectionName. Let me know if this doesn't resolve your issue.

**Comment by gregorybleiker** [comment]
@amdeel yes, I have only one fn app running orchestrator and tasks. Also, in the vscode extension the tasks do show up. I have the suspicion it has something to do with the `top` parameter

**Comment by amdeel** [comment]
@gregorybleiker Can you provide more information on this and a way to reproduce this? This API works fine for me.

**Comment by gregorybleiker** [comment]
I think this was related to the fact that we deployed a new version of the app and old instances were still hanging around in the workitem queue. I found this very frustrating, as the activities were clearly still being executed but did not show up in the API. Ideally, this would not be possible to happen at all and so it is not an issue with the API.
