### ISSUE TITLE
.NET Framework 4.8 does not compile with latest extension version

### ISSUE THREAD

**Issue by michaelelleby** [Azure/azure-functions-durable-extension#2291]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

Using Durable Functions as WebJobs with .NET Framework 4.8 does not compile, giving the error `'IWebJobsBuilder' does not contain a definition for 'AddDurableTask' and no accessible extension method 'AddDurableTask' accepting a first argument of type 'IWebJobsBuilder' could be found (are you missing a using directive or an assembly reference?)`
If I downgrade the project to .NET Framework 4.6.1 it compiles succesfully.

This is using Microsoft.Azure.WebJobs NuGet package version `3.0.33`

### Expected behavior
> A clear and concise description of what you expected to happen.
Project should compile with .NET Framework 4.8

### Actual behavior
> A clear and concise description of what actually happened.
Compiler error `'IWebJobsBuilder' does not contain a definition for 'AddDurableTask' and no accessible extension method 'AddDurableTask' accepting a first argument of type 'IWebJobsBuilder' could be found (are you missing a using directive or an assembly reference?)` when targeting .NET Framework 4.8

### Relevant source code snippets
```csharp
var hostBuilder = new HostBuilder()
	.ConfigureWebJobs(config =>
	{
		config.AddDurableTask(options => { options.HubName = "MyTaskHub"; });
	})
```

https://github.com/michaelelleby/DurableTaskBugDemo is a repository demonstrating the issue, and the branch `framework-v461` demonstrates that the same code can compile when targeting .NET Framework 4.6.1
However since 4.6.1 was declared end-of-life on April 26th this year, using that is not an option.

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.8.1
- **Azure Functions runtime version (1.0 or 2.0)**: N/A
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by lilyjma** [comment]
@michaelelleby - apologies for the delayed response. Are you still experiencing this issue?

**Comment by bachuv** [comment]
It seems like #2292 (linked issue) was closed as it was an issue with the storage account and it looks like this issue was also resolved by changing the storage resource. @michaelelleby, let us know if this issue was also resolved by changing the storage resource. If not, we can investigate further. Thanks!
