### ISSUE TITLE
Durable Functions are not scaling as expected or desired

### ISSUE THREAD

**Issue by Tyler-V** [Azure/azure-functions-durable-extension#2293]
### Description
I am building a system that processes large txt files in a pipe-delimited format of 15+data points and can contain up to 500k individual lines

I have reviewed [Bindings for Durable Functions](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings?tabs=csharp%2C2x-durable-functions#host-json) and am trying to set appropriate settings to ensure I am not bottlenecked on CPU/memory for the functions

What I am noticing is that regardless of the settings I have tried in host.json, I am seeing fewer instances than I would anticipate where it should be scaled out (monitoring Application Insights | Live metrics | Servers)

The system has 1 Orchestrator and 3 Sub-Orchestrators, each orchestrator calls 1-3 activities that involve a fair amount of business logic, EF Core querying, etc. <500 lines dealing in large data structures (Maps, Sets, sometimes Lists) where we are batching Activities in groups of 5000 records to use fan-in / fan-out strategy

For example, one 500k file would result in one of the sub-orchestrators processing a list of 500,000 objects in 100 activities handling 5000 entities at a time

We are using Azure Functions Premium with an Elastic Plan of Production EP3 (840 ACU / 14 GB memory)

For these tests, we have set our serverless databases to 10 vCPU and observed <30% utilization on all domains so we know it is not being bottlenecked by the Database

### Expected behavior

I would expect the Azure Functions Scale Controller to start up a new instance once one of the servers reaches ~100% CPU and/or memory utilization

I would like to see what the best settings are to take advantage of fan-in / fan-out where I believe if scaling correctly it should make little difference in running a 50k line file vs a 500k line file

### Actual behavior

In most cases, I am observing 1-4 servers instances at most where the first 1 or 2 are in well excess of 300-400% while the remaining operate under light (1-5% CPU) and 8-10 GB memory

![image](https://user-images.githubusercontent.com/3893234/196743626-79830a18-260e-42d8-bd00-2ccfaf0391a1.png)

### App Details

We used the default host.json settings previous to this run and then tried the following settings and noticed no change in scale-out
```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true
      }
    }
  },
  "functionTimeout": "00:10:00",
  "extensions": {
    "durableTask": {
      "hubName": "DurableFunctionsHub",
      "storageProvider": {
        "connectionStringName": "AzureWebJobsStorage",
        "controlQueueBatchSize": 32,
        "controlQueueBufferThreshold": 128,
        "controlQueueVisibilityTimeout": "00:05:00",
        "maxQueuePollingInterval": "00:00:30",
        "partitionCount": 4,
        "trackingStoreConnectionStringName": "TrackingStorage",
        "trackingStoreNamePrefix": "DurableTask",
        "useLegacyPartitionManagement": true,
        "workItemQueueVisibilityTimeout": "00:05:00"
      },
      "tracing": {
        "traceInputsAndOutputs": false,
        "traceReplayEvents": false
      },
      "maxConcurrentActivityFunctions": 5,
      "maxConcurrentOrchestratorFunctions": 4,
      "extendedSessionsEnabled": false,
      "extendedSessionIdleTimeoutInSeconds": 30,
      "useAppLease": true,
      "useGracefulShutdown": false,
      "maxEntityOperationBatchSize": 50
    }
  }
}
```

Functions.csproj
```
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <LangVersion>10.0</LangVersion>
    <UserSecretsId>58a7abc5-421b-4c2f-aad4-0d26de5fd2c5</UserSecretsId>
    <PublishReadyToRun>true</PublishReadyToRun>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="Azure.Identity" Version="1.7.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.4.0" />
    <PackageReference Include="Azure.Storage.Common" Version="12.12.0" />
    <PackageReference Include="Azure.Storage.Files.Shares" Version="12.11.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.8.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
    <PackageReference Include="System.Text.Encodings.Web" Version="6.0.0" />
    <PackageReference Include="System.Text.Json" Version="6.0.6" />
  </ItemGroup>
```

### Screenshots
![image](https://user-images.githubusercontent.com/3893234/196754935-402674c1-1900-4fac-82ab-6a83c2f4f8f4.png)
![image](https://user-images.githubusercontent.com/3893234/196755052-007d8ca9-d262-4084-877f-caa1c19618f6.png)
![image](https://user-images.githubusercontent.com/3893234/196755491-312e243d-98ee-4a38-a52e-9a4b038acbf3.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: 10/19/2022, we ran several tests and made observations
- **Function App name**: dev-01
- **Azure region**: East US
- **Orchestration instance ID(s)**: 
239ceb24e1be48ebacc96cf30cb99252
3905d8a63091416f96cbba5785443fa1:82
3ea37442250f4de980d377c699e62dd2:1
d4de147b6102467498e961a52b675856

Referenced #1556

**Comment by olitomlinson** [comment]
> For example, one 500k file would result in one of the sub-orchestrators processing a list of 500,000 objects in 100 activities handling 5000 entities at a time

Not an expert but this sounds like a choke point in the design. Ideally, you don’t want a single sub-orc handling all 500k, as this is not going to distribute over all the available partitions. 

If you can split the 500k into 100 different sub orchestrations (with each responsible for 500 entities) then that should distribute more uniformly over the available partitions.

there are 4 partitions by default. If you’re looking for max throughput I would certainly crank up the partition count value to 12 (maximum)

General rule of thumb : start with the default host.json settings, then tweak the partition count, only then go into the more granular settings. Be scientific about what you change, I.e. don’t change more than one variable at once etc 

If you *really* want to add another layer of detail to your diagnosis - leverage custom events in  AppInsights and instrument your code with event markers before and after calls to the ‘CallActivity’ and also inside the Activity itself, at the start and end. This will give you a bunch of data that you can graph in AppInsights and spot any weird trends. Example I did here many moons ago when I was trying to track down a nasty performance degradation https://github.com/Azure/azure-functions-durable-extension/issues/779#issuecomment-498715624

**Comment by olitomlinson** [comment]
@Tyler-V 

It definitely helps to spread your work across many sub-orchestrations, so that they have the best chance of being allocated to all of the available partitions. This specifically helps marshal results from Activities back to the Orchestration concurrently, in the event that the orchestration has to do more work once it has received the result back from the Activity.

Dialling up the partitions to 12 (the max) will definitely help if orchestration throughput is the current bottleneck. As an FYI, just because you specify 12 (or any number of partitions for that matter) doesn't mean you're going to get 12 compute nodes straight away. The scale controller will make decisions based on how many nodes actually are assigned at any point in time. For example, if the scale controller sees that Activity results are backing-up and the `control-queue` length is growing over time, then it will assign more nodes and the partitions will re-balance over the new amount of available nodes, thereby increasing throughput. If you want to force 12 nodes, you can absolutely do that by setting the `plan scale out minimum instances` to 12. I would actually recommend doing this just to see what your 'best case' throughput scenario is. If you see no throughput increase when setting partitions to 12 and minimum instances to 12, then this implies that you have an Activity bottleneck.

It's also worth baring in mind that any node is capable of executing Orchestration logic AND Activity Logic. Which means if you do scale up to 12 nodes, then you're actually allocating more throughput for your Activity logic to consume too.

---

Do you have many 500k batches being executed in parallel? or can you guarantee there will be only ever one batch executing at a time?

**Comment by Tyler-V** [comment]
@olitomlinson it looks like the partition count maximum is 16 and I started there trying to change that value to see if it results in better fan-in / fan-out,

So here is something interesting, I'm unable to change the partition count even after recreating the taskhub

I stopped the azure functions... deleted the dev01-applease, dev01-leases, all the existing queues

![image](https://user-images.githubusercontent.com/3893234/197871138-8e888627-2562-40e2-b75e-8408f1c46db9.png)

After I start the azure functions again, it creates a task hub again with a partition count of the default 4

![image](https://user-images.githubusercontent.com/3893234/197870810-49b8cfaa-397a-4733-966e-3db7d9bae966.png)

When I look at the dev01-leases container and look at the taskhub.json with the files last modified date of the current time

I can see that it is showing a partition count of 4 for some reason,

![image](https://user-images.githubusercontent.com/3893234/197871952-8b34aae1-9a65-4aa8-be1f-8efdb0b943a5.png)

However looking at the wwwroot of kudu I can see the proper host.json is deployed showing a partition count of 16

![image](https://user-images.githubusercontent.com/3893234/197872132-aae90a4f-df51-43a4-a519-406f36d8f173.png)

**Comment by Tyler-V** [comment]
@olitomlinson starting with trying to change the partition count from the default of 4 to 12 or (max 16) I am running into issues,

I can see that even after stopping the functions and deleting the task hub in the storage account (removing the containers azure-webjobs-hosts, azure-webjobs-secrets, removing all the queues, and removing the tables of history and instances) when I  start the functions again, the resources are recreated and it is only ever creating 4 partitions

![image](https://user-images.githubusercontent.com/3893234/197879551-4b2a13c6-7ec7-43bf-9d26-648febaabe5f.png)

![image](https://user-images.githubusercontent.com/3893234/197880036-94b65f63-a218-43dd-a16d-6015122e45dc.png)

On kudu I can see what is deployed in the wwwroot and it seems like `partitionCount: 16` is not being applied, it always defaults to 4 any ideas?

**Comment by Tyler-V** [comment]
Big oof - I can confirm my `host.json` is deployed but is being ignored because of how we are configuring the application and clearing builder sources on Startup to map user secrets / key vault / etc. based on different environments

Going to continue working on this and see what optimizations will be best now that host.json settings will actually apply!

**Comment by davidmrdavid** [comment]
Thanks @olitomlinson for helping drive this discussion ❤️ .
@Tyler-V: please let us know how it goes now that it seems your `host.json` is actually being applied. Thanks all

**Comment by Tyler-V** [comment]
@davidmrdavid @olitomlinson we have noticed some improvements with the host.json now taking affect (whoops) and changing the behavior of the scale controller by way of the max activity / orchestrations

```
      "maxConcurrentActivityFunctions": 20,
      "maxConcurrentOrchestratorFunctions": 1,

```

We have set these based on the combination of our batching size per activity (now 500) and comparing the live CPU / Memory of each instance at runtime

Here is our current host.json, just curious if you have any other insight / recommendations before I close out this issue - thanks!

```
  "extensions": {
    "durableTask": {
      "hubName": "xxx",
      "storageProvider": {
        "connectionStringName": "AzureWebJobsStorage",
        "controlQueueBatchSize": 32,
        "controlQueueBufferThreshold": 256,
        "controlQueueVisibilityTimeout": "00:05:00",
        "maxQueuePollingInterval": "00:00:30",
        "partitionCount": 16,
        "trackingStoreConnectionStringName": "AzureWebJobsStorage",
        "trackingStoreNamePrefix": "xxx",
        "useLegacyPartitionManagement": false,
        "workItemQueueVisibilityTimeout": "00:05:00"
      },
      "tracing": {
        "traceInputsAndOutputs": false,
        "traceReplayEvents": false
      },
      "maxConcurrentActivityFunctions": 20,
      "maxConcurrentOrchestratorFunctions": 1,
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 30,
      "useAppLease": true,
      "useGracefulShutdown": false,
      "maxEntityOperationBatchSize": 50
    }
  }
```

**Comment by davidmrdavid** [comment]
Good to hear your changes are now taking effect :-)

I don't have any suggestions at this time, though I'm personally not an expert on this side of application config. My experience with performance-tuning is that finding the right parameters is ultimately very workload-driven, so I would encourage you to continue to fine tune these over time. Other than that, I can't spot anything that seems necessarily "off" from your config.

**Comment by lilyjma** [comment]
@Tyler-V - I'm closing this issue was your question seems to be answered. Please reopen if needed. Thanks!
