### ISSUE TITLE
Multiple instances of an orchestrated function

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-functions-durable-extension#23]
I've got a durable function executed from the portal. Whenever I make a change to the function and save it or execute it manually using a workaround described [here](#10), multiple instances of the function get executed. 

![image](https://user-images.githubusercontent.com/1309622/28531921-7db3ecb0-7055-11e7-84ed-2cb7a658711d.png)

1. What is a way to see and drop those function instances?
1. Orchestrator should be a single-instance, is there a way to specify an instance ID?

**Comment by cgillum** [comment]
We don't yet have a simple way to view all instances of an orchestrator function. One option you have is to look at the logs and collect the distinct instance IDs (we trace this information automatically). The other method is to use the data in table storage (though in general we recommend only using this for debugging). One you have the IDs of the instances you want to drop, you can terminate them either using an API call from another function or using an HTTP API call.

Documentation on instance control can be found here: https://azure.github.io/azure-functions-durable-extension/articles/topics/instance-management.html#terminating-instances.  We don't yet have complete documentation for the HTTP APIs, but today you can terminate instances by sending an HTTP `POST` request to the following endpoint:
```
http://{host}/admin/extensions/DurableTaskConfiguration/instances/{instanceID}/terminate?reason={text}
```

...where `{host}` is the domain name of your function app, {instanceID} is the ID of the instance you want to terminate, and `{text}` is optional reason metadata for why the instance was terminated (this data shows up in the output the next time someone queries for the status of the terminated instance).

Regarding your second question, you can specify an instance ID using an overload of the `StartNewAsync` API. You can find the API docs [here](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationClient.html#Microsoft_Azure_WebJobs_DurableOrchestrationClient_StartNewAsync_System_String_System_String_System_Object_).

**Comment by cgillum** [comment]
Closing for now. Let me know if you have further questions about any of this.

**Comment by daronyondem** [comment]
I'm having the same issue here. I don't want to move into the singleton implementation because of the warning in the documentation.

![image](https://user-images.githubusercontent.com/2984187/34364267-259f4dd4-ea95-11e7-96fa-d6d0a31c68e1.png)

I have a timertrigger kicking a new instance of the orchestrator with a random instanceID on every execution. I see a random number of orchestrators (10 to 17 instances) getting started on the portal. When I look at the timertrigger function itself, the one that starts a new instance, everything is fine. It only runs once in every interval. 

At the end of the orchestrator, I have a single function call just after waiting for a fan-out to finish. If I had multiple orchestrator instances running at the same time the final function should have run multiple times as well. It does not. I added some additional instrumentation code and it looks like only the last executed instance of the orchestrator is actually making the whole way to the end. Others look succeeded in the portal but they do not execute the ActivityCalls in them. 

It feels like I'm missing something in my understanding of an orchestrators lifecycle. What happens when an orchestrators function ends? (the one with `OrchestrationTrigger`)

**Comment by cgillum** [comment]
It sounds like you're observing the replay behavior and confusing it with multiple instances. It's really just one instance which gets replayed to recover state whenever it receives a batch of messages.

If you haven't already, take a read of this documentation topic: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-checkpointing-and-replay

The most relevant point is here:

> Every time the function resumes from an `await`, the Durable Task Framework reruns the orchestrator function from scratch. On each rerun it consults the execution history to determine whether the current async operation has taken place. If the operation took place, the framework replays the output of that operation immediately and moves on to the next `await`. This process continues until the entire history has been replayed, at which point all the local variables in the orchestrator function are restored to their previous values.

Activity functions are called only once, regardless of this replay behavior. It sounds like you are indeed observing this.

Other useful information about this replay behavior can be found in the [Diagnostics](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-diagnostics) topic, including notes on how you can filter out the replays so you see only the logical execution.

**Comment by daronyondem** [comment]
It makes sense. Thanks for the help. I was able to get the right numbers from AppInsights with the custom AIQL.

So, this means the total execution time (duration) of the orchestrator is actually the sum of all the records listed below. Is my understanding correct?

![image](https://user-images.githubusercontent.com/2984187/34373975-7643d5f2-eaef-11e7-8c2e-31454a5ab749.png)

In this case, this is an orchestrator being executed every 5 minutes.

**Comment by cgillum** [comment]
Yes, that's correct. Replay execution is metered the same way as normal function execution. As you can see these numbers are often very small since the orchestrator shouldn't be doing any I/O or CPU-intensive work, so I don't expect it will have much impact on a consumption plan bill.

**Comment by kashimiz** [comment]
Hi @raghupalaparthygithub,

Currently, orchestrating functions across multiple function apps (hosts) is not supported.

One possible workaround at present:

1. Orchestrator in Function app 1 (FA 1) calls an activity function in FA 1.

2. Activity function in FA 1 calls an HTTP-triggered function in FA 2 and receives its result.

3. Activity function in FA 1 returns the result of the HTTP-triggered function in FA 2.

4. Orchestrator in FA 1 receives the return value from the activity function and proceeds.

**Comment by mslot** [comment]
> Hi @raghupalaparthygithub,
> 
> Currently, orchestrating functions across multiple function apps (hosts) is not supported.
> 
> One possible workaround at present:
> 
> 1. Orchestrator in Function app 1 (FA 1) calls an activity function in FA 1.
> 2. Activity function in FA 1 calls an HTTP-triggered function in FA 2 and receives its result.
> 3. Activity function in FA 1 returns the result of the HTTP-triggered function in FA 2.
> 4. Orchestrator in FA 1 receives the return value from the activity function and proceeds.

Is this still the case? I have looked throughout the docs, and can't find anything to validate this is true (or isn't true).
