### ISSUE TITLE
App Insights distributed tracing telemetry missing for Durable Functions

### ISSUE THREAD

**Issue by miriamflorestr** [Azure/azure-functions-durable-extension#2304]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.
If Distributed Tracing is enabled for durable functions we experience the following issues:
1. Custom role name is not set.
2. There is no way to add custom properties to telemetry request which belongs to durable activity functions.
3. Exceptions which occurred in orchestration main thread does not have role name and has wrong operation id, and wrong values for properties like role instance, user agent, etc.

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

### Expected behavior
> A clear and concise description of what you expected to happen.
1. Custom role name must be set using telemetry initializer.
2. Activity.Current.AddTags() should add custom dimensions inside activity function request telemetry.
3. Exception telemetry from orchestration thread should have the same operation id, and role name as other telemetry.

### Actual behavior
> A clear and concise description of what actually happened.
See Description

### Relevant source code snippets
Sample code can be found here: https://github.com/Stastrstr/distributedtracingissues

### Known workarounds
> Provide a description of any known workarounds you used.
For custom role name we search for the role name assigned by default.
Added custom events for issue where AddTags() does not add custom tags.
No workaround for the exceptions. There is no clear way to understand what exception belongs to which application.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
 <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.7.2" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
- **Azure Functions runtime version (4.0)**:
    <TargetFramework>net6.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
- **Programming language used**: c# .net 6.0

### Screenshots
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/78872415/199535304-2bf6c939-c889-4106-bb15-a8506fd22438.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment]
@bachuv and @jviau, would the upcoming distributed tracing work make any of this possible?

**Comment by jviau** [comment]
For setting of role name, role instance, and some other properties like user-agent, these are not managed by Durable. Are they set by any pieces of telemetry for your app? Typically, this is set by the end user. A `ITelemetryInitializer` would work: https://medium.com/@woeterman_94/application-insights-how-to-set-the-cloud-role-name-in-net-core-net-5-62dff23db199. For User-Agent, it is not applicable for durable orchestrations/activities - this is not a HTTP request. For the `HttpState_...` operations you have, that is not durable specific but rather a basic HTTP trigger function - so the best place to discuss that would be in the [Azure Functions github](https://github.com/Azure/azure-functions-host/).

For the inconsistent operation IDs and inability to add activity tags, these will be addressed by the distributed tracing work.
