### ISSUE TITLE
RaiseEvent Exception on Orchestration that Should Exist

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-durable-extension#2308]
### Description

I have two seperate Durable Functions Apps. Im using  `IDurableClientFactory` to RaiseEvents between them.

Calling RaiseEvent from A to B sometimes result in exception `No instance with ID 'ad9ade574b0d4815ac5c7965b2647fa0:0' was found. (Parameter 'instanceId')` 

StackTrace
```csharp
System.ArgumentException: No instance with ID 'ad9ade574b0d4815ac5c7965b2647fa0:0' was found. (Parameter 'instanceId')
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.GetOrchestrationInstanceStateAsync(TaskHubClient client, String instanceId) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 709
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableClient.RaiseEventInternalAsync(TaskHubClient taskHubClient, String taskHubName, String instanceId, String eventName, Object eventData) in D:\a\_work\1\s\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableClient.cs:line 722
```
[![](https://img.shields.io/badge/Formatted%20by-https%3A%2F%2Fst.elmah.io-%230da58e)](https://st.elmah.io)

...but when looking at AzureStorage, the instance does exist.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/8879065/200793636-853095dc-724f-424b-b755-9cb57d162478.png">

Interestingly, If I look at the timestamp of that exception, according to my logs, its at 1667979935636 (Wed Nov 09 2022 07:45:35 GMT+0000) which is before the timestamp in AzureStorage, where the earliest timestamp is 2022-11-09T07:45:36.8160302Z  (see screenshot).

Does this mean the RaiseEvent was fired before the Orchestration state was persisted to Azure Tables?

Another reason could that RaiseEvent is trying to act on an Internal Orchestration, but should be targeting an external Orchestration, but im not sure that this is the case as this exception is intermittent (in most cases the code is working fine) and my durable client options are set to `IsExternalClient = true`.

A snippet of the DurableClientOptions (note that external is set hardcoded to true)
``` csharp
 DurableClientOptions opts = new DurableClientOptions()
  {
      ConnectionName = $"MyConnName",
      IsExternalClient = true,
      TaskHub = configuration.GetValue<string>($"MyTaskHub"),
  };
```

### Expected behavior
When calling RaiseEvent after an Orchestration has started, the event should be raised on the target orchestration.

### Actual behavior
Exception thrown stating target Orchestration is not found.

### Known workarounds
Wait and Check for orchestration existences before continuing code execution

### App Details

- **<TargetFramework>net6.0</TargetFramework>**
- **Durable Functions extension version -**: 2.8.0
- **Azure Functions runtime version **: 4
- **Programming language used **: CSHARP

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: Wed Nov 09 2022 07:45:35 GMT+0000
- **Function App name**:  

ParentOrchestrationFunctionApp
durablestream-processor-dev
- **Function name(s)**:  HttpConnectorOrchestrator

ChildEntityFunctionApp
durablestream-ratelimiter-dev
- **Function name(s)**: HttpScheduler.ProcessRequestAsync

  Processor, Ratelimiter
- **Azure region**: WestEurope
- **Orchestration instance ID(s)**: 

**ParentOrchestrationId**
ad9ade574b0d4815ac5c7965b2647fa0:0,

**ChildEntityId (Where RaiseEvent is executed)**
@httpscheduler@93f98b82-fb63-4b1b-a47e-123218a373c0

- **Azure storage account name**: bbfunctionsstaging

**Comment by cgillum** [comment]
> Does this mean the RaiseEvent was fired before the Orchestration state was persisted to Azure Tables?

Yes, this is most likely the reason. To be even more specific, this will happen if the _Instances_ table does not yet have a record of the instance existing. The way to avoid this is to ensure that the orchestration has actually been created before raising the external event (i.e., the workaround you mentioned above).

**Comment by gorillapower** [comment]
Without confirming, my assumption is that the parent Orchestation should exist, because the RaiseEvent is actually initialised from an Activity within that orchestration (the Activity Signals an Entity, which then raises the event) . But perhaps the Orchestration just exists in memory at that point and has not been persisted. 

In any event, I will implement the work around to see if this solves the issue

**Comment by davidmrdavid** [comment]
@cgillum: if the ExternalEvent is raised within an Activity, the orchestrator should already exist in the Instances table, shouldn't it?

**Comment by cgillum** [comment]
@davidmrdavid No, not necessarily. We send queue messages to prior to updating the Instances table whenever saving changes to Azure Storage. This means there is a race condition where the activity can start executing before the Instances table was updated, resulting in problems like this. It's an unfortunate consequence of not being able to transactionally update a table and send a queue message at the same time in Azure Storage.

@gorillapower one way to workaround this issue is to create a no-op durable timer in your orchestration prior to making your activity function call. This ensures that the Instances table has been updated before your activity function executes, which ensures that the raise event call from app A to app B will always succeed.

**Comment by gorillapower** [comment]
@cgillum after implementing your suggestion, the exceptions are no longer happening, thank you!
