### ISSUE TITLE
Precompiled samples won't compile for netstandard2.0

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-functions-durable-extension#233]
Problem: C# precompiled samples won't compile under netstandard2.0

Steps to reproduce:
1. Change `csproj` to `<TargetFramework>netstandard2.0</TargetFramework>`
2. Build
3. Several errors appear:

> Error	CS1061	'HttpRequestMessage' does not contain a definition for 'GetQueryNameValuePairs' and no extension method 'GetQueryNameValuePairs' accepting a first argument of type 'HttpRequestMessage' could be found (are you missing a using directive or an assembly reference?)		
\azure-functions-durable-extension\samples\precompiled\HttpSyncStart.cs

Is this extension method available in .NET Standard 2.0?

> Error	CS0246	The type or namespace name 'CreateMessageOptions' could not be found (are you missing a using directive or an assembly reference?)		
\azure-functions-durable-extension\samples\precompiled\Monitor.cs	91

I think precompile directive is missing in `using` block similar to what `PhoneVerification` has

**Comment by cgillum** [comment]
The precompiled samples predate the VS support for running the functions v2 host, so I think we just got used to not testing them with this configuration. Now that Functions v2.0 has better tooling support, it makes sense for us to make sure the samples compile for both Functions v1.x and Functions v2.0.

@kashimiz would you mind taking a look at this?

**Comment by cgillum** [comment]
I had to do some testing with the samples anyways so I went ahead and fixed this.
