### ISSUE TITLE
No binding parameter exists for... 

### ISSUE THREAD

**Issue by DannyvanderKraan** [Azure/azure-functions-durable-extension#234]
I am using Microsoft.Azure.WebJobs.Extension.DurableTask 1.2.0-beta3 and I am still getting: "...no binding parameter exists for..." 

My model:

```
   public class NewZippedBagMutationFileMessage
    {
        public string Url { get; set; }
        public string Name { get; set; }
    }
```

My function signature:

 ```
       public static async Task<string> Run([ActivityTrigger] NewZippedBagMutationFileMessage newZippedBagMutationFileMessage,
            [Blob("zipped-bagmutationfiles/{Name}", FileAccess.Write, Connection = "AzureWebJobsStorage")]  Stream zippedBagMutationFile,
            ILogger log,
            [Inject]IProvideBagMutationFiles repository)
        {
//Stuff happens...
}

```
It can't bind "Name". Am I doing something wrong or is this still an issue? I read that it should be fixed: https://github.com/Azure/azure-functions-durable-extension/issues/74. Thank you in advance for looking into this.

**Comment by cgillum** [comment]
The syntax of the binding expressions is a it different. I apologize that we don't have this documented yet, but take a look at this PR description for some examples: https://github.com/Azure/azure-functions-durable-extension/pull/172

In your case, I think you simply need to change `{Name}` to `{data.Name}`.

**Comment by DannyvanderKraan** [comment]
Yes this resolves the problem. Thank you!

And no worries. I think you guys got a lot of work to do. Very happy with Durable Functions by the way. Let me know if I can help out. Want me for instance to add this to the docs?
