### ISSUE TITLE
Add F# samples

### ISSUE THREAD

**Issue by mikhailshilkov** [Azure/azure-functions-durable-extension#235]
Extend samples with some F# examples similar to C# precompiled project

**Comment by mikhailshilkov** [comment]
Created initial commit at https://github.com/mikhailshilkov/azure-functions-durable-extension/commit/cc9129023ddc298ce700cd8509ebb0d974e97620

`Monitor` sample is still missing.
Only compiles for .NET Standard 2.0.

@cgillum Would that work?

**Comment by cgillum** [comment]
This looks great! The only change I would make is to update the nuget package version to 1.2.**2**-beta3 (makes it compatible with the latest v2.0 runtime in Azure) and name the directory **fsharp** instead of **fs**.
