### ISSUE TITLE
SignalEntityAsync doesn't seem to leverage custom JsonSerializationSetings from custom IMessageSerializerSettingsFactory

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-functions-durable-extension#2361]
### Description
I've got a durable entity defined in class scope that has properties with private setters.  When i call SingnalEntityAsync all these properties are set to default when the actual handle method is called.  If i add a [JsonProperty] to these properties with a private setter, their value is correct.

I tried setting a private resolver contract with
```
public class PrivateResolver : DefaultContractResolver
    {
        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            var prop = base.CreateProperty(member, memberSerialization);
            if (!prop.Writable)
            {
                var property = member as PropertyInfo;
                var hasPrivateSetter = property?.GetSetMethod(true) != null;
                prop.Writable = hasPrivateSetter;
            }
            return prop;
        }
    }

    internal class CustomMessageSerializerSettingsFactory : IMessageSerializerSettingsFactory
    {
        public JsonSerializerSettings CreateJsonSerializerSettings()
        {
            return new JsonSerializerSettings()
            {
                ContractResolver = new PrivateResolver(),
                TypeNameHandling = TypeNameHandling.None,
                DateParseHandling = DateParseHandling.None,
            };
        }
    }

 builder.Services.AddSingleton<IMessageSerializerSettingsFactory, CustomMessageSerializerSettingsFactory>();
```

i'm seeing my PrivateResolver::CreateProperty being called with the expected MemberInfos so DI seems configured right, but all SignalEntityAsync's from the DurableClient don't seem to set values for properties with private setters still.

### Expected behavior
Expect properties with private setters to have appropriate value 

### Actual behavior
value is set to default (null)

### Relevant source code snippets
see above

### Known workarounds
explicitly setting a [JsonProperty] attribute on each property and the value appears

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.9.1
- **Azure Functions runtime version (1.0 or 2.0)**: 4
- **Programming language used**: c#

### Screenshots
N/A

### If deployed to Azure
N/A

**Comment by davidmrdavid** [comment]
@sebastianburckhardt: Am I correct in understanding that the `[JsonProperty]` attribute is strictly necessary for class-style Entity state to be persisted? I thought this was the case, but I may be mistaken.

@drdamour: any chance you could provide us with a minimal repro? That would help accelerate this on our end.

**Comment by drdamour** [comment]
Not stale

**Comment by davidmrdavid** [comment]
Indeed, not stale. Pinging @sebastianburckhardt again, and will reach out internally as well

**Comment by sebastianburckhardt** [comment]
> but all SignalEntityAsync's from the DurableClient don't seem to set values for properties with private setters still

This may be a misunderstanding about how the [SignalEntityAsync](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-entities#example-client-signals-entity-through-interface) API works.

For example, consider that your are using this API to signal a counter entity, say as follows:
```csharp
 await client.SignalEntityAsync<ICounter>(entityId, proxy => proxy.Increment());    
```
Then `proxy` is not actually the counter object - its state is empty. This proxy is generated using reflection (similar to what you would encounter in a mock testing environment) and its only use is to generate signal messages (when you call `Increment` it actually just generates a message and puts it into the queue, to be executed on whatever remote machine may be currently hosting the counter).

Does this make sense? Or am I missing something? What exactly is the invocation on your client that is not giving you the expected behavior?

**Comment by drdamour** [comment]
> 
> Does this make sense? Or am I missing something? What exactly is the invocation on your client that is not giving you the expected behavior?

yeah makes sense but not related to this. Bot using proxy.  

Im putting a breakpoint in the entity dispatch and hitting it in debugger when the actual execution happens (the equivalent of activity function

all the props on the entity are null.l at that point because the jsonserializersettings dont seem to be being used

**Comment by sebastianburckhardt** [comment]
Got it, sorry for the misunderstanding. I think I found the problem. Just like you said, the code that deserializes the entity state does not use the configured settings. This is a bug.

This is roughly how it works currently:
```csharp
var entityObject = ActivatorUtilities.CreateInstance(_functionInvocationServices, objType, parameters);
JsonConvert.PopulateObject(serializedState, entityObject);
```

But the second line should really look like this:
```csharp
JsonConvert.PopulateObject(serializedState, entityObject, this.messageDataConverter.JsonSettings);
```

I will create a PR for this.

**Comment by drdamour** [comment]
cool, i couldn't find the those lines i knew they were there but this code base is tricky with so much of it being in durable task. glad i gained your confidence enough that you believed my terrible description enough to go looking!
