### ISSUE TITLE
Orchestration instances are either stuck in pending state or running very slow for a long time. 

### ISSUE THREAD

**Issue by madhupriyatamPV** [Azure/azure-functions-durable-extension#2381]
### Description
We are facing the issue of our orchestration instances stuck in Pending state for a very long time or the instances running for a long time and are slow. The orchestration trigger is not letting us create another instance since one of them is pending. We do have terminateasync to handle such scenarios, but it is not working as expected as well. How can we handle this as this is occurring quite often?

### Expected behavior
TerminateAsync should terminate orchestrators stuck with RuntimeStatus Pending.  

### Actual behavior
TerminateAsync does not terminate orchestrators stuck with RuntimeStatus Pending and orchestration instances are stuck as pending. 
Most of the times the instances are slow processing. 

### This is the code of our orchestration trigger:
```csharp
private static bool ShouldStartNewInstance(DurableOrchestrationStatus status)
{
return status == null ||
status.RuntimeStatus == OrchestrationRuntimeStatus.Canceled ||
status.RuntimeStatus == OrchestrationRuntimeStatus.Failed ||
status.RuntimeStatus == OrchestrationRuntimeStatus.Terminated ||
status.RuntimeStatus == OrchestrationRuntimeStatus.Completed ||
status.RuntimeStatus == OrchestrationRuntimeStatus.Unknown;
}

    private async Task<IActionResult> StartScheduler(
        IDurableOrchestrationClient starter,
        ILogger log,
        SchedulerConfiguration config,
        string functionName)
    {
        var instanceStatus = await starter.GetStatusAsync(config.SchedulerName, false, false, false);
        bool shouldStartNew = ShouldStartNewInstance(instanceStatus), isForceRestart = false;
        if (!shouldStartNew && config.ForceRestart)
        {
            await starter.TerminateAsync(config.SchedulerName, "user kill");
            shouldStartNew = true;
            isForceRestart = true;
            // Delay a while to make sure staus get updated
            await Task.Delay(5 * 1000);
            log.LogInformation($"Shutting down durable function by forceRestart {config.SchedulerName}");
        }

        if (shouldStartNew)
        {
            await starter.StartNewAsync(functionName, config.SchedulerName, config);
            log.LogInformation($"Started {functionName} with ID = '{config.SchedulerName} with force={isForceRestart}, config = '{JsonConvert.SerializeObject(config)}'.");
            return new OkObjectResult($"Started {functionName} with ID = '{config.SchedulerName} with force={isForceRestart}");
        }
        else
        {
            return new ConflictObjectResult(
                $"An instance of ScheduleLowPriorityEvents with ID '{config.SchedulerName}' already exists. " +
                $"Status: {instanceStatus.RuntimeStatus}");
        }
    }
```

### Known workarounds
Open the instances table with Azure Storage Explorer, look for RuntimeStatus Pending orchestrators older than desired value, manually change RuntimeStatus to Terminated and save.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.7.0
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: c#

### 
I ran the diagnosis for our azure function and see this issue. We are working on adding extendedSessionsEnabled and extendedSessionIdleTimeoutInSeconds and dedicated storage account. Other than this, please suggest if there are any other fixes. 

<img width="689" alt="image" src="https://user-images.githubusercontent.com/77655882/217593319-e2b0e1e2-3f72-474e-9a94-d38f167afb79.png">

- **Function App name**: AzureAAAFastUpdateAMER
- **Function name(s)**: 
- **Azure region**: West US 2
- **Orchestration instance ID(s)**: LowPrioritySchedulerAMER, HighPrioritySchedulerAMER
- **Azure storage account name**: aaafastupdatestorage

**Comment by davidmrdavid** [comment]
Hi @madhupriyatamPV: Do you have any instanceIDs we can use to filter down our logs for the affected orchestrations? A timerange in UTC where the issue can be seen for each instanceID would also be ideal. Thanks!

**Comment by madhupriyatamPV** [comment]
Hi @davidmrdavid , if you are looking for the execution Ids. here is one of them: be574cfe3fea48d4a4543dd861a281eb
2023-02-09T00:35:49.5451892Z

**Comment by madhupriyatamPV** [comment]
But as shared earlier in the OG post, instance Ids are LowPrioritySchedulerAMER, HighPrioritySchedulerAMER and 
2023-02-08T00:35:49.5451892Z to 2023-02-09T00:35:49.5451892Z is the timerange.

**Comment by davidmrdavid** [comment]
Hi @madhupriyatamPV:

Sorry for the late reply. I took a look at "LowPrioritySchedulerAMER" from 2023-02-08T00:35:49.5451892Z to 2023-02-09T00:35:49.5451892Z and saw it was in the Running state throughout this time. However, I see it doing work throughout this time. It appears to be in long cycle of scheduling some task, waiting for that task to complete, then scheduling a timer, waiting for for that timer to fire, and then scheduling a task again to restart the cycle. Given that I see it doing work constantly, I cannot yet determine that the orchestrator is *stuck*.

Looking at this data alone, I'm unable to determine if this is expected given the code of your orchestrator, or if this cycle is supposed to end. Can you please provide me with a description of what your orchestrator is doing (some pseudocode would help), how long these timers are waiting for, and any context as to why I'm seeing this cycle? Thanks!

**Comment by davidmrdavid** [comment]
Additionally, I noticed you're using a rather old version of the Durable Functions Extension. Any chance you could upgrade to the latest release? That would help ensure we have access to the latest telemetry, and that you have access to the latest reliability and performance improvements. Thanks!

**Comment by davidmrdavid** [comment]
Issue is not stale, re-opening
