### ISSUE TITLE
Eternal orchestration executes orchestrator function twice on every execution

### ISSUE THREAD

**Issue by michaelelleby** [Azure/azure-functions-durable-extension#2382]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

Eternal orchestration is executed twice on every execution, instead of just once as is expected. Simply start the orchestrator using the HTTP trigger http://localhost:7163/api/Function1_HttpStart

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

### Expected behavior
> A clear and concise description of what you expected to happen.

Orchesetrator function is executed **once** every 5 seconds.

### Actual behavior
> A clear and concise description of what actually happened.

Orchesetrator function is executed **twice** every 5 seconds.

### Relevant source code snippets
Sample solution demonstrating the issue is available at https://github.com/michaelelleby/DurableFunctionsDoubleOrchestratorExecution

### Known workarounds
> Provide a description of any known workarounds you used.

None.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.9.1
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

This happens even when debugging the function app locally through Visual Studio.

**Comment by cgillum** [comment]
This is by design. The first execution runs until the first await where you create the timer. The second execution is triggered by the completion of your timer.

**Comment by michaelelleby** [comment]
Ah so I need to check the `context.IsReplay` property to see if it is the first execution, got it.
