### ISSUE TITLE
RaiseEvent not received by the orchestration instance

### ISSUE THREAD

**Issue by ltouro** [Azure/azure-functions-durable-extension#2389]
### Description

As the usage of our orchestrations increase (Azure storage), we noted that some events raised with "workflowClient.RaiseEventAsync" are never received by the workflow.

### Expected behavior
If workflowClient.RaiseEventAsync does not throw, the event is eventually received by the workflow.

### Actual behavior
Some events are not received by the workflow

It is indeed possible/expected that RaiseEvent may not always be received by the workflow? 

### Other information

We have a growing number of past workflows in the history that seems to make everything slower. It is expected to mainting the history small? Does this may help with that issue?

We use a custom host (not Azure Functions runtime).

**Comment by ltouro** [comment]
Package Versions: 

Microsoft.Azure.WebJobs.Extensions.Storage 5.0.1
Microsoft.Azure.WebJobs.Extensions.DurableTask 2.7.2

**Comment by cgillum** [comment]
Can you share an example orchestration which occasionally doesn't receive events? Whether an orchestration receives an external event depends on the orchestration's implementation.

**Comment by ltouro** [comment]
These are pretty complex workflows, so I would need to try to create a small repro first. 

Do you mean the raised event only shows up in History if the implementation is handling a WaitForExternalEvent task? Not 100% sure but events seems to show in the history table even if they are not being waited yet (or ever for that matter).

**Comment by cgillum** [comment]
The received event will always show up in the history, whether an orchestration tries to handle it or not. The case where you might expect to *lose* these events is when doing `ContinueAsNew`.

In the case where you're seeing these events dropped, do they show up in the history? Also, do you have any `ContinueAsNew` usage in these orchestrations?

**Comment by ltouro** [comment]
No usage of ContinueAsNew in this case. The orchestration remains in Running state and sending the event again is usually what it takes to continue processing.

Thanks for the info. I will try to narrow a repro case or at least get some evidence of this happening that I could share

**Comment by emattison** [comment]
I believe I am seeing this issue as well. My orchestration code is below. This is a .NET 6 Isolated project. I am using the following packages.

- Microsoft.Azure.Functions.Worker.Sdk 1.10.0
- Microsoft.Azure.Functions.Worker 1.14.0
- Microsoft.Azure.Functions.Worker.Extensions.Durabletask 1.0.2
- Microsoft.Azure.Functions.Worker.Extensions.Http 3.0.13

```
public class OrchestratorFunctions
{
	private const string INSTANCE_ID_QUERYSTRING = "instanceId";
	private const string ORCHESTRATOR_NAME = nameof(WaitForProcessingOrchestrator);
	private const string IMAGE_PROCESSING_EVENT_NAME = "ImageProcessing";
	private const string DOCUMENT_PROCESSING_EVENT_NAME = "DocumentProcessing";
	private readonly ILogger<OrchestratorFunctions> _logger;

	public OrchestratorFunctions(ILogger<OrchestratorFunctions> logger)
	{
		_logger = logger;
	}

	[Function(nameof(WaitForProcessingOrchestrator))]
	public async Task WaitForProcessingOrchestrator(
		[OrchestrationTrigger] TaskOrchestrationContext context)
	{
		var eventTasks = new List<Task>
		{
			// Setup events to wait for before continuing
			context.WaitForExternalEvent<bool>(IMAGE_PROCESSING_EVENT_NAME),
			context.WaitForExternalEvent<bool>(DOCUMENT_PROCESSING_EVENT_NAME)
		};

		if (!context.IsReplaying)
			_logger.LogInformation("Waiting for events");

		await Task.WhenAll(eventTasks);

		_logger.LogInformation("All events completed");
	}

	[Function(nameof(TriggerOrchestration))]
	public async Task<HttpResponseData> TriggerOrchestration(
		[HttpTrigger(AuthorizationLevel.Function, "post")] HttpRequestData req,
		[DurableClient] DurableTaskClient client)
	{
		string? instanceId = req.Query[INSTANCE_ID_QUERYSTRING];

		if (string.IsNullOrEmpty(instanceId))
			throw new ArgumentException($"{INSTANCE_ID_QUERYSTRING} is missing", INSTANCE_ID_QUERYSTRING);

		_logger.LogInformation("Kicking off orchestration");

		await client.ScheduleNewOrchestrationInstanceAsync(ORCHESTRATOR_NAME, new StartOrchestrationOptions { InstanceId = instanceId });

		return req.CreateResponse(System.Net.HttpStatusCode.Accepted);
	}
}
```

**Comment by ltouro** [comment]
Today we had a new case. The "RaiseEvent' was submited but never showed on the history table. 

We have app insights entries showing the Azure Storage accepting the request (status code 201):

![image](https://github.com/Azure/azure-functions-durable-extension/assets/5283919/28af211d-9c57-493a-9a4f-d4ca7221b8fb)
![image](https://github.com/Azure/azure-functions-durable-extension/assets/5283919/2962fcd8-756c-42eb-bd04-cff07c673f14)

Let me know if you want me to share the evidence with you

**Comment by ltouro** [comment]
The event was raised in the time between 'timestamp' and '_Timestamp'. Not sure what these two fields mean but the 5-minute windows seems a little suspicious. As if the first 'execution start' attempt failed and the message re-queued (and events in the meantime discarded)

![image](https://github.com/Azure/azure-functions-durable-extension/assets/5283919/e6ea8dbc-e131-489a-820d-5b5941307b3c)

**Comment by ltouro** [comment]
Thanks for your input @cgillum. Altough we can go after the possible reasons the app was restarted, I think that is something not totally avoidable and even expected from time to time. We use containers in an managed environment, so the manager may be moving things around eventually. Thus, I would rather make sure that this kind of scenario is not a problem than trying to get a 100% uptime. 

I think it is possible/reasonable to check wheter the workflow is already running before raising the event and give a meaningful message to our client when this is not the case. 

Since it seems that is expected behaviour from the framework, I will close this isue for now.
