### ISSUE TITLE
Functions v2 HTTP API different URL prefix (using Microsoft.Azure.WebJobs.Extensions.DurableTask v1.2.2-beta3)

### ISSUE THREAD

**Issue by CarlosSardo** [Azure/azure-functions-durable-extension#239]
Hi,

In the [HTTP API reference docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-http-api#http-api-reference) for Durable Functions (runtime v2) the URL prefix is documented with _**webhookextensions/handler**_:

`GET /webhookextensions/handler/DurableTaskExtension/instances/{instanceId}?taskHub={taskHub}&connection={connection}&code={systemKey}&showHistory={showHistory}&showHistoryOutput={showHistoryOutput}`

Although, when using:

- **Microsoft.Azure.WebJobs.Extensions.DurableTask v1.2.2-beta3**
- Microsoft.NET.Sdk.Functions v1.0.13
- VS 2017 v15.6.2 with Azure Functions and WebJobs Tools v15.0.40405.0

When starting the func-app locally and triggering the **HttpStart** function, we get a different URL prefix  _**runtime/webhooks**_ instead:

```
{
   "id":"1e3e4d612ac543bcbf43c2e5b733d1eb",
   "statusQueryGetUri":"http://localhost:7071/runtime/webhooks/DurableTaskExtension/instances/1e3e4d612ac543bcbf43c2e5b733d1eb?taskHub=DurableFunctionsHub&connection=Storage&code=UcoEaxQnCp3pb2iduaJalfpDBuNCbYETDd0j/aMY4m0nmB4yd7xngA==",
   "sendEventPostUri":"http://localhost:7071/runtime/webhooks/DurableTaskExtension/instances/1e3e4d612ac543bcbf43c2e5b733d1eb/raiseEvent/{eventName}?taskHub=DurableFunctionsHub&connection=Storage&code=UcoEaxQnCp3pb2iduaJalfpDBuNCbYETDd0j/aMY4m0nmB4yd7xngA==",
   "terminatePostUri":"http://localhost:7071/runtime/webhooks/DurableTaskExtension/instances/1e3e4d612ac543bcbf43c2e5b733d1eb/terminate?reason={text}&taskHub=DurableFunctionsHub&connection=Storage&code=UcoEaxQnCp3pb2iduaJalfpDBuNCbYETDd0j/aMY4m0nmB4yd7xngA=="
}
```

**Comment by cgillum** [comment]
Good catch! I had not noticed that this was changed. We'll update the docs. Or, if you'd like to contribute directly, you can open a PR against the documentation GitHub repo as well (it will get assigned to me for review). :)

More details on contributing to docs here: https://docs.microsoft.com/en-us/contribute/

**Comment by CarlosSardo** [comment]
I can update the docs and submit a PR. Thanks @cgillum

**Comment by cgillum** [comment]
I approved the docs PR. It should get merged in the next few days. Thanks for doing this!
