### ISSUE TITLE
Properties of HttpRequestException are overwritten, when exception is thrown in an activity function and handled in orchestrator

### ISSUE THREAD

**Issue by michaelelleby** [Azure/azure-functions-durable-extension#2397]
### Description
Exceptions of type `HttpRequestException` thrown in an activity function, get all their information discarded.

### Expected behavior
Exception is retains its properties, when caught in orchestrator.

### Actual behavior
When an activity function throws an exception of type `HttpRequestException`, e.g. when making a HTTP request to an external API and gets a timeout, the `HttpRequestException` gets wrapped in `FunctionFailedException` as [documented](https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-error-handling#errors-in-activity-functions) and can be caught in the orchestrator by catching `FunctionFailedException`. But when inspecting the `InnerException` property of the `FunctionFailedException` in the orchestrator, the StatusCode property is null and the `Message` property does not contain the original error message, instead it contains the text `Exception of type 'System.Net.HttpRequestException' was thrown.` This means that it is impossible to determine that it was a timeout error, when handling the exception in the orchestrator, because both the `StatusCode` and `Message` properties now contain useless data.

### Relevant source code snippets
I have made a tiny project to demonstrate the issue https://github.com/michaelelleby/DurableFunctionsExceptionBug

### Known workarounds
None, because it is impossible to know which exceptions will be thrown, and thus we cannot implement our own workaround exception wrappers.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.9.1
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
I have provided the source code of a Function App demonstrating the issue, see GitHub link above.

**Comment by bachuv** [comment]
@michaelelleby Thanks for opening this issue and letting us know about this! From what I understand, are you looking to see if we can expose the `StatusCode` and `Message` of the `HttpRequestException` that was thrown in the activity function?

**Comment by michaelelleby** [comment]
@bachuv I am looking for the values:
- ReasonPhrase
- Content
- StatusCode
- Version
I understand that `Content` is special, however losing the response content makes it very hard to troubleshoot errors, when viewing log entries.
