### ISSUE TITLE
Error handling for Azure Event Grid publishing

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#241]
This is a followup for https://github.com/Azure/azure-functions-durable-extension/issues/216. Current Event Grid publishing does not have a defined error handling behavior. Protocol errors will be ignored, but connection failures will cause the orchestration instance to fail.

There are ramifications for both failure and non-failure policies, so we should probably allow the user to decide which option is better. For transient errors (connectivity failures, HTTP 503, etc.) we should implement automatic retry for improved reliability. More details on the REST API can be found here: https://docs.microsoft.com/en-us/azure/event-grid/post-to-custom-topic

**Comment by TsuyoshiUshio** [comment]
Do you mean 

* Make customer can add some attribute on `host.json`  for failure/non-failure policies
* Make customer can add some attribute for retry policy
* Implement these

I'm not a good programmer and also, I can't work this in a couple of days and no one want to do it, I'd like to do it!  I only care about your review work load for me like last time. I felt sorry about that.  If these are OK, I'd love to do it.

**Comment by TsuyoshiUshio** [comment]
Other thing is, how about the document contribution as you mentioned last time? Maybe we need to update this page. I can add some example and explanation on this page. e.g. host.json configration.  https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-versioning  Is this what you did intend to?

**Comment by cgillum** [comment]
For this item, I was thinking this:

* Customer adds an attribute on host.json for failure/non-failure policies
* We add automatic retry for HTTP 503, timeouts, and connectivity errors. We can skip configuration for this for now. I expect there are some best practices available that we can follow.

I would love to have your contribution if you are willing. :) There is no rush on getting this done quickly since it will not be commonly needed (hopefully Azure Event Grid is always highly available). However, I do think we will want this in order for it to truly be "production ready" and give customers greater confidence in the feature.

Here is an interesting post on best practices for implementing automatic retry with HttpClient: https://stackoverflow.com/questions/19260060/retrying-httpclient-unsuccessful-requests. This answer in particular looks like a good, clean approach with minimal dependencies: https://stackoverflow.com/a/35183487/2069 (uses [Polly](https://github.com/App-vNext/Polly)).

**Comment by TsuyoshiUshio** [comment]
Thank you @cgillum ! I'd happy to do it! :) To contribute this repo is my pleasure and fun. Also working with you is totally awesome experience. I'll do it carefully.

**Comment by TsuyoshiUshio** [comment]
Hi @cgillum , I guess the documentation task which assigned me is much higher priority than this one, right? I really wanted this however, I should prioritise the documentation one. However, if possible this should be done before the GA.  I ask @yuka1984 to handle this. However, she is available from the next week. Is it Ok for you? I'll focus on the documentation one. If you can't wait, I'll keep on doing this.

**Comment by cgillum** [comment]
I agree documentation is higher priority, otherwise many developers will not try to use this feature. Your plan is okay with me. 👌

よろしくお願いします！

**Comment by yuka1984** [comment]
Hi @cgillum . I am interested in implementing this topic and want to do a commit. We are planning to start work from around this weekend.

**Comment by cgillum** [comment]
The code for this has been merged. However, we also need to update the documentation with the new public API surface area ([API docs](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskExtension.html) and the [Event publishing](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-event-publishing) topic).
