### ISSUE TITLE
Unable to use Azure Durable entities from Durable orchestration function in .NET 6 isolated azure functions

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/azure-functions-durable-extension#2410]
Hi All,
I'm using Azure function in .NET 6 isolated mode. I'm using azure durable entities also. My intent is to call Azure durable entities from Azure durable orchestration. I have added the below reference  `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.9.2" />`
My orchestration code is as below
```
namespace AzureSagaFunctionApp.Orchestration
{
    public static class AzureSagaOrchestrator
    {
        [Function(nameof(AzureSagaOrchestrator))]
        public static async Task<bool> RunOrchestrator(
            [Microsoft.Azure.Functions.Worker.OrchestrationTrigger] IDurableOrchestrationContext context, ILogger iLogger)
        {

            ILogger logger = context.CreateReplaySafeLogger(iLogger);
            var userInput = context.GetInput<UserInputRequestMessage>();
            var gameEntityId = new EntityId(nameof(GameService), userInput.GameId);
            var userCredit = new EntityId(nameof(UserCreditService), $"{userInput.UserId}_{userInput.GameId}");
            var gameObj = context.CallEntityAsync(gameEntityId, "GetGameAsync", userInput.GameId);


            //replace with entity triggers and not activity tiggers


            // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!"]
            return true;
        }



        [Function("StartOrchestration")]
        [OpenApiOperation(operationId: "HttpStart", tags: new[] { "StartOrchestration" })]
        [OpenApiSecurity("function_key", SecuritySchemeType.ApiKey, Name = "code", In = OpenApiSecurityLocationType.Query)]
        [OpenApiRequestBody("application/json", typeof(UserInputRequestMessage))]
        [OpenApiResponseWithBody(statusCode: HttpStatusCode.OK, contentType: "application/json", bodyType: typeof(StandardResponse), Description = "The OK response")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequestData req,
             [Microsoft.Azure.Functions.Worker.DurableClient] DurableTaskClient client,
            FunctionContext executionContext)
        {
            ILogger logger = executionContext.GetLogger("StartOrchestration");
            var userInputJson = new StreamReader(req.Body).ReadToEnd();
            var userInputs = JsonConvert.DeserializeObject<UserInputRequestMessage>(userInputJson);
            // Function input comes from the request content.
            string instanceId = await client.ScheduleNewOrchestrationInstanceAsync(
                nameof(AzureSagaOrchestrator), userInputs);

            var standardResponse = new StandardResponse { OperationStatus = 200, Status = $"Started orchestration with ID = '{instanceId}'." };
            var response = new HttpResponseMessage { 
                Content = new StringContent(JsonConvert.SerializeObject(standardResponse),Encoding.UTF8,"application/json"),
                StatusCode=HttpStatusCode.Created,ReasonPhrase="Orchestration started"};
            logger.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);
            return response;
            // Returns an HTTP 202 response with an instance management payload.
            // See https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-http-api#start-orchestration
            //return client.CreateCheckStatusResponse(req, instanceId);
        }
    }
}
```
My program.cs is as below
```
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(worker=>  worker.UseNewtonsoftJson())
    .ConfigureServices((hostBuilderContext, services)=>
    {
        services.AddMongoDbClient(hostBuilderContext.Configuration["ConnectionString"]);
        services.AddSingleton<IUserRepository, UserRepository>();
        services.AddSingleton<IGameRespository,GameRespository>();
        services.AddSingleton<IUserCreditRepository, UserCreditRepository>();
        services.AddSingleton<IVotingRepository, VotingRepository>();
        services.AddLogging();
        services.AddDurableClientFactory();
    })
    .ConfigureOpenApi()
    .Build();

host. Run();
```
When I execute the **StartOrchestration function**, The orchestration function never executes. Could you please tell me what should I do get my orchestration function started? I'm currently running the code on my local and I will be hosting the same in Azure functions.

**Comment by VenkateshSrini** [comment]
Hi,
Any update on this issue please would be of immense help

**Comment by davidmrdavid** [comment]
Hi @VenkateshSrini: My understanding is that Durable Entities are not available in the C# isolated worker _yet_. That's still under active development.

FYI @sebastianburckhardt.

However, you seem to be reporting a more general error: am I right in assuming you are not able to run an orchestrator without entities in the C# isolated worker as well?

**Comment by cgillum** [comment]
> I have added the below reference `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.9.2" />`

WebJobs packages cannot be used in the .NET Isolated worker. The orchestration parameter type must be `Microsoft.DurableTask.TaskOrchestrationContext`, which you get transitively when you reference Microsoft.Azure.**Functions.Worker**.Extensions.DurableTask.

**Comment by VenkateshSrini** [comment]
@cgillum 
> > I have added the below reference `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.9.2" />`
> 
> WebJobs packages cannot be used in the .NET Isolated worker. The orchestration parameter type must be `Microsoft.DurableTask.TaskOrchestrationContext`, which you get transitively when you reference Microsoft.Azure.**Functions.Worker**.Extensions.DurableTask.

 If I remove the `Microsoft.Azure.WebJobs.Extensions.DurableTask` then I'm not able to resolve the type `IDurableOrchestrationContext`. Also functions like ` var gameEntityId = new EntityId(nameof(GameService), userInput.GameId);` is showing a syntax error. Without all these how will I invoke an Azure durable entity?

**Comment by VenkateshSrini** [comment]
> Hi @VenkateshSrini: My understanding is that Durable Entities are not available in the C# isolated worker _yet_. That's still under active development.
> 
> FYI @sebastianburckhardt.
> 
> However, you seem to be reporting a more general error: am I right in assuming you are not able to run an orchestrator without entities in the C# isolated worker as well?

This is not started in any document on MSDN. Can you please point me to the correct document

**Comment by cgillum** [comment]
Durable Entities is not yet supported on the .NET Isolated worker, as explained [here](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview#feature-parity-with-in-process-durable-functions):

> Not all features from in-process Durable Functions have been migrated to the isolated worker yet. Some known missing features that will be addressed at a later date are:
>
> * Durable Entities
> * CallHttpAsync

FYI @lilyjma we should probably update the [stateful entities conceptual guide](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-entities?tabs=csharp) to also make this clear.

**Comment by VenkateshSrini** [comment]
@cgillum , thanks for your reply. Having said that the durable entities are not support in isolated worker yet, how would I ensure that one the record in the collection that is actively perused by an orchestration is not modified by other instance of a orchestration function. I'm looking like a soft lock like `context.LockAsync` ?

**Comment by cgillum** [comment]
`context.LockAsync` is also not available since it depends on entities.

What kind of collection is this? Is it some collection in an external database? Do you just need to modify it or do you also need to query it?

**Comment by jeromekol** [comment]
Is there an eta for Durable Entities in Isolated Functions? We use that feature in some places and would like to migrate to .NET 7.

**Comment by fireblade95402** [comment]
Same question from me on the Isolated Functions. I have a customer wanting to move to .NET 7. Be great to know when we might expect this release.

**Comment by jviau** [comment]
We are aiming for this September for entitity support in dotnet isolated.

**Comment by martin1cerny** [comment]
Thank for the information @jviau. It seems to be the last blocker for us to migrate. What shall I watch to get a notification about durable entity support in dotnet isolated? Will you update this issue thread?

**Comment by VenkateshSrini** [comment]
Do we have an Eta on this? Can you please let us know what is stopping the Durable Entities being implemented in Isolated worker?

**Comment by davidmrdavid** [comment]
@VenkateshSrini: This is being actively worked on, and I _believe_ the ETA is a bit over a month from now **if** everything goes according to plan.

The main challenge is that Durable Entities need to be re-implemented for the .NET isolated worker, and this isn't a trivial task. But getting it done is one of our highest priority workstreams at this time.

**Comment by VenkateshSrini** [comment]
@davidmrdavid ,
Requesting you to post the updates on this in this thread so that we are notified well in advance

**Comment by davidmrdavid** [comment]
@VenkateshSrini: I believe the main tracking ticket for this feature is [here](https://github.com/microsoft/durabletask-dotnet/issues/19#issue-1216624946). If you could subscribe to notifications on that ticket, that's would be the best way to stay up to date. Once the ticket is closed, it should be safe to assume the release is close to imminent. Unfortunately, I can't promise to be able to update this thread as incremental progress goes on as I'm not the main person driving this work.

**Comment by VenkateshSrini** [comment]
@davidmrdavid ,
Thanks for your help and information. I have subscribed to the ticket that you have said in the above response

**Comment by lilyjma** [comment]
Support for Entities is now available in .NET isolated. Please see [here](https://github.com/microsoft/durabletask-dotnet/issues/19#issue-1216624946). Closing this issue.
