### ISSUE TITLE
Task Hub name must be specified in host.json when using slots 

### ISSUE THREAD

**Issue by FerZablah** [Azure/azure-functions-durable-extension#2427]
### Description
Same as [#1966](https://github.com/Azure/azure-functions-durable-extension/issues/1966), [#1057](https://github.com/Azure/azure-functions-durable-extension/issues/1057), [#1313](https://github.com/Azure/azure-functions-durable-extension/issues/1313) and related to [#92760](https://github.com/MicrosoftDocs/azure-docs/issues/92760) 
I have 2 slots, the prod slot and the staging slot.
When I deploy a Durable Functions App to the staging slot, it displays:
> Microsoft.Azure.WebJobs.Extensions.DurableTask: Task Hub name must be specified in host.json when using slots.

This only happens in the staging slot, when swapping to the prod slot the error goes away. I do have the hub name specified in the host.json file.

I have also tried setting the ```AzureFunctionsJobHost__extensions__durableTask__hubName``` app setting to a value (with the "Deployment slot setting" box checked), but the error persists.  

### Expected behavior

The function app should load up correctly in both slots.

### Actual behavior

This error is displayed when loading up the staging slot:
> Microsoft.Azure.WebJobs.Extensions.DurableTask: Task Hub name must be specified in host.json when using slots.

### Relevant source code snippets
host,json
```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "RITaskHub"
    }
  },
  "functionTimeout": "01:00:00"
}
```

### Known workarounds

I have also tried setting the ```AzureFunctionsJobHost__extensions__durableTask__hubName``` app setting to a value (with the "Deployment slot setting" box checked), but the error persists.  

### App Details

- **Durable Functions extension version:** v2.9.0
- **Azure Functions runtime version:** v4
- **Programming language used:** C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
-  3/20 9AM PT - 3/21 12PM PT

Note: **I can provide the below details over a secure channel, internally**
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by kemmis** [comment]
+1 Same issue here.

**Comment by mpaul31** [comment]
Task hubs cannot be shared across apps/slots. Try using an app settings token replacement in your host.json:

`"hubName": "%DurableTaskHub%"`

**Comment by davidmrdavid** [comment]
I'm investigating this internally. In this case, @FerZablah does have a `hubName` field in their `host.json`, but their `host.json` config is not being applied at all. I believe this may be due to IConfiguration, or something alike, being override in their `Startup.cs` file, but that's still TBD.

**Comment by bachuv** [comment]
Hi @FerZablah, are you still experiencing this issue? I wasn't able to reproduce it on my end. Are you by chance overriding any configuration setup in your Startup.cs?
