### ISSUE TITLE
Limit Concurrent Access to External Resource

### ISSUE THREAD

**Issue by andrewkittredge** [Azure/azure-functions-durable-extension#2434]
**Is your feature request related to a problem? Please describe.**
Functions can open too many connections to a database or hit an API too fast. 

**Are there any existing GitHub discussions or issues filed that help give some context to this proposal?**
Links to any previous discussions or issues providing context for the proposal.

**Describe the solution you'd like**
Add had a semaphore functionality to OrchestrationContext limiting the number of concurrent activity functions that access a resource.  

```
[FunctionName("StartsDBTasks")]
public static async Task StartDBTasks([OrchestrationTrigger] IDurableOrchestrationContext context)
{
    var queryParams = context.GetInput();
    using var databaseConnectionSemaphore = context.AcquireSemaphore(name: "MyDatabase", maxConcurrent:50);
    context.CallActivity("ActivityThatUsesMyDatabase", queryParams)
}
```

**Describe alternatives you've considered**
You can limit the number of instances with Scale up/Scale out but those are confusing.

**Comment by ltouro** [comment]
This seems a very interesting feature and I would vouch to have a generic approach on the lib

Don't know how fast would that would be, but can't you use a Durable Entity to track how many WFs are using the external resource?

Then, you create a generic logic that checks the number is below your threshold and get the lock or wait a few more seconds.

**Comment by sebastianburckhardt** [comment]
We have talked about this feature in the past as something for which we may add built-in support in the future, similarly to how we already support locks on entities. However, this won't be available very soon, so in the meantime, you could consider using entities to build some kind of semaphore yourself. Something like @ltouro is suggesting could look like this:

```csharp
[FunctionName("OrchestrationWithSemaphore")]
public static async Task<string> OrchestrationWithSemaphore([OrchestrationTrigger] IDurableOrchestrationContext context)
{
    EntityId semaphore = new EntityId("SemaphoreEntity", "MySemaphoreInstance");
    Guid requestId = context.NewGuid();
    DateTime startTime = context.CurrentUtcDateTime;
    TimeSpan timeOut = TimeSpan.FromMinutes(5);
    try
    {
        while (true)
        {
            if (await context.CallEntityAsync<bool>(semaphore, "TryAcquire", requestId))
            {
                break; // we have acquired the semaphore
            }
            if (context.CurrentUtcDateTime > startTime + timeOut)
            {
                throw new Exception("timed out while waiting for semaphore");               
            }
            else
            {
                await context.CreateTimer(context.CurrentUtcDateTime + TimeSpan.FromSeconds(1), CancellationToken.None);
            }             
        }           
        await context.CallActivityAsync("ActivityThatRequiresSemaphore", null);

        return "Completed successfully.";
    }
    finally
    {
        context.SignalEntity(semaphore, "Release", requestId);
    }
}

[FunctionName("SemaphoreEntity")]
public static Task Run([EntityTrigger] IDurableEntityContext ctx) 
    => ctx.DispatchAsync<SemaphoreEntity>();

public class SemaphoreEntity
{
    public List<Guid> Requests { get; set; } = new List<Guid>();

    public int MaxCount { get; set; } = 50;

    public bool TryAcquire(Guid id)
    {
        int position = this.Requests.IndexOf(id);
        if (position == -1)
        {
            this.Requests.Add(id);
            position = this.Requests.Count - 1;
        }
        return (position < this.MaxCount);
    }
 
    public void Release(Guid id)
    {
        this.Requests.Remove(id);
    }
}
```

Note while this should work correctly, it is not a perfect solution. It may add a lot of delay to your processing, especially when using the AzureStorage provider. And it may reduce throughput because of all the extra messages in the system. Still, it may be good enough for some situations. I did a bit of testing [here](https://github.com/microsoft/durabletask-netherite/pull/242), it seems to work o.k. so far.

**Comment by lilyjma** [comment]
@andrewkittredge - Please let us know if Sebastian's suggestion works for you. Thanks!
