### ISSUE TITLE
DurableOrchestrationClient  inside an orchestration function

### ISSUE THREAD

**Issue by andreujuanc** [Azure/azure-functions-durable-extension#244]
Related to https://github.com/Azure/azure-functions-durable-extension/issues/243

```
 public static async Task SomeFunc(
            [OrchestrationClient]DurableOrchestrationClient starter,
            [OrchestrationTrigger] DurableOrchestrationContext context,
            TraceWriter log)
        {


             var status = await starter.GetStatusAsync(context.InstanceId);
```
In this sample, status is not running.  And it looks like it's the previous status. ie, failed, completed, etc.

Is this the correct behaviour? Am I not supposed to do this whilst on an orchestration function? Or is it a bug?

**Comment by andreujuanc** [comment]
More info:
`Function 'WgmCodeJobs (Orchestrator)', version '' failed with an error. Reason: System.InvalidOperationException: Multithreaded execution was detected. This can happen if the orchestrator function previously resumed from an unsupported async callback.`

**Comment by cgillum** [comment]
The Durable Orchestration client performs async I/O which is not allowed in an orchestrator function. It can only be used in non-orchestrator functions. This error message is expected.

**Comment by ElanHasson** [comment]
> The Durable Orchestration client performs async I/O which is not allowed in an orchestrator function. It can only be used in non-orchestrator functions. This error message is expected.

This should probably be mentioned in the docs: "The Orchestration Client is unsafe within orchestrations."
