### ISSUE TITLE
Orchestrator takes long time to start

### ISSUE THREAD

**Issue by asipras** [Azure/azure-functions-durable-extension#2444]
### Description
 Once orchestrator is triggered it goes into Pending state and the actual execution starts after 20 minutes. This does not happen on all orchestrator runs but occasionally hence hard to diagnose what the issue is.

### Expected behavior
Once the orchestrator is triggered it should start within reasonable amount of time.

### Actual behavior
Orchestrator goes into pending state and starts execution after 20 minutes.

### Known workarounds
This happens on some orchestrator runs and so far there are no workarounds for this.

### App Details

- **Microsoft.Azure.Functions.Extensions : version 1.1.0 
- **Microsoft.Azure.Webjobs.Extesions.DurableTask : 2.8.1
- **Azure Functions runtime version : 4.0
- **Programming language used**: c#

### Screenshots
> This is the screen shot of the log messages from application insights. All times are UTC.
![image](https://user-images.githubusercontent.com/16964799/230941141-d714689b-da36-4341-bb06-5e9b99f87318.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:  From 2023-04-06T16:40:59.1518982Z (pending) to 2023-04-06T17:00:32.4224509Z (actual start)
- **Function App name**:  func-CalcOrch-prod-ea
- **Function name(s)**: CalculateOrchestrator
- **Azure region**: EastUS2
- **Orchestration instance ID(s)**: 0d4fc2a3-62af-4202-c678-08db36b2f135
- **Azure storage account name**:  stnewtonprodea001

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment]
Hi @asipras. It looks like there are some logs missing from your screenshot. According to our internal telemetry, your orchestration with ID _0d4fc2a3-62af-4202-c678-08db36b2f135_ started running and had its status updated to "Running" at 2023-04-06 16:41:29 UTC, which is about 30 seconds after it was scheduled and within the expected range.

Double-check your logs query to see if you might be accidentally filtering your logs. Also, double-check to see if your app's logging configuration might be sampling or filtering some of these logs unexpectedly. From our side, it appears everything is working correctly.

**Comment by asipras** [comment]
Thanks @cgillum for quick reply. Indeed we do sample our logs so that can explain the application insight query results. 

Can you share the logs that you have for this instance? This particular calculation is long running one and I would like to understand why it is taking 20 mins from start before it starts queueing messages.

**Comment by cgillum** [comment]
@asipras I'm not seeing a 20-minute gap, but I am seeing about a 10-minute gap before a large fan-out of sub-orchestrations gets scheduled.

![image](https://user-images.githubusercontent.com/2704139/230970809-014b2f08-0da5-4fa0-b472-38dd949f3dc2.png)

Most of the time seems to be spent waiting for the first activity to start after it has been scheduled (maybe the work-item queue is backed up?). After that, there's a 5-minute delay before the orchestrator sees the response (the "DuplicateMessageDetected" warning) - not sure why that happened, though.
