### ISSUE TITLE
/runtime/webhooks/durableTask/instances ignores query parameter showInput.

### ISSUE THREAD

**Issue by michaelelleby** [Azure/azure-functions-durable-extension#2447]
### Description
> A clear and concise description of what the bug is. Please make an effort to fill in all the sections below; the information will help us investigate your issue.

> NOTE: JavaScript issues should be reported here: https://github.com/Azure/azure-functions-durable-js

Documentation https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-all-instances-status clearly states:

| Field | Parameter type | Description |
| --- | -- | -- |
| showInput | Query string | Optional parameter. If set to false, the function input will not be included in the response payload. |

however when calling `/runtime/webhooks/durableTask/instances?showInput=false` the instance input is included in the returned JSON.
I can see that calling `/runtime/webhooks/durableTask/instances/00000000-0000-0000-0000-000000000000?showInput=false` omits the input, i.e. when querying for a specific instance, the input is omitted as expected.

### Expected behavior
> A clear and concise description of what you expected to happen.
Input is omitted from response.

### Actual behavior
> A clear and concise description of what actually happened.
Input is included in response.

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: v2.9.3
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by nytiannn** [comment]
Hi, @michaelelleby michaelelleby. Thanks for the information. Did you mean that, when showInput == false, the input is included in the History table?
