### ISSUE TITLE
What is the binding type of orchestration client?

### ISSUE THREAD

**Issue by JohnReeson** [Azure/azure-functions-durable-extension#245]
I read the document, it says `an output binding that acts as a client`
However when I create  a Httpstart template in portal or download the sample here, the Json file says  `"direction": "in"`. In portal, I change the direction to out and the function also works.
Have I mistaken anything?

**Comment by cgillum** [comment]
Sorry for the confusion. In turns out that the specified direction doesn't matter when binding to DurableOrchestrationClient. I think it matters more when binding to IAsyncCollector or when using non-.NET language bindings.
