### ISSUE TITLE
Clicking on a instance of a durable function getting a an error

### ISSUE THREAD

**Issue by mike-leuer** [Azure/azure-functions-durable-extension#2458]
### Description
Clicking on a instance of a durable function getting a an error
Load failed. EACCES: permission denied, lstat 'c:\git\[***REMOVED***]\python-functions\.venv\lib64'
![image](https://user-images.githubusercontent.com/97471415/234705468-f3648e82-8aa6-4bc7-aee5-2e95f740bd2e.png)

Was working in the past.

**Comment by bachuv** [comment]
Hi @mike-leuer, have you made any role changes since the last time you observed it working?

**Comment by mike-leuer** [comment]
Not that I know of I should be contributor in everything. But I can double check if you can guide me in what documentation of roles are required.
