### ISSUE TITLE
Distributed Tracing does not work when adding environment variables

### ISSUE THREAD

**Issue by benclerix-cegeka** [Azure/azure-functions-durable-extension#2460]
### Description

I took the sample from [this guide](https://github.com/Azure/azure-functions-durable-extension/blob/dev/samples/correlation-csharp/getting-started.md).
I filled in an App Insights key as follows in `local.settings.json`:
```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "APPINSIGHTS_INSTRUMENTATIONKEY": "<APP INSIGHTS KEY HERE>"
  }
}
```
I ran the function locally and triggered the durable function via http://localhost:7071/api/HttpStart_MultiLayerOrchestrationWithRetry.
Distributed Tracing works, I can see correlated requests with "DtActivity" as a prefix (e.g.: "DtActivity MultiLayerOrchestrationWithRetry_Hello").

I then added a FunctionsStartup as follows:
````csharp
using FunctionAppCorrelation;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(Startup))]

namespace FunctionAppCorrelation
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var config = new ConfigurationBuilder().AddEnvironmentVariables().Build();
            builder.Services.AddSingleton<IConfiguration>(config);
        }
    }
}
````
This requires changing FunctionAppCorrelation.csproj with `<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />` to: 
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
    <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.*" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118" PrivateAssets="All" />
  </ItemGroup>
  <ItemGroup>
    <AdditionalFiles Include="..\..\..\.stylecop\stylecop.json" />
    <Compile Include="..\..\..\.stylecop\GlobalSuppressions.cs" Link="GlobalSuppressions.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
When I run this as provided above Distributed Tracing does not work. I do not see the requests with "DtActivity" as a prefix (I only see: "MultiLayerOrchestrationWithRetry_Hello").

When I do not add the singleton IConfiguration then Distributed Tracing works again. This leads me to believe it has nothing to do with the FunctionsStartup, but rather with the environment variables.

Below I listed the environment variables that the code has access to:
```
ZES_ENABLE_SYSMAN
windir
WEBSITE_HOSTNAME
VS_Perf_Session_GCHeapCount
VSSKUEDITION
VSLS_SESSION_KEEPALIVE_INTERVAL
VSLANG
VSAPPIDNAME
VSAPPIDDIR
VisualStudioVersion
VisualStudioEdition
VisualStudioDir
USERPROFILE
USERNAME
USERDOMAIN_ROAMINGPROFILE
USERDOMAIN
USERDNSDOMAIN
TMP
ThreadedWaitDialogDpiContext
TEMP
SystemRoot
SystemDrive
SignInWithHomeTenantOnly
SESSIONNAME
ServiceHubLogSessionKey
PUBLIC
PSModulePath
ProgramW6432
ProgramFiles(x86)
ProgramFiles
ProgramData
PROCESSOR_REVISION
PROCESSOR_LEVEL
PROCESSOR_IDENTIFIER
PROCESSOR_ARCHITECTURE
POWERSHELL_DISTRIBUTION_CHANNEL
PkgDefApplicationConfigFile
PATHEXT
Path
OS
OneDriveCommercial
OneDrive
NUMBER_OF_PROCESSORS
MSBuildLoadMicrosoftTargetsReadOnly
LOGONSERVER
Logging
Logging:LogLevel
Logging:LogLevel:Microsoft.Hosting.Lifetime
LOCALAPPDATA
IIS_USER_HOME
IIS_SITES_HOME
IIS_DRIVE
IIS_BIN
HOMEPATH
HOMEDRIVE
GCExpConfigUsedInSession
FUNCTIONS_WORKER_RUNTIME
FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT
FUNCTIONS_CORETOOLS_ENVIRONMENT
FPS_BROWSER_USER_PROFILE_STRING
FPS_BROWSER_APP_PROFILE_STRING
ForceIdentityAuthenticationType
ENABLE_XAML_DIAGNOSTICS_SOURCE_INFO
EFC_9596
DriverData
ComSpec
COMPUTERNAME
CommonProgramW6432
CommonProgramFiles(x86)
CommonProgramFiles
CegekaCI
AZURE_FUNCTIONS_ENVIRONMENT
AZURE_DEVOPS_ACCESSTOKEN
AzureWebJobsStorage
AzureWebJobsScriptRoot
AzureFunctionsJobHost
AzureFunctionsJobHost:SequentialRestart
ASPNETCORE_SUPPRESSSTATUSMESSAGES
APPINSIGHTS_INSTRUMENTATIONKEY
APPDATA
ALLUSERSPROFILE
```
If the values are relevant I can post some of them on request (some of them might contain sensitive information).

### Expected behavior
I expect Distributed Tracing to work even with the environment variables applied.

### Actual behavior
When I run this as provided above Distributed Tracing does not work. I do not see the requests with "DtActivity" as a prefix (I only see: "MultiLayerOrchestrationWithRetry_Hello").

When I do not add the singleton IConfiguration then Distributed Tracing works again. This leads me to believe it has nothing to do with the FunctionsStartup, but rather with the environment variables.

### Relevant source code snippets
See above.

### Known workarounds
None, we need environment variables to be taken into account in our real application.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.4.0" />
- **Azure Functions runtime version (1.0 or 2.0)**: 3.17.0.0
- **Programming language used**: C#

### Screenshots
> If applicable, add screenshots to help explain your problem.
![2023-04-27 18_01_49-appinsights-dev - Microsoft Azure — Mozilla Firefox](https://user-images.githubusercontent.com/34366781/234920135-c7e159a2-f196-472e-ad0f-405e5be98999.png)

### If deployed to Azure
Not deployed to Azure, just running locally.

**Comment by santo2** [comment]
+1

**Comment by davidmrdavid** [comment]
FYI @bachuv

**Comment by benclerix-cegeka** [comment]
Hi,
Is there an update on this?

**Comment by bachuv** [comment]
Hi @benclerix-cegeka, sorry for the delay. Just to clarify, distributed tracing doesn't work when you add this line, correct?

```
var config = new ConfigurationBuilder().AddEnvironmentVariables().Build();
```

Have you tried the approach explained in the [Use dependency injection in .NET Azure Functions documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources)? Thanks!

**Comment by benclerix-cegeka** [comment]
Correct, when adding `var config = new ConfigurationBuilder().AddEnvironmentVariables().Build();` to `public override void Configure(IFunctionsHostBuilder builder)` it doesn't work.

When customizing configuration sources as you mentioned in [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources) it does work.

Thanks a lot. I'll close this issue for now.

**Comment by bachuv** [comment]
Thanks for the update! Glad to hear that it works now.
