### ISSUE TITLE
Orchestrations are freezing mid execution, and resuming after few minutes.

### ISSUE THREAD

**Issue by miniGweek** [Azure/azure-functions-durable-extension#2463]
### Description

We have an Elastic Premium EP2 App Service Plan that hosts 3 Function Apps where 1 of these  is an Azure Durable Function.
These function apps have 1 Storage Account ( General Purpose v2 ) as the backend. 
This Storage Account hosts the runtime for all the 3 Function Apps, as well as the Orchestrations for the Durable Function.
The function apps are hooked up with Azure Application Insights for logging.

We are noticing that `sometimes` the Orchestration ( and it's activities ) don't do anything for 2-3 minutes and then resumes again. This causes problem for our app.

### Expected behavior
Orchestrations , Sub-Orchestrations and Activities shouldn't have such a longer gap between their executions.

### Actual behavior
Orchestrations are freezing sometimes, and resuming after 2-3 minutes. 

### Relevant source code snippets
The host.json looks like the following for the Durable Function
```json
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "enableDependencyTracking": true,
      "dependencyTrackingOptions": {
        "enableSqlCommandTextInstrumentation": true
      },
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  }
}
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version is 2.9.3**:
- **Azure Functions runtime version is 4.1.3**:
- **Using C#**:

### Screenshots

![image](https://user-images.githubusercontent.com/4948376/236388730-f4498a6d-3558-4500-9f2f-4f1acf7e5f0e.png)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**: Between `04/05/2023, 11:57:45.478 pm` and `05/05/2023, 12:01:22.685 am`
- **Function App name**:  Not disclosing
- **Function name(s)**: AnalogueIn1Vout12vTests
- **Azure region**: Australia East
- **Orchestration instance ID(s)**:  HostInstanceId = `2b259056-0b29-4eb5-8861-144f8844c18f` , prop__instanceid = `e89d4b8d8c3f41cca2f270e384436d50:0`
- **Azure storage account name**:   Not disclosing.

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by bachuv** [comment]
Hi @miniGweek, sorry for the delay. Yes, we are looking into it now. Have you had a chance to look at the [Durable Functions Troubleshooting Guide](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-troubleshooting-guide#orchestration-starts-after-a-long-delay)? Thanks!
