### ISSUE TITLE
Activity function not being called as expected after IDurableOrchestrationContext.CreateTimer() in Azure Durable Function Orchestrator

### ISSUE THREAD

**Issue by ravi-bamrotiya** [Azure/azure-functions-durable-extension#2465]
I am having calling multiple activity function from an orchestrator one by one synchronously using await. 

Orchestrator needs to wait to call the first activity function if some other process is going on in the system. wait works the fine but after waiting over activity function are not being called as expected in sequence.

If there is no wait all works as expected.

that means if I call 'IDurableOrchestrationContext.CreateTimer()', the code written after that not working property. it is calling first activity function but not calling the next activity function.

**Comment by bachuv** [comment]
Hi @ravi-bamrotiya, thanks for reaching out. Would you be able to provide a repro/sample code that shows the issue that you're seeing? This will help us reproduce the issue on our end. Thanks!
