### ISSUE TITLE
Singleton out of process orchestrator two running at the same time

### ISSUE THREAD

**Issue by torepaulsson** [Azure/azure-functions-durable-extension#2466]
Hi,
We've used the singleton pattern for our orchestrator to make sure only one execution is performed at one time, because of a critical section regarding two sequential operations, see  https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons?tabs=csharp#singleton-example

Now when we've tested it, sometimes the orchestration will have to instances running at the same time. We can see logs from one activity in the orchestrator is running at the same time and failing because of it.

Is this pattern broken in the out of process worker?

**Comment by jviau** [comment]
The backend is the same, so the equivalent code should still work in out-of-proc. Can you share a minimal repro?

**Comment by torepaulsson** [comment]
Any news on this? Is there anything more I can do to help?

**Comment by jviau** [comment]
@torepaulsson which backend are you using?

**Comment by jviau** [comment]
I was able to identify the issue - we are missing passing in dedupe statuses in the new backend. So, it isn't really 10 orchestrations being ran, rather the same instance is being restarted 10 times - sometimes even concurrently.

**Comment by torepaulsson** [comment]
I've seen this issue one our production code running on dotnet isolated windows azure function, the example i've only run locally.

Great that you've found the issue @jviau!
