### ISSUE TITLE
Eternal orchestration eventually stops calling activity functions

### ISSUE THREAD

**Issue by grantjames** [Azure/azure-functions-durable-extension#2482]
Description
I have a durable function using the singleton pattern to ensure only one instance of it ever runs. I've created a simplified version below that calls an activity function to simulate some work and then waits for an external event. Once the external event arrives it uses `ContinueAsNew` to start over again.

The reason I'm using the external event is because the trigger that starts the orchestrator can fire at any moment and so if the orchestrator is already running I'll want it to start all over again as soon as it has completed its current run.

This seems to run perfectly, however, at some point in time the orchestrator just stops calling any activities. I know this is incredibly vague, but I can't find any pattern or reason as to why this happens. Checking the logs I see a log to say that the trigger function is sending the wake event to the orchestrator, then I see "Executing orchestrator" and then "Executed orchestrator". I see no logs to say it has run the activitiy.

The thing is, it must be running it because it still responds for the external event every time the trigger function sends it, it just doesn't run the activity.

```csharp
namespace GJTest.Function
{
    public static class DurableFunctionsOrchestrationCSharp1
    {
        const string _instanceId = "some-unique-instance-id";

        const string _eventIdentifier = "NewEvents";

        [FunctionName(nameof(RunOrchestrator))]
        public static async Task RunOrchestrator(
            [OrchestrationTrigger] IDurableOrchestrationContext context, ILogger log)
        {
            await context.CallActivityAsync(nameof(SimulateWork), null);

            await context.WaitForExternalEvent(_eventIdentifier);
            context.ContinueAsNew(null);
        }

        [FunctionName(nameof(SimulateWork))]
        public static async Task SimulateWork([ActivityTrigger] IDurableActivityContext context, ILogger log)
        {
            log.LogInformation("Simulating some work");
            await Task.Delay(TimeSpan.FromSeconds(5));
            log.LogInformation("Finished simulating some work");
        }

        [FunctionName("HttpTriggerOrchestrator")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestMessage req,
            [DurableClient] IDurableOrchestrationClient starter,
            ILogger log)
        {
            if (await OrchestrationHasFinished(starter, log))
            {
                log.LogInformation("Starting a new instance of orchestration");
                await starter.StartNewAsync(nameof(RunOrchestrator), _instanceId);
            }
            else
            {
                log.LogInformation("Orchestrator already running, sending wake event");
                await starter.RaiseEventAsync(_instanceId, _eventIdentifier);
            }

            return starter.CreateCheckStatusResponse(req, _instanceId);
        }

        private static async Task<bool> OrchestrationHasFinished(IDurableOrchestrationClient starter, ILogger log)
        {
            var existingInstance = await starter.GetStatusAsync(_instanceId);
            log.LogInformation($"Orchestration status is {existingInstance?.RuntimeStatus.ToString()}");

            return existingInstance == null 
                || existingInstance.RuntimeStatus == OrchestrationRuntimeStatus.Completed 
                || existingInstance.RuntimeStatus == OrchestrationRuntimeStatus.Failed 
                || existingInstance.RuntimeStatus == OrchestrationRuntimeStatus.Terminated;
        }
    }
}
```

Expected behavior
Orchestrator runs forever and starts over after receiving the external event.

Actual behavior
At some unspecified point the function eventually stops calling the activity functions. Or at least that is what appears to be happening.

To get it working again, I have to terminate the orchestration and use a new instance ID. I imagine I'd achieve the same results by deleting the instance from the instances table.

App Details
Microsoft.Azure.WebJobs.Extensions.DurableTask: v2.9.2
Azure Functions runtime version: 4
Programming language used: dotnet

I should add that I've recently updated to the latest (v2.9.5) of the DurableTask package so I'm currently monitoring it with that version.

**Comment by nytiannn** [comment]
Thanks! So, after execution started, there is no TaskScheduled/Task Completed event for the activity function? Have you checked the work item queue, which is responsible for activity functions, being good?

**Comment by nytiannn** [comment]
Thanks, @grantjames . The problem could because the work item queue went wrong and stopped processing message. Anyways, if this happens again, you could provide the details to us, and we can work on investigate together.

**Comment by grantjames** [comment]
This is happening more frequently now, but I think my assumption of it not calling the activity functions was wrong. It seems to be something to do with the external event. In the logs I am getting:

`2023-06-09T08:12:44Z   [Information]   Executing 'RunOrchestrator' (Reason='(null)', Id=fb0a4858-9c12-4707-8ec8-81485cf4c1ba)
2023-06-09T08:12:44Z   [Information]   5e63f05d-69c1-4790-ad60-783c072e9aa9: Function 'RunOrchestrator (Orchestrator)' saved a 'NewEvents' event to an in-memory queue. State: ExternalEventDropped. HubName: netesthlxdahfunc01. AppName: ne-test-hlx-dah-func-01. SlotName: Production. ExtensionVersion: 2.9.5. SequenceNumber: 86.
2023-06-09T08:12:44Z   [Information]   Executed 'RunOrchestrator' (Succeeded, Id=fb0a4858-9c12-4707-8ec8-81485cf4c1ba, Duration=10ms)`

It seems like it's just adding the event to an in memory queue and not actually progressing past the `WaitForExternalEvent` line. I also can't find anything in the docs to explain what a state of `ExternalEventDropped` means.

**Comment by nytiannn** [comment]
Hi, @grantjames . Thanks for the messages provided.

For the `ExternalEventDropped`, the detailed information can been seen in this [page](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-external-events?tabs=csharp#send-events): Internally, the "raise-event" API enqueues a message that gets picked up by the waiting orchestrator function. If the instance is not waiting on the specified event name, the event message is added to an in-memory buffer. If the orchestration instance later begins listening for that event name, it will check the buffer for event messages and trigger the task that was waiting for it. **`ExternalEventDropped` means that the external event is successfully saved to the buffer.**   If later an orchestrator listens to this event, it will check buffer first to see if there is previous saved ones. This [PR](https://github.com/Azure/azure-functions-durable-extension/pull/578) also illustrates the implements of this feature. 

So, this message is normal and should not be a problem. **The problem is that the activity function is failed.** I ran a query for the instanceId provided, I found the following exception message:
<img width="724" alt="image" src="https://github.com/Azure/azure-functions-durable-extension/assets/110135109/c51cce35-c1e9-45a0-8bcc-6c60e89cdce8">

It seems that the activity function has some problem. Could you check the error message for it? And please let me know if anything I could help.

**Comment by grantjames** [comment]
Thank you for your continued help @nytiannn 👍 

Can I first please ask that you remove the screenshot above? I didn't realise the instance ID in my message would be queryable and show stack traces.

That does raise another question I have, though - does the instance ID provided to `StartNewAsync` need to be unique across the whole of Azure? I have that same instance ID used for the orchestrator across environments - i.e. different resource groups within different subscriptions, so I'd expect to see some exceptions thrown from the development environment.

Thanks again :-)

**Comment by nytiannn** [comment]
Sorry for the inconvenience. I already removed the image.

InstanceId should be unique among TaskHub. https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-orchestrations?tabs=csharp-inproc#orchestration-identity

**Comment by grantjames** [comment]
Thank you very much, @nytiannn :-) I really appreciate your help. I think my problem definitely lies in an activity function causing issues and not the durable functions library. I'm happy for this issue to be closed.

Thanks again.
