### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.DurableTask depends on now deprecated Microsoft.AspNetCore.* 2.2

### ISSUE THREAD

**Issue by johannesoenema** [Azure/azure-functions-durable-extension#2487]
### Description
Microsoft.AspNetCore.* just got deprecated, but Microsoft.Azure.WebJobs.Extensions.DurableTask is depending on it.

#### Example
Implicitely referenced Microsoft.AspnetCore.Server.Kestrel:
![image](https://github.com/Azure/azure-functions-durable-extension/assets/12686691/e86cf778-df1f-4824-83a9-aa4587601afa)
Deprecated:
![image](https://github.com/Azure/azure-functions-durable-extension/assets/12686691/5929c59c-d704-4bca-b4ac-3e35365236de)

Microsoft.AspnetCore.Server.Kestrel.Core tells me even this:
![image](https://github.com/Azure/azure-functions-durable-extension/assets/12686691/1920de88-3fac-4851-9c4a-9211c498c203)

Are there any plans to update this?

### Relevant source code snippets
Related to [Microsoft.Azure.WebJobs.Extensions.Http depends on now deprecated Microsoft.AspNetCore.* 2.2](https://github.com/Azure/azure-webjobs-sdk/issues/2982)

### Screenshots
[Csproj file](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj)
![image](https://github.com/Azure/azure-functions-durable-extension/assets/12686691/0d661751-12d0-4920-a6d2-42bdb760d680)

**Comment by nytiannn** [comment]
Hi, @johannesoenema. Could you tell me the environment and language information? And did you run the function locally or on Azure? Thanks!

**Comment by johannesoenema** [comment]
Hi @nytiannn, I am not sure how this will help, but of course I can provide this information:
NuGet package version: Microsoft.Azure.WebJobs.Extensions.Durabletask 2.9.5
Language: C#

This issue doesn't depend on environment, it has to do with the dependency chain of packages that are used:
- Microsoft.Azure.WebJobs.Extensions.Durabletask 2.9.5 (.NET Standard 2.0)
  - Microsoft.AspNetCore.Mvc.WebApiCompatShim ≥ 2.2.0 (https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.WebApiCompatShim)
  - Microsoft.AspNetCore.Routing ≥ 2.2.0 (https://www.nuget.org/packages/Microsoft.AspNetCore.Routing/)
  - Microsoft.AspNetCore.Server.Kestrel ≥ 2.2.0 (https://www.nuget.org/packages/Microsoft.AspNetCore.Server.Kestrel/)

All these direct dependencies indicate that they are deprecated.

**Comment by nytiannn** [comment]
Hi, @johannesoenema. Thanks. This package is only used for Function V1. And we cannot remove it now unless with a major update, which unfortunately will not be provided in a short time. But since it's only for the Function V1, as long as you are using the Function V4, it shouldn't be a problem and the message could be ignored. Thanks!

**Comment by johannesoenema** [comment]
Hi @nytiannn. Thanks for helping me understand why some code is still there. I see indeed that some code paths are only used for Functions V1. I have still some questions regarding this, because if I look to the code and its dependencies then it still looks to me that the code is still used in Functions V4.

**For example** 
_Microsoft.AspNetCore.Mvc.WebApiCompatShim 2.2.0_

If I inspect where this nuget package is being used, it points me to the `DurableClient` and `LocalHttpListener`. The code of the `DurableClient` is used in the `CreateCheckStatusResponse` method of the `IDurableOrchestrationClient` interface. This code can still be used in version 4 as far as I can see.
![afbeelding](https://github.com/Azure/azure-functions-durable-extension/assets/12686691/a186c2a8-ecdc-4d34-b37e-d142852bbd4b)

![afbeelding](https://github.com/Azure/azure-functions-durable-extension/assets/12686691/a7312ce8-5886-4da2-a493-113a452b9f4d)

I see the same thing for the other packages. Maybe I missing something, I don't work on this code myself, but could you elaborate on this?

**Comment by johannesoenema** [comment]
I will close this issue. I found out that as long I will use `HttpRequestMessage` instead of `HttpRequest`, it will use the `CreateCheckStatusResponse` overload method that points to `System.Net.Http` (6.0.0) instead of the obsolete package `Microsoft.AspNetCore.Http` (2.2.0). When using v4 functions you would most likely pick the correct overload.

It would be great to get rid of obsolete packages, but I see why they are still needed here.

**Comment by StefanOverHaevgRZ** [comment]
@nytian @johannesoenema Would it be a big deal to release a major version of this package, without the old dependencies?
From the docs, the [v1 will be deprecated on September 14, 2026](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=isolated-process%2Cv4&pivots=programming-language-csharp) - that'd be the last date, someone could use the "legacy" version.
I think it would be a good incentive for every consumer to migrate to the new major version and be ready for that deprecation.

It might be a good idea to do this together with the .NET 8 release.

![image](https://github.com/Azure/azure-functions-durable-extension/assets/52310648/b2e56710-68ae-4649-a7b7-39ad48ede60a)
![image](https://github.com/Azure/azure-functions-durable-extension/assets/52310648/9368403a-8b9a-44be-8e96-e5b27686b14b)
![image](https://github.com/Azure/azure-functions-durable-extension/assets/52310648/051e0643-da6d-4109-bc80-8f142268e903)

**Comment by davidmrdavid** [comment]
Hi @StefanOverHaevgRZ: there's actually an effort in the works to release a new version of the Durable Extension that upgrades our Azure Storage SDK to V2 and, during planning, the suggestion of dropping old dependencies as part of this release was discussed. Unfortunately, due to our backwards compatibility obligations at this time, we're not doing that just yet.  

Once Functions V1 is deprecated in 2026, we should have another good opportunity to update our _static_ dependencies (at runtime you're getting up to date dependencies if you're in Functions V4).
