### ISSUE TITLE
Having useAppLease in host.json turned on causes orchestrator to get stuck on "pending" state

### ISSUE THREAD

**Issue by HaroutVTG** [Azure/azure-functions-durable-extension#2488]
### Description
> Having useAppLease in host.json turned on causes orchestrator to get stuck on "pending" state. The request is acknowledged by the HTTP Starter and a work item is created but doesn't get picked up by the orchestrator until after 15-20 minutes.

### Expected behavior
> All requests to get processed within the expected timeframe

### Actual behavior
> The orchestrator randomly forgets to pick up a work item from the hub for around 15-20 minutes cause huge delays. This happens approx. 1/6 times.

### Known workarounds
> Set useAppLease in host.json to false

### App Details

- **Azure Functions runtime version (1.0 or 2.0)**: 2
- **Programming language used**: Python

**Comment by nytiannn** [comment]
Hi, @HaroutVTG. This looks as a known bug which is a rare race condition during shutdown process. The related PR is [here](https://github.com/Azure/durabletask/pull/876). And this has been released with Durable Functions [v2.9.4](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v2.9.4). Please upgrade to the [latest versio](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/)n of Durable Function and the issue should be gone. Thanks!

**Comment by nytiannn** [comment]
Feel free to open it if you still have problems. Thanks!
