### ISSUE TITLE
need to update the way URL is treated

### ISSUE THREAD

**Issue by watashiSHUN** [Azure/azure-functions-durable-extension#25]
[here](https://github.com/Azure/azure-functions-durable-extension/blob/1f0b9bdb5619bc8f20ac81d24a9e0c47fa67a4d8/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L43-L54) `http://{host}/admin/extensions/DurableTaskConfiguration`
the assumption is that admin entry point's authorization model is anonymous

in the new [webjobs-sdk-script](https://github.com/Azure/azure-webjobs-sdk-script/pull/1659/commits/cbe3c28105361a3584fc6cc4f4e1041c44beffb8), 
we are enforcing systemkey level authorization

the new url:
`"{scheme}://{hostName}/admin/extensions/{extensionName}?code={keyValue}"`

probably need to sanitize these lines:
```
Uri statusQueryGetUri = new Uri(instancePrefix + "?" + querySuffix);
Uri sendEventPostUri = new Uri(instancePrefix + "/" + RaiseEventOperation + "/{eventName}?" + querySuffix);
Uri terminatePostUri = new Uri(instancePrefix + "/" + TerminateOperation + "?reason={text}&" + querySuffix);
```

**Comment by cgillum** [comment]
Thanks for reminding me about this - I like your suggestion.  I'll probably also need to look into supporting callers that pass in the code via the `x-functions-key` HTTP header.

**Comment by cgillum** [comment]
It turns out the system key is included in the web hook URL that the extension queries. I needed to update my code to ensure it doesn't get stripped out from the URLs that I generate for an instance. This is fixed in the latest release.
