### ISSUE TITLE
Function triggers but never executes when nuget package Worker.Extensions.DurableTask is referenced

### ISSUE THREAD

**Issue by Dohva** [Azure/azure-functions-durable-extension#2502]
### Description
Functions trigger but do not initialize and execute when Microsoft.Azure.Functions.Worker.Extensions.DurableTask is referenced in the .csproj file. Issue is consistent between versions 1.0.0 and 1.0.2.
Logs show that the function triggers, but breakpoints or logging in the relevant function constructor shows that it is never reached. Functions will time out when the time limit is hit, even when raised to an hour. No exceptions or otherwise error messages appear besides the time out.
Issue disappears when the nuget package is no longer referenced in .csproj file.

### Expected behavior
> The function executes or throws exception when triggered. Attempted with Http Trigger

### Actual behavior
> The function triggers and times out with no error message. (Besides the time out)

### Relevant source code snippets
No references made to any of the package's classes or interfaces. Only the package reference to Microsoft.Azure.Functions.Worker.Extensions.DurableTask

### Known workarounds
> Only disabling the package or removing it resolves the problem, but is no less blocking

### App Details
- **C# .net 7**
- **Azure Functions V4, isolated worker, output as Exe**
- **Microsoft.Azure.Functions.Worker v. 1.8.0**
- **Microsoft.Azure.Functions.Worker.Sdk v. 1.11.0**
- **Microsoft.Azure.Functions.Worker.Extensions.DurableTask v. 1.0.2** (also experienced with 1.0.0)
- **Registered AzureWebJobsServiceBusConnectionString to Service Bus in Azure** (after exceptions detailing the configuration as missing)
- **Running azurite**
- Everything running only locally, besides a Storage Account and Service Bus

**Comment by toffereins-stratusgroup** [comment]
I have just run into this issue and thought I would try my luck in checking the issue tracker to see if I wasn't alone and if there was a magic fix..
I spent the better part of the last 2 hours trying to troubleshoot and find the cause.

@Dohva I found that Microsoft.Azure.Functions.Worker v1.08 is the culprit. Moving to 1.09+ resolved this issue for me. I hope this works for you also.

**Comment by Dohva** [comment]
@toffereins-stratusgroup 
I just double checked my packages, and I'm already on 1.18.0.
My original issue has a typo in that regard, where it stated 1.8.0 instead.

Thank you for reaching out with your proposed solution.

**Comment by nytian** [comment]
Hi, I am sorry for the inconvenience. Would you mind provide me the DF app name, region and time stamp, and maybe orchestration instance Id that suffered from the issue? I can query and check what happened. Thanks!

**Comment by Dohva** [comment]
My problem was resolved on @toffereins-stratusgroup's suggestion.
