### ISSUE TITLE
 ASP.NET Core integration DurableTaskClient Issues

### ISSUE THREAD

**Issue by zachp-intec** [Azure/azure-functions-durable-extension#2508]
Either this is missing functionality or I just can't find the right method to use, but I'm struggling to figure out how to utilize Microsoft.Azure.Functions.Worker.DurableTaskClientExtensions.CreateCheckStatusResponse when I'm using HttpRequest and the only available input for CreateCheckStatusResponse is HttpRequestData.  Is there a workaround for this problem?  Also, seems like it's not supported functionality to utilize HttpRequest & HttpRequestData in the same project?  I don't need to use them both, but would like to find a reliable way to work with durable functions.

**Comment by jviau** [comment]
@zachp-intec the AspNetCore model for Functions dotnet isolated is still in preview and is a separate extension package. Durable is also its own GA'd extension package so we will not be adding an aspnetcore integration for a preview extension just yet. For the time being, you can perform a mapping from `HttpRequestData` to `HttpRequest`.

**Comment by zachp-intec** [comment]
Thanks @jviau!

**Comment by prashantagrawalcrowe** [comment]
@zachp-intec do have any workaround for this issue?
