### ISSUE TITLE
[QUERY] Webjob restarts durable function activity after crashing/restarting

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-functions-durable-extension#2524]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#18971](https://github.com/Azure/azure-sdk-for-net/issues/18971).

## Details

**Query/Question**
I have a Webjob (2.3.0) running some durable functions.  We had an issue where the machine was running out of memory and crashing.  The problem we're encountering is upon restarting the webjob kicks off the activity again, causing the webjob to crash again and it just repeats ad infinitum.  Our RetryOptions for each durable activity are set for a max of 2, but this is kicking off outside of that and we have no way to tell that the activity is being restarted.  In our case the activity will eventually succeed, but it ran a dozen times to get there and consumed a lot of resources along the way without us having any say in the matter.  

Is there a setting/strategy to handle this?  Ideally we can configure a retry strategy here, or at least have a way for the code to see how many times this method has been tried.

I can reproduce locally by simply putting a breakpoint and stopping the Webjob in the middle of a durable activity.  When I debug again and sometimes wait a few minutes the activity method will be called (but not the orchestrator).

**Environment:**
 - Azure.WebJobs 2.3.0 with Durable Functions
 - Azure AppService
 - Visual Studio 2019 16.8.4

**Comment by davidmrdavid** [comment]
@alexsegura1,  @KranthiPakala-MSFT  - This issue just got transferred to us, apologies for the great delay. Is this still an issue you need assistance with?

**Comment by alexsegura1** [comment]
hi @davidmrdavid yes it could still be useful if we had a way of dealing with this.

I'm not currently working on the team that operates that system anymore, if you could communicate with @johnwang16 that'd be great.

**Comment by davidmrdavid** [comment]
Hi @johnwang16, do you have a minimal reproducer for this issue that you could share with us?
