### ISSUE TITLE
Unable to trigger durable azure function

### ISSUE THREAD

**Issue by mksp2016** [Azure/azure-functions-durable-extension#2527]
### Description

We have created azure function app and deployed durable function to it, however when we are testing it, it throws following error

Result: Failure Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'Function1_HttpStart': Cannot convert input parameter 'client' to type 'Microsoft.DurableTask.Client.DurableTaskClient' from type 'System.String'. Error:System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Microsoft.DurableTask.Client.DurableTaskClient'. Path: $ | LineNumber: 0 | BytePositionInLine: 1. ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Microsoft.DurableTask.Client.DurableTaskClient'. --- End of inner exception stack trace --- at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, NotSupportedException ex) at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(Type type, Utf8JsonReader& reader, ReadStack& state) at System.Text.Json.Serialization.Converters.ObjectDefaultConverter1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) at System.Text.Json.Serialization.JsonConverter1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value) at System.Text.Json.Serialization.JsonConverter1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) at System.Text.Json.Serialization.JsonConverter1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state) at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state) at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo) at System.Text.Json.JsonSerializer.ReadFromStreamAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken) at Microsoft.Azure.Functions.Worker.Converters.JsonPocoConverter.GetConversionResultFromDeserialization(Byte[] bytes, Type type) in D:\a_work\1\s\src\DotNetWorker.Core\Converters\JsonPocoConverter.cs:line 66 at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 100 at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 41 at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13 at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 82 Stack: at Microsoft.Azure.Functions.Worker.Context.Features.DefaultModelBindingFeature.BindFunctionInputAsync(FunctionContext context) in D:\a_work\1\s\src\DotNetWorker.Core\Context\Features\DefaultModelBindingFeature.cs:line 100 at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a_work\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 41 at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a_work\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13 at Microsoft.Azure.Functions.Worker.Handlers.InvocationHandler.InvokeAsync(InvocationRequest request) in D:\a_work\1\s\src\DotNetWorker.Grpc\Handlers\InvocationHandler.cs:line 82

### Expected behavior
> Function should get triggered 

### Actual behavior
> Getting error while triggering 
 _Result: Failure Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'Function1_HttpStart': Cannot convert input parameter 'client' to type 'Microsoft.DurableTask.Client.DurableTaskClient' from type 'System.String'. Error:System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Microsoft.DurableTask.Client.DurableTaskClient'._

### Relevant source code snippets
```csharp

         /// <summary>
        ///  Azure Function to start the InventoryProcessingJob
        /// </summary>
        /// <returns></returns>
        [Function("Function1_HttpStart")]
        public async Task<HttpResponseData> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
            [DurableClient] DurableTaskClient client,
            FunctionContext executionContext)
        {
            // Function input comes from the request content.
            string instanceId = await client.ScheduleNewOrchestrationInstanceAsync(
                nameof(InventoryProcessingJob));

            _logger.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);

            // Returns an HTTP 202 response with an instance management payload.
            // See https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-http-api#start-orchestration
            return client.CreateCheckStatusResponse(req, instanceId);
        }
```
  
### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
- **Azure Functions runtime version (1.0 or 2.0)**:
- **Programming language used**:
**Details for function app:** 

![image](https://github.com/MicrosoftDocs/azure-docs/assets/34733888/841d63e5-e5cf-42ff-b2d2-f674a595a3cb)

![image](https://github.com/MicrosoftDocs/azure-docs/assets/34733888/0fc31fd3-c1fc-4a0c-a389-18b8f0419c78) 

### Screenshots
![image](https://github.com/Azure/azure-functions-durable-extension/assets/34733888/9cc887fb-1e9a-4340-802d-33ac425c2aa3)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**: 
- **Function name(s)**: Function1_HttpStart 
- **Azure region**: East US
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by ltouro** [comment]
Shouldn't you use `IDurableOrchestrationClient` instead `DurableTaskClient` directly?

i.e.:
```
[FunctionName("GetAllStatus")]
public static async Task Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestMessage req,
    [DurableClient] IDurableOrchestrationClient client,
    ILogger log)
{
    var noFilter = new OrchestrationStatusQueryCondition();
    OrchestrationStatusQueryResult result = await client.ListInstancesAsync(
        noFilter,
        CancellationToken.None);
    foreach (DurableOrchestrationStatus instance in result.DurableOrchestrationState)
    {
        log.LogInformation(JsonConvert.SerializeObject(instance));
    }
    
    // Note: ListInstancesAsync only returns the first page of results.
    // To request additional pages provide the result.ContinuationToken
    // to the OrchestrationStatusQueryCondition's ContinuationToken property.
}
``` 

[source](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp)

**Comment by mksp2016** [comment]
> Shouldn't you use `IDurableOrchestrationClient` instead `DurableTaskClient` directly?
> 
> i.e.:
> 
> ```
> [FunctionName("GetAllStatus")]
> public static async Task Run(
>     [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestMessage req,
>     [DurableClient] IDurableOrchestrationClient client,
>     ILogger log)
> {
>     var noFilter = new OrchestrationStatusQueryCondition();
>     OrchestrationStatusQueryResult result = await client.ListInstancesAsync(
>         noFilter,
>         CancellationToken.None);
>     foreach (DurableOrchestrationStatus instance in result.DurableOrchestrationState)
>     {
>         log.LogInformation(JsonConvert.SerializeObject(instance));
>     }
>     
>     // Note: ListInstancesAsync only returns the first page of results.
>     // To request additional pages provide the result.ContinuationToken
>     // to the OrchestrationStatusQueryCondition's ContinuationToken property.
> }
> ```
> 
> [source](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management?tabs=csharp)

That's for web jobs.

We are following below documentation 
https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-isolated-create-first-csharp?pivots=code-editor-vscode

**Comment by jviau** [comment]
@mksp2016 this is a known issue where source generators are not running in your build, and the durable extension is not being registered at startup. You need to either:

1. Fix source generation
2. Manually add a call to `DurableTaskExtensionStartup.Configure`

**Comment by arunchackot** [comment]
Faced similar issue and was following MS article on Durable function while working with an existing solution.

Was able to resolve this issue by upgrading below package:

`<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" OutputItemType="Analyzer" />`

Hope this helps!

**Comment by ebuljan** [comment]
@ elephantrider98 Did you find the answer?  We have the same issue.

**Comment by jviau** [comment]
@elephantrider98 there are a couple issues with your startup, below is what I recommend:

``` CSharp
using Microsoft.DurableTask.Client;
using Microsoft.DurableTask.Converters;
using Microsoft.DurableTask.Worker;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(IFunctionsWorkerApplicationBuilder builder => new DurableTaskExtensionStartup().Configure(builder)) // this is the important call to make if source gen is not working for you.
    .ConfigureAppConfiguration((hostContext, configApp) =>
    {
        configApp.AddEnvironmentVariables()
    })
    .Build();

host.Run();
```

**Comment by elephantrider98** [comment]
@jviau thank you! This unblocked our function startup after implementing your suggestion.

**Comment by cgillum** [comment]
Note for future viewers: at this point in time, calling `new DurableTaskExtensionStartup().Configure(builder)` should NOT be used. The durable extension should be getting registered automatically. If you add this line of code to your Program.cs anyways, it will cause various problems with function processing.

**Comment by vakuras** [comment]
@cgillum How to make durable extension register automatically?

We've just started to migrate to isolated durable functions and we face the same issue as above.

**Comment by elephantrider98** [comment]
@vakuras  echoing @cgillum above, we now no longer need the explicit call for registration. The following works for our startup.

```            
var host = Host.CreateDefaultBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .Build();

return host.RunAsync();
```
