### ISSUE TITLE
Event Grid data payload should use lowercase letters

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#253]
I noticed the code uses upper-case field names, which is inconsistent with the rest of the Azure Event Grid payload JSON:

```csharp
Data = new
{
    HubName = hubName,
    FunctionName = functionName,
    Version = version,
    InstanceId = instanceId,
    Reason = reason,
    EventType = orchestrationRuntimeStatus,
},
```
I suggest we make these lowercase for consistency. We should also get rid of the `Version` field since that is not used.

Here is what I think it would look like in C#:

```csharp
Data = new
{
    hubName = hubName,
    functionName = functionName,
    instanceId = instanceId,
    reason = reason,
    eventType = orchestrationRuntimeStatus,
},
```

**Comment by TsuyoshiUshio** [comment]
@cgillum Ok. I'll fix soon.

**Comment by cgillum** [comment]
I'm just talking about the `Data` field.  In your outer data contract, you used `[JsonProperty]` to set all the field names to lowercase. however, the fields inside `Data` will not be lowercased since it's a dynamic type and cannot use `[JsonProperty]` (which is why you just have to make the dynamic field members lowercase). I'm not sure if that's what you were referring to when you mentioned how the Event Grid trigger works.

BTW, if you can submit a PR today then I can merge it tomorrow PDT and we can release without any breaking change.

**Comment by TsuyoshiUshio** [comment]
@cgillum  I sent a pull request. Please have a look. 

https://github.com/Azure/azure-functions-durable-extension/pull/259

**Comment by cgillum** [comment]
Looks great - I'll include that in the release. Thanks!
