### ISSUE TITLE
Documentation for Azure Event Grid publishing

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#254]
Let's add a documentation page on docs.microsoft.com which covers the basics of how to set up Azure Event Grid publishing from Durable Functions. This should include a step-by-step guide that includes:

* How to configure publishing in host.json
* How to create the custom Event Grid topic
* How to write an Azure Function which listens to the custom events
* How to test locally

It's okay if some of these points link to existing documentation on docs.microsoft.com.

**Comment by TsuyoshiUshio** [comment]
@cgillum  Sure. I'll talk with the Documentation team and do it.

**Comment by TsuyoshiUshio** [comment]
@cgillum  I start writing the documentation. Not finished. however, please have a look for overview review. Then I'll correct the strategy and write `How to test locally` section. 
https://github.com/MicrosoftDocs/azure-docs-pr/pull/38541
