### ISSUE TITLE
Durable Functions Hang When Distributed Tracing is Enabled

### ISSUE THREAD

**Issue by danielmackay** [Azure/azure-functions-durable-extension#2542]
### Description
When using Azure Durable Functions, the runtime hangs after a certain number of activity function executions.  We've noticed this to be consistently 29 executions.

### Expected behavior
Orchestrator functions should be able to execute any number of activity functions and complete successfully

### Actual behavior
Orchestrator function hangs after 29 activity function executions

### Relevant source code snippets
Sample repository demonstrating issue: https://github.com/danielmackay/azure-durable-function-distributed-tracing-bug

### Known workarounds
disabling `extensions.durableTask.tracing.distributedTracingEnabled` in `host.json` resolves the issue.

### App Details

```xml
      <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.21.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.19.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="1.0.0-preview5" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.1.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.12.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.14.0" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.0.2" />
      <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.2.0" />
      <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
```

- **Durable Functions extension version (e.g. v1.8.3)**: see above
- **Azure Functions runtime version (1.0 or 2.0)**: v4
- **Programming language used**: C#
- **.NET version used**: 7.0.200

### Screenshots
Always stops at this `TaskEventId` and `SequenceNumber`

![image](https://github.com/Azure/azure-functions-durable-extension/assets/2636640/d21f8523-8931-49d1-9836-be4cfedb36c5)

**Comment by lilyjma** [comment]
thanks for raising the issue @danielmackay - I noticed that you're using an older version of the Durable Functions extension. We're now at v2.10.0. Could you try upgrading to the [latest version](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/2.10.0) and see if this problem persists? If yes, please let us know. Thanks!

**Comment by guudan** [comment]
Have same issue.

I am using the durable function in the dotnet isolated Azure Function running on .Net 4.8. Therefore I am utilizing following nuget package:
https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.DurableTask/1.0.2

I found following exception in my logs:
```
TaskActivityDispatcher-498319e8ce9b48fba75b5521a0286778-0: Failed to fetch a work-item: Newtonsoft.Json.JsonReaderException: The reader's MaxDepth of 64 has been exceeded. Path 'OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[1].OrchestrationTraceContexts[0]', line 1, position 9934.
   at Newtonsoft.Json.JsonReader.Push(JsonContainerType value)
   at Newtonsoft.Json.JsonReader.SetToken(JsonToken newToken, Object value, Boolean updateIndex)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at DurableTask.Core.TraceContextBase.Restore(String json) in /_/src/DurableTask.Core/TraceContextBase.cs:line 181
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.<>c__DisplayClass91_0.<LockNextTaskActivityWorkItem>b__0() in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs:line 1378
   at DurableTask.AzureStorage.AzureStorageOrchestrationService.LockNextTaskActivityWorkItem(TimeSpan receiveTimeout, CancellationToken cancellationToken) in /_/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs:line 1372
   at DurableTask.Core.WorkItemDispatcher`1.DispatchAsync(WorkItemDispatcherContext context)
```

**Comment by davidmrdavid** [comment]
@bachuv ^

**Comment by davidmrdavid** [comment]
Hey @guudan: in case you're still experiencing this issue, could you please open a new ticket? Thanks!

**Comment by magarma** [comment]
I'm having the same issue. After some activities and DistributedTracingEnabled, the function hangs
In my case .Net 8, isolated functions.
![image](https://github.com/user-attachments/assets/8c5f3c4e-0499-4bdc-bb0c-4abe3d9e9605)
