### ISSUE TITLE
Documentation for custom orchestration status

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#255]
We need documentation on docs.microsoft.com that covers custom status reporting from an orchestrator function. This will include the following:

- [x] New topic page which covers the feature (when to use it, how to use it, limitations, etc.)
- [x] Update existing [HTTP API](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-http-api#get-instance-status) article to reference the new fields in the Get Status response payload
- [x] Update the [Instance Management](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-instance-management) article to reference the new fields/APIs
- [x] Update the [Diagnostics](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-diagnostics) article to reference the new `customStatus` field.

**Comment by gled4er** [comment]
Hello @cgillum,

I am interested in helping with this issue. 

If this is ok with you, may I ask you to share directions about the feature - when to use it, how to use it, limitations, etc.?

I will be happy to expand them and work on the page. 

Thank you!

**Comment by cgillum** [comment]
Thanks, that would be great! You can find more details here: https://github.com/Azure/azure-functions-durable-extension/pull/193

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you very much for the link!

**Comment by gled4er** [comment]
Hello @cgillum,

Do we need to pass `customState` to the methods in `EtwEventSource` and `EndToEndTraceHelper` in order to be visible in the Diagnostics? Because currently this is not happening.

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you for the clarification.

**Comment by cgillum** [comment]
Looks like we forgot to update the Diagnostics page. That's okay for now. We can do it post-GA.

**Comment by gled4er** [comment]
Hello @cgillum,

I can do it now. Just can you clarify what should be the change for it? We are not passing Custom Status to the tracking methods.

Thank you!

**Comment by cgillum** [comment]
Sure, if you have time.

The idea is to add a short section describing tips about how you can add richer monitoring to your orchestrator function using custom status. For example, showing how you can add `SetCustomStatus` calls to indicate progress for some long-running operation, and then query that progress using the HTTP status query APIs (e.g. a web page could be checking this status and displaying it to an end-user).

No need to go into details. Maybe include the simplest possible sample function that is just a few short lines of code. We just need to describe the general idea, add a super-trivial sample code snippet, and list one or two possible use-cases to help developers think about how this might be helpful to them.

**Comment by gled4er** [comment]
Hello @cgillum,

Got it! 

I will work on that next.

Thank you!

**Comment by gled4er** [comment]
Hello @cgillum,

When you have time please check this PR - https://github.com/MicrosoftDocs/azure-docs-pr/pull/39707 and let me know what should be fixed next?

Thank you!
