### ISSUE TITLE
String payloads are escaped differently between 1.0.2 and 1.0.3

### ISSUE THREAD

**Issue by plamber** [Azure/azure-functions-durable-extension#2581]
### Description
We recently upgraded to Microsoft.Azure.Functions.Worker.Extensions.DurableTask version 1.0.3 a few days ago, and unfortunately, we encountered the same issue that was previously reported in issue #2577. Although a hotfix was applied to #2577, it led to unexpected behavior where the JSON data is now being read but with escaped characters like \\u0022. This is a departure from the behavior we observed in version 1.0.2.

An example of the JSON input before.
```
"{\"id\":\"73debd7d-e710-41cf-9388-9817c8efa517\"}"
````

### Expected behavior
The serialization of 1.0.3 behaves the same as 1.0.2 since I assume it shouldn't contain a breaking change. 

### Actual behavior
Instead of returning the payload 

```
"{\"id\":\"73debd7d-e710-41cf-9388-9817c8efa517\"}"
````

it returns the payload with an escaping

```
"{\\u0022id\\u0022:\\u002273debd7d-e710-41cf-9388-9817c8efa517\\u0022}"
````

### Relevant source code snippets
```csharp
// initiating the payload
var payload = "{\"id\":\"73debd7d-e710-41cf-9388-9817c8efa517\"}";
String instanceId = await client.ScheduleNewOrchestrationInstanceAsync("Orchestrator", payload);

// in the orchestrator reading the payload
public async Task<List<string>> RunOrchestrator([OrchestrationTrigger] TaskOrchestrationContext context)
{
        string? requestJson = context.GetInput<string>();
}
```

### Known workarounds
Downgrade to 1.0.2

**Comment by davidmrdavid** [comment]
Thanks for the report, we should have caught this. The team is working on a hotfix now.

**Comment by jviau** [comment]
This has been addressed. The root issue is we were double serializing the input due to a recent change. That change has been reverted. To get the updated changes, you need only re-build your function app and it should pick up the latest webjobs extension (`2.11.3`)

**Comment by plamber** [comment]
Thank you
