### ISSUE TITLE
Spelling mistake in error log

### ISSUE THREAD

**Issue by abhi-markan** [Azure/azure-functions-durable-extension#2588]
### Description
> When a durable function encounters an error or catches an exception, an error message in thrown with a spelling mistake.

### Expected behavior
`Updating FunctionsHostingConfigurations...`

### Actual behavior
`Updaiting FunctionsHostingConfigurations...`

### Relevant source code snippets
```shell
 Updaiting FunctionsHostingConfigurations 'RecycleOn50031=1,PatchStackifyIssue=1,FunctionsSyncTriggersDelaySeconds=60,FunctionsSyncTriggersDelayBackground=1,RunDiagnosticAnalysisInDaaS=1,MemoryDumpOnProactiveAutoHeal=1,microsoft.azure.webjobs.extensions.storage.queues=1,microsoft.azure.webjobs.extensions.servicebus=1,Microsoft.Azure.WebJobs.Extensions.CosmosDB=1,Microsoft.Azure.WebJobs.Extensions.EventHubs=1,DisableLinuxExecutionDetails=1,WORKER_INDEXING_ENABLED=1,EnsureGitSafeDirectoryEnabled=1'
```

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 1.5.4
- **Azure Functions runtime version (1.0 or 2.0)**:  3.8.2.0
- **Programming language used**: Node

### Screenshots
N/A

### If deployed to Azure
N/A

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by davidmrdavid** [comment]
Thanks @abhi-markan. Hmm, I don't immediately recognize this log. Are you sure this is a durable functions issue? Might be from the Azure Functions runtime itself.

**Comment by abhi-markan** [comment]
Hello,

It well could be from Azure Functions runtime.

Thanks
