### ISSUE TITLE
Versions 2.11.x unlisted on nuget

### ISSUE THREAD

**Issue by mlankamp** [Azure/azure-functions-durable-extension#2592]
Why are the versions 2.11.1/2/3 unlisted from nuget?

See: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/2.11.3

**Comment by cgillum** [comment]
Each of these nuget packages contained regressions that were significant enough that we needed to take down these versions. The team is working on some changes that will allow us to publish a 2.11.4 relatively soon.

**Comment by mlankamp** [comment]
Clear. Maybe post a notice somewhere (issue or readme).

**Comment by cgillum** [comment]
Pinned this issue for increased visibility.

**Comment by mlankamp** [comment]
@cgillum maybe remove this pinned issue, new version2.12.0 is out
