### ISSUE TITLE
Non-deterministic workflow failure during slot deployment

### ISSUE THREAD

**Issue by mitchellrust** [Azure/azure-functions-durable-extension#2635]
We have seen occasional failures in our orchestrations during deployment to our function apps, using slot deployments. This does not occur on every deployment, but we've seen it repeated multiple times.

The error message is as follows:

`Non-Deterministic workflow detected: A previous execution of this orchestration scheduled an activity task with sequence ID 0 and name 'DetectARInvoiceChanges' (version ''), but the current replay execution hasn't (yet?) scheduled this task. Was a change made to the orchestrator code after this instance had already started running?`

Here is the scenario that we see this happening in:
- Our function app uses slot deployments to minimize downtime during deployments, with two slots: `staging` and `production`.
- Each of our slots have their own task hubs, with their own control queues and tables. These are all contained in the same Azure Storage Account. We've defined this in our app settings for the `production` and `stage` slots individually.
- During a slot deployment, there could be any number of orchestrations in the middle of executing on our `production` slot, or waiting for scheduled activity tasks to complete before resuming.
  - We have seen this failure exclusively when an orchestration is awaiting the completion of a scheduled activity task.
- During the "Slot Swap" step of our slot deployment, we have seen in logs that orchestrations awaiting activity completions get resumed in the `staging` slot. This doesn't make a ton of sense, as we wouldn't expect any tasks to be scheduled on the `staging` slot control queues, but perhaps something in the app-settings switch causes things to cross over here.

Based on our scenario and what the logs have shown us, it seems that our `staging` slot is resuming orchestrations somehow, and naturally can't find the history for the orchestration because that all exists in the `production` slot task hub. This seems to be nuance specific to using the slot deployments, from what we can tell.

**Comment by davidmrdavid** [comment]
Hi @mitchellrust: Thanks for reaching out. My best guess here is that, while your swap slot was taking place, there was probably already a request-message to replay your orchestrator enqueued in your staging slot's control queue. That would prompt a replay irrespective of the swap. After all, in a swap, we don't actually move the underlying storage resources (like the queues), only the slot config and application code.

@cgillum: I'm curious if you'd agree this is a likely explanation. I wonder if this is an underlying risk based on how the slot swap works.

**Comment by cgillum** [comment]
@mitchellrust can you tell us more about how your task hubs are configured? For example, are they hardcoded in host.json or do you assign it using an app setting (and if so, is it a slot-sticky app setting)?

**Comment by mitchellrust** [comment]
@cgillum sorry for the delay, been working with Microsoft support on this but with no luck. We utilize an app-setting to assign the task hub name for our function app, `AzureFunctionsJobHost__extensions__durableTask__hubName`. This is a sticky deployment slot setting, yes. We don't have any configuration for our tasks hubs in our host.json file at all, it is all done by app-settings. The app-setting for our staging slot hub name has been hardcoded completely differently from the production function app.

@davidmrdavid thanks for the explanation! What I'm struggling to understand though is how any messages could be enqueued in our staging slot's control queues to begin with. Any of the in-flight orchestrations prior to the swap would be running on the production slot only, and at no point do we start an orchestration instance in our staging slot. I may very well be missing some key context on how the slot swap process works that would result in this, am I misunderstanding?

**Comment by mitchellrust** [comment]
Here is our MS case tracking ID as well for this issue: 2310310040011442

**Comment by mitchellrust** [comment]
I've opened a new issue for this #2696
