### ISSUE TITLE
Nuget install crashed Visual Studio

### ISSUE THREAD

**Issue by envoy-mcapodici** [Azure/azure-functions-durable-extension#265]
It gets stuck after this, I need to kill VS after this happens:

PM> install-package Microsoft.Azure.WebJobs.Extensions.DurableTask -PreRelease
  GET https://api.nuget.org/v3/registration3-gz-semver2/microsoft.azure.webjobs.extensions.durabletask/index.json
  OK https://api.nuget.org/v3/registration3-gz-semver2/microsoft.azure.webjobs.extensions.durabletask/index.json 213ms
Restoring packages for C:\Users\xyz\xyz.csproj...
Installing NuGet package Microsoft.Azure.WebJobs.Extensions.DurableTask 1.3.1-rc.

VS 2017 15.4.0

**Comment by cgillum** [comment]
Do other packages work? Or other versions of this package? My guess is that this is an issue with your version of nuget and/or Visual Studio and not an issue with Durable Functions. Which version of nuget do you have installed?

**Comment by envoy-mcapodici** [comment]
Yes other packages work, We use a lot of packages from different vendors and a lot of Azure packages and had no problems with them. 

Earlier versions of the same package have the same problem.

Package Manager Console Host Version 4.4.0.4475
Nuget Version 4.4.0

**Comment by cgillum** [comment]
Would you mind opening an issue directly to Visual Studio and mentioning our package? Unfortunately I'm not really equipped to debug Visual Studio crashes. They will probably need to collect some traces from you as well. 

Our package doesn't have any internal hooks into VS, so there is no excuse for VS to crash.
