### ISSUE TITLE
Overview of function-to-function communication

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#266]
It would be useful to have a single topic which covers function-to-function communication. Information about this is currently scattered throughout, and it would be nice to have a landing page which covers this as a dedicated topic, linking out to related documents as necessary.

Categories to describe would include the following:

- [x] **Orchestration triggers**: This is all about how to start orchestrator functions. We should show examples of using HTTP triggers, Service Bus triggers, and Timer triggers as we get questions about non-HTTP triggers quite a bit. We should also mention that users can either rely on the auto-generated instance ID (recommended) or a user-specified instance ID. Alternatively, we could link to the existing instance management topic and add more examples there.
- [x] **Calling activity functions**: Basic examples, including notes about how the binding rules work.
- [x] **Calling sub-orchestrations**: Basic description plus a link to the sub-orchestrations topic.
- [x] **Multiple parameters and return values**: Includes tips for using arrays, custom types, or C# ValueTuples.
- [x] **Error handling**: Basic description of how exceptions work and that retry policies can be leveraged. Should link to the relevant section of the diagnostics topic, where the detailed content will live.
- [x] **External events**: Basic description of raising events to orchestrator functions. Should link to the existing article. That article should be improved to describe some of the improvements around listening to multiple events sequentially or concurrently, since these are important enterprise messaging patterns.
- [x] **Cross function app communication**: Explain how this can't be done directly, but give instructions on how this can be done indirectly (e.g. using async HTTP patterns). There is an existing GitHub issue which goes over this in more detail.

**Comment by jeffhollan** [comment]
Created fork of docs and working on this now

**Comment by jeffhollan** [comment]
@cgillum a few questions while I do this.  

* What is the cross function app communication story? As far as I knew the only way to do this would be an indirect method (HTTP, Queue).  Is there something in the extension that makes this possible?

* For multiple values / return types, are you saying it would be supported to do something like:
  ```csharp
       (string, int) response = await context.CallActivityAsync("myFunction", someValue);
  ```
   As long as my activity function returned a ValueTuple as well?

**Comment by cgillum** [comment]
For cross function app communication, I suggest taking a look through this thread, which has some good information and example code: https://github.com/Azure/azure-functions-durable-extension/issues/156

Regarding multiple values, yes, ValueTuple would need to be used on both ends. Kanio wrote a blurb on this as part of our GA push: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-bindings#passing-multiple-parameters. However, it's currently in the Binding docs which is not particularly discoverable, so it's probably worth migrating over to your doc.

**Comment by jeffhollan** [comment]
One other question I have had - if I have an activity function that doesn't really need an input, I assume I still need to give a type?  I usually just so something like `[ActivityTrigger] string data` and pass in `null` from the orchestrator.  But looking at doc linked above wonder if best practice would be passing in `DurableActivityContext` and just not retrieving inputs.  

Clarifying as figure this section could include things like passing in no parameters, passing in one parameter, passing in multiple parameters (I assume via ValueTuple as shown in doc) -- and similarly for return values (void, single, ValueTuple)

**Comment by cgillum** [comment]
I think using `DurableActivityContext` should be considered best practice for the "no inputs" case, though it shouldn't really make any difference. Unfortunately Azure Functions doesn't really support "no-parameter" functions as a first-class thing. :)

**Comment by jeffhollan** [comment]
Sent an email with review link

**Comment by jeffhollan** [comment]
Just edited the docs and signed off for merge. Hopefully will publish tomorrow

**Comment by cgillum** [comment]
https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-types-features-overview
