### ISSUE TITLE
Worker Activity string parameter gets wrapped in escaped quotes.

### ISSUE THREAD

**Issue by marked23** [Azure/azure-functions-durable-extension#2677]
### Description
My Orchestrator calls an Activity while passing in a string parameter.  When that string arrives in the Activity method, it is wrapped in escaped quotes. 

### Expected behavior
The string should be the same value as it was when the caller sent it.  
`"foobar"  ->  "foobar"`

### Actual behavior
When the string arrives in the Activity, it's wrapped in escaped quotes.
`"foobar"  ->  "\"foobar"\"`

### Relevant source code snippets
```csharp
public async Task Orchestrator(...)
{
    string nextUrl = "foobar";
    nextUrl = await context.CallActivityAsync<string>(nameof(GetNextUrl), nextUrl, options);
}

public async Task<string?> GetNextUrl([ActivityTrigger] string givenUrl, FunctionContext executionContext)
{
     // givenUrl contains "\"foobar"\"
}
```

### Known workarounds
```csharp
if (givenUrl.StartsWith("\"") || givenUrl.EndsWith("\"") ) 
{
    givenUrl = givenUrl.TrimStart(new[] { '\\', '"' });
    givenUrl = givenUrl.TrimEnd(new[] { '\\', '"' });
}
```

### App Details

- **Microsoft.Azure.Functions.Worker**: 1.20.0  
- **Microsoft.Azure.Functions.Worker.Sdk**: 1.16.2  
- **Microsoft.Azure.Functions.Worker.Extensions.DurableTask**: 1.1.0  
- **Azure Functions runtime version (1.0 or 2.0)**:  4.27.5.21554
- **Azure Functions Core Tools**: 4.0.5455  

- **Programming language used**:  C# in dotnet 6

### If deployed to Azure
Running locally.

**Comment by lukecusolito** [comment]
@marked23 I have the same issue, another workaround until a fix is available is to downgrade to `1.1.0-preview.2` this resolved it for me

**Comment by betim-raqi** [comment]
I have the same problem, downgrading `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` to version **1.0.4** seem to work

**Comment by Tiktack** [comment]
Facing same problem. Downgrade to 1.0.4 helped.

**Comment by tgskiman** [comment]
I am experience this and noticed that it is also escaping characters in the string (e.g.: " becomes \")
