### ISSUE TITLE
Isolated durable entities: SignalEntityAsync payload is not unserialized using the provided custom serializer

### ISSUE THREAD

**Issue by RemyBoyer** [Azure/azure-functions-durable-extension#2679]
### Description

When overriding `WorkerOptions.Serializer`, the custom serializer is used when serialising the *SignalEntityAsync* payload to the worker.
On the worker though, the deserialization does not use the custom Serializer.

### Expected behavior

I expect that the override of `WorkerOptions.Serializer` should work everywhere, including in the durable entities, as stated in the documentation [here](https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-serialization-and-persistence?tabs=csharp-isolated#customizing-serialization-and-deserialization): 

> Durable Functions running in the [.NET Isolated worker process](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) uses the same object-serializer configured globally for your Azure Functions app (see [WorkerOptions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.workeroptions)). This serializer happens to be [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json) by default rather than Newtonsoft.Json. Any changes to WorkerOptions.Serializer will transitively apply to Durable Functions.

### Actual behavior

The deserialization may fail since it's not using the same serializer when serializing and deserializing.
In the code below, the error is, for example:

```
Exception while executing function: Functions.MyEntity. Microsoft.Azure.WebJobs.Extensions.DurableTask: The JSON value could not be converted to MyEnum. Path: $ | LineNumber: 0 | BytePositionInLine: 3.
```

### Relevant source code snippets
```csharp
using Azure.Core.Serialization;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.DurableTask.Client;
using Microsoft.DurableTask.Entities;
using Microsoft.Extensions.Hosting;
using System.Text.Json;
using System.Text.Json.Serialization;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults(options =>
    {
        var jsonOptions = new JsonSerializerOptions()
        {
            PropertyNameCaseInsensitive = true,
        };
        jsonOptions.Converters.Add(new JsonStringEnumConverter());

        options.Serializer = new JsonObjectSerializer(jsonOptions);
    })
    .Build();

host.Run();

public static class Function1
{
    [Function("Function1_HttpStart")]
    public static async Task HttpStart(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
        [DurableClient] DurableTaskClient client)
    {
        var entityId = new EntityInstanceId("MyEntity", Guid.NewGuid().ToString());
        await client.Entities.SignalEntityAsync(
            entityId,
            "Initialize",
            MyEnum.B);
    }
}

public class MyEntity
{
    public void Initialize(MyEnum e)
    {
    }

    [Function(nameof(MyEntity))]
    public static Task CounterEntity([EntityTrigger] TaskEntityDispatcher dispatcher)
    {
        return dispatcher.DispatchAsync<MyEntity>();
    }
}

public record InitializeRequest(MyEnum e);

public enum MyEnum { A, B };
```

### Known workarounds

I've dug into the source code and found that the issue resides at least in [TaskEntityDispatcher](https://github.com/Azure/azure-functions-durable-extension/blob/edb6648938d51e4d960706ece9f2b2126f242b60/src/Worker.Extensions.DurableTask/TaskEntityDispatcher.cs#L43C75-L43C75).

The [GrpcRunner](https://github.com/microsoft/durabletask-dotnet/blob/b12cd675b6260b47dbe6a5fa3866f71784fa81e9/src/Worker/Grpc/GrpcEntityRunner.cs#L53C81-L53C81) accepts an `IServiceProvider`, that isn't supplied by `TaskEntityDispatcher`. 

This ends up using `DurableTaskShimFactory.Default` that does not use the `DurableTaskWorkerOptions` `DataConverter`:

```csharp
        DurableTaskShimFactory factory = services is null
            ? DurableTaskShimFactory.Default
            : ActivatorUtilities.GetServiceOrCreateInstance<DurableTaskShimFactory>(services);
```

Changing `TaskEntityDispatcher` to send the `IServiceProvider` to `GrpcEntityRunner` fixed the issue in my tests. But there might be more issues (or other ways to fix it).

### App Details

```
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.2" />
```

```
Azure Functions Core Tools
Core Tools Version:       4.0.5455 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.27.5.21554
```

### Screenshots

Not really useful

**Comment by sebastianburckhardt** [comment]
Thanks for reporting this!

Your analysis and your suggested fix look right to me. I have created a PR #2686.
