### ISSUE TITLE
Isolated Process with DurableClient and ASP.NET Core integration will throw exception on CreateCheckStatusResponse

### ISSUE THREAD

**Issue by Duranom** [Azure/azure-functions-durable-extension#2683]
**Description**
Packages:
- [Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore v1.1.1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore/1.1.1)
- [Microsoft.Azure.Functions.Worker.Extensions.DurableTask v1.1.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.DurableTask/1.1.0)

When using the version of the functions packages that provides ASP.NET Core integration and DurableTaskClient, the method `[CreateCheckStatusResponse](https://github.com/Azure/azure-functions-durable-extension/blob/3dd943bc227f5e63a58c3b585400669accd636d7/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs#L46C24-L46C24)` will throw an InvalidOperationException because the implementation writes to the `HttpResponseData` synchronous

**Expected behavior**
There should be no exception thrown, however as synchronous writing is not allowed since ASP.NET Core 3+ a Async version will be needed to be exposed.

**Actual behavior**
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead
```
Result: An unhandled exception occurred.
Exception: System.AggregateException: One or more errors occurred. (Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.)
  ---> System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    at Azure.Core.Serialization.JsonObjectSerializer.Serialize(Stream stream, Object value, Type inputType, CancellationToken cancellationToken)
    at Microsoft.Azure.Functions.Worker.DurableTaskClientExtensions.CreateCheckStatusResponse(DurableTaskClient client, HttpRequestData request, String instanceId, HttpStatusCode statusCode, CancellationToken cancellation) in /_/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:line 97
    at Microsoft.Azure.Functions.Worker.DurableTaskClientExtensions.CreateCheckStatusResponse(DurableTaskClient client, HttpRequestData request, String instanceId, CancellationToken cancellation) in /_/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:line 34
```

### Relevant source code snippets
```csharp
[Function("SimpleHttpTriggerHttpData")]
public async Task<HttpResponseData> Run(
[HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestData req,
[DurableClient] DurableTaskClient durableClient)
{
       return durableClient.CreateCheckStatusResponse(req, "FakeId"); //Will result in exception
}
```

**Known Workarounds**
The following configuration is possible, however this would be rather avoided
```
services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
```

**Other information**
When using ASP.NET Core integration it would be nice to also have a `CreateCheckStatusResponse` version that accepts `HttpRequest` and returns an `ActionResult` to keep it more consistent with the HttpTriggers.

**Comment by jviau** [comment]
@Duranom the `CreateCheckStatusResponse` extension method is not designed for the aspnetcore integration, which is a separate extension. This issue is external to the durable extension and we do not have plans to integrate with AspNetCore extension for the time being. To unlock yourself you can use the extension method and then copy the values of the `HttpResponseData` over to an `ActionResult` which is AspNetCore compatible.

**Comment by Duranom** [comment]
Question regarding about closing this as not planned.
The main issue is that the `CreateCheckStatusResponse` performs a synchronous call that makes it fail with the AspNetCore extension. That there will be no further integration with AspNetCore extensions like returning a `ActionResult` alone is fine and can manage that with another extension.

But concerning the main issue of `CreateCheckStatusResponse` not playing nice with the AspNetCode because of a synchronous serialization. If there can be an async method version of `CreateCheckStatusResponse` that instead of performing the synchronous call `serializer.Serialize(response.Body, payload, payload.GetType(), cancellation);` but with `serializer.SerializeAsync` than would remove the need of the workaround.
Copying `CreateCheckStatusResponse` and make the async version in own code can be done as well, but seeing as there is also a todo there, there will be need of a constant watch for potential changes.

**Comment by jviau** [comment]
@Duranom `CreateCheckStatusResponse` does not play nice with AspNetCore because it was never designed to be used with AspNetCore. `HttpResponseData` is not a type understood by AspNetCore and is not owned by the durable extension to begin with. `HttpResponseData` is part of the existing HTTP types from `Microsoft.Azure.Functions.Worker.Extensions.Http` - it is not meant to be used with AspNetCore at all. Now if support for using `HttpResponseData` in AspNetCore is added in the future, that will not be the responsibility of the durable extension as we do not own that type.

From the durable teams perspective, this is not planned as we do not own the code where the changes would need to happen.

**Comment by Duranom** [comment]
Thought with at least of version 1.1.1 of `Microsoft.Azure.Functions.Worker.Extensions.Http` that here does was support as there is an extended version `HttpRequestData` made for the integration [AspNetCoreHttpRequestData](
https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Http.AspNetCore/src/HttpDataModel/AspNetCoreHttpRequestData.cs). And when using the AspNetCore integration everything of HttpTriggers seem to use that.

However I will re-raise this issue in the [azure-functions-dotnet-worker](https://github.com/Azure/azure-functions-dotnet-worker) and see what comes out of it. Maybe also cleared up if using AspNetCore integration means you are still allowed to use `HttpRequestData` with HttpTrigger or not at all.
And whom/where a async version of `CreateCheckStatusResponse` has to be made for AspNetCore integration with that.

**Comment by prashantagrawalcrowe** [comment]
> @Duranom the `CreateCheckStatusResponse` extension method is not designed for the aspnetcore integration, which is a separate extension. This issue is external to the durable extension and we do not have plans to integrate with AspNetCore extension for the time being. To unblock yourself you can use the extension method and then copy the values of the `HttpResponseData` over to an `ActionResult` which is AspNetCore compatible.

Can you please give more clarification to unblock ourselves from this issue?

**Comment by Duranom** [comment]
@prashantagrawalcrowe 
There are three work arounds for now:
1. (Recommended) When using ASP.NET Core integration adjust your azure function so that it enables synchronous writing. Just put the following snippet in the section where you configure your services in the Program.cs when configuring your host.
I would recommend for now this unless it becomes too heavy and causes side effects. (See ASP.NET Core Kestrel synchronous-io: [](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/options?view=aspnetcore-8.0#synchronous-io))

```C#
services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
```

2. For HttpTriggers with ASP.NET Integration that use `HttpRequestData/HttpResponseData`.
The following copied version from the package source will work with the first work-around, however keep in mind that this will need to do reflection at a point due to the need to access an internal property. So you will need to keep an eye out on this repo all the time to ensure the reflection will work and if any changes have been made.
```C#
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using System;
using System.Net;
using System.Threading;
using Azure.Core.Serialization;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.DurableTask.Client;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Options;

namespace Microsoft.Azure.Functions.Worker;

/// <summary>
/// Extensions for <see cref="DurableTaskClient"/>
/// </summary>
public static class DurableTaskClientExtensions
{
    /// <summary>
    /// Creates an HTTP response that is useful for checking the status of the specified instance.
    /// </summary>
    /// <param name="client">The <see cref="DurableTaskClient"/>.</param>
    /// <param name="request">The HTTP request that this response is for.</param>
    /// <param name="instanceId">The ID of the orchestration instance to check.</param>
    /// <param name="cancellation">The cancellation token.</param>
    /// <returns>An HTTP 202 response with a Location header and a payload containing instance control URLs.</returns>
    public static Task<HttpResponseData> CreateCheckStatusResponse(
        this DurableTaskClient client,
        HttpRequestData request,
        string instanceId,
        CancellationToken cancellation = default)
    {
        return client.CreateCheckStatusResponseAsync(request, instanceId, HttpStatusCode.Accepted, cancellation);
    }

    /// <summary>
    /// Creates an HTTP response that is useful for checking the status of the specified instance.
    /// </summary>
    /// <param name="client">The <see cref="DurableTaskClient"/>.</param>
    /// <param name="request">The HTTP request that this response is for.</param>
    /// <param name="instanceId">The ID of the orchestration instance to check.</param>
    /// <param name="statusCode">The status code.</param>
    /// <param name="cancellation">The cancellation token.</param>
    /// <returns>An HTTP response with a Location header and a payload containing instance control URLs.</returns>
    public static async Task<HttpResponseData> CreateCheckStatusResponseAsync(
        this DurableTaskClient client,
        HttpRequestData request,
        string instanceId,
        HttpStatusCode statusCode,
        CancellationToken cancellation = default)
    {
        if (client is null)
        {
            throw new ArgumentNullException(nameof(client));
        }

        static string BuildUrl(string url, params string?[] queryValues)
        {
            bool appended = false;
            foreach (string? query in queryValues)
            {
                if (!string.IsNullOrEmpty(query))
                {
                    url = url + (appended ? "&" : "?") + query;
                    appended = true;
                }
            }

            return url;
        }

        // TODO: To better support scenarios involving proxies or application gateways, this
        //       code should take the X-Forwarded-Host, X-Forwarded-Proto, and Forwarded HTTP
        //       request headers into consideration and generate the base URL accordingly.
        //       More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded.
        //       One potential workaround is to set ASPNETCORE_FORWARDEDHEADERS_ENABLED to true.
        string baseUrl = request.Url.GetLeftPart(UriPartial.Authority);
        string formattedInstanceId = Uri.EscapeDataString(instanceId);
        string instanceUrl = $"{baseUrl}/runtime/webhooks/durabletask/instances/{formattedInstanceId}";
        string? commonQueryParameters = GetQueryParams(client);

        HttpResponseData response = request.CreateResponse(statusCode);
        response.Headers.Add("Location", BuildUrl(instanceUrl, commonQueryParameters));
        response.Headers.Add("Content-Type", "application/json");

        ObjectSerializer serializer = GetObjectSerializer(response);
        var payload = new
        {
            id = instanceId,
            purgeHistoryDeleteUri = BuildUrl(instanceUrl, commonQueryParameters),
            sendEventPostUri = BuildUrl($"{instanceUrl}/raiseEvent/{{eventName}}", commonQueryParameters),
            statusQueryGetUri = BuildUrl(instanceUrl, commonQueryParameters),
            terminatePostUri = BuildUrl($"{instanceUrl}/terminate", "reason={{text}}}", commonQueryParameters),
        };

        // Need to capture context!
        await serializer.SerializeAsync(response.Body, payload, payload.GetType(), cancellation).ConfigureAwait(true);
        return response;
    }

    private static ObjectSerializer GetObjectSerializer(HttpResponseData response)
    {
        return response.FunctionContext.InstanceServices.GetService<IOptions<WorkerOptions>>()?.Value?.Serializer
            ?? throw new InvalidOperationException("A serializer is not configured for the worker.");
    }

    private static string? GetQueryParams(DurableTaskClient client)
    {
        var clientType = client.GetType();
        if (client.GetType().FullName == "Microsoft.Azure.Functions.Worker.FunctionsDurableTaskClient"
            && clientType.GetProperty("QueryString") is { } queryStringProp)
        {
            return queryStringProp.GetValue(client, null) as string;
        }

        return null;
    }
}
```

3. For HttpTriggers with ASP.NET Integration that use `HttpRequest` and `IActionResult`.
The same applies as for point 2. It still needs to do reflection due to the need to access an internal property. So you will need to keep an eye out on this repo all the time to ensure the reflection will work and if any changes have been made.
```C#
// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DurableTask.Client;
using System.Net;

namespace Microsoft.Azure.Functions.Worker;

/// <summary>
/// Extensions for <see cref="DurableTaskClient"/>
/// </summary>
public static class DurableTaskClientExtensions
{
    /// <summary>
    /// Creates an <see cref="IActionResult"/> response that is useful for checking the status of the specified instance.
    /// </summary>
    /// <param name="client">The <see cref="DurableTaskClient"/>.</param>
    /// <param name="request">The HTTP request that this response is for.</param>
    /// <param name="instanceId">The ID of the orchestration instance to check.</param>
    /// <returns>An <see cref="IActionResult"/> with HTTP 202 response and a payload containing instance control URLs, to the <see cref="HttpResponse"/> the Location header is added.</returns>
    public static IActionResult CreateCheckStatusResponse(
        this DurableTaskClient client,
        HttpRequest request,
        string instanceId)
    {
        return client.CreateCheckStatusResponse(request, instanceId, HttpStatusCode.Accepted);
    }

    /// <summary>
    /// Creates an <see cref="IActionResult"/> response that is useful for checking the status of the specified instance.
    /// </summary>
    /// <param name="client">The <see cref="DurableTaskClient"/>.</param>
    /// <param name="request">The HTTP request that this response is for.</param>
    /// <param name="instanceId">The ID of the orchestration instance to check.</param>
    /// <param name="statusCode">The status code.</param>
    /// <returns>An <see cref="IActionResult"/> with the desired <paramref name="statusCode"/> a payload containing instance control URLs, to the <see cref="HttpResponse"/> the Location header is added.</returns>
    public static IActionResult CreateCheckStatusResponse(
        this DurableTaskClient client,
        HttpRequest request,
        string instanceId,
        HttpStatusCode statusCode)
    {
        if (client is null)
        {
            throw new ArgumentNullException(nameof(client));
        }

        static string BuildUrl(string url, params string?[] queryValues)
        {
            bool appended = false;
            foreach (string? query in queryValues)
            {
                if (!string.IsNullOrEmpty(query))
                {
                    url = url + (appended ? "&" : "?") + query;
                    appended = true;
                }
            }

            return url;
        }

        // TODO: To better support scenarios involving proxies or application gateways, this
        //       code should take the X-Forwarded-Host, X-Forwarded-Proto, and Forwarded HTTP
        //       request headers into consideration and generate the base URL accordingly.
        //       More info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded.
        //       One potential workaround is to set ASPNETCORE_FORWARDEDHEADERS_ENABLED to true.
        string baseUrl = new Uri(request.GetEncodedUrl()).GetLeftPart(UriPartial.Authority);
        string formattedInstanceId = Uri.EscapeDataString(instanceId);
        string instanceUrl = $"{baseUrl}/runtime/webhooks/durabletask/instances/{formattedInstanceId}";
        string? commonQueryParameters = GetQueryParams(client);

        request.HttpContext.Response.Headers.Append("Location", BuildUrl(instanceUrl, commonQueryParameters));
        request.HttpContext.Response.Headers.Append("Content-Type", "application/json");

        return new ObjectResult(new
        {
            id = instanceId,
            purgeHistoryDeleteUri = BuildUrl(instanceUrl, commonQueryParameters),
            sendEventPostUri = BuildUrl($"{instanceUrl}/raiseEvent/{{eventName}}", commonQueryParameters),
            statusQueryGetUri = BuildUrl(instanceUrl, commonQueryParameters),
            terminatePostUri = BuildUrl($"{instanceUrl}/terminate", "reason={{text}}}", commonQueryParameters),
        })
        {
            StatusCode = (int)statusCode
        };
    }

    private static string? GetQueryParams(DurableTaskClient client)
    {
        var clientType = client.GetType();
        if (client.GetType().FullName == "Microsoft.Azure.Functions.Worker.FunctionsDurableTaskClient"
            && clientType.GetProperty("QueryString") is { } queryStringProp)
        {
            return queryStringProp.GetValue(client, null) as string;
        }

        return null;
    }
}
```

**Comment by MarekLani** [comment]
I would like to reopen this. I don't think issue should be closed when default scafoldding for durable function in .NET Core Isolated project yields exeception and requires workarounds. This should be addressed. As a programmer I want the default setup to work. Seeing red error messages right after starting the sample project while following documentation is really not good user experience and if I was new to the technology I would be really questioning it

**Comment by davidmrdavid** [comment]
Hi @MarekLani - noted on the feedback, I agree the default set up should work; but I'm trying to make sure we're talking about the same "default" set up.

Can you please help me understand what's the sample project you're using that's leading to this "out of the box" exception? Some links to the docs or samples that are yielding this would help. Thanks!

**Comment by ebuljan** [comment]
Create new .NET 8 Durable Functions Orchestration project in VS 17.9.4.  Then call Function1_HttpStart from a REST client.  It will fail with the error described above.

**Comment by jprpicw** [comment]
Honestly, you follow official documentation on how to create a new Durable Function which tells you to trigger the function through postman and you receive errors and status code 500, made me rethink what I am doing wrong and waste time on googling until I found this issue which is somehow closed.

**Comment by benwarrick** [comment]
We've been using function apps for about two years now. If I were evaluating them today, seeing the VS template fail and needing to poor through all this just to get a base example to work would have ruined my enthusiasm for Azure functions. Right now we're migrating from .Net 6 to 8, and I'm seeing this issue. The recommended workaround is also not a recommended approach to asynchronous. 

For anyone interested, here's my simple and ingenious workaround. 

```
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.DurableTask;
using Microsoft.DurableTask.Client;
using Microsoft.Extensions.Logging;

namespace Testaroo
{
    public static class Durable2
    {
        [Function(nameof(Durable2))]
        public static async Task<List<string>> RunOrchestrator(
            [OrchestrationTrigger] TaskOrchestrationContext context)
        {
            ILogger logger = context.CreateReplaySafeLogger(nameof(Durable2));
            logger.LogInformation("Saying hello.");
            var outputs = new List<string>();

            // Replace name and input with values relevant for your Durable Functions Activity
            outputs.Add(await context.CallActivityAsync<string>(nameof(SayHello), "Tokyo"));
            outputs.Add(await context.CallActivityAsync<string>(nameof(SayHello), "Seattle"));
            outputs.Add(await context.CallActivityAsync<string>(nameof(SayHello), "London"));

            // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!"]
            return outputs;
        }

        [Function(nameof(SayHello))]
        public static string SayHello([ActivityTrigger] string name, FunctionContext executionContext)
        {
            ILogger logger = executionContext.GetLogger("SayHello");
            logger.LogInformation("Saying hello to {name}.", name);
            return $"Hello {name}!";
        }

        [Function("Durable2_HttpStart")]
        public static async Task<string> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
            [DurableClient] DurableTaskClient client,
            FunctionContext executionContext)
        {
            ILogger logger = executionContext.GetLogger("Durable2_HttpStart");

            // Function input comes from the request content.
            string instanceId = await client.ScheduleNewOrchestrationInstanceAsync(
                nameof(Durable2));

            logger.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);

            // Returns an HTTP 202 response with an instance management payload.
            // See https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-http-api#start-orchestration
            //return client.CreateCheckStatusResponse(req, instanceId);

            return "WTF";
        }
    }
}
```

**Comment by Duranom** [comment]
> We've been using function apps for about two years now. If I were evaluating them today, seeing the VS template fail and needing to pour through all this just to get a base example to work would have ruined my enthusiasm for Azure functions. Right now we're migrating from .Net 6 to 8, and I'm seeing this issue. The recommended workaround is also not a recommended approach to asynchronous.

Did you update to the latest version 1.1.2 that is available as that has the `CreateCheckStatusResponseAsync` that was introduced since 1.1.1?

**Comment by cgillum** [comment]
Just confirming that as of 1.1.2, there's a `CreateCheckStatusResponseAsync` that can be used. I believe the team is working on fixing the default templates to use the correct API.

Here's what I got working after updating my nuget package references.

```csharp
[Function("HelloCities_HttpStart")]
public static async Task<HttpResponseData> HttpStart(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req,
    [DurableClient] DurableTaskClient client,
    FunctionContext executionContext)
{
    ILogger logger = executionContext.GetLogger("HelloCities_HttpStart");

    // Function input comes from the request content.
    string instanceId = await client.ScheduleNewOrchestrationInstanceAsync(nameof(HelloCities));

    logger.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);

    // Returns an HTTP 202 response with an instance management payload.
    // See https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-http-api#start-orchestration
    return await client.CreateCheckStatusResponseAsync(req, instanceId);
}
```

**Comment by davidmrdavid** [comment]
Yeah we dropped the ball on this one, my apologies for not realizing the templates had stopped working; I'm looking to follow up with the tooling teams to understand why their test validation did not catch this.

I think part of the confusion, on our end, was that it wasn't fully clear (at least to me) that this exception was getting triggered with the templates. I'm not sure that this was the case when this GitHub issue first got created, but it is certainly the issue _now_.

In any case, I've fixed our templates [here](https://github.com/Azure/azure-functions-templates/pull/1513) and will be following up with the VS and VSCode teams to make sure these get shipped asap. In the meantime, it might be good to create some kind of pinned comment flagging this issue. I don't believe this thread is the right thread to pin or re-open, but instead we should create one talking specifically about templates. I'll look to follow  up - cc/ @lilyjma

**Comment by jacksorjacksor** [comment]
Yep, for anyone else having this issue from the default Durable Functions template it's case of replacing line 51 from

`return client.CreateCheckStatusResponse(req, instanceId);`

to

`return await client.CreateCheckStatusResponseAsync(req, instanceId);`

**Comment by javtec** [comment]
I'm having the same issue.  I'm simply following the documentation to get the baseline durable function working in VS Code and getting the same error over and over.  This is very disappointing that the sample code doesn't work as expected.
I'm following the instructions at this URL:
https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-create-first-csharp?pivots=code-editor-vscode
And I got to the point titled "Test the function locally" which is where it fails.
I'm following this thread to resolve the issue.  But my sample code should work out of the box.

**Comment by javtec** [comment]
I was able to get it to work following the instructions at this link:
[https://github.com/Azure/azure-functions-templates/pull/1513](url)

But the final fix was to replace the whole line of code from this:

"return client.CreateCheckStatusResponse(req, instanceId);"

to this:

"return await client.CreateCheckStatusResponseAsync(req, instanceId);"

I added "await" and that got the code working.

**Comment by codebrane** [comment]
I upgraded to 1.1.2 and this:

    [Function("Orchestration_HttpStart")]
```
public static async Task<HttpResponseData> HttpStart(
  [HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestData req,
  [DurableClient] DurableTaskClient client,
  FunctionContext executionContext)
{
      ILogger logger = executionContext.GetLogger("Orchestration_HttpStart");
      string instanceId = await client.ScheduleNewOrchestrationInstanceAsync(
          nameof(BrunelBrightspaceTeamsOrchestration));

    logger.LogInformation("Started orchestration with ID = '{instanceId}'.", instanceId);
    return await client.CreateCheckStatusResponseAsync(req, instanceId);
} // Orchestration_HttpStart

```

causes this build error:

> Since this is an async method, the return expression must be of type 'HttpResponseData' rather than 'Task<HttpResponseData>'
