### ISSUE TITLE
Input and state lost when one entity call another with SignalEntity on .NET 8 isolated

### ISSUE THREAD

**Issue by thomaseyde** [Azure/azure-functions-durable-extension#2690]
### Description

When you call an entity from another entity with `operation.Context.SignalEntity()`, data for input and state are both lost. State is lost if the calling entity try to set the state on the called entity before calling `operation.Context.SignalEntity()`.

Input passed with `client.Entities.SignalEntityAsync()` from a function trigger works as expected.

### Expected behavior
State should be kept. Input should be passed.

### Actual behavior
Input as retrieved with `operation.GetInput<T>()` is null.

### Relevant source code snippets
Create a new function app on .NET 8 with isolated worker.

Add a trigger:

```csharp
public class QueueTrigger
{
    [Function(nameof(QueueTrigger))]
    public async Task Run([QueueTrigger("bug")] string message, [DurableClient] DurableTaskClient client)
    {
        if (message == "one")
        {
            await client.Entities.SignalEntityAsync(
                new EntityInstanceId(nameof(OneFunction), "key"), "queued", message);
        }

        if (message == "another")
        {
            await client.Entities.SignalEntityAsync(
                new EntityInstanceId(nameof(AnotherFunction), "key"), "queued", message);
        }
    }
}
```

Add two functions:

```csharp
public class OneFunction(ILogger<OneFunction> logger)
{
    [Function(nameof(OneFunction))]
    public Task Run([EntityTrigger] TaskEntityDispatcher dispatcher)
    {
        return dispatcher.DispatchAsync(operation =>
        {
            var input = operation.GetInput<string>();
            logger.LogWarning("OneFunction input: '{Input}'", input);

            var another = new EntityInstanceId(nameof(AnotherFunction), "key");
            operation.Context.SignalEntity(another, "another", input);

            if (operation.Name != "self")
            {
                operation.Context.SignalEntity(operation.Context.Id, "self", input);
            }
        
            return default;
        });
    }
}

public class AnotherFunction(ILogger<AnotherFunction> logger)
{
    [Function(nameof(AnotherFunction))]
    public Task Run([EntityTrigger] TaskEntityDispatcher dispatcher)
    {
        return dispatcher.DispatchAsync(
            operation =>
            {
                var input = operation.GetInput<string>();
                logger.LogWarning("AnotherFunction input: '{Input}'", input);
                return default;
            });
    }
}
```

Create a queue `bug` and add a message containing `one` to it.
Set breakpoints on calls to `GetInput()`.
Debug the function app.

Functions receiving a call from the trigger will have input. Functions with calls from an entity does not.

### Known workarounds
No workarounds found.

### App Details

- **Durable Functions extension version**: See package references below
- **Azure Functions runtime version**: 2 (from `host.json`)
- **Programming language used**: C#

````
        <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.20.0" />
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" Version="1.1.0"/>
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.2.0"/>
        <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.16.4" />
````

**Comment by thomaseyde** [comment]
I found that `SendSignalMessage` accepts a `SendSignalOperationAction` which is created in `SignalEntity`. However, the input value is not used anywhere. `RequestMessage` has a property `Input` which is not assigned anything.

```c#
        // TaskEntityDispatcher

        void SendSignalMessage(WorkItemEffects effects, SchedulerState schedulerState, SendSignalOperationAction action)
        {
            OrchestrationInstance destination = new OrchestrationInstance()
            {
                InstanceId = action.InstanceId
            };
            RequestMessage message = new RequestMessage()
            {
                ParentInstanceId = effects.InstanceId,
                ParentExecutionId = null, // for entities, message sorter persists across executions
                Id = Guid.NewGuid(),
                IsSignal = true,
                Operation = action.Name,
                ScheduledTime = action.ScheduledTime,
            };
            string eventName;
            if (action.ScheduledTime.HasValue)
            {
                DateTime original = action.ScheduledTime.Value;
                DateTime capped = this.entityBackendProperties.GetCappedScheduledTime(DateTime.UtcNow, original);
                eventName = EntityMessageEventNames.ScheduledRequestMessageEventName(capped);
            }
            else
            {
                eventName = EntityMessageEventNames.RequestMessageEventName;
                schedulerState.MessageSorter.LabelOutgoingMessage(message, action.InstanceId, DateTime.UtcNow, this.entityBackendProperties.EntityMessageReorderWindow);
            }
            this.ProcessSendEventMessage(effects, destination, eventName, message);
        }

```

**Comment by plamber** [comment]
Hi @thomaseyde,
I had a similar issue that I was able to resolve by downgrading to DurableTask 1.0.4. 

I logged the issue https://github.com/Azure/azure-functions-durable-extension/issues/2693 and I am experiencing with the latest package 1.1.0 and .NET isolated.

Cheers,
Patrick

**Comment by sebastianburckhardt** [comment]
Thanks for reporting this. Your analysis looks right to me - obviously the input should be passed along. I will create a PR with a fix.

**Comment by sebastianburckhardt** [comment]
BTW, I did not understand the part about the lost state:

> State is lost if the calling entity try to set the state on the called entity before calling operation.Context.SignalEntity()

How would the calling entity set the state on the called entity before calling signal?

**Comment by thomaseyde** [comment]
I am sure I tried to set the state on the target entity from the calling entity as a workaround, but I forgot to take notes. Now I can't figure out how I did it.

**Comment by lilyjma** [comment]
Closing because fixed in https://github.com/Azure/durabletask/pull/1016
