### ISSUE TITLE
WIP: Versioning

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#27]
THIS IS A WORK IN PROGRESS SPEC. SIGNIFICANT CHANGES ARE EXPECTED BASED ON RECENT INTERNAL DISCUSSION. STAY TUNED.

## Summary
This feature adds the ability for users to add version metadata to their orchestrator and activity functions. It also allows invoking specific versions of orchestrator and activity functions. Internally this versioning feature will leverage the existing versioning capabilities of the Durable Task Framework.

## Motivation
Users will often need to update their orchestrator and activity function code. For normal functions this is not a big deal as long as any changes are backwards compatible with any existing callers/triggers of that function. 

With long-running Durable Functions, however, the consequences of a change are more subtle and can result in breakage for in-progress orchestrator function executions. For example, making a change to the sequence of activity calls can cause an in-progress orchestrator function execution to get out of sync with it's history, resulting in unexpected behavior or in `NonDeterministicOrchestrationException` failures. For this reason, a proper versioning story is necessary so that developers have the tools they need to version their durable functions.

For more context on the replay behavior of orchestrator functions and why deterministic execution is required, see the [Orchestrator Checkpointing and Replay](https://azure.github.io/azure-functions-durable-extension/articles/topics/checkpointing-and-replay.html) topic in the documentation.

## Scenarios
There are a lots of ways that developers can change their code, and it's important that there is guidance for all those cases. In this section we'll call out the main versioning scenarios that need to be addressed. For each scenario, versioning will be called out as being **OPTIONAL**, **RECOMMENDED**, or **REQUIRED**.

### Changes to the body of activity functions
Versioning is **OPTIONAL** if the body of an activity function is updated but the API signature remains the same. These changes are safe because activity functions are executed only once and the resulting output is saved in the execution history. In-flight instances which have already called the updated activity will therefore never see the logic changes. When keeping the same version of the activity function in this way, new and in-flight instances which have not yet called the activity will execute the latest activity logic (which is ideal for bug fixing).

### Changes to activity function signatures
Versioning is **RECOMMENDED** if an activity signature changes (which can include the parameters or the return type). This is a breaking change that will disrupt in-flight orchestrations that invoke the activity function. Such changes will require new versions of both the orchestrator function (the client) and the activity function to ensure that in-flight orchestrations are not impacted.

The reason this is recommended but not required is because there are a small number cases where breaking changes can be made safely across both the activity function and the orchestrator function. For example, changing an input parameter from `int` to `double` may be a simple matter of having the caller cast an existing `int` variable into a `double` before calling the activity function. Essentially, small changes like this which don't impact the history replay outcome can be made without requiring strict versioning. However, versioning is always recommended for this scenario to avoid any potential for unintended breakage.

### Changes to orchestrator task ordering
Versioning is **REQUIRED** if an orchestrator function changes the order in which it schedules durable tasks. Failure to version an orchestrator function will cause
in-flight instances to fail with a `NonDeterministicOrchestrationException` error once the replay logic encounters the change in task execution order.

A simple example of task order changes includes an orchestration which calls and awaits activity function `A`, followed by activity function `B`. If the logic is swapped such that it first calls and awaits activity function `B` followed by activity function `A`, in-flight instances will fail as described previously. Note that durable timer tasks and external events are also subject to order change restrictions.

**This rule also applies to cases where orchestrator functions adds new calls or remove existing calls**. These kinds of changes will cause replays to no longer match the existing execution history, resulting in runtime failures or worse. This includes explicitly adding or removing calls or implicitly removing them by (for example) changing the number

### Changes to orchestrator logic, without affecting task ordering
Versioning is technically **OPTIONAL** if the internal implementation of an orchestrator function changes in a way that neither affects task execution order nor the parameters of activity functions. However, knowing whether or not a particular change may impact the execution history can be very tricky, even for relatively simple orchestrations. As a general rule, if the reliability of the function execution is important, versioning the orchestration is **RECOMMENDED**.

### Explicit Side-by-Side Versioning
Side-by-side versioning refers to the ability to deploy multiple versions of the same orchestration or activity side-by-side. The idea is that the old versions of orchestrations are kept around so that in-flight instances can complete successfully. Client code can then be upgraded to target the newest deployed version.

The main advantage of side-by-side versioning are that older versions do not need to be modified, allowing them to run as they always have without re-testing.

Side-by-side versioning works by adding version metadata to the function metadata. Using the Visual Studio tooling support for Azure Functions, one can set the `Orchestration` (or `Activity` in the case of activity functions) and `Version` properties in the trigger attribute:

```csharp
[FunctionName("E1_HelloSequenceV2")]
public static async Task<List<string>> HelloSequenceV2(
    [OrchestrationTrigger(Orchestration = "HelloSequence", Version = "2"]
    DurableOrchestrationContext context)
{
    // implementation...
}
```

In the general "Azure Portal" UX, one can set the `orchestration` (or `activity` in the case of activity functions) and `version` fields in the trigger binding to declare the version:

```json
{
  "bindings": [
    {
      "name": "context",
      "type": "orchestrationTrigger",
      "orchestration": "E1_HelloSequence",
      "version": "2", 
      "direction": "in"
    }
  ],
  "disabled": false
}
```

If no version information is explicitly assigned, the extension defaults to a `*` version, which has special meaning and is described further below.

### Implicit Side-by-Side Versioning
Implicit side-by-side versioning is the same as explicit versioning except that instead of specifying version attributes on the functions, one simply creates new functions with new names - e.g. adding a version suffix to the name ("HelloWorld-V1" and "HelloWord-V2")

The main disadvantage of implicit vs. explicit versioning is the loss of version metadata. Version metadata can be useful in a variety of scenarios. For example, when using Application Insights for monitoring, the version of a function is included in its own column and can be used for filtering or aggregation. It's conceivable that some tooling could be built around the version metadata as well.

### In-Place Versioning
Runtime versioning means that orchestrator functions use code to make versioning decisions. The following shows how version information flows into the orchestration context and can be used by the orchestrator to execute slightly different logic:

```csharp
[FunctionName("E1_HelloSequence")]
public static async Task<List<string>> Run(
    [OrchestrationTrigger] DurableOrchestrationContext context)
{
    var outputs = new List<string>();

    outputs.Add(await context.CallFunctionAsync<string>("E1_SayHello", "Tokyo"));
    outputs.Add(await context.CallFunctionAsync<string>("E1_SayHello", "Seattle"));
    outputs.Add(await context.CallFunctionAsync<string>("E1_SayHello", "London"));

    if (int.TryParse(context.Version, out int version) && version > 1)
    {
        // Version 1 did not include this call
        outputs.Add(await context.CallFunctionAsync<string>("E1_SayHello", "São Paulo"));
    }

    // returns ["Hello Tokyo!", "Hello Seattle!", "Hello London!", "Hello São Paulo!"]
    return outputs;
}
```

This pattern applies whenever no version is explicitly configured or if `*` is specified as the version. The semantic meaning is that this function will match *any* version specified by a client - sort of like a wildcard. Note that explicit version labels always take precedence over the default `*` wildcard version label.

## Version Selection
Client code explicitly decides which version of a function to target when calling `StartNewAsync`, `CallFunctionAsync`, or `ContinueAsNew`. If the specified name/version combination is not known, then an exception will be thrown. Examples:

**Starting a specific version of an orchestrator function**
```csharp
[FunctionName("StartMyFunc")]
public static async Task Run(
    [ManualTrigger]string data,
    [OrchestrationClient] DurableOrchestrationClient starter)
{
    await starter.StartNewAsync("MyOrchestratorFunc", data, version: "V2");
    // ...
}
```

**Calling a specific version of an activity function**
```csharp
[FunctionName("MyOrchestratorFunc")]
public static async Task Run(
    [OrchestrationTrigger] DurableOrchestrationContext ctx,
    TraceWriter log)
{
    if (!ctx.IsReplaying)
    {
        log.Info($"Started version {ctx.Version}.");
    }

    await ctx.CallFunctionAsync("MyActivityFunc", null, version: "V2.1");
    // ...
}
```

**Restrating self as a new version**
```csharp
[FunctionName("MySingletonFunc")]
public static async Task Run(
    [OrchestrationTrigger] DurableOrchestrationContext ctx,
    TraceWriter log)
{
    // ...
    ctx.ContinueAsNew(newVersion: "V3", state);
}
```

If no version is specified, the runtime assumes the default `*` version, which is the default for any function which does not explicitly declare its version.

**Comment by SimonLuckenuik** [comment]
@cgillum, this seems to be out of date compared to official documentation found here: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-versioning ?

**Comment by cgillum** [comment]
Closing this for now since it's out-of-date and we have versioning documentation. There are some new versioning strategies we'd like to explore in addition to what we have, but those can be explored using separate issues.
