### ISSUE TITLE
Custom status values are not displayed in the HTTP status query API

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#271]
I noticed this while writing some new test applications. The custom status value is available in the client APIs but we don't expose it in the HTTP status query response yet. Just an oversight.

The code that needs to be updated is here:
https://github.com/Azure/azure-functions-durable-extension/blob/master/src/WebJobs.Extensions.DurableTask/HttpApiHandler.cs#L195-L203.

It would probably be good to add a unit test for this as well.

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you for catching this.

I will work on it!

Thank you!
