### ISSUE TITLE
Isolated Process with DurableClient and ASP.NET Core integration will throw exception on CreateCheckStatusResponse

### ISSUE THREAD

**Issue by Duranom** [Azure/azure-functions-durable-extension#2717]
**Description**
This issue is re-raised here as result of discussion in [azure-functions-durable-extension issue: 2683](https://github.com/Azure/azure-functions-durable-extension/issues/2683)

Packages used:
- [Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore v1.1.1](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore/1.1.1)
- [Microsoft.Azure.Functions.Worker.Extensions.DurableTask v1.1.0](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.DurableTask/1.1.0)

When using these versions of the functions packages that provides ASP.NET Core integration and DurableTaskClient, or newer, the method [CreateCheckStatusResponse](https://github.com/Azure/azure-functions-durable-extension/blob/dev/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs) will throw an InvalidOperationException because the implementation writes to the `HttpResponseData` through serialization synchronous.

This point has been raised in the (azure-functions-durable-extension repo)[https://github.com/Azure/azure-functions-durable-extension/issues/2683], and there the following points came to light:
- It is unclear when using Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore package if you should still use a `HttpTrigger` function that accepts and returns `HttpRequestData` \ `HttpResponseData`. This as of v1.1.1 the package seem to provide support through [AspNetCoreHttpRequestData.cs](https://github.com/Azure/azure-functions-dotnet-worker/blob/main/extensions/Worker.Extensions.Http.AspNetCore/src/HttpDataModel/AspNetCoreHttpRequestData.cs) and does seem to play nice for now, but it is not clear if this is recommended
  - If it is not advised can this be added to [asp.net core integration documentation](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#aspnet-core-integration)
- From Durable's teams perspective they are using the type as intended so the issue is re-raised here. So no async version will be introduced.
- Not clear whom/where a async version of CreateCheckStatusResponse has to be made for AspNetCore integration

All that I know is that to solve the exception is that an extension method version would need to be introduced that performs the serialization asynchronous, that extension method version would than be taken changes should the non-asynchronous version be updated and to avoid the work around.

Reference:
https://github.com/Azure/azure-functions-durable-extension/issues/2683

**Expected behavior**
When using ASP.NET Core integration and the durable task extension method there should be no exception thrown, however as synchronous writing is not allowed since ASP.NET Core 3+ a Async version will be needed to be exposed.

**Actual behavior**
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead
```
Result: An unhandled exception occurred.
Exception: System.AggregateException: One or more errors occurred. (Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.)
  ---> System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
    at Azure.Core.Serialization.JsonObjectSerializer.Serialize(Stream stream, Object value, Type inputType, CancellationToken cancellationToken)
    at Microsoft.Azure.Functions.Worker.DurableTaskClientExtensions.CreateCheckStatusResponse(DurableTaskClient client, HttpRequestData request, String instanceId, HttpStatusCode statusCode, CancellationToken cancellation) in /_/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:line 97
    at Microsoft.Azure.Functions.Worker.DurableTaskClientExtensions.CreateCheckStatusResponse(DurableTaskClient client, HttpRequestData request, String instanceId, CancellationToken cancellation) in /_/src/Worker.Extensions.DurableTask/DurableTaskClientExtensions.cs:line 34
```

### Relevant source code snippets
```csharp
[Function("SimpleHttpTriggerHttpData")]
public async Task<HttpResponseData> Run(
[HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestData req,
[DurableClient] DurableTaskClient durableClient)
{
       return durableClient.CreateCheckStatusResponse(req, "FakeId"); //Will result in exception
}
```

**Known Workarounds**
One option is to copy the `CreateCheckStatusResponse` into the consumers project and make a asynchronous version, however this does introduce having to keep an eye on the original code every time the package is updated in case of changes.
It does need modification to use reflection as the `FunctionsDurableTaskClient` needs to be accessed to get query parameters, thus not nice.

Another option from that ASP.NET Core provided for those updating in the past was to apply the following configuration which will allow calling synchronous writes to the HttpRequest. However this would be rather avoided:
```
services.Configure<KestrelServerOptions>(options =>
{
    options.AllowSynchronousIO = true;
});
```

**Addition requested**
When using ASP.NET Core integration it would be nice to also have a `CreateCheckStatusResponse` version that accepts `HttpRequest` and returns an `ActionResult` to keep it more consistent with the ASP.NET Core integration HttpTriggers. However that would be just a nice to have.

**Comment by dxynnez** [comment]
@jviau  thanks for providing the fix.

But I am still a bit confused - what's the point of using the AspNetCore extension when the function is still binding to HttpRequestData? Would there be any CreateCheckStatusResponse that would just natively work with the HttpRequest?

**Comment by Duranom** [comment]
> @Duranom is there any major drawback to enabling synchronous IO?

Sorry for late reply due to winter vacations period.

This is a bit hard to say specifically for Azure Functions as how how that works in design and how the ASP.NET core integration is build upon it, so hard to say if thread starvation and all occurs. Neither have the migrated functions yet deployed due some blocking issue's that might take a bit before get any insights into it.

**Comment by jviau** [comment]
@dxynnez so ideally yes, you would be using AspNetCore APIs and not `HttpRequestData`. However, the position we are in is that AspNetCore and Durable are both extensions and we do not want to introduce cross-extension dependencies, nor do we want to introduce AspNetCore dependencies to Durable Functions packages. For the short term, we are providing these async APIs so you can work with AspNetCore (although not the ideal solution). In the future we can explore adding an entirely new Durable Functions package which brings in AspNetCore and those APIs or explore alternative ways to have a tighter AspNetCore API. But that is not a high priority at this time.
