### ISSUE TITLE
Question: Filtering SubOrchestrator lifecycle event

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-durable-extension#273]
I start thinking a use case which when we use Sub Orchestrator. 

In this case, we might want to filter  Sub orchestrators. Can we identify whether it is Parent or Sub orchestrator?  Maybe this method might be the one. Is it true? 

https://github.com/Azure/azure-functions-durable-extension/blob/38bdffb20dbb8a209fec7e9c5088b7167dd07f01/src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs#L57

**Comment by gled4er** [comment]
Hello @TsuyoshiUshio ,

Yes, you can use the `ParentInstanceId` to get the parent orchestrator. If this property has no value then this is the parent orchestrator. 

Thank you!

**Comment by cgillum** [comment]
Yep, that's the best way to do it.
