### ISSUE TITLE
No FunctionContext available on Durable functions Activity function

### ISSUE THREAD

**Issue by marcosamaral** [Azure/azure-functions-durable-extension#2741]
### Description

After updating to Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.1, I get null on my FunctionContext on activity function, with that being the only change.

### App Details

Microsoft.Azure.Functions.Worker.Extensions.DurableTask 1.1.1
Azure Functions runtime version 4
Programming language used: C#

**Comment by nytian** [comment]
Hi, @marcosamaral  can you give me a sample that does not work? Thanks!

**Comment by marcosamaral** [comment]
@nytian I get this issue with something as basic as:

```
[Function(nameof(ReadInbox))]
public async Task<List<string>> ReadInbox([ActivityTrigger] FunctionContext functionContext)
{
    ILogger logger = functionContext.GetLogger(nameof(ReadInbox));
    (...)
```
    
with functionContext just being null in the function. Again, same code works fine with 1.1.0, and I get this behavior by just updating the version 1.1.1.

**Comment by nytian** [comment]
Close as bug fixed at PR #2806

**Comment by zhufamily** [comment]
The very same error happens for version 1.1.5 and is inconsistent in results ...

**Comment by nytian** [comment]
@zhufamily Can you provide me a sample of your source code and also the error details? Thanks!
