### ISSUE TITLE
Waiting for multiple event types inside a loop only responds to first event type received

### ISSUE THREAD

**Issue by ethanroday** [Azure/azure-functions-durable-extension#275]
**Steps to Reproduce:**

1. Create an orchestrator function like the one below, which waits for multiple events using the `Task.WhenAny()` pattern. It increments a counter on receiving the `Increment` event or stops on receiving the `Stop` event.
2. Start an instance of the function by calling `StartNewAsync()` from a simple HTTP triggered function.
3. Raise three `Increment` events using the HTTP API.
4. Raise a `Stop` event using the HTTP API.

**Expected result:**

The orchestration function is completed and its custom status is `{ count: 3 }`. Raising additional events does not change the state of the function.

**Actual result:**

The custom status is `{ count: 3 }`, but the orchestration function is still running. The logs indicate that a `Stop` event was received, but the function never responded to it:
![image](https://user-images.githubusercontent.com/896670/39319527-2c71bf84-4936-11e8-95e5-b5ec43740a91.png)
I can even send another `Increment` event and make the count go to 4, which causes the orchestration function to end normally (by failing the while loop condition).

Sometimes, sending an additional `Stop` event makes it work, although this behavior is not consistent.

I say that it's only responding to the first event type because, if I start the function and then send the `Stop` event as the first event, the function breaks out of the while loop and completes with a count of 0 as expected.

Orchestrator function code:

    public static async Task<bool> Run(DurableOrchestrationContext context, TraceWriter log)
    {
      var counter = 0;
      while (counter < 4)
      {
        context.SetCustomStatus(new { count = counter });

        var incrementEvent = context.WaitForExternalEvent<bool>("Increment");
        var stopEvent = context.WaitForExternalEvent<bool>("Stop");
        var eventReceived = await Task.WhenAny(incrementEvent, stopEvent);

        // If it's a stop event, break out of the loop
        if (eventReceived == stopEvent)
        {
          break;
        }
        // If it's an increment event, increment the counter
        else if (eventReceived == incrementEvent)
        {
          counter++;
        }
      }
      return true;
    }

**Comment by ethanroday** [comment]
I can work around this by only using a single type of event, `Message`, and have it take the following shape:

    {
      string eventName;
      object payload;
    }

So this is not blocking per se. However, the behavior is still very unexpected.

**Comment by cgillum** [comment]
Thanks for the details, and sorry for the delay in looking at this issue. Which version of the Microsoft.Azure.WebJobs.Extensions.DurableTask nuget package are you using?

**Comment by cgillum** [comment]
I used your code and reproduced the issue using **v1.3.1-rc**. I switched my project to target **v1.2.2-beta3**, and everything works as expected. So this looks like a regression in the latest release.

FYI @gled4er

**Comment by cgillum** [comment]
I think I understand what's happening here. Your code is actually creating multiple "Stop" tasks because of how the loop is constructed, and the one you're waiting on in the final loop iteration is not the one which actually gets completed, thus your orchestrator is not responding.  If you send multiple "Stop" events, I suspect it will actually complete.

I can see how this is non-obvious, so I need to mull on this for a bit to think about the best way to prevent this kind of problem.

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you letting me know about the issue. 

I will share my findings on this thread.

Thank you!

**Comment by cgillum** [comment]
I have created a version of the nuget package which contains a fix for your issue. We have also added a test case for this. Can you give it a try and see if it works for you?

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.3.5-rc

**Comment by ethanroday** [comment]
Works! Thanks for the fix.

**Comment by cgillum** [comment]
Great! Thanks for confirming.
