### ISSUE TITLE
Potential memory leak when using DefaultAzureCredential for Storage Account

### ISSUE THREAD

**Issue by jeromekol** [Azure/azure-functions-durable-extension#2771]
### Description
We use Durable Entities to manage state for one of our applications. The flow looks like this: IoT Hub => Azure Functions => Update Durable entity. We consume around 200 messages per second. Recently we moved from in-process Azure Functions with .NET 6 to out-of-process Azure Functions running .NET 8. Managed Identity is used to connect to the Storage Account for Durable Entities, by configuring the appsetting according to [documentation](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob&pivots=programming-language-csharp#connecting-to-host-storage-with-an-identity). We did not have any issues with .NET 6 and in-process model. However, when we moved to .NET 8 we saw a steady rise of memory (up to 5gb) until the function was eventually restarted by Azure and freeing the memory. We were able to solve that issue by changing from identity-based connection to connection string (incl. storage access key).

### Expected behavior
No steady rise of memory usage.

### Actual behavior
Once the function starts it takes up to one day until the majority of the memory is used up and until the function gets unresponsive. That eventually triggers a self-heal action by the Azure infrastructure and restarts the function.

### Relevant source code snippets
no snippets, just configuration on appsettings.

### Known workarounds
We use Storage Connection strings for the time being.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 1.1.1
- **Azure Functions runtime version (1.0 or 2.0)**: 4
- **Programming language used**: c# (dotnet-isolated)

### Screenshots
> If applicable, add screenshots to help explain your problem.
Memory before and after change (only configuration changes)
![memory_leak_durable_func](https://github.com/Azure/azure-functions-durable-extension/assets/35995674/389aedeb-fbe3-4cde-a3c1-8b80c1ad3014)

Screenshot from WinDbg after analyzing a memory dump:
![windbg_mem_durable_func](https://github.com/Azure/azure-functions-durable-extension/assets/35995674/f235450c-e57c-48e9-b629-6c596795b6dc)

### If deployed to Azure
> We have access to a lot of telemetry that can help with investigations. Please provide as much of the following information as you can to help us investigate!

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**: 
- **Orchestration instance ID(s)**: d16b2edbfc7f42f28b93d17bc64bdca2 (that is an executionId, not sure if it is the one needed)
- **Azure storage account name**:

> If you don't want to share your Function App or storage account name GitHub, please at least share the orchestration instance ID. Otherwise it's extremely difficult to look up information.

**Comment by cgillum** [comment]
Thanks for the detailed analysis! Just to confirm, managed identity + in-processes .NET worked fine, and connection strings + out-of-process .NET worked fine, but managed identity + out-of-process .NET resulted in this memory leak?

@wsugarman have you seen anything like this before in your workloads? The fact that the DurableTask extension shows up in the list of leaking objects makes me wonder if it's something in our stack which is at fault.

**Comment by wsugarman** [comment]
I haven't seen this myself, but perhaps we're not exercising these code paths enough within a small window. It could also be a symptom of trying to marry these two SDKs together (both Azure.Identity and the now defunct WindowsAzure.Storage).

Seeing so many objects is certainly suspicious. Do we invoke IStorageAccountProvider.GetStorageAccountDetails throughout the lifetime of a Durable Functions app, or is it just called in the beginning upon initializing the extension?

**Comment by cgillum** [comment]
@wsugarman that's a good point - not sure about how often we call `IStorageAccountProvider.GetStorageAccountDetails`, but this reminds me that we'll need to update the out-of-process .NET worker extension to use the newer Storage Backend V2 implementation, which has the "better" managed identity integration.

**Comment by lilyjma** [comment]
I believe this is fixed in the latest .NET isolated package [v1.1.5](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.DurableTask/1.1.5
) (which uses Durable Functions extension v2.13.5 that has the fix).

**Comment by lilyjma** [comment]
@jeromekol - Were you able to try out if the latest .NET isolated package resolves the issue?
