### ISSUE TITLE
Remove warning about fixed numer of control queue partitions

### ISSUE THREAD

**Issue by gled4er** [Azure/azure-functions-durable-extension#279]
Hello,

I think it will be good to remove the alert about fixed number of control queue partitions [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-perf-and-scale).

Thank you!

**Comment by cgillum** [comment]
Yep, I already have that change here: https://github.com/MicrosoftDocs/azure-docs-pr/pull/38970. Thank you for pointing this out! I'll go ahead and close this one.
