### ISSUE TITLE
Unable to locate GetStatusAsync 

### ISSUE THREAD

**Issue by aaramians** [Azure/azure-functions-durable-extension#2790]
using .Net 8, Isolated Process
I'm having a very hard time trying to locate GetStatusAsync or matching functionality, in the old world IDurableClient.GetStatusAsync.
migration documentation does not exactly describe how to grab status payload using DurableTaskClient

https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationclient.getstatusasync?view=azure-dotnet

This was used to mitigate an issue while using application gate way, and durable status api not honering X-ORIGINAL-HOST and X-Forwarded-Host, the problem is durable status api is not reachable and a helper function mirror the status/outcome payload.

**Comment by davidmrdavid** [comment]
@jviau: can you chime in on this?

**Comment by jviau** [comment]
I believe you want `DurableTaskClient.GetInstanceAsync`: https://github.com/microsoft/durabletask-dotnet/blob/main/src/Client/Core/DurableTaskClient.cs#L308

> This was used to mitigate an issue while using application gate way, and durable status api not honering X-ORIGINAL-HOST and X-Forwarded-Host, the problem is durable status api is not reachable and a helper function mirror the status/outcome payload.

Another way to workaround this would be to instantiate your own shim `HttpRequestData` class which has the `Url` property set to your original/forwarded host. Then you can call `CreateCheckStatusResponseAsync` and pass in that shim object.

**Comment by nytian** [comment]
Update the document with PR https://github.com/MicrosoftDocs/azure-docs-pr/pull/273552

**Comment by davidmrdavid** [comment]
Closed as it should be documented here now: https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-dotnet-isolated-overview#public-api-changes
