### ISSUE TITLE
Durable function created in Isolated worker in a separate project throwing binding type not registered error

### ISSUE THREAD

**Issue by arunmk-ms** [Azure/azure-functions-durable-extension#2825]
### Description

A durable function created in Isolated worker in a separate project is throwing the below error. I am able to reproduce this issue and a sample project is attached. 

```
The 'HelloCitiesOutside' function is in error: The binding type(s) 'orchestrationTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
The 'SayHelloOutside' function is in error: The binding type(s) 'activityTrigger' are not registered. Please ensure the type is correct and the binding extension is installed.
The 'StartHelloCitiesOutside' function is in error: The binding type(s) 'durableClient' are not registered. Please ensure the type is correct and the binding extension is installed.
```

### Expected behavior
Isolated worker has to be started and the new activity and orchestration function should be available.

### Actual behavior
Isolated worker is started with the above error.

### Relevant source code snippets

[TestApp.zip](https://github.com/Azure/azure-functions-durable-extension/files/15382447/TestApp.zip)

### Known workarounds
All the functions have to be moved to startup project for the activity and orchestration trigger to be enabled. 

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 1.1.3
- **Azure Functions runtime version (1.0 or 2.0)**: 4.0
- **Programming language used**: C sharp

### Screenshots
<img width="845" alt="image" src="https://github.com/Azure/azure-functions-durable-extension/assets/43769805/4de73ec7-e3e8-407d-b031-d2183ec341bf">

**Comment by bachuv** [comment]
Hi @arunmk-ms , it looks like the Durable Functions extension isn't installed or properly configured. Can you check if the project dependencies are getting resolved correctly?

<img width="353" alt="image" src="https://github.com/Azure/azure-functions-durable-extension/assets/15795068/2a285298-ba1d-4ef1-a48f-7978825c1f2d">

Also, in Visual Studio, you can check under "Project" > "Manage NuGet Packages" if the correct Durable Functions Isolated project is installed.

**Comment by arunmk-ms** [comment]
Hi @bachuv , the DurableTask extension is already present. You can see the same in the sample project attached as well.

<img width="332" alt="image" src="https://github.com/Azure/azure-functions-durable-extension/assets/43769805/da358d65-95b3-49b9-b31d-cd81905c6f48">

**Comment by davidmrdavid** [comment]
I downloaded the zip, and I think I understand the set up now - your orchestrator functions are registered in a csproj outside of the main Azure Functions app project. I', not fully certain if this is supported.

@liliankasem - is this something we support in the .NET isolated worker? To split your functions across several projects? Not sure if the function indexing works in this case.

**Comment by satvu** [comment]
@davidmrdavid We do support indexing functions in dependencies (see [here](https://github.com/Azure/azure-functions-dotnet-worker/blob/16fe6c687e1c44a2fbfe11fe2f48fa1e5b34910c/sdk/Sdk.Generators/FunctionMetadataProviderGenerator/FunctionMetadataProviderGenerator.cs#L131)), and I see that the functions in the dependency are are included in the generated metadata for this repro. I wonder if the extension package needs to be installed on the "main" app and not just the dependency? 

The error comes from [this part](https://github.com/Azure/azure-functions-host/blob/62c4472bbf7240ab17e8fd47d1319f158b7c68c3/src/WebJobs.Script/Description/FunctionDescriptorProvider.cs#L266) of the host, and I'm not super familiar with it, but is there a chance extension bundles do not take into consideration extensions in dependencies?

**Comment by satvu** [comment]
Actually, @arunmk-ms can you upgrade the worker SDK to 1.17.2 or higher? Does that fix your issue?

**Comment by davidmrdavid** [comment]
changing the SDK to 1.17.2, as described above, worked for me:

>     <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.17.2" PrivateAssets="All" />
