### ISSUE TITLE
Durable Entities not executed in dotnet isolated worker

### ISSUE THREAD

**Issue by ivankaurov** [Azure/azure-functions-durable-extension#2830]
### Description
After updating `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` NuGet package to version 1.1.3, Durable Entities stopped to be executed.
Issue also reproducible locally on Azure Storage Emulator

### Actual behavior
Durable entities not executed. Message in `control` queues are accumulated and `Dequeue Count` number is growing

### Relevant source code snippets
```csharp
   public static Task DispatchBarrierTrigger(
       this TaskOrchestrationContext context,
       EntityInstanceId id,
       BarrierTriggers trigger)
       => context.Entities.SignalEntityAsync(
           id: id,
           operationName: nameof(OrchestrationGatedBarrier.DispatchTrigger),
           input: trigger)
```

### Known workarounds
Revert `Microsoft.Azure.Functions.Worker.Extensions.DurableTask` back to version 1.1.2

### App Details
- `Microsoft.Azure.Functions.Worker`: 1.22.0
- `Microsoft.Azure.Functions.Worker.Sdk`: 1.17.2
- `Microsoft.Azure.Functions.Worker.Extensions.DurableTask`: 1.1.3
- **Durable Functions extension version (e.g. v1.8.3)**:
- **Azure Functions runtime version (1.0 or 2.0)**:
- **Programming language used**: C# (.net 8.0)

### Screenshots
![image](https://github.com/Azure/azure-functions-durable-extension/assets/8070029/984e1467-e3de-42f7-b8eb-fe4240c53761)

### If deployed to Azure

- **Timeframe issue observed**: since 21st of May
- **Function App name**: `azfun-import-supplierparenting-test-sievo`
- **Function name(s)**: `DataImportCoordinatrEntity` (and other Entity-functions)
- **Azure region**: West Europe
- **Orchestration instance ID(s)**:
- **Azure storage account name**: `azfunstimportsplprntte`

**Comment by th3ragex** [comment]
Probably related: https://github.com/microsoft/durabletask-dotnet/issues/315

**Comment by davidmrdavid** [comment]
Closing as the latest .NET isolated release should have fix this. Thanks!
