### ISSUE TITLE
Make Netherite working in EP1 SKU

### ISSUE THREAD

**Issue by vany0114** [Azure/azure-functions-durable-extension#2832]
As agreed with @davidmrdavid and the Durable Functions team in our call, I'm opening another issue to work towards making Netherite work in EP1 SKU. 

Some links as reference:
https://github.com/Azure/azure-functions-durable-extension/issues/2603
https://github.com/Azure/azure-functions-durable-extension/issues/2603#issuecomment-2125988474

**Comment by davidmrdavid** [comment]
Thanks @vany0114. Commenting here mostly to subscribe to future activity

**Comment by davidmrdavid** [comment]
@vany0114: so do we have clear next steps here?  Are you attempting the "vertical" partitioning we discussed? On my end, the immediate next thing I'd like to do is to merge this PR (https://github.com/microsoft/durabletask-netherite/pull/387) which will provide you with clearer signals than just "client timeout", it will throw a different exception if the partition is 'stuck'.

After that, I'm looking to see if we can do some kind of throttling.

**Comment by vany0114** [comment]
> @vany0114: so do we have clear next steps here? Are you attempting the "vertical" partitioning we discussed?

@davidmrdavid We're planning on that, but I think it will take a while.

**Comment by davidmrdavid** [comment]
Hi @vany0114 - I believe you mentioned you won't be using Netherite anymore. Should we close this issue then?

**Comment by vany0114** [comment]
Yep we can close it, and a friendly reminder about this one: https://github.com/Azure/azure-functions-durable-extension/issues/2534#issuecomment-2158442430 🙏

**Comment by davidmrdavid** [comment]
Thanks, closing this one - replying on the other thread shortly
