### ISSUE TITLE
Remove "preview" from documentation, READMEs, etc.

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#284]
It's no longer in preview when we GA.

**Comment by gled4er** [comment]
Hello @cgillum,

If you agree, I want to help with this issue.

Thank you!

**Comment by cgillum** [comment]
Thanks @gled4er for the offer, it would be great to get your help. Please remember to open the PR against the **release-build-functions** branch in the docs repo.

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you very much for the assignment and reminding me about **release-build-functions**!
