### ISSUE TITLE
Durable Functions Hang When Distributed Tracing is Enabled with Failed to fetch a work-item: The reader's MaxDepth of 64 has been exceeded

### ISSUE THREAD

**Issue by magarma** [Azure/azure-functions-durable-extension#2874]
### Description
When using Azure Durable Functions, the runtime hangs after a certain number of activity function executions. We've noticed this to be between 25-30 executions.
It hangs with a NewtonsoftJson error when trying to get a work-item: The reader's MaxDepth of 64 has been exceeded.
See screenshot below.

### Expected behavior
Orchestrator functions should be able to execute any number of activity functions and complete successfully

### Actual behavior
Orchestrator function hangs after 29 activity function executions

### Relevant source code snippets
This issue was also raised by other user with some sample code.
https://github.com/Azure/azure-functions-durable-extension/issues/2542

### Known workarounds
disabling extensions.durableTask.tracing.distributedTracingEnabled in host.json resolves the issue.

### App Details

![image](https://github.com/user-attachments/assets/16fe13f8-6967-4552-b6b7-167494e4c5be)

- **Durable Functions extension version (e.g. v1.8.3)**: See above
- **Azure Functions runtime version (1.0 or 2.0)**: v4
- **Programming language used**: C# 8.0.107

### Screenshots

![image](https://github.com/user-attachments/assets/aadb1aaa-9095-47fd-b082-b120fe3aa60f)

**Comment by cgillum** [comment]
Do you still have the problem if you use distributed tracing V2?

```json
{
  "extensions": {
    "durableTask": { 
      "tracing": { 
        "distributedTracingEnabled": true, 
        "version": "V2" 
      } 
    } 
  }
}
```

**Comment by magarma** [comment]
Thanks @cgillum , using V2 fixes the problem.
