### ISSUE TITLE
Response from CallHttpAsync does not contain the actual error information

### ISSUE THREAD

**Issue by yuramag** [Azure/azure-functions-durable-extension#2954]
### Description
I am calling `TaskOrchestrationContext.CallHttpAsync()` from my durable function. This call makes an HTTP POST request to another JS/TS function in Azure that looks like this:

```js
export async function execute(value) {
    throw new InternalError('ERROR');
}
```

### Expected behavior
I expect that the response should contain information about the error, such as error message and type.

### Actual behavior
All I get is HTTP 500 status code and an empty string HTTP content.

### Relevant source code snippets

```csharp
var uri = new Uri("https://<app>.azurewebsites.net/api/<func>?code=<key>");
var request = new DurableHttpRequest(HttpMethod.Post, uri)
{
    Content = "<payload>"
};
var response = await runtime.CallHttpAsync(request);
if (!response.StatusCode.IsSuccessful())
    throw new Exception($"Error executing Azure function, HTTP status code: '{response.StatusCode.ToInt()}', error message: <error-from-js-code>"); 
```

### Known workarounds
- No workarounds found

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: `Microsoft.Azure.Functions.Worker.Extensions.DurableTask v1.1.6`
- **Azure Functions runtime version (1.0 or 2.0)**: `AzureFunctionsVersion=v4`
- **Programming language used**: C#, JS/TS

**Comment by cgillum** [comment]
Can you clarify what the response looks like if you hit your JS/TS endpoint with an HTTP client like `curl`? Since your function throws an error rather than directly writing an HTTP response, it's unclear if any content is to be expected. Some HTTP servers will not display the content of an error in the HTTP response for security reasons.

Also, the code snippet you shared doesn't seem to be attempting to read the response content. Can you clarify what C# code you're using to use to read the HTTP response content?

**Comment by yuramag** [comment]
All I get is an empty content in the response, and status code 500.

Are you saying this is by design? Can this behavior be changed somehow? Since I am invoking my own function via this HTTP call I expect to get the original error message back.

If this is by design, I guess I'd have to wrap my function code by `try/catch` and pass the error message to the response manually.

**Comment by cgillum** [comment]
> Are you saying this is by design? Can this behavior be changed somehow?

You'll need to consult with the documentation for your JS/TS server. I don't think you mentioned where this is being hosted other than "Azure".

**Comment by yuramag** [comment]
> You'll need to consult with the documentation for your JS/TS server. I don't think you mentioned where this is being hosted other than "Azure".

Obviously I meant JavaScript function app in Azure: https://learn.microsoft.com/en-us/azure/azure-functions/create-first-function-vs-code-node?pivots=nodejs-model-v4
