### ISSUE TITLE
Non-Deterministic workflow detected

### ISSUE THREAD

**Issue by lipalath-ms** [Azure/azure-functions-durable-extension#2955]
Caught unexpected exception in Part# 3, marking sync job as errored. Exception:
Microsoft.DurableTask.TaskFailedException: Task 'SubOrchestratorFunction' (https://github.com/Azure/azure-functions-durable-extension/issues/1) failed with an unhandled exception: Non-Deterministic workflow detected: A previous execution of this orchestration scheduled an activity task with sequence number 7 named 'GeCountFunction', but the current orchestration replay instead scheduled an activity task named 'UpdaterFunction' with this sequence number. Was a change made to the orchestrator code after this instance had already started running?
at Microsoft.DurableTask.Worker.Shims.TaskOrchestrationContextWrapper.CallSubOrchestratorAsync[TResult](TaskName orchestratorName, Object input, TaskOptions options)
at OrchestratorFunction.RunOrchestratorAsync(TaskOrchestrationContext context)

**Comment by cgillum** [comment]
Your issue description is very vague, but it sounds like you're running into orchestration code versioning issues, described here: https://learn.microsoft.com/azure/azure-functions/durable/durable-functions-versioning.
