### ISSUE TITLE
Enable out-of-proc orchestration starter functions.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-durable-extension#296]
Currently, the [JavaScript orchestration starter function](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-instance-management#starting-instances) shown in the docs does not work, throwing an exception when the host runtime indexes it due to DurableOrchestrationClient being unable to bind to string.

We should fix this so our docs are accurate and JavaScript folks can do what the C# folks do.

Work will also be needed so that we can return the status/event/terminate endpoints JSON that a C# starter provides.

**Comment by cgillum** [comment]
@kashimiz is this issue fixed with your recent binding PR?

**Comment by kashimiz** [comment]
Fixed in that we can do out-of-proc starter functions per output bindings as instructed in our docs, but this part hasn't been implemented or designed:

> Work will also be needed so that we can return the status/event/terminate endpoints JSON that a C# starter provides.

**Comment by kashimiz** [comment]
As of the 1.1.2 release of Azure/azure-functions-durable-js, this has been fixed.
