### ISSUE TITLE
Retry Failed Orchestrations

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-functions-durable-extension#297]
Is it possible to 'retry' an orchestration Instance that is in a failed state? With webjobs and queue triggers i was able to place poison-queue items back into the working queue, which would then continue the process (in my chain of queue-trigger functions).

Is there a similar way to continue a failed orchestration chain in Durable Functions?

**Comment by kashimiz** [comment]
We don't currently have support for this, but retry behavior for failed orchestrations is on our roadmap.

One workaround would be to monitor the status of an orchestration and, if it goes into Failed state, call a new orchestration instance with the same output and ID.

**Comment by cgillum** [comment]
I've opened the following issue to track the ability to "revive" a failed orchestration: https://github.com/Azure/azure-functions-durable-extension/issues/301.

**Comment by vjhbtigoyal** [comment]
@kashimiz - Hi Katy,
I tried with above approach and it rewrites same table rows with new execution id. After reading the comment, i got the feeling that it will be able to figure out which activities have already happened.
Anyways, Thanks :)

Thanks,
Vijay
