### ISSUE TITLE
Automatic Function Retry

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#30]
## Summary
This issue tracks adding automatic "retry-on-failure" parameters to the `CallFunctionAsync` API. The behavior is that it will automatically retry a function invocation if it fails with an error up to a specified number of times and using a specified backoff behavior.

## Motivation
Manually implementing retry behavior in code is possible but can add a lot of complexity. Building it into the API could greatly simplify this experience.

**Comment by tohling** [comment]
Addressed in commit https://github.com/Azure/azure-functions-durable-extension/pull/51
