### ISSUE TITLE
Sub-orchestrations tasks are not completed after 5 minutes

### ISSUE THREAD

**Issue by Kimmen** [Azure/azure-functions-durable-extension#300]
Starts several sub-orchestrations in fan-in/fan-out manor. If the sub-orchestrations are not completed within ~5 minutes, the "outer" orchestration doesn't receive any task-completions (await Task.WhenAny() doesn't complete). 

**Scenario:**
We want a group of users to respond to events using a phone app and they have a certain time to respond to it. So we have a sub-orchestration that awaits a response from the a user and another that initiates this sub-orchestration for each user in parallell. 

If the users respond within 5 minutes (or so) the sub-orchestration-tasks are completed, but otherwise the tasks are not completed.

**Packages:**
* Microsoft.NET.Sdk.Functions (1.0.13)
* Microsoft.Azure.WebJobs.Extensions.DurableTask (1.3.0-rc)

**Comment by cgillum** [comment]
Hi @Kimmen, can you share a basic outline of what your orchestrator function looks like? I didn't quite understand what you mean when you said it doesn't receive any task-completions. I also need to understand how you are enforcing the 5 minute timeout.

And FYI we released an upgrade nuget package today, v1.4.0. Can you upgrade to that version?

**Comment by Kimmen** [comment]
In short, it looks like this:
`public async Task Dispatch() 
{
  IEnumerable<Tasks<SomeResponse>> subOrchTasks = this.CallSubOrchestrations(someList);

  while (this.AquiredEnoughResponses(subOrchTasks ) && NotFinished(subOrchTasks ))
  {
    await Task.WhenAny(GetNonCompleted(subOrchTasks )).Unwrap();
  }
}'

I know, the code is a bit weird, but I want to report back once there are enough reported users. 

if any suborchestration doesn't completes within five minutes, the `await Task.WhenAny(...)` doesn't seem to hit. When inspecting the task's IsCompleted property is false.

Why there's a five minute limit, I have no clue. Can't find any trace that we are setting this. I'll try to reproduce this simpler solution.

Also, tried to upgrade to v1.4.0, but we are getting another issue not related to this one.

**Comment by Kimmen** [comment]
Seemed like upgrading to 1.4.0 fixed it. 

Thanks!
