### ISSUE TITLE
Ability to "revive" failed orchestrations

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#301]
### Problem
There are cases when an orchestrator instance can fail due to a bug, an environment issue, etc. In such cases, the orchestration fails and the process needs to be manually restarted from scratch. This is not ideal because often times the process involved several complex steps, human interactions, etc, and it's not always practical to rebuild that state.

### Proposal
The durable task framework uses an event sourcing model under the hood to manage state. This means that in theory it should be possible to "rewind" back to a previously known good state and restart execution from there. Exposing this as a feature would be a great way to recover failed orchestrations (after the underlying issue has been fixed).

**Comment by cgillum** [comment]
Actually, we already have our intern Catherine working on this one. It reminds me that we need to make her a contributor to this repo so we can properly assign this issue...

**Comment by gled4er** [comment]
Hello @cgillum,

Great!

Thank you for the update!

**Comment by vjhbtigoyal** [comment]
Hi Guys,
Regarding above mentioned feature, this was the most important scenario for us to handle while we are designing a new architecture where we wanted to support replays from failure points if all retries in a workflow fails.
@cgillum - Is it possible to share some estimated time line for this work with us? Would it be part of v2 GA?

Thanks a lot in advance,
Vijay

**Comment by cgillum** [comment]
@vjhbtigoyal yes, this feature will be available no later than the v2 GA.

**Comment by cgillum** [comment]
We've added this to the v1.6.0 release, which is available now. Release notes and documentation will be available soon.

**Comment by jaltin** [comment]
Hi @cgillum,

Great to hear that this has been added to the v1.6.0 release. I would really like to use this in my function apps, but have no idea how to go about it.

Has the documentation for this been made available yet (I haven't found anything related to it)? If so, could you point me to where it is?

Thanks!

Jonas

**Comment by cgillum** [comment]
Hi @jaltin. Yes, we have some initial documentation here:

* https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-instance-management#rewinding-instances-preview
* https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-http-api#rewind-instance-preview

**Comment by jaltin** [comment]
Thanks for the links @cgillum, looks very straightforward to use.

It's currently in preview. Do you have any idea/guesstimate as to when this might come out of preview? Curious as I am hoping to use this in a production scenario as soon as possible.

**Comment by cgillum** [comment]
We don't have a date you for when it will come out of preview. We need a bit more information about how well (and whether) it's working for people first.

**Comment by rogerwhybrow** [comment]
It has been over two years now and it appears this capability is still in preview.

Any word on when this might go GA?

**Comment by cgillum** [comment]
No updates to share at this time. It's something we want to take out of preview but has unfortunately been stuck behind competing priorities.

**Comment by rogerwhybrow** [comment]
Sorry to dwell on this again but this is a feature we would really like to employ in our workloads.

Is there a tentative date for when the "rewind" feature will become generally available? Or alternatively a road-map that highlights where this is in terms of priority?

**Comment by ankitjain91** [comment]
@cgillum  can you confirm if the ability to revive a failed workflow is available in Durable Task Framework as well? We are using it in our project and need to re-run failed workflows.

**Comment by cgillum** [comment]
> can you confirm if the ability to revive a failed workflow is available in Durable Task Framework as well?

Yes, there is a public API exposed for it here: https://github.com/Azure/durabletask/blob/516f9990ebb4fd307949e3060d3c1768a10296ec/src/DurableTask.AzureStorage/AzureStorageOrchestrationService.cs#L1736
