### ISSUE TITLE
Documentation update for Event publishing

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-durable-extension#303]
Hi @cgillum, 

We might forget to update this page. 
However, where can I find the page source? 

https://github.com/Azure/azure-functions-host/wiki/host.json

**Comment by cgillum** [comment]
That's a wiki page, so I think it might need to be updated by someone on the product team. But there is a note at the top saying it's no longer being updated.

The most up-to-date information can be found here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json, and it has the event publishing settings.

**Comment by TsuyoshiUshio** [comment]
Thanks. I'll send pull request to that page.
