### ISSUE TITLE
Map-Reduce Sample

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-durable-extension#304]
Are demo apps from [Serverless Computing in Azure](https://developer.microsoft.com/en-us/events/build/content/serverless-computing-in-azure) session on GitHub?

**Comment by cgillum** [comment]
Not currently. We're working on a more complete map/reduce-like sample that can be shared broadly. I'll re-purpose this issue to track it.

FYI @tohling

**Comment by cgillum** [comment]
A basic map-reduce sample can be found in the AzureSamples repo here: https://github.com/Azure-Samples/durablefunctions-mapreduce-dotnet
