### ISSUE TITLE
Implement event sourcing snapshotting

### ISSUE THREAD

**Issue by peteroden** [Azure/azure-functions-durable-extension#308]
With long execution chains, the replay can take a long time. You can use the ContinueAsNew method to truncate the history at a point in time, but it would be great to implement the ability to snapshot automatically so you don't have to replay the entire history. This could be a configurable setting such that you could specify some threshold, e.g. number of events, before it gets shortened by snapshotting. this would prevent the history from getting too long without having to truncate the entire history in your code.

**Comment by cgillum** [comment]
Agreed this could be useful. The trick is knowing how to rebuild state from a snapshot midway through a function's execution. I'm not sure how solvable that is.

In the meantime, enabling extended sessions is another way to minimize replay time for longer sequences: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-perf-and-scale#orchestrator-function-replay.

**Comment by cgillum** [comment]
I'm still not sure this is going to be possible outside of `ContinueAsNew` scenarios, because the history is tightly coupled with the code and unfortunately the code cannot be automaticlaly updated to reflect the snapshotted history.
