### ISSUE TITLE
Support for HttpRequest/IActionResult in HTTP-specific APIs

### ISSUE THREAD

**Issue by YodasMyDad** [Azure/azure-functions-durable-extension#318]
The latest Azure functions code has moved away from using `Task<HttpResponseMessage>` and `HttpRequestMessage req` and has moved to this format

```
        public static async Task<IActionResult> Run(
                        [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]
                        HttpRequest req,
                        TraceWriter log)
```

Returning an IActionResult and HttpRequest instead of HttpRequestMessage

**Comment by gled4er** [comment]
Hello @cgillum,

I am interested in helping with this issue.

Do you have any recommendation or design guidelines apart from the description above?

Thank you!

**Comment by cgillum** [comment]
Now that Functions 2.0 is GA, I think it's the perfect time to revisit this one.  I was originally thinking we needed to use `#ifdef` for this, but actually we might be able to reference the `Microsoft.AspNetCore.Http.Abstractions` for both the .NET 4.6.1 and the .NET Standard 2.0 implementations.  So basically, we will have two sets of HTTP APIs, one set that works with .NET Framework HTTP APIs and one that works with .NET Core HTTP APIs.

**Comment by cgillum** [comment]
Bumping this one back up. We're planning a Durable Functions 2.0 release, where we drop support for Functions 1.0 and fully embrase Functions 2.0+. This means we can actually replace our legacy HTTP APIs with the new ones (`HttpRequest`, `IActionResult`, etc.)

**Comment by davet44** [comment]
convert HttpResponseMessage to 
IActionResult
