### ISSUE TITLE
Internal tracing improvements needed

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#326]
After investigating some issues in production, we found a few issues with the DurableTask.AzureStorage tracing (which is captured internally by Azure).

- [x] **The version of the DurableTask.AzureStorage nuget package is not traced**: There was a recent issue where two function apps with two versions of this dependency were running, and this was not detected until looking at the details of the traces.
- [x] **Sub-orchestration traces are hard to find**: When filtering traces by Instance ID, it's not possible to see when sub-orchestrations are started because the sub-orchestration "Send" trace uses the sub-orchestrators instance ID instead of the parents. This makes it harder to detect what an instance is doing. Ideally it would use the parent's instance ID. This would also make it more consistent with how WebJobs.Extensions.DurableTask tracing works.
- [x] **Message renewal is not traced**: When activity functions run long, the storage provider will need to periodically update the message to ensure it doesn't become visible on the queue and processed by another worker. This renewal doesn't have any tracing, so it is not possible to know whether it is actually happening.
- [x] **Host lifecycle events are not traced**: Related to https://github.com/Azure/azure-functions-durable-extension/issues/348, host lifecycle events need to be traced so that they can be correlated to other issues/behaviors which may be observed.
- [x] **Host configuration values are not traced**: It's often useful to know how the durable settings on the function app were configured during an investigation. Naturally, any tracing of these settings need to be careful not to expose any secrets.
- [x] **It's difficult to correlate storage provider logs to a specific function app**: This is important when trying to identify whether two function apps are processing messages from the same task hub.
- [ ] **Activity ID traces for WebJobs.Extensions.DurableTask are unreliable**: The activity IDs change somewhat arbitrarily. This isn't critically important to fix but could potentially make it easier to correlate DurableTask.AzureStorage traces with WebJobs.Extensions.DurableTask traces.

**Comment by cgillum** [comment]
The first 3 issues will be included in the v1.5.0 release.

**Comment by cgillum** [comment]
The next two issues have been fixed in the [v1.6.0 release](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.6.0).

**Comment by ConnorMcMahon** [comment]
@cgillum,

What is the status on these last two work items?

**Comment by ConnorMcMahon** [comment]
I have checked off the second to last category, as your work in the v2.3.0 release made that substantially easier.

Do we think that improving the activity ids is worth fixing at this point?

**Comment by cgillum** [comment]
@ConnorMcMahon I think it's worth fixing, though it's probably not high priority. Having this would make certain debugging scenarios easier. It also might make end-to-end tracing and log correlation simpler if it can be done in a way that integrates nicely with our Application Insights support.
