### ISSUE TITLE
History update needs to consider 4 MB limit

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#339]
The `AzureStorageOrchestrationService` code which lives in **DurableTask.AzureStorage** leverages Azure Table Storage Entity Transactions to efficiently and transactionally write history events to table storage. There are a few limitations to entity transactions as described in this documentation: https://docs.microsoft.com/en-us/rest/api/storageservices/performing-entity-group-transactions

The requirements are this:
1. All entities subject to operations as part of the transaction must have the same `PartitionKey` value.
2. An entity can appear only once in the transaction, and only one operation may be performed against it.
3. The transaction can include at most 100 entities, **and its total payload may be no more than 4 MB in size**.
4. All entities are subject to the limitations described in [Understanding the Table Service Data Model](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model).

All of these requirements are honored in the code except for the part in **bold**. Without fixing this, customers with large fan-out scenarios could have their orchestrations stalled indefinitely.

**Comment by cgillum** [comment]
I think the fix should be relatively straight-forward. All changes can likely be made in **AzureTableTrackingStore.UpdateStateAsync**.  While looping through the new history events, in addition to keeping track of the number of events in the batch, we should also try to estimate the number of bytes in the batch.

Currently we have logic like this:

```csharp
// table storage only supports inserts of up to 100 entities at a time.
if (historyeventbatch.count == 99)
{
    etagvalue = await this.uploadhistorybatch(instanceid, executionid, historyeventbatch, neweventlistbuffer, newevents.count, etagvalue);

    // reset local state for the next batch
    neweventlistbuffer.clear();
    historyeventbatch.clear();
}
```
I propose we update it to look like this (with a new `estimatedBytes` local variable):

```csharp
// table storage only supports inserts of up to 100 entities at a time or 4 MB at a time.
if (historyeventbatch.count == 99 || estimatedBytes > 3 * 1024 * 1024 /* 3 MB */)
{
    etagvalue = await this.uploadhistorybatch(instanceid, executionid, historyeventbatch, neweventlistbuffer, newevents.count, etagvalue);

    // reset local state for the next batch
    neweventlistbuffer.clear();
    historyeventbatch.clear();
    estimatedBytes = 0;
}
```

The `estimatedBytes` local variable can be incremented using the UTF-16 size of the relevant string payloads in the table entities. For example:

```csharp
int estimatedBytes = 0;
// ...

for (int i = 0; i < newEvents.Count; i++)
{
    HistoryEvent historyEvent = newEvents[i];
    DynamicTableEntity entity = this.tableEntityConverter.ConvertToTableEntity(historyEvent);
    // ...
    switch (historyEvent.EventType)
    {
        case EventType.ExecutionStarted:
            // ...
            estimatedBytes += Encoding.Unicode.GetByteCount(executionStartedEvent.Input);
            break;
        case EventType.ExecutionCompleted:
            // ...
            estimatedBytes += Encoding.Unicode.GetByteCount(executionCompleted.Result);
            break;
        case EventType.ExecutionTerminated:
            // ...
            estimatedBytes += Encoding.Unicode.GetByteCount(executionTerminatedEvent.Input);
            break;
        case EventType.ContinueAsNew:
            // ...
            estimatedBytes += Encoding.Unicode.GetByteCount(executionCompletedEvent.Result);
            break;
    }
}
```

We already have this `switch` statement, it probably just needs to moved *before* the `UploadHistoryBatch` call.

**Comment by gled4er** [comment]
Hello @cgillum,

Thank you very much for the detailed guidance!

**Comment by cgillum** [comment]
This will go out with the next release.
