### ISSUE TITLE
Structured Logging

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#35]
## Summary
This feature is about emitting structured logs from the trigger code into Application Insights for easier customer diagnostics.

## Motivation
Today there are two types of logs emitted from the extension: structured ETW logs and unstructured trace logs. Customers only have access to the latter and can have it go to the file system or to Application Insights. Ideally the customer can have these structured logs go to Application Insights, making it easier to write rich queries and get useful insights to how their durable functions are running and what they're doing. This will be very important as people start to use the extension in production scenarios.

## Design Notes
The `ILogger` work that Brett did is supposed to support structured logging. We should look into leveraging this within the durable task extension code so that customers have see an query structured logs emitted by our extension.

**Comment by tohling** [comment]
Addressed in commit https://github.com/Azure/azure-functions-durable-extension/commit/e34644df6c35b9f15c283d7a1399ecc9646a0089
