### ISSUE TITLE
Managing more than one orchestrators in single function app

### ISSUE THREAD

**Issue by goldytech** [Azure/azure-functions-durable-extension#352]
Hello,
I've created Azure Function App in which I've a single orchestrator function which manages the entire workflow.

Now I want to add another workflow (i.e. create another brand new orchestrator function) in the same Azure function App.

Will this work ? 
What is the recommended practices in this scenarios. How will the taskhub names manage in this ?

**Comment by SimonLuckenuik** [comment]
You can create multiple Orchestrator functions to create multiple workflows in the same Azure Function App, they just need to have a different _orchestratorFunctionName_ when calling _StartNewAsync_ and they are able to live in the same Hub.

**Comment by goldytech** [comment]
Thanks for help.

**Comment by lak-amith531** [comment]
> _orchestratorFunctionName_

How can we include this in the binding of queueTriggger starter? For example,

```
{
  "scriptFile": "__init__.py",
  "bindings": [
    {
      "name": "msg",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "rorchestrator",
      "connection": "DATALAKE_CS",
    },
    {
      "name": "starter",
      "type": "durableClient",
      "direction": "in"
    }
  ]
}
```
