### ISSUE TITLE
Orchestrator stuck in "Running" status

### ISSUE THREAD

**Issue by mark-r-cullen** [Azure/azure-functions-durable-extension#355]
Hi,

I'm experimenting again with durable functions and have run in to an issue I can't figure out. I've narrowed it down to the following use case:

`[FunctionName("Test")]
        public static async Task RunTest([TimerTrigger("0 */1 * * * *")]
                                         TimerInfo myTimer,
                                         [OrchestrationClient] DurableOrchestrationClientBase client,
                                         ILogger log)
        {
            var instanceId = "Test";

            var existingInstance = await client.GetStatusAsync(instanceId).ConfigureAwait(false);
            if (existingInstance == null || existingInstance.RuntimeStatus != OrchestrationRuntimeStatus.Running)
            {
                await client.StartNewAsync("TestOrchestrator",
                                            instanceId,
                                            new [] { 1 })
                            .ConfigureAwait(false);
            }
        }

        [FunctionName("TestOrchestrator")]
        public static async Task TestOrchestrator([OrchestrationTrigger] DurableOrchestrationContextBase context, ILogger log)
        {
            var ids = context.GetInput<IEnumerable<int>>();

            var tasks = new List<Task>();
            foreach (var id in ids)
            {
                tasks.Add(context.CallActivityAsync<bool>("TestActivity", id));
            }

            await Task.WhenAll(tasks).ConfigureAwait(false);
        }

        [FunctionName("TestActivity")]
        public static async Task<bool> TestActivity([ActivityTrigger] int id, ILogger log)
        {
            try
            {
                await Task.Delay(1000).ConfigureAwait(false);

                return true;
            }
            catch (Exception ex)
            {
                log.LogError(new EventId(), ex, ex.Message);

                return false;
            }
        }`

The activity runs fine, the orchestrator seems to return out fine, but the orchestrator status in the table row is never marked as "Complete" - it is stuck forever as "Running".

Any ideas what I'm doing wrong here? 

edit - don't know what's going wrong with the code formatting in this post either, sorry....

**Comment by cgillum** [comment]
*(I fixed the formatting for you. You can click the Edit button to see what I did)*

Two questions:
1. Which version of Microsoft.Azure.WebJobs.Extensions.DurableTask are you running?
2. Which Azure Functions runtime are you using (v1 or v2)?

Also, what happens if you remove the `ConfigureAwait(false)` from your `Task.WhenAll(tasks)` call in the orchestrator function? I suspect that may be related because it likely messes with how the Durable Task Framework manages task execution, and making the orchestrator get "stuck" like this could be expected.

**Comment by mark-r-cullen** [comment]
Hi

Thanks for your quick reply. I just tried removing the ConfigureAwait from the Orchestrator and it looks like it's working as expected now. Thanks so much!

**Comment by romangobrey** [comment]
Hi there. Have a similar issue.

I have a simple trigger function and orchestrator. Noticed that if an orchestrator function has async in its signature along with Task as an output or generic Task and also has something in the body with await the backup record in azure table stays in Running state... Is it normal? I guess not. As soon as the function ends (exits normally) execution instance is not marked as Completed. If I change the function signature to be sync (e.g. returns void and there is not async word) and function ends - this instance is marked as Completed immediately. The same with async and Task in signature but without code that uses await in the body - also works as expected.

Some code:

```
[FunctionName(nameof(TriggerAsync))]
public async Task TriggerAsync(
    [DurableClient] IDurableOrchestrationClient orchestrationClient,
    [TimerTrigger("0 */1 * * * *")] TimerInfo timer)
{
    _logger.LogWarning("Trigger. Starting new orchestration");

    await orchestrationClient.StartNewAsync(nameof(OrchestrationAsync));
}

[FunctionName(nameof(OrchestrationAsync))]
public async Task OrchestrationAsync(
    [OrchestrationTrigger] IDurableOrchestrationContext context,
    [DurableClient] IDurableOrchestrationClient starter)
{
    var logger = context.CreateReplaySafeLogger(_logger);

    try
    {
        logger.LogWarning($"Orchestration. Doing something...");
        //just an example of async code
        await starter.GetStatusAsync(context.InstanceId);
        logger.LogWarning($"Orchestration. Done");
    }
    catch
    {
        logger.LogWarning($"Orchestration. Error");
        throw;
    }
}
```
