### ISSUE TITLE
Version conflict detected for Newtonsoft.Json on restore in F# sample project

### ISSUE THREAD

**Issue by ztj** [Azure/azure-functions-durable-extension#357]
I was just poking around the samples and ran into this issue when VSCode failed to load the sample project for F#. The console output for dotnet restore follows. 

`Quiet:fsharp zjensen$ dotnet restore
  Restoring packages for /Users/zjensen/src/external/azure-functions-durable-extension/samples/fsharp/DurableFSharp.fsproj...
/Users/zjensen/src/external/azure-functions-durable-extension/samples/fsharp/DurableFSharp.fsproj : error NU1107: Version conflict detected for Newtonsoft.Json. Reference the package directly from the project to resolve this issue.
/Users/zjensen/src/external/azure-functions-durable-extension/samples/fsharp/DurableFSharp.fsproj : error NU1107:  DurableFSharp -> Microsoft.Azure.WebJobs.Extensions.DurableTask 1.5.0 -> DurableTask.AzureStorage.Private 1.2.4 -> Newtonsoft.Json (>= 11.0.2)
/Users/zjensen/src/external/azure-functions-durable-extension/samples/fsharp/DurableFSharp.fsproj : error NU1107:  DurableFSharp -> Microsoft.NET.Sdk.Functions 1.0.13 -> Newtonsoft.Json (= 10.0.3).
  Restore failed in 642.8 ms for /Users/zjensen/src/external/azure-functions-durable-extension/samples/fsharp/DurableFSharp.fsproj.`

I can get it to build by following the suggestion to directly reference one of those versions in the project file. However, I’m not in a position to test whether that actually works.

This is in the v1.5.0 tag, (SHA b13ca16ff99be5b937b5db23e7459cfa150a3c5e)

**Comment by markheath** [comment]
I just tried updating a functions V2 C# project to 1.5.0 and got the same issue. Worked fine on a V1 version of the same project.
 
```
Version conflict detected for Newtonsoft.Json. Reference the package directly from the project to resolve this issue. 
 VideoProcessorV2 -> Microsoft.Azure.WebJobs.Extensions.DurableTask 1.5.0 -> DurableTask.AzureStorage.Private 1.2.4 -> Newtonsoft.Json (>= 11.0.2) 
 VideoProcessorV2 -> Microsoft.NET.Sdk.Functions 1.0.13 -> Newtonsoft.Json (= 10.0.3).
```

My csproj file looks like this:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AzureFunctionsVersion>v2</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.4.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SendGrid" Version="3.0.0-beta5" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.13" />
  </ItemGroup>
```

What's the recommended way to resolve this?

**Comment by markheath** [comment]
I added an explicit reference to Newtonsoft.Json 11.0.2 and it seems to work (only tested locally so far)

**Comment by cgillum** [comment]
Ah, my apologies for being sloppy with my samples testing. Your workaround is correct. This is an issue with the current Microsoft.NET.Sdk.Functions package, which does not match the latest Functions v2 runtime dependencies. The functions team is aware of it and working on a new nuget release.

FYI @ahmelsayed

**Comment by progresivo** [comment]
Had the same issue and solved it by updating to their latest versions the Sdk,Functions package and the WindowsAzure.Storage package, also adding Newtonsoft.Json 11.0.2 as @markheath (only tested locally)
