### ISSUE TITLE
Unable to install the Durable Extension NuGet package

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-functions-durable-extension#36]
I'm trying to create a demo using the Durable Functions binding extension but I'm having issues with NuGet. My current set up is:

- Latest version of VS2017 (15.3.3) 
- Latest version of Azure Functions Extension (15.0.30812)
- Latest version of NuGet

## Steps to recreate:

1. File -> New -> Project -> Cloud -> Azure Functions
2. Update Microsoft.Net.Sdk.Functions to latest 1.0.2
3. Follow the instructions to use Durable Functions here: https://azure.github.io/azure-functions-durable-extension/articles/installation.html 
4. Try to install NuGet package **Microsoft.Azure.WebJobs.Extensions.DurableTask**

## Installation error

```
Restoring packages for C:\Users\chmatsk\Source\Repos\FunctionApp1\FunctionApp1\FunctionApp1.csproj...
Version conflict detected for Microsoft.Azure.WebJobs. Reference the package directly from the project to resolve this issue. 
 FunctionApp1 (>= 1.0.0) -> Microsoft.Azure.WebJobs.Extensions.DurableTask (>= 0.2.2-alpha) -> Microsoft.Azure.WebJobs (>= 2.1.0-beta1-10950) 
 FunctionApp1 (>= 1.0.0) -> Microsoft.NET.Sdk.Functions (>= 1.0.2) -> Microsoft.Azure.WebJobs (>= 2.1.0-beta1).
Package restore failed. Rolling back package changes for 'FunctionApp1'.
```

**Comment by cgillum** [comment]
What does your .csproj file look like? I've seen similar issues before and the resolution was to add the WebJobs package explicitly.

```
<PackageReference Include="Microsoft.Azure.WebJobs" Version="2.1.0-beta1-10950" />
```

Here is what we use in the [sample project](https://github.com/Azure/azure-functions-durable-extension/blob/master/samples/precompiled/VSSample.csproj):

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="2.1.0-beta1-10950" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="2.1.0-beta1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="1.0.0-beta1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="0.2.2-alpha" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Twilio" Version="1.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```

**Comment by lindydonna** [comment]
@cgillum is there a reason you're depending on that specific version? If you could just specify beta1 the problem would go away

The reason this is coming up now is that we've hardcoded a max version for WebJobs and related dependencies. This is to help customers avoid the problem where they bring in a new major version of a dependency and get runtime errors.

**Comment by cmatskas** [comment]
Hi @lindydonna and @cgillum
I've managed to resolve the problem based on Chris's response. My `.csproj` now looks like this:
```    
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="0.2.2-alpha" />    
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.0" />
<PackageReference Include="Microsoft.Azure.WebJobs" Version="2.1.0-beta1-10950" />
```
Thanks both for your help

**Comment by cgillum** [comment]
@lindydonna the timestamp on [MyGet for `2.1.0-beta1`](https://www.myget.org/feed/azure-appservice/package/nuget/Microsoft.Azure.WebJobs/2.1.0-beta1) is several months old and I have several dependencies in `Microsoft.Azure.WebJobs.Host` which were added much more recently.

Is there another package with recent updates that I should be referencing from my package instead?

**Comment by lindydonna** [comment]
@cgillum Good point. I'm not sure the best solution.

@fabiocav Is this a case where we should be rolling forward the NuGet dependencies of Microsoft.NET.Sdk.Functions?  I mentioned in triage last week that we'll need some process around this whenever we add customer-facing functionality.

**Comment by fabiocav** [comment]
I have been talking to @mathewc and we need to push a 2.1.0 update to NuGet. The Event Grid extension depends on that as well. I've created this to track: https://github.com/Azure/azure-webjobs-sdk/issues/1330

**Comment by cgillum** [comment]
Let me know when this happens and I'll take care of updating the DF Nuget package accordingly.

**Comment by fabiocav** [comment]
@cgillum the 2.1.0 packages have been updated: https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.1.0-beta3
