### ISSUE TITLE
Exceptions thrown in Orchestrator function do not surface as failures in Application Insights

### ISSUE THREAD

**Issue by anuragtokhi** [Azure/azure-functions-durable-extension#362]
Exceptions thrown from orchestrator function do not register under Failures or Exceptions in Application Insights. This means that any alerts based on failures count or exception count will not catch these errors.

Here is an example where traces show an exception raised from orchestrator function but it is shown to be successful.

![image](https://user-images.githubusercontent.com/19335004/41801292-474f9ab6-763f-11e8-9879-22e314077bfd.png)

**Comment by cgillum** [comment]
Sorry for the long delay on this issue. We've fixed it in our latest release: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.7.1
