### ISSUE TITLE
Visual Studio Template for V1

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-durable-extension#363]
We don't have Visual Studio Template for V1. We have it for V2,  however, V1 is GA. 

I always copy it from V2 template to create V1 environment. 

https://github.com/Azure/azure-functions-durable-extension/issues/49

In this issue, it is said that 15.5 include the template, however I can't find it on 15.8.

**Comment by jeffhollan** [comment]
Thanks @TsuyoshiUshio  - created a corresponding issue on the templates repo https://github.com/Azure/azure-functions-templates/issues/701
