### ISSUE TITLE
RaiseEventAsync should have a return value to let caller know if the provided instanceId is valid or not.

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/azure-functions-durable-extension#369]
Current signature: `Task RaiseEventAsync(string instanceId, string eventName, object eventData)`

I would like to have RaiseEventAsync to return something letting me know if the workflow _instanceId_ was was running (and will eventually receive the event). What happen if the instance if failed?

**Comment by cgillum** [comment]
Wow, I'm surprised we're not throwing an exception in this case. Same for `TerminateAsync`. We should fix this.
