### ISSUE TITLE
Orchestrator function data lost while calling activity

### ISSUE THREAD

**Issue by SainiAshish** [Azure/azure-functions-durable-extension#379]
We have a orchestrator function which calls an activity. Orchestrator function is called by a orchestrator client. We have logs inside the orchestrator function.
Intermediately when orchestartor function calls the activity some of the properties value gets lost and initialized as null and also for those calls messages are not getting logged to application insights  as well as we are not able to see those messages in log streaming.  But logs in activity are logging properly.

Below is the execution flow:
![image](https://user-images.githubusercontent.com/8440148/42319272-13c251e0-806f-11e8-94a1-b699dcb40cc3.png)

if there is some issue during deserialization then azure function should throw exception.
Problem is that exception is not getting bubbled up from azure function and consumed.
 
This is  the data which is passed from orchestration client which we have verified from the azure function table storage logs
![image](https://user-images.githubusercontent.com/8440148/42318501-dec47880-806c-11e8-9e2c-1a645ba2ce33.png)

data received in activity:
![image](https://user-images.githubusercontent.com/8440148/42318608-2b64d3a6-806d-11e8-9c6c-8129d1278d97.png)

And this issue is happening intermediately even for same message sometimes it worked fine and all the logs get logged properly but whenever the data loss happen it didn't log the messages in orchestrator function..

**Comment by cgillum** [comment]
This looks like a serialization problem with the `DSWebControllerServiceBusMessage` type. Can you share the definition of this class?

**Comment by SainiAshish** [comment]
@cgillum  Please find the class definition.
    [DataContract]
    public class DSWebControllerServiceBusMessage : ServiceBusBaseMessage
    {
       
        public DSWebControllerServiceBusMessage()
            : base(Guid.NewGuid(), ServiceBusMessageTypes.DistributionServiceWebRequest)
        {
        }

        public DSWebControllerServiceBusMessage(Guid requestId, Email sender, List<Email> distributionList, string emailBody, string surveyId, Guid tenantId)
            : base(requestId, ServiceBusMessageTypes.DistributionServiceWebRequest)
        {
            this.Sender = sender;
            this.DistributionList = new List<Email>(distributionList);
            this.EmailBody = emailBody;
            this.SurveyId = surveyId;
            this.TenantId = tenantId;
        }

        
        [DataMember]
        public string AccessToken { get; set; }

       
        [DataMember]
        public bool ExpansionStatus { get; set; }

        [DataMember]
        public Nullable<Guid> CorrelationId { get; set; }

        [DataMember]
        public Email Sender { get; set; }

        [DataMember]
        public List<Email> DistributionList { get; set; }

        [DataMember]
        public string EmailSubject { get; set; }

        [DataMember]
        public string EmailBody { get; set; }

        [DataMember]
        public string SurveyId { get; set; }

        [DataMember]
        public Guid TenantId { get; set; }

        [DataMember]
        public SurveyParams SurveyParams { get; set; }
    }


    [DataContract]
    public class ServiceBusBaseMessage : IServiceBusMessage
    {
        
        public ServiceBusBaseMessage(Guid requestId, ServiceBusMessageTypes formsProServiceMessageType)
        {
            this.RequestId = requestId;
            this.FormsProServiceMessageTypes = formsProServiceMessageType;
        }

        [DataMember]
        public Guid RequestId { get; private set; }


        [DataMember]
        public ServiceBusMessageTypes FormsProServiceMessageTypes { get; private set; }
    }

[DataContract]
    public sealed class Email
    {

        [DataMember]
        public Guid UniqueId { get; private set; }

        [DataMember]
        public String Id { get; set; }

        [DataMember]
        public String Name { get; set; }
        [DataMember]
        public Nullable<Guid> UserId { get; set; }
        [DataMember]
        public String RespondentType { get; set; }

        [DataMember]
        public String Store { get; set; }

        [DataMember]
        public Dictionary<string, string> Personizations { get; set; }

        [DataMember]
        public string ContactId { get; set; }

        [DataMember]
        public string FirstName { get; set; }

        [DataMember]
        public string LastName { get; set; }

        public Email()
        {
            this.UniqueId = Guid.NewGuid();
            this.Personizations = new Dictionary<string, string>();
        }

        public Email(string id, Guid guidId) : this()
        {
            this.UserId = guidId;
            this.Id = id;
            this.Name = String.Empty;
        }

        public Email(string id, string name) : this()
        {
            this.Id = id;
            this.Name = name;
        }

        public Email(string id, string name, Guid guidId) : this()
        {
            this.UserId = guidId;
            this.Id = id;
            this.Name = name;
        }

        public Email(string id, string name, string respondentType, Guid? guidId, string store) : this()
        {
            this.Id = id;
            this.Name = name;
            this.RespondentType = respondentType;
            this.UserId = guidId;
            this.Store = store;
        }
    }


    [DataContract]
    public sealed class SurveyParams
    {
       
        [DataMember]
        public string SurveyUrl { get; set; }

   
        [DataMember]
        public string SurveyId { get; set; }
    }

**Comment by cgillum** [comment]
What happens if you serialize and deserialize this data directly, in a simple console application? Do you see the same behavior?

```csharp
string serialized = JsonConvert.SerializeObject(emailMessageBatches[0]);
var deserialized = JsonConvert.DeserializeObject<DSWebControllerServiceBusMessage>();
// compare "serialized" with "emailMessageBatches[0]"
```

**Comment by SainiAshish** [comment]
No,  It works fine in console app and when run the function app locally. We are facing this issue intermediately only in deployed app in azure.

**Comment by cgillum** [comment]
You mentioned something about logs:

> And this issue is happening intermediately even for same message sometimes it worked fine and all the logs get logged properly but whenever the data loss happen it didn't log the messages in orchestrator function..

Is it possible that you have two different versions of your application deployed to Azure? To be sure, you may want to try stopping and then re-starting your function app. You may also want to try redeploying with a different task hub name value in your host.json, just to make 100% sure there isn't some other version of the code which is interfering with your tests: https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-task-hubs#task-hub-names

**Comment by cgillum** [comment]
Did you try changing the task hub name like I suggested?

**Comment by SainiAshish** [comment]
Thanks @cgillum.

As you suggested i tried changing the task name.
After that it is working fine and I didn't see that issue. But in order to make sure that issue is fixed because we were facing that issue intermediately. 
How can I verify that there was another instance of azure function which was consuming the message and causing the issue.

Also, why do we have to explicitly add the hub name isn't that the function runtime should handle itself.
Are there any limitation which gets imposed on function app after using the hub name

**Comment by cgillum** [comment]
One way you could potentially verify whether multiple function apps were using the same storage account and task hub is by checking your Application Insights logs to see if multiple applications might have been writing to the same AI account. I also suggest looking at the host logs to see if there were any strange errors around the time you did your last update.  If you can share the name of your function app with me, then I can also search through our telemetry to see if there are multiple task hub names in use for your application right now.

As for your task hub questions, please read the [Task Hub documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-task-hubs) and let me know if they don't answer your questions.

**Comment by SainiAshish** [comment]
Thanks @cgillum.

Shared the function app. Also i searched the logs of application insights and table storage logs of function app and didn't find any errors.
Can you please verify in azure telemetry is there any other app which is interfering with our function app.

**Comment by SainiAshish** [comment]
@cgillum 

I have found that if we specify the custom task hub name then it has issues with scaling out.
This is the bug which someone opened.
https://github.com/Azure/azure-functions-durable-extension/issues/111
Can you please let us know if that issue still exists if we specify the custome hub name.

**Comment by cgillum** [comment]
Looking at our scale controller logs, it looks like your function app is switching back and forth between using a task hub named **MFPDistributionService** and **DurableFunctionsHub**. In fact, t appears you are sometimes explicitly specifying a task hub name and sometimes leaving it out.  I would look into your function app deployment pipeline to determine the cause of this (it might even be related to the original issue of data loss).

**Comment by SainiAshish** [comment]
@cgillum 
Those deployment I was trying to verify that specifying that custom hub name actually fixed it or not.
For now I have created the separate storage account for the function app.
Please provide us more information on issue with scaling out of function app if we specify custom hub name.
