### ISSUE TITLE
JS API Implementation Timeline

### ISSUE THREAD

**Issue by deman4ik** [Azure/azure-functions-durable-extension#380]
Have you any timeline on releasing "Not Yet Implemented" JS APIs from Checklist?
I know that durable functions are only in preview now, but we need to know will we be able to completely switch from c# to js in the near future?

**Comment by cgillum** [comment]
FYI @kashimiz 

The plan is to have the JS features GA by this fall, alongside the GA of Functions v2. As part of that GA, all the features in the checklist are expected to be implemented.
