### ISSUE TITLE
Task hub name should default to the function app name

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#383]
Currently task hub names default to "DurableFunctionsHub". Instead, the default task hub name should derive from the function app name. This will have the following benefits:

1. It will make it much harder for developers to accidentally run multiple function apps in the same task hub (see https://github.com/Azure/azure-functions-durable-extension/issues/379).
2. Customer support will have an easier time collecting all relevant logs for a function app if both extension-level and DTFx-level traces use the same distinct task hub name (see https://github.com/Azure/azure-functions-durable-extension/issues/326).

This is a breaking change, so it would need to be introduced as part of a breaking change release.

**Comment by ConnorMcMahon** [comment]
Unfortunately, any default we tried brainstorming up with doesn't play nicely with slots. 

The answer seems to be to remove the default task hub name, and enforce that developers provide a hub name. If we are able to come up with a default that works well with slots in the future, we can always add that in the future without it being a breaking change.

**Comment by ConnorMcMahon** [comment]
This was addressed by PR #652.
