### ISSUE TITLE
Unable to cast object of type 'Microsoft.Azure.WebJobs.DurableOrchestrationContext' Error

### ISSUE THREAD

**Issue by voiply-fyanko** [Azure/azure-functions-durable-extension#384]
When starting JS durable function using C# script (DurableFunctionsHttpStart1) and calling E1_HelloSequence, keep getting the error below.
```
{
runtimeStatus: "Failed",
input: null,
output: "Unable to cast object of type 'Microsoft.Azure.WebJobs.DurableOrchestrationContext' to type 'System.String'.",
createdTime: "2018-07-09T18:38:42Z",
lastUpdatedTime: "2018-07-09T18:38:46Z"
}
```

```
6de7f5f048594fb780bcbdfe8b1a5955: Function 'DurableFunctionJS (Orchestrator)', version '' failed with an error. Reason: System.InvalidCastException: Unable to cast object of type 'Microsoft.Azure.WebJobs.DurableOrchestrationContext' to type 'System.String'.
   at lambda_method(Closure , Functions , Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.TaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TaskMethodInvoker.cs:line 21
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 63
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.TaskOrchestrationShim.Execute(OrchestrationContext innerContext, String serializedInput). IsReplay: False. State: Failed. HubName: MyTaskHub. AppName: qnabuilder. SlotName: Production. ExtensionVersion: 1.2.2.0. SequenceNumber: 15.
```

**Comment by cgillum** [comment]
I noticed the following in your log message: **ExtensionVersion: 1.2.2.0**.

Please upgrade to the latest version of `Microsoft.Azure.WebJobs.Extensions.DurableTask`, which is currently v1.5.0. JavaScript orchestrator functions are not supported in the version you are currently using.

**Comment by voiply-fyanko** [comment]
Thanks, what is the process to upgrade it I it installed automatically.

**Comment by voiply-fyanko** [comment]
Yes that may be the issue, I have extensions.csproj set to right package. Is there  away to execute something similar to npm install that will update the nuget package?

<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <WarningsAsErrors />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.5.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.0-beta3" />
  </ItemGroup>
</Project>

**Comment by cgillum** [comment]
The Azure Portal experience is mostly geared towards playing with the concepts of Azure Functions, but once you're past the learning phase, we recommend "upgrading" to the VS Code environment. That's my recommendation too. There are ways to upgrade extensions in the portal but it's a bit of a hack involving deleting old build artifacts and then running the dotnet build command in the console.

**Comment by magaudef** [comment]
Hi @cgillum , I have the same issue while running the quickstart tutorial in JavaScript.
I have the latest extension version installed:
- "Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.7.0"
- "Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.0.1"
