### ISSUE TITLE
Logs should include the version number of the extension

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#39]
All logs emitted by the Durable Task extension should include the version number of the extension.  This will be important for servicing. It can just be a new column in the existing (structured) logs.

Here is a code snippet which shows how the version information can be fetched:
```
static readonly string ExtensionVersion = FileVersionInfo.GetVersionInfo(typeof(DurableTaskExtension).Assembly.Location).FileVersion;
```

**Comment by tohling** [comment]
Addressed in commit https://github.com/Azure/azure-functions-durable-extension/commit/4dad3957208a874e6e4b7adad0058be0feb1e0a4
