### ISSUE TITLE
How to get the SystemKey automatically?

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-durable-extension#390]
Hi, 

I'd like to automate a call of the HTTP API. However, it requires SystemKey (parameter name code). How can I get the key? It is not host keys.  On the documentation, it is said that we can find by the  CreateCheckStatusResponse. However it requires start an instance. 

Do we have anyway to get the System Key? like function keys?

**Comment by TsuyoshiUshio** [comment]
Or other simple solution is , Add OrchestrationClient GetSystemKey() methods. It is not helpful to secure it(it becomes customer's responsibility) however, the implementation is very easy.  e.g. customer can deploy HttpTriggerWithFunctionKey, we can fetch the function key. However, customer deploy the httptrigger function with durable functions. Hmm... If you have a good idea, please let me know.

**Comment by cgillum** [comment]
I was thinking it might be easier to make API calls directly using public AzureStorageOrchestrationService APIs rather than using HTTP. As you can see, there's no easy way to know the system key. However, if you simply know the storage account, you can still enumerate the instances via DurableTask.AzureStorage.

**Comment by TsuyoshiUshio** [comment]
You right. Using OrchestratorClient  might be easy. (I forget the parameter even I developed it lol). Ok. I'll start with create a function to fetch the value and enumerate the instance value and see if there are instances or not. Since we need one more functions enable this, it is not ideal. If you come up a very good idea to implement to get SystemKey for the HttpAPI, please let me know. Ohter idea is KeyVault integration. For example, if the DurableTaskExtension start, and if there is configuration on the host.json, it upload secrets which customer want to the KeyVault which customer specified.  This is just an idea.

**Comment by TsuyoshiUshio** [comment]
@cgillum I come up with the solution. How about KeyVault integration? Not only the SystemKey, AdminKey and FunctionKey is a big problem of Azure Functions (Not only the Durable). If we can probe KeyVault integration with SystemKey, then do the same thing for FunctionHostScript.  If the customer configure host.json, When the DurableTaskExtension start, it store the SystemKey to KeyVault.

**Comment by cgillum** [comment]
As you mentioned this is a problem for Azure Functions in general, so I would suggest any KeyVault integration we investigate be done in the Azure Functions host and not in the durable extension.

**Comment by TsuyoshiUshio** [comment]
@cgillum SystemKey is the part of the Azure Functions? not only for Durable Functions?

**Comment by cgillum** [comment]
Correct. SystemKey is for any extension in Azure Functions. The MS Graph binding has a SystemKey too. Each extension is assigned a unique SystemKey by the Azure Functions host, but the Azure Functions host manages all the keys itself.

**Comment by TsuyoshiUshio** [comment]
@cgillum admin key and functions keys and System key fetch is always problem of the deployment. It might helpful if we make it enable through the keyvault. e.g. VSTS support keyvault. Maybe we should contribute to the azure functions host repo.

**Comment by cgillum** [comment]
It's possible to fetch them via [Key Management ARM APIs](https://github.com/Azure/azure-functions-host/wiki/Key-management-API),  But is this necessary, or can a storage account connection string + `AzureStorageOrchestrationService` object be used instead?

**Comment by TsuyoshiUshio** [comment]
Thanks. Right. Key Management ARM API is the answer. :) I can't understand the spec at the first time, however, one guy told me how to use it.
