### ISSUE TITLE
Would like more control over scaling durable functions

### ISSUE THREAD

**Issue by ianadavies** [Azure/azure-functions-durable-extension#396]
Would be great if we could have more control over how azure functions scale when the performance of running a fanout orchestration is important. 

See this [post](https://stackoverflow.com/questions/51657553/azure-durable-functions-scaling) 

Would be great if we could have something like this,  rough and would need much more thought but something  along these lines.

```
 var activityBatchRequest = new DurableFunctionBatchRequest<TResult>
            {
                ActivityName = "ComputeItems",
                ApproximateCpuTimePerActivity = new TimeSpan(0, 0, 0, 10),
                RequestedExecutionTime = new TimeSpan(0, 0, 0, 20),
                Activities = activities
            };
            var tasks = orchestrationContext.CallActivityBatchAsync<IEnumerable<TResult>(activityBatchRequest);
```

This way Azure could calculate roughly how many vm's to scale out to so it can attempt to meet the users request time

**Comment by cgillum** [comment]
Thank you for submitting your idea. I reviewed the StackOverflow post and it looks like there are some very good answers there.

If I understand correctly, there are two primary problems that need to be solved:

1. Ensuring that multiple activity functions are not competing with each other for precious CPU time.
2. Ensuring that enough VMs can be provisioned (and quickly) so that your workload can be processed in the smallest possible time.

For (1) I think [this](https://stackoverflow.com/a/51659347/2069) suggestion has you covered. Setting the [maxConcurrentActivityFunctions](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-perf-and-scale#concurrency-throttles) is the proper way to ensure each activity function runs on its own VM.

For (2), the Azure Functions Scale Controller currently adds new VMs gradually based on what it observes in terms of your current activity function backlog. We don't allow customers to directly control how quickly new VMs get added, unfortunately. The product team is looking into adding some new features to Azure Functions as a whole which will help customers have more control over the scale of their function apps. Stay tuned for announcements related to this in the coming months.

**Comment by ianadavies** [comment]
Hi cgillum,

Thanks for the reply. I have tried setting maxConcurrentActivityFunctions to 1 and yes this does work to a point but the scale controller will still queue a lot of items and a number of our simulations will need to run before it "learns" and scales to our needs. 

But also this isn't really good enough for us as in a real life scenario our requests may not happen for a number of days or we may trigger a number of small simulations through the day and/or Azure will have already cleared a number of nodes as they were not in use (this is the behaviour i'm seeing anyway).

Suddenly one very large simulation will need to be executed needing a lot of compute nodes and speed will be of the essence for us and will be one of our biggest selling points.

Another option to point 2 as a possible enhancement would be the ability for us to request that azure provisions of a number of nodes that has a lifetime  as we would know how many nodes we need a minute or so in advance. The provision is then cleared by Azure if its's not used in time or not being consumed.

Then maybe something like this could work?
 ```
var provisionRequest = new DurableFunctionVmProvisionRequest
            {
                VmRequestCount = 200,
                ExpectedExecutionTime = new TimeSpan(0, 0, 0, 30),
         }
var provisionAccepted = await ctx.makeVMProvisionRequestAsync(provisionRequest);

```

**Comment by ianadavies** [comment]
Hi Chris,

Thanks for the reply. I have added another comment to the ticket, see below


Hi cgillum,

Thanks for the reply. I have tried setting maxConcurrentActivityFunctions to 1 and yes this does work to a point but the scale controller will still queue a lot of items and a number of our simulations will need to run before it "learns" and scales to our needs.

But also this isn't really good enough for us as in a real life scenario our requests may not happen for a number of days or we may trigger a number of small simulations through the day and/or Azure will have already cleared a number of nodes as they were not in use (this is the behaviour i'm seeing anyway).

Suddenly one very large simulation will need to be executed needing a lot of compute nodes and speed will be of the essence for us and will be one of our biggest selling points.

Another option to point 2 as a possible enhancement would be the ability for us to request that azure provisions of a number of nodes that has a lifetime as we would know how many nodes we need a minute or so in advance. The provision is then cleared by Azure if its's not used in time or not being consumed.

Then maybe something like this could work?

var provisionRequest = new DurableFunctionVmProvisionRequest
           {
               VmRequestCount = 200,
               ExpectedExecutionTime = new TimeSpan(0, 0, 0, 30),
        }
var provisionAccepted = await ctx.makeVMProvisionRequestAsync(provisionRequest);



________________________________

**Comment by cgillum** [comment]
I understand. We have other customers who have had similar concerns, not just for Durable Functions, but for regular Azure Functions triggers as well (queues, event hubs, etc.).  We have plans to make this possible later this year.

**Comment by ianadavies** [comment]
@cgillum  You mentioned here that you had plans to make this possible later this year. Any news on this?

I have opened this ticket on StackOverflow [https://stackoverflow.com/questions/51657553/azure-durable-functions-scaling/51659347](https://stackoverflow.com/questions/51657553/azure-durable-functions-scaling/51659347)

This is becoming a real problem for us now as we are ready to demo our software to potential clients and I was expecting to be able to scale to 200 nodes since the consumption plan supported this.

Is there anyway we can connect and show you the problems we are having ?


Thanks

**Comment by BenjaBobs** [comment]
@ianadavies 

Hi, after poking around a bit I found that you can achieve *some* control with a [Premium Plan](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale#premium-plan).

By sending the following requests you can control the following.
*Note: It requires the Contributor role for plan and the functions app respectively*
### Instance Count:
```http
PATCH https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Web/serverfarms/<premiumPlanName>?api-version=2018-11-01
Authorization: <bearer token>
Content-Type: application/json

{
    "id": "/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Web/serverfarms/<premiumPlanName>",
    "kind": "elastic",
    "location": "<location>",
    "name": "<premiumPlanName>",
    "properties": {
        "numberOfWorkers": 20, 
    },
    "sku": {
        "capacity": 20, 
    },
}
```

### Pre-warmed instance count:
```http
PATCH https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Web/sites/<functionsAppName>/config/web?api-version=2018-11-01
Authorization: <bearer token>
Content-Type: application/json

{
    "id": "/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Web/sites/<functionsAppName>/config/web",
    "name": "<functionsAppName>",
    "type": "Microsoft.Web/sites/config",
    "location": "<location>",
    "properties": {
        "reservedInstanceCount": 20,
        "functionsRuntimeScaleMonitoringEnabled": false
    }
}
```

It doesn't help you much if you're still set on Consumption Plan though.
