### ISSUE TITLE
Azure Slots Causing Issues for Scheduled Functions

### ISSUE THREAD

**Issue by SqweeeRyan** [Azure/azure-functions-durable-extension#397]
We wrote a new durable function that was scheduling out executions that would range from 1 to 10 minutes out from "now". Everything worked great locally and on test, but we were seeing just some of the executions work in our production environment. After comparing all our settings between local/test and prod, the only difference was that we were deploying to Azure Function staging slots, and then swapping the stage slot with the prod slot.

We disabled our staging slots, and then the durable functions were all firing at the correct time, 100% of the time. So it seems that the Azure Function slots are somehow causing the scheduled functions to not fire properly.

We were using separate storage accounts for the staging slot vs the live production slot.

Hope this is helpful! Let me know if you need any more information from us.

**Comment by jeffhollan** [comment]
Just curious when you say you disabled the slots did you simply delete the slots or actually deploy to an app that didn't have the setting enabled?  Only ask as toggling on the feature also does some changes with how things like keys are managed and may help narrow down investigation.

**Comment by SqweeeRyan** [comment]
We didn't delete the slot, we just turned it off. Attaching a screenshot. We haven't re-deployed the app since turning it off...we'll probably just change the CD process to deploy straight to the production slot and skip the swap step entirely.

![image](https://user-images.githubusercontent.com/40248974/43608389-d7281bd2-9655-11e8-8ffb-2e632b832223.png)

**Comment by cgillum** [comment]
This is using the Consumption Plan, right? I can't think of any explanations for this off the top of my head. If the storage accounts are different, then it's pretty much impossible for the two apps to interfere with each other.

I took a quick peek into our telemetry, and I didn't detect any actual usage of non-production slots by your app. I did notice, however, that you have separate -prod and -test apps (with corresponding prod and test storage accounts). Can you confirm whether the slots feature was actually being used?

Regardless, is it possible that your production and test environments may be sharing some other resource? For example, if your orchestrations are triggered by a vanilla queue or Service Bus trigger, is it possible that both environments could be unintentionally pointed to the same trigger?

**Comment by SimonLuckenuik** [comment]
Did you double-check if your app settings\connection strings are correctly being swapped as sticky\non-sticky?
