### ISSUE TITLE
Retry on Activity with delay - How it will behave in consumption plan

### ISSUE THREAD

**Issue by vjhbtigoyal** [Azure/azure-functions-durable-extension#402]
Hi Team,
I wanted to understand the impact of delays in activity retry in case of consumption plan. During that delay, does orchestrator goes to sleep or it blocks the process?
For ex, If i have a retry of 10 mins delay for 3 times in orchestrator for a activity, in case of consumption plan, will it not work and restart the function(considering consumption plan has been set to 10 mins)? Or will it go to sleep for each of those 10 mins.

var retryOptions = new RetryOptions(
        firstRetryInterval: TimeSpan.FromSeconds(600),
        maxNumberOfAttempts: 3);

    await ctx.CallActivityWithRetryAsync("FlakyFunction", retryOptions, null);

Thanks,
Vijay

**Comment by vjhbtigoyal** [comment]
@cgillum  Sorry to directly tag you here but this issue is open from last 10 days. Could you assign this to someone or have a look at it?

**Comment by cgillum** [comment]
We took a look at this, and internally the durable task framework uses timer messages to implement the retry. The retries are also included in the orchestration history, so it should be safe to have delays longer than 10 minutes.
