### ISSUE TITLE
Custom TaskHub specified, still get DurableFunctionsHub storage object instances created

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#403]
I specified a custom TaskHub for my OrchestratorClient object. While I see the correct Storage Account queues, blob, and table instances, I **also** see queues, tables, and blob instances created prefixed with `durablefunctionshub` which, of course, shouldn't be used because I already gave my own custom hub name to use.

**Comment by cgillum** [comment]
That's probably expected. The server side components are configured to use the default task hub name (unless you changed it) whereas the client-side components are configured to use the new task hub name - so both task hubs would be getting initialized.

Does that sound like a reasonable possibility?

**Comment by cgillum** [comment]
I think we identified the issue in-person today, and it's basically by design as I suggested.
