### ISSUE TITLE
RuntimeStatus "Pending" when created multiple durable functions instance 

### ISSUE THREAD

**Issue by sonnguy** [Azure/azure-functions-durable-extension#404]
My workflow :
 1- Upload files to Blob storage.
 2- Function app trigger blob and call Durable function.
In this case when I uploaded multiple files as same time, sometimes it work well and it create all instances has RuntimeStatus is "Running" but sometimes have a few instance has RuntimeStatus is "Pending".

FUNCTIONS_EXTENSION_VERSION: 2.0.11857
Function V2
Microsoft.Azure.WebJobs.Extensions.DurableTask: 1.5

**Comment by cgillum** [comment]
We made a few reliability improvements in the v1.6.0 release (which is out now) which might help with this scenario. After your function app has been updated with the newest Azure Functions v2 runtime (a breaking change), please give the [v1.6.0 release](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask/1.6.0) a try to see if it improves your results. If it still doesn't help, please reactivate this issue and provide an instance ID for one of the "stuck" instances.

**Comment by sonnguy** [comment]
Ok @cgillum, I will try with your solution and if it still doesn't work i will give more information to investigate. 

Thanks.
