### ISSUE TITLE
Multiple function apps with same storage account and task hubs cause collisions.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-durable-extension#407]
Under the following circumstances, collisions will occur between two Durable Function apps' queues and tables, leading to unexpected behavior:

Two function apps that:
- are running Durable Functions
- share an Azure Storage account
- both have the same HubName defined OR both use the default HubName in their host.json

The current workaround that exists is to explicitly define a different HubName for each function app, but we should consider taking care of this isolation for the user, as Azure Functions does.

**Comment by cgillum** [comment]
We have another issue that tracks using the function app name to generate a default task hub name: https://github.com/Azure/azure-functions-durable-extension/issues/383 (targeted for a v2 release since it is a breaking change). Would that satisfy this issue?

**Comment by kashimiz** [comment]
Ah, yes, it would. I'll close this one as a duplicate.
