### ISSUE TITLE
DurableOrchestrationClient.GetStatusAsync() - ability to accept a list of instance ids and return their status

### ISSUE THREAD

**Issue by vjhbtigoyal** [Azure/azure-functions-durable-extension#410]
Hi,
We have a requirement where we need to get status of around 8-10 instance ids for one of our business operations. Currently the only way looks like calling GetStatus(via Http api or Orchestration Client) multiple times with individual instance id.
Is it possible to expose a new method which can accept list of instance ids and return their status.

Thanks,
Vijay

**Comment by cgillum** [comment]
Given that it's possible to simply query for these 8-10 instances independently (and concurrently) I don't think we would be able to properly prioritize a feature like this with our limited resources.

I would suggest simply creating an HTTP trigger function which makes multiple `GetStatus` calls in parallel using the orchestration client binding. One advantage creating your own custom implementation of this is that you can optimize it for your scenario, whereas we could only create a very generic implementation.
