### ISSUE TITLE
Status "Succeeded" on Application Insights when orchestrator failed

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-durable-extension#411]
If the Activity fails, runtimeStatus will be Failed, but on Application Insights it will succeed.

**Status query result**

```json
{
  "instanceId": "5ad6d773dc3a42a1b74dc89bc5f1097a",
  "runtimeStatus": "Failed",
  "input": {},
  "customStatus": null,
  "output": "***",
  "createdTime": "2018-08-27T07:25:33Z",
  "lastUpdatedTime": "2018-08-27T07:25:34Z"
}
```

**Application Insights**

![image](https://user-images.githubusercontent.com/1356444/44647056-f66b5880-aa17-11e8-9ade-22daf5b5cf91.png)

**Runtime**

- Azure Functions v2
- Microsoft.Azure.WebJobs.Extensions.DurableTask = 1.5.0

**Comment by cgillum** [comment]
Thanks for this information. We'll look into this.

**Comment by shibayan** [comment]
By implementing `TaskOrchestrationDispatcher`, It  always return `CompletedTask` even if the orchestrator fails. Azure Functions Host treats it as successful.

https://github.com/Azure/durabletask/blob/f9cc450539b5e37c97c19ae393d5bb1564fda7a8/src/DurableTask.Core/TaskOrchestrationDispatcher.cs#L400

**Comment by cgillum** [comment]
@shibayan Interesting. Thanks for pointing that out. I will investigate this further to see if we can return something different here.

**Comment by cgillum** [comment]
The fix for this issue has been released: https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.7.1
