### ISSUE TITLE
Events being dropped when firing right after orchestration starts.

### ISSUE THREAD

**Issue by jetedrow** [Azure/azure-functions-durable-extension#413]
I am looking into using Durable functions to replace manually maintained queue-based triggers in my functions to maintain order, etc.

I am attempting to use a variation of the human interaction pattern (albeit only machines interacting with the orchestration).  My problem I believe is the speed at which the process is running.

_Note, all examples have been greatly simplified so that the issue can be explained succinctly._

**Orchestrator Function**
```C#
[FunctionName("Durable_Orchestrator")]
public static async Task Orchestrate([OrchestrationTrigger] DurableOrchestrationContext ctx)
{
	var response = ctx.WaitForExternalEvent<ResponseMetadata>("ResponseData");
	var request = ctx.GetInput<RequestMetadata>();
	await ctx.CallActivityWithRetryAsync("Durable_CreateInteraction", retryOptions, request.RequestId);
	await ctx.CallActivityWithRetryAsync("Durable_SaveRequestMetadata", retryOptions, request);
	using (var cts = new CancellationTokenSource())
	{
		var timeout = ctx.CreateTimer(ctx.CurrentUtcDateTime.AddMinutes(30), cts.Token);
		var winner = Task.WhenAny(response, timeout);
		if (winner != timeout)
		{
			cts.Cancel();
			await ctx.CallActivityWithRetryAsync("Durable_SaveResponseMetadata", retryOptions, response.Result);
		}
	}
}
```
There are two HTTP triggers that are called by external functions: Durable_RequestReceived and Durable_ResponseReceived.

**Durable_RequestReceived**:  This client function gathers some information and starts a new orchestration, passing this information in as the input.  The function then returns success as the data is now stored successfully.
```C#
[FunctionName("Durable_RequestReceived")]
public static async Task<HttpResponseMessage> RequestReceived(
	[HttpTrigger(AuthorizationLevel.Function, "post", Route = "durable/{correlationId:guid}/request")] HttpRequestMessage req,
	string correlationId, [OrchestrationClient] DurableOrchestrationClientBase starter, TraceWriter log)
{
	// ... Business Logic ...
	var request = await req.ReadAsAsync<RequestMetadata>();
	await starter.StartNewAsync("Durable_Orchestrator", correlationId, request);
	// ... Business Logic ...
	return req.CreateResponse(HttpStatusCode.Created);
}
```
There is now some variable background processing that happens in the "real world", as well as the orchestration begins to process this input data and save it to the database.  When this is complete, it waits for an event called ResponseData (or timeout of 30 minutes).

**Durable_ResponseReceived**:  This client function gathers the response data and sends the ResponseData event to this instance of the orchestration. (The data has the same Guid instance id within it.)
```C#
[FunctionName("Durable_ResponseReceived")]
public static async Task<HttpResponseMessage> ResponseReceived(
	[HttpTrigger(AuthorizationLevel.Function, "post", Route = "durable/{correlationId:guid}/response")] HttpRequestMessage req,
	string correlationId, [OrchestrationClient] DurableOrchestrationClientBase starter, TraceWriter log)
{
	// ... Business Logic ...
	var response = await req.ReadAsAsync<ResponseMetadata>();
	await starter.RaiseEventAsync(correlationId, "ResponseData", response);
	// ... Business Logic ...
	return req.CreateResponse(HttpStatusCode.Created);
}

```
If all goes well, the event is picked up by the orchestration, and this response data is saved to the database, and the orchestration completes.

HOWEVER:  Some of these request/response cycles may only take milliseconds to complete.  (The request is guaranteed to happen before the response, and starter.StartNewAsync is guaranteed to be called prior to the event being raised.)

It seems that when the event is raised rapidly after the orchestration is started, it is somehow dropped because the orchestration has not yet reached the code to wait for the event.

**Things I've already tried:**

- Make sure that the orchestration is running prior to raising the event.  This still does not allow the event to fire (no logs of it either).
```C#
var status = await starter.GetStatusAsync(correlationId);
while (status.RuntimeStatus != OrchestrationRuntimeStatus.Running)
{
	await Task.Delay(50);
	status = await starter.GetStatusAsync(correlationId);
}
await starter.RaiseEventAsync(correlationId, "ResponseData", response);
```
- Made sure that the first line of the orchestrator function is to start waiting for the event (see orchestrator function above).
- Make the orchestration function await the event as the first line, and only do processing once all data is returned.  I believe the orchestration may still not be ready to process this event and it is being discarded when a quick response is received.
```C#
var response = await ctx.WaitForExternalEvent<ResponseMetadata>("ResponseData");
```

**Conclusion**
From my trials, I believe that there is a disconnect with the external events not having guaranteed delivery in this circumstance.  Is this the intended behavior?  I thought that I would have been safe to send this event and it would have been processed where it was requested to be, even if the orchestration is currently not waiting for it to be received and is working on something else, or the instance is in a pending state.

If this cannot be completed, is there another way to make this work currently without going back to using queue triggers and manually maintaining state and process order myself?

**Comment by cgillum** [comment]
Thanks for all the details. I suspect that the external events are getting dropped while the orchestrator function is awaiting on the calls to `Durable_CreateInteraction` and `Durable_SaveRequestMetadata`.

In your list of things you already tried, you mentioned the following:

> Make the orchestration function await the event as the first line, and only do processing once all data is returned. I believe the orchestration may still not be ready to process this event and it is being discarded when a quick response is received.

I expect this should have actually worked, _especially_ if you're also waiting for the orchestrator to enter a "Running" state before sending the event. The only time external events should be getting dropped are when the orchestrator is awaiting on something other than that event. Can you confirm that this is not working?

Another suggestion would be to use the [custom status](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-custom-orchestration-status) feature to notify the sending client when it's ready to handle the external event.

In any case, can you share the following?

* The version of the extension you are using
* The Azure region your function app is running in.
* An orchestration instance ID which reproduced the problem.
* A general timeframe for when the orchestration instance mentioned previously was started (even if it's just the date)?

If you executed this in Azure, I can look into our detailed telemetry to confirm the issue.

**Comment by jetedrow** [comment]
Sorry about the slow reply.  I am using the following:
- Microsoft.Azure.Webjobs.Extensions.DurableTask **v1.5.0**
- Microsoft.NET.Sdk.Functions **v1.0.14**
- Currently running in Azure in the **East US** region.

The code was modified to check that the instance was running as well as check for a custom status that was added.

**Durable_ResponseReceived**
```C#
var status = await starter.GetStatusAsync(correlationId);
while (status?.CustomStatus?.ToString() != "WaitingForResponse")
{
    await Task.Delay(50);
    status = await starter.GetStatusAsync(correlationId);
}
await starter.RaiseEventAsync(correlationId, "ResponseData", response);
```
**Durable_Orchestrator**
```C#
var retryOptions = new RetryOptions(TimeSpan.FromSeconds(5), 100) { BackoffCoefficient = 1.75, MaxRetryInterval = TimeSpan.FromMinutes(30) };
ctx.SetCustomStatus("WaitingForResponse");
var response = await ctx.WaitForExternalEvent<ResponseMetadata>("ResponseData");
var request = ctx.GetInput<RequestMetadata>();
await ctx.CallActivityWithRetryAsync("Durable_CreateInteraction", retryOptions, request.RequestId);
await ctx.CallActivityWithRetryAsync("Durable_SaveRequestMetadata", retryOptions, request);
await ctx.CallActivityWithRetryAsync("Durable_SaveResponseMetadata", retryOptions, response);
```
At this time, with the above code, I have been unable to reproduce this, and I thank you for pointing me in the direction of the custom status message.

I believe my statement about awaiting the event as the first line was never done with the "wait" logic in the sending function.  I did both of these independently, and as such the event was fired before the instance entered the Running status.  Sorry for the confusion.

Is there a spot I can place a feature request to be able to send an event to an already running (but not yet waiting for) instance?  This could greatly simplify my code, as I would prefer this wait to happen after the first two activity functions, but would allow for too much time and the event would not be received.  Having guaranteed (eventual) delivery for events like this (possibly with errors if the instance does not exist) would be beneficial for environments where delivery must be guaranteed, but operations can happen in varying orders.

**Comment by cgillum** [comment]
> Is there a spot I can place a feature request to be able to send an event to an already running (but not yet waiting for) instance? This could greatly simplify my code, as I would prefer this wait to happen after the first two activity functions, but would allow for too much time and the event would not be received. Having guaranteed (eventual) delivery for events like this (possibly with errors if the instance does not exist) would be beneficial for environments where delivery must be guaranteed, but operations can happen in varying orders.

You are not the first to ask for something like this. :) Feel free to open a separate GitHub issue for this feature.
