### ISSUE TITLE
Terminate API not available

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#416]
# Problem Statement
I've deployed a Durable Function implementation to Azure and when I kick off the starter I get back the set of API URLs to use to get status, post events, and terminate. The given Terminate URL doesn't work; it simply returns
```json
{
    "Message": "No such API"
}
```
back to me upon HTTP GET to its location

# Environment
* Azure Functions v2 deployed to Azure
* DF Extension v1.5.0

**Comment by cgillum** [comment]
The terminate URL is a POST request (because it has side-effects). GET is not supported.

As a hint, the name of the URL has the verb "Post" in it (terminate**Post**Uri):

```
{
    "id":"XXX",
    "statusQueryGetUri":"XXX",
    "sendEventPostUri":"XXX",
    "terminatePostUri":"XXX"
}
```

**Comment by brandonh-msft** [comment]
bah! thanks and sorry! that's what I get for using Postman's cute little "click a link in a response and we'll create a new request for you" :)
