### ISSUE TITLE
Missing a operation completion log

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-durable-extension#418]
After updating to Durable Functions v1.6, operation completion log is no longer output.

**Durable Functions 1.5**

![image](https://user-images.githubusercontent.com/1356444/44844622-61ba6200-ac86-11e8-92df-2a2d49a5829c.png)

**Durable Functions 1.6**

![image](https://user-images.githubusercontent.com/1356444/44844604-5830fa00-ac86-11e8-9b50-4ebe6646478e.png)

**Comment by cgillum** [comment]
Thanks. Can you provide more information? Which Functions runtime version? Also, did your function actually execute?

**Comment by shibayan** [comment]
Thanks. More env information is following.

Functions Runtime: 2.0.12050-alpha
Execute?: yes, correctly

**Comment by shibayan** [comment]
Sorry, I confirmed that it occurred in HttpTrigger and TimerTrigger. Since it seems to be a runtime problem, I will move the Issue.
