### ISSUE TITLE
Minor Version with breaking change

### ISSUE THREAD

**Issue by Nepomuceno** [Azure/azure-functions-durable-extension#420]
Hi Since the version 1.6 contains a breaking change I would suggest to move it to version 2.0 and unlist the version 1.6 from Nuget.

In case of that being a pre-release including a -beta or something similar as a suffix might fix it. 

Sorry if this seams rude this might be due to my lack of domain of English I just want the best of the project. 

Thank you!

**Comment by Nepomuceno** [comment]
Most of the other extensions are using -beta already
![image](https://user-images.githubusercontent.com/106517/44915142-22455180-ad2a-11e8-98f0-e9be6bcd4368.png)
https://github.com/Azure/app-service-announcements/issues/129

**Comment by cgillum** [comment]
Thank you for your comment. Please allow me to clarify.

1.6 is not a breaking change per-se. From an API perspective, it is fully compatible with previous releases. If you are using it with Functions V1, it is a simple upgrade and there is no interruption. The breaking change is strictly in the Functions V2 host. This is why we are not using a -beta suffix. I hope that helps clarify.
