### ISSUE TITLE
Need to update samples for v1.6.0 release

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#421]
The samples are still written to match v1.5.0. For samples which work with Functions v2, they also need to be updated to match other breaking changes, such as the host.json breaking changes.

**Comment by davidrevoledo** [comment]
@cgillum I can help with that :) what samples ?

**Comment by cgillum** [comment]
I actually went ahead and did this as part of the Functions 2.0 GA release work.
