### ISSUE TITLE
HttpManagementPayload is in the wrong namespace

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#423]
`HttpManagementPayload` is currently in the `Microsoft.Azure.WebJobs.Extensions.DurableTask` namespace. By convention, types that are expected to show up in user functions are supposed to be in the `Microsoft.Azure.WebJobs` namespace.

Note that this is a breaking change.

**Comment by gled4er** [comment]
Hello @cgillum,

Do you think I can help with this issue?

I think it is straightforward but if you have any concerns or suggestions, I will be happy to follow them.

Thank you!

**Comment by cgillum** [comment]
Sure! We will need to wait to check it in for our V2 release, but having it ready in a PR would be helpful.

**Comment by gled4er** [comment]
Great! 

Thank you for the quick reply!
