### ISSUE TITLE
v2 apps encounter 409 CONFLICT from associated Storage Account

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#430]
nupkg v1.6.0

Created a Function App from scratch w/ an associated storage account, all is well here.
I deploy my v2 Function App from Visual Studio 2017. Incidentally I also deployed *identical code* to a v1 Function app.

In the V2 Function App, the App Insights Live Stream shows me continuous 409 CONFLICT errors coming from the Storage Account:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/20270743/45121006-a88bda00-b114-11e8-9de7-ea8712cac17d.png">

The v1 Function App has no such issue and it's worth noting that the v1.5.0 nupkg didn't have this issue.

**Comment by cgillum** [comment]
Some questions:

* One possibility is that there is a regression caused by the recent [Azure Functions v2 update](https://github.com/Azure/app-service-announcements/issues/129). Have you seen this in any non-durable functions apps?
* Is there any way to get more information on these 429s? I expect 429 may have different meanings depending on the context.

**Comment by brandonh-msft** [comment]
Answers:
1. I haven't tried yet but can quickly spin up a v2 app and run it. However they don't interact w/ Storage in the same way, so...
1. I'll dig in to App Insights' logs and get more details on a few of them & post back. standby.

**Comment by brandonh-msft** [comment]
I get some 404s on a standard Function App. Just created an HTTP Trigger one from w/in the portal and hit it a few times:

![image](https://user-images.githubusercontent.com/20270743/45122531-ed197480-b118-11e8-8e62-dedee316bbff.png)

Still working on pulling out details from AI on the DF runs; for whatever reason my AI Events, Metrics, and Failures are all completely blank 😟

**Comment by brandonh-msft** [comment]
Unfortunately for whatever reason my AI instance proper is reporting zero data w/in it. Perhaps something due to the current outage?

Regardless, kicked off the DF one again and saw the 409s and even a 412:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/20270743/45122720-8a74a880-b119-11e8-924c-a6927ca4c981.png">

**Comment by brandonh-msft** [comment]
this has been reported by other users
https://github.com/Azure/azure-functions-host/issues/3363#issuecomment-417759496

looks to be related to the breaking change to v2. closing.

**Comment by cgillum** [comment]
Cool. Thanks for confirming.
