### ISSUE TITLE
Tracking Activity Function completion state while fan-out strategy

### ISSUE THREAD

**Issue by AbhishekTripathi** [Azure/azure-functions-durable-extension#436]
I have following situation in my orchestrator (pseudo code)
```csharp
public static async Task Orchestrator(
            [OrchestrationTrigger] DurableOrchestrationContext context,
            CancellationToken cancellationToken,
            TraceWriter log)
        {
....
var activities = someEnumerable.Select(x=>context.CallActitivityWithRetryAsync.....);
if (context.IsReplaying)
{
    log.Info($"Orchestrator({context.InstanceId}) completed {activities.Count(x => x.IsCompleted)} activities out of total {activities.Count}");
}
var aggregatedOutput = await Task.WhenAll(activities);
}
```

In the above code, I expect the log to emit the completion status during orchestrator replay. The observed behavior is that the completion status is not being updated as the activities are getting completed and the number continues to be 0. 
Expected behavior would be to have the activity Tasks respect the completion status as they are getting completed.

**Comment by cgillum** [comment]
This is by design. A task will never be considered completed until it has been awaited. Your logging code always executes before the call to await, which is why you always see zero completions.

**Comment by cgillum** [comment]
It's best if you think about this like normal C# code.  In a normal C# program, you would not expect to see an asynchronous task marked as completed immediately after you create it and before you await it.

Every call to `CallActitivityWithRetryAsync` creates a new task, whether it's a replay execution or not. That task will not be marked as completed until we actually replay the result onto that newly created task. This happens during the `await`.
