### ISSUE TITLE
Consumption plan: activation and scale-out not working for V2 apps

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#455]
## Issue
Orchestration and activity-triggered functions on **Functions 2.0** running in the Azure Functions **Consumption plan** and using a **non-default task hub name** may not get activated or scaled-out by the Scale Controller.

Function apps which target v1 or do not specify a task hub name are not affected.

## Details
Shortly before the GA release of Functions 2.0, a breaking schema change was made to [host.json](https://github.com/Azure/azure-functions-host/wiki/host.json-(v2)), requiring users to put [durableTask](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#durabletask) configuration inside an `extensions` configuration section. One of the properties users could configure was the `hubName` property.

The Scale Controller was not correctly updated to account for this host.json schema change and therefore is not able to detect the correct `hubName` configuration. Because of this, it's not able to correctly detect when messages are available and does not know to activate or scale out the function app.

## Workaround
To work around this issue, add a duplicate `durableTask` configuration entry to `host.json`. For example, if you have the following in your host.json:

```json
{
  "extensions": {
    "durableTask": {
      "hubName": "MyTaskHub"
    }
  }
}
```
Add a duplicate `durableTask/hubName` entry *outside* of the `extensions` section. For example:

```json
{
  "extensions": {
    "durableTask": {
      "hubName": "MyTaskHub"
    }
  },
  "durableTask": {
    "hubName": "MyTaskHub"
  }
}
```
The two `hubName` values must match. The functions runtime will read the version *inside* the `extensions` section and the Scale Controller will read the version *outside* of `hubName`.

## Fix
The following PR tracks fixing this issue: https://github.com/projectkudu/kudu/pull/2877

**Comment by davidebbo** [comment]
The fix has now been deployed, so this workaround is no longer needed.

**Comment by davidebbo** [comment]
One thing to note is that if you were affected with the issue, you need to explicitely sync the triggers once now that the fix is out. To do this, go to the Function App in the Portal and click the little refresh icon next to the Function App name in the tree.

**Comment by MurrayFoxcroft** [comment]
Still appearing on my functions instance, even after tearing it and related storage and app service plan down and redeploying in full. Runs for a few hours, goes to sleep, click on the refresh on the functions blade and off it goes again.  Please re-open and address. Thanks

**Comment by cgillum** [comment]
@MurrayFoxcroft Let's use the other issue you opened to investigate further: https://github.com/Azure/azure-functions-durable-extension/issues/467
