### ISSUE TITLE
Auto-Start a DurableOrchestrationClient?

### ISSUE THREAD

**Issue by csheets** [Azure/azure-functions-durable-extension#456]
Using a DurableOrchestrationClient function to start an orchestration process -- this orchestration need to be automatically started but not seeing any way to make that happen.  Is there anyway to start an orchestration automatically without a trigger so that it just starts once it is loaded?

My complete orchestration scenario/path is:

DurableOrchestrationClient function (StarterFunc) --> DurableOrchestrationContext function (MainOrchestrationFunc - calls an activity func to get a config used to spawn the following eternal funcs) --> 1 or more Eternal DurableOrchestrationContext function instances (WorkerFuncs) --> several activity functions to do various work and then calls context.ContinueAsNew(tConfig);

so ultimately the idea is to kickoff an integration engine process that has a separate worker instance for cor each "customer" 

thanks.

**Comment by cgillum** [comment]
> Is there anyway to start an orchestration automatically without a trigger so that it just starts once it is loaded?

There isn't a way to start it "automatically" per-se but I kind of want to ask, what does "automatically" actually mean in this context?

The way I think it about is that there is some deployment step to push your function app into production. If some orchestration needs to be always running, then I would have some trigger that is used to "jump-start" all the orchestrations which need to be running right away. So basically it becomes just another step in your deployment pipeline (implemented as a function). Does that make sense?

I'm happy to brainstorm this with you a bit more if you have other thoughts/concerns.

**Comment by csheets** [comment]
Thanks for your reply.  I get what you are saying -- I wasn't thinking about triggering it as part of deployment.  Typically just use the built-in GitHub Azure deployment without additional steps but can think about a custom deployment script or a DevOps deployment pipeline of some sort.  Is that kinda what you were were thinking?
