### ISSUE TITLE
Azure functions Runtime version: 2.0.12115.0 (beta) for java which is in preview can we use it for production?

### ISSUE THREAD

**Issue by pragathikadaganchi** [Azure/azure-functions-durable-extension#457]
We developed an application in java serverless function app with Azure functions Runtime version: 2.0.12115.0 (beta) for java which is in preview can we use it for production? Right now there are no breaking changes in the application and runtime.

**Comment by cgillum** [comment]
This question should be asked at https://github.com/Azure/Azure-Functions. This repository is for Azure **Durable** Functions (which doesn't support Java yet).

Generally speaking, a product should be GA before you attempt to use it in production. Java support for Azure Functions is still in preview, as you mentioned.
