### ISSUE TITLE
Durable functions templates not available in the Azure portal

### ISSUE THREAD

**Issue by jujubesplayground** [Azure/azure-functions-durable-extension#458]
When creating a new method in an azure function, the stqrter, activity and orchestrator templates are not available in the portal. This makes it difficult to have the correct extensions installed in order to use durable functions. 
![image](https://user-images.githubusercontent.com/24315332/46480620-e18d9c00-c7f1-11e8-8856-f6a6c489e89d.png)

**Comment by cgillum** [comment]
I'm able to see these fine:
![image](https://user-images.githubusercontent.com/2704139/46501724-235f1800-c7db-11e8-8e1f-98a690ec7c0b.png)

Are you sure you're using a Functions 2.0 app and not a Functions 1.0 app? These templates are only available for Functions 2.0.

**Comment by jujubesplayground** [comment]
I created a brand new function, in version 2, I still have no template related to durable functions. All I have is 
![image](https://user-images.githubusercontent.com/24315332/46522585-77253c00-c883-11e8-8e45-bcedcb4aaeb2.png)
and here are the settings
![image](https://user-images.githubusercontent.com/24315332/46522635-9d4adc00-c883-11e8-81dc-92b1e25fd8b1.png)
I don't know what I am doing wrong

**Comment by kashimiz** [comment]
Oop, I see it - your function app's language is currently set to node. If you change your ```FUNCTIONS_WORKER_RUNTIME``` app setting to ```dotnet```, you'll get the C# templates when you try to create a new function.

Templates for JavaScript/Node Durable Functions aren't yet available in the portal; we're still working on the orchestration client experience. Once that's ready, you'll see he corresponding templates available!

**Comment by jujubesplayground** [comment]
Thank you for your reply, it makes sense now. Are the durable functions supported in node even though the templates are not available? Or is it safer to stick to C# for now if durable functions are needed? Any idea of the timeline for the roll out of durable functions in node?
    Le vendredi 5 octobre 2018 à 18:44:30 UTC+2, Katy Shimizu <notifications@github.com> a écrit :  
 
 
Oop, I see it - your function app's language is currently set to node. If you change your FUNCTIONS_WORKER_RUNTIME app setting to dotnet, you'll get the C# templates when you try to create a new function.

Templates for JavaScript/Node Durable Functions aren't yet available in the portal; we're still working on the orchestration client experience. Once that's ready, you'll see he corresponding templates available!

**Comment by jujubesplayground** [comment]
Yes I am 
    Le jeudi 4 octobre 2018 à 22:41:59 UTC+2, Chris Gillum <notifications@github.com> a écrit :  
 
 
I'm able to see these fine:


Are you sure you're using a Functions 2.0 app and not a Functions 1.0 app? These templates are only available for Functions 2.0.

**Comment by cgillum** [comment]
Durable Functions in JavaScript is supported as a preview feature currently. We have several samples you can use to get started: https://github.com/Azure/azure-functions-durable-extension/tree/master/samples/javascript

As part of getting the JavaScript support to GA, we will also be adding these templates. The GA of JavaScript Durable Functions is scheduled to happen before the end of the year.
