### ISSUE TITLE
HubName property in host.json not being used?

### ISSUE THREAD

**Issue by csheets** [Azure/azure-functions-durable-extension#461]
For some reason the custom HubName property value that I have set in host.json file is not being read used in  the local Azure emulator or when deployed to Azure.  See output below for local emulator. For 
Azure deployment have verified by looking at the names of storage queue and table names. Must be missing something somewhere?

Here is the project host.json content:
```
{
  "version": "2.0",
  "durableTask": {
    "HubName": "TMWOutHubv1"
  }
}
```

And here is the output from the local emulator: (I have also confirmed that host.json with the HubName property is in the project path "bin\Debug\netstandard2.0\" dir):

info: Host.General[0]
      Building host: startup suppressed:False, configuration suppressed: False
info: Host.Startup[0]
      Reading host configuration file 'F:\GitHub\<<project path here>>\bin\Debug\netstandard2.0\hos
t.json'
info: Host.Startup[0]
      Host configuration file read:
      {
        "version": "2.0"
      }
[10/5/2018 3:55:57 PM] Initializing extension with the following settings: Initi
alizing extension with the following settings:
[10/5/2018 3:55:57 PM] AzureStorageConnectionStringName: , MaxConcurrentActivity
Functions: 40, MaxConcurrentOrchestratorFunctions: 40, PartitionCount: 4, Contro
lQueueBatchSize: 32, ControlQueueVisibilityTimeout: 00:05:00, WorkItemQueueVisib
ilityTimeout: 00:05:00, ExtendedSessionsEnabled: False, EventGridTopicEndpoint:
, NotificationUrl: https://0.0.0.0:7071/runtime/webhooks/durabletask, LogReplayE
vents: False. InstanceId: . Function: . HubName: DurableFunctionsHub. AppName: .
 SlotName: . ExtensionVersion: 1.6.2. SequenceNumber: 0.

**Comment by SimonLuckenuik** [comment]
Starting at V2, Hubname is now located under extensions:

https://github.com/Azure/azure-functions-durable-extension/blob/master/samples/precompiled/host.json

```
{
  "version": "2.0",
  "logging": {
    "applicationInsights": {
      "sampling": {
        "isEnabled": false
      }
    }
  },
  "extensions": {
    "http": {
      "routePrefix": ""
    },
    "durableTask": {
      "HubName": "SampleHubVS"
    }
  }
}
```

**Comment by cgillum** [comment]
Simon is correct. V2 changed the location of extension settings. You can find more details here: https://github.com/Azure/azure-functions-host/wiki/host.json-(v2)

**Comment by csheets** [comment]
thanks
