### ISSUE TITLE
[Feature/Idea] Callback capability?

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#464]
Am wondering if it'd be possible/useful for Durable Functions to support a `callback` query parameter or JSON property in Body that would allow it to send the result of of the `statusQueryGetUri` back to a caller when the `runtimeStatus` changes to `Completed` (or `Failed`).

This seems like it could be incredibly useful, thought I'd propose it and get some feedback

**Comment by cgillum** [comment]
We might already have this feature (currently in preview): https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-event-publishing. Let me know if this is what you had in mind.

**Comment by brandonh-msft** [comment]
ah yes i had forgotten about the EG integration. good call, thanks!
