### ISSUE TITLE
Possible QueryString Encoding Issue Causing NullReferenceException

### ISSUE THREAD

**Issue by garfbradaz** [Azure/azure-functions-durable-extension#470]
I first posted this Issue on _stackoverflow_ [here](https://stackoverflow.com/questions/52738284/correct-use-of-azure-durable-function-serializing-complex-objects) and @cgillum kindly answered and asked me to post here. I will though add that question here as well.

So I'm prototyping some *Azure Durable Functions*, to try and understand to see if they will fit within a proposed solution for our internal API system.

Based on examples, I've created a *Orchestrator Client* (`HelloOrchestratorClient.cs`), that responds to a `HttpTrigger`. This client extracts some information from the original request, then proceeds to fire off a *Orchestrator Function* (`HelloOrchestrator.cs`) passing in some of the information extracted:

### Complex HelloOrchestratorClient.cs:

```c#
[FunctionName("HttpSyncStart")]
public static async Task<HttpResponseMessage> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, methods: "get", Route = "orchestrators/{functionName}/wait")]
    HttpRequestMessage req,
    [OrchestrationClient] DurableOrchestrationClient starter,
    string functionName,
    ILogger log)
{       
    HttpReq originalRequest = new HttpReq() {
            DeveloperId = GetDevKey(req,apiHeaderKey),
            QueryString = req.RequestUri.Query,
            APIName = GetQueryStringValue(req,APIName),
            APIVersion = GetQueryStringValue(req,APIVersion)

    };
    string instanceId =   await starter.StartNewAsync(functionName, originalRequest);

    TimeSpan timeout = GetTimeSpan(req, Timeout) ?? TimeSpan.FromSeconds(30);
    TimeSpan retryInterval = GetTimeSpan(req, RetryInterval) ?? TimeSpan.FromSeconds(1);

    return  await starter.WaitForCompletionOrCreateCheckStatusResponseAsync(
        req,
        instanceId,
        timeout,
        retryInterval);

}
```
The `HelloOrchestrator.cs` simply for now is just calling off to one of our internal API's and returning a `JsonProduct` payload (Simple POCO describing, you guessed it, a title), using a `ActivityTigger` named `HelloOrchestrator.APICall` to make the API call itself. 

### Complex HelloOrchestrator.cs:

```c#
[FunctionName("E1_JsonProduct")]
        public static async Task<List<JsonProduct>> Run(
            [OrchestrationTrigger] DurableOrchestrationContextBase context,
            ILogger log)
        {
            List<JsonProduct> output = new List<JsonProduct>();
            HttpReq r = context.GetInput<HttpReq>();
            if(r != null)
            {
                if(r.DeveloperId == null)
                {
                    return output;
                }
                output.Add(await context.CallActivityAsync<JsonProduct>("E1_CallAPI",r));
                return output;
            }
            return output;
        } 

[FunctionName("E1_CallAPI")]
public async static Task<JsonProduct> APICall([ActivityTrigger] HttpReq req,
    ILogger log)
{

    JsonProduct products  = null;
    string u = $"{baseAddress}{req.APIVersion}/{req.APIName}{req.QueryString}";  

    var request = new HttpRequestMessage(HttpMethod.Get, u);
    request.Headers.Accept.Add(
        new MediaTypeWithQualityHeaderValue("application/json")
    );
    request.Headers.Add("x-apikey",req.DeveloperId);
     log.LogInformation($"URL calling = '{request.RequestUri.AbsoluteUri}'.");
    HttpResponseMessage response = await client.SendAsync(request);
    // return await response.Content.ReadAsStringAsync();
    if(response.IsSuccessStatusCode)
    {
        var formatter = new JsonMediaTypeFormatter
        {
            SerializerSettings = HelloProj.CosmosDB.Models.Products.Converter.Settings
        };

        products = await response.Content.ReadAsAsync<JsonProduct>(new [] {formatter});
    }
    return products;
}
```
*Side Note*: The plan is if I can get this to work, is to fan out a bunch of processes to different API's and fan back in again and merge the JSON payload and return it back to the originator.

### Issue I'm experiencing

So, when my `List<JsonProduct>` is returned back from `HelloOrchestrator.Run`, I receive the following `NullReferenceException` found on this [Gist (Big stack trace)](https://gist.github.com/garfbradaz/b1d98f6bf61718c9b4f5a88c7ff6050b) and I receive a **500 response** from the *Orchestrator Client*.

The following proves the output returned does actually have an object at runtime:

![Image Posted on SO](https://i.stack.imgur.com/ToU0L.png)

Could it be due to the complexity of `JsonProduct` (Again find the model classes [here](https://gist.github.com/garfbradaz/386cd3a37934b5ff90724c9d7026baac))? I ask, because when I swap out my *Orchestrator Function* for a simpler model structure, I ***don't*** receive a 500, I receive my JSON Payload.

This example shows the *Simple Orchestrator Function* `HelloOrchestrator.cs`, returning a simple `TestToDo` ([Gist for model](https://gist.github.com/garfbradaz/d19fa06eb1a7d6ca80a6b308775f31c5)) flat object that doesn't error:

### Simple HelloOrchestrator.cs:

```c#
 [FunctionName("E1_Todo")]
    public static async Task<TestToDo> RunToDo(
    [OrchestrationTrigger] DurableOrchestrationContextBase context,
        ILogger log)
    {
        HttpReq r = context.GetInput<HttpReq>();
        TestToDo todo = new TestToDo();
        if(r != null)
        {
            todo = await context.CallActivityAsync<TestToDo>("E1_CallAPITodo",r);
        }
        return todo;
    }

[FunctionName("E1_CallAPITodo")]
public async static Task<TestToDo> APITodoCall([ActivityTrigger] HttpReq req,
    ILogger log)
{

    var request = new HttpRequestMessage(HttpMethod.Get, "https://jsonplaceholder.typicode.com/todos/1");
    request.Headers.Accept.Add(
        new MediaTypeWithQualityHeaderValue("application/json")
    );
     log.LogInformation($"URL calling = '{request.RequestUri.AbsoluteUri}'. for {req.QueryString}");
    HttpResponseMessage response = await client.SendAsync(request);
    return await response.Content.ReadAsAsync<TestToDo>();
```

## More Information

If you require my full prototype projects, you can find them here:

 - [Complex Project (Throws 500 and exception)][5]

When you run it, use the following in something like Postman (After F5ing it):

> http://localhost:7071/api/orchestrators/E1_JsonProduct/wait?timeout=20&retryInterval=0.25&api=products&apiVersion=v1&filterByImprints=w%26n&limit=20

Interesting ([Question](https://stackoverflow.com/a/52750858/393581) that  @cgillum asked in the SO post, was the error could be due to an QueryString encoding. So I tested again using the following and it **worked**, so it seems @cgillum could be right:

> http://localhost:7071/api/orchestrators/E1_JsonProduct/wait?timeout=20&retryInterval=0.25&api=products&apiVersion=v1&filterByImprints=WANDN&limit=20

FYI: Both **W&N** and **WANDN** are valid values for our *filterByImprints* parameter.

 - [Simple Project (No 500 or Exception thrown)][6]

When you run it, use the following in something like Postman (after F5ing it):

> http://localhost:7071/api/orchestrators/E1_Todo/wait?timeout=20&retryInterval=0.25

  [5]: https://github.com/HachetteUK/github-issue-demos/tree/master/Azure-Function-Demo-Complex
  [6]: https://github.com/HachetteUK/github-issue-demos/tree/master/Azure-Function-Demo-Simple

**Comment by garfbradaz** [comment]
I will pull down the Azure Functions project and reference it in my project. and try and clean some more info.

**Comment by garfbradaz** [comment]
@cgillum This is still on my list of todos to get you more info.

**Comment by cgillum** [comment]
This will be fixed in the next release.
