### ISSUE TITLE
Can't mock or use DurableActivityContext in unit tests

### ISSUE THREAD

**Issue by sam-piper** [Azure/azure-functions-durable-extension#487]
Hi there,

I'm able to mock `DurableOrchestrationClient` and `DurableOrchestrationContext` types in my unit tests using the respective abstract base classes provided in the durable task framework.

However, as of v1.6.2, there's no equivalent for the `DurableActivityContext` class which I'm using in several of my activity triggers, and it cannot be constructed as there is only an internal constructor. I think there should be an abstract base class provided for this type as well, so that it can be mocked using common frameworks such as Moq or NSubstitute, in alignment with the design pattern you've already established.

For now I'm working around this issue by declaring these activity trigger parameters as objects, and casting to the desired `DurableActivityContext` type inside the function method, so that I can pass my own mock objects directly, however this isn't  ideal.

**Comment by cgillum** [comment]
We didn't create an abstract base class for this type because this type technically isn't needed. For example, if your parameter type is `int` then you can use `int` as your trigger parameter type instead of `DurableActivityContext`.

We call this out in the docs here: [Unit testing activity functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-unit-testing#unit-testing-activity-functions)

**Comment by sam-piper** [comment]
That's fine if your activity takes an input parameter - if it doesn't and you pass null to the activity as its input, then the design pattern falls a bit short, as you have to declare something for the ActivityTrigger attribute to be attached to, the framework injects DurableActivityContext for you and you can't mock this, other than by using object at the method signature level. Unit testing an activity method should be straightforward for both parameter-driven and parameter-less activities.

I still think that a base class is needed here for completeness.

I think you've closed the issue a bit prematurely and dismissively.

**Comment by cgillum** [comment]
Another user made a suggestion about why this is necessary. Let's use the other issue to track: https://github.com/Azure/azure-functions-durable-extension/issues/414
