### ISSUE TITLE
Visual Studio Templates

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#49]
Templates are needed to make it easy to create new Durable Functions triggers/bindings in the Visual Studio development experience.

**Comment by cgillum** [comment]
The Visual Studio experience for Functions 2.0 has been punted out to GA.

**Comment by cgillum** [comment]
Hey, @soninaren have the VS templates for Durable Functions been released?  If so, we can close this issue.

**Comment by soninaren** [comment]
Yes, it has been release for VS preview 15.5 or later.
