### ISSUE TITLE
Use SQL server or PostgresSql to store Workflow state instead of Azure Storage

### ISSUE THREAD

**Issue by VenkateshSrini** [Azure/azure-functions-durable-extension#491]
Hi All,
We are using one of the cloud foundry implementation to host the mico service application. Now that we can run the Azure function and Azure Durable function in .NET core and Docker, We wanted to try the same in org, Since my org is still on 100% on prem (soon they are evaluating some public clouds. Azure is one of them. But their soon will be a few years I guess :)) we cannot allow anything, even the state of workflow to be stored in any public case. 
Though the Azure function/ Durable function satisfies our requirement 100%, the only thing that holds us back is the dependency on Azure storage. 

I guess the main aspects of Azure storage used by Durable function is Azure table and Azure queue. Can this be made sought of Injectable, so that we can substitute the Azure table with SQL server or PostgreSQL and Azure storage queue with Rabbit MQ/Redis/Event sourcing using PostgreSQL and Martin framework

**Comment by cgillum** [comment]
The underlying [Durable Task Framework](https://github.com/Azure/durabletask) (DTFx) already supports injectable storage providers. To make your scenario work, the first step would be implementing a SQL/Postgres provider in the DTFx repo. @fbeltrao, was it you who created a prototype of a SQL provider for DTFx?

Once the new provider is implemented, we would need to make an update to Durable Functions to support swapping out the storage provider for other providers. We don't currently have plans to support this, though long term it's something we're definitely interested in if it can open up new scenarios like yours or allow for better perf/scale.

**Comment by VenkateshSrini** [comment]
Is there some blog that will help me to do it with some code samples please

**Comment by VenkateshSrini** [comment]
Is there not any step by step docs which tells at the minimum what should be implemented to achieve this

**Comment by fbeltrao** [comment]
The way I learned was looking at the simple implementation provided by the emulator:
https://github.com/Azure/durabletask/tree/master/src/DurableTask.Emulator

Here you'll find more about the state (queues, history, state, lease management):
https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-perf-and-scale

**Comment by gled4er** [comment]
Hello @VenkateshSrini,

No, we need to work with @cgillum to make this code production ready. I will leave @fbeltrao to give more information about the SP.

Thank you!

**Comment by fbeltrao** [comment]
SQL scripts are located here: https://github.com/fbeltrao/durabletask/tree/azure-functions-persistence-abstraction/src/DurableTask.CosmosDB/SQL. The implementation relies on SQL Server memory optimised tables and stored procedures. 

As @gled4er mentioned, our implementation was an experiment.

**Comment by VenkateshSrini** [comment]
OK.I will try build something with but at the same time since Postgres and MySQL and supported as managed offering in Azure, if the same thing can be done one of them at least then it will be great. I would suggest PostgreSQL as if you see it can be made to act as a document storage as well as aven store using Martin.
