### ISSUE TITLE
Documentation for GetStatus Paging HTTP APIs

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#496]
Since PR https://github.com/Azure/azure-functions-durable-extension/pull/473 is finished, we will need documentation for it so that people can discover it.

I believe we only need to update the following article:

* https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-http-api

**Comment by TsuyoshiUshio** [comment]
@k-miyake This is the issue.

**Comment by k-miyake** [comment]
@cgillum @TsuyoshiUshio 
OK, I will try it in a few days.

**Comment by cgillum** [comment]
This work has been completed.
