### ISSUE TITLE
function.json settings need to resolve templated strings

### ISSUE THREAD

**Issue by christopheranderson** [Azure/azure-functions-durable-extension#50]
In function.json, settings can specify templates in their values. For instance: "%myappsettinng%" will replace that value with a value from an app setting named "myappsetting".

This is important for #27 (Versioning) because we need to do models like "myOrchestration-%version%" to handle graceful versioning rollover.

**Comment by cgillum** [comment]
Re-purposing this issue to track the `durableTask.HubName` in host.json. The current versioning strategy has shifted away from changing function names. Instead, we'll rely on the use of separate function apps with separate task hubs configured. The task hub is configured in host.json, so we'll need that setting to be resolvable via app settings.

**Comment by cgillum** [comment]
This capability was added in the **v1.7.0** release.
