### ISSUE TITLE
WaitForExternalEvent has no overloaded version with no type

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#511]
**Summary**
A durable function eventName callback url expects application/json.  The fact that that is forced makes can lead to some confusion since context.WaitForExternalEvent<T>.  That function should be overloaded not to take a type.  Since if you specify <string> and pass no body, it doesn't get called, with no exception.   It appears to be attempting to coerce json to whatever type is given, but that appears to silently fail with no logging or anything and the post to the callback uri returns 202 which is expected.​

**Problem Statement**: Currently, it is not possible for partners to create a Durable Function that uses "WaitForExternalEvent" without giving a type. The partner wants to be able to be able to use this method to wait for an event with no body.

**Desired Experience**: Durable Functions should provide a version of the "WaitForExternalEvent" method without giving a type.

**Comment by cgillum** [comment]
I think I understand the ask, which is for a version of `WaitForExternalEvent` without a type parameter. However, I didn't understand why this is needed. Can you elaborate, or provide an example?

**Comment by brandonh-msft** [comment]
This is so they didn't have to provide a body/return value in their event. Just fire it as a "signal" instead of passing a message/value.

**Comment by cgillum** [comment]
Don't users have the option of passing `null`?

**Comment by brandonh-msft** [comment]
yes but then what is `<T>`? This feels more like "hacking around" the API rather than using it for its intended purpose. A `WaitForExternalEvent()` non-generic overload would make this look & "smell" cleaner.

**Comment by cgillum** [comment]
`<T>` can be anything, including `object`. It's a pretty painless workaround.

> This feels more like "hacking around" the API rather than using it for its intended purpose. A WaitForExternalEvent() non-generic overload would make this look & "smell" cleaner.

This is the feedback I was looking for, and it is valid. It was not clearly called out in the original issue as a workaround so I wasn't sure whether you were aware of it - hence my questions.

**Comment by brandonh-msft** [comment]
rock on. i'm considering working on a PR for this.
