### ISSUE TITLE
Instances in the "Pending" state but actually completed

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#520]
There is a race condition in the `StartNewAsync` API implementation which can cause instances to be reported as "Pending" when they are actually running or completed. This happens because starting an orchestration and setting it's initial status is a non-transactional action. Things happen in this order:

1. A message is queued to start the instance
2. A "Pending" record is written to the Instances table

It's possible that between (1) and (2) that an orchestration starts and completes, resulting in a completed orchestration with a "Pending" status.

**Comment by gorillapower** [comment]
@cgillum I have a function that has been in pending for three days, i think it may related to this, although my function is a javascript function. If i look in the history table, i can see that the function seems completed, but on the instances table it is in 'pending' state. 

Is there a way to rectify this in the meantime (cancel, roll back, etc)?

**Comment by cgillum** [comment]
Unfortunately there's no way to roll it back. You can create a new instance with the same ID or you can manually edit the state in Azure Storage.

To update the appropriate record in Azure Storage, look for the {TaskHubName}Instances table, use the instance ID as the partition key, and manually update the "Pending" column with "Completed".
