### ISSUE TITLE
Limit the number of actions per orchestration

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#522]
Performance of orchestrations can drop significantly if an instance has too large of a history. For that reason, we should limit the maximum number of actions a single orchestration instance can make. If more actions are needed, users can break their large orchestrations into sub-orchestrations or use `ContinueAsNew` to limit the size of their history.

**Comment by SimonLuckenuik** [comment]
Assuming that when reaching the maximum number of actions, the Workflow will be suspended or something similar, I think we need to keep in mind that it can be fairly easy to reach a maximum without realizing it is possible. 

For example: imagine a simple scenario where a workflow is doing retries on an activity (with small change to activity input data) at regular interval while an external dependency is unavailable, you can easily have the number of actions increase a lot.

Some suggestions:
- Maybe adding a way to opt-out or configure that limit
- If ContinueAsNew is considered, we need to make sure that it is atomic and that no message can be lost (WaitForExternalEvent)
- Consider adding a new "snapshot" concept, where a user creates a snapshot and replay starts from that snapshot, preventing a complete replay of the states (and prevent loading associated data)

**Comment by cgillum** [comment]
Thanks for the feedback. I agree with having a way to opt-out in case of emergency. We will probably need very targeted guidance for folks who run into these limits.

Regarding ContinueAsNew, we definitely need to make some improvements here. However, it's worth noting that the issue with WaitForExternalEvent is not unique to ContinueAsNew. Other actions, including scheduling activity functions, can cause external event messages to get dropped. We might have to tackle external event reliability separately.

The snapshot concept would be a great way to fix this, but it's unclear to me how such a feature could be implemented on top of the Durable Task Framework without the developer explicitly coding it in. The history of an orchestration is tightly coupled to the code, so I don't know if there is a way we could make it into a management experience. `ContinueAsNew` is basically the only way to do snapshots right now.

**Comment by wahyuen** [comment]
@cgillum did you happen to have any numbers to share for this issue? Does this tie into the size of DurableFunctionsHubHistory in storage? Attempting to diagnose why a large number of orchestrations (that then call numerous sub orchestations) is having low throughput.

**Comment by SimonLuckenuik** [comment]
Is there a configuration item to change the default value of 100k?

**Comment by amdeel** [comment]
@SimonLuckenuik Yes! My PR referenced above does make the value configurable, just defaulted to 100k. The variable is MaxOrchestrationActions and can be changed in the host.json.

**Comment by SimonLuckenuik** [comment]
Thank for the clarification Amanda!
