### ISSUE TITLE
Support for source-linking in Durable Functions extension

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#526]
The Azure Functions core DLLs support this already. The Durable Functions extension should support this as well.

More info: https://github.com/dotnet/sourcelink/blob/master/README.md

**Comment by cgillum** [comment]
Ideally we would at it to all three assemblies used by Durable Functions, but the priority order would be:

1. Microsoft.Azure.WebJobs.Extensions.DurableTask
2. DurableTask.AzureStorage
3. DurableTask.Core

**Comment by gled4er** [comment]
Great!

Thank you for the clarification!
