### ISSUE TITLE
Have UI/Design View for Durable Functions Workflow

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-functions-durable-extension#532]
# Customer Request

Create a simple UI/Design View for users to use for Durable Functions when going throug the workflow (like that of Logic App Design View).

It enhances the user experience and helps developers debug their Durable Functions more easily.

**Problem Statement**: The partner would like for Durable Functions to have a simple UI or Design View, similar to the Logic App Design View.

**Desired Experience**: Durable Functions should have a Design View similar to the one available for Logic Apps.

**Comment by cgillum** [comment]
The Key Value prop of Durable Functions is that you can write workflows in code (i.e. the IDE is your designer). This is why we've stayed away from looking into a UI/design surface so far.

This doesn't mean we're completely against this idea. However, my question for you; what is it that the customer needs which cannot be solved using (as you mentioned) Azure Logic Apps? I'd like to understand that better to know if it makes sense for us to go this route vs. improving the Logic Apps experience.
