### ISSUE TITLE
Python support

### ISSUE THREAD

**Issue by MurrayFoxcroft** [Azure/azure-functions-durable-extension#548]
Hi, 

Is there an ETA for Python support?

Thanks

**Comment by kashimiz** [comment]
Hi @MurrayFoxcroft, we're currently gathering feedback to gauge user interest in this feature. (An upvote and/or a comment on [this GitHub issue](https://github.com/Azure/azure-functions-python-worker/issues/227) would help!)

**Comment by t-eckert** [comment]
@kashimiz If work goes forward on this, I would love to contribute!

**Comment by roycem90** [comment]
waiting for it

**Comment by rodbutters** [comment]
@kashimiz Is it possible to write the durable function in javascript for a python function app? Lack of durable functions for Python is slowing down my port from that online book seller's cloud to Azure. IMHO this is critical missing functionality. Happy to explain why. Thx.

**Comment by rcarmo** [comment]
I'm looking forward to this too. Are there any blueprints to guide contribution?

**Comment by techiesaurus** [comment]
Please prioritize Python support.

This [Azure Durable Functions] is such a great model overall for microservices in general, it needs Python to get the critical mass of support it deserves.

**Comment by abij** [comment]
Looking forward for this functionality!

**Comment by masante** [comment]
this is so much needed to migrate our python project and workloads to micro services. 
Please!

**Comment by kashimiz** [comment]
Hi folks, sorry for the delay in response. My area of work has shifted to the core runtime, so I don't have a lot of insight into the status of this request. @anthonychu, can you weigh in?

**Comment by anthonychu** [comment]
Yes! We've started work on it and aiming to have a public preview in March or April. Follow this issue here: https://github.com/Azure/azure-functions-python-worker/issues/227

**Comment by wasuaje** [comment]
Hello I'm really interested in this supporting python for standard functions apps. Any ETA?

**Comment by anthonychu** [comment]
@wasuaje Looks like you've found the update at https://github.com/Azure/azure-functions-python-worker/issues/227#issuecomment-606151211. You can follow [these instructions](https://github.com/anthonychu/python-durable-preview) to try it out. We're still waiting for some deployments to complete before we can announce a preview.

**Comment by wasuaje** [comment]
Yes Sir, thank you very much!

**Comment by ConnorMcMahon** [comment]
I am resolving this issue, as the feature is now in public preview. You can track progress towards GA at https://github.com/Azure/azure-functions-durable-python.
