### ISSUE TITLE
Broken Build

### ISSUE THREAD

**Issue by trhumphries** [Azure/azure-functions-durable-extension#551]
Any idea when it'll be fixed?

**Comment by kashimiz** [comment]
Hi @trhumphries, could you elaborate on what you mean by "broken build"? Are you trying to build the WebJobs.Extensions.DurableTask solution locally and encountering build errors, or are you referring to the AppVeyor build badge on the repo's main page, or something else?

**Comment by trhumphries** [comment]
I’m referring to the AppVeyor build badge

Terry Humphries
Senior Software Developer
GTP Services, LLC
816-377-1113

[cid:image001.png@01D3FC1B.2842F670]


This email is the property of GTP Services, LLC and may contain confidential and/or privileged information.  If you are not the intended recipient or have received this e-mail in error please notify the sender immediately and delete this e-mail.  Any unauthorized copying, disclosure or distribution of the material in this e-mail is strictly forbidden.




On Dec 20, 2018, at 3:42 PM, Katy Shimizu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @trhumphries<https://github.com/trhumphries>, could you elaborate on what you mean by "broken build"? Are you trying to build the WebJobs.Extensions.DurableTask solution locally and encountering build errors, or are you referring to the AppVeyor build badge on the repo's main page, or something else?

**Comment by cgillum** [comment]
Sorry that I missed this, and thanks for bringing it to our attention. It was a single flaky test which failed. I re-ran it in AppVeyor and now the badge is green.
