### ISSUE TITLE
What happens to WaitForExternalEvent which never called back?

### ISSUE THREAD

**Issue by andrew-vandenbrink** [Azure/azure-functions-durable-extension#553]
Is there default timeout?
Is there any impact if we have lot of WaitForExternalEvent which not called back?
Can we purge down these messages? that stalled due WaitForExternalEvent

**Comment by cgillum** [comment]
1. There is no default timeout. If you need a timeout, you can use the overload which takes one.
2. There is no impact if `WaitForExternalEvent` is not called back. See our [sample](https://github.com/Azure/azure-functions-durable-extension/blob/7ab9ee091a410757e827611c51549126dbd35ead/samples/precompiled/PhoneVerification.cs#L45-L62) which uses a `WaitForExternalEvent` which might never get called back.
3. I'm sorry, I didn't understand. What messages are you referring to, and why did they stall?

**Comment by andrew-vandenbrink** [comment]
Purging History API https://github.com/Azure/azure-functions-durable-extension/pull/498
Will this delete also message which still WaitForExternalEvent ? Or will it forever stalled in the storage because it is never completed?

**Comment by cgillum** [comment]
Purging the history won't delete any queue messages. However, it doesn't need to. Purge only works on completed instances, and there will never be completed instances that have pending queue messages.  If an orchestration receives an external event that it doesn't know how to handle, that message will be deleted.

Let me know if you have any other questions about this.

**Comment by RonniePitts** [comment]
Does WaitForExternalEvent  work on the  consumption plan given there is a hardset limit function timeout after 10 minutes (max)?

**Comment by cgillum** [comment]
@RonniePitts yes, all features work on the Consumption plan. If an orchestration is waiting for an external event, it gets unloaded from memory until that event is delivered and you don't receive any billing charges for that waiting time.
