### ISSUE TITLE
Error in orchestrator or activity function does not deadletter servicebus message

### ISSUE THREAD

**Issue by raymond-holmboe** [Azure/azure-functions-durable-extension#560]
More details here:
https://stackoverflow.com/questions/53983470/message-from-servicebus-queue-disappears-on-error-in-activity-function

**Comment by cgillum** [comment]
Copy/pasting my response here:

This behavior is by-design. Starting an orchestration is asynchronous - i.e. the `StartNewAsync` API will not automatically wait for the orchestration to run or complete. Internally, `StartNewAsync` just drops a message into an Azure Storage queue and writes an entry into an Azure Storage table. If that happens successfully, then your Service Bus function will continue running and complete successfully, at which point the message will be deleted.

Your workaround is acceptable if you truly need the Service Bus queue message to retry, but I question why you would need to do this. The orchestration itself can manage its own retries without relying on Service Bus. For example, you could use [CallActivityWithRetryAsync](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationContextBase.html#Microsoft_Azure_WebJobs_DurableOrchestrationContextBase_CallActivityWithRetryAsync__1_System_String_Microsoft_Azure_WebJobs_RetryOptions_System_Object_) to retry internally within the orchestration.

See the [Error Handling](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-error-handling) topic of the Durable Functions documentation.

**Comment by dhabierre** [comment]
Hi @raymond-holmboe ,

I have the same question.
I am using a ServiceBusTrigger to receive message from Queue.
I also use Durable Functions.

When the input message is not correct I'd like to put it in the Dead Letter Queue for analyze.

At present time, if I am right, it is possible to do it if an exception is raised in the first function:

```csharp
[FunctionName("Function_TaskExecutorStarter")]
public static async Task Run(
    [ServiceBusTrigger("%QueueName%", Connection = "ServiceBusQueueConnection")] string message,
    [OrchestrationClient] DurableOrchestrationClient orchestrator,
    ILogger logger)
{
    logger.LogInformation($"Start to process message from ServiceBus Queue: {message}");

    var instanceId = await orchestrator.StartNewAsync("Function_RunOrchestrator", message);

    logger.LogInformation($"Started orchestration with ID = '{instanceId}'");

    if (await orchestrator.HasFailedAsync(instanceId)) // custom extension method
    {
        throw new FunctionFailedException("Something went wrong while processing message => put message in Dead Letter Queue for analyzing");
    }
}
```

How to do differently, and properly!
Thanks.

**Comment by boylec** [comment]
@dhabierre did you have any luck with your solution?
