### ISSUE TITLE
Question about burst workloads in consumption

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#576]
_Moving question from @olitomlinson into a separate issue_

> While I’m here (and feel free to copy/paste and raise this as a separate issue), do you have much anecdotal evidence of DF adopters triggering & completing 100k of orchestrator workloads in a burst (following the above code snippet) on Consumption Plan?
>
> So far my out-of-the-box experience (on default host.json settings such as partition count 4) is yielding good* results on 10k-20k orchestrators being started as fast as possible(serviceBusTrigger).
>
> But when I exceed 20k orchestrators in a burst, the control queues start grinding to a halt, and nothing seems to progress. It feels like DF goes into an im-outside-a-normal-use-case mode and becomes bogged down and gives up. I tried 100k batch and had to drop the entire TaskHub state after a few hours as it just was not doing much but consuming a few control items every minute. (I can reliably reproduce this scenario every time I do a 100k batch)
>
> I’ve used app insights to determine there are no exceptions and performed crude analysis of the Azure Storage performance KPIs (as prescribed by the DF docs to determine the storage health) and nothing is alarming me.
>
> What’s weird is that it’s blistering fast for the first 10-20k and then drops off. This is where the functions host scale controller ‘black box’ concerns me... is it giving me lots of function host instances to clear the big ingestion service bus queue which feeds the orchestration starter? And then once all the work is inside DF, the scale controller is not acknowledging the huge amount of work that needs processing on the control and work queues?
>
> What I’m hypothesising is that the reason 10-20k flies through is it is riding on the coat-tails of a scaled out host due to the service bus ingestion queue, but after the ingestion queue clears to zero, does the scale controller aggressively start ‘scaling-in’ because it fails to acknowledge the huge storage queue lengths (specifically control queues) inside DF?
>
> Your insight would be much appreciated here! I appreciate I could be barking up the wrong tree with the scale controller
> 
> —-
>
> “Yielding Good* results” means the control queues are drained/completed within a minute of instanciating 10-20k orchestrator triggers.
>
> A linear 1:1 processing time is acceptable as the work load grows, but what is not acceptable is an exponentially slow processing time which is what I’m observing.
>
> P.s I also reconfigured to 16 partitions in host.json, and observed the same effects of the control queues grinding to a halt with many thousands of control items on each of the 16 control queues (during a 100k batch)

**Comment by olitomlinson** [comment]
Interestingly, I've just upgraded to 1.7.1 and now I'm not getting the slow down as described in this question. In fact, its crazy fast! Could the out-order-events have been slowing down the runtime?

**Comment by cgillum** [comment]
That is interesting. The fix was intended to address a specific case where orchestrators can get completely stuck indefinitely. However, it's possible that in some scenarios orchestrators were getting stuck only temporarily, and that the 1.7.1 fix took care of that as well.

But to kind of answer your question, we do run load tests that process 100K+ activity functions running in a single orchestration. However, these tests are somewhat simplistic and might not encounter the same issues.

It's difficult to explain concisely how the scale controller works with Durable Functions, but generally speaking it should **not** scale-in unless the queue length is less than the number of workers.

Do let me know if you end up seeing this weird latency behavior again.
