### ISSUE TITLE
Durable functions don't work out of the box ("Server encountered an internal error")

### ISSUE THREAD

**Issue by riverar** [Azure/azure-functions-durable-extension#581]
## Repro steps
1. Open Visual Studio 2017 15.9.5
2. Create new Azure Functions v2 project (empty)
3. Add durable function orchestrator
4. F5 project and note failure

## Expected
Function to be available on local machine for debugging

## Actual
A host error occurred
Microsoft.WindowsAzure.Storage: Server encountered an internal error. Please try again after some time.

![image](https://user-images.githubusercontent.com/475132/51433910-aed5ab00-1c0a-11e9-97aa-4d71560b3c76.png)

## Environment
Azure Functions Core Tools (2.4.249 Commit hash: c29620154bc23d7fe3fc431713c5c0e43cbc241c)
Function Runtime Version: 2.0.12265.0
Microsoft.Azure.WebJobs.Extensions.DurableTask 1.7.1
Microsoft.NET.Sdk.Functions 1.0.24
Visual Studio 2017 15.9.5
Windows 10 1809

Azure Storage Emulator logs attached
[Logs.zip](https://github.com/Azure/azure-functions-core-tools/files/2776148/Logs.zip)

Also posted at https://github.com/Azure/azure-functions-core-tools/issues/994

**Comment by riverar** [comment]
@cgillum I just shockingly discovered 5.8 -- the version I was running -- [is critically broken](https://github.com/Azure/azure-storage-net/issues/810). Upgrading to 5.9 and downgrading to 5.7 seems to resolve the issue. What's the servicing/comms plan here? I just wasted days on this!

**Comment by cgillum** [comment]
Ouch, really sorry to hear that. I understand how stuff like this is quite maddening. 😓

Some users reported the same issue a while back. I had opened an issue with a known workaround in the Azure Functions host repo for the runtime team to investigate further: https://github.com/Azure/azure-functions-host/issues/3621. I am glad though that newer versions resolve the issue.

**Comment by riverar** [comment]
Thanks @cgillum, should we close this then?

While my colleagues can reproduce this issue, a fresh VM and fresh VS 2017 install pulls down Storage Emulator 5.7. I suspect someone over there stopped the roll-out of 5.8.
