### ISSUE TITLE
Visual Studio 15.9.6 crash before start Functions Runtime 2.0.12265.0

### ISSUE THREAD

**Issue by andreatosato** [Azure/azure-functions-durable-extension#589]
**Describe the bug**
Azure Functions on dev machine crash before start.

**Investigative information**
- Durable Functions extension version: Microsoft.Azure.WebJobs.Extensions.DurableTask Version="1.7.1"
- Function App version: (2.0)
- Function Runtime Version: 2.0.12265.0
- Programming language used: C#
- .NET Core version: netcoreapp2.1

**To Reproduce**
Create **DurableOrchestratorFuctions** from Visual Studio 15.9.6 scaffolding

**Actual behavior**
_Microsoft.WindowsAzure.Storage: Server encountered an internal error. Please try again after some time._

**Screenshots**
![image](https://user-images.githubusercontent.com/24985956/51709595-1df63980-2027-11e9-84e7-d01edc8ac6a1.png)

**Additional context**
- Development environment (Visual Studio 15.9.6)
- Azure Storage Explorer Work
- Simple HttpFunctionTrigger Work

**Comment by kashimiz** [comment]
What version of the Azure Storage Emulator are you using? This looks similar to a previously reported problem caused by version 5.8 of the emulator. In that case, changing to version 5.7 or 5.9 resolved the issue.

**Comment by andreatosato** [comment]
My version is 5.8.
How can I update it?
Visual Studio does not update it. Is there a dedicated link for the azure storage emulator?

**Comment by kashimiz** [comment]
The Storage Emulator is part of the Azure SDK, so an update to that should update the emulator as well. For a targeted update, the [Storage Emulator documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#get-the-storage-emulator) provides a direct download link, which is also available under Command Line Tools on the [Azure Downloads page.](https://azure.microsoft.com/en-us/downloads/) These links are for version 5.9.

**Comment by andreatosato** [comment]
@kashimiz you save my day!
