### ISSUE TITLE
Suppress unnecessary dependency tracking for internal storage calls.

### ISSUE THREAD

**Issue by kashimiz** [Azure/azure-functions-durable-extension#593]
Prompted by [this StackOverflow post](https://stackoverflow.com/questions/54400108/failing-dependency-call-in-azure-durable-functions): Currently, Application Insights' dependency tracking feature reports 404 responses from Azure Storage such the initial call made by `table.CreateIfNotExists()` when the table doesn't exist, which is part of the Durable Functions extension's program flow. We should suppress these to reduce noise in customer's App Insights logs.

**Comment by JohnReeson** [comment]
Link [one identical issue](https://github.com/Azure/azure-webjobs-sdk/issues/2039).

**Comment by oising** [comment]
This one is bothering my app insights OCD.

**Comment by ProjectPete** [comment]
Bump!  
+1 oising!  
    
It's a distracting red, please make this tweak or advise us on a work-around.   

We need a clearer vision for 2020!  :D  
 
Apart from these tiny issues... I flippin lovin' Function Apps and the monitoring/logs around them...  
A true game changer. Interesting times...

Happy New Year to all durable devs & digital devotees x

**Comment by hugobarona** [comment]
Definitely I am looking forward to this change since the 404 dependency errors are really distracting, especially when i am using Live Metrics Stream in the functions in Production while executing several requests per minute.

**Comment by cgillum** [comment]
@amdeel this might be a good one for you to look into. Here is a StackOverflow post that describes how to do this for SQL (we would need to do one slightly differently - i.e. for Azure Storage calls): https://stackoverflow.com/questions/38320886/app-insights-disable-sql-dependency-telemetry

@brettsam would be a great person to consult with on this as well.

**Comment by shelbaz** [comment]
Bump. Looking forward to this update, too many false positive errors in ApplicationInsights because of it.

**Comment by ConnorMcMahon** [comment]
Don't want to delay 2.2.0 for this, so targeting 2.2.1.

**Comment by ConnorMcMahon** [comment]
punting for 2.3.0

**Comment by corwestermaniddink** [comment]
Update please?

**Comment by oising** [comment]
La la la la la la

**Comment by ravibha** [comment]
We are facing a similar issue as well. Seeing 404 dependency failures when durable functions are being executed. Dependency type is 'Azure Table'. Has this been fixed already? I was not able to tell from the backlog item.

Thanks!

**Comment by cgillum** [comment]
This is not fixed yet. I realize this is likely very annoying, so apologies for the delays in getting around to this. It's in our backlog.

**Comment by tanujnarula** [comment]
@cgillum @oising 

Hello Chris,

Main problem is, we went ahead and created "SuppressAzureTableTelemetryProcessor" to suppress this 404 error but to find out that web job sdk's function "AddApplicationInsightsWebJobs" does not support adding this processor and this ITelemetryProcessor wont be triggered. So we are at loss how to handle this now?

We also tried adding it using "services.AddApplicationInsightsTelemetryProcessor<SuppressAzureTableTelemetryProcessor>();", but it wont trigger or use it.

Here is the issue which I refer.
https://github.com/Azure/azure-webjobs-sdk/issues/2584


Any further suggestions?

Regards
Sam.

**Comment by tanujnarula** [comment]
Hello Folks, @cgillum  @oising 
Any feedback on the issue must just above?

**Comment by AndiHahn** [comment]
Hi @cgillum @ConnorMcMahon ,
When this issue will be fixed? Is there any workaround to suppress these errors?
It's spamming my application insights and makes it hard to figure out real failures.

**Comment by ConnorMcMahon** [comment]
We will prioritize this for our 2.4.0 release, as this should be simple to fix and there is clearly some pain points here.

**Comment by amdeel** [comment]
To be transparent here, we've been blocked on this work. Like stated above, we do not have the ability to add ITelemetryProcessors at this time.

However, I'm going to do some further investigation on this work to see if we can suppress these 404s another way.

**Comment by akw123** [comment]
getting spammed by this error as well. Hope the team able to push this in soon.
It has impacted our ability to pinpoint failures.

**Comment by ConnorMcMahon** [comment]
We have a PR out for this that we hope to get released in the very near future.
