### ISSUE TITLE
How to query state of an orchestration instance

### ISSUE THREAD

**Issue by rahulvmarathe** [Azure/azure-functions-durable-extension#597]
Hello,

I have a scenario where, multiple instances of an orchestration will run for long time (few hours to few days but less than 7 days). Over it's lifetime the orcehstrator's state will go through changes. What is the best way to query the state of an instance without storing it to another external entity such as a Redis Cache/Cosmos Db.

Regards
Rahul

**Comment by cgillum** [comment]
Hi @rahulvmarathe, thanks for the question. Take a look at our documentation on [Custom Orchestration Status](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-custom-orchestration-status). By combining this with our [instance query capabilities](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management#querying-instances), you should be able to track the status of all your orchestration instances over their lifetimes without storing data in any external store.

Let me know if there are any questions I can help answer if the documentation I linked to above isn't enough.

**Comment by rahulvmarathe** [comment]
Thanks @cgillum, Custom Orchestration Status should work for my use case.
