### ISSUE TITLE
SetCustomStatus not updating or CallActivityAsync restarting the function code execution.

### ISSUE THREAD

**Issue by natalicontguard** [Azure/azure-functions-durable-extension#598]
Hi, 
My project is about updating multiple items in CSOM (sharepoint online), and I wish to allow the client to perform HTTP polling requests for checking the updating progress. 
I saw that durable functions can help me achieve this goal. 
However when I tried to implement the code I seem to have some issues:
1. I wish to set the context.SetCustomStatus() based on the updating progress of the SP ClientContext - when I tried to set the value for this status, I did so in the loop for updating items in bulks of 10 items at a time (updated 10/30, updated 20/30... and so on). 
when just using the context.SetCustomStatus() without any trigger activity - won't seem to work. the function RuntimeStatus stays on "Pending" until the function is completed.
2. When adding a CallActivityAsync method, the context.SetCustomStatus() is updating. However in this case - the function keeps on restarting and run from the start to the last CallActivityAsync (since it is called every 10 items: starting 0 to 10, then 0 to 20, then 0 to 30, and so on)

What am I missing?

**Comment by cgillum** [comment]
Before jumping into specifics, have you read through the documentation here about orchestration replay and code constraints?

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-checkpointing-and-replay
