### ISSUE TITLE
Local debug and CORS 

### ISSUE THREAD

**Issue by baywet** [Azure/azure-functions-durable-extension#599]
**Describe the bug**
When debugging locally a combination of a azure function/durable task and a front end application. If I want to track the progress of my task in the front end application, it is not possible because the durable tasks extension doesn't handle CORS request, so the browser will block any request to the `statusQueryGetUri` and other URIs

**Investigative information**

- Durable Functions extension version: 1.7.1
- Function App version (1.0 or 2.0): 2.0
- Programming language used: C#

**To Reproduce**

1. Create a durable task that is triggered by an http trigger https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-concepts#c
2. Create a simple front end application that queries on the status
```JS
//fetch request to the function getting the status response
await fetch(status.statusQueryGetUri);
```
3. You'll have CORS error messages in the console.

**Expected behavior**
fetch request to succeed when debugging locally.

**Actual behavior**
Getting CORS error messages in the console
```
Access to fetch at 'http://localhost:7071/runtime/webhooks/durabletask/instances/3e0095001e644680873312373400cb68?taskHub=DurableFunctionsHub&connection=Storage&code=r3IuoMv54hcP4ULprjOIBJvvnVxbN54s7asAtczw77fStYZbIMo4ug==' from origin 'https://baywet.sharepoint.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**Comment by cgillum** [comment]
When running locally, the Azure Functions Core Tools allows you to specify CORS configuration in either the command-line or in the local.settings.json file, as described here: https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#local-settings-file.  Does doing this unblock your scenario?

**Comment by baywet** [comment]
Thanks! I had somehow not come across that in my searches. Closing.

**Comment by dfberry** [comment]
```
{
  "IsEncrypted": false,
  "Values": {
    "FUNCTIONS_WORKER_RUNTIME": "<language worker>",
    "AzureWebJobsStorage": "<connection-string>",
    "MyBindingConnection": "<binding-connection-string>",
    "AzureWebJobs.HttpExample.Disabled": "true"
  },
  "Host": {
    "LocalHttpPort": 7071,
    "CORS": "*",
    "CORSCredentials": false
  },
  "ConnectionStrings": {
    "SQLConnectionString": "<sqlclient-connection-string>"
  }
}```
