### ISSUE TITLE
HttpStart failure: Webhooks are not configured

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#6]
The samples ask you to try starting an orchestration using an HTTP POST message. When doing this, you may see a failure that looks like the following:

```
mscorlib: Exception while executing function: Functions.HttpStart. Microsoft.Azure.WebJobs.Extensions.DurableTask: Webhooks are not configured.
```
The orchestrator function runs successfully, but the HTTP trigger returns a 500 error response instead of an HTTP 202 response.

**Comment by cgillum** [comment]
The following app setting needs to be added to the local.appsettings.json file:

```
"WEBSITE_HOSTNAME": "localhost:7071"
```

This only impacts locally hosted functions. It was missed during initial testing because the dev/test environment had this specified as an environment variable. A clean Windows 10 VM revealed the problem. The sample app will need to be updated to include this setting.

**Comment by mmisztal1980** [comment]
I confirm, it works.

**Comment by cgillum** [comment]
The sample app has been updated to include this setting by default (https://github.com/Azure/azure-functions-durable-extension/blob/master/samples/precompiled/local.settings.json#L6). Thanks for your patience on these initial issues.

Related issue: https://github.com/Azure/azure-webjobs-sdk-script/issues/1658
