### ISSUE TITLE
Passing an invalid instance id into StartNewAsync causes function to be run endlessly.

### ISSUE THREAD

**Issue by dantheman999301** [Azure/azure-functions-durable-extension#601]
**Describe the bug**
Passing an custom instance id to `DurableOrchestrationClient.StartNewAsync` with characters that are not allowed as Table Storage PartitionKeys or RowKeys causes the function to retry infinitely.

**Investigative information**

- Durable Functions extension version: 1.7.1
- Function App version (1.0 or 2.0): 2.0
- Programming language used: C#

**To Reproduce**

1. Create a function that starts a new Orchestrator, supplying the instance id with a bad character (see https://blogs.msdn.microsoft.com/jmstall/2014/06/12/azure-storage-naming-rules/ for invalid characters)
2. Inside the Orchestrator code, call at least one `CallActivityAsync` or throw and error, don't think it matters which.

e.g.
```
        public static async Task StartOrchestrator(
            [ServiceBusTrigger("transform", Connection = "connectionString")] string fileId,
            [OrchestrationClient] DurableOrchestrationClient starter,
            ILogger logger)
        {
            var existingInstance = await starter.GetStatusAsync(fileId);
            if (existingInstance == null)
            {
                logger.LogInformation("Orchestration starting from Service bus with Id {fileID}", fileId);

                await starter.StartNewAsync("StartProcessing", fileId, fileId);
                logger.LogInformation($"Started orchestration with ID = '{fileId}'.");
            }
        }
```

And basically any of the examples code for Durable Functions should cause it to retry over and over. Easy thing to pass in to cause it is something with a question mark in it.

**Expected behavior**
Ideally, I'd think `StartNewAsync` should throw an error before anything is started.

**Actual behavior**
Gets to the Orchestrator and endlessly retries.

**Known workarounds**
Validate the instance id manually.

Just as a note, I realise that this is essentially user error (and we only found it when we were actually trying to break something else entirely) but thought I'd raise it anyway.

**Comment by cgillum** [comment]
Thanks for opening this issue. It sounds like we need to add a bit more validation for the instance IDs.
