### ISSUE TITLE
How do I access the orchestrators instanceID from within an activity function?

### ISSUE THREAD

**Issue by russgove** [Azure/azure-functions-durable-extension#604]
How do I access the orchestrators instanceID from within an activity function?

I am using c#

**Comment by kashimiz** [comment]
Hi @russgove,

In C# you can bind your `ActivityTrigger` to the `DurableActivityContext` object, whose `instanceId` field represents the orchestration instance ID. Have a look at the [API documentation here](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableActivityContext.html) for more information.

**Comment by cgillum** [comment]
Let us know if you need any additional help regarding this.

**Comment by russgove** [comment]
thanks. i have ended up creating a class for each activity function to hold its parameters. is that a common/recommended approach?

**Comment by cgillum** [comment]
That approach is perfectly fine too.

**Comment by Meadow201317** [comment]
> Hi @russgove,
> 
> In C# you can bind your `ActivityTrigger` to the `DurableActivityContext` object, whose `instanceId` field represents the orchestration instance ID. Have a look at the [API documentation here](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableActivityContext.html) for more information.

The link is unavailable now. Could you please update it? :)

**Comment by davidmrdavid** [comment]
I suspect this is the new home of that documentation: https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableactivitycontext?view=azure-dotnet#definition

**Comment by cgillum** [comment]
I've updated the link to point to the new location for the docs.
