### ISSUE TITLE
Heavy storage resource usage for Durable Function while being idle

### ISSUE THREAD

**Issue by SimonLuckenuik** [Azure/azure-functions-durable-extension#607]
**Describe the bug**
Heavy storage resource usage for Durable Function while being idle. It seems that most of our storage costs are related to Durable Functions: for example, we have a tenant with 3 Function Apps running Durable Functions, which are mainly idle, but will still consume 1681 * 10 000 operations in a month -- 9$ of storage operations together.

**Investigative information**
- Programming language used: C# with dotnet worker
- References used:
```
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.8.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.7.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions" Version="3.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.2" />
```

- host.json:
```
{
  "version": "2.0",
  "aggregator": {
    "batchSize": 1000,
    "flushTimeout": "00:00:30"
  },
  "extensions": {
    "http": {
      "routePrefix": "",
      "maxOutstandingRequests": 200,
      "maxConcurrentRequests": 100,
      "dynamicThrottlesEnabled": true
    },
    "queues": {
      "maxPollingInterval": "00:00:05",
      "visibilityTimeout": "00:00:00",
      "batchSize": 1,
      "maxDequeueCount": 5,
      "newBatchThreshold": 1
    },
    "serviceBus": {
      "maxConcurrentCalls": 16,
      "prefetchCount": 100
    },
    "eventHub": {
      "maxBatchSize": 1000,
      "prefetchCount": 100
    },
    "durableTask": {
      "HubName": "QDef",
      "ControlQueueBatchSize": 32,
      "PartitionCount": 4,
      "ControlQueueVisibilityTimeout": "00:05:00",
      "WorkItemQueueVisibilityTimeout": "00:05:00",
      "MaxConcurrentActivityFunctions": 10,
      "MaxConcurrentOrchestratorFunctions": 10,
      "AzureStorageConnectionStringName": "AzureWebJobsStorage",
      "TraceInputsAndOutputs": false,
      "LogReplayEvents": false,
      "EventGridTopicEndpoint": "",
      "EventGridKeySettingName": "",
      "EventGridPublishRetryCount": 3,
      "EventGridPublishRetryInterval": "00:00:30"
    }
  },
  "watchDirectories": [ "Shared", "bin" ],
  "healthMonitor": {
    "enabled": true,
    "healthCheckInterval": "00:00:10",
    "healthCheckWindow": "00:02:00",
    "healthCheckThreshold": 6,
    "counterThreshold": 0.80
  },
  "functionTimeout": "00:10:00",
  "logging": {
    "logLevel": {
      "default": "Information",
      "Host": "Information",
      "Host.Results": "Information",
      "Host.Aggregator": "Information",
      "Host.Triggers.DurableTask": "Information",
      "Function": "Information"
    },
    "applicationInsights": {
      "sampling": {
        "isEnabled": true,
        "maxTelemetryItemsPerSecond": 30
      }
    }
  },
  "singleton": {
    "lockPeriod": "00:00:15",
    "listenerLockPeriod": "00:01:00",
    "listenerLockRecoveryPollingInterval": "00:01:00",
    "lockAcquisitionTimeout": "00:01:00",
    "lockAcquisitionPollingInterval": "00:00:03"
  }
}
```
- Example of API call frequency when running with Azurite locally (Azurite used to provide the screen capture only, usually using the standard Azure Storage Emulator). We see a lot of activity related to the control queues. It seems that instead of simply messages at a regular interval it does it multiple time for the same controle queue (in that screen capture GET qdef-control-01/messages is called multiple times instead of a single time (I assume there are no messages in those queues since the service is idle):
![durablefunctionresourceusage](https://user-images.githubusercontent.com/13141534/52717249-b0c32d80-2f6e-11e9-924d-1ee7098383f4.gif)

- Example of usage for last 7 days for a single Function App. Storage account used only for Azure Functions / Durable Function specific data:
  - With Split at API level
![usage7days](https://user-images.githubusercontent.com/13141534/52719127-fc77d600-2f72-11e9-85a3-1e1492dfb662.png)
  - Raw without split
![usage7daysnosplit](https://user-images.githubusercontent.com/13141534/52720497-b96b3200-2f75-11e9-8c65-b94da5faf477.png)

- Storage Account content:
![image](https://user-images.githubusercontent.com/13141534/52719310-66907b00-2f73-11e9-9cc5-ffe86018df8d.png)

**If deployed to Azure**
Plan: Consumption
Region: West US
Storage kind: StorageV2 
Invocations to find related Function Apps
-Function App 1 Invocation : 2019-02-01T15:19:08.6796609Z - 9c2503fa-8074-4670-afac-ed7c0bb19d90
-Function App 2 Invocation : 2019-02-01T15:19:07.8852575Z - fe3fa664-26e5-4368-8324-e6105c40f180
-Function App 3 Invocation : 2019-02-01T21:17:01.9267561Z - 5cda9f51-8ec7-4894-add5-f24dba0cbea7

**Known workarounds**
None, tried looking around the available config items for Durable Functions inside host.json, but nothing seems to match that particular setting for control queues to allow to reduce the polling interval.

**Comment by cgillum** [comment]
I'm working on a fix for the following issue: https://github.com/Azure/azure-functions-durable-extension/issues/618. Do you think that would address your need?

**Comment by SimonLuckenuik** [comment]
Thanks for having a look @cgillum. Out of curiosity, what is supposed to be the current polling delay? From the logs and quick look in durable task, it looked like 200ms or so.

To answer your question, I think it will at least allow us to tweak depending on app usage of Durable Functions. Considering that for us those are background Orchestrators, we don't mind adding delay between polling. 

However, I think it would be interesting to be able to have "orchestrator categories" (could end-up in messages in different priority based control queues?) to fine tune even more inside de same app. For example, we have some orchestrator which are basically timer based with long timers (days to months), sitting idle most of the time, so every minute polling (maybe more, like 5 minutes) would probably do the trick, while some others are more realtime and would maybe require polling at every 500ms. I will raise a different issue to get the discussion started around that topic.

**Comment by ConnorMcMahon** [comment]
I'm going to close this issue, as the original ask is answered, and a new issue is opened for the new ask.
