### ISSUE TITLE
Support Azure Queues for Orchestrator Lifecycle Events

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#613]
We subscribe to the EventGrid events generated from Durable Functions Orchestrators.

This is great most of the time, but when we are under load and there are lots of orchestrator events, we find the backend (consumption plan function) saturated and can’t cope with the sheer amount of events to process concurrently.

We’ve mitigated this by using the newly announced Azure Storage Queue integration in Event Grid, so we can pull events at a rate that is sustainable. https://azure.microsoft.com/en-gb/blog/more-reliable-event-driven-applications-in-azure-with-an-updated-event-grid/

I’m asking that you support Lifecycle events  direct to Azure Storage Queue integration, to save me the burden of integrating with EG as a pass through.

Thanks.

**Comment by cgillum** [comment]
Thanks for the suggestion, and for the link to that blog post.

I like the idea, but I wonder how much value it adds over EG. Just to make sure I understand, is the concern that configuring EG is too much manual overhead (when you already have a storage account)?

**Comment by olitomlinson** [comment]
Don’t get me wrong, EG is a breeze to set-up although it’s not fully supported in Terraform just yet. It’s just more moving parts for me to have to implement and manage.

But anyway, EG is focused on real-time push of events, which is great if your use-case requires real-time but you need a hyper scale backend. I don’t require real-time.

Real time push of events isn’t the problem inherently, but the cost is. 

EG is the most expensive form of transport out of Storage Queues, Service Bus etc. I’m anticipating 5 million orchestrators a day, x 2 events (running, completed) which equals about £5 a day - just to shovel some events onto an Azure Storage Queue for processing. (and that’s assuming the that each EG event delivers first time with without retrys that incur additional cost)

It’s certainly a cost I could do without, if DF was able to publish straight to Storage Queues.

**Comment by cgillum** [comment]
Ah, thanks for that info. I had not considered the cost of EG. I think it makes sense for us to pursue a direct-to-queue notification mechanism.

**Comment by olitomlinson** [comment]
@cgillum I've implemented a PR https://github.com/Azure/azure-functions-durable-extension/pull/638 to achieve this by filtering out unwanted events at source, which is, on reflection, a better way to solve the problem (I only care about 'Failed' events)

**Comment by cgillum** [comment]
Closing this since the original need has been covered by https://github.com/Azure/azure-functions-durable-extension/pull/638.

I think the right way to customize this moving forward would be to implement https://github.com/Azure/azure-functions-durable-extension/issues/775.
