### ISSUE TITLE
Durable function execute at Runtime version: 1.0.12299.0 will broken

### ISSUE THREAD

**Issue by a9261** [Azure/azure-functions-durable-extension#616]
**Describe the bug**
I create a azure function v1 project on VS2017 , It's running ok on my local but when i publish to azure function (Runtime version: 1.0.12299.0 (~1)) , It broken 

error msg : Exception while executing function: FetchXjProcess. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'context'. Microsoft.Azure.WebJobs.Extensions.DurableTask: Unable to cast object of type 'System.String' to type 'Microsoft.Azure.WebJobs.DurableOrchestrationContext'.

btw , passing multiple parameters doesn't work on function 1.x . 
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#passing-multiple-parameters
**Investigative information**

- Durable Functions extension version: 1.7.1
- Microsoft.NET.Sdk.Functions 1.0.24
- Function App version: 1.0
- Programming language used:  C#

***If deployed to Azure***
- Timeframe issue observed: 2019-02-22T07:43:48.357
- Region: South India
- Orchestration instance ID(s): e57af826-6db0-4158-82ce-2b0505130e6e

**Comment by cgillum** [comment]
Regarding this:

> error msg : Exception while executing function: FetchXjProcess. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'context'. Microsoft.Azure.WebJobs.Extensions.DurableTask: Unable to cast object of type 'System.String' to type 'Microsoft.Azure.WebJobs.DurableOrchestrationContext'.

It sounds like you've defined an orchestrator function which uses `string` as the parameter, which is not supported. Orchestrator functions can only have `DurableOrchestrationContext` or `DuraleOrchestrationContextBase` as the parameter type. I would expect this fails both locally and in Azure.

**Comment by a9261** [comment]
Thank you i will follow your recommend try it

**Comment by a9261** [comment]
It's work , Thank you :)
