### ISSUE TITLE
After 1.7.1 Eternal Orchestration Functions stops on host shutdown

### ISSUE THREAD

**Issue by ielcoro** [Azure/azure-functions-durable-extension#630]
**Describe the bug**
After updating to 1.7.1 all of our orchestration functions stop running when the hosts shutdowns on consumption plan. Only after an event that restarts the host occurs (like a new Service Bus message, connecting through log streaming or the portal) the orchestration restarts. 

Downgrading the host to 1.7.0 solves the issue. We had downgraded all of our production instances to 1.7.0 and created a very simple sample function instance that reproduces the problem.

**Investigative information**

- Durable Functions extension version: 1.7.1
- Function App version (1.0 or 2.0): 2.0
- Programming language used: C#

***If deployed to Azure***

Invocation Id: 4ad4653f6dd74281ab94af10f6d59766
Timestamp: 2019-03-03T17:32:20.604 (2019-03-03T16:32:20.604 UTC)
Region: West Europe

**To Reproduce**
Just creating an eternal orchestration function that runs every two minutes:

```csharp
[FunctionName("ReproBugOrchestration")]
        public static async Task RunOrchestrator(
            [OrchestrationTrigger] DurableOrchestrationContext context,
            CancellationToken token)
        {
           await context.CallActivityAsync<string>("ReproBugOrchestration_Hello", "Tokyo");
           await context.CreateTimer(context.CurrentUtcDateTime.AddMinutes(2), token);

           context.ContinueAsNew(null);
        }

        [FunctionName("ReproBugOrchestration_Hello")]
        public static string SayHello([ActivityTrigger] string name, ILogger log)
        {
            log.LogInformation($"Saying hello to {name}.");
            return $"Hello {name}!";
        }

        [FunctionName("ReproBugOrchestration_HttpStart")]
        public static async Task<HttpResponseMessage> HttpStart(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")]HttpRequestMessage req,
            [OrchestrationClient]DurableOrchestrationClient starter,
            ILogger log)
        {
            // Function input comes from the request content.
            string instanceId = await starter.StartNewAsync("ReproBugOrchestration", null);

            log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

            return starter.CreateCheckStatusResponse(req, instanceId);
        }
```

**Expected behavior**
The function should run endessly every two minutes.

**Actual behavior**
Instead, it runs for an hour or so, and then stops running. If the instance is connected to app insights you get a "host is stopping" trace before the orchestration stops. Azure storage durable functions table shows the orchestration as running.

**Screenshots**
![image](https://user-images.githubusercontent.com/587365/53702201-8f828e00-3e04-11e9-967a-cde4831710dd.png)

**Known workarounds**
Downgrade to durable functions 1.7.0
**Additional context**

- Development environment (ex. Visual Studio): Visual Studio, Visual Studio Code

**Comment by cgillum** [comment]
Hi @ielcoro. Thanks for providing these details.

I took a look at your app and it seems the Azure Functions scale controller is not detecting any triggers in your function app. This can result in exactly the behavior you mentioned. The simple resolution is to click the Refresh button next to your function app name in the portal.

![image](https://user-images.githubusercontent.com/2704139/53753088-3d258980-3e65-11e9-8d73-c51e94ce7b1b.png)

Normally people get into this state when they deploy their function app using an unsupported method, like FTP or deploying via a URL to blob storage. Can you tell me more about how you are doing deployments?

**Comment by ielcoro** [comment]
Thanks @cgillum 

I suspected something like that while doing the analysis, and had already tried to refresh the triggers, both in the production instances and in the repro app without luck, it only starts the host, like any other interaction with the portal, runs for a while and stops. 

Our production apps are deployed from a DevOps Pipeline and this sample application is deployed from VS Code, using the template generated from func command line, both show the correct count of triggers synced in the deploy logs or vs code output window. 

Keep in mind that doing exactly the same steps with version 1.7.0 works (our production apps are as we speak running with 1.7.0). 

Anyway I'm going to try to refresh the sample app now, and monitor the running time and report back when it stops.

**Comment by ielcoro** [comment]
Same behavior after refreshing, runs for an hour and stops after that:

![image](https://user-images.githubusercontent.com/587365/53762780-4d6f5000-3ec9-11e9-82e9-b4be00097d34.png)

**Comment by ielcoro** [comment]
Sorry for the delay reporting back, we had to re-diagnose this issue and get back online  our production service.

As I said before we rolled back to 1.7.0 and saw our production functions working again without stopping. Well, we were wrong. 

After some time, our functions stopped working, we rolled back to the latest 1.6.x but the same behaviour applied, functions started running for sometime, and stopped after a host stop message. Receiving a message through service bus or going through the portal restarted the functions again.

Discarding Durable functions as the source, we found this issue https://github.com/Azure/azure-functions-host/issues/4152 regarding the latest runtime deployment   (v2.0.12332) and functions stopping. We followed the workaround there and now the problem is gone, at the time of this post will complete two days running without stopping.

**Comment by mhoeger** [comment]
@ielcoro - Very sorry you faced this issue. Did you find the workaround in #4152 worked for you? If so, it is now safe to remove `WEBSITE_USE_PLACEHOLDER=0` as a fix has been rolled out. If you keep having issues, I can debug further into this.

**Comment by ielcoro** [comment]
Thanks @mhoeger,

Yes the workaround did work for us. We did not remove it yet, but we plan to do so soon, when it's safe to do so for our customers.
