### ISSUE TITLE
Durable function app switches slots in middle of orchestration

### ISSUE THREAD

**Issue by farzanDE** [Azure/azure-functions-durable-extension#634]
**Describe the bug**

I have a durable function app with a production and staging slot on a Consumption plan. I am not using the slot swap feature but each individual slot is git deployed from a BitBucket source. There are some environment variables that are different for the production and staging slots.

I initially tested only on the staging slot (there was no code deployed in production though all environment variables were present) and it worked without issue. After deploying to production, I made a call to trigger the production orchestrator. The app started correctly, but over time it shifted processing to the staging slot for some reason (i.e. I have partial data updates in my production database, but the remaining ones are in the staging database). While the production orchestrator was running, I did not make any call to the staging slot.

From the Live metrics stream in Application Insights, I can see from telemetry traces that the early function executions are marked as running on "Production" while the later executions are marked as "staging". A transition occurred at some point in between that I haven't yet located.

**Investigative information**

- Function App version (1.0 or 2.0): 2.0
- Programming language used: Javascript
- durable-functions npm module version: 1.1.4

***If deployed to Azure***

The following information is for an orchestrator execution during the final stages (when it had already moved to staging slot)
- Invocation Id: f16a6bdd-f7b2-435b-88f4-59067ccb4915
- Timestamp (UTC): 2019-03-08T04:49:14.4933564Z
- Region: Southeast Asia

The following information is for an orchestrator execution during the early stages (when it ran in the production slot)
- Invocation Id: 52787ac7-1f74-441c-84b0-54fb4edc6f67
- Timestamp (UTC): 2019-03-08T04:15:30.5954457Z
- Region: Southeast Asia

**To Reproduce**
Not sure. Issue presumably occurs when a durable function app has multiple slots.

**Expected behavior**
Slots should work independently with no cross-linking

**Actual behavior**
App starts off in one slot and moves to other in between

**Comment by farzanDE** [comment]
Additional note: I know that Slots for Function Apps are in Preview mode, but I have standard (non-durable) function apps deployed with a similar structure (production and staging slots each linked to BitBucket sources), and have never seen this issue there. The problem seems to be related to durable functions only.

**Comment by SimonLuckenuik** [comment]
If both your staging and production slot are pointing on the same Storage account, I believe you will end-up with your control queues shared by both application orchestrator (staging and prod), so some messages from the queues will be consumed by one or the other slot...

**Comment by farzanDE** [comment]
I see. I'll test again after separating the Storage accounts. Thanks

**Comment by farzanDE** [comment]
No issues after separating the storage accounts. Thanks for the help. Closing this issue
