### ISSUE TITLE
I want to check state, if orchestrator call WaitForExternalEvent and pendding.

### ISSUE THREAD

**Issue by yuka1984** [Azure/azure-functions-durable-extension#637]
I would like to know if Orchestrator is currently waiting waiting for WaitforExternalEvent using Durable OrchestrationClientBase.
I would like to solve the following problem in the following cases.
We make an asynchronous request to the external with CallActivity in Orchstrator, then call WaitForExternalEvent to create a process waiting for an asynchronous return from outside.
The response time from the external is a wide range. In some cases it may take about 5 seconds, but it may take more than 2 hours.
A trouble will occur when the response time from the outside is short.
When Orchestrator makes an asynchronous request to the outside with CallActivity and a response is returned at a very early timing, a RaiseEvent occurs before Orchestrator calls WaitForExternalEvent and transitions to the wait state (before writing that state to History) Occasionally, Orchestraotr can not continue because History becomes unintended state.
Of course there is also a solution to temporarily receive external response and set RaiseEvent with a time difference, but I do not think that is good.
I think that it is possible to check the status of WaitForExternalEvent by analyzing Hisotry data, but it is complicated and it is difficult because the code changes depending on the case.
I'd like a function or property that can get the WaitForExternalEvent state with DurableOrchestrationStatus.

**Comment by olitomlinson** [comment]
This is a known bug (https://github.com/Azure/azure-functions-durable-extension/issues/573) and is fixed in 1.8.0 which will hopefully be released in the next few weeks.

a Release Candate is available for 1.8.0 which you can test against, instructions available here :

https://github.com/Azure/azure-functions-durable-extension/issues/580#issuecomment-471136123

**Comment by yuka1984** [comment]
@olitomlinson thanks. I closed this issue.
