### ISSUE TITLE
End-to-end tests have become very flakey

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#646]
The automated end-to-end tests have become very flakey. A wide variety of tests seem to be randomly failing due to orchestrations either not starting or failing to complete. This needs to be investigated to see if there could be a regression. Anecdotally, the failures mostly seem to involve timer messages, but this is not always the case.

Recent test failures:
* WaitForExternalEventWithTimeout ([1](https://ci.appveyor.com/project/appsvc/azure-functions-durable-extension/builds/23431033/job/anroksi3e00uh78l/tests), [2](https://ci.appveyor.com/project/appsvc/azure-functions-durable-extension/builds/23432577/job/kns1e0m6hl3cwmo1/tests))
* VerifyUniqueGuids ([1](https://ci.appveyor.com/project/appsvc/azure-functions-durable-extension/build/job/6p5cq1fh3hoioa3e/tests))
* RaiseEventToSubOrchestration ([1](https://ci.appveyor.com/project/appsvc/azure-functions-durable-extension/build/job/nempcb4pu3k8qe14/tests))

**Comment by olitomlinson** [comment]
Agreed, I was getting this a hell of a lot when running the tests locally in VS2017  against remote Azure Storage.

**Comment by cgillum** [comment]
@olitomlinson that's actually good to know that you observed this locally. I'll try to reproduce it locally as well as see if I can better debug the issue.

**Comment by blackalbum** [comment]
I'm having this issue too. When I start End to End tests, it fails due to the fact that it cannot find the local azure storage connection string. Any solution?

**Comment by cgillum** [comment]
@blackalbum Is that a flakiness issue? Or do the tests just not run at all? Did you follow the local testing instructions in the [contribution guide](https://github.com/Azure/azure-functions-durable-extension/blob/dev/CONTRIBUTING.md#running-the-tests-visual-studio)?

The issue I'm observing is that sometimes orchestrations don't seem to start or don't seem to complete in the specified timeout. Looking through the Azure Storage logs and history tables, it seems like some of the internal messages are being heavily delayed, but I have yet to understand why.

**Comment by cgillum** [comment]
I did not mean to close this - the tests are still flakey.

**Comment by TsuyoshiUshio** [comment]
Once Azure DevOps guy fix the Anonymous PR issue, how about moving Azure DevOps and use replay feature?

**Comment by cgillum** [comment]
Oh nice! Yes, if the anonymous PR issue is fixed, then I think it would be a good idea to move to Azure DevOps. We can probably get much faster CI runs that way too.
