### ISSUE TITLE
Documentation to Self host(On Premise) as opposed to cloud?

### ISSUE THREAD

**Issue by maulik-modi** [Azure/azure-functions-durable-extension#651]
Hi team,

After creating Azure storage account and service bus, I was able to get [Durable Task Samples](https://github.com/Azure/durabletask) working in my local pc, is it possible to run Azure functions Durable extension local pc? If it is permitted use case then we can develop providers and run everything on premise.

1) Instance store IOrchestrationServiceInstanceStore for NoSQL DB
2) Blob store IOrchestrationServiceBlobStore for NoSQL DB
3) Extended session IOrchestrationSession for Radis
4) IOrchestrationService Similar to ServiceBusOrchestrationService for RabbitMQ

Thanks,
Maulik.

**Comment by cgillum** [comment]
It is possible to use the durable extension on a local PC. You have a few options:

1. Use the Functions Core Tools for local development/debugging ([docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local))
2. Deploy your function app as a Docker image ([docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-function-linux-custom-image))
3. Self-host the durable extension in the WebJobs runtime ([docs](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-webjobs-sdk))

Unfortunately these options won't allow you to use a custom IOrchestrationService, which means you're still stuck with the Azure Storage provider. Starting in Durable Functions 2.0, we're planning on making this extensible. See https://github.com/Azure/azure-functions-durable-extension/issues/652 for more details.
