### ISSUE TITLE
Allow storage providers other than DurableTask.AzureStorage

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#652]
The Durable Task Framework allows using an extensible set of storage providers. The currently supported providers include:

* [DurableTask.AzureStorage](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.AzureStorage/)
* [DurableTask.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.ServiceBus/)
* [DurableTask.Emulator](https://www.nuget.org/packages/Microsoft.Azure.DurableTask.Emulator)

An official Service Fabric provider is also currently under development.

However, the Durable Task extension for Azure Functions is hardcoded to use **DurableTask.AzureStorage**. This is problematic particularly for those who want to run Durable Functions in a non-Azure environment (which some refer to as "on-premises" or "the Edge").

This work item tracks allowing users to choose their own storage provider, whether it's one of the official supported providers listed above (P1), or an arbitrary provider that a user may have developed themselves (P2).

Related issue (host.json changes): https://github.com/Azure/azure-functions-durable-extension/issues/641

**Comment by olitomlinson** [comment]
A cosmosDb provider would be really great. 

Reason being Azure storage replication is async, so it is possible that writes could go missing in the event of a failover to another region, whereas CosmosDb has guaranteed replication of writes.

**Comment by SimonLuckenuik** [comment]
SQL Server provider would be interesting, so that we can easily leverage a provider with built-in backup\restore.
