### ISSUE TITLE
HistoryPurgeAPI is not work.

### ISSUE THREAD

**Issue by yuka1984** [Azure/azure-functions-durable-extension#661]
Hi.
I tried the PurgeHistory API locally.
Azure Funcitons Core Tool version is 2.4.432

I got GetStatusAPI URL
http://localhost:7071/runtime/webhooks/durabletask/instances/beea722176664c0bbcf049e534effa84?taskHub=DurableFunctionsHub&connection=Storage&code=q1bnGZP3nZplIPgQQgwqXkvex8VdRx9dT59Z4jaAQMOIyA6WnLQBYA==

and request HTTP Get method.

I got status success.

and I tried same url and change http status to delete method.

So returned 404 Not found.

I have debugged and confirmed Durable Functions.

If i send get method, DurableTaskExtension.ConvertAsync method called.

but i send delete method, DurableTaskExtension.ConvertAsync method not called.

thank you.

**Comment by cgillum** [comment]
@gled4er is this something you could help investigate?

**Comment by yuka1984** [comment]
@gled4er @cgillum 

I checked azure functions host code.

https://github.com/Azure/azure-functions-host/blob/86d9664dd0c5637017befa73fdacf6c013363f2b/src/WebJobs.Script.WebHost/Controllers/HostController.cs#L221

This method have attribute httpget and httppost.

I think azure functions host support webhook only Get and Post.

**Comment by cgillum** [comment]
Oh, I think this means we made a mistake in our testing! The unit tests will pass and the Functions CLI will work, but a real HTTP request will not.

@fabiocav, @mathewc would either of you be opposed to us adding support for HTTP DELETE  for [ExtensionWebHookHandler](https://github.com/Azure/azure-functions-host/blob/86d9664dd0c5637017befa73fdacf6c013363f2b/src/WebJobs.Script.WebHost/Controllers/HostController.cs#L221) in the Functions host API controller?  I can help create a PR for that if you think it's acceptable.

**Comment by ConnorMcMahon** [comment]
This has been fixed in the Functions runtime now, and should have been resolved in one of the past few releases.
