### ISSUE TITLE
1 in 10,000 Activities completes but fails to return to Orchestration

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#669]
During load testing, I've a scenario where an Activity is called but the Activity Result fails to make it back to the Orchestration. The Instance is then stuck in a state of `Running` as its waiting for the response. It seems to happen once or twice in every 10,000.

**Orhcestrator code**
```
...
context.SetCustomStatus(new { Status = $"Forwarding to **** '{submission.TopicSubscriptionName}'" });
var retryOptions = new RetryOptions(TimeSpan.FromSeconds(5), 10);
retryOptions.BackoffCoefficient = 2;
retryOptions.MaxRetryInterval = TimeSpan.FromSeconds(60);
retryOptions.RetryTimeout = TimeSpan.FromMinutes(10);

context.RunWhenNotReplay(() => logger.TrackEvent("[Started] V1 **** - Forward To ****"));
var result = await context.CallActivityWithRetryAsync<ForwardTo****Result>("****_ForwardTo****_ActivityTrigger", retryOptions, submission);
context.RunWhenNotReplay(() => logger.TrackEvent("[Complete] V1 **** - Forward To ****"));

context.SetCustomStatus(new { Status = $"Waiting for **** result from '{submission.TopicSubscriptionName}'" });
return result;
...
```

**Activity Code**
In the activity, a message is placed on Service Bus. I observe the SB Message always arrives, so the user-code in the activity is working as expected.
```
[FunctionName("Router_ForwardTo****_ActivityTrigger")]
public async static Task<ForwardTo****Result> Run([ActivityTrigger] ServiceBusTopicSubmission<****Submission> submission, 
    ILogger log,
    [ServiceBus("submission", Connection = "ServiceBusConnectionString")] IAsyncCollector<Message> ****SubmissionTopc
)
{
    var message = new Message(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(submission.Payload)))
    {
        Label = submission.TopicSubscriptionName,
        MessageId = submission.MessageId,
        ContentType = "application/json"
    };

    await ****SubmissionTopc.AddAsync(message);

    return new ForwardTo****Result
    {
        Success = true,
        QueueSubmittedTs = DateTime.UtcNow
    };
}
```

 I've observed the History table and I can't see the the activity response coming in, it usually looks like ` 
 { "Success" = "true", "QueueSubmittedTs" = "<DATETIME>"} `.

Also, My App Insights events that are logged in the Orhcestrator code corroborates what is happening. ( I didn't get the second `TrackEvent` event that signals the Activities response has been received back into the Orchestrator.

**Other info**

In this particular load test, I'm restarting 10,000 existing instances with the same Id and same Payload using the `Starter.StartNewAsync` method, not the Rewind API. The original instances are in a failed state and never get to the point in the code that I have referenced above, so in this test, this is the first time this activity code has executed on this Instance Id)

**Diagnostic info**
Instance Id : 027c68f4-98d6-44a7-ac11-dde624f59de5
Execution Id: fc2d8f70a7f34c3fbc03057feb6f1065
Region : UK South
Durable Functions : v1.8.0  - v2 runtime.

**Comment by olitomlinson** [comment]
@cgillum are you able to take a look at the logs for this? Many thanks!

**Comment by cgillum** [comment]
Hi @olitomlinson. I'm not sure I fully understand. Are you saying that instance ID `027c68f4-98d6-44a7-ac11-dde624f59de5` schedules 10,000 activity functions and one doesn't return, or are you saying you scheduled 10,000 orchestrations with the exact same instance ID and one of them did not complete? 

I did a search for `027c68f4-98d6-44a7-ac11-dde624f59de5` and I only saw a small number of instances executed. The first instance I see is from `2019-03-23 18:03:41.7715461` (UTC). Am I looking at the right data?

**Comment by olitomlinson** [comment]
@cgillum Sorry for not being clear.

10,000 orchestration instances (all with distinct IDs), each making 1 call to an Activity.

9,999 of the activities returned successfully to their respective orchestrator instances.

1 Activity did not - InstanceId `027c68f4-98d6-44a7-ac11-dde624f59de5` is still running as its activity result didnt come back to the Orchestrator.

P.S. Im only including the `10,000` number to give you an idea of the scenario that this looks to be a race condition or some anomaly.

**Comment by cgillum** [comment]
OK, so I looked at just that orchestration ID, and I see that an activity function call failed repeatedly in a way that corresponds with your retry options. It appears that it never actually completed successfully - i.e. the retry options expired. At `2019-03-23 18:11:07.6958739` UTC, I see that the orchestration was marked as completed in Azure Storage. I also see that an event grid notification was fired for this instance immediately after the final failed activity function attempt. But you're saying that your orchestration never went into the Completed state?

**Comment by olitomlinson** [comment]
What you are seeing is the first pass of the instance, check my **other info** section of the first post.

In the first pass the 10,000 orchestrators failed (by design) and then I restarted them all with the failure removed.

Yes in the first pass the orchestrator went into a failed state (which is the EG event you are acknowledging) but I restarted the orchestrator and it should have worked. _it did work 9,999 times, one didn’t_

Happy to have a call with you to describe the scenario if my words are failing 😀

**Comment by olitomlinson** [comment]
First pass - induce failure in activity.
Activity gets retried 10 times, reaches terminal state of failed.

Fix the error in Activty

Second pass - activity complete as expected. Orchestrator moves onto second activity, never receives activity result.

**Comment by cgillum** [comment]
Got it. It looks like there were actually three passes (execution ID `8ebb...`, `6030...`, and finally `fc2d...`), but I do so see where it appears to get stuck.

There are a couple things I noticed that I need a bit more information about:
1. I'm seeing **two** activity function calls. You mentioned there is a second activity call, but the code you shared doesn't reflect this.

2. I'm seeing an external event sent to this orchestration (interestingly it was received at the **exact same time** as the second activity function return value at `2019-03-23 19:01:39.0265`). I didn't notice any external event processing in your orchestration either, so I wonder if I'm not getting the full picture.

Can you share a bit more of the orchestration code so that I can properly understand the events that I'm seeing in our telemetry? Also, if you could you send a screenshot (or csv) which shows the final history events in your Azure Storage account, that could be helpful as well.

**Comment by olitomlinson** [comment]
Hmmm I don't see a third pass. I only see the first pass of `603` and the second pass of `f2c`

1. The code I shared is the **second** activity. 

I didn't share the code for the first activity as there are no problems with that (you will see that this activity retried 10 times and failed in the first pass, this was expected, and then fixed in the second pass)

2. The Orchestration is essentially doing the following : 

1 - Activity Call 1 -> Calls an external HTTP API to get some data
2 - Activity Call 2 -> Publishes a message on Service Bus to trigger an external system A
3 - Orchestration begins to `WaitForExternalEvent`
4 - External System A puts a reply Message on Service Bus.
5 -` ServiceBusTrigger` Function receives Service Bus Message and raises the Event that is being waited for in step 4.
7 - Orchestration either completes or continues with other logic.

The event you are referencing is expected (step 5), however Activity call 2 has not yet returned a result, so the orchestration won't process the received event.

Given the privacy of the work I can't publicly share the source, but if you give me your email address or something else private I'm happy to share that way :)

**Comment by ConnorMcMahon** [comment]
@olitomlinson, are you still experiencing issues like this. I know we've made a lot of reliability improvements in the past couple of years.

**Comment by olitomlinson** [comment]
Yeah I’ve l not experienced this in a long, long time now.
