### ISSUE TITLE
Direct access to actors from clients

### ISSUE THREAD

**Issue by sebastianburckhardt** [Azure/azure-functions-durable-extension#674]
(This issue was brought up in the discussion of #663)

The current implementation #663 of durable actors #22 does not allow clients to access actors directly - instead, they have to call an orchestration which then calls the actor. This is cumbersome and slow. 

We should consider extending `IDurableOrchestrationClient` so clients can access actors directly.

- Signaling actors from the client is very easy, we can start with that (all the client needs to do is raise an event). 
- Calling actors from clients is not at all straightforward because there is no easy way to track the status and/or send the result back. If we want to support that, we need to figure out a design (perhaps extend the storage provider?).

**Comment by cgillum** [comment]
Have you considered an approach where actors are _queried_ rather than _called_? For example, I could imagine a case where we signal an actor to update its state, and then use the existing `GetStatusAsync` API (or some equivalent) to query that state. It's not as powerful as a _get_ method because you can't write any custom code to control what state the client sees, but it might solve the problem for a large set of use-cases. Thoughts?

**Comment by sebastianburckhardt** [comment]
Yes, querying is a bit easier to support. It is not as easy as with orchestrations though because  the actor does not keep a permanent record of all the operations is processes; once it calls ContinueAsNew, you can no longer look at the history to determine the status of an operation.

**Comment by sebastianburckhardt** [comment]
Until we have a better way of sending things to the client within the runtime, the following solution can provide a stop-gap by adding *approximate* versions of actor read and update capabilities from within the client.

- For the purpose of updating actors, clients can signal the actor (one-way). 
- For the purpose of reading from actors, clients can get the entire state of the actor.

These are however not 100% clean, in the following ways:
- the update completes after the signal is enqueued, not after the actor is actually updated.
- the read returns a possibly stale version of the actor state.
- the read does not return the actor state if the state is larger than 16KB
- the read must return all of the state, and exposes its representation (breaks encapsulation)

However, I think this is o.k. for now because clients that are not happy with these limitations can fall back to calling actors via an orchestration - from within an orchestrations, the model is 100% clean.

**Comment by sebastianburckhardt** [comment]
I think that this issue will be resolved after merging #719 which removes the 16KB limitation.
