### ISSUE TITLE
Name property of OrchestrationStatus isn't propogated to JavaScript durable functions like it is in .NET

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-durable-extension#679]
**Describe the bug**

When creating a .NET durable function and you want to get the status of all instances the returned type has a `Name` property which represents the name of the Function.

When attempting the same in JavaScript the `Name` property is not returned on the object as it has to use the [webhook API](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-all-instances-status) call rather than going directly through the .NET code.

Because of this in JavaScript it isn't possible to determine the durable function instances and perform filtering or invoke an event on a particular one.

I've created a sample that shows the different between the two implementations: https://github.com/aaronpowell/durable-status-test (with the `master` branch being JavaScript and the `dotnet` branch being C#).

**Investigative information**

- Durable Functions extension version: 1.7.1
- Function App version (1.0 or 2.0): 2.0
- Programming language used: JavaScript and .NET
- durable-functions npm module version: 1.1.4

**To Reproduce**

1. Clone https://github.com/aaronpowell/durable-status-test
2. Start the functions app
3. Navigate to `<host>/api/start/<some input>`
4. Navigate to `<host>/api/check/<some input>`
5. See that there is no `Name` property in the response
6. Repeat for the `dotnet` branch and observe there is a `Name` property in the response

**Expected behavior**

Parity in the types returned so that the `Name` appears for all types, allowing events to be raised on instances.

**Actual behavior**

`Name` property is only returned for .NET.

**Known workarounds**

The only workaround I can find is to add additional metadata into the `input` when starting a function from the orchestrator.

**Additional context**

PR #678 has been created to resolve this issue.

**Comment by cgillum** [comment]
This fix has been released in the [v1.8.1 release](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.8.1).
