### ISSUE TITLE
Expired CreateTimer() events aren't processed at scheduled time

### ISSUE THREAD

**Issue by mhoeger** [Azure/azure-functions-durable-extension#684]
_From @apsteger on May 11, 2019 04:59_

Investigative information
Timers created with CreateTimer() don't seem to be triggered at the scheduled times. I noticed this running locally. I posted this question on StackOverflow

Why doesn't my Durable Function Orchestrator awaken at the time specified in DurableOrchestrationContext.CreateTimer()?

Why does my orchestrator function sleep for longer than the time I specify with CreateTimer()? I am calling it like this:

var resumeAt = context.CurrentUtcDateTime.AddSeconds(60);
await context.CreateTimer(resumeAt, CancellationToken.None);

You can see from the logs below that it actually resumes after 80 seconds rather than 60 seconds:

[03/06/2019 10:41:47 PM] 0021fd6e-1055-4f3b-ba42-34301c7affed: Function 'Dps_Orchestrator (Orchestrator)' is waiting for input. Reason: CreateTimer:2019-03-06T22:42:47.3037098Z. IsReplay: False. State: Listening. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.7.1. SequenceNumber: 9096.

[03/06/2019 10:43:07 PM] 0021fd6e-1055-4f3b-ba42-34301c7affed: Function 'Dps_Orchestrator (Orchestrator)' was resumed by a timer scheduled for '2019-03-06T22:42:47.3037098Z'. IsReplay: False. State: TimerExpired. HubName: DurableFunctionsHub. AppName: . SlotName: . ExtensionVersion: 1.7.1. SequenceNumber: 9098.

What is going on?

_Copied from original issue: https://github.com/Azure/azure-functions-host/issues/4180_

**Comment by cgillum** [comment]
Hi @apsteger. From the logs, I can see that you're running your function app locally. Unfortunately there are a lot of variables that could be causing this, such as running on a really slow or busy machine, or it could be due to other debugging that is being done on this process that is preventing the timer message from getting dequeued from storage.

Are you able to reproduce this problem in Azure? If so, then we should be able to look at our Azure telemetry to see what's going on. I would just need to know which region your app is located in and ideally the ID of your orchestration instance.

**Comment by brttjwll** [comment]
I am also seeing this issue. I would like to understand better why this delay occurs, and how to improve it.

I have a very simple function app which is based on period work example. https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-eternal-orchestrations?tabs=csharp#periodic-work-example

I schedule 30 seconds of sleep using CreateTimer(), and I observe the function is resumed usually 20-25 seconds after the timer was scheduled to expire.

Example log message:

6/24/2020, 9:33:37.899 PM | StaticId: Function 'Periodic_Cleanup_Loop (Orchestrator)' was resumed by a timer scheduled for '2020-06-24T21:33:11.6146871Z'. IsReplay: False. State: TimerExpired. HubName: PeriodicWorkExample20200624114312. AppName: PeriodicWorkExample20200624114312. SlotName: Production. ExtensionVersion: 2.2.2. SequenceNumber: 65.

My function app is in the east us region.

**Comment by cgillum** [comment]
@brttjwll would you mind opening a new issue for this? That would make tracking easier.
