### ISSUE TITLE
Events added to in-memory queue clarification

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#686]
I am also trying to understand functionality added in version 1.8.0 to address the "Race conditions causing external events to be dropped" issue.

I have a Orchestration running with the following code:

```
        [FunctionName("TestOrch")]
        public static async Task Start([OrchestrationTrigger] DurableOrchestrationContextBase context)
        {
            await context.CreateTimer(context.CurrentUtcDateTime.AddSeconds(5000), CancellationToken.None);

            await context.WaitForExternalEvent("Test");

            context.ContinueAsNew(null);
        }
```

And started with the following:

```
        await client.StartNewAsync("TestOrch", instanceId, null);

        await client.RaiseEventAsync(instanceId, "Test", 1);

        await client.RaiseEventAsync(instanceId, "Test", 2);
```
What is the expected behavior? What I am seeing is `ContinueAsNew` is only being called once.

Any clarification would be great!

also, are events not considered state the gets reset with ContinueAsNew?

**Comment by cgillum** [comment]
The expected behavior is that `ContinueAsNew` gets call twice. If that's not happening, then this is probably a bug. Actually, another user opened a similar issue not too long ago, and I'm currently investigating it: https://github.com/Azure/azure-functions-durable-extension/issues/676. My expectation is that you're experiencing the same underlying issue.

**Comment by mpaul31** [comment]
hmm ok based on the following documentation regarding ContinueAsNew I would expect once as the second event should be discarded.

https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationContext.html#Microsoft_Azure_WebJobs_DurableOrchestrationContext_ContinueAsNew_

**Comment by cgillum** [comment]
@mpaul31 Ah, yes, it looks like we forgot to update some of the documentation. I'll reopen this to track fixing the docs to clarify the expected behavior.

**Comment by mpaul31** [comment]
i could still see it being useful to have the events discarded when ContinueAsNew is called. For example, what if I want my orchestration to wait for a "refresh" event before invoking ContinueAsNew.
