### ISSUE TITLE
Activity function OutOfMemory leaves orphan workitem that continually reprocesses

### ISSUE THREAD

**Issue by TheFairey** [Azure/azure-functions-durable-extension#687]
**Describe the bug**
I have an activity function that merges PDFs together however if I have too many to merge I suspect it's hitting an out of memory error as occasionally I seem to catch them but more often than not the host instance just dies

**Investigative information**

- Durable Functions extension version: 1.8
- Function App version (1.0 or 2.0): 1.0
- Programming language used: .Net Framework 4.6.1

- Function info: 2019-03-31T09:28:44.8841496Z Function started (Id=07a10607-19d4-4194-a795-6a464050349b)
- Region: North Europe

**To Reproduce**
I'm wondering if maybe I should have posted this in the Functions Issues, I tried the following as a simple function and I see the add chunks then it just stops, not sure if this is a realistic test of when it might run as an activity though?

```
using System;
using System.Collections.Generic;

public static void Run(TimerInfo myTimer, ILogger log)
{
    log.LogInformation($"C# Timer trigger function Memory Eater executed at: {DateTime.Now}");
    List<byte[]> wastedMemory = new List<byte[]>();

    try{
        while(true)
        {
            byte[] buffer = new byte[4194304]; // Allocate 4MB
            wastedMemory.Add(buffer);
            log.LogInformation($"Added a 4MB chunk");
        }
    }
    catch(Exception e){
        log.LogInformation($"Exception - {e.ToString()}");
        throw e;
    }
    log.LogInformation($"Somehow made it through?"); // Never see this obviously
}
```

**Expected behavior**
Catch whatever is killing the instance and generate an appropriate exception

Alternatively can I stipulate a max dequeue count maybe for the workitem, currently it's around 700 odd

**Actual behavior**
A silent untraceable death!

Thanks

Si

**Comment by cgillum** [comment]
I suspect the problem is that the functions host gets recycled when there is an `OutOfMemoryException`. This is causing the message to get placed back onto the queue and then retried after about 5 minutes.

We don't really have a way to deal with this today. What we really need is a Poison Message handling strategy, which is being tracked here: https://github.com/Azure/azure-functions-durable-extension/issues/338.

**Comment by TheFairey** [comment]
Makes sense, is there any way to access the dequeue count currently from within the activity. Failing that I'll have to find some other way to handle this. As you point out it's spinning up every 5 mins to try and process the message again currently!
