### ISSUE TITLE
Couple of issues with using the HTTP API

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#695]
DF v1.8.0 
Functions Runtime V2
UK South

Given an instance id (05f702ae-00bc-489d-aa01-5c0e10675d4c) that is in the 'Failed' state

1. Make request to [Get Instance Status](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-instance-status) endpoint :

**Actual**  HTTP 500,  despite the response body actually containing a valid and expected instance payload.

**Expected** HTTP 200

2. Make request to the [Purge Single Instance History](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-instance-status) endpoint :

**Actual** HTTP 404 and not actually Purging, despite the instance actually existing in the Task Hub Storage.

**Expected** HTTP 20x - The resource is deleted

**Comment by cgillum** [comment]
Thanks @olitomlinson. At a high level I don't disagree with you on (1). However, I think we returned HTTP 500 intentionally because polling clients (like Azure Logic Apps) need a HTTP-level signal that indicates that a long-running operation failed. Returning 200 makes it look like the operation succeeded.

Regarding (2), this sounds like a bug that we should fix.

**Comment by olitomlinson** [comment]
@cgillum with regards to (1) the response did actually succeed, I got the response body that I expected (the full dump of the instance state) but got HTTP 500 rather than the 200.

**Comment by olitomlinson** [comment]
Actually I think I see what you're saying now.

_Because_ the instance is in a failed state, you want to return HTTP 500.

Maybe the default behaviour for this endpoint should be changed in v2 to return 200 if the orchestration is in a failed state. 

However, for exceptional use-case like polling from Logic Apps, an optional request parameter could be supplied to change the behaviour to return 500. Or even better, a separate endpoint that contains the exceptional behaviour, just for logic apps.

**Comment by mpaul31** [comment]
i would never expect a 200 for a failed state, i am not following your logic why most would expect a 2XX response code.

**Comment by olitomlinson** [comment]
The problem is the domain (orchestration) is bleeding out its internal state into the HTTP response code, which is not correct usage of a HTTP response code.

Was there an Internal Server Error (500) whilst processing _this_ request? No there wasn't, as evidenced by the response body which contained the orchestration state.

I appreciate that this is a nice short-cut for Logic Apps to get a HTTP-level signal on the state of the orchestration, but that's exactly what it is, a short cut for a particular scenario.

For those reasons returning a 500 shouldn't be the _default_ behaviour.

**Comment by cgillum** [comment]
@olitomlinson I think that's fair feedback, and something we should consider for v2, since that is a breaking change release.

**Comment by ConnorMcMahon** [comment]
The purge history should have been fixed as a part of issue #707.

**Comment by cgillum** [comment]
@amdeel, could you look into making a fix for the following?

> **Actual**
> HTTP 500, despite the response body actually containing a valid and expected instance payload.

The suggestion mentioned in [this comment](https://github.com/Azure/azure-functions-durable-extension/issues/695#issuecomment-482005209) seems reasonable to me - i.e. let's find a way to make the HTTP 200 vs. 500 behavior configurable.

One option I can think of is to add a new parameter to the [CreateCheckStatusResponse](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationClient.html#Microsoft_Azure_WebJobs_DurableOrchestrationClient_CreateCheckStatusResponse_System_Net_Http_HttpRequestMessage_System_String_) API that allows you to choose which behavior you want. I suggest consulting with Connor on how we can best design and implement this.
