### ISSUE TITLE
OrchestratorFunctions breakpoints not hit and never resuming after CallSubOrchestratorWithRetryAsync

### ISSUE THREAD

**Issue by jamesmundy** [Azure/azure-functions-durable-extension#698]
**Describe the bug**
I have an Azure Function triggered by a message that then uses the client to start an Orchestrator function which starts a series of sub-orchestrators, awaits for these to finish and then should call a finalise Activity Function.

I noticed when deployed to Azure my final activity was not being called so looked into this locally and this was the case also. The suborchestrations are called (I can see their output) so clearly the initial orchestrator is being called to trigger them but no breakpoints are hit in this initial orchestrator and the final bit of the code after awaiting the suborchestrations is never called.

**Investigative information**

- Durable Functions extension version: 1.8.0
- Function App version (1.0 or 2.0): 1.0 (1.0.12299.0 on Azure)
- Programming language used: C#

***If deployed to Azure***
Operation ID: e57eff1c-0cb2-4c56-9aae-df5f98b9520a
Operation Name: CalculatePointscoreSummaryOrchestrationFunction
I only ran once before I rolled back

**To Reproduce**

Here's a simplified version of the code:
```
[FunctionName("CalculatePointscoreSummary")]
        public static async Task CalculatePointscoreSummary([QueueTrigger(QueueName)] string value,
            [OrchestrationClient]DurableOrchestrationClient durableOrchestrationClient,
            [FInject(typeof(ILoggerServices))] ILoggerServices loggerServices,
            TraceWriter log,
            ExecutionContext context)
        {
                    var message = //Get function input queue message
                    var divisionMessages = //Create message code
                    var orchestration = await durableOrchestrationClient.StartNewAsync(nameof(CalculatePointscoreSummaryOrchestrationFunction), divisionMessages);
        }

        [FunctionName(nameof(CalculatePointscoreSummaryOrchestrationFunction))]
        public static async Task CalculatePointscoreSummaryOrchestrationFunction([OrchestrationTrigger]DurableOrchestrationContext durableOrchestrationContext,
            TraceWriter log,
            ExecutionContext context)
        {
            var divisionMessages = durableOrchestrationContext.GetInput<List<PointscoreSummaryDivisionCalculationMessage>>();

            var parallelTasks = new List<Task>();
            foreach (var divisionMessage in divisionMessages)
            {
                var task = durableOrchestrationContext.CallSubOrchestratorWithRetryAsync(nameof(CalculatePointscoreSummaryDivisionFunction), _retryOptions, divisionMessage);
                parallelTasks.Add(task);
            }

            await Task.WhenAll(parallelTasks);

            await durableOrchestrationContext.CallActivityWithRetryAsync(nameof(FinalisePointscoreSummaryFunction), _retryOptions, new PointscoreSummaryCalculationMessage(divisionMessages.First().SeriesId));
        }
        
        [FunctionName(nameof(CalculatePointscoreSummaryDivisionFunction))]
        public static async Task CalculatePointscoreSummaryDivisionFunction([OrchestrationTrigger]DurableOrchestrationContext durableOrchestrationContext,
            TraceWriter log,
            ExecutionContext context)
        {
            var message = durableOrchestrationContext.GetInput<PointscoreSummaryDivisionCalculationMessage>();
            var boatMessages =
                await durableOrchestrationContext.CallActivityWithRetryAsync<List<PointscoreSummaryBoatCalculationMessage>>(nameof(GetBoatSummmaryMessages),
                    _retryOptions, message);
        }
```

**Expected behavior**
The orchestator should resume after the last suborchestrator is complete.

**Actual behavior**
No breakpoints are hit in `CalculatePointscoreSummaryOrchestrationFunction` and it doesn't continue after starting the suborchestrators.

**Additional context**
- Development environment: VS 2017 Community (latest)

**Comment by cgillum** [comment]
Hi @jamesmundy. I found the function app associated with operation ID `e57eff1c-0cb2-4c56-9aae-df5f98b9520a`. However, we don't have any record of any durable function execution using 1.8.0 in the last 7 days. All of them are using v1.7.1. I checked both your "prod" and "dev" apps. Are you sure you deployed a version of your app with v1.8.0?

In any case, I looked into the v1.7.1 execution that I *think* maps to `e57eff1c-0cb2-4c56-9aae-df5f98b9520a`. It appears to map to orchestration instance ID `ab9bb2890c9d4005a7bbdd94a8204bee` but I would need your help confirming. I see that the sub-orchestrations are starting and completing, but oddly I don't see any indication that they called an activity function, or that any results were sent back to the parent orchestration. It's quite strange - something I wouldn't expect unless the orchestration code were doing some illegal async operations (which can confuse the orchestration engine).  Is the sub-orchestration code you provided the exact code which your application is using, or is there perhaps additional code executing before the call to `CallActivityWithRetryAsync`?

**Comment by jamesmundy** [comment]
Hi @cgillum thanks for looking into this.
Firstly, I apologise for the confusion - I forgot I only upgraded to 1.8 after deploying and the same issue occurred.
Your question did give me pause for thought though and I took another look at the sub-orchestrator function and found I was calling an async method in one of my services but it was never reaching that point where it would have thrown an exception (which has happened when I was learning about durable functions). Removing that async method call and turning it into an ActivityFunction caused the breakpoints to be hit again and the sub-orchestrator to work as planned.

Here is the function:
```
[FunctionName(nameof(CalculatePointscoreSummaryOrchestrationFunction))]
        public static async Task CalculatePointscoreSummaryOrchestrationFunction([OrchestrationTrigger]DurableOrchestrationContext durableOrchestrationContext,
            [FInject(typeof(IPointscoreService))] IPointscoreService pointscoreService,
            [FInject(typeof(ILoggerServices))] ILoggerServices loggerServices,
            TraceWriter log,
            ExecutionContext context)
        {
            var divisionMessages = durableOrchestrationContext.GetInput<List<PointscoreSummaryDivisionCalculationMessage>>();

            var parallelTasks = new List<Task>();
            foreach (var divisionMessage in divisionMessages)
            {
                var task = durableOrchestrationContext.CallSubOrchestratorWithRetryAsync(nameof(CalculatePointscoreSummaryDivisionFunction), _retryOptions, divisionMessage);
                parallelTasks.Add(task);
            }

            await Task.WhenAll(parallelTasks);

	    //await pointscoreService.OrderPointscoreForSeries(message); Turn into Activity
            await durableOrchestrationContext.CallActivityWithRetryAsync(nameof(FinalisePointscoreSummaryFunction), _retryOptions, new PointscoreSummaryCalculationMessage(divisionMessages.First().SeriesId));
        }
```
I've deployed to production and it now all works perfectly: `4dad06c0-3f1e-4c0f-916b-932edcce64f0`
Is having an async method in the orchestrator enough to throw it off even if it never reaches that point? The breakpoints being ignored was strange too.

As an aside, we just managed to reduce a process that was taking 10+ minutes to run in 44 seconds by breaking the task up and doing lots of parts in parrallel with sub orchestrations. Thanks for your hard work!

**Comment by cgillum** [comment]
Awesome - glad to hear that resolved the issue.

An illegal async shouldn't affect any code that executes _before_ that async operation, so I'm not sure why the earlier breakpoints wouldn't have worked.

Since the core issue is resolved, I'll go ahead and close this issue. Let me know if there are other questions you have though.
