### ISSUE TITLE
how to support an event that triggers multiple times

### ISSUE THREAD

**Issue by rahulvmarathe** [Azure/azure-functions-durable-extension#699]
I have a scenario where an orchestrator needs to support two types of activities 1. happening only one time in the orchestrator's lifetime, 2. activities that may happen multiple times.

Activities that need to happen one time are implemented in the main orchestrator. 

The activities that may happen more than one time are implemented in a sub-orchestrator. The activities that may happen more than one time are triggered via external events. The event implementation in the the sub-orchestrator restarts the sub-orchestrator by calling ContinueAsNew function. 

However, in this implementation in the sub-orchestrator i am not able to append to an existing state when an event triggers, as by design ContinueAsNew overwrites the state.

Looking for suggestions to:

1. Support events that may occur more than once during the life of an orchestrator.
2. Support state that gets updated and not overwritten in case of an event.

Thanks and regards
Rahul

**Comment by cgillum** [comment]
I think the issue you're referring to was also reported [here](https://github.com/Azure/azure-functions-durable-extension/issues/676). In the [v1.8.1](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.8.1) release of our extension, we added support for saving external events across `ContinueAsNew` calls.  See this [ContinueAsNew](https://azure.github.io/azure-functions-durable-extension/api/Microsoft.Azure.WebJobs.DurableOrchestrationContext.html#Microsoft_Azure_WebJobs_DurableOrchestrationContext_ContinueAsNew_System_Object_System_Boolean_) overload which has a `preserveUnprocessedEvents` parameter for more information.
