### ISSUE TITLE
Purge Sub-orchestrations history

### ISSUE THREAD

**Issue by dscpinheiro** [Azure/azure-functions-durable-extension#704]
**Describe the bug**
As mentioned on https://github.com/MicrosoftDocs/azure-docs/issues/29312#issuecomment-482900343, the PurgeInstanceHistory API does not purge the history of sub-orchestrations.

**Investigative information**
- Durable Functions extension version: 1.8.0
- Function App version (1.0 or 2.0): 2.0
- Programming language used: C#

**To Reproduce**
For instance, if I have an orchestration id _e30696ff3f484cdc8832f0ccd3c68ad8_, which has three sub-orchestrators, calling the DurableOrchestrationClient.PurgeInstanceHistoryAsync method will only remove the parent orchestrator.

Before:
![before](https://user-images.githubusercontent.com/3842788/56131308-11fa8380-5f55-11e9-8ae5-7dfc0137f0ac.png)

After:
![after](https://user-images.githubusercontent.com/3842788/56131318-16bf3780-5f55-11e9-9955-982d39336e74.png)

It'd be very convenient if the other records were deleted as well.

**Comment by s-krawczyk** [comment]
+1

**Comment by s-krawczyk** [comment]
Any idea how to do it even manually?

**Comment by cgillum** [comment]
The recommended way to do this manually is to generate your own sub-orchestration IDs in a way that you can determine the relationship between the parent and the child. This could be done by either using a naming convension or externally store the relationship between the parent instance ID and the sub-orchestration ID.

If this is not possible or if you already have data you want to purge, then another option is to leverage the `ParentInstance` column in the history table. The payload is a JSON structure which has a reference to the parent instance ID. For example:

```json
{
  "Name": "MyParentOrchestrator",
  "OrchestrationInstance": {
    "InstanceId": "4dc5d0c35a3640e08be36c6c1b9d2108",
    "ExecutionId": "0699a52cdfd743109df39f4abf80abef"
  },
  "TaskScheduleId": 0,
  "Version": ""
}
```

**Comment by LockTar** [comment]
@dscpinheiro I see you closed this. Is this already released? If so, which version?

**Comment by dscpinheiro** [comment]
I don't believe it's been released; back when I created this issue (if I remember correctly) I ended up using the `ParentInstance` column as suggested in https://github.com/Azure/azure-functions-durable-extension/issues/704#issuecomment-483735285

I recommend creating a new issue if this doesn't help you, I'm not working with Azure at the moment so I wouldn't even be able to verify any fixes.
