### ISSUE TITLE
CS1503	Argument 1: cannot convert from 'Microsoft.AspNetCore.Http.HttpRequest' to 'System.Net.Http.HttpRequestMessage'

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-durable-extension#705]
**Starter function compilation fails due to conversion failure**
Compilation fails with message on this line " return starter.CreateCheckStatusResponse(req, orchestrationId);"  with reason "cannot convert from 'Microsoft.AspNetCore.Http.HttpRequest' to 'System.Net.Http.HttpRequestMessage'

**Investigative information**

- Durable Functions extension version: 1.8.0
- Function App version (2.0):
- Programming language used: c#

**To Reproduce**
Create new durable function app with return statement as 
`return starter.CreateCheckStatusResponse(req, orchestrationId);`

**Expected behavior**
Should not give compile time error

**Actual behavior**
Currently throws compile time error.

**Screenshots**
![image](https://user-images.githubusercontent.com/10679463/56152917-9ad7e600-5f7a-11e9-950f-d0e7d16141c5.png)

**Known workarounds**
Provide a description of any known workarounds you used.

**Additional context**

- Development environment (Visual Studio 2019)

**Comment by cgillum** [comment]
Durable Functions does not yet support the ASP.NET Core HTTP APIs. You will need to use the older `HttpRequestMessage`/`HttpResponseMessage` APIs in your HTTP triggers instead (take a look at our [samples](https://github.com/Azure/azure-functions-durable-extension/blob/dev/samples/precompiled/HttpStart.cs) for what this looks like).

There is another issue tracking adding support for the newer ASP.NET Core-style HTTP triggers: https://github.com/Azure/azure-functions-durable-extension/issues/318.
