### ISSUE TITLE
using ILogger for input parameter for OrchestrationTrigger function throws run time error

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-functions-durable-extension#706]
**Describe the bug**
using ILogger for input parameter for OrchestrationTrigger function throws run time error 

**Investigative information**

- Durable Functions extension version: 1.8.0
- Function App version (2.0):
- Programming language used: c#

**To Reproduce**
Create new orchestration function and change input parameter for logger as ILogger instead of TraceWriter.

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

**Expected behavior**
Orchestrator function should run fine with ILogger as input parameter

**Actual behavior**
I fails with run time exception as below.
```
Error indexing method 'O_ProcessVideoOrchestrator'
[04/15/2019 5:38:12 PM] Microsoft.Azure.WebJobs.Host: Error indexing method 'O_ProcessVideoOrchestrator'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'logger' to type ILogger. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```

**Screenshots**
![image](https://user-images.githubusercontent.com/10679463/56153464-d6bf7b00-5f7b-11e9-9598-8c1fd7b6ae87.png)

![image](https://user-images.githubusercontent.com/10679463/56153490-ea6ae180-5f7b-11e9-99a3-22e114bb527c.png)

**Known workarounds**
TraceWriter type works fine.

**Additional context**

- Development environment (Visual Studio 2019)

**Comment by cgillum** [comment]
I was unable to reproduce this issue locally. If you're saying that `TraceWriter` works, then my guess is that you're actually running Functions 1.0 (and not 2.0). I believe `ILogger` support was added only in Functions 2.0 and `TraceWriter` was deprecated.

Can you double-check your function app version? It should be included further up in the func host console output.

**Comment by damienestewart** [comment]
@krishnasingh1818, I'd also check your usings and make sure you have `using Microsoft.Extensions.Logging;` there.
