### ISSUE TITLE
Roslyn analyzer to detect illegal code in orchestrator functions

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#708]
Related to https://github.com/Azure/azure-functions-durable-extension/issues/58.

For orchestrator functions, there are several code constraints documented in our [code constraints documentation](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-checkpointing-and-replay#orchestrator-code-constraints). Unfortunately, not all users read documentation, and even if they do, specific guidelines can evolve over time. There are some very limited runtime checks to help detect cases where users write illegal code, but there are a lot of cases which cannot be caught.

One way to improve the overall experience is to include a Roslyn Analyzer in the Durable Functions extension which can detect code constraint violations at build time.

Some things which should be flagged:

- [x] Use of non-Durable input or output bindings
- [x] Use of APIs such as `Task.Delay`, `Task.Run`, or `Task.Factory.StartNew`.
- [x] Use of `Task.ContinueWith` which does not explicitly include the `ExecuteSynchronously` flag.
- [x] Use of common network APIs such as `HttpClient`, `HttpWebRequest`, `SqlConnection`, `CloudBlobClient`, etc.
- [x] Use of common "random-like" APIs such as `Guid.NewGuid`, `DateTime.Now`, `DateTime.UtcNow`, `Random`, etc.
- [ ] Use of non-readonly static variables in orchestration logic.
- [x] Use of environment variables in orchestration logic (e.g. `Environment.GetEnvironmentVariable(...)`)

Ideally, each warning or error should indicate what the workaround is and point to official documentation related to forbidden APIs.

**Comment by ladeak** [comment]
I would be happy to help to with some of these tasks. Is it expected to be delivered by one person, or tasks can be shared? Is there a getting started document (other then the Contributor Onboarding). I have questions around, which branch would we branch off etc.? I assume adding a new project for the analyzer is ok, and which .net standard would it target: 2.0 or 1.3? (I had previously seen issues with netstandard2.0, but I am seeing aspnet core also targets 2.0: https://github.com/aspnet/AspNetCore/tree/master/src/Analyzers/Analyzers/src )

**Comment by cgillum** [comment]
Hi @ladeak. These can definitely be broken up and done by multiple contributors. The Contributor guide is all we have right now for onboarding, but I'm happy to help answer questions for things which aren't already covered.

As far as project structure, I think a new project under the `src` directory makes sense, and ideally it would target .NET Standard 2.0. Let me know if you have other questions that I can help answer - we'd love to have contributions!

**Comment by ladeak** [comment]
Hi @cgillum, 
I have started the work on this branch, starting with the last bullet point: ```Guid.NewGuid()``` (and later with ```DateTime```, ```Random```, etc.). So far I am adding analyzer template projects and an empty skeleton and a unit test (which fails in the sense of TDD).

Progress can be tracked on my fork:
https://github.com/ladeak/azure-functions-durable-extension/tree/ladeak-analyzer/src/WebJobs.Extensions.DurableTask.Analyzers

Shall I open a "work in progress" PR, or that is fine in a later stage?

I have limited time in the next week or so, but I will have some time allocated to this throughout June.

**Comment by cgillum** [comment]
Hi @ladeak. Yes, that would be great if you could open a PR! I've been thinking about this lately and would love to have something like this soon. If you don't have time to finish it, I would consider it important enough that we could help complete it.

**Comment by ladeak** [comment]
Hi @cgillum ,

I don't want to hold you up, so I opened the PR: https://github.com/Azure/azure-functions-durable-extension/pull/856

I am sorry, but I could really get into the implementation part, it is mostly the empty project (and corresponding test project) setup, dependencies, etc.
I could not spend the amount of time, I was hoping for. I really would like to continue, but I do not see a clean opportunity in the summer.

**Comment by cgillum** [comment]
This work was done as part of #949 and will be released along with our Durable Functions 2.0.0-beta3 release.
