### ISSUE TITLE
Initial public actor API cleanup

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#709]
This is for tracking  some public surface area changes that we need to track for the initial release.

- [x] Rename `IDurableOrchestrationClient.SignalActor` to `SignalActorAsync`.
- [x] Rename `IDurableOrchestrationClient.ReadActorState` to `ReadActorStateAsync`.
- [x] Rename `Actor` to `Entity` in public APIs.
- [x] Remove JSON serializer settings from API parameters (let's do this in a separate all-up PR)

I'll continue to add more to this issue as I find them.

**Comment by sebastianburckhardt** [comment]
I have PRs open for all of these.
