### ISSUE TITLE
v2 C# function stuck in "Pending" on Linux 

### ISSUE THREAD

**Issue by richcoresln** [Azure/azure-functions-durable-extension#710]
Should it currently be possible to develop c# v2 functions in VS Code on Linux?
I can see instances being created in my azure storage account, however their states never leave "Pending".
On publishing these functions to Azure, they Complete successfully.

I'm using 1.8.0 of the extension, 2.2.203 dotnet and 2.5.553 of Azure function core tools.
Also using version 0.16.0 of the Azure Functions VS Code extension and running Ubuntu (18.04).

I'm new to using Durable Functions so any insights / advice appreciated, I may well be missing something obvious.

**Comment by cgillum** [comment]
In theory this should just work since it's all .NET Core. I've personally tested on macOS as well, though not Linux.

One question: what are you using for your Azure Storage dependency - i.e. what value do you have for the `AzureWebJobsStorage` app setting? Is it pointing to a real Azure Storage account? And if so, is it possible that another function app could be listening to the same task hub in that same storage account? One issue folks often run into is that function apps using the same storage account and task hub steal messages from each other, resulting in odd behavior like this.

**Comment by richcoresln** [comment]
Thanks @cgillum, good to hear that it should work in theory.

The issue can be reproduced against a new, Azure hosted storage account connecting via a Shared Access Signature (with full permissions) as specified in the `AzureWebJobsStorage` app setting.
No other functions apps are listening to this task hub, or using this storage account.

To provide some more information on the issue, I am using the "precompiled" sample found in this repository. The "HttpStart" function appears to complete successfully, returning the check status response for the "E1_HelloSequence". However the state of this instance in Task Hub remains in the "Pending" state and no history items records exist.

I have also tried testing against an emulated storage account (using azurite running inside docker) which appears to result in a different error. I suspect this is a separate unrelated issue to the one reported, in this instance, the task hub tables are created successfully in the emulated storage account, however calling `StartNewAsync` results in the following exception being thrown:
`[18/04/2019 06:24:57] Executed 'HttpStart' (Failed, Id=577b8a26-ea39-495f-8f91-c3f31de3b661)
[18/04/2019 06:24:57] System.Private.CoreLib: Exception while executing function: HttpStart. Microsoft.WindowsAzure.Storage: Unexpected response code, Expected:OK or NotFound, Received:InternalServerError.`

 



Result returning,

**Comment by richcoresln** [comment]
I am also seeing the same issue when creating Javascript functions.
Any more pointers for what to look into to try to figure out what might be going on here?

**Comment by richcoresln** [comment]
After digging into this a bit more I have discovered that the issue only seems to exist when attempting to use a Shared access signature against an Azure storage account.
When using the connection string from the Access Keys the issue is no longer present and orchestrations complete successfully.

Any idea why this occurs?

**Comment by cgillum** [comment]
Ah, that's an interesting finding. One possibility is that the version of the Azure Storage SDK we are using (v8.6.0) doesn't support the Shared access signature connection string. Can you try adding a nuget reference to [WindowsAzure.Storage 9.3.3](https://www.nuget.org/packages/WindowsAzure.Storage/9.3.3) to see if that resolves the issue?
