### ISSUE TITLE
State management for actors should be simplified

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#712]
I'm writing a simple actor test case. I noticed that `IDurableActorContext.GetState<T>` returns an `IStateView<T>`. My first reaction was "Why do we need `IStateView<T>` instead of just `T`"?  It took me a minute, but eventually I reasoned that it must be because we require the user to call the `WriteBack` method in the case where the state object is mutable.

To be honest, the experience felt a bit cumbersome, and I had to stop coding to spend time trying to understand what the expectations were for `IStateView<T>` - e.g. do I have to check if it can be null? What kind of concrete types are there? What are these other methods for? How do I mock this for unit testing and how much work will it be? Etc.

I was wondering if we could simplify the experience a bit. Here is my suggestion:

* Change `public IStateView<T> GetState<T>()` to simply `public T GetState<T>()`. This will simplify the process of accessing state.
* Create a new method `void SetState(object state)` for writing back the state. I think this is more discoverable and clear than `IStateView<T>.WriteBack()`.
* Remove `IStateView<T>`.

I believe these changes will result in a lot less cognative overhead for the developer (fewer methods and types that need to be reasoned about), simplified mocking, and is generally more consistent with existing durable APIs - which I think is important. It's also more likely to be consistent with the experience we create for other languages, which are less typed than .NET.

I think we should consider this for the initial release. I can put together a before/after example if that would help illustrate the increase in simplicity.

**Comment by sebastianburckhardt** [comment]
I agree that we should simplify this since it is causing unnecessary mental overhead. Some minor advantages to the old scheme were:

- for simple types such as the  integer in the counter example, you can write ```state.Value++``` instead of context.SetState(context.GetState<int> + 1). Certainly not a big deal.

- users can exert full  control over when and how things get serialized and deserialized, and can keep this independent of reading and updating the state.  For example,
```csharp
using (var s = ctx.GetState<T>( /* serialization settings */))
{
   /// read and update s as many times as you want
} 
```
This may be useful in some advanced scenarios, for example when using multiple alternative C# types for the same actor, but I agree it is more complicated than necessary for the simple stuff. 

BTW, the user is not really required to call the writeback, we are implicitly calling at the end of the operation. Another reason not to expose this at all.

**Comment by cgillum** [comment]
Regarding this:

> Users can exert full control over when and how things get serialized and deserialized, and can keep this independent of reading and updating the state.

I might be misunderstanding but even with a simplified `T GetState<T>()` you can read/write the local variable as much as you want. And I don't this the simplified version would prevent you from having control over serialization. From a performance perspective, we can still optimize the internal implementation of `GetState<T>()` and `SetState(object)` to only do (de)serialization when absolutely necessary.

One possible compromise would be to return an instance of a concrete type which only holds a pointer to the state object.  For example:

```csharp
public EntityState<T> GetState<T>();
```

...where EntityState<T> is defined simply as...

```csharp
public class EntityState<T>
{
    T State { get; set; }
}
```

This would allow the `state.Value++` pattern, but not require developers to be concerned about a new interface (i.e. one less thing that needs to be mocked for unit tests) or even calling `SetState(object)`. However, you might be trading _predictability_ for simplicity with an approach that allows users to _not_ explicitly save state.
