### ISSUE TITLE
Implement StartNewOrchestration functionality for actors & orchestrations

### ISSUE THREAD

**Issue by sebastianburckhardt** [Azure/azure-functions-durable-extension#715]
The current API allows actors and orchestrations to start new orchestrations using fire-and-forget semantics. This is how it works currently:

```
throw new NotImplementedException(); // TODO
```

Obviously we need to either implement this or remove it from the API.

**Comment by sebastianburckhardt** [comment]
After looking at this a little, I think this requires changes to DTFx. Given the tight schedule to the alpha release I vote for removing it from the API for now.

**Comment by cgillum** [comment]
@sebastianburckhardt do you think we still need this even if entities can bind to `IOrchestrationClient` and start orchestrations that way?

I believe we may have discussed this already, but I don't recall what the conclusion was (if any).

**Comment by sebastianburckhardt** [comment]
We need it for the exactly-once guarantee.

It's not particularly difficult to implement (I have a draft in a branch).

We have not made a big deal out of that yet, but I think in the long term the "exactly-once" story is actually important for positioning the Durable Functions model (orchestrations + entities) relative to low-level actor models that usually make no ordering or reliability guarantees for message delivery.
