### ISSUE TITLE
Question: In-flight Orchestrations and Activites during Slot Swap

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#722]
Can someone please help explain what happens during this scenario?

**Comment by cgillum** [comment]
This is more of an Azure App Service question, but for the most part, a slot-swap just changes the HTTP routing behavior of App Service frontends to an alternate app instance. In-flight orchestrations and activities will continue to run. The non-production slot might have its process recycled in some situations, but it will auto-recover and keep executing as before.

**Comment by mpaul31** [comment]
got it thanks. im going to guess the majority of us have slot settings so there is a small window where the prod and non prod slot runs concurrently with prod app settings before the worker is restarted. i was just trying to work out in my head if any race conditions could occur
