### ISSUE TITLE
Consider renaming IDurableEntityContext.GetOperationContent<T> to GetInput<T>

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#725]
The `IDurableEntityContext` interface defines a `GetOperationContent<T>()` method for reading the payload data of an operation. I'm wondering if it would be better to rename this to `GetInput<T>()`. 

One reason is for consistency with `IDurableActivityContext.GetInput<T>()` and `IDurableOrchestrationContext.GetInput<T>()`. I also like `GetInput<T>()` because it conveys the same meaning in fewer words.

One problem I've had so far with `GetOperationContent` when reading through the code and writing samples is that I often misread it or mistype it as `GetOperationContext` (switching the `n` for an `x`). WCF has an [OperationContext](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.operationcontext) type and that might be part of the reason why I get these confused. The fact that we have "context" parameters in all the durable function types also likely throws me off.

**Comment by sebastianburckhardt** [comment]
Yes, I completely agree. This was already on my list of things I wanted to change.
