### ISSUE TITLE
Debugging Durable Functions

### ISSUE THREAD

**Issue by philemon33** [Azure/azure-functions-durable-extension#729]
**Describe the bug**
Prop__ fields are empty in the App Insights traces collection

**Investigative information**

- Durable Functions extension version: 1.7.1
- Function App version (1.0 or 2.0): 2.0
- Programming language used: Javascript

***If JavaScript***

- durable-functions npm module version: 1.1.4

***If deployed to Azure***

- Timeframe issue observed: 2019-04-25T12:20:00.132
- Function App name: Tagger4
- Function name(s): A-Consume, B-Orchestrator
- Region: West Europe
- Orchestration instance ID(s): tagger-icao-based-id-5022466

> If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [Functions Host wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**To Reproduce**

1. Go to App Insights Tagger4
2. Click on Search -> Analysis
3. Run Query:
let targetInstanceId = "tagger-icao-based-id-5022466";
let start = datetime(2019-04-25T12:00:00);
traces
| where timestamp > start and timestamp < start + 240m
| where customDimensions.Category == "Function.A-Consumer.User"
| extend functionName = customDimensions["prop__functionName"]
| extend instanceId = customDimensions["prop__instanceId"]
| extend state = customDimensions["prop__state"]
| extend isReplay = tobool(tolower(customDimensions["prop__isReplay"]))
| extend sequenceNumber = tolong(customDimensions["prop__sequenceNumber"])
| where isReplay != true
| where message contains targetInstanceId
| project timestamp, functionName, state, instanceId, sequenceNumber, appName = cloud_RoleName

**Expected behavior**
A list of traces with the fields timestamp, functionName, state, instanceId, sequenceNumber, appName populated.

**Actual behavior**
A list of traces with the fields timestamp, and appName populated. **The field functionName, state, instanceId, sequenceNumber are blank.** ( see screenshot below)

**Screenshots**
![image](https://user-images.githubusercontent.com/5710468/56742107-6e8b4900-6774-11e9-8433-ffe548464e3c.png)

**Comment by cgillum** [comment]
What are the contents of these traces that have the blanks (you can expand the traces shown in your screenshot)? There are some traces where having blanks might be expected. I can't tell based on the screenshot you've provided.

**Comment by philemon33** [comment]
The blank fields in the screenshot (functionName, state, instanceId, sequenceNumber) are expected to have values.

**Comment by cgillum** [comment]
What are the contents of these traces that have the blanks (you can expand the traces shown in your screenshot)?

**Comment by philemon33** [comment]
It will take me some tome to reproduce, as we moved on, and I need to recreate all resources.

**Comment by cgillum** [comment]
Okay - do let me know if you're able to reproduce this. Otherwise if you don't have the time, I think we can let this issue age out.
