### ISSUE TITLE
Make partition counts configurable in Azure Functions

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#73]
## Summary
There needs to be an option to configure the partition count in host.json. This configuration property also needs to be documented.

## Reasoning
Durable Functions supports configuring the number of control queue partitions. See more details in the [Performance & Scale topic](https://azure.github.io/azure-functions-durable-extension/articles/topics/perf-and-scale.html) in the documentation. It's possible to configure this number when self-hosting the extension as an Azure WebJob. However, this configuration knob is not currently exposed to host.json, which means Azure Functions customers are limited to the default four partitions.

**Comment by andreasbotsikas** [comment]
+1 on exposing the PartitionCount property to tackle with fan-out scenarios with multiple coordinators

**Comment by tohling** [comment]
Fix https://github.com/Azure/azure-functions-durable-extension/commit/4e94b5f25eb8461efb4f785335db391ab893e7c5 merged to dev branch.
