### ISSUE TITLE
Orchestration trigger doesn't complete all the activity functions if its starts replaying

### ISSUE THREAD

**Issue by iamsuresha** [Azure/azure-functions-durable-extension#732]
I have an orchestration function which has some activities in the queue. First time it works fine and completing some activities. After few seconds orchestrator starts again with IsReplaying value 'True' but this time its not continuing the activities which are scheduled already and tasks ends here saying 'Non-Deterministic workflow detected: TaskScheduledEvent: 0 TaskScheduled '

@cgillum

**Comment by cgillum** [comment]
Can you please share your orchestrator function code?

**Comment by iamsuresha** [comment]
[FunctionName("MyDurableFeed")]
public static async Task<bool> TransformOrchestration([OrchestrationTrigger] DurableOrchestrationContext context)
{
    List<IProductDetail> productDetails = new List<IProductDetail>();
    List<Task<ProductDetail>> catTasks = new List<Task<ProductDetail>>();
    var timerCategories = new Stopwatch();
    var timerWarehouses = new Stopwatch();
    var timerProducts = new Stopwatch();

    if (context.IsReplaying == false)
    {

        string accountNumberShipTo = _appSettings.AccountNumberShipTo;
        string[] allAccountsToSend = accountNumberShipTo.Split(new string[] { "," }, StringSplitOptions.None);

        timerProducts.Start();
        if (allAccountsToSend.Length > 0)
        {
            foreach (string account in allAccountsToSend)
            {
                accNumShipTo = account.Split(new string[] { "-" }, StringSplitOptions.None);

                Dictionary<string, string[]> ProductSkusByAccountNumberShipto = new Dictionary<string, string[]>();

                List<IProductDetail> allProducts = new List<IProductDetail>();
                List<string> warehouseIds = new List<string>();
                warehouseIds = _appSettings.WholesaleWarehouse.Split(',').ToList();
                if (warehouseIds.Count == 0)
                    warehouseIds.Add("");
                timerWarehouses.Start();
                foreach (string warehouseId in warehouseIds)
                {
                    IEnumerable<IProductDetail> products = _productService.GetProductAsync(accNumShipTo[0], accNumShipTo[1], warehouseId);
                    productDetails = AutoMapper.Mapper.Map<IEnumerable<IProductDetail>>(products).ToList();
                }
            }
        }

        timerProducts.Stop();
        totalTimeProducts = timerProducts.Elapsed.TotalMinutes;


        timerCategories.Start();

        for (int i = 0; i < productDetails.Count; i++) 
        {
            Task<ProductDetail> task = context.CallActivityAsync<ProductDetail>("FetchCategoriesBySku", productDetails[i]);
            catTasks.Add(task);
        }
        await Task.WhenAll(catTasks);
    }
    timerCategories.Stop();
    totalTimeCategories = timerCategories.Elapsed.TotalMinutes;

    timerWarehouses.Stop();
    totalTimeWarehouses = timerWarehouses.Elapsed.TotalMinutes;

    //Assigning category ID and Product Categories
    productDetails.ForEach(cat => cat.CategoryId = catTasks.Find(x => x.Result.RetailSkuId == cat.RetailSkuId).Result.CategoryId);
    productDetails.ForEach(cat => cat.ProductCategory = catTasks.Find(x => x.Result.RetailSkuId == cat.RetailSkuId).Result.ProductCategory);
}

And my activity function code below:

    [FunctionName("FetchCategoriesBySku")]
        public static ProductDetail FetchCategoriesBySku([ActivityTrigger] DurableActivityContext context)
        {
            var prod = context.GetInput<ProductDetail>();
            List<string> categoriesDelimitedByCommas = _categoriesService.GetCategoriesBySku(prod.Sku);
            if (categoriesDelimitedByCommas.Any())
            {
                numberSkusWithCats++;
                prod.CategoryId = categoriesDelimitedByCommas[0];
                prod.ProductCategory = string.Join(",", categoriesDelimitedByCommas);
            }
            else
            {
                numberSkusWithNoCats++;
            }
            return prod;
        }

**Comment by cgillum** [comment]
Thanks. There are two major problems with the orchestration code, both of which make it non-deterministic:

1. Your use of `if (context.IsReplaying == false)` means that you aren't replaying logic, and failing to replay any of your previously executed orchestration logic will confuse the orchestration engine, resulting in "Non-Deterministic workflow detected".  `context.IsReplaying` should only be used for code which does not impact the orchestration logic, such as logging statements.
2. Your use of static variables is also problematic because static variable values are not guaranteed to be available. This means that replays are not guaranteed to have the same data at the same point in time as a previous execution, which also puts you at risk for "Non-Deterministic workflow detected".

If you remove the use of `context.IsReplaying` and your use of static variables in your orchestration logic, then I expect everything will work correctly.

For more information on the replay behavior of orchestrations, see this documentation: https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-checkpointing-and-replay

**Comment by iamsuresha** [comment]
Thank you @cgillum it worked. I just want to know id there anyway to calculate the total time taken to run the orchestration because I have stopwatch but it initiates every time replays

**Comment by cgillum** [comment]
Each orchestration instance has a creation time and a completed time. You can use those to approximate the end-to-end latency.

**Comment by iamsuresha** [comment]
That solved my issue. Thank you so much for your timely reply.
