### ISSUE TITLE
REST APIs for Durable Entities

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#733]
The patterns of interaction are different between entities and orchestrations. I think it makes sense to give entities their own REST APIs separate from orchestrations. Some ideas:

### Signaling an entity
```http
POST /runtime/webhooks/durabletask/entities/{name}/{key}?op={operation}

(JSON input)
```
Signals the `{name}` entity with key `{key}` with `5` as the operation input. For example:

```http
POST /runtime/webhooks/durabletask/entities/counter/device1?op=add

5
```

### Querying the state of an entity
```http
GET /runtime/webhooks/durabletask/entities/{name}/{key}
```
Returns the state of the entity named `{entity}` with key `{key}` as a JSON payload.

The nice thing about having HTTP APIs like this is that simple interaction scenarios require less coding - i.e. I don't have to write an HTTP trigger function to call the client APIs. It would also enable a simpler integration with the JavaScript client.

**Comment by sebastianburckhardt** [comment]
Should we also support a `DELETE` verb? Not sure if it has much application but it would fit the pattern.

**Comment by cgillum** [comment]
What would calling `DELETE` on an entity do? Remove the state? I think it makes sense to include this.

**Comment by sebastianburckhardt** [comment]
There is some ambiguity about `DELETE`. It could delete just the entity, or delete all the metadata (e.g. queues, locks, scheduler, ...) as well. In this case I think it should only delete the entity state, and maybe we need another API call (more like purge) that destructively (and dangerously) removes all data including history.

Given this complication maybe it is better to keep `DELETE` out of the story for now, so we don't run into misunderstandings until we have the rest of the management functions figured out.
