### ISSUE TITLE
[Question] Rerun specific activity during fanout/fanin

### ISSUE THREAD

**Issue by chinarosesz** [Azure/azure-functions-durable-extension#739]
My current workflow is making REST calls to a dependent service every four hours for data retrievel and processing, after that I massage the data in the right schema and then ingest it to Kustos or Data Lake. This process currently runs using durable functions scaling out to multiple machines because I could potentially call the same activity 100 times or more.

Since I’m using the Fan-out/Fan-in pattern, if a specific task fails after some retries, is there a way for Durable Functions to rerun the all the failed tasks? In my sample code below, it would be the accountName.

Below is a snip of my orchestrator code.

```csharp
        [FunctionName("Orchestrator")]
        public async Task OrchestratorAsync([OrchestrationTrigger] DurableOrchestrationContext context, ILogger logger)
        {
            // Retrieve account names from context
            IEnumerable<string> accountNames = context.GetInput<IEnumerable<string>>();

            // Get projects for each account
            List<Task> parallelTasks = new List<Task>();
            foreach (string accountName in accountNames)
            {
                Task task = context.CallActivityWithRetryAsync("RunBuildPumpActivity", RetryOptions, accountName);
                parallelTasks.Add(task);
            }

            // Wait for all accounts to complete
            await Task.WhenAll(parallelTasks);

            logger.LogInformation("All builds have been succesfully inserted");
        }
```

**Comment by cgillum** [comment]
Yes, you can definitely do this. It's really just a matter of figuring out how to model it in your code. For example, you could get all the failed tasks using the following snippet:

```csharp
List<Task> failedTasks = parallelTasks.FindAll(t => t.IsFaulted);
```

You might need a dictionary or some other data structure to map specific `Task` objects to specific `accountName` values so that you can run the activity functions again, but this should all be very doable.

**Comment by chinarosesz** [comment]
Very nice. Thank you.

Let's say I log all failedTasks in a dictionary with the accountName to AppInsights. Can I pass in a specific account to RunBuildPumpActivity from the portal and click Run? Or is this something that has to be implemented in code where I loop through all the failed accounts and then run them again?

**Comment by cgillum** [comment]
This is something you'd need to implement in code where you loop through the failed accounts.  If you want it to be completely automated, then you would add some code to re-run the failed activity functions sometime after the `Task.WhenAll`.

If you wanted to add a manual step you could do something along the lines of the [human interaction](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-concepts#human) pattern, where you require someone to click a link that sends an external event that triggers the re-running of the failed account tasks.

**Comment by chinarosesz** [comment]
For some reason, after reading human interaction pattern, I felt this could complicate my pipeline a bit more. I'll keep it simple to begin with by logging failed tasks and see where this goes. At the moment, I'm setting RetryOptions to rerun five times and wait for five minutes each time, I think that should be good enough and I won't need to rerun the failed tasks. Please correct me if my understanding is incorrect here for RetryOptions.

**Comment by cgillum** [comment]
That sounds very reasonable to me. Adding additional retry logic on top of the built-in retry logic would indeed add a lot more complexity.
