### ISSUE TITLE
ActivityTrigger input binding not binding property name to output parameter

### ISSUE THREAD

**Issue by VividDigital** [Azure/azure-functions-durable-extension#74]
I'm adjusting a functions app to use durable functions for a set of actions so I can tell when the process is done. Basically when an image is submitted it is diced into a number of tiles via a queue. 

Right now I'm adding a queue item for each tile to be processed, and the output binding to azure table storage and blob storage require a property from the bound input. The QueueTrigger signature looks like this:

`public static async Task Run
        (
            [QueueTrigger("image-piece")]ImagePieceModel imagePiece,
            [Table("{FolderName}")] IAsyncCollector<MosaicPiece> pieceRecords,
            [Blob("mosaics/{FolderName}/original.jpg")]ICloudBlob myBlob,
            [Blob("mosaics/{FolderName}/pieces/{X}_{Y}.jpg", FileAccess.Write)]Stream pieceStream,
            TraceWriter log
        )`

FolderName, X, and Y are all properties on ImagePieceModel and are handled automatically. When I change the QueueTrigger to be an ActivityTrigger the function is in error with: No binding parameter exists for 'FolderName'.

Is this functionality not implemented here? Do I have to use Binder, and if so can I do so with multiple outputs ie. the Table and 2 Blobs?

**Comment by cgillum** [comment]
I would expect this scenario to work, but it's possible there is a bug or some missing functionality in the activity trigger binding implementation which is preventing this from working.

@MikeStall any thoughts? The activity binding code is [here](https://github.com/Azure/azure-functions-durable-extension/blob/master/src/WebJobs.Extensions.DurableTask/Bindings/ActivityTriggerAttributeBindingProvider.cs).

I do suspect using `Binder` is the best way to work around this issue. I'm not aware of any reason why you couldn't use it for multiple outputs.

**Comment by VividDigital** [comment]
Any ideas here?

Ryan Payne
416.904.7238
http://thevividweb.com

**Comment by cgillum** [comment]
This might be related to https://github.com/Azure/azure-functions-durable-extension/issues/78. The symptoms are similar to other issues I've encountered.

**Comment by cgillum** [comment]
This should be fixed in the 1.1.0-beta2 release.

**Comment by DannyvanderKraan** [comment]
I am using Microsoft.Azure.WebJobs.Extension.DurableTask 1.2.0-beta3 and I am still getting: "...no binding parameter exists for..." 

My model:

```
   public class NewZippedBagMutationFileMessage
    {
        public string Url { get; set; }
        public string Name { get; set; }
    }
```

My function signature:

 ```
       public static async Task<string> Run([ActivityTrigger] NewZippedBagMutationFileMessage newZippedBagMutationFileMessage,
            [Blob("zipped-bagmutationfiles/{Name}", FileAccess.Write, Connection = "AzureWebJobsStorage")]  Stream zippedBagMutationFile,
            ILogger log,
            [Inject]IProvideBagMutationFiles repository)
        {
//Stuff happens...
}

```
It can't bind "Name". Am I doing something wrong or is this still an issue? Thank you in advance for thinking with me.

**Comment by cgillum** [comment]
Mentioning here as well, this issue has been fixed in Beta 3 (I accidentally closed this during the beta 2 release). The syntax is a little different for activity triggers than it is for some other trigger types. See this PR for examples: https://github.com/Azure/azure-functions-durable-extension/pull/172
