### ISSUE TITLE
[Question] logReplayEvents set to false but still writes to AppInsights

### ISSUE THREAD

**Issue by chinarosesz** [Azure/azure-functions-durable-extension#744]
I've explicitely set `logReplayEvents` to `false` because I don't want the extra logs as it can be difficult to search. However, I am unable to see any changes to Application Insights after this value is configured to false. 

I have an Azure Function in .NET Core, when I looked at the logs, the orchestrator shows duplicate logs. I even added a debugging message to check the value of IsReplaying property and it returns true. I believe it's supposed to return false because of my configuration in host.json. 

Not sure what else I'm missing. I verified that host.json gets deployed with the updated value by looking at Kudu. 

host.json
```json
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "AdoProjectFunctions",
      "logReplayEvents": false
    }
  }
}
```
orchestrator code
```csharp
[FunctionName("Orchestrator")]
public static async Task OrchestratorAsync([OrchestrationTrigger] DurableOrchestrationContext context, ILogger logger)
{
    logger.LogInformation($"IsReplaying={context.IsReplaying}");
            
    // Get list of account names
    IEnumerable<string> accountNames = context.GetInput<IEnumerable<string>>();

    // For each account get projects, do this in parallel
    List<Task<JArray>> parallelTasks = new List<Task<JArray>>();
    foreach (string accountName in accountNames)
    {
        logger.LogInformation($"EntityName=Project, EntityStatus=Running, EntityAccount={accountName}");

        Task<JArray> task = context.CallActivityWithRetryAsync<JArray>("Activity_PullData", ProjectFunctions.RetryOptions, accountName);
        parallelTasks.Add(task);

        logger.LogInformation($"EntityName=Project, EntityStatus=Done, EntityAccount={accountName}");
    }

    // Wait for all accounts to complete pulling data from Azure Devops
    JArray[] resultsArray = await Task.WhenAll(parallelTasks);

    // Ingest to DataLake
    await context.CallActivityAsync("Activity_IngestToDataLake", resultsArray);

    // Ingest to Kustos
    await context.CallActivityAsync("Activity_IngestToKustos", resultsArray);
}

```
AppInsights shows that the orchestrator gets logged multiple times, when it should be only once.

![image](https://user-images.githubusercontent.com/1569868/57055295-6ee18380-6c4f-11e9-83cc-fda53b2ec2e9.png)

**Comment by cgillum** [comment]
The `logReplayEvents` setting is specifically about the df-specific tracking data events that are documented [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics#application-insights). This setting doesn't have any impact on the generic functions app insights tracing that you are showing in your screenshot. We don't currently have any way of suppressing those, unfortunately.

**Comment by chinarosesz** [comment]
I see. I can live with the extra logs. 

Is it possible to turn off replay, at least in debug mode? Currently I'm working around by using conditional debug and prefer that I don't have to do it all the time.

**Comment by ConnorMcMahon** [comment]
@chinarosesz, take a look at using [extended sessions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#orchestrator-function-replay) when debugging locally. You may even want to consider doing that in production, assuming that the trade-offs make sense for your production scenario.

**Comment by chinarosesz** [comment]
Thanks for the suggestion. I will give this a try, just a bit worried about the trade-offs.

**Comment by pawel-zolty** [comment]
If you are use durable function v2 there is no field `logReplay` anymore.
Schema look like this:
```
{
 "extensions": {
  "durableTask": {
    "hubName": "MyTaskHub",
    "storageProvider": {
      "connectionStringName": "AzureWebJobsStorage",
      "partitionCount": 4,
      .............
    },
    "tracing": {
      "traceInputsAndOutputs": false,
      "traceReplayEvents": false,
    },
    ...........
```

You should use extensions.tracing.traceReplayEvents field instead.
