### ISSUE TITLE
 Sub-orchestrator does not return control to parent orchestrator when using same instanceId

### ISSUE THREAD

**Issue by gautamdhameja** [Azure/azure-functions-durable-extension#746]
When calling a sub-orchestrator by passing the InstanceId of the parent orchestrator, the sub-orchestrator never returns control to the parent orchestrator after its execution.

For example, in the following snippet, I am passing the instance id of the parent orchestrator as the value of `instanceId` parameter of the `CallSubOrchestratorAsync` method. In this case, the control never returns to the line after the `CallSubOrchestratorAsync` call.

```
[FunctionName("SagaOrchestrator")]
public static async Task<Booking> RunOrchestrator(
    [OrchestrationTrigger] DurableOrchestrationContext context)
{
    var booking = await context.CallActivityAsync<Booking>("GetBooking", context.InstanceId);
    Console.WriteLine("Flight: {0}, Hotel: {1}, Taxi: {2}", booking.Flight, booking.Hotel, booking.Taxi);

    var hotelBooking = await context.CallSubOrchestratorAsync<Booking>("HotelBookingOrchestrator", context.InstanceId, null);
    
    // control never returns here after the execution of the line above
    
    Console.WriteLine("Flight: {0}, Hotel: {1}, Taxi: {2}", hotelBooking.Flight, hotelBooking.Hotel, hotelBooking.Taxi);

    return booking;
}
```

However, when the  `instanceId` parameter of the `CallSubOrchestratorAsync` method is passed as null or another value then it works fine.

**Initial analysis:** It seems (just an assumption) that the `instanceId` is being used internally to check/manage the status of the orchestrator execution. When the sub-orchestrator completes execution with the same `instanceId` then the framework also marks the parent orchestrator as completed (because of same `instanceId`).

**Use-case:** I was passing in the same `instanceId` to use it as the workflow id for logging in all activities. Later I found that there is `ParentInstanceId` available in the `context` which can be used for this purpose. Still, this seems to be a valid issue because the flow is broken when reusing `instanceId` across sub-orchestrators.

**Comment by cgillum** [comment]
The instance ID of a parent must never be used as the instance ID of a sub-orchestration. The instance IDs must always be different (e.g. a new GUID). Otherwise, the sub-orchestration will overwrite the history of the parent orchestration, and this explains why the parent orchestration never resumes.

I've opened an issue to track throwing an exception if `CallSubOrchestrationAsync` is ever called with the parent instance's ID.

**Comment by gautamdhameja** [comment]
Thanks. Can this be also made clear in the docs?
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-sub-orchestrations

I think a bit of description for the `InstanceId` param for sub-orchestrators and best practices around that would be good to add to the docs.
