### ISSUE TITLE
WaitForExternalEvent with timeout throws immediately if timeout > 6 days

### ISSUE THREAD

**Issue by lxalln** [Azure/azure-functions-durable-extension#749]
When calling `context.WaitForExternalEvent(eventName, TimeSpan.FromDays(7)`, a `TimeoutException` is thrown immediately, with a message saying that the event was not received within 7 days.

After battling with this and eventually switching to `Task.WhenAny` and `context.CreateTimer(context.CurrentUtcDateTime.AddDays(7))`. I received an exception telling me that I must not create a timer that is longer than 6 days.

When I then set `context.WaitForExternalEvent(eventName, TimeSpan.FromDays(6)`, it works as expected.

It would have saved me an hour or 2, if the immediately thrown `TimeoutException` had included a message similar to that from `CreateTimer`. Either that or an `ArgumentException` should be thrown because currently `TimeSpan.FromDays(7)` is not valid.

Function app version 2.0
Programming language: C#
Extension version: 1.8.0

**Comment by cgillum** [comment]
Interesting. I agree this is super misleading. We'll look into this.

**Comment by cgillum** [comment]
This fix was released as part of [v1.8.2](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.8.2).
