### ISSUE TITLE
[Question] Is it possible to access Azure Key vault in Durable functions?

### ISSUE THREAD

**Issue by anskanth** [Azure/azure-functions-durable-extension#750]
Hi, Trying to build a durable function which has to access KeyVault and get some secured creds to process further. however, it seems there is a technical limitation in it. Not getting any exception, the function is just dying when it hit the line keyvault.getsecretasync. 
Surprisingly this is working in a normal Azure function and sort of working in local debugging as well. Any thoughts?
`var tokenProvider = new AzureServiceTokenProvider();
            var keyvaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(tokenProvider.KeyVaultTokenCallback));
            
            var userId = await keyvaultClient.GetSecretAsync(ConfigurationManager.AppSettings.Get("UserIdVault")).ConfigureAwait(false);
            log.Info("got user id");`

Thanks
-Srikanth

**Comment by cgillum** [comment]
My guess is that you're using the key vault client in an orchestrator function? That's not allowed, because doing any I/O in an orchestrator function is forbidden. Instead, you should do that in an activity function. Otherwise you will run into problems just like this.

You can find more information on how orchestrator functions work and their limitations in this documentation:
https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-checkpointing-and-replay

**Comment by anskanth** [comment]
Thanks, Chris for the quick reply. Yes, I understand that I shouldn't be using that in Orchestrator and so I moved it to a Acitivity function as shown below. But I have to decorate my activity function as well with async as I've to call GetSecretAsync method. Is that a problem? This code still not executes.
` [FunctionName("longrunfunction")]
        public static async Task<string> longrunfunction([ActivityTrigger] int number, TraceWriter log)
        {
            log.Info("run started" + number);
            
            var tokenProvider = new AzureServiceTokenProvider();
            var keyvaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(tokenProvider.KeyVaultTokenCallback));
            
            var userId = await keyvaultClient.GetSecretAsync(ConfigurationManager.AppSettings.Get("UserIdVault")).ConfigureAwait(false);
            log.Info("got user id");
            return $"{userId.Value}";
        }`
I will be calling this method from my orchestrator as 
` [FunctionName("PtsOrchestrator")]
        public static async void RunOrchestrator(
          [OrchestrationTrigger] DurableOrchestrationContext context, TraceWriter log)
        {
            try
            {

                log.Info(ConfigurationManager.AppSettings.Get("UserIdVault"));
                
                await context.CallActivityAsync("longrunfunction", 10);`

Wondering, if there is any silly mistake I'm doing...

**Comment by anskanth** [comment]
Hi Chris, thanks for this. I found the silly mistake what I'm doing... :)
