### ISSUE TITLE
Consider disambiguating generic parameters T in new IDurableEntityContext interface

### ISSUE THREAD

**Issue by reisenberger** [Azure/azure-functions-durable-extension#757]
The new [`IDurableContext` implementation](https://github.com/Azure/azure-functions-durable-extension/blob/0145114fade719b9a712f63134711effbd933acf/src/WebJobs.Extensions.DurableTask/ContextInterfaces/IDurableEntityContext.cs) has multiple methods with method-generic parameter `T`.  

Those `T` can in fact be different types for the different methods on `IDurableEntityContext`, for the same entity function. Could labelling them all (both) `T` hinder discoverability for devs that they may be different?

Could rename to make clearer they may be different types:

    TState GetState<TState>(Func<TState> initializer = null);

    TInput GetInput<TInput>();

---

If the change was adopted, guess it might also want to flow to other overloads, eg `ReadEntityStateAsync<TState>`, `CallEntityAsync<TResult>`

---

The question was initially prompted for me by reading the [doco](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-preview#entity-functions), which happens to give an example:

    int currentValue = ctx.GetState<int>();
    int operand = ctx.GetInput<int>();

**Comment by sebastianburckhardt** [comment]
This seems like a reasonable suggestion to me. With all the different methods and overloads, it is not always immediately clear what the type argument is representing. Using more explicit names can help.

**Comment by cgillum** [comment]
FYI @amdeel, this might be a good first task for you. :)
