### ISSUE TITLE
[Question] How to make OrchestrationClient Start Orchestration once Deployed

### ISSUE THREAD

**Issue by jmotes** [Azure/azure-functions-durable-extension#758]
I have an orchestration client set up similarly to the sample in the link below (not doing the singleton check yet however), but do have the routing working.

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons#c

It works great locally - I can trigger it via a POST request to http://localhost:7071/api/orchestrators/StartMySequence

Once I've deployed it and my orchestration sequence functions to Azure, I try to trigger it with a POST request to https://[projectname].azurewebsites.net/api/orchestrators/StartMySequence?code={function_code}

I get an HTTP 500 and in the Monitor section for the Function in Azure I get "Not Implemented".

I assume the OrchestrationClient doesn't know how to communicate with the orchestration sequence (StartMySequence) function once deployed. What am I doing wrong?

Full code for the client:

```
public static class SyncTrigger
{
        
    [FunctionName("HttpStart")]
    public static async Task<HttpResponseMessage> RunSync(
        [HttpTrigger(AuthorizationLevel.Function, methods: "post", Route = "orchestrators/{functionName}")] HttpRequestMessage req,
        [OrchestrationClient] DurableOrchestrationClientBase starter,
        string functionName,
        ILogger log)
    {
        // Function input comes from the request content.
        dynamic data = await req.Content.ReadAsAsync<object>();

        string instanceId = await starter.StartNewAsync(functionName, new SyncRequest
        {
            ApiKey = data?.api_key,
            ApiPassword = data?.api_password,
            ApiUrl = data?.api_url,
            ClientName = data?.client_name,
            WebsiteUrl = data?.website_url
        });

        log.LogInformation($"Started orchestration with ID = '{instanceId}'.");
            
        return starter.CreateCheckStatusResponse(req, instanceId);
    }
}
```

Edit: more detailed error from the Azure Portal:

```
Error writing logs to table storage: Microsoft.WindowsAzure.Storage.StorageException: Not Implemented
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.WindowsAzure.Storage.Table.CloudTable.CreateIfNotExistsAsync(TableRequestOptions requestOptions, OperationContext operationContext, CancellationToken cancellationToken)
   at Microsoft.Azure.WebJobs.Logging.Utility.SafeCreateAsync(CloudTable table, Int32 intervalMilliseconds, Int32 totalMilliseconds) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\Utility.cs:line 96
   at Microsoft.Azure.WebJobs.Logging.Utility.SafeExecuteAsync(CloudTable table, TableBatchOperation batch) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\Utility.cs:line 191
   at Microsoft.Azure.WebJobs.Logging.Utility.WriteBatchAsync[T](ILogTableProvider logTableProvider, IEnumerable`1 e1) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\Utility.cs:line 269
   at Microsoft.Azure.WebJobs.Logging.LogWriter.FlushTimelineAggregateAsync(Boolean always) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\LogWriter.cs:line 265
   at Microsoft.Azure.WebJobs.Logging.LogWriter.FlushCoreAsync() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Logging\Internal\LogWriter.cs:line 316
Request Information
RequestID:3ad6a3a6-f002-00a0-44e1-0918b4000000
RequestDate:Mon, 13 May 2019 23:16:51 GMT
StatusMessage:Not Implemented
ErrorCode:
ErrorMessage:The requested operation is not implemented on the specified resource.
RequestId:3ad6a3a6-f002-00a0-44e1-0918b4000000
Time:2019-05-13T23:16:51.5593638Z
```
--

**Comment by cgillum** [comment]
That's very odd. The `NotImplementedException` is coming from Azure Storage. Your code isn't doing anything wrong.

What version of the Azure Functions runtime are you using? Also, are you pulling in any specific version of the Azure Storage SDK in your function project?

**Comment by jmotes** [comment]
@cgillum I'm using Azure Functions 1.24 since that's the latest version that compiles with an external .net 4.7 library that I'm utilizing. I'm not doing anything with Azure Storage directly.

**Comment by cgillum** [comment]
I did a quick search and this came up: https://stackoverflow.com/questions/40627029/azure-table-storage-501-notimplemented-on-createifnotexistsasync

Can you double check the type of storage account you're using? It sounds like this can happen if you're using something other than a general purpose storage account. For example, if you use a blob-only storage account, this error message is expected.

**Comment by jmotes** [comment]
@cgillum I looked through Azure and actually can't seem to find the storage account. I'm new to Durable Functions but assumed Azure will create the storage account for Activity return values, etc. itself. 

Do I need to create the storage account and define it in a settings file?

**Comment by jmotes** [comment]
@cgillum ok, looks like I am using blob only storage. I looked at the application settings for the Function App in Azure and it's using a blob storage account I created for another app. I've deleted the app and redeployed and it still uses it. Any idea why it's doing that?

**Comment by jmotes** [comment]
@cgillum that was it! It's working perfectly after re-creating the function app with a new storage account. Thanks so much for your help!

**Comment by cgillum** [comment]
Awesome - glad we got that figured out. :)
