### ISSUE TITLE
CallActivityWithRetryAsync, orchestration continue to run even all retries failed with exception

### ISSUE THREAD

**Issue by andrew-vdb** [Azure/azure-functions-durable-extension#760]
Durable function version 1.8

I believe in the past, when all retries failed, the orchestration will throw exception.

Actual:
CallActivityWithRetryAsync
All retries fails with exception,
Orchestration continue to run

Expected:
CallActivityWithRetryAsync
All retries fails with exception,
Orchestration should throw FunctionFailedException

**Comment by cgillum** [comment]
We have a test which verifies that `CallActivityWithRetryAsync` correctly raises an unhandled exception once all retries are exhausted. I'm curious to know how your orchestration differs from this test. Do you have a simple repro you can share?

**Comment by andrew-vdb** [comment]
I have try catch which causing the retry still continue... sorry
