### ISSUE TITLE
[Question] Correlate Orchestration instance ID with dependencies in AppInsights

### ISSUE THREAD

**Issue by chinarosesz** [Azure/azure-functions-durable-extension#761]
I followed this documentation on how to query for execution history given an instance ID and it works great https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics. 

I've started looking around to see if it's possible for me to correlate dependencies and traces related the same activity function. For example: I have an activity function that calls into multiple REST endpoints, can I query for dependencies, traces, and durable tasks execution logs using the same orchestration ID? Or is there another recommended way to do this?

**Comment by cgillum** [comment]
We don't have a good way to do this yet. This PR is tracking some work we're doing in the Durable Task Framework to enable this: https://github.com/Azure/durabletask/pull/261
