### ISSUE TITLE
Duplicated entity signals

### ISSUE THREAD

**Issue by sebastianburckhardt** [Azure/azure-functions-durable-extension#762]
I am observing some entity signals getting duplicated when simulating failures locally, by stopping, then restarting the functions runtime in the middle of a job.

This may be caused by the dequeueing logic, I will need to investigate.

**Comment by cgillum** [comment]
Messaging guarantees are at-least-once. Wouldn't this be expected if you restart the runtime in the middle of processing?

**Comment by sebastianburckhardt** [comment]
Some of the entity logic expects exactly-once (e.g. the locking). I think we want to shoot higher here and guarantee exactly-once and in-order delivery for all communication between entities, and between entities and orchestrations.
