### ISSUE TITLE
Function timing out with await 

### ISSUE THREAD

**Issue by kijujjav** [Azure/azure-functions-durable-extension#770]
I have a function which awaits on two tasks, If none of the task return within 30 min, my azure function is timing out and seeing the blow exception

Timeout value of 00:30:00 exceeded by function 'WaitForDcsInputWorkflow' (Id: '1c74f25c-13ac-4823-a4ac-35f7be6adc8a'). Initiating cancellation.

- Durable Functions extension version:1.8.1
- Function App version (1.0 or 2.0): 2.0
- Programming language used: .NET

***If deployed to Azure***

- Timeframe issue observed: 2019-05-22T21:21:20.776
- Function App name: NetAssistStatefulWorkflow
- Function name(s): WaitForDcsInputWorkflow
- Region: West Us
- Orchestration instance ID(s):c9e42d89168340b38d8bc601c84abe9c
Invocation Id: 7b60dcd4-afc2-46b1-958b-a3a8f46ef0c8

> If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [Functions Host wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

**To Reproduce**

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots**

**Known workarounds**
Provide a description of any known workarounds you used.

**Additional context**

- Development environment (ex. Visual Studio)
- Links to source
- Additional bindings used
- Function invocation IDs

**Comment by ConnorMcMahon** [comment]
@kijujjav, was there a reason you closed this issue? Is this still something you want us to investigate?

**Comment by kijujjav** [comment]
@ConnorMcMahon, there was a bug in my code

**Comment by ConnorMcMahon** [comment]
Thanks for clarifying!
