### ISSUE TITLE
Update WebJobs dependency to 2.3.0 for V1 Function apps

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#771]
**Microsoft.Azure.WebJobs.Extensions.DurableTask** for Functions v1 targets Microsoft.Azure.WebJobs v2.2.0. However, there is a newer version, [v2.3.0](https://www.nuget.org/packages/Microsoft.Azure.WebJobs/2.3.0), that has been out for a while and contains a variety of fixes.  We should update to this latest version.

Related issue: https://github.com/Azure/azure-functions-durable-extension/issues/691

**Comment by cgillum** [comment]
This fix was released as part of [v1.8.2](https://github.com/Azure/azure-functions-durable-extension/releases/tag/v1.8.2).

**Comment by ConnorMcMahon** [comment]
Reopening this issue with #811.

**Comment by juunas11** [comment]
Any ETA on this? We have 5k of the exceptions mentioned here https://github.com/Azure/azure-functions-durable-extension/issues/691 in the last 24 hours.

I cannot update the WebJobs library to 2.3.x since the Functions SDK depends on 2.2.x.
Or is the only solution to update to v2?

**Comment by ConnorMcMahon** [comment]
It looks like the underlying issue with upgrading to 2.3.x in "Microsoft.NET.Sdk.Functions" was fixed 1.0.30-beta1. However, there is not yet a non-prelease version of the package with the fix, so I don't necessarily feel comfortable upgrading it quite yet.

**Comment by ConnorMcMahon** [comment]
It looks like 1.0.30 has finally released (along with 1.0.31), so it may be possible for us to finally upgrade. I will mark it for v2.2.0 release.
