### ISSUE TITLE
[Durable V2] Resolve ILifeCycleNotificationHelper using Dependency Injection

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-durable-extension#775]
I would like to change LifeCycleNotificationHelper registering to Dependency Injection instead of defining it in host.json.

#### Example
```
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        builder.Services.AddSingleton<ILifeCycleNotificationHelper, CustomLifeCycleNotification>();
    }
}
```

I want to make changes in v2 because it is a breaking change.

**Comment by cgillum** [comment]
This sounds like a good idea to me!

**Comment by ConnorMcMahon** [comment]
This was actually already release as a part of 2.0.0-beta3.
