### ISSUE TITLE
While running azure durable function in azure portal, i am getting function failed for some reasons but the instances are stored in history table. Is there anyway to delete the instances when getting failed because i have 1000s of records to be deleted manually in case if it failed

### ISSUE THREAD

**Issue by iamsuresha** [Azure/azure-functions-durable-extension#778]
Kindly advise on this @cgillum

**Comment by olitomlinson** [comment]
You have two options.

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#purge-multiple-instance-history

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-instance-management#purge-instance-history

**Comment by avantadore** [comment]
See code below.... depending on state you can purge


            var instances = await starter.GetStatusAsync(); 
            foreach (var instance in instances)
            {
                log.LogInformation(JsonConvert.SerializeObject(instance));
                if (instance.Name.Equals("ReportSchedulerOrchestration"))
                {
                    switch (instance.RuntimeStatus)
                    {
                        case OrchestrationRuntimeStatus.Running:
                            break;
                        case OrchestrationRuntimeStatus.ContinuedAsNew:
                            break;
                        case OrchestrationRuntimeStatus.Terminated:
                        case OrchestrationRuntimeStatus.Completed:
                        case OrchestrationRuntimeStatus.Failed:
                        case OrchestrationRuntimeStatus.Canceled:
                        case OrchestrationRuntimeStatus.Pending:
                            await starter.PurgeInstanceHistoryAsync(instance.InstanceId);
                            break;
                        default:
                            throw new ArgumentOutOfRangeException();
                    }
                }
