### ISSUE TITLE
Durable functions should depend on storage 7.x when targetting webjobs 2.x

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-functions-durable-extension#78]
Found this via:
https://github.com/Azure/azure-webjobs-sdk/issues/1397

The problem is that the NET 461 version of durable functions depends on a higher version of storage than used by the webjobs sdk that durable functions also depends on. It should be 7.x but its 8.x:

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.DurableTask
```
.NETFramework 4.6.1
- DurableTask.AzureStorage (>= 1.0.0-beta)
- Microsoft.Azure.WebJobs (>= 2.1.0-beta4)
```
https://www.nuget.org/packages/DurableTask.AzureStorage/
```
.NETFramework 4.5.1
- DurableTask.Core (>= 2.0.0.3-preview)
- Newtonsoft.Json (>= 7.0.1)
- WindowsAzure.Storage (>= 8.3.0)
```

**Comment by cgillum** [comment]
This is fixed in the 1.1.0-beta2 release.
