### ISSUE TITLE
Non-deterministic operation question

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#788]
Question regarding the section on Non-deterministic operations in orchestrations. I have a try catch wrapped around all of my activity calls from my orchestration in the case of a failure after all retries are exhausted. I would like to make an async call to store some information in table storage. after I make this call i `throw` the original exception. 

My question is whether or not this is a violation of non-deterministic operations? 

Thanks,

**Comment by olitomlinson** [comment]
@mpaul31 Is this what you're describing?

```
try
{ 
    context.CallActivityWithRetries....
}
catch(ex)
{
   context.CallActivity... //store some stuff
   throw;
}
```

**Comment by mpaul31** [comment]
@olitomlinson here is what i was thinking. Just unsure if this needs to be done via an Activity.

```
try
{ 
    context.CallActivityWithRetries....
}
catch(ex)
{
   await tableStorageFaultProvider.Handle(ex);
   throw;
}
```

**Comment by olitomlinson** [comment]
In your example, once you throw the orchestration is going to go into a ‘failed’ state, get serialised, persisted to the TaskHubInstance storage queue, and likely never get woken up again, so I don’t see where the runtime has the opportunity to analyse for a non-deterministic workflow, but I don’t know the internals so I can’t offer advice.

Personally, I would write to the storage via an Activity. 

I’m hopeful that one day the Rewind API will become GA, in which case you will benefit from the safety of performing your side-effects in activities.

**Comment by mpaul31** [comment]
Thanks that was what I was also thinking, but not knowing the internals made me want to ask. I am leaning towards using the activity. @cgillum thoughts?

**Comment by cgillum** [comment]
I agree that putting your `tableStorageFaultProvider.Handle(ex)` in an activity function is going to be your best bet. My fear is that if you call storage directly from your orchestration, it could potentially cause the orchestration to go into either a "stuck" state or into a `Completed` state instead of a `Failed` state.

**Comment by mpaul31** [comment]
makes sense thanks!
