### ISSUE TITLE
Azure Event Grid - Add Context Data

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#791]
I really like the idea of subscribing to lifecycle events from event grid, however I was wondering if there is a way we can attach context/meta data to an orchestration instance so we can have access to it from the event payload? For instance, we let durable manage our instance ids, but when an orchestration fails, we would like to have access to some of the underlying correlation ids associated to the instance (we pass in the input args).

**Comment by cgillum** [comment]
The event will have the orchestration instance ID, and you can use this ID to query the state of the instance, either via a function which uses our client APIs or directly using the built-in [HTTP API](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-http-api#get-instance-status) (which can give you the input, custom status, etc.). Does this meet your needs, or do you require this information to actually be embedded in the event payload directly?

**Comment by mpaul31** [comment]
i think it would be nice to expose possibly a simple key-value pair for the envelope metadata, but using the APIs should work fine too.

Thanks for the feedback!
