### ISSUE TITLE
Durable Function Error

### ISSUE THREAD

**Issue by breddynet** [Azure/azure-functions-durable-extension#794]
My durable function is running without any issues in local Machine and when deployed into the Azure functions i get Error Object is null error. 

If i invoke the function 3-4 times then it will start working, by looking at the logs i am not able to identify the root cause of the issue 

Here is the code 

```csharp
[FunctionName("FnProcess_HttpStart")]
public static async Task<HttpResponseMessage> HttpStart(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get")]HttpRequestMessage req,
    [OrchestrationClient]DurableOrchestrationClient starter,
    ILogger log, ExecutionContext context)
{
    _config = new ConfigurationBuilder()
                .SetBasePath(context.FunctionAppDirectory)
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();

    
    // Function input comes from the request content.
    string instanceId = await starter.StartNewAsync("FnProcessInfo", "");

    log.LogInformation($"Started orchestration with ID = '{instanceId}'.");

    return starter.CreateCheckStatusResponse(req, instanceId);
}

[FunctionName("FnProcessInfo")]
public static async Task<List<string>> RunOrchestrator(
    [OrchestrationTrigger] DurableOrchestrationContext context, ILogger log)
{
    var activityTasks = new List<Task<string>>();
    var output = new List<string>();
    var retryOptions = new RetryOptions(firstRetryInterval: TimeSpan.FromSeconds(30), maxNumberOfAttempts: 3);

    try
    {
        List<UserInfo> providers = new List<UserInfo>();

        log.LogInformation("started");
        
        // Fill user Object by calling the SQL

      
        log.LogInformation("Processing");
        //Delete Previously processed Records
        // Call to DB

        //Call Kusto to save data into SQL
        // Call to DB

        // Adding 25 sec Wait for save to complete
        System.Threading.Thread.Sleep(2000);

        // Get Userid's to Exclude for processing
        Call DB

        var ids = new HashSet<string>(ignoreUser.Select(x => x.UserId));
        var UsersList = providers.Where(x => !ids.Contains(x.UserId));

        if (UsersList != null && UsersList.Any())
        {
            log.LogInformation($"Total Count {UsersList.Count()}");
            foreach (var user in UsersList)
            {
                Task<string> identifierTask = context.CallActivityWithRetryAsync<string>("FnActivityAsync", retryOptions, user);
                activityTasks.Add(identifierTask);
            }
        }
        await Task.WhenAll(activityTasks);

        log.LogInformation($"Completed orchestration ");
    }
    catch (Exception ex)
    {
        var logKusto = new ActivityLog
        {
            SessionId = "",
            UserName = "",
            ActivityParam1 = "Fail",
            ActivityParam2 = "Error",
            ActivityDetailsJson = $"{ex}",
            ActivityType = "Bulk"
        };
        LogAnalytics.LogInfo(logKusto);

      
        log.LogInformation($"Error {ex}");
    }

    return output;
}
```

**Comment by cgillum** [comment]
There's not enough information here for me to provide much help. At a minimum you will need to share a callstack or at least mention which function reports the error.

**Comment by breddynet** [comment]
The following function giving the error [FunctionName("FnProcessInfo")]
public static async Task<List<string>> RunOrchestrator(
    [OrchestrationTrigger] DurableOrchestrationContext context, ILogger log)

**Comment by breddynet** [comment]
Error
2019-06-06T16:36:21.544 [Information] Executing 'FnProcessInfo' (Reason='', Id=1a333bc5-731e-4bab-a948-7b2134976b3e)
2019-06-06T16:36:21.612 [Information] started
2019-06-06T16:36:21.698 [Error] Executed 'FnProcessInfo' (Failed, Id=1a333bc5-731e-4bab-a948-7b2134976b3e)
Orchestrator function 'FnProcessInfo' failed: Object reference not set to an instance of an object.

**Comment by breddynet** [comment]
var activityTasks = new List<Task<string>>();
            var output = new List<string>();
            try
            {
                List<UserInfo> providers = new List<UserInfo>();

                log.LogInformation("started");
                
                var retryOptions = new RetryOptions(firstRetryInterval: TimeSpan.FromSeconds(30), maxNumberOfAttempts: 3);

                var commandText = "StoredProcedure"; // Line 41

ERROR in DB :

System.NullReferenceException: Object reference not set to an instance of an object.
   at FnProcessUpdate.FnIdentifiers.RunOrchestrator(DurableOrchestrationContext context, ILogger log) in C:\Users\XXX\source\repos\ApiTeam\XXX.ProcessSyncSync\XXX.Function.ProcessSync\ FnProcessInfo.cs:line 41

**Comment by cgillum** [comment]
Well, it's clear that the `NullReferenceException` is happening in your code, and it's clearly not the line that you mentioned in your snippet. At this point, I suggest you more carefully debug your code, and perhaps take advantage of remote debugging to help narrow down where the actual problem is coming from (more info [here](https://github.com/Azure/Azure-Functions/issues/872)).

If it happens in Azure but not locally, then most likely there is some configuration difference between your two environments that is causing the issue (e.g. different App Settings, etc.). If it starts working after 2-3 tries, then something more interesting is probably happening, like some invalid coding practices (static variables, non-deterministic API calls, etc.). Make sure to read through our [code constraints](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-checkpointing-and-replay#orchestrator-code-constraints) documentation to ensure you're following all the requirements.

**Comment by breddynet** [comment]
The issue is with reading application settings i have declared as static variable and that is causing the issue 

in my Orchestrator function 
public static async Task<HttpResponseMessage> HttpStart(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get")]HttpRequestMessage req,
    [OrchestrationClient]DurableOrchestrationClient starter,
    ILogger log, ExecutionContext context)
i am loading 
_applicationSettings = new ApplicationSettings
            {
                SqlConnection = _config.GetConnectionString("SqlConnection"),

What is the best way to do this ?

**Comment by breddynet** [comment]
I have fixed it by sending as input to the orchestrator and reading as input.

Let me know if there is any other way to do this
