### ISSUE TITLE
HTTP Async: Help witth Sample

### ISSUE THREAD

**Issue by ukluk** [Azure/azure-functions-durable-extension#8]
The samples are great, but documentation is missing in order to connect the moving parts.
I  created 2 functions
fn1 is just the **HttpStart** with no modifications, but the authLevel = "function"
fn2 is the worker (based on **E1_SayHello**), but I am parsing a json object

And this is the POST from fiddler
POST https://{host}.azurewebsites.net/api/orchestrators/**E1_SayHello**?code=xxxxxxxxxxxxxxxxxxxxxxx== HTTP/1.1
User-Agent: Fiddler
Content-Type: application/json; charset=utf-8
Content-Length: 409

{"TaskId":"Debug06_FE_Manager","Tenant":1,"ActivityType":1,"ProfileCode":null,"Gateway":"*","Geotag":null,"StartedUtc":"2017-07-05T21:15:07.3250104Z","Input":"Yellow","Activity":"Unit Test: Device Activity Change to Yellow","Ticket":"b9450d29-b765-4a7e-8559-ddac3f74dd64","AggTicket":null,"UserCode":null,"Active":0,"Total":0,"PosX":0.0057151555110305343,"PosY":0.31893127985248865,"PosZ":0.12992700381666747}

When I run the HttpStart I get the following trace:
    Started orchestration with ID = 'f7c11a73b8f44ce6942b6e59a77d45c4'.

And a 202 (Created) response with body
{"id":"'f7c11a73b8f44ce6942b6e59a77d45c4'",
"statusQueryGetUri":"https://{host}.azurewebsites.net/admin/extensions/DurableTaskConfiguration/instances/'f7c11a73b8f44ce6942b6e59a77d45c4'?taskHub=DurableFunctionsHub&connection=Storage

but the statusQueryGetUri returns 404 (NotFound)

I tried to monitor with traces when fn2 gets called, but I never see the invocation

Modified E1_SayHello looks like this:

    public static async Task<string> Run(
    	DurableOrchestrationContext context,
    	TraceWriter log)
    {
    	log.Info($"Started fn2.");
    
    	// Get request body from the Json string
    	var activity = context.GetInput<TaskActivity>();`
    	
    	//work here
    	await Task.Delay(10000);
    	return "OK";
    }

**Comment by cgillum** [comment]
Are you using the version of **HttpStart** that's provided in the samples, or did you write your own version?  It's very strange to me that you have quotes around your instance IDs - the sample code doesn't do this. Can you share the HTTP trigger you're using to start new instances?  Better yet, can you share the entire function app code?

Agreed that documentation around the HTTP APIs is missing. I've opened a separate issue to track that: https://github.com/Azure/azure-functions-durable-extension/issues/9

**Comment by cgillum** [comment]
Closing since this has been figured out.
