### ISSUE TITLE
A non-empty HubName configuration is required for Durable Functions 2.0

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-functions-durable-extension#800]
**Describe the bug**

When I deploy an Durable Functions App to Function App, it said that hubName is required. 

```
The function runtime is unable to start. Microsoft.Azure.WebJobs.Extensions.DurableTask: A non-empty HubName configuration is required.
```

**Investigative information**

- Durable Functions extension version: 2.0.0-alpha
- Function App version (1.0 or 2.0): 2.0.12507.0
- Programming language used: C#

***If deployed to Azure***

- Timeframe issue observed: between 2019-06-10 21:26:36.654 and 2019-06-10 21:12:13.742

- Function App name: prbot
- Function name(s): CIHook
- Region: westus2
- Orchestration instance ID(s): Not started yet. 

> If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [Functions Host wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

It happens when we deploy the function. We can't execute it. 

**To Reproduce**

1. Clone this repo https://github.com/TsuyoshiUshio/PullRequestBot/commit/3212719b917345f7076114b9e69c92b1d09c5d74
2. remove below from the host.json

```
,
  "extensions": {
    "durableTask": {
      "hubName": "MyTaskHub" 
    }
```

3. deploy to a function app. 

> While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

N/A

**Expected behavior**

Successfully deployed with Default TaskHub name

**Actual behavior**
A clear and concise description of what actually happened.

```
A non-empty hubName configuration is required
```

**Known workarounds**

Add the hubName configuration to host.json.

**Additional context**

- Development environment (ex. Visual Studio) Visual Studio 2019
- Links to source https://github.com/TsuyoshiUshio/PullRequestBot/commit/3212719b917345f7076114b9e69c92b1d09c5d74
- Additional bindings used HttpTrigger
- Function invocation IDs N/A

**Comment by cgillum** [comment]
This is by-design. There were two main reasons we did this:

1. We get a lot of CRIs from customers who deploy multiple function apps to Azure with the same Azure Storage account and a default task hub name. This causes bad runtime behaviors and users don't understand why until we point it out to them.
2. Having a unique task hub specified makes it much easier for us to look up trace information in Azure.

We considered using the name of the site and/or the slot name as the default, but this did not seem to work reliably with the behavior of slots, so we decided to just require users to specify a non-empty task hub name.

/cc @ConnorMcMahon
