### ISSUE TITLE
PurgeInstanceHistoryAsync Performance

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#802]
I have noticed looking at my AI logs the `PurgeInstanceHistoryAsync` is not the most performant and rightfully so. I am purging history once per day using a timer trigger for anything older than 24 hours and we hit the default 30 minute function timeout, which causes an immediate restart and numerous availability alerts until the function succeeds. 

So now I am looking to potentially run it throughout the day during normal business hours, but I want to make sure the additional overhead is not too high.

One question I have is I have a parent orchestration that calls a sub-orchestration that returns a result to the parent. If the sub orchestration is completed and gets purged before his parent completes, will this cause any ill effects?

**Comment by cgillum** [comment]
If the sub-orchestration gets purged before the parent instance is complete, I don't expect any issue. This is because the result of the sub-orchestration is saved in the history of the parent orchestration, so it shouldn't need to look up anything related to the sub-orchestration during replay.

**Comment by mpaul31** [comment]
perfect thanks for the confirmation!
