### ISSUE TITLE
Question: Any way to implement Singleton Orchestrator for Sub-Orchestrations?

### ISSUE THREAD

**Issue by oatsoda** [Azure/azure-functions-durable-extension#803]
I notice that [Orchestrators can be made Singleton](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-singletons) by checking the `instanceId` using `starter.GetStatusAsync`

There doesn't appear to be the same ability with [Sub-Orchestrations](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-sub-orchestrations)?

I am creating a set of durable functions to run **upgrades** on a set of X databases.  Periodically it will check that each are up to date and if not, upgrades them.  But this is not thread safe so I need to ensure that an upgrade only takes place once.

If I use a single, Singleton Orchestrator then I can start Activities for each database to upgrade them but I am unsure whether the Durability of the functions could potentially cause an Activity for a specific database to end up with more than one instance running at the same time.

Hence I was thinking to create a Sub Orchestrator for each Database and make it Singleton (and **that** Sub Orchestrator call the Activity.  But unless I am missing something there doesn't appear to be a way of making the Sub Orchestrator a Singleton?

**Comment by mpaul31** [comment]
If you use a singleton parent orchestration, you can enforce the sub-orchestration to be a singleton by ensuring you only _call_ it once. However, the _real_ issue you need to be concerned with is with most distributed messaging systems, such as durable, you are guaranteed _at-least-once_ message delivery, so your activities will always have the potential to be called more than once.

OR you could use the the new "Entities" feature from the Durable 2.0 Preview, which sounds to be a great fit for your use case.

**Comment by oatsoda** [comment]
OK, but I am looking at using a Fan Out pattern - to kick off all the activities in parallel.  I have ensured the Orchestrator is a Singleton.

I don't have an issue with the activities being executed more than once, but I cannot allow multiple to be executed **at the same time** as the activities are not thread safe..

From what I see during "normal" operation this shouldn't be a problem but I am not sure of the consequences of other failures that could occur and cause the Orchestrator to run again.

That is why I was wondering if I could Fan Out with Sub-Orchestrators as if they were named I could check them.

**Comment by olitomlinson** [comment]
If you fan out, then its highly likely that some of your activities are going to be called concurrently, which is not what you desire.

**If you can fit an individual database upgrade into a single Activity Function**, then could use the `context.ContinueAsNew()` to create a loop, and then call the activity for each database and await the result of each Activity. This way you are are processing the upgrades sequentially within the orchestration. Something like this...

```
//starter code

var databasesToCheckAndUpgrade = new [] {"Db1","Db2",Db3"}.ToQueue();

var singletonResult = client.GetStatusAsync("TheOnlyInstanceId");

if (singletonResult == null)
{
   client.StartNewAsync("Database_Upgrade_Orchestration", "TheOnlyInstanceId", databasesToCheckAndUpgrade);
}
else 
{
   if(singletonResult.RuntimeStatus != "Pending" && singletonResult.RuntimeStatus != "Running" &&  singletonResult.RuntimeStatus != "ContinueAsNew"  )
   {
      client.StartNewAsync("Database_Upgrade_Orchestration", "TheOnlyInstanceId", databasesToCheckAndUpgrade);
   }
   else
   {
      //Orchestration is currently in flight - defer this request to check your databases
   }
}
````


```
//orchestration code

[FunctionName("Database_Upgrade_Orchestration")]
public static async Task Run([OrchestrationTrigger] DurableOrchestrationContext context)
{
    var databasesToUpgrade = context.GetInput<queue<string>>();

    var database = databasesToUpgrade.Dequeue();

    var result = await context.CallActivityAsync("DoCheckAndUpgrade", database );
     //handle upgrade failures etc

    if (databasesToUpgrade.Any())
          context.ContinueAsNew(databasesToUpgrade);

    //Orchestration will exit and complete if no databases left to complete
}
```

**Comment by olitomlinson** [comment]
In fact, I'm pretty sure you can `await` on a call to a sub-orchestrator, I've just never tried it.

Replace the above call 

`var result = await context.CallActivityAsync("DoCheckAndUpgrade", database );`

with

`var result = await context.CallSubOrchestratorAsync<string>("Upgrade_Database_Activity", database);`

**Comment by oatsoda** [comment]
Thanks @olitomlinson. 

Even in your example though, can it guarantee that the Activity is only ever executed once at the same time?  I mean with the same value for `database`.  In normal operation you would expect that, but are there cases when recovering from platform failures that could trigger the Activity for the same database at the same time.

_I probably haven't been very clear on what I am doing..._

Regarding Fan Out - my issue isn't the Activity itself running in parallel, it is the same Activity for the same Database running in parallel.

Currently I have:

- Timer Function (Starter Code)
   > Singleton pattern to ensure Orchestrator only executed once at a time
   - Orchestrator Function
      > Calls Activity to get list of Databases requiring upgrade
      > Fan Out each Database by calling Activity for each and using `Task.WhenAll`

I think this should work fine, but I am looking for some guarantees that the Database Activity for the same Database can never run in parallel.

When running locally using VS and Functions CLI I have seen some odd things when stopping and starting debugging.  Also, as @mpaul31 states above there is an "at least once" pattern in use so it is possible that it could run more than once - like I say, not a problem unless it does this in parallel.

Hence I was wondering if somehow I could "name" the Database Activity and check it is already running - much like the Orchestrator Singleton pattern - and therefore my original question.

**Comment by olitomlinson** [comment]
Ah I see what you're saying! 

This sounds like your asking for the theoretical possibility, which I'm not equipped to answer with certainty. 

But from what I'm aware of, the activity will be invoked by the consumption of a single Azure Storage Queue Message by the Durable Function Extension.

This message will be _leased_ by the Function while it runs the Activity.

While the message is being actively leased, no other Function instance will be able to consume this message. 

However, if the Function running the activity code exits ungracefully, or fails to complete within the function timeout window (which varies depending on your configuration and environment) then yes, the Message will _eventually_ loose its time-based lease, and become available to be consumed again, and then your activity code will be re-ran. 

From my understanding, while the message is actively leased for its lease-duration, you're safe, but I'm definitely not an authority on this.

----

Apologies in advance, you didn't ask for my opinion on this but ill share anyway... the thought of running multiple database upgrades concurrently is a generally a scary prospect to me. 

Unless you're 100% confident in your upgrade approach, or you have no other choice but to upgrade at the same time, I would favour a more cautious pattern of upgrading each database sequentially with a _cool down_ window between each upgrade to give you time to monitor and react to health issues and degradation.

**Comment by oatsoda** [comment]
@olitomlinson And that is my worry.  I guess I could [adjust the settings in the host.json](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-bindings#host-json) such as `controlQueueVisibilityTimeout` and `workItemQueueVisibilityTimeout`...but unless I can be 100% then I think I am struggling to make this watertight. 

Unless I decide on an alternative to Durable Functions then I could write my own "lease" using a Blob Storage or Table Storage entity.

---------------------------------------------------

No apology needed - I am well aware of this.  I am actually porting this from another product which uses a bog standard Windows service for this.   It upgrades hundreds of DBs in parallel and has been working fine for 4 years!  But it does have some protection - mainly that a single DB has to be upgraded successfully before it starts all the others.  This mitigates against a "bad migration".  But it has never really happened as all migrations are fully tested before being deployed.

In my Durable Function scenario, before the Fan Out I pick a middle-sized DB and upgrade it individually by calling the Activity from the Orchestrator.  Only once that single one has completed does the Fan Out occur.

**Comment by olitomlinson** [comment]
Yeah locking on a blob is a very common way of getting exclusivity on a resource, and you could certainly do that in your Activity to be double-sure! You could even have a follow-up activity that removes the locks, ready for the next run.

----

Thats fair! :)

**Comment by ElanHasson** [comment]
Follow-up Question on this -- When you start an orchestration while specifying an `instanceId`, if an orchestration with that same `instanceId` is already running, is the start queued up for execution when it finishes? I thought I remembered seeing somewhere the StartOrchestration request will be silently discarded, but can't seem to find it again.
