### ISSUE TITLE
Troubleshooting why one VM is always doing more work then the others

### ISSUE THREAD

**Issue by mpaul31** [Azure/azure-functions-durable-extension#804]
I'm trying to figure out why one of our VMs is constantly doing more work than the others. The only place I am creating my own orchestration instance id is for one of my sub-orchestrations. All I am doing is taking the parent orchestrations instance id and appending on a string I use to correlate the two.

```
var response = await context.CallSubOrchestratorAsync<IEnumerable<JObject>>(
    SubOrchestration.Function, $"[{siteId}]-[{inventoryId}]-[{context.InstanceId}]", args);
```

Also, our scaling rules allow from 2-5 VM's based on CPU usage, so I have my `partitionCount` set to 5.

![Capture](https://user-images.githubusercontent.com/206767/59461108-9dc24c00-8dee-11e9-9ac9-0ad928500253.PNG)

Any suggestions on how and where I should dig into? 

Thanks!

**Comment by cgillum** [comment]
My first suggestion is to look at the distribution of orchestration execution across your VMs. Are orchestrations evenly distributed across all VMs, or do they skew towards just one VM (i.e. a "hot" partition)?

Orchestrations are load balanced across partitions using a hashing algorithm on the instance ID. If the IDs are randomly generated (the default), then they should get distributed evenly across all partitions (5 in your case). For the cases where you're generating your own instance ID, then there is a chance that the distribution could get skewed. Based on what you're describing, it's hard to tell whether that might be the case for you.

It's possible that _orchestrations_ are evenly distributed, but that _activity_ functions are not. If you can get the next level of detail, then it will be easier to diagnose what's going on.

**Comment by mpaul31** [comment]
Gotcha makes sense. What would be the best way to go about getting this metrics? Would it be running a log analytics query and aggregate based on machine name or is there a better way to go about this?

**Comment by cgillum** [comment]
Are you using [Application Insights](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-diagnostics#application-insights)? If so, you can query and aggregate on both machine name (I think they call it cloud_RoleInstance or something like that) and function type.

**Comment by mpaul31** [comment]
Yes I am thanks!

**Comment by mpaul31** [comment]
Assuming my queries are coorect, looks like both are not even:

Orchestrations
![image](https://user-images.githubusercontent.com/206767/59465266-80927b00-8df8-11e9-9b87-607b40c398ff.png)

Activities
![image](https://user-images.githubusercontent.com/206767/59465817-c1d75a80-8df9-11e9-98a5-0c9fcd4290ad.png)

What would you suggest I look into next? I can easily swap out the custom instance id and see if that helps but not sure about the activities.

**Comment by cgillum** [comment]
I would try swapping out the custom instance ID. My expectation is that if the orchestrations are balanced, then the activity functions will be balanced too (I can explain this in more detail once we get to that point).

**Comment by mpaul31** [comment]
OK sounds good. I can't cut a new release to prod for a few days so I'll keep you posted.

**Comment by mpaul31** [comment]
after removing the custom instance IDs I am still seeing unbalanced CPU usage between VMs.

Suggestions for next steps I can look at?

![image](https://user-images.githubusercontent.com/206767/60105686-ca9d2a00-9731-11e9-8af8-12ee5f533287.png)

**Comment by cgillum** [comment]
Two other thoughts come to mind:

1. How are you triggering your parent orchestrations?
2. For the sub-orchestrations, are you using auto-generated instance IDs or creating your own random instances IDs (e.g. `context.NewGuid()`)?

I believe the auto-generated sub-orchestration IDs might actually not be evenly distributed. Creating your own randomly generated IDs might be a good thing to try.

**Comment by mpaul31** [comment]
Hi Chris,

1. We are using a Cosmos Change Feed Trigger binding to start our parent orchestrations.
2. We are using the auto-generated sub-orchestration IDs. 

In regards to #2, are you able to verify the auto-generated sub-orchestration IDs are not evenly distributed?

Thanks!

**Comment by cgillum** [comment]
The auto-generated sub-orchestration IDs are generated in the for of `XXX:1`, `XXX:2`, `XXX:3`, etc, where `XXX` is always the same, and it's not clear to me whether that would provide an even distribution. That's why I was wondering if you could try generating your own sub-orchestration IDs using `context.NewGuid()`.

**Comment by mpaul31** [comment]
OK gotcha. I'll let you know my findings!

**Comment by mpaul31** [comment]
well finally got a release out with using the `context.NewGuid()` for the sub-orchestration and now I am seeing even stranger numbers. the parent orchestration distribution is way off. and just to re-iterate, I call `StartNewAsync` and let the runtime create the instance id.

Do I need to use `context.NewGuid()` for the parent orchestration as well?

![image](https://user-images.githubusercontent.com/206767/60981701-cf9ed380-a304-11e9-8f6a-10154b1338cc.png)

**Comment by mpaul31** [comment]
@cgillum any ideas on next steps?
