### ISSUE TITLE
Passing polymorphic object models using durable orchestration context

### ISSUE THREAD

**Issue by raveeshupahuja** [Azure/azure-functions-durable-extension#805]
**Bug Description **

Trying to pass polymorphic objects throws exception in de-serialization.  For instance code below will fail.
``` csharp
await context.CallSubOrchestratorAsync<IMyInterface<T1>>(nameof(MyFunction), (polymorphicObjectArg));
```
**Investigative information**
Seems like azure functions are not using TypeNameHandling setting in the json serialization to handle polymorphism.
See code [here](https://github.com/Azure/azure-functions-durable-extension/blob/f4b8f4575f792fb1049b14e0da910f0512d1cd85/src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs#L21)

**Expected behavior**
Serialize/deserialize polymorphic models as arguments and return types.

**Suggested Fix**
Use TypeNameHandling.Auto [here](https://github.com/Azure/azure-functions-durable-extension/blob/f4b8f4575f792fb1049b14e0da910f0512d1cd85/src/WebJobs.Extensions.DurableTask/MessagePayloadDataConverter.cs#L21)

**Comment by cgillum** [comment]
This is somewhat related to https://github.com/Azure/azure-functions-durable-extension/issues/65.

FYI @SimonLuckenuik I believe you had some thoughts on this at one point.

**Comment by SimonLuckenuik** [comment]
I am not a big fan of TypeNameHandling, it couples your code naming, organization and compilation output to your data contract. Let's say you do refactoring and change the namespace, you broke your data contract and won't be able to deserialize. I personally prefer using a discriminator inside the JSON payload and use so kind of converter to handle the polymorphism if required.

**Comment by raveeshupahuja** [comment]
In the context of passing arguments between azure function I believe code naming, organisation and compilation output will not change, right?

**Comment by raveeshupahuja** [comment]
Also to be able to use discriminator based JSON payload, I believe the user of the Azure function has to do extra work by adding custom converters to JSON serializer settings for each polymorphic model. IMO all extra work should be required only when you need to be able to change namespace, code naming etc.

**Comment by SimonLuckenuik** [comment]
Keep in mind that the input\output data is persisted and used during playback and that your orchestrator can have a very long lifetime. 

So let's say you release a first version of your code with the class name "Potata" and you figure out and you should have written "Potato" and change it in the next release, the deserialization of the data won't be working and you won't figure it out until your orchestrator replays.

**Comment by SimonLuckenuik** [comment]
If https://github.com/Azure/azure-functions-durable-extension/issues/65 is implemented, you will be able to use TypeNameHandling.Auto if you want, but I would not like that to become the default behavior.

**Comment by raveeshupahuja** [comment]
But currently you can't use polymorphic models anyways. So if you use TypeNameHandling.Auto then current functionality is not impacted but it will enable polymorphism with restriction of not being able to change polymorphic model. Which is better than none.

**Comment by raveeshupahuja** [comment]
Being said that I think #65 is a good feature to have anyways since that will enable each user to choose based on their own preferences.

**Comment by mpaul31** [comment]
I ran into the same thing with one of my activites that returns `IEnumerable<SomeBase>`. I ended up changing the return value to `IEnumerable<JObject>` and using a custom `JsonConverter`.

**Comment by underscoreHao** [comment]
There's an issue on StackOverflow for this issue and I provided an answer similar to what @mpaul31 has done. Although I didn't want to deal JObjects everywhere in my durable context calls the JSON converter seems to be doing the job - https://stackoverflow.com/questions/58752301/context-getinputmodel-returns-base-class-instead-of-specified-derived-class-in/59090235#59090235

**Comment by ConnorMcMahon** [comment]
I would attempt to inject an `IMessageSerializerSettingsFactory` with custom JsonConverters to light up this scenario. We are working on official documentation for this. (#1208)

**Comment by ConnorMcMahon** [comment]
We now have documentation regarding custom serialization.
