### ISSUE TITLE
Activity function processed twice on different VMs

### ISSUE THREAD

**Issue by spzSource** [Azure/azure-functions-durable-extension#807]
Recently I've noticed interesting behavior in  processing on scaled out app service. As title says, activity function was started for execution twice on different instances (VMs). Here is an audit entries from app insight:

![image](https://user-images.githubusercontent.com/2921990/59569543-bbfca600-9093-11e9-8a30-7938c6b14b31.png)
![image](https://user-images.githubusercontent.com/2921990/59569559-febe7e00-9093-11e9-8ad5-8b43a13554e5.png)
![image](https://user-images.githubusercontent.com/2921990/59569561-09791300-9094-11e9-95ec-2389b670827d.png)

Information from durable hub history:
![image](https://user-images.githubusercontent.com/2921990/59569586-65dc3280-9094-11e9-9dd2-cd6649497b32.png)

There were **no** any host shutdowns appeared during processing. Means that this one is not connected to similar issue, as stated [here](https://github.com/Azure/azure-functions-durable-extension/issues/386). And seems that the issue appears only on auto-scaled configuration for App Service. On pre-scaled configuration I didn't notice such issues.

I know that the function must be idempotent, since we have only "at least once" guarantee for message processing ([doc](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale)), but just would like to know the root cause of such behavior.

**Investigative information**

- Durable Functions extension version: **1.8.0**
- Function App version: **2.0**
- Programming language used: **C#**

- Timeframe issue observed (UTC): **2019-06-14T12:55:13  - 2019-06-14T13:02:33.624**
- Function App name: **faneurtstqas13fo7d32tlve**
- Function name(s): **ReadFromDataLake**
- Region: **NorthEurope**
- Sub-Orchestration instance ID(s): **e38a1454b2ba4a278669dd4d4c825523:1**

**Comment by cgillum** [comment]
Actually, from what I can see, a host shutdown is exactly what caused this. Here is the timeline:

* At **2019-06-14 12:49:33** a scale-in request was received to remove two of your instances
* At **2019-06-14 12:55:14** this particular function execution started on one of the instances that were scheduled for shutdown
* At **2019-06-14 12:56:59** the functions host finally shut down
* At **2019-06-14 13:01:49** the message for the previous function reappeared on the queue and execution started again on a new instance.

So the behavior here is more-or-less expected based on what was discussed in #386.
