### ISSUE TITLE
WaitForExternalEvent with timeout generates an uncancellable timer

### ISSUE THREAD

**Issue by AtOMiCNebula** [Azure/azure-functions-durable-extension#816]
I've been using `WaitForExternalEvent` with a timeout in an orchestrator function of mine, and am just getting around to debugging why the orchestration hangs until the event is raised (or the timeout is reached, *even* if I took a route through the orchestration that didn't necessitate it finishing.  The documentation for the non-timeout version of `WaitForExternalEvent` suggests (correctly) that you don't need to cancel those (also #553)...but the timeout overload uses `CreateTimer` inside and while it does the right thing to ensure the token is cancelled if the event is received before the timeout itself is reached...I must now wait for the event to be received, or the timeout to fire.

I think I have a few options.  I could roll the timeout code myself so that I can have access to the `CancellationTokenSource`, but that feels like a cop-out.  I could also detect the scenario and have my orchestration send itself the event, but that also feels like a cop-out.  The option I'm leaning towards is to contribute back a fix for this though, since then everyone can be happy and not have to try to dance around the library. :smile:

What is the right solution here?  Add another set of overloads that allows passing in a `CancellationTokenSource` instance for every overload that takes a `TimeSpan`?  I suspect there's some subtleties to think through, such as who's responsible for disposing it.  If the token source is passed in, then it's probably not the library's job to dispose it anymore maybe?

Assuming this is an API that the extension is willing to take on, I'm happy to think through it and put up a PR for the issue, I just want to make sure you agree it's the right direction.  Thanks!

**Comment by cgillum** [comment]
Hi @AtOMiCNebula.  I'm not sure I fully understood the issue. Would you be able to demonstrate the problem you're running into using a code sample? I'm wondering if there might be a more straightforward solution.

**Comment by AtOMiCNebula** [comment]
I probably should have included example code in my initial report, sorry about that @cgillum!  The following orchestration (trivially adapted from the Visual Studio template) takes two minutes to transition from `Running` to `Completed`.  If the call to `WaitForExternalEvent` is updated to remove the `TimeSpan`, it completes in seconds.

```csharp
[FunctionName("DurableFunction")]
public static async Task RunOrchestrator(
    [OrchestrationTrigger] DurableOrchestrationContext context)
{
    await Task.WhenAny(
        context.WaitForExternalEvent("event", TimeSpan.FromMinutes(2)),
        context.CallActivityAsync("DurableFunction_Hello", "Tokyo"));
}
```

All `CreateTimer` overloads require passing in a `CancellationToken`, and I'm suggesting with this that the `TimeSpan`-accepting overloads for `WaitForExternalEvent` should also take `CancellationToken`s.

**Comment by AtOMiCNebula** [comment]
@cgillum Ping!  Please let me know if any clarifications are still needed.  I have also added a test case to the PR, hopefully that can help too. :)

**Comment by cgillum** [comment]
Thanks for the code sample - that makes the issue super-clear to me. I think the reason you're seeing the delay is because an orchestration requires all outstanding tasks to be completed before it can complete (this is a behavior of the Durable Task Framework).

I also now agree that we need to expose a `CancellationToken` parameter to `WaitForExternalEvent` in order for your scenario to work correctly. I'll follow up on the PR you submitted earlier.

**Comment by AtOMiCNebula** [comment]
@ConnorMcMahon / @cgillum Sadly, it looks like this change was completely blown away shortly after getting merged into dev, and none of it ended up getting included in the v2 release. ☹️

As best as I can tell, it looks like the fault lies with 780749d3a3fbbc648b04e71e2d17afc1efe789d4; there were tons of merge conflicts, but no work appears to have been done to actually resolve most of them, instead just ignoring them. :(

Trying to replay that merge locally yields the following:
```
You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:

        modified:   .github/ISSUE_TEMPLATE/bug_report.md
        new file:   .github/ISSUE_TEMPLATE/feature_request.md
        new file:   .github/ISSUE_TEMPLATE/new-release-template.md
        modified:   samples/v1/javascript/package-lock.json
        modified:   samples/v1/javascript/package.json

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

        both modified:   samples/v1/precompiled/VSSample.csproj
        deleted by us:   src/WebJobs.Extensions.DurableTask/DurableOrchestrationContext.cs
        deleted by us:   src/WebJobs.Extensions.DurableTask/DurableOrchestrationContextBase.cs
        both modified:   src/WebJobs.Extensions.DurableTask/DurableTaskExtension.cs
        deleted by us:   src/WebJobs.Extensions.DurableTask/DurableTaskOptions.cs
        both modified:   src/WebJobs.Extensions.DurableTask/Listener/TaskOrchestrationShim.cs
        both modified:   src/WebJobs.Extensions.DurableTask/Microsoft.Azure.WebJobs.Extensions.DurableTask.xml
        both modified:   src/WebJobs.Extensions.DurableTask/WebJobs.Extensions.DurableTask.csproj
        both modified:   test/Common/DurableTaskEndToEndTests.cs
        both modified:   test/Common/TestHelpers.cs
        both modified:   test/Common/TestOrchestrations.cs
        both modified:   test/FunctionsV1/WebJobs.Extensions.DurableTask.Tests.V1.csproj
```

What's the right plan of action here?  Apologies for not noticing this sooner, I thought you were going to attempt a v1.8.4 release prior to shipping v2.0. ☹️
