### ISSUE TITLE
How is function time calculated?

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-functions-durable-extension#818]
In a normal Azure Function app, function times are calculated simply as EndTime - StartTime, regardless of any internal async logic. So if one Function app calls an API, the API time counts against the Function.

I'm curious how this translates into Durable Functions. If I call the same API as mentioned above, I'm guessing I would end up with about the same total function time.

Now let's say I call `WaitForExternalEvent`. The function time must stop because we won't run into `functionTimeout` issues, right?

When the external event finally returns, is the function time essentially reset?

So let's say I'm in a Function A for 3 minutes, which then calls `WaitForExternalEvent`. When the event finally triggers Function A to restart, does Function have a new 5 minutes to run or is there only 2 minutes left (assuming `functionTimeout` is set to 5 minutes)?

Can I safely assume that whatever the answer is for the above, also applies to `CallActivityAsync`?

**Comment by olitomlinson** [comment]
When execution reaches a point in your code like `await context.CallActivity... | await context.WaitForExternal...` the function essentially saves its state and terminates, so your orchestration function is not accruing compute charges while awaiting.

However, if your Activity then spins up and for example takes 30 seconds to complete, you will be charged for compute for 30 seconds as usual. During this time period, to reiterate, your orchestration is not accruing charges.

**Comment by MisinformedDNA** [comment]
@olitomlinson Thank you, that's very helpful.
