### ISSUE TITLE
Orchestration and SubOrchestration Functions starting on the same VM's

### ISSUE THREAD

**Issue by kashish52** [Azure/azure-functions-durable-extension#825]
I have a Durable Function App which has has sub orchestrators in it. the sub orchestrations are called in parallel. The host.json file of the function is below:
  {
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 30,
      "partitionCount": 5,
      "maxConcurrentActivityFunctions": 10,
      "maxConcurrentOrchestratorFunctions": 1
    }
  },
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": false
      }
    }
  }

I have set the the maxmaxConcurrentOrchestratorFunctions to 1 but when i try to start two different instances of the orchestrator function both of them start on the same vm. Even Sub orchestrations also start on the same vm. Is this the expected behaviour or is there any any workaround for this issue.

Info:
Orhcestration functions are http triggered
I am using the consumption plan.

**Comment by ConnorMcMahon** [comment]
In general, orchestrations should be approximately evenly assigned across partitions via our hashing algorithm ([FVN-1](https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function)). Assuming you aren't assigning your own instance ids in a pattern that causes the hashing method to consistently generate the same partition, it is highly unlikely for all of your instances to be on the same partitions.

Note that if you have n partitions, and your function app is running on less than n instances. then the n partitions will be split across the n instances. For instance, if you have very light load on the Azure Functions consumption plan, then you likely only will be assigned one instance/VM. That means that all 5 of your partitions will still go to the same VM.

If you give us some sample instance ids that are landing on the same VM (including Timestamps and the Azure Region they are from), we can help diagnose what exactly is going on.

**Comment by kashish52** [comment]
The reason why we were using the sub orchestrations is because each sub orchestration was memory heavy. Since the memory of the consumption plan is only 1.5 GB. These sub orchestrations on the same VM caused the VM's to behave improperly (sleeping in our case). As far as the the instance id is concerned since this issue is very old the Application Insight does not have the logs. Will update the issue when we face this issue again
