### ISSUE TITLE
How to reset orchestration after hang

### ISSUE THREAD

**Issue by Planche95** [Azure/azure-functions-durable-extension#829]
**Describe the bug**
As mentioned in #822 it looks like my orchestration hang after I call it with json array of over 4000 elements. 
![image](https://user-images.githubusercontent.com/18653765/60459251-ef693400-9c40-11e9-970d-17e0018190f2.png)
As u can see I have 31 tasks stuck in Running state for couple of hours. My question is how to 'unblock' orchestration? For every new call it takes an hour to run or it stuck in running state again.

**Investigative information**

- Durable Functions extension version: 1.8.2
- Function App version (1.0 or 2.0): 2.0
- Programming language used: C#

**Comment by Planche95** [comment]
I deleted everything connected to durable function from the storage, and it's unblocked now

**Comment by espray** [comment]
@Planche95  did you try calling `DurableOrchestrationClientBase.TerminateAsync()`

**Comment by ConnorMcMahon** [comment]
@Planche95, did you have any other questions, or are we good to close this issue?
