### ISSUE TITLE
Timeout and durable functions

### ISSUE THREAD

**Issue by pierre-weceipt** [Azure/azure-functions-durable-extension#83]
Hi, I just wanted to make things clear sa I did not find my answer in the existing doc. Are activity functions subject to the same timeouts as regular azure functions (5min default up to 10min with config)?

**Comment by cgillum** [comment]
Yes, the 10 minute limit applies to activity functions. They are just like regular Azure functions.

**Comment by pierre-weceipt** [comment]
Ok, that's what I thought :)
