### ISSUE TITLE
Usage of static classes

### ISSUE THREAD

**Issue by kijujjav** [Azure/azure-functions-durable-extension#830]
Question 1 : Can we use static classes and their static members in activity functions and sub-orchestrations without passing them as function arguments?

Question 2: Does multiple orchestration Clients share the same static members of static classes?`

**Comment by cgillum** [comment]
> Question 1 : Can we use static classes and their static members in activity functions and sub-orchestrations without passing them as function arguments?

Yes, this is fine in activity functions. It's no different than if you used them on regular functions, like queue-triggered functions or HTTP-triggered functions. Just remember that if your static variables are mutable, the values may be different on different VMs.

> Question 2: Does multiple orchestration Clients share the same static members of static classes?

I don't understand the question. What static members and what static classes are you referring to? Can you provide an example?

**Comment by kjujjava** [comment]
1. If I set these static variables in an orchestration, any activities that are called after that will have the new values right?

2. the question was if these static variables are shared between multiple http requests which will trigger the orchestrations

**Comment by kijujjav** [comment]
1. If I set these static variables in an orchestration, any activity that is called after that will have new values right?

2. the question was if the static variable values are shared between multiple http calls which will trigger orchestrations.

**Comment by cgillum** [comment]
> If I set these static variables in an orchestration, any activity that is called after that will have new values right?

No, not necessarily. The activity function may run on a different VM from the orchestrator function, in which case your static variables will be null.

> the question was if the static variable values are shared between multiple http calls which will trigger orchestrations.

This is true only if the HTTP calls are received by the same VM. If they arrive on a different VM, then they may have different values or the static variables may be null. This is the same behavior for all Azure Functions, not just Durable Functions.

**Comment by kijujjav** [comment]
Hi Chris,

Here are two scenarios, let me know if the behavior is the same in both cases.

        Orch(sets static variables here)                                                                      Orch 
              |                                                                                                            |
              |                                                                                                            |
---------------------                                                                ---------------------------------------------
sub-orch1          sub-orch2                                       sub-orch1(set static variables)                      sub-orch2
       |                         |                                                                 |                                                          |                     
       |                         |                                                                 |                                                          |    
  activity1               activity2                                                      activity1                                        activity2        
           

I can understand that in the second scenario, static variables in activity 2 will be null because they are set by sub-Orch1. what is the behavior for the first case, will both activities have the static variable values that are set in main Orch?

**Comment by kijujjav** [comment]
> Hi Chris,
> 
> Here are two scenarios, let me know if the behavior is the same in both cases.
> 
> Scenario 1:
> 
> ```
>     Orch(sets static variables here)                            
>           |  
>           | 
> ```
> 
> sub-orch1 sub-orch2
> | |
> | |
> activity1 activity2
> 
> Scenario 2:
> 
> ```
>       Orch                           
>           |  
>           | 
> ```
> 
> sub-orch1 (sets static variables here) sub-orch2
> | |
> | |
> activity1 activity2
> 
> I can understand that in the second scenario, static variables in activity 2 will be null because they are set by sub-Orch1. what is the behavior for the first case, will both activities have the static variable values that are set in main Orch?

**Comment by kijujjav** [comment]
```
Hi Chris,

Here are two scenarios, let me know if the behavior is the same in both cases.

Scenario 1:

        Orch(sets static variables here)                            
              |  
              | 
--------------------------------------
sub-orch1                    sub-orch2
       |                         |                          
       |                         |  
  activity1               activity2       


Scenario 2:

          Orch                           
              |  
              | 
------------------------------------------------------------------
sub-orch1 (sets static variables here)                           sub-orch2
       |                                                             |                          
       |                                                             |  
  activity1                                                    activity2       
           

I can understand that in the second scenario, static variables in activity 2 will be null because they are set by sub-Orch1. what is the behavior for the first case, will both activities have the static variable values that are set in main Orch?
```

**Comment by kijujjav** [comment]
Hi @cgillum Can you please shed some light on this?

**Comment by cgillum** [comment]
Static variables are process-wide globals. If one is set by any function, it will be available to any other function running in the same process. It doesn't matter if it's an orchestrator, sub-orchestrator, activity, etc. This is not at all specific to Azure Functions. This is simply how .NET works.

**Comment by kijujjav** [comment]
Thanks, I understand that, I was trying to understand the behavior in distributed systems as they don't run in the same process space.
