### ISSUE TITLE
Add more context to ILogger implementation

### ISSUE THREAD

**Issue by kijujjav** [Azure/azure-functions-durable-extension#833]
Is there a way to add more context to ILogger implementation provided by durable functions?

**Comment by cgillum** [comment]
Durable Functions does not provide an `ILogger` implementation. This is provided by the Azure Functions runtime. Can you provide more detail on what you're trying to accomplish?

**Comment by kijujjav** [comment]
we want to add some parameters to every log message without passing them in each and every log statement for structured logging, these values will start the same thought the orchestration. 
Ex: workflow id | workflow name | log message

We want the above to be the format of a log message without passing workflow id and workflow name to every log function call.

**Comment by cgillum** [comment]
I believe you can use dependency injection for this. See this documentation for more details, including some sample code: https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection.
