### ISSUE TITLE
Default to log only if not replaying

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-durable-extension#834]
It's become very common to see people only log if the current evaluation is not during a replay.  Today most people decorate each log statement with a single-line if statement.  As this becomes the norm, in v2 we should consider making this the default behavior.  It would need to work across all languages, and would need to still have some way for users to opt *in* to the behavior of logging on replays as well.

**Comment by olitomlinson** [comment]
I use a simple extension method that wraps the call to `context.IsReplaying` which makes the code neater.

Example

`context.WhenNotReplay({} => log.logInformation(“something important”));`

**Comment by cgillum** [comment]
I considered the `context.WhenNotReplay(() => log.LogInformation("..."))` approach a while back, but decided against it because it might encourage developers to put business logic in the lambda, which would result in non-deterministic orchestrations.

@ConnorMcMahon Do you think there might be a way to use DI to solve this in .NET? For example, it would be great if we could inject our own `ILogger` which wraps the host-provided `ILogger`, only actually logging when not-replaying.

I suspect solving this in JavaScript will be a bit more straight forward since we can hijack the logging APIs, but .NET will require a bit more careful design.

**Comment by ConnorMcMahon** [comment]
Unfortunately, from what I could find, extensions cannot participate in the dependency injection pipeline that is used to populate `ILogger` in the customer's function. @fabiocav might be able to point us in the right direction if that is possible.

What about a new API like `IDurableOrchestrationContext.LogOnce(ILogger logger, string message)`? It could even just be an extension method that is essentially a wrapper method for the context.IsReplay check. Not perfect, but it is a bit more concise than the current options the customer has.

**Comment by ConnorMcMahon** [comment]
After discussing this offline, the easiest solution will likely be an extension method like `ILogger CreateOnlyOnceLogger(this IDurableOrchestrationContext context, ILogger baseLogger)`, which will create a customer `ILogger` instance that only logs when not replaying that line.

That way, customers can just add one line to the top of their program like below to get this behavior:

`log = context.CreateOnlyOnceLogger(log);`

**Comment by olitomlinson** [comment]
@ConnorMcMahon Nice!

Please could you also make an overload that accepts `TelemetryClient` instead of `ILogger`. 

We use `TelemetryClient` exclusively as it contains `TrackEvent` and `TrackMetric` methods, which `ILogger` does not support.

**Comment by ConnorMcMahon** [comment]
@olitomlinson 

I would love to see something equivalent for `TelemetryClient`. Unfortunately, it looks like [the class is sealed](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.telemetryclient?view=azure-dotnet), which limits our ability to wrap it with our own custom implementation like we can with `ILogger`. 

Something like your extension method is likely the best we could do, and we would need to design it in a way that avoids the temptation to stick business logic in there.

**Comment by olitomlinson** [comment]
@ConnorMcMahon Ahh, not to worry. Its not a big deal for me to carry on using the Extension method :)
