### ISSUE TITLE
 Activity funtion did not run but did not get an error.

### ISSUE THREAD

**Issue by yuka1984** [Azure/azure-functions-durable-extension#835]
**Describe the bug**

Although the Orchestrator completed successfully. Durable Functions log and history table appears to have executed the Activity, the Activity Functions did not actually execute.
The expecteds activity's  application logic was not executed.
Request log of Activity function did not exist on Application Insights log.

**Investigative information**

- Durable Functions extension version: 1.7.1
- Function App version (1.0 or 2.0): 1.0
- Programming language used: C#

***If deployed to Azure***

- Invocation ID : 878ecba8-b231-40ab-8346-12e8bc6eab94
- EventTime : 2019/7/3 9:16:39 (+09:00)
- Region : JapanEast

**Comment by yuka1984** [comment]
I think this issue' s cause is  function host.  But, I did not have confidence, so I wrote it here.

**Comment by cgillum** [comment]
I see your function app, but unfortunately I cannot use the invocation ID to find the orchestration ID. Do you know the orchestration ID for the activity function that did not execute?

**Comment by yuka1984** [comment]
Orchestration ID : 242b12b9ee564bbeb2e6d1b00fb951cd:3
Parent Orchestration ID : cb5a1b1a85f241cc8a702bc65957cb48:1
Parent Parent : 11cf04c47cad4c1da085789890cd9f98:934
Parent Parent Parent : 40f539cc8ba54fe1a4c9fa22fd06559f

**Comment by cgillum** [comment]
Hi @yuka1984. I found the logs for `242b12b9ee564bbeb2e6d1b00fb951cd:3`. Here is what I see:

* At **2019-07-03 00:16:34.** I see that the `Allocate' orchestrator function started and that an event grid notification was sent.
* At **2019-07-03 00:16:34** I see that the `DecrementStockBackOffice` activity function started and completed successfully in less than 1 second (TaskEventId is 0).
* At **2019-07-03 00:16:40** I see that the `AllocateOrderRequest` activity function started and completed successfully in less than one second (TaskEventId is 1).
* At **2019-07-03 00:16:44** I see that the `Allocate` orchestrator function completed. I also see that an event grid notification was successfully sent.

So from Durable Function's perspective, everything ran correctly. Can you clarify which function did not run for you?

**Comment by yuka1984** [comment]
Yes. This activity name is "AllocateOrderRequest".
I can found orchestration history on Durable History table and can found durable trace log on Application Insights.
But I can't found Execution function log on Application Insights.
And this activity's logic was not executed.

**Comment by lilyjma** [comment]
@yuka1984 -- Apologies for the delayed response. Are you still experiencing the issue?
