### ISSUE TITLE
Provide IDurableEntityContext to class model instances

### ISSUE THREAD

**Issue by cecilphillip** [Azure/azure-functions-durable-extension#858]
### Description
Invocations of entity functions have access to an instance of `IDurableEntityContext`, so they have access to properties like `Self` and the ability to message other entities through `SignalEntity`. 

Currently, I don’t see a way to access these capabilities in the operations within an instance of the class based model.

### Proposed behavior
Maybe an option could be to allow classes to optionally accept an instance of `IDurableEntityContext` or some comparable interface via constructor
```csharp
    public interface IUserEntity
    {
        void AddBundle(LinkBundle bundle);
        IList<LinkBundle> Bundles { get; }
    }

    public class UserEntity: IUserEntity
    {      
        [JsonProperty("bundles")]
        public IList<LinkBundle> Bundles { get; } = new List<LinkBundle>();

        public void AddBundle(LinkBundle bundle) => Bundles.Add(bundle);

        public UserEntity(IDurableEntityContext ctx) { … }

        // do we need this method?
        [FunctionName(nameof(UserEntity))]
        public static Task Run([EntityTrigger] IDurableEntityContext ctx)
        => ctx.DispatchAsync<UserEntity>();
    }
```
As an additional suggestion, can the associated entity trigger be implied via convention for the class based model and optionally overridden? Considering most of the properties on the `IDurableEntityContext` are immutable, I’d suspect that the implementation of this trigger will probably be fairly common.

**Comment by sebastianburckhardt** [comment]
Supporting dependency injection for the context sounds reasonable.

However, note that we already support another very simple solution to get to the current context: you can access the context for the currently executing entity via the static member `Entity.Current`.

**Comment by cecilphillip** [comment]
👀 I didn't know that was available. `SetMockContext` looks very helpful for resting as well

**Comment by ElanHasson** [comment]
Wow, yeah I was thinking of how to access the context earlier today. Don't think I encountered this in any of the samples.

**Comment by ConnorMcMahon** [comment]
It sounds like this issue no longer needs to be open, considering we have an alternative approach.
