### ISSUE TITLE
Entities REST API is case sensitive (v2)?

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-durable-extension#864]
This may be ok but just raising as I’m not sure how common case sensitive REST APIs are.  If I have an entity “counter” of class type `Counter` and try to get the state:

This call will fail with a 404 even if instance exists (of `@Counter@test`)
`http://localhost:7071/runtime/webhooks/durabletask/entities/counter/test`

This call succeeds:
`http://localhost:7071/runtime/webhooks/durabletask/entities/Counter/test`

I’m ok if the answer is it’s case sensitive and will stay that way, but figured I’d flag for conversation.

**Comment by cgillum** [comment]
I very much prefer these APIs (and Entity IDs in general) be case-insensitive. @amdeel this would be another good one for you to investigate.

**Comment by cgillum** [comment]
Looking at some documentation and articles on Azure Table Storage, it seems like case insensitive lookups aren't supported. That likely means we'll need to normalize the entity IDs in our code (e.g convert them to lowercase) before saving them to storage. We'll also need to make sure any reflection code we have is also case insensitive.

**Comment by espray** [comment]
According to W3's "HTML and URLs" they should case-sensitive
https://www.w3.org/TR/WD-html40-970708/htmlweb.html
