### ISSUE TITLE
How to get Dependency Injection working with durable functions?

### ISSUE THREAD

**Issue by JacquesJamiesonLancom** [Azure/azure-functions-durable-extension#865]
I've previously used Single functions with a dependency injection `Startup.cs`. Is there a way i can get this work with durable functions?

**Comment by cgillum** [comment]
It should work exactly the same way as ordinary functions. Are you running into issues?

**Comment by JacquesJamiesonLancom** [comment]
I created durable function from the functions cli tool, removed the static method and class modifiers and add a constructor with my service. 

Then created a class called startup and added the DI code referenced in the documentation and a sample I found in one of the azure samples directory.

When I go to run the code it compiles but the Startup class with the DI fails to get executed.

It's strange because if I do exact same steps for non durable function the setup works fine.

If there is a sample durable function with DI that works right of the bat I'd be eager to have a look how I'm going about it wrong.

**Comment by gorillapower** [comment]
I am successfully using DI with durable functions. I modified the samples to use DI in a my version of the repo here to demonstrate, https://github.com/gorillapower/azure-functions-durable-extension/blob/dev/samples/precompiled/Startup.cs

I can reference dependencies from the HttpStart constructor and from the E1_HelloSequence constructor

**Comment by cgillum** [comment]
Thanks @gorillapower! @JacquesJamiesonLancom, please take a look at that example to see whether there might be something odd with your setup.

**Comment by stas-sultanov** [comment]
I've expereinced exactly the same issue.

But found out that if only [NotNull] added to IHttpClientFactory which is pramater to constructor
of class that contains functions and should be instantiated by DI - durable function with DI stops working and says that it can not find sutable constructor.

Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.1.1

**Comment by stas-sultanov** [comment]
I've expereinced exactly the same issue.

But found out that if only [NotNull] added to any interface which is pramater of the constructor
of the class that contains functions and should be instantiated by DI - durable function with DI stops working and says that it can not find sutable constructor.

Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.1.1
