### ISSUE TITLE
Debugging Options: "Enable Just My Code" ignored for Durable Functions

### ISSUE THREAD

**Issue by paulpce** [Azure/azure-functions-durable-extension#872]
### Description
When debugging durable functions, I'm constantly hammered by "xxxxx.cs not found" messages while trying to debug. The "Enable Just My Code" debugging option is enabled.

### Expected behavior
I should be able to set breakpoints in my code and debug only my code without being interrupted by file not found messages when "Enable Just My Code" is on.

### Actual behavior
When debugging durable functions, I'm constantly hammered by "xxxxx.cs not found" messages of various DF class source files. I have the "Enable Just My Code" option switched on, but it still insists on trying to debug DF source code as well. Examples of files regularly seen:
TriggeredFunctionExecutor.cs
FunctionResult.cs
FunctionAssemblyLoadContext.cs
FileLogger.cs
ScriptLoggingBuilderExtensions.cs

I need to push through sometimes 10, sometimes many dozens of these messages at a time to debug through a complex series of orchestrations and activities.  It is frustrating and time consuming.

### App Details

- **Durable Functions extension v1.8.2
- **Azure Functions runtime v2.0
- VS 2019 (16.1.1)
- C#

**Comment by cgillum** [comment]
These are not Durable Functions source files, these are Azure Functions (WebJobs) runtime source files.

@fabiocav could this be because the shipped WebJobs SDK packages are compiled in debug mode instead of release mode? I recall a thread on this kind of issue recently.

**Comment by paulpce** [comment]
> these are Azure Functions (WebJobs) runtime source files

Ah, my apologies. I should have checked that.  I haven't seen the same thing running the non-durable functions in my solution so assumed they were all DF source files. I have Microsoft.Azure.WebJobs v3.0.8 installed as a dependency in all my Azure Functions projects, including the one with Durable Functions extension.

I found [this recent issue](https://github.com/Azure/azure-webjobs-sdk/issues/2261) which seems to be what you were referring to. Happy to close this issue if it's confirmed that's the problem.

**Comment by paulpce** [comment]
On reflection, I think the issue has just been exacerbated in Durable Functions because of the constant entry/exit/replay while debugging.  I probably would not have hit the issue in the other functions.

**Comment by fabiocav** [comment]
Yes. We're tracking that with and will have the updated packages released soon https://github.com/Azure/azure-webjobs-sdk/issues/2261

Please track that issue for updates.

**Comment by paulpce** [comment]
Thanks!
