### ISSUE TITLE
Geo Story

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-durable-extension#88]
What's the mutiple Geo experience with durable extensions. Example having Traffic Manager  in front of AzFunc Durable.
1. What if the DC goes down.
  A. When the DC comes backup will processing continue???
  B. Will both DC work together on the Durable Orchestration?
2. What if the initial request comes in to 1 DC and the Status request is directed to another DC

**Comment by cgillum** [comment]
These are great questions. I've opened a separate GitHub issue to track creating official documentation for this topic (https://github.com/Azure/azure-functions-durable-extension/issues/89). Here is some info that might be helpful:

- Today, all durable state is stored in a particular storage account + task hub. More info [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-task-hubs).
- If the whole DC goes down, you'll lose access to both compute and storage, so all in progress orchestrations will be effectively stopped.
- When the DC comes back up processing will continue automatically from where it left off. There will be no data loss as long as the underlying Azure Storage data isn't lost (which is highly unlikely).
- Multiple function apps cannot collaborate on the same task hub today. For geo/disaster recovery, you will want to go with multiple storage accounts - one in each geo region.  It's up to you to decide how you want to configure Traffic Manager (failover mode or geo-load balancing). Just remember that the two environments are completely isolated from each other.

Let me know if you need any more clarification.

**Comment by espray** [comment]
@cgillum Thanks for the reply.
Yes that was my understanding DC outage scenario and what I was reading about Task hubs. Just did not want to assume. :)

What is the recommended replication strategy for the task hub? I would assume LRS.


Question 2 was around  Pattern 3: Async HTTP APIs [https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-overview#pattern-3-async-http-apis](url)

I have Traffic Manager (TM) on top of 2 Durable AzFunc (F1 & F2). TM routs a request to F1 and a 202 is returned. Now a request is made to get that status (https://myfunc.trafficmanager.net/admin/extensions/DurableTaskExtension/b79baf67f717453ca9e86c5da21e03ec) TM routes the request to F2 this time, I assume a 404 would be returned. Is that correct?
This also ties into the replication strategy for the task hub.

![image](https://user-images.githubusercontent.com/5826764/32675934-495b8134-c61e-11e7-9e07-e0f4beb918a3.png)

**Comment by cgillum** [comment]
Official DR guidance has been merged into docs.microsoft.com will be published around the time of Build.
