### ISSUE TITLE
Question: Disable HTTP APIs

### ISSUE THREAD

**Issue by espray** [Azure/azure-functions-durable-extension#880]
Can the HTTP APIs be disabled?

**Comment by kashimiz** [comment]
Hi @espray, the HTTP APIs are defined as extension webhooks, and we don't provide a way to disable those. For what purpose do you want to disable the HTTP APIs?

**Comment by espray** [comment]
Security being the primary reason for disabling the HTTP APIs

**Comment by cgillum** [comment]
@espray The HTTP APIs are already protected by extension-specific API keys, so there is _some_ security in place already. However, I do recognize that API keys and other "shared secrets" are not great in terms of security best practices.

We could add an option in host.json to disable them. We could also consider other options for locking them down in ways that are more secure. Could you tell us a bit more about your security requirements? I just want to understand if there's more we could do in this area beyond having a simple on/off switch.

**Comment by espray** [comment]
#838 looks to have the same concerns/issues
