### ISSUE TITLE
Retry logic cause huge memory spike

### ISSUE THREAD

**Issue by andrew-vdb** [Azure/azure-functions-durable-extension#886]
### Description
We intentionally create exception which cause retry logic to run in durable function
The retry policy as follow
```
new RetryOptions(TimeSpan.FromMinutes(5), 5)
            {
                BackoffCoefficient = 2
            };
```

10 orchestration doing retry on more or less in the same time

### Expected behavior
> No memory spike

### Actual behavior
Memory usage spiking pretty high during retry
![image](https://user-images.githubusercontent.com/12871379/62469334-588c1c00-b798-11e9-9374-c560ca67d171.png)

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**:
v1.8.3
- **Azure Functions runtime version (1.0 or 2.0)**:
2.0
- **Programming language used**:
c#

Let me know if you need to have azure support ticket to take a look into this case

**Comment by cgillum** [comment]
Hi @andrew-vdb I think a support ticket would be good so that we can get more information about your app. Information such as your app name, the time range, the exception details, etc. will be needed.

**Comment by andrew-vdb** [comment]
There is no exception, I mean we intentionally make the activity function to fail and retry, the issue is more on the huge memory usage for this scenario

support request 119080522001676

**Comment by andrew-vdb** [comment]
@cgillum is this code how durable function do retry?
https://github.com/Azure/durabletask/blob/master/src/DurableTask.Core/RetryInterceptor.cs
![image](https://user-images.githubusercontent.com/12871379/63258004-5f785b80-c27b-11e9-9362-6065b6b735f4.png)

**Comment by andrew-vdb** [comment]
Moved the issue to azure function host
