### ISSUE TITLE
[v1.8.3] host.json config ignored

### ISSUE THREAD

**Issue by marcin-synak** [Azure/azure-functions-durable-extension#894]
### Description
It seems that our configuration for Durable Functions in host.json is now ignored. For us, the main problem is that "hubName" defaults to "DurableFunctionsHub".

We have several functions (published separately) utilizing DF extension and the same Azure Storage. Until now, it worked well with different hub configured for each function.

Now, with all functions using the same default hub, all kinds of weird things happen (such as failed calls to non-existng functions).

No changes to code or config were made recently. The problem affects our existing older functions (v1.8.0) as well as cleanly published one with the most recent libraries ( DF extension v1.8.3, Azure Functions SDK 1.0.29).

Perhaps something changed recently in the way Azure Functions work? Or in host.json structure?
Any help would be very appreciated.

### Expected behavior
Function is initialized with config values as defined in host.json

### Actual behavior
Function is initialized with default config values

### Relevant source code snippets

Here's the host.json:
```
{
  "version": "2.0",
  "functionTimeout": "00:10:00",
  "extensions": {
    "durableTask": {
      "hubName": "RecommendationsHub",
      "maxConcurrentActivityFunctions": 10,
      "maxConcurrentOrchestratorFunctions": 5,
      "extendedSessionsEnabled": true,
      "extendedSessionIdleTimeoutInSeconds": 30
    }
  },
  "logging": {
    "logLevel": {
      "default": "Information"
    }
  }
}
```

Here's a bit from the log:
```
019-08-10T03:23:57.064 [Information] Initializing extension with the following settings: Initializing extension with the following settings:AzureStorageConnectionStringName: , MaxConcurrentActivityFunctions: 40, MaxConcurrentOrchestratorFunctions: 40, PartitionCount: 4, ControlQueueBatchSize: 32, ControlQueueVisibilityTimeout: 00:05:00, WorkItemQueueVisibilityTimeout: 00:05:00, FetchLargeMessagesAutomatically: True, ExtendedSessionsEnabled: False, EventGridTopicEndpoint: , NotificationUrl: https://adrakercorefunctionsrecommendations.azurewebsites.net/runtime/webhooks/durabletask, TrackingStoreConnectionStringName: , MaxQueuePollingInterval: 00:00:30, LogReplayEvents: False. InstanceId: . Function: . HubName: DurableFunctionsHub. AppName: AdRakerCoreFunctionsRecommendations. SlotName: Production. ExtensionVersion: 1.8.3. SequenceNumber: 0.
```

### App Details
- Durable Functions extension version 1.8.0, 1.8.3
- Azure Functions runtime version 2.0
- App written in C#, published using VS2019 using Consumption plan

**Comment by marcin-synak** [comment]
OK, I've found the reason for our issue. It seems it was not restricted to DurableTask but affected all extensions.

Apparently, at some point, Azure Functions "flow" was changed so all host.json settings are written to the default IConfiguration object.
Since we were using some custom DI configuration, we were overwriting the default IConfiguration with our own and all host.json-related info was lost.

The issue is well described here:

https://github.com/Azure/azure-functions-host/issues/4480

**Comment by rayrad** [comment]
Adding a little more info for others that land here. Also, since I haven't seen anyone else mention this I may be interpreting/doing this wrong. If so, please speak up.

**Scenario**
- Functions v2 app, SDK 1.0.29
- C#
- using `[assembly: FunctionsStartup(typeof(Startup))]`
- Using `new ConfigurationBuilder()`, adding my config stuff
- Registering built `IConfigurationRoot` as singleton `IConfiguration`

**What I Observed**
Setting a breakpoint prior to adding my `IConfigurationRoot` and looking at the `IServiceCollection` I could see there was already a singleton `IConfiguration` registered. Furthermore, this instance had the provider for host.json in it, but it wasn't getting loaded when running in Azure.

**My Theory**
It appears that when two singletons of the same service are registered the DI framework will just grab the last added one.

**My Solution**
I extracted the existing `IConfiguration` provider from the `IServiceCollection` and added it to the `ConfigurationBuilder` so that its values are included in the `ConfigurationRoot` that I register and  therefore gets grabbed by the DI framework.

**Code**
```csharp
public IConfigurationRoot AddSettings(IServiceCollection services, string basePath, string name, bool optional, bool reloadOnChange)
{
    var builder = new ConfigurationBuilder().SetBasePath(basePath);

    var existingConfigs = services.Where(svc => svc.ServiceType.Name == "IConfiguration").ToList();
    foreach (var cfg in existingConfigs)
        builder.AddConfiguration((IConfigurationRoot) cfg.ImplementationInstance);

    // Register/load the requested json settings file
    builder.AddJsonFile(name, optional, reloadOnChange);

    // Add all environment vars and build the ConfigurationRoot object. Then register it with the services container
    builder.AddEnvironmentVariables();
    var config = builder.Build();

    // Register the resulting IConfigurationRoot to as a singleton
    services.AddSingleton<IConfiguration>(config);

    return config;
}
```
I hope this is helpful to someone

**Comment by Amd3202** [comment]
@rayrad that was EXTREMELY helpful thank you! Been at this issue a while! I wasn't sure what value to set as basePath so i removed it and it seems to work (at least locally). Thanks again!

**Comment by rayrad** [comment]
I believe `basePath` is the location where to find the JSON files you want to load. But if `name` contains the complete path it will probably work fine.

**Comment by Amd3202** [comment]
yep, thanks i think because the settings.json is in the project root it doesn't need it...

**Comment by eriktack** [comment]
based on the answer by @rayrad, I had to modify it slightly to get the existing instance, as the `ImplementationInstance` is always null for me, I did it like so:
`
foreach (var cfg in builder.Services.Where(svc => svc.ServiceType.Name == nameof(IConfiguration))) {
                var serviceProvider = builder.Services.BuildServiceProvider();
                var existingInstance = serviceProvider.GetService<IConfiguration>();
                configBuilder.AddConfiguration(existingInstance);
            }
`

**Comment by eriktack** [comment]
Expanding on the solution by @rayrad , the `ImplementationInstance` is always null for me, even though there is an existing `IConfiguration` item in the service container.

This works for me to get the host.json settings to remain in the config:
```
            var serviceProvider = builder.Services.BuildServiceProvider();
            var existingConfigInstance = serviceProvider.GetService<IConfiguration>();
            if (existingConfigInstance != null) {
                configBuilder.AddConfiguration(existingConfigInstance);
            }
```

**Comment by xperiandri** [comment]
``` F#
type FunctionConfigurationStartup () =
    inherit FunctionsStartup () with
        override __.Configure (hostBuilder : IFunctionsHostBuilder) =
            let services = hostBuilder.Services
            let serviceProvider = services.BuildServiceProvider ()

            match serviceProvider.GetService<IConfiguration>() with
            | :? IConfigurationRoot as configurationRoot ->
                let configurationBuilder =
                    (new ConfigurationBuilder ())
                        .AddConfiguration (configurationRoot)

                // Configure Azure App Configuration
                match configurationRoot.GetValue<string>("AppConfigEndpoint") with
                | null -> ()
                | appConfigEndpoint ->
                let hostingEnvironment = serviceProvider.GetRequiredService<IHostingEnvironment>()

                configurationBuilder.AddAzureAppConfiguration (fun appConfigOptions ->
                    // possible to run this locally if refactored to use ClientSecretCredential or DefaultAzureCredential
                    appConfigOptions.Connect(Uri(appConfigEndpoint), (*ManagedIdentityCredential*)DefaultAzureCredential(false))
                        // Load configuration values with no label
                        .Select(KeyFilter.Any, LabelFilter.Null)
                        // Override with any configuration values specific to current hosting env
                        .Select(KeyFilter.Any, hostingEnvironment.EnvironmentName)|> ignore) |> ignore
                let configuration = configurationBuilder.Build()
                services.Replace(ServiceDescriptor.Singleton(typeof<IConfiguration>, configuration)) |> ignore

                // Configure Options
                services
                    .Configure<HttpOptions>(fun (options : HttpOptions) -> options.RoutePrefix <- String.Empty; ())
                    .Configure<CosmosOptions>(configuration.GetSection("CosmosDB"))
                    .Configure<SecurityOptions>(configuration.GetSection("Security"))
                |> ignore
            | _ -> ()
```

I implemented the same approach in v3 but `host.json` is not applied at all although I see `HostJsonProvider` in configuration sources.
