### ISSUE TITLE
Manually cancelling tasks that will never complete

### ISSUE THREAD

**Issue by gdodd1977** [Azure/azure-functions-durable-extension#895]
I'm using the pattern of creating multiple WaitForExternalEvent tasks and implementing Task.WhenAny() to get a winner task. But my understanding is that an orchestration will never complete until all tasks are completed. I saw a PR (#820) that would allow passing in a CancellationToken to WaitForExternalEvent. Seems like I could wrap my code in a using block for a new CancellationTokenSource and pass that CTS into my WaitForExternalEvent calls and then call cts.Cancel() when I was done to make sure those tasks are cancelled and the orchestration can complete. 

Code example:
`var task1 = context.WaitForExternalEvent(orchestrationEvent1);
var task2 = context.WaitForExternalEvent(orchestrationEvent2);
var task3 = context.WaitForExternalEvent(orchestrationEvent3);
var winner = await Task.WhenAny(task1, task2, task3);`

My understanding is that if task1 wins, task 2 and 3 will still be waiting forever for something to happen and the orchestration will never complete. I can't pass in a TimeSpan to throw a timeout exception because I have no idea how long it will be before those external events are fired and we really don't care either.

**Comment by fkalseth** [comment]
We have similar code to handle a similar requirement: Three external events where we're interested in the first one to happen, within a given timeout. This seems to work as expected for us:

```

var optionA = context.WaitForExternalEvent("a");
var optionB = context.WaitForExternalEvent("b");
var optionC = context.WaitForExternalEvent("c");

var cancelTimeout = new CancellationTokenSource();
var timeout = context.CreateTimer(context.CurrentUtcDateTime.Add(MaxTimeToWait), cancelTimeout.Token);

var winner = await Task.WhenAny(
    optionA,
    optionB,
    optionC,
    timeout);

cancelTimeout.Cancel();

if(winner == ...)
```

Note the use of a custom timer vs timeout overload, as per #820 

This is on `Microsoft.NET.Sdk.Functions` 1.0.28 and `Microsoft.Azure.WebJobs.Extensions.DurableTask` 1.8.3

**Comment by gdodd1977** [comment]
For my situation, I don't have a specific time period, so a Timer won't help me. I just want to be able to cancel the other WaitForExternalEvents when one of them wins.

**Comment by fkalseth** [comment]
The Timer doesn't affect the WaitForExternalEvents. I just tested removing the Timer in our code, and I see orchestration continuing (and completing) as soon as _one_ of the external events happen. 

We just use the Timer because we don't want to wait indefinetely in case none of the external events ever happen. As such, the timer is just a fourth kind of "external event," if you like.

**Comment by gdodd1977** [comment]
OK. I guess that events aren't the same as timers in that they don't need to explicitly be completed for an orchestration to complete.
