### ISSUE TITLE
Orchestration stuck in `Running` state but is actually complete.

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#901]
I have an orchestration that is stuck in the `Running` state in the TaskHubInstances table.

When looking up the history for the orchestration, I can see the history progressed through to completion. My application telemetry also corroborates this.

Orchestration ID : 5040f0dd-45d5-4eee-9dfe-ce56eb05758f
Execution ID : e1835df599324ae1abe05f655cf5eaa6

UK South
v1.8.3 
Azre Functions 2
.NET CORE c#

**Comment by graham-saunders** [comment]
I'm seeing this as well

Account info:

Azure region: West US
Function app name: VirtuousIntJobsProd
Function name: ProcessStatisticsForOrganization
Azure storage account name: virtuousjobsprod
Hub name: InterminableJobsHubInstances
Example of execution stuck in "Running" state:

Orchestration instance ID (partition key): 1d216e87034b4571a3e633f148dc656b:235
Time: 2019-08-22T08:17:32.915Z

Example of completed execution:
Orchestrator instance ID (partition key): 1d216e87034b4571a3e633f148dc656b:233
Time: 2019-08-22T08:03:09.534Z

**Comment by ElanHasson** [comment]
I think I am seeing the same thing.

Azure Region: US Central
Function Name: AmazonProductLookup
Execution Id: c3d462a017d64b51bf67fdd0c2c525f9
Microsoft.Azure.WebJobs.Extensions.DurableTask: 2.0.0.-beta2
Azure Functions 2.

Additional Details:

My orchestration looks like this:

```csharp
 public async Task AmazonProductLookup(
            [OrchestrationTrigger] IDurableOrchestrationContext context)
        {
            try
            {

                var asins = await context.CallActivityWithRetryAsync<List<(string PopReceipt, string MessageId, string ProductIdentifier)>>(nameof(this.DequeueAmazonLookupRequests), new RetryOptions(TimeSpan.FromSeconds(5), 5) { BackoffCoefficient = 1 }, input: null);
                if (asins.Count == 0)
                {
                    this.logger.LogInformation("No work found in queue, Nothing to do.");

                    await context.CreateTimer(context.CurrentUtcDateTime.AddSeconds(30), CancellationToken.None);
                    return;
                }

                await context.CallActivityWithRetryAsync(nameof(this.ProcessPopReceipt), new RetryOptions(TimeSpan.FromSeconds(5), 5) { BackoffCoefficient = 1 }, input: asins);

                var results = await context.CallSubOrchestratorAsync<AmazonItemResponse>(nameof(this.PerformAmazonLookup),
                    input: asins.Select(i => i.ProductIdentifier).Distinct().ToArray());

                if ((results?.Items?.Item?.Length ?? 0) == 0)
                {
                    this.logger.LogInformation("Lookups returned zero results. Nothing to do.");
                    return;
                }

                var tasks = new List<Task>(results.Items.Item.Length);
                foreach (var item in results.Items.Item)
                {
                    this.logger.LogInformation("Processing lookup of {asin}", item.ASIN);

                    tasks.Add(context.CallActivityWithRetryAsync(nameof(ProcessAmazonProductLookupStub), new RetryOptions(TimeSpan.FromSeconds(5), 5) { BackoffCoefficient = 1 }, input: (item, new DateTimeOffset(context.CurrentUtcDateTime))));
                }

                await Task.WhenAll(tasks);

                this.logger.LogInformation("Completed all work. Sleeping and trying again.");
            }
            finally
            {
                context.ContinueAsNew(null);
            }
        }
```

**Comment by ConnorMcMahon** [comment]
I can reproduce this myself. Will investigate.

**Comment by ConnorMcMahon** [comment]
It turns out my reproduction of this was not actually this issue.

@olitomlinson, do you have a more recent instance id I can take a look at?

**Comment by olitomlinson** [comment]
@ConnorMcMahon I'm not currently tracking anything, but ill do some more digging.

**Comment by olitomlinson** [comment]
@ConnorMcMahon Got one. Same scenario. `runtimeStatus` is showing as `Running` in the instances table, but the history and my telemetry is showing that it ran through to completion.

ExecutionId : ee1951a535144f2893e8432c362f8232
_Timestamp : 2020-02-18T18:09:19.244Z
UK West 
DF 1.8.5

**Comment by ConnorMcMahon** [comment]
Thanks for the update @olitomlinson!

**Comment by ConnorMcMahon** [comment]
@olitomlinson 

I took a look at your instance, and it appears this is a rare race condition when hitting split brain:

Here is the timeline:

2020-02-18 18:09:10.2188036: Worker 1 has the partition lease for that instance.
2020-02-18 18:09:12.0376246: Worker 2 steals that lease. Both workers think they have the lease until Worker 1 tries to renew.
2020-02-18 18:09:18.8188942: Worker 1 receives the `Execution Started` event.
2020-02-18 18:09:19.2515457: Worker 1 finishes processing event and schedules activity
**2020-02-18 18:09:19.3080468: Worker 1 finishes updating history table**
2020-02-18 18:09:19.4017033: Worker 2 grabs `Task Completed` event after activity completed
..._Worker 2 continues processing orchestration_
2020-02-18 18:09:19.7265158: Worker 2 marks orchestration instance status as completed
**2020-02-18 18:09:19.9012976: Worker 1 marks orchestration instance status as running**
2020-02-18 18:09:21.4271348: Worker 1 realizes it no longer has the lease and releases it.

The two bolded steps should have happened closer together. If they had, this race condition would have been avoided.

@cgillum, I know you mentioned the possibility of us improving our lease stealing algorithm to reduce split brain. I believe that would have helped avoid this scenario.

**Comment by overunityx** [comment]
I have a similar issue driving me crazy.

In my test, i have a function app with 50 orchestration 'workers' on Azure Tenant 1 - reading blobs from Azure Tenant 2 - and writing results to Azure Tenant 3.

If I run the function app on any Storage Emulator, it runs flawlessly for days, under heavy load.
If I run the same app on azure cloud (consumption plan) using the same resources and conditions... it falls apart in minutes. with orchestrations stuck doing nothing at all in 'running' state.

Each orch has a durable entity tracking its state, and i can see the last activity it was doing. (which is not consistent). But it also seems that the orch moved a few tasks ahead and completed some of the job. And it doesnt seem to be communicating with its Durable entity during those tasks.

**Comment by ConnorMcMahon** [comment]
@overunityx, I think your issue is actually different based on what you are describing. From your description, it sounds like your orchestrations are actually getting stuck, not just having the incorrect state of "Running" when they are actually completed.

If this is the case, could you open a separate issue with as much information about a stuck orchestration instance id as you can.

Required info:
- Instance Id
- Region
- Time range in UTC

Helpful info:
- App name
- Storage account name
- Taskhub name

**Comment by ConnorMcMahon** [comment]
Also @olitomlinson,

I took a second look at this today, and it looks like a recent [change now](https://github.com/Azure/durabletask/commit/256027abc2b00747b8c4fb5f9c7dea6994ad423d#diff-da2e17723a7df5abeded73c957cc086cL1208) will use Insert instead InsertOrReplace on the initial history write, which may fix this specific issue, as we will throw an error instead of silently appending the history and updating the state back to running.

Have you encountered any of this behavior on 1.8.5, 2.1.1, or 2.2.0?

**Comment by olitomlinson** [comment]
@ConnorMcMahon I'm using 2.2.0 in prod and I've not seen this happen for a while. I'll assume this is fixed and close it. I'll re-open if I spot anything :) Cheers!
