### ISSUE TITLE
Cannot customize IDurableHttpMessageHandlerFactory using DI

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-functions-durable-extension#923]
### Description
Customization using a class that implements `IDurableHttpMessageHandlerFactory` is not working.

### Expected behavior
`HttpMessageHandler` is created using Factory added by DI.

### Actual behavior
Always created using the default Factory.

### Relevant source code snippets
```csharp
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        // Register own factory
        builder.Services.AddSingleton<IDurableHttpMessageHandlerFactory, MyDurableHttpMessageHandlerFactory>();
    }
}

public class MyDurableHttpMessageHandlerFactory : IDurableHttpMessageHandlerFactory
{
    public HttpMessageHandler CreateHttpMessageHandler()
    {
        // Cannot reach this code
        return new HttpClientHandler();
    }
}
```

**Comment by cgillum** [comment]
I'm going to add some official documentation which describes this pattern once we release beta3. Here is what I've written. Let me know if you think this is okay.

### Extensibility (.NET only)

You can use [Azure Functions .NET dependency injection](https://docs.microsoft.com/azure/azure-functions/functions-dotnet-dependency-injection) to customize the behavior of the HTTP client used by orchestrator functions. This ability can be useful for making small behavioral changes. It can also be useful for unit testing the HTTP client by injecting mock objects.

The following example demonstrates using dependency injection to disable SSL certificate validation for orchestrator functions that call external HTTP endpoints.

```csharp
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        // Register own factory
        builder.Services.AddSingleton<
            IDurableHttpMessageHandlerFactory,
            MyDurableHttpMessageHandlerFactory>();
    }
}

public class MyDurableHttpMessageHandlerFactory : IDurableHttpMessageHandlerFactory
{
    public HttpMessageHandler CreateHttpMessageHandler()
    {
        // Disable SSL certificate validation (not recommended in production!)
        return new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback =
                HttpClientHandler.DangerousAcceptAnyServerCertificateValidator,
        };
    }
}
```

**Comment by cgillum** [comment]
Docs have been updated with this content. They should be live tomorrow.
