### ISSUE TITLE
Why is a webjob shutdown cancellation token propagated when the task hub worker stops?

### ISSUE THREAD

**Issue by kabcampbell** [Azure/azure-functions-durable-extension#925]
I've been monitoring when instances of my webjobs shut down using the following code:
```
using (host)
{
    var programLogger = host.Services.GetService<ILogger<Program>>();

    var applicationInstanceID = Environment.GetEnvironmentVariable("WEBSITE_INSTANCE_ID");

    var shutdownToken = new WebJobsShutdownWatcher().Token;
    shutdownToken.Register(() => programLogger.LogWarning("Webjob on InstanceID {InstanceId} is shutting down!", applicationInstanceID));

    await host.RunAsync();
}
```
Since I installed the durable tasks extension, I noticed that this message is getting logged every time the task hub worker stops, presumably because it is idle. Is this the intended behavior? Is there another way I should be looking for webjob shutdowns now that I am using this extension?

**Comment by ConnorMcMahon** [comment]
Hmm, the task hub worker should not be stopped when it is idle, it should run until the WebJobs runtime shuts down the extension, which generally should only happen when the WebJobs runtime itself is shutting down.

**Comment by kabcampbell** [comment]
Maybe my question is phrased slightly wrong. What seems to be happening is that when the task hub worker goes idle, the WebJobsShutdownWatcher token is getting propagated. In the past I have used the above code to log job host shutdowns, but since installing the durable tasks extension it logs that warning every time the task hub worker goes idle.

**Comment by lilyjma** [comment]
@kabcampbell -- apologies for the delayed response. We're a little confused about your question. Do you have a repro of this behavior or more info you can provide?
