### ISSUE TITLE
Stuck orchestration - incorrect duplication detection

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#926]
### Description
An internal customer reported an issue where an orchestration got stuck. Upon further investigation, it looks like an instance of the functions host got into a bad state. 12 hours later, the owning partition moved to another VM and the orchestration progressed correctly.

### Expected behavior
The orchestration runs to completion in a normal amount of time.

### Actual behavior
The orchestration got stuck for ~12 hours

### Relevant source code snippets
N/A

### Known workarounds
Restarting the function app may be a possible mitigation.

### App Details

- **Durable Functions extension version**: v1.8.3
- **Azure Functions runtime version (1.0 or 2.0)**: ??
- **Programming language used**: ??

### Kusto Query
The following Kusto query shows exactly what's happening for this particular instance. This is in the **Central US** region.
```
DurableFunctionsEvents
| where TIMESTAMP between (datetime(2019-09-05 09:50:00) .. 12h)
| where InstanceId == "064451532c7f422ab1c4d2f50cf4e94c:67" or TargetInstanceId == "064451532c7f422ab1c4d2f50cf4e94c:67"
| where ProviderName == "DurableTask-AzureStorage"
| extend ActId = substring(ActivityId, 0, 8), RelActId = substring(RelatedActivityId, 0, 8), ExId = substring(ExecutionId, 0, 4), MsgId = substring(MessageId, 0, 8) 
| project TIMESTAMP, EventStampName, RoleInstance, Pid, Tid, ActId, RelActId, Level, MsgId, ExId, TaskName, TaskEventId, PartitionId, EventType, Age, NewEvents, DequeueCount, Details, LatencyMs, TaskHub, Account, ExtensionVersion 
| order by TIMESTAMP asc
```

**Comment by ElanHasson** [comment]
Hi Chris,

Thanks for sharing this so it can help others.

> the owning partition moved to another VM

Can you please elaborate on what you mean when you say this?

Thanks

Elan

**Comment by cgillum** [comment]
@ElanHasson We use blob leases to determine which VMs (or rather, function app instance) should run which orchestrations. More details can be found [here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-perf-and-scale#orchestrator-scale-out). If your function app scales out or scales in, then a lease might move from one instance to another. In this particular case, the movement of the lease caused the stuck orchestration to move to a new (healthy) instance, allowing it to resume and ultimately complete its execution.

**Comment by ElanHasson** [comment]
Cool, thanks for clarifying.

**Comment by ConnorMcMahon** [comment]
It turns out that the reason the customer hit this issue was due to the fact that the only instance their site was running on was hitting OutOfMemoryExceptions. When the site would restart, the site would resume the orchestrations.

The reason the site was hitting OutOfMemoryExceptions was due to the app being configured as 32 bit instead of 64 bit. Once the customer switched their application to 64 bit, they no longer encountered issues.
