### ISSUE TITLE
Entity invocation fails with explicit interface implementations

### ISSUE THREAD

**Issue by aaronpowell** [Azure/azure-functions-durable-extension#928]
If you implement an interface **explicitly** on the Entity class the `DispatchAsync` will fail as the method(s) aren't found.

Example implementation:

```csharp
public interface IChatRoom {
    DateTime Post(string content);
    List<KeyValuePair<DateTime, string>> Get();
}

public class ChatRoom : IChatRoom {
    public ChatRoom()
    {
        this.ChatEntries = new SortedDictionary<DateTime, string>();
    }

    [JsonProperty("chatEntries")]
    public SortedDictionary<DateTime, string> ChatEntries { get; set; }

    // an operation that adds a message to the chat
    DateTime IChatRoom.Post(string content)
    {
        var timestamp = DateTime.UtcNow;
        this.ChatEntries.Add(timestamp, content);
        return timestamp;
    }

    // an operation that reads all messages in the chat
    List<KeyValuePair<DateTime, string>> IChatRoom.Get()
    {
        return this.ChatEntries.ToList();
    }
}
```

The reason for this is that the method name(s) are `Namespace.InterfaceName.MethodName` on the type implementing it.

I came across this problem when trying to use Durable Entities with F# which **only** supports explicit interface implementations ([ref 1](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/interfaces#calling-interface-methods) and [ref 2](https://fsharpforfunandprofit.com/posts/interfaces/#explicit-and-implicit-interface-implementations)).

Here's an F# sample:

```fsharp
type ITheatersForMovie =
    abstract member Init: Theater array -> unit

type TheatersForMovie() =
    member val Theaters = Array.empty<Theater> with get, set

    [<FunctionName("TheatersForMovie")>]
    member __.Run([<EntityTrigger>] ctx : IDurableEntityContext) =
        ctx.DispatchAsync<TheatersForMovie>()

    interface ITheatersForMovie with
        member this.Init theaters =
            this.Theaters <- theaters
```

The error message shown is similar to the one in #862. 

Digging into the code it seems that the problem is on this line: https://github.com/Azure/azure-functions-durable-extension/blob/v2.0.0-beta2/src/WebJobs.Extensions.DurableTask/EntityScheduler/TypedInvocationExtensions.cs#L37-L42

A workaround is to create a method on the type that matches the name that is on the interface which just calls through to the interface:

```fsharp
type ITheatersForMovie =
    abstract member Init: Theater array -> unit

type TheatersForMovie() =
    member val Theaters = Array.empty<Theater> with get, set

    [<FunctionName("TheatersForMovie")>]
    member __.Run([<EntityTrigger>] ctx : IDurableEntityContext) =
        ctx.DispatchAsync<TheatersForMovie>()

    interface ITheatersForMovie with
        member this.Init theaters =
            this.Theaters <- theaters

    member this.Init theaters =
        (this :> ITheatersForMovie).Init theaters
```

**Comment by aaronpowell** [comment]
The only solutions I can think of is to:

* Use `GetMethods` and then run a LINQ `Where` against them to filter against the name, maybe in an `EndsWith` test
* Require the interface to be passed in, not the class to `DispatchAsync` and then reflection can be done against the interface
  * Not sure that'd work because, if I understand it correctly, the type is created within that method
* Use `GetMethod` as current, if it returns `null` then check for interfaces and look against each of them for the named method on them (or do a LINQ-`Where` lookup)
* Not support explicit interface implementations (which will mean that F# support is really problematic)

**Comment by cgillum** [comment]
FYI @shibayan in case you have any thoughts on a solution for this. I didn't realize that reflection behaves differently with explicit interface implementations!

**Comment by aaronpowell** [comment]
I didn't realise either! Caught me off guard when I was trying to work out the problem.

@shibayan - I'm happy to implement the fix if you let me know which of the options are preferred.

**Comment by shibayan** [comment]
@cgillum @aaronpowell I didn't know this either. I think that both the first and third solutions work well.

In my opinion, it's better to get a method from the type of the implemented interface. In that case, I want to restrict that only one interface can be implemented in Entity class.

Either way, there may be a method with the same name in the explicit and implicit implementations, so we should consider which method should take precedence.

**Comment by aaronpowell** [comment]
That's a good point on the order of precedence around methods with the same name as the interface. My assumption would be that you want the interface method to be the one to call, since the proxy is _really_ what you work against in the `SignalEntityAsync` call.

**Comment by shibayan** [comment]
Will it behave as follows?

- If interface is implemented
  - Search by explicit implementation first. If not found, current behavior
- If interface is not implemented
  - Keep current behavior

**Comment by aaronpowell** [comment]
@shibayan @cgillum I've opened PR #935 which addresses this bug. Tried to tackle a number of scenarios and edge cases along the way.

**Comment by cgillum** [comment]
PR is merged! This fix will go out with beta3.
