### ISSUE TITLE
No way to use IDurableEntityContext in DispatchAsync pattern

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-durable-extension#930]
Was hoping to use the new dependency injection stuff to do something like the `End()` method here:

```csharp
public class Counter
    {
        private readonly IDurableEntityContext _ctx;
        private readonly ILogger _log;
        public Counter(IDurableEntityContext ctx, ILogger log)
        {
            _ctx = ctx;
            _log = log;
        }
        public int Count = 0;
        public void Increment() => Count++;
        public void Decrement() => Count--;
        public void End() => _ctx.DestructOnExit();

        [FunctionName(nameof(Counter))]
        public static Task Run(
            [EntityTrigger] IDurableEntityContext ctx,
            ILogger log) 
            => ctx.DispatchAsync<Counter>(ctx, log);
    }
```

But it throws an exception whenever I try to run the `End()` operation - I assume something about using the context in an already-existing context method made it unhappy.  I would want some way to have access to the current entity context in my methods though.

**Comment by cgillum** [comment]
We actually have a static method that is designed for accessing the current entity context, `Entity.Current`. Would that unblock your scenario?

```csharp
public class Counter
{
    private readonly ILogger _log;

    public Counter(ILogger log)
    {
        _log = log;
    }

    public int Count = 0;

    public void Increment() => Count++;
    public void Decrement() => Count--;
    public void End() => Entity.Current.DestructOnExit();

    [FunctionName(nameof(Counter))]
    public static Task Run(
        [EntityTrigger] IDurableEntityContext ctx,
        ILogger log) 
        => ctx.DispatchAsync<Counter>(log);
}
```

**Comment by jeffhollan** [comment]
Awesome! Yep that works.  Thank

**Comment by olitomlinson** [comment]
> ```cs
> Entity.Current
> ```

@cgillum Just a thought, I think this might need a code example in the docs in the scenario of showing how to do entity-to-entity signalling using class-based entities. 

Initially It had me stumped because class-based entities don't have `context` in the scope of their entity methods, _unless of course_, you use `Entitiy.Current`

**Comment by cgillum** [comment]
@olitomlinson I agree. FYI @sebastianburckhardt and @anthonychu
