### ISSUE TITLE
[2.0.0-beta2] How to stop the internal Entity traces being published to App Insights?

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#941]
I'm not sure what I'm missing here, but I can't seem to suppress the default Entity traces.

Here is the kind of stuff I'm seeing when searching `traces` in App Inisights :

![image](https://user-images.githubusercontent.com/4224880/65389057-af01e980-dd49-11e9-8f5d-d2b56d651d65.png)

an example trace message

`@thread@879a2448-dafe-41d0-<redacted>: Function 'thread (Entity)' completed. ContinuedAsNew: True. IsReplay: False. Output: (1420 bytes). State: Completed. HubName: ThreadTaskHub. AppName: redacted20190817022226. SlotName: Production. ExtensionVersion: 2.0.0. SequenceNumber: 523.`

the `host.json` file

```
{
  "version": "2.0",
  "extensions": {
    "durableTask": {
      "hubName": "ThreadTaskHub",
      "storageProvider": {
        "azureStorage": {
          "connectionStringName": "DurableFunctionsStorage",
          "trackingStoreConnectionStringName": "DurableFunctionsStorage",
          "partitionCount": 5
        }
      },
      "tracking": {
        "traceInputsAndOutputs": false,
        "traceReplayEvents": false
      }
    }
  },
  "logging": {
    "logLevel": {
      "default": "Warning",
      "Host.Triggers.DurableTask": "Warning",
      "Host.Results": "Error",
      "Function": "Error",
      "Host.Aggregator": "Warning",
      "Function.Thread": "Warning",
      "Function.thread": "Warning"
    }
  }
}
```
What am I missing here? I would have expected the above `logLevel` configurations would have suppressed the `traces`?

---

For completeness here is the Entity code. The Entity class isn't really doing anything complicated (it is working as expected, no problems here)

```
public class Thread
    {
        [JsonProperty("Foos")]
        public List<Foo> Foos = new List<Foo>();

        public void Handle(Foo foo)
        {
            Foos.Add(foo);
        }

        [FunctionName(nameof(Thread))]
        public static Task Run([EntityTrigger] IDurableEntityContext ctx)
            => ctx.DispatchAsync<Thread>();
    }
```

started from a queue triggered client

```
[FunctionName("redacted")]
        public async Task RunAsync(
            [QueueTrigger("redacted", Connection = "StorageConnectionString")]string queueItem,
            [DurableClient] IDurableEntityClient client)
        {
            var foo = new Foo();
            try
            {
                var entityId = new EntityId(nameof(Thread), Guid.NewGuid().ToString());
                await client.SignalEntityAsync(entityId, "Handle", foo);
            }
            catch(Exception ex)
            {
                _logger.TrackException(ex);
            }
        }
```

**Comment by olitomlinson** [comment]
I think this might be a wider problem with Functions and not specifically DF, as I've removed DF from the project and its still ignoring my configuration for normal functions.

**Comment by cgillum** [comment]
@brettsam any thoughts or suggestions?

**Comment by brettsam** [comment]
Where are those logged? If you look at the customDimensions in App Insights, does it have a Category?

**Comment by olitomlinson** [comment]
@brettsam @cgillum Figured it out and its not a DF issue.

I'm using self-instantiated `TelemetryClient` in a `Startup : FunctionStartup` class and then passing that to the trigger functions via constructor injection. `host.json` logging settings are ignored (as per this issue)

If I remove the DI configuration `builder.Services.AddSingleton(_ => TelemetryClientFactory.Create());` and then instantiate the `TelemetryClient` in the trigger function constructor, everything works as expected and the `host.json` logging settings are honoured.

Feels like there is some DI issue with `TelemetryClient` maybe?

**Comment by brettsam** [comment]
Our TelemetryClient has a lot of custom behavior, so if you create your own, you're missing that. You can simply request the TelemetryClient in your ctor and you'll get "ours" via DI, which should have all the correct filtering wired up. 

Is there custom behavior you need to add to the App Insights behavior that we already include?

**Comment by olitomlinson** [comment]
@brettsam This is what our Factory method does. We use this so we can run the app locally with a well known website name so we can continue to use AppInsights for debugging purposes  :

```
public static class TelemetryClientFactory
    {
        private static TelemetryClient _telemetryClient;

        public static TelemetryClient Create(string fallbackApplicationName)
        {
            if (_telemetryClient != null) return _telemetryClient;

            var key = GetEnvironmentVariable("APPINSIGHTS_INSTRUMENTATIONKEY") ?? string.Empty;
            var cloudName = GetEnvironmentVariable("WEBSITE_SITE_NAME") ?? fallbackApplicationName;

            TelemetryConfiguration.Active.InstrumentationKey = key;
            _telemetryClient = new TelemetryClient
            {
                InstrumentationKey = key,
                Context =
                {
                    Cloud =
                    {
                        RoleName = cloudName.ToLower()
                    }
                }
            };

            return _telemetryClient;
        }

        private static string GetEnvironmentVariable(string name)
        {
            return Environment.GetEnvironmentVariable(name, EnvironmentVariableTarget.Process);
        }
    }
```

If we run this factory method from DI, the LogLevel settings from host.json are ignored

`builder.Services.AddSingleton(_ => TelemetryClientFactory.Create("redacted"));`

if we run it in the constructor of a typical function class, it works just fine. 

So there is nothing wrong with the Factory itself, just appears to be a timing issue of running it in `Startup` Services, which sounds like a bug?

**Comment by brettsam** [comment]
You're overriding our built-in `TelemetryClient` with this call: `builder.Services.AddSingleton(_ => TelemetryClientFactory.Create("redacted"))`, so nothing we do is being used, including the filters. I have a bug filed to prevent this (or at least log a warning so you know you're doing it).

If you're trying to override the RoleName, register an `ITelemetryInitializer`  with DI instead. Then you can set the RoleName on all telemetry. We actually do that already [here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsRoleEnvironmentTelmetryInitializer.cs) -- you can mostly copy that and use your logic. Then everything flows through the correct pipeline.

Note that I'd recommend adding a reference to https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/ and let it pull in your App Insights reference so you don't move ahead of what we support. (for example, 2.11 is out as of Monday but we don't have support yet -- it's coming in our next release as we're always slightly behind).

**Comment by olitomlinson** [comment]
Thanks for that @brettsam - that's very useful!

But I'm still struggling to understand why it loads in the `LogLevel` settings just fine but only when I call my Factory method from **within** the constructor of the Function, but not through DI?

```
 public class FooHandlerFunction
    {
        private readonly TelemetryClient _logger;

        public InboundHandler(Database inboxDatabase)
        {
            _logger = TelemetryClientFactory.Create("redacted");
        }

        [FunctionName("Redacted")]
        public async Task RunAsync([QueueTrigger("inbound", Connection = "StorageConnectionString")]string queueItem)
        {
               ...
        }
   }
```

**Comment by brettsam** [comment]
Here, only your function is using your TelemetryClient. The rest of the system still uses the one with all of our Initializers, Modules, etc. I suspect that anything you logged using this _logger would also ignore filters. When you register the TelemetryClient via DI, you also override what the host internally uses and not just your function.

**Comment by olitomlinson** [comment]
@brettsam Ah this makes complete sense now! Thank you so much for taking the time to explain that! I didn't realise it would override the TelemetryClient that is used inside of Durable Functions/Entites!

**Comment by olitomlinson** [comment]
@brettsam I'm struggling with this. I did as you prescribed and created a custom `TelemetryInitialiser` from your example [here](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Logging.ApplicationInsights/Initializers/WebJobsRoleEnvironmentTelmetryInitializer.cs) and hooked that up through DI, and receive the `TelemetryClient` through the function ctor. However, the telemetryClient isn't emitting any of my user-code events, traces, metrics etc.

I have also added a reference to `Microsoft.Azure.WebJobs.Logging.ApplicationInsights - 3.0.13` (which pulls in `Microsofy.ApplicationInsights - 2.10`)

Please can you advise where I'm going wrong? many thanks.

---

```
public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            ...
            builder.Services.AddSingleton<ITelemetryInitializer>(_ => new CustomTelemetryInitializer("redacted"));
        }
    }

```

---

```
public class CustomTelemetryInitializer : ITelemetryInitializer
    {
        internal const string AzureWebsiteName = "WEBSITE_SITE_NAME";
        internal const string AzureWebsiteSlotName = "WEBSITE_SLOT_NAME";
        private const string DefaultProductionSlotName = "production";
        private const string WebAppSuffix = ".azurewebsites.net";
        private string _overrideCloudRoleName;

        public CustomTelemetryInitializer(string OverrideCloudRoleName)
        {
            _overrideCloudRoleName = OverrideCloudRoleName;
        }

        public void Initialize(ITelemetry telemetry)
        {
            // We cannot cache these values as the environment variables can change on the fly.
            if (string.IsNullOrEmpty(telemetry.Context.Cloud.RoleName))
            {
                telemetry.Context.Cloud.RoleName = GetRoleName(_overrideCloudRoleName);
            }

            if (string.IsNullOrEmpty(telemetry.Context.GetInternalContext().NodeName))
            {
                telemetry.Context.GetInternalContext().NodeName = GetNodeName(_overrideCloudRoleName);
            }

            if (string.IsNullOrEmpty(telemetry.Context.InstrumentationKey))
            {
                telemetry.Context.InstrumentationKey = Environment.GetEnvironmentVariable("APPINSIGHTS_INSTRUMENTATIONKEY");
            }
        }

        private static string GetRoleName(string overrideCloudRoleName)
        {
            return GetAzureWebsiteUniqueSlotName(overrideCloudRoleName);
        }

        private static string GetNodeName(string overrideCloudRoleName)
        {
            string name = GetAzureWebsiteUniqueSlotName(overrideCloudRoleName);

            if (!string.IsNullOrEmpty(name))
            {
                // maintain previous behavior of node having the full url
                name = name + WebAppSuffix;
            }

            return name;
        }

        /// <summary>
        /// Gets a value that uniquely identifies the site and slot.
        /// </summary>
        private static string GetAzureWebsiteUniqueSlotName(string overrideCloudRoleName)
        {
            string name = Environment.GetEnvironmentVariable(AzureWebsiteName) ?? overrideCloudRoleName;
            string slotName = Environment.GetEnvironmentVariable(AzureWebsiteSlotName);

            if (!string.IsNullOrEmpty(slotName) &&
                !string.Equals(slotName, DefaultProductionSlotName, StringComparison.OrdinalIgnoreCase))
            {
                name += $"-{slotName}";
            }

            return name?.ToLowerInvariant();
        }
    }
```

**Comment by olitomlinson** [comment]
@brettsam Please can you help me?
