### ISSUE TITLE
 Cannot bind parameter 'starter' to type DurableOrchestrationClient.

### ISSUE THREAD

**Issue by SS-TT** [Azure/azure-functions-durable-extension#943]
### Description
Launching the function locally or publishing from Visual Studio works fine, however when deploying from the Azure DevOps task I get this message on start:

> Microsoft.Azure.WebJobs.Host: Error indexing method 'MyFunction'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

I think it may be related to the fact that VS publishes using a Web Deploy profile while Azure uses Zip Package, but I'm not sure about that.

### Expected behavior
Function must start correctly even when deploying from Azure DevOps

### Actual behavior
Function fails to start only when deploying from Azure DevOps

### Relevant source code snippets
```csharp
// insert code snippet here
```

### Known workarounds
> Provide a description of any known workarounds you used.

### App Details

- **Durable Functions extension version (v1.8.3)**:
- **Azure Functions runtime version (2.0)**:
- **Programming language used (C#)**:

### Screenshots
> If applicable, add screenshots to help explain your problem.

### If deployed to Azure
I can't share these details, and I can't even provide the orchestration instance ID as the function is not even starting.

- **Timeframe issue observed**:
- **Function App name**:
- **Function name(s)**:
- **Azure region**:
- **Orchestration instance ID(s)**:
- **Azure storage account name**:

**Comment by SS-TT** [comment]
Thanks for your reply.

Here's the requested signature: 

```csharp
public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Function, "post", Route = null)] HttpRequest req,
            [OrchestrationClient] DurableOrchestrationClient starter)
```

If this is a coding issue, I don't understand why it works locally (and also when publishing from VS) while it doesn't work when publishing from Azure DevOps.

**Comment by SS-TT** [comment]
Could it be related to the `extensions.json` file?
Seems like this file is created when publishing locally but it's missing in the DevOps build.
It's contents have references to this type: `Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableTaskWebJobsStartup`

**Comment by adamreed90** [comment]
I am having this issue as well...

**Comment by JakobRahrBorkJensen** [comment]
I have had the same issue with an HTTP triggered Azure Function v2, putting strings into a Queue. 
The fix proposed by SS-TT worked for me implemented as a Command Line step right after the dotnet build step in CI pipeline.

**Comment by tjones0808** [comment]
having the same issue. works perfectly fine locally once deployed I get this error message.

**Comment by prabirkrsarkar** [comment]
Hi,
    Was trying to test the following functions locally using VS Code - (Version: 1.52.1) : - https://docs.microsoft.com/en-us/samples/azure-samples/iot-hub-dotnet-autoscale/iot-hub-dotnet-autoscale/

Getting the following error while building the code with VSCode.

"2020-12-29T12:03:40.415Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'IotHubScaleInit'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)."

Any help is appreciated.

Thnx
Prabir

**Comment by ConnorMcMahon** [comment]
Could someone who had this issue provide a .csproj for their file? In general, dotnet build _should_ create the extensions.json file in the bin folder, especially in our templates.
