### ISSUE TITLE
Orchestrations with large retry intervals can get stuck

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-functions-durable-extension#944]
### Description
An orchestrator function that calls a continuously failing activity function with retry options that cause a retry to exceed 7 days can get permanently stuck in a way that is difficult to debug.

The problem is that DurableTask.AzureStorage attempts to enqueue a message with a visibility delay that is too large and the call gets rejected. The extension does not handle this gracefully and the orchestration gets stuck retrying continuously.

The extension should prevent this from happening by enforcing a maximum retry interval that is no greater than 6 days (or use a version of the Azure Storage SDK that allows arbitrary visibility delays).

### Known workarounds
Specify RetryOptions.MaxRetryInterval = TimeSpan.FromDays(6), or some other value that is less than 7 days.

**Comment by ConnorMcMahon** [comment]
This is fixed for V1. Need to get in a PR for V2 before it goes GA.

**Comment by cgillum** [comment]
Fixed with https://github.com/Azure/azure-functions-durable-extension/pull/1006.
