### ISSUE TITLE
Error when running Durable functions locally, targeting .NET Core 

### ISSUE THREAD

**Issue by handeeadiguzel** [Azure/azure-functions-durable-extension#95]
Hi,

I'm trying to run the following code sample locally, targeting .NET core (netstandard2.0):
[https://azure.github.io/azure-functions-durable-extension/files/VSDFSampleApp.zip](url)

I've changed the target framework to: **netstandard2.0** and **"FUNCTIONS_EXTENSION_VERSION": "beta"**,
 
**Nuget dependencies:** 

- Microsoft.Azure.WebJobs (3.0.0-beta3)
- Microsoft.Azure.WebJobs.Extensions.DurableTask(1.0.0-beta)
- Microsoft.NET.Sdk.Functions(1.0.6)

**Installed:**

- .NET Core SDK 2.0.3 
- Azure Functions Core Tools 2.0

I can run the sample locally when I target .NET framework. And when I upload the sample that targets .NET core to Azure, the functions are running just fine. I just can't run it locally. I get the following error for all OrchestrationClient functions: 

```Microsoft.Azure.WebJobs.Host: Error indexing method 'HttpStart.Run'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'starter' to type DurableOrchestrationClient. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. config.UseServiceBus(), config.UseTimers(), etc.).```

Code:
```
[FunctionName("HttpStart")]
public static async Task<HttpResponseMessage> Run(
    [HttpTrigger(AuthorizationLevel.Function, methods: "post", Route = "orchestrators/{functionName}")] HttpRequestMessage req,
    [OrchestrationClient] DurableOrchestrationClient starter,
    string functionName,
    TraceWriter log)
```

Am I configuring something wrong? Are there any samples that use Durable functions and targets .NET core? Thank you.

**Comment by cgillum** [comment]
The first thing I would suggest is to update your Microsoft.NET.Sdk.Functions package to 1.0.7, which is the latest and (I believe) has some fixes related to running on .NET Standard.  Try that and see if it helps. I've definitely gotten this working on my local box, but i think I was using an older version of .NET Core SDK - e.g. 2.0.0.

What version of VS2017 are you using?

**Comment by handeeadiguzel** [comment]
Thanks for suggesting to check VS version. I figured out what the issue is. 

I'm using Visual Studio Professional 2017 15.4.4 
And Visual Studio uses:
**Azure Functions Core Tools (1.0.7)
Function Runtime Version: 1.0.11375.0**

When I try to run the same solution using CLI from command line, with the following version I can actually target .NET Core (still using SDK & Runtime 2.0.3) and I get no errors: 
**Azure Functions Core Tools (2.0.1-beta.21)
Function Runtime Version: 2.0.11370.0**

Would it be possible to change the core tools version VS is using? Without that I'm not sure if debugging from VS would work.

**Comment by cgillum** [comment]
The latest version of VS (mentioned in the linked issue) will give you the support you need. There is a way to get it working in earlier versions of VS as well, but requires a bunch of manual setup, so I advise the former option. :)
