### ISSUE TITLE
Durable entity function keeps firing

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-functions-durable-extension#954]
### Description
During local development I am experiencing an issue where an entity function is repeatedly firing after being invoked. Initially I thought it might have been something in my code but I've managed to reproduce the issue with this code:

```csharp
namespace MyNamespace
{
    public static class MyClass
    {
        [FunctionName("MyClass")]
        public static void Run([EntityTrigger] IDurableEntityContext ctx)
        {
            var state = ctx.GetState<int>(() => 0);
            state++;
            ctx.SetState(state);
        }
    }
}
```

Which is invoked via the following:

```csharp
var entityId = new EntityId("MyClass", uniqueid);
await entityClient.SignalEntityAsync(entityId, "Evaluate");
```

The function gets called no problems, and then it gets called again, and again and again. In my scenario the HTTP triggered function gets a quick burst of messages which it routes to the same entity instance, then another burst, then a bit of a break and another burst with the traffic to that entity eventually going back to zero within a minute or so.

What I am seeing though is that once I trigger the function against the entity once it keeps of running it again and again. I can't see any exceptions in the console output to make me think it is retrying. And it doesn't appear to stop.

I've proven to myself that it can't be any external traffic by shutting off the source of HttpTriggers so it can't reach my local dev environment (so they aren't new incoming events).

### Expected behavior
I would expect that a call against a durable entity would be called once, and exactly once.

### Actual behavior
Continued calls once triggered.

### Known workarounds
I can stop the replay by resetting the dev storage and deleting all the tables, queues and blobs.

### App Details

- **Durable Functions extension version (e.g. v1.8.3)**: 2.0.0-beta
- **Azure Functions runtime version (1.0 or 2.0)**: 2.0.12673.0
- **Programming language used**: csharp

**Comment by cgillum** [comment]
FYI @sebastianburckhardt I created a repro similar to this one and I'm running into a serialization problem:

The problem appears in both beta2 and beta3, though the error message details are slightly different:
```
Microsoft.Azure.WebJobs.EntitySchedulerException
  HResult=0x80131500
  Message=Failed to deserialize entity state: Unexpected initial token 'Integer' when populating object. Expected JSON object or array. Path '', line 1, position 1.
  Source=Microsoft.Azure.WebJobs.Extensions.DurableTask
  StackTrace:
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableEntityContext.GetPopulatedState[TState](TState initialValue, Boolean usedTypeInitializer) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableEntityContext.cs:line 222
   at Microsoft.Azure.WebJobs.Extensions.DurableTask.DurableEntityContext.Microsoft.Azure.WebJobs.IDurableEntityContext.GetState[TState](Func`1 initializer) in C:\GitHub\azure-functions-durable-extension\src\WebJobs.Extensions.DurableTask\ContextImplementations\DurableEntityContext.cs:line 190
   at VSSample.MyClass.RunOperation(IDurableEntityContext ctx) in C:\GitHub\azure-functions-durable-extension\samples\v2\precompiled\Repro.cs:line 14
   at Microsoft.Azure.WebJobs.Host.Executors.VoidMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidMethodInvoker.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.<InvokeAsync>d__10.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 52

Inner Exception 1:
JsonSerializationException: Unexpected initial token 'Integer' when populating object. Expected JSON object or array. Path '', line 1, position 1.
```

I don't know if it's the exact cause of @mitchdenny's issue, but it might be related.

Specifically, the problem seems to be our use of `JsonConvert.PopulateObject(...)`. I think this API fails if the state is a primitive value and not an object.

@mitchdenny does the behavior change if you make your state into a custom class? For example, instead of doing `ctx.SetState<int>(...)` try `ctx.SetState<MyState>(...)` (where `MyState` has an int field that you increment).

```csharp
public static class MyClass
{
    class MyState { public int Value { get; set; } }

    [FunctionName("MyClass")]
    public static void RunOperation([EntityTrigger] IDurableEntityContext ctx)
    {
        var state = ctx.GetState<MyState>(() => new MyState());
        state.Value++;
        ctx.SetState(state);
    }

    [FunctionName("HttpStartRepro")]
    public static async Task Run(
        [HttpTrigger(AuthorizationLevel.Function, methods: "post")] HttpRequestMessage req,
        [DurableClient] IDurableEntityClient entityClient)
    {
        string uniqueId = "unique3";
        var entityId = new EntityId("MyClass", uniqueId);
        await entityClient.SignalEntityAsync(entityId, "Evaluate");
    }
}
```

**Comment by cgillum** [comment]
The fix for the problem we encountered with your scenario should go out with the beta3 release. Do let us know if you continue to run into this problem in that release. I tried the updated bits myself and everything was working correctly.

**Comment by MaxWilsonMS** [comment]
I believe I'm hitting this issue, but the weird thing is that it only repros when running in Azure. From my local dev machine everything works okay, but in Azure the same messages keeps getting processed over and over, and new messages are ignored.

My code:

```C#
    [JsonObject(MemberSerialization.OptIn)]
    public class StoreEntity
    {
        private XServerService xServer;
        private ILogger log;

        public StoreEntity(XServerService xServer, ILogger log)
        {
            this.xServer = xServer;
            this.log = log;
        }

        [JsonProperty("value")]
        public State CurrentState { get; set; } = new State();

        public async Task ProcessClose(Transaction closingTransaction)
        {
            await xServer.CloseShift(closingTransaction, log);
            await xServer.PostTransaction(closingTransaction, log);
            CurrentState.IsShiftOpen = false;
        }

        public async Task ProcessSale(Transaction salesTransaction)
        {
            // for now we just assume that there is a shift open and we can post to it as soon as transactions flow in
            log.Log($"Processing transaction {salesTransaction.Id} for store {salesTransaction.GetStoreNumber()}");
            if(!(CurrentState.IsShiftOpen == true))
            {
                await xServer.OpenShift(salesTransaction, log);
                CurrentState.IsShiftOpen = true;
            }
            await xServer.PostTransaction(salesTransaction, log);
        }

        [FunctionName(nameof(StoreEntity))]
        public static async Task Run([EntityTrigger] IDurableEntityContext ctx, ILogger log)
        {
            try
            {
                log.Log(LogLevel.Information, $"Starting to process {ctx.GetInput<Transaction>().Id}");
                await ctx.DispatchAsync<StoreEntity>(log);
            }
            catch(Exception e)
            {
                log.Log(LogLevel.Error, $"Failed to process {ctx.GetInput<Transaction>().Id} due to exception: {e.ToString()}");
            }
        }

        public class State
        {
            public bool? IsShiftOpen { get; set; }
        }
    }
```

I can see from AppInsight logs that my ProcessSale() is completing without exceptions, and yet I can also see from AppInsight logs that it keeps reprocessing the same signals over and over again. (I can also see from the logs that I'm not generating new signals for the same transaction.) Newer signals for newer transactions are ignored.

Updating to Microsoft.Azure.WebJobs.Extensions.DurableTask v2.2.0 from 2.1.1 and redeploying to Azure did not help, but switching to a new TaskHub temporarily mitigated the blockage and let me resume processing new transactions.

I tried hooking up my local dev box to the same Azure Storage Account + TaskHubName that had the original issue, but it processed the transactions without errors or infinite loops, as expected.

How can I tell if I'm hitting the same issue reported in #954?
