### ISSUE TITLE
Cumbersome to RaiseExternalEvent for Sub-orchestrations.

### ISSUE THREAD

**Issue by Kimmen** [Azure/azure-functions-durable-extension#97]
**Scenario**
We have function logic that notifies users about an event and awaits responses from those users. The logic notifies the users twice: first via a "standard" notification and if they don't respond within a certain time we notify them via SMS.

We solve this by doing two orchestration: first one determines which users are to be notified and waits for responses. Second orchestration is the "await for response" orchestration, which first sends a notification, waits for a user response or a timeout (similar to the [Hurman Interaction](https://docs.microsoft.com/en-us/azure/azure-functions/durable-functions-phone-verification) section in the documentation), using ExternalEvents (Wait and Raise).

The idea was to be able to set a predictable instanceId for the sub-orchestration so it is easy to RaiseExternalEvent once the user do respond. But it seems like you are not able to set an instance id for a sub-orchestration. At first I thought that the sub-orchtestration run in the same context as the parent (somehow) and used the same instance id, but that's not the case. 

I guess you got your reasons for not be able to set instance ids for sub-orchestration, but it would be nice in our case! Now we are persisting the instance id in a store and retrieving it when we get a response from the user.

**Comment by cgillum** [comment]
Actually, there isn't a good reason for this. We simply forgot to include this feature! Another user raised a similar issue here: https://github.com/Azure/azure-functions-durable-extension/issues/91

This is something we plan on adding. Thank you for sharing the details of your scenario. It's a good one that I had not previously thought about.

**Comment by Kimmen** [comment]
Greate! I inspected the code and saw that it was at least possible to provide an instance id to a sub-orchestration. For now we have a working workaround, but we are able to simplify the code once this is in place.

**Comment by cgillum** [comment]
I've added the new APIs which will allow you to specify an instance ID when you start a new sub-orchestration. You can find them in the latest version of the NuGet package. There's also a new automated test which does exactly your scenario, so I feel pretty good about it. :)

**Comment by Kimmen** [comment]
That's great! Now we can remove redundant code, thanks.
