### ISSUE TITLE
Running a Durable Function in a multi-region set-up.

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-functions-durable-extension#970]
@cgillum This is going to be difficult to explain, ill do my best.

In order to improve our availability and throughput to our customers, we are duplicating our entire system into another region, and then using Traffic Manager (DNS) to route requests into either region. Assume that both regions will be receiving equal amounts of traffic in an active-active configuration.

Once a request arrives into a region, it starts a new orchestration. We are accepting that the lifetime of this instance of an orchestration is locked to this region at this point.

This has been working fine for us so far.

Now we must change the orchestration to wait for an external event using the `WaitForExternalEvent` pattern. The request that contains the expected event will arrive from a 3rd party through our main public ingestion API. Then using traffic manager, the request will be directed to a region at random (maintaining our active-active configuration).

The problem here is that once the event arrives into a region, it is statistically likely that it will have arrived at the the _wrong_ region (where the desired orchestration instance does not exist) and the event will get dropped.

---

What I would like is an **omnipresent orchestration.** where an event can be picked up and processed via any Function App that is running the same version of code. 

I know in principle this is incredibly difficult as the whole point of Durable Functions is that they are stateful, and what I'm asking for is something that is more akin to stateless.

---

We are going to mitigate this short term by building a mechanism to intercept the request and essentially _broadcast_ it to all listening instances of the Durable Function App across all the regions. 

Eventually the right region will pick up the event and it will be raised to the desired orchestration, the downside is that N regions will also pick up the message and process it (and subsequently drop it) which is wasting precious cycles in our high-throughput use-case. At the moment for every event that gets processed successfully, this will mean another event gets dropped in a differing region. 

To add another dimension of complexity, we also run multiple isolated copies of the system in each region, and this is expected to grow as we scale and allocate customers into different systems based on their commercial arrangement with us. So it is very realistic to expect a future where we have 2 region, with 10 systems inside each region, so 19 events messages dropped per 1 successful event message. Highly wasteful and generally won't scale.

---

It would be incredible if there was some back plane where all Function Apps (running the same code) could participate in some kind of decentralised sharing of state, but I appreciate this would be a monumental effort.

Other thoughts come to mind using cosmos (in a multi-master configuration which cosmos supports) as the backing store for durable functions, to allow something like :

1. **Ideal** - any instance of the function app could party on the same distributed state and process any event. **or**
2. **less ideal** _but still much better better than nothing_ - There is a centralised source-of-truth of orchestration metadata which contains enough info to re-route an event to the correct instance of the Function App. 

---

I guess what I'm looking for is some direction to allow me to make informed decisions and start building my own road-map for how I'm going to scale Durable Functions within my own system. Many thanks.

**Comment by olitomlinson** [comment]
I appreciate you are sprinting to close off v2, but do you have any thoughts on this @cgillum ?

**Comment by olitomlinson** [comment]
@cgillum cheeky bump

**Comment by cgillum** [comment]
Tagging @anthonychu on this.

**Comment by ConnorMcMahon** [comment]
@anthonychu, can you take a bit of time to look at this and see if this is something we would need to build something more, or if there is some workable solution we can use with our existing functionality that we could provide guidance on.

**Comment by cgillum** [comment]
@olitomlinson Thanks for taking the time to spell out your scenario.

To summarize, it sounds like you effectively have a routing problem - i.e. you need to know which task hub to route external events to.

You mentioned that you're broadcasting events to all regions, which can be wasteful since only one out of the N endpoints can actually handle the message. Had you considered another approach which is to create a map of _InstanceID_ --> _Endpoint_, and storing that map in Cosmos DB? Then, your public ingestion API could consults the routing table and deliver the event to the correct function app. Would something like that work as a more scalable alternative?

**Comment by anthonychu** [comment]
For this specific scenario, my recommendation is along the lines of what @cgillum suggested. It can be a centralized store to look up InstanceID -> Endpoint. Or you may be able to bypass the centralized store by embedding something in the callback URL that is invoked by the 3rd party system so you can route it to the right function app.

**Comment by olitomlinson** [comment]
@cgillum @anthonychu thank you for the response! It's really appreciated!

Chris, your summary of this being a routing issue is absolutely accurate.

We considered a centralised routing service which intercepts all requests ( which exactly matches your description of `instanceId -> Endpoint`). We ruled this out after digging into the potential design of this service, as we realised this service would also have to be built in an active-active configuration (likely using cosmos multi-master writes to distribute the routing information). Although entirely possible, we felt this was a long-term solution to the problem and not something we could deliver quickly.

We've actually ended up with a bit of a hybrid approach, similar to @anthonychu suggestion of embedding something in the callback URL.

Our solution right now is to encode just enough routing info of the originating TaskHub into the orchestration `InstanceId`. When an event is received into one of the random Function App, the Function App decodes the `instanceId`, and will then raise the event into the TaskHub if it has arrived on the correct instance, or it will relay it over HTTP to the correct TaskHub that exists elsewhere. 

It's not entirely glamorous as it relies on every Function App to know the Endpoints of all the other Function Apps ( hello circular references in our Terraform configuration) and we end up chaining HTTP across multiple Functions (hello double billing and latency) but it works and doesn't require building & owning a separate centralised routing service. 

Ideally, It would be nice not to have to hand roll this. 

It would be nice if I could give all my Function Apps an optional connection string to a multi-master cosmos collection and the Durable extension writes routing information to it.

So when I do `await client.RaiseEventAsync()` my event _may_ get processed by the local TaskHub, or using the routing information provided by cosmos, it will be transparently routed to the correct TaskHub. 

As a developer, this would all happen without me doing anything, but just providing a cosmos connection string.

---

With any of the solutions mentioned, another problem still exists that the TaskHub state is locked to a Storage Account. When Azure Storage has an outage, we are stuck. Manual failover of storage account is a heavy-weight option, but this is not something we feel confident performing, particularly due to data loss due to async replication, and then the fail-back scenario to consider as well. Yukk.

If we could once again use Cosmos as the state provider for DF, then we could in theory support an active-passive approach to migrating one or more active orchestrations from one region to another in the event of a regional failure.

**Comment by ConnorMcMahon** [comment]
@olitomlinson 

It sounds like there are a few potential ways we could make multi-tenant support easier.

1. Some first-party support for TaskHub routing into `IDurableClient` (likely using CosmosDB due to the multi-region support)
2. Some documentation or some other official guidance around how to build a robust production ready routing service for multi-tenant apps.

Any other items and/or ideas for how we could make sure we have good support for multi-tenancy?

**Comment by olitomlinson** [comment]
@ConnorMcMahon you mention multi-*tenant* a lot in your previous comment, do you mean multi-*region* ?

**Comment by ConnorMcMahon** [comment]
@olitomlinson I used multi-tenant, but the correct wording likely should have been multi-taskhub scenarios. I think in general the routing problem applies to any time when you have multiple task hubs (i.e. multi-tenant OR multi-region scenarios). Multi-region support is really just a more complex sub-case of multi-taskhub support.

**Comment by olitomlinson** [comment]
@ConnorMcMahon Got you! 

I don't have much to add at this point as this particular use-case has only just gone into production so we don't have much to retrospect on yet...

Our approach is to encode enough routing information in the Orchestration Id. We then make requests to external systems with that Id contained as a reference data. When the external system calls back, it passes the origin reference data, which we then decode in the Function App and use to route it to a different function app or process it _in-situ_.

Here is a simplified example of what we are doing.

```
public class RoutingInformation
{
    public string Id { get; set; }
    public string Environment { get; set; }
    public string Region { get; set; }
    public string Route { get; set; }
    public string Stack { get; set; }

    public static string Encode(Guid id, string env, string region, string route, string stack )
    {
        return $"{id}|{env}|{region}|{route}|{stack}";
    }

    public static RoutingInformation Decode(string encodedId)
    {
        var components = encodedId.Split("|");

        return new EdgeInformation
        {
            Id = components[0],
            Environment = components[1],
            Region = components[2],
            Route = components[3],
            Stack = components[4]
        };
    }

    public string BuildDestinationFunctionAppEndpoint(string authCode)
    {
        return 
            $"https://{Environment}-{Region}-XXXXXXXXXX-{Route}-XXXXXXXXX-{Stack}.azurewebsites.net/api/event-handler"
                .SetQueryParam("code", authCode);
    }
}
```

```
[FunctionName("event-handler")]
public async Task<HttpResponseMessage> RunAsync(
    [HttpTrigger(AuthorizationLevel.Anonymous, "post")] HttpRequest req,
    [OrchestrationClient] DurableOrchestrationClient client,
    ILogger logger)
{
    {
        // redacted bespoke auth code handling as we have to use AuthorizationLevel.Anonymous

        var event = JsonConvert.DeserializeObject<EventData>(await req.ReadAsStringAsync(););

        var routingInformation = RoutingInformation.Decode(event.Id);

        if (!HasEventArrivedAtCorrectDestination(routingInformation))
            return await routingInformation.BuildDestinationFunctionAppEndpoint(authCode).PostJsonAsync(event);

        var instanceId = routingInformation.Id;
        await client.RaiseEventAsync(instanceId, event.Type.ToString(), event.Data);

        return new HttpResponseMessage(HttpStatusCode.OK);
    }

    private bool HasEventArrivedAtCorrectDestination(Configuration configuration, RoutingInformation routingInformation)
    {
        if (Configuration.Environment != routingInformation.Environment ||
            Configuration.Region != routingInformation.Region ||
            Configuration.Route != routingInformation.Route ||
            Configuration.Stack != routingInformation.Stack)
        {
            return false;
        }  
        return true;
    }
}
```

It works, but my biggest concerns is that all this routing is happening at the user-code level. Ideally I would be able to just call 'client.RaiseEventAsync(...) and all this routing would happen transparently to me.

Also we have double billing and chaining of HTTP calls between Function Apps which makes me nervous for operating at-scale.

I don't know if this concept of encoding TaskHub routing information into the instance Id is something you could explore further? I'll have a think and report back what we find of routing in the above way.

**Comment by ConnorMcMahon** [comment]
@olitomlinson, to make sure we are on the same page with this, it sounds like app lease covers _most_ of this, but you would like activities to still be processed, right?

**Comment by olitomlinson** [comment]
@ConnorMcMahon kind of...

In this particular set up I run two identical function apps, each with their own TaskHub. I wanted to route an external event to either of the FunctionApps and then have the TaskHub relay it to the other TaskHub if the orchestration instance is not for TaskHub that it was originally routed into.

With the new app lease stuff, I can route an event to either FunctionApp, but as the TaskHub is _shared_ this problem that I'm describing in the original post is not the same.

I think the best thing for me to do is to rearchitect my set-up to make use of a single TaskHub shared across both Function Apps as made possible by app lease.

---

Yes, I would still like activities to be executed on the primary or secondary, but Chris had some strong opinions in the other geo-redundancy on why this can't happen. I'm less concerned about executing activities on the secondary, its a _nice to have but not essential_ feature.

I'm happy to close this now.
