### ISSUE TITLE
Generated task hub name may be invalid

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-durable-extension#979]
Just created a durable function and gave it a name that I suppose tried to generate an invalid task hub name?  This was the error I got.  Would be good if the logic helped create a task hub that was valid. Realize there may be naming clashes if you do things like remove slashes, but if we can't support those characters as the hub I think that may be better than crashing?

![durableerror](https://user-images.githubusercontent.com/7132626/67261883-7abc3e80-f457-11e9-8cf6-b7aed4b78af5.png)

**Comment by cgillum** [comment]
Same as this issue? https://github.com/Azure/azure-functions-durable-extension/issues/976

**Comment by jeffhollan** [comment]
Yep! Thanks for catching.  I even tried to find a dupe first :)
