### ISSUE TITLE
Durable function performance issues

### ISSUE THREAD

**Issue by tsinghal18** [Azure/azure-functions-durable-extension#980]
Below if my code of orchestrator, I am using combination of chaining and fanin/fanout

`const df = require("durable-functions");
const geocodeActivity = "getActualData";
const getDataActivity = "getDataFromDB";
const ld = require('lodash')

module.exports = df.orchestrator(function* (context) {
    const outputs = [];
    const parallelTasks = [];
    try {
        let payload = context.bindingData.input;
        payload.dataType = "truth";
        let truthData = yield context.df.callActivity(getDataActivity, payload);
      
        for (const data of truthData) {
            const truthDataObj = payload;
            truthDataObj.data = data;
            //console.log("ORCHESTRATOR: " + JSON.stringify(truthDataObj));
            parallelTasks.push(context.df.callActivity(geocodeActivity, ld.cloneDeep(truthDataObj)));
        }
        let actualData = yield context.df.Task.all(parallelTasks);
        let uploadDataInfo = payload;
        uploadDataInfo['actual_data'] = actualData;
        let uploadedCsv = yield context.df.callActivity("uploadActualData", uploadDataInfo);
        if (uploadedCsv == false || uploadedCsv == null || uploadedCsv === undefined) {
            outputs.push("failed");
        } else {
            outputs.push(uploadedCsv);
        }
        
    } catch (err) {
        context.log(JSON.stringify(err));
        outputs.push('-1');
    }
    return outputs;
`

I am having below observations
1) Many times the orchestrators keeps stuck in running

2) The 1st Activity that is called for getDataActivity, returns record from DB, that can go upto million in rows and each row containing atleats 20 columns

3) Then I am looping through each record and performing some actions

But I have observed many times that it gets stuck in running or sometimes the server on which orchestrator is running gets restarted

Is it something to do with the huge amount of data that is getting returned from "GetDataActivity"?
If yes what are your advise here, how can I try to solve this

**Comment by tsinghal18** [comment]
I finally was able to see below error
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

How can i fix this?

**Comment by ConnorMcMahon** [comment]
@tsinghal18,

One option would be to do the following:

1. Make a first query that exclusively gives you an estimate (or accurate count) of the number of rows that `GetDataActivity()` will return.
2. If the row count is low enough, keep your current code.
3. If the row count is too high, you can attempt to paginate your GetDataActivity() query, with each sub-query being handled by a sub-orchestration (these could probably be run in parallel). You can wait until all of the sub-orchestrations are finished, and accumulate the results from each of those in your parent orchestration before sending it, or if even that amount of data is too large, you can have each sub-orchestration be responsible for it's own uploading.

Hope that helps!
