### ISSUE TITLE
Provide an ability to easily disable all new triggers in a TaskHub via a Feature Flag

### ISSUE THREAD

**Issue by jaxidian** [Azure/azure-functions-durable-extension#981]
**Is your feature request related to a problem? Please describe.**
When I'm deploying updates to long-running durable functions, I want to have the ability to swiftly transition from the old version to the new version. There is [some guidance here](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-versioning) and, for us, the "Side-by-side deployments" method seems like it will work best and we plan to implement it by versioning our TaskHub names.

**Describe the solution you'd like**
In our case, we plan to version our TaskHub names:
- MyHubv1
- MyHubv2
- MyHubv3

However, we'd like to be able to quickly/easily set a single feature flag to disable all *new* triggered instances from being created in the older versions. By this, I mean things such as TimerTrigger would stop executing although an OrchestrationTrigger might still need to execute to complete a chain. I don't expect the system to necessarily understand which version is newer (although that would be nice). Rather, I want the ability to "disable new instances" on a Task Hub basis so I could disable them on v2 before I go to deploy v3 (or better yet, as a part of v3 deployment scripts). This way, long-running v2 durable functions can complete while only v3 will spawn new executions.

**Describe alternatives you've considered**
Clunky one-off managed feature flags can somewhat accomplish this. But this is somewhat clunky, error prone, and distracts me from my ultimate goal: Not writing plumbing code.

**Additional context**
A Twitter chat on this happened [here](https://twitter.com/cgillum/status/1186796230636032000). Thanks Chris Gillum for pointing me here. :-)

**Comment by ConnorMcMahon** [comment]
I think this definitely adds some value. I just have a few questions about your ideal approach to this scenario that we could take into account in any designs.

1. Do you want a solution that only prevents that application from starting new orchestrations on its TaskHub (i.e. via a durable client or via the webhook), or do you need a solution that would effectively turn it of for durable clients on other applications that are pointed at your taskhub?
2. What would you expect if a task hub is turned off and someone attempts to start a new orchestration? Errors, or some way to point to the new taskhub?
