### ISSUE TITLE
Orchestrator can't deserialize activity exceptions

### ISSUE THREAD

**Issue by spplante** [Azure/azure-functions-durable-extension#983]
### Description
From the orchestrator, I am unable to catch a simple WebException thrown by an activity.

### Expected behavior
Orchestrators should be able to implement basic try/catch logic in order to catch exceptions thrown by activities

### Actual behavior
Initially my activity was throwing a **WebException** and my orchestrator was getting a base **Exception** with message the following message :

> The activity function '*****' failed: "Failed to deserialize exception from TaskActivity...

When returning a base **Exception**, it works fine. So I decided to create my own custom **MyCustomException**, which is exactly the same as a base **Exception** except I added one single int property, and I get the same error :

> The activity function '*****' failed: "Failed to deserialize exception from TaskActivity: {"$type":"MyNamespace.MyCustomException...

I even tried to implement the methods below in order to tell the framework how to serialize/deserialize my custom exception, but no success, the code doesn't even reach the deserialization constructor it is totally ignored:

- public MyCustomException(SerializationInfo info, StreamingContext context)
- override public void GetObjectData(SerializationInfo info, StreamingContext context)

So the only exception that worked for me was a base **Exception**, I must be doing something wrong, I cannot believe that basic error handling isn't supported in durable activities?!? 

### Relevant source code snippets

Custom Exception :
```csharp
using System;
using System.Net;
using System.Runtime.Serialization;

namespace MyNamespace
{
    [Serializable]
    public class MyCustomException: Exception
    {
        public int RetryAfter { get; set; }

        public MyCustomException(): base()
        {
            this.RetryAfter = 120;
        }

        public MyCustomException(int retryAfter): base()
        {
            this.RetryAfter = retryAfter;
        }
    }
}

```

### App Details

- Durable Functions extension version: v1.8.3
- Azure Functions runtime version : 1.0
- Programming language used: C#

**Comment by ConnorMcMahon** [comment]
This has a solution as of the 2.1 release. I have opened an issue to document this better (#1208).
