### ISSUE TITLE
Mixing durable and non-durable functions in webjobs

### ISSUE THREAD

**Issue by kabcampbell** [Azure/azure-functions-durable-extension#985]
I have a webjob that has a number of functions in Functions.cs. I would like to make some of those into durable tasks and leave others as is. Are there any issues with doing this?

For example, I noticed that the durable task hub worker seems to take over aspects of the webjob host, shutting it down after periods of inactivity and then "waking up" when another durable task is triggered. Will this kind of behavior impact the other, non-durable, triggered functions on that host?

**Comment by cgillum** [comment]
There shouldn't be any problem with mixing durable and non-durable functions in webjobs. A Durable function isn't really any different than any other type of trigger except that it has more sophisticated execution capabilities.

The durable task hub worker can't actually take down the webjob host. When we talk about unloading functions from memory, what we're referring to is the ability to let functions *naturally* unload from memory like they would anyways for non-durable triggers. The functions can be unloaded yet still (virtually) continue where they left off after they "wake up", which is the point of emphasis. There will not be any impact to any other triggered functions on that host.

I hope this information is helpful. Let us know if you have any other questions about this.
