### ISSUE TITLE
Allow settable retry-after header to work with Azure 202 patterns

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-functions-durable-extension#99]
Today calling an http function that returns the durable orchestrator status has a 202 header and a location.  When calling from Azure Logic Apps, because there is no `retry-after` header it immediately calls the location header (which returns a 404 as I assume it's still initializing).  Would prefer to return a  `retry-after` header as well to let the polling client know what an appropriate polling interval would be [per Azure 202 patterns](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-async-operations)

Fixes could be either:
1. Allow returning of a retry-after header so the Logic App won't poll until after that duration
2. Make the status endpoint callable immediately as not to receive a 404

**Comment by cgillum** [comment]
Ideally we would implement your second suggestion because getting a 404 response isn't helpful to anyone. :P

In the meantime, try adding the `retry-after` header manually in the HTTP trigger function that is starting the orchestration, like the following:

```csharp
[FunctionName("HttpTrigger_HttpStart")]
public static async Task<HttpResponseMessage> HttpStart(
    [HttpTrigger(AuthorizationLevel.Function, "post")]HttpRequestMessage req,
    [OrchestrationClient]DurableOrchestrationClient starter,
    TraceWriter log)
{
    // Function input comes from the request content.
    ProcessRequest requestData = await req.Content.ReadAsAsync<ProcessRequest>();
    string instanceId = await starter.StartNewAsync("HttpTrigger_Orchestrator", requestData);
 
    log.Info($"Started orchestration with ID = '{instanceId}'.");
 
    HttpResponseMessage response = starter.CreateCheckStatusResponse(req, instanceId);
    response.Headers.RetryAfter = new RetryConditionHeaderValue(TimeSpan.FromSeconds(10));
    return response;
}
```

The resulting response headers will include the `retry-after` header, looking something like this (running locally on Functions v1):

```http
HTTP/1.1 202 Accepted
Content-Type: application/json; charset=utf-8
Date: Mon, 27 Nov 2017 17:25:55 GMT
Location: http://localhost:7071/admin/extensions/DurableTaskExtension/instances/eb49a7c1241840f2a9899fd2a0e84615?taskHub=SampleHubVS&connection=Storage&code=SE2NVBADa7RWYhZnunqMgPURuoJFJIQnMUzMvIQ4QkeRjWe5rvRFzg==
Retry-After: 10
Server: Microsoft-HTTPAPI/2.0
Transfer-Encoding: chunked
```

**Comment by jeffhollan** [comment]
Confirming returning initial retry-after header does work
